### ISSUE TITLE
Missing info in new documentation for Submit VAT retrun

### ISSUE THREAD

**Issue by ubiuser** [hmrc/vat-api#1001]
Important information that was available in the old docs are missing from https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0/oas/page#tag/organisations/operation/SubmitVATreturnforperiod.

This includes the different types of errors returned with their description, and the error samples completely miss the `message` field in the response.

**Comment by DDCTLS-DEV-TEAM** [comment]
Hi @ubiuser,

I have had a look through and all the details around the errors are there still. The descriptions and the error codes can be cycled through with the dropdown of the errors on the right hand side of the screen and the description's are all there on above the example. None of these descriptions or errors have changed in moving the documentation from the old style to the new so all the information should still be there. 

The `message` field has never been shown on the documentation and the priority was to make sure all the information was included in the switch over. we can however look at adding the messages field in the near future now thanks to the new format this will be possible and a story will be raised to get this added. 

Hope this answered your issue and any more problems feel free to raise a new issue.

**Comment by ubiuser** [comment]
I missed the drop down option, and the descriptions are indeed there when I scroll through them. Thanks!
