### ISSUE TITLE
{ "code" : "MATCHING_RESOURCE_NOT_FOUND", "message" : "A resource with the name in the request can not be found in the API" }

### ISSUE THREAD

**Issue by mathiasbanda** [hmrc/vat-api#102]
PUT https://test-api.service.hmrc.gov.uk/vat/666952560/returns

My data looks like this:
{
  "periodKey": "#002",
  "vatDueSales": 100.00,
  "vatDueAcquisitions": 100.00,
  "totalVatDue": 200,
  "vatReclaimedCurrPeriod": 100.00,
  "netVatDue": 100,
  "totalValueSalesExVAT": 500,
  "totalValuePurchasesExVAT": 500,
  "totalValueGoodsSuppliedExVAT": 500,
  "totalAcquisitionsExVAT": 500,
  "finalised": false
}

**Comment by mathiasbanda** [comment]
the parser taken out 00 in front of the hash #

**Comment by MarkAKelly** [comment]
Hi @mathiasbanda 

The endpoint is a POST, so using a PUT method will result in your resource not found error.

Cheers, Mark

**Comment by mathiasbanda** [comment]
Cheers Mark, spot on
