### ISSUE TITLE
Non-Repudiation Store for VAT returns

### ISSUE THREAD

**Issue by swdatatracks** [hmrc/vat-api#103]
Hello,

How do I call the Non-Repudiation Store to get the "Receipt ID, Receipt signature, Receipt timestamp" headers, after a successful submission?

If it is a part of the Submission endpoint at "/vat/{vrn}/returns", we are not getting any of the above said headers in the response. Could you please help us on this regard?

**Comment by jacobbrownlow** [comment]
Hi 

It is not possible to call NRS directly. When submitting a VAT return a call is made to NRS in the background. The response from NRS will be returned to the vendor by appending to the DES response header.

I have just tried this in ET and we can see them in the header. 
![image](https://user-images.githubusercontent.com/35334115/38610162-eb224e28-3d77-11e8-9cca-8aaab0b10a83.png)
![image](https://user-images.githubusercontent.com/35334115/38610120-c9e17c02-3d77-11e8-9a35-5b65dead091d.png)

Please could you try again and if it is not working send us a screenshot, or the request/responses.
Thanks, Jacob

**Comment by swdatatracks** [comment]
@jacobbrownlow, thank you, we are able to get the headers now.
