### ISSUE TITLE
Non-Repudiation result from submit VAT Return

### ISSUE THREAD

**Issue by sonicmule** [hmrc/vat-api#104]
I'm just looking at processing the result from submit VAT Return re Non-Repudiation.
Currently we have a result in the body of the response that looks like this -

{"processingDate":"2018-04-11T08:55:56.014Z",
"paymentIndicator":"BANK",
"formBundleNumber":"609972980752",
"chargeRefNumber":"XA2PQBnAsz42Vb13"}

Which is cool as I can store this in the database and create a JSON object to handle this.

But now we are getting important info through the header that needs to be stored as well -
Receipt-Id
Receipt-Signature
Receipt-Timestamp

Can you explain why these are not included as part of the response body?
In the interests of scalability would it not be better to pass this in as part of the response body?
Otherwise we will need to store these in individual database fields with the possibility of more header fields coming along in the future that need reference at a later date.

Hope this makes sense.

**Comment by mathiasbanda** [comment]
@sonicmule 
Very good question

**Comment by obeea** [comment]
If I store the formBundleNumber, do I also need to store the Receipt-Id from the header, as both seem unique, so if we (or our client) had to query something with HMRC, which reference is relevant?

**Comment by mathiasbanda** [comment]
Presumably Receipt-Id as I understand, Receipt-Id  as to be displayed I cannot imagine it's there for any other purpose. That said let's hear it from the experts

**Comment by jonathanleather** [comment]
@sonicmule 
Apologies for the very late reply to this. The headers were a design decision that the current team had no involvement in. We are unable to change this in the current API version but I will pass on your comments if/when we implement a new version of the API.

@obeea @mathiasbanda 
The backend teams have informed me that the `formBundleNumber` would be the best to use when querying with HMRC.

Thanks 
Jon

**Comment by mathiasbanda** [comment]
Thanks @Jon apparently the HMRC compliance team insist Receipt-ID has to be available /visible to the end user for querying purposes. So will have them both :)
