### ISSUE TITLE
PeriodKey value changes based on the date range in /vat/{vrn}/obligations

### ISSUE THREAD

**Issue by skarvm** [hmrc/vat-api#105]
The Retrieve Obligations endpoint(/vat/{vrn}/obligations) is returning the value #001 as periodKey for the first period in the given date range. For example, if we pass the date range as [2018-04-01, 2019-03-31] the periodKey for the April quarter is #001 and if the date range [2018-07-01, 2019-03-31] the periodKey #001 is assigned to the July quarter. Does this mean the retrieve obligations to be always called with the entire year as range to get the correct periodKey for each period or is it just the sandbox behaviour? isnt the periodKey unique to a particular vrn and obligation period?

We are looking to call the Retrieve Obligations once and store the periodKeys and the corresponding period dates in our system and use that while submitting the returns. This is because we have one system where the user uploads the submission values which gets sent to another system that calls the endpoint.

**Comment by AbsoluteAccounting1** [comment]
Have you received a response to this?

**Comment by scottylace** [comment]
@skarvm @AbsoluteAccounting1 

Apologies for a very late response on this one. The behaviour you are seeing above is sandbox behaviour only. The "periodKey" will uniquely identify an obligation period and will not be driven by the query parameter date range.

**Comment by AbsoluteAccounting1** [comment]
Could you please tell me how you determine what start and end date are associated to a period key please?

**Comment by AbsoluteAccounting1** [comment]
Could you please tell me how it is determined what the period keys are please?

Is there anyway for the user to obtain this information on the Business Tax hub?

**Comment by jacobbrownlow** [comment]
Hi @AbsoluteAccounting1 

The following issues relate to period keys, they may be worth a look
https://github.com/hmrc/vat-api/issues/63
https://github.com/hmrc/vat-api/issues/80
https://github.com/hmrc/vat-api/issues/109

Essentially the backend creates a corresponding period key when the obligation is created. We do not have any control over them. 

For testing in sandbox they need only be any 4 alphanumeric characters.

Regards, Jacob
