### ISSUE TITLE
•Modified VAT Returns (Submit 9 Box) to accept whole values ending in '.00' for boxes 7-10.

### ISSUE THREAD

**Issue by mathiasbanda** [hmrc/vat-api#107]
FYI:
No idea what it did before but I thought you should know the api now rejects boxes 6 and 7 if they have values not ending in '.00'

**Comment by jacobbrownlow** [comment]
HI @mathiasbanda,

Are you saying your having a problem entering values for boxes 6 and 7?

A change has recently been made where boxes 6-10 can be entered with values ending in .00, however it is still the case that these values should be whole numbers, and can still be entered as such.

**Comment by MarkAKelly** [comment]
Yes that is correct @mathiasbanda .  Boxes 6-10 have always only ever accepted integers, that is values in the valid range but with no decimal places.  
There was a need from some developers to be able to submit whole numbers in a currency format, so it is now possible to submit decimalised representations of integer values (suffixed with `.00`, i.e. 1000.00).

We still do not permit the submission of decimal values other than the above.

Mark

**Comment by mathiasbanda** [comment]
Thanks Mark, if those are the rules, why not say so in the error messages? That "amount should be a monetary value (to 2 decimal places)..." means 1000.00 and NOT 1000.01 will never be obvious to everyone.

**Comment by MarkAKelly** [comment]
@mathiasbanda I've raised this with our content designer who we are working with to improve documentation and error messages, so keep an eye out for any upcoming changes that should hopefully provide some more clarity around the technical validation in the API.

**Comment by mathiasbanda** [comment]
That's great
