### ISSUE TITLE
When are periodKeys Generated

### ISSUE THREAD

**Issue by Sean-Deverell** [hmrc/vat-api#109]
I’m currently reviewing the APIs available for VAT MTD.

Looking at the Submit VAT return for period API is appears each submission requires a periodKey.

To get the periodKey it looks like we should be able to make a call to the Retrieve VAT obligations API.

So this all makes sense, my question is when would the list of periods and associated periodKeys be generated on your systems to allow us to retrieve them?

**Comment by MarkAKelly** [comment]
Hi @Sean-Deverell,

For VAT, the backend systems create the obligation and the corresponding period key on the first day of the next tax period.  They are not done as a batch job in advance at the start of the tax year.

Hope this helps.

Mark

**Comment by skarvm** [comment]
Hi @MarkAKelly ,
Will the periodKey generated on the first day of a period change later? We are looking to 'cache' the periodKeys by calling the Retrieve Obligations on every month or so and then submit the VAT return with the 'cached' period keys (without making another obligation call prior to submission). Do you see any issue with this approach?

**Comment by MarkAKelly** [comment]
Hi @skarvm,

I can't really comment on what might be best practice for consumers of these API's, although you are correct - the period keys should not change once they have been created.
