### ISSUE TITLE
Has the endpoint url change to vat api taken place now?

### ISSUE THREAD

**Issue by mathiasbanda** [hmrc/vat-api#127]
Have the pending endpoint changes to the VAT api actually happened? because it's all been working until sometime this afternoon now getting server error 500 when in fact the client code here hasn't changed

**Comment by MarkAKelly** [comment]
As this is related to issue #135, I'm going to close this issue @mathiasbanda.

Again, feel free to reopen if you feel you need to.

Cheers, 
Mark
