### ISSUE TITLE
INTERNAL_SERVER_ERROR / Remote server error (500)

### ISSUE THREAD

**Issue by mathiasbanda** [hmrc/vat-api#131]
Both get obligations: 
https://test-api.service.hmrc.gov.uk/vat/666194206/obligations?from=2018-01-01&to=2018-07-30&status=A

And posting vat are failing with similar error Inter server error. It was working yesterday morning but then stop from about 11 and it hasn't worked since. Something is going on here. The only thing that happened here was I was in a meeting. What's going on please

**Comment by CoppensBart** [comment]
@mathiasbanda ,check this issue:
https://github.com/hmrc/vat-api/issues/130
On a side note, you are still using the "old" endpoints

**Comment by mathiasbanda** [comment]
Thanks @CoppensBart presumably the root's changed? What's the new one then, please

**Comment by mathiasbanda** [comment]
Thanks @CoppensBart I dug up the email it doesn't say when the changes will happen - maybe I missed the update

**Comment by MarkAKelly** [comment]
@mathiasbanda @CoppensBart there will be some guidance coming around shortly about setting up new test users that marry up to our new authentication process.

We are waiting for the service team that maintains the creation of test users to deploy the changes for use in the Sandbox environment.

In the meantime please go through the normal channel for access issues at SDSTeam@hmrc.gsi.gov.uk and your question will be dealt with.

Cheers,

Mark

**Comment by mathiasbanda** [comment]
Who knows what the latest is on this please? @audupa, says it's working I am now getting this: the remote server returned an error: (403) Forbidden. What is the state of this and yes I made the VAT api subscription it is turned on

**Comment by nnotsofun** [comment]
yep @mathiasbanda seeing the same issue here for hitting the obligations end point.
 
steps i took in sequential order:
* have tried turning our api subscription off and back on
* then created a new organisation (through the GUI - not create users end point, does this make a difference?)
* reauthorised with the new organisation 
* used that new organisation vrn/token to hit the obligations end point - and got the 403 response.

![image](https://user-images.githubusercontent.com/17335370/39506931-01a1aa1a-4e1f-11e8-9523-8f828be08b6e.png)

**Comment by mathiasbanda** [comment]
Thanks @nnotsofun

**Comment by narendravijayarao** [comment]
Hi...

Yes the recommended approach to create a user is using API instead of GUI.

Thanks,
Narendra

**Comment by nnotsofun** [comment]
Thanks @narendravijayarao that did the trick - @mathiasbanda fyi

**Comment by mathiasbanda** [comment]
@narendravijayarao, @nnotsofun 

Thanks guys but that doesn't change anything for me. Just gone through creating a new business, use the vrn to retrieve obligations still same error: The remote server returned an error: (403) Forbidden. In any case I have never used the UI to create a user. Have I upset someone in my feedback? I take it all back.

**Comment by jacobbrownlow** [comment]
Hi @mathiasbanda 

Can I clarify that you are using the _/create-test-user/organisations_ endpoint
with the following service
```json
{
  "serviceNames": [
    "mtd-vat"
  ]
}
```
and then hitting
https://test-api.service.hmrc.gov.uk/organisations/vat/**vrn**/obligations...  ?

**Comment by mathiasbanda** [comment]
@jacobbrownlow 
That appears to have been it, because now I added that service it is working. No idea how long it's been in there thank you

**Comment by nnotsofun** [comment]
@jacobbrownlow do you know if this error code CLIENT_OR_AGENT_NOT_AUTHORISED replaces UNAUTHORIZED as listed [here](https://developer.service.hmrc.gov.uk/api-documentation/docs/reference-guide#errors) for MTD VAT?

**Comment by jacobbrownlow** [comment]
Hi @nnotsofun 
403 CLIENT_OR_AGENT_NOT_AUTHORISED is what will be returned for any authorisation errors.
Regards, Jacob

**Comment by immanuelarun** [comment]
Hi Folks,

The original issue being discussed here is about INTERNAL_SERVER_ERROR and I hit this error today.

I noticed when I requested the resource without a status query parameter which is supposed to be optional I got this error.

Upon adding the status query parameter I got a successful response.

https://test-api.service.hmrc.gov.uk/organisations/vat/6663xxxxx/obligations?from=2018-01-01&to=2018-07-31&status=O

**Comment by jacobbrownlow** [comment]
Hi @immanuelarun 

I am not able to replicate this issue using the same dates and no status (in sandbox)

![image](https://user-images.githubusercontent.com/35334115/42880393-142c2cce-8a8c-11e8-9c4c-1eec73cffb30.png)

If it continues to happen can you supply more details

Regards, Jacob

**Comment by immanuelarun** [comment]
Hi @jacobbrownlow 

I've been testing with different dates and all of the tests are failing if 2018-01-01 was not given as the from date and to date = 2018-07-31 for the query. 

I don't think providing or not providing status parameter is important. I may've been wrong on that one.

Can you try these? All of the queries below gives me internal server error:
https://test-api.service.hmrc.gov.uk/organisations/vat/6663xxxxx/obligations?from=2018-01-01&to=2018-03-31&status=O

https://test-api.service.hmrc.gov.uk/organisations/vat/6663xxxxx/obligations?from=2018-04-01&to=2018-06-30&status=O

https://test-api.service.hmrc.gov.uk/organisations/vat/6663xxxxx/obligations?from=2018-07-01&to=2018-09-30&status=O

Has it got anything to do with my VRN number?

Regards,
Immanuel.

**Comment by immanuelarun** [comment]
Thanks @jacobbrownlow

**Comment by mathiasbanda** [comment]
That's great to know I must admit I am concerned about these apparent  discrepancies  between sandbox and live production because not all the tests we are doing now are actually valid as far production is concerned. We are running live test later this month and unfortunately I have no idea what will actually work. Presumably production has it's own set of rules and therefore errors. 

My question then is: Will these quarterly date ranges for obligations work in production?
