### ISSUE TITLE
CLIENT_OR_AGENT_NOT_AUTHORISED Error

### ISSUE THREAD

**Issue by aswinpillai** [hmrc/vat-api#135]
When we access the obligations endpoint  we are getting 403 Forbidden error .

Endpoint we are trying to use is 
`https://test-api.service.hmrc.gov.uk/organisations/vat/{Vrn}/obligations`

We are using the credentials and VRN returned as a part of creating the test organisation while accessing the above endpoint

Error response is as follows :
 
we are getting the following error 
`{
    "code": "CLIENT_OR_AGENT_NOT_AUTHORISED",
    "message": "The client and/or agent is not authorised."
}`

Would someone be able to help us resolve this issue ?

Thanks 
Aswin

**Comment by Accu-Man** [comment]
I discovered this yesterday: SDSTeam say it is a known problem their end.

**Comment by audupa** [comment]
@aswinpillai I would suggest you to check if your VAT (MTD) API subscription is turned on. I guess after the new API release this was turned off for us. Once you have it turned on, you should be seeing the 500 Internal Server Error which HMRC is still working on fixing it.

**Comment by aswinpillai** [comment]
@audupa  Yeah same thing happened to us also . We did turn the subscriptions back on after HMRC's update. After that we started getting 500 in all the VAT endpoints and from yesterday onwards we are getting 403 forbidden on the obligations endpoint

**Comment by Accu-Man** [comment]
Thanks. It had been switched off. I have started the process again with a new Test User. It allows me to authorise but I still get Err403 when I request Obligations

**Comment by MarkAKelly** [comment]
@Accu-Man @aswinpillai @audupa there will be some guidance coming around shortly about setting up new test users that marry up to our new authentication process. 

We are waiting for the service team that maintains the creation of test users to deploy the changes for use in the Sandbox environment.  

In the meantime please go through the normal channel for access issues at SDSTeam@hmrc.gsi.gov.uk and your question will be dealt with. 

Cheers,

Mark

**Comment by aswinpillai** [comment]
Its now working for us after the latest fix from HMRC . So closing the issue
