### ISSUE TITLE
Developer Hub API subscription for VAT

### ISSUE THREAD

**Issue by carpii** [hmrc/vat-api#148]
In the HMRC Developer Hub, you can configure your application to allow access to various API endpoints

There does not appear to be a subscription for this VAT API though. 

Does it fall under another API description?

**Comment by jonathanleather** [comment]
Hi @carpii 

The VAT-API currently falls under "Private API's".
In order for you to see it / subscribe you will need to have your application whitelisted. 

To do this please contact SDST - SDSTeam@hmrc.gsi.gov.uk who will guide you through this. They will then pass your details on to us who will then whitelist you, granting you access to the API.

Cheers
Jon

**Comment by carpii** [comment]
@jonathanleather Thanks Jon!
