### ISSUE TITLE
VAT API

### ISSUE THREAD

**Issue by AbsoluteAccounting1** [hmrc/vat-api#149]
Can someone tell me what test VRN number i should use on the new making tax digital VAT test Api. I have created a test user and authenticate successfully.
Thanks

**Comment by MarkAKelly** [comment]
Hi @AbsoluteAccounting1,

I believe the VRN you need is returned as part of the initial request you made to the create test user API.

**Comment by AbsoluteAccounting1** [comment]
Thanks Mark. So i have to go through the create test user API in code rather than creating the test user via the hrmc developer portal?

**Comment by markogrady** [comment]
You need to create a test organisation rather than a user and the vrn will
appear on screen

**Comment by AbsoluteAccounting1** [comment]
Thank you. I'll give that a go.
