### ISSUE TITLE
write:vat scope on View VAT Return

### ISSUE THREAD

**Issue by sonicmule** [hmrc/vat-api#151]
Just implemented the View VAT Return function and noticed it uses the write:vat scope instead of read:vat.
Is there a reason for this as the function is a GET?

**Comment by jacobbrownlow** [comment]
Hi @sonicmule 

Yes I believe GET requests require read:vat permissions.
When setting up your permissions you can use *scope=read:vat+write:vat* to enable both.

Regards, Jacob

**Comment by rbs-ben** [comment]
I wanted to bump this as I don't think the given answer makes sense.  You say "GET requests require read:vat permissions" but this one doesn't, it requires write:vat.  The question is, why?

It's true we can request read:vat+write:vat , but this seems like a workaround.  To view a VAT return the user will have to grant permission for the software to "Change your VAT information", which isn't appropriate.
