### ISSUE TITLE
CLIENT_OR_AGENT_NOT_AUTHORISED for every request passing correctly obtained token

### ISSUE THREAD

**Issue by agabuza** [hmrc/vat-api#154]
Hi,

Receiving 403 (CLIENT_OR_AGENT_NOT_AUTHORISE) for every request sent to sandbox (obligations, liabilities, etc.). 
Bearer token used in the request is generated for test user through the Oauth2 auth code flow. 
Any ideas?

Thanks,
Anatolii

**Comment by narendravijayarao** [comment]
Hi Anatolii,

Can you confirm that you are using the /create-test-user/organisations endpoint with the following service
{
 "serviceNames": [
   "mtd-vat"
 ]
}

Thanks,
Narendra

**Comment by AGRocks** [comment]
I've used a link 'Create test user -》Organization' from Auth form (not an API endpoint). 

Will it have required accesses?

**Comment by narendravijayarao** [comment]
Hi Anatolii,

At the moment we only support the test user created via API. Please try creating the user using API.

Thanks,
Narendra.

**Comment by agabuza** [comment]
Thanks, working now! 
Would suggest to remove 'Create Test User' link from login form to avoid such scenarios.

**Comment by MrSent** [comment]
So, I'm right in saying that creating a test user using the web interface doesn't work when testing with that user via API calls? Wow, there's a few days wasted I could have done without. Why is that page still on the website?

**Comment by jacobbrownlow** [comment]
Hi @MrSent

Unfortunately the Frontend doesn't currently work for mtd vat. We are waiting for this enhancement to be approved by the team who owns it. I will chase them up. Sorry for the confusion.

Jacob
