### ISSUE TITLE
Explanation of CLIENT_OR_AGENT_NOT_AUTHORISED

### ISSUE THREAD

**Issue by kmanish86** [hmrc/vat-api#157]
Hi Team,
Reaching out to understand the  error 403 CLIENT_OR_AGENT_NOT_AUTHORISED during VAT read / write api? 

- We believe it is to indicate that the "Access Token passed in the request is valid but is not authorized to access the data of the given VRN". Let us know if this is incorrect.
- As per the list of common errors defined in https://developer.service.hmrc.gov.uk/api-documentation/docs/reference-guide#errors this situation overlaps with 401 - UNAUTHORIZED. Is there any difference between the two.
- Is it safe to say that the possible solution for the user is to ensure they have access to the VRN and validate if VRN entered is indeed accurate ?  
- Could it also be returned if the user is not subscribed to MTD ?

**Comment by westwater** [comment]
Hey @kmanish86,
These are the scenarios that are covered by a 403.

A 403 CLIENT_OR_AGENT_NOT_AUTHORISED response would be returned if either:
- the client is not subscribed to MTD
- the agent is not subscribed to Agent Services
- the client has not authorised the agent to act on their behalf

A ticket has been created to add this detail into the API documentation

**Comment by kmanish86** [comment]
👍

**Comment by kmanish86** [comment]
Hi @westwater : In order for us to build great end user experience in our product, will it be possible to give granular error code for each scenario instead of a generic error code.

**Comment by CoppensBart** [comment]
I'm currently getting the same error message for a newly created test user (organisation).
With the user credentials I can do a successful call to the "Hello World/Application/User" end points.
Any ideas about why this happens?

**Comment by nnotsofun** [comment]
I have gotten the 403 client not aurthorised error code on newly created organisations through the endpoint when using a different vrn - so not using an agents (which doesn't appear to work for VAT?). 

When I change the endpoint to use the associated Vat number it works - I may have misunderstood, but it doesn't appear that scenario is listed in your response @westwater - is that the expected outcome in that scenario? This scenario is along the lines of @kmanish86's first point.

**Comment by jacobbrownlow** [comment]
Hi @nnotsofun 

Currently there is no method of setting up an Individual or Agent test user in the sandbox environment.
The only way to setup an Organisation is by using the create-test-user API with service name "mtd-vat".

If you change the VRN in your request, then the client (Organisation) is no longer linked to the bearer token, and so you will be returned a 403 CLIENT_OR_AGENT_NOT_AUTHORISED. This scenario would fall under "the client is not subscribed to MTD".

Does this help?
Jacob

**Comment by nnotsofun** [comment]
Thanks @jacobbrownlow that does make sense to me - but like @kmanish86 indicated I do feel that scenario of trying to access an unlinked identifier such as a VRN, falls more under the umbrella of the UNAUTHORIZED code's description.

```
Supplied OAuth token not authorised to access data for given tax identifier(s) 
```

Will there be a scenario in MTD VAT where the UNAUTHORIZED code will be returned?

**Comment by scottylace** [comment]
Hi @nnotsofun @kmanish86, for the foreseeable future this will stay as 403 - CLIENT_OR_AGENT_NOT_AUTHORISED. For consistency purposes, we have taken your comments on-board with the wider API Platform not just MTD.

**Comment by khabut** [comment]
I am also getting error CLIENT_OR_AGENT_NOT_AUTHORISED
 which was working. I have resubmitted tokens and unsubscribed and subscribed to bat api but keep getting this error. Has something changed or do I need a new vrn number and how do I get this?

**Comment by Deedles46** [comment]
We also get 


{"code":"CLIENT_OR_AGENT_NOT_AUTHORISED","message":"The client and/or agent is not authorised."}
we then sent  post request



did you run this request on postman?


{
  "serviceNames": [
    "corporation-tax",
    "paye-for-employers",
    "submit-vat-returns",
    "national-insurance",
    "self-assessment",
    "mtd-income-tax",
    "mtd-vat",
    "lisa",
    "secure-electronic-transfer",
    "relief-at-source",
    "customs-services"
  ]
} which we sent to this end point (https://test-api.service.hmrc.gov.uk/create-test-user/organisations)but we got an error. Please send us the correct test user set up documentation so we can follow it.

**Comment by jacobbrownlow** [comment]
Hi @Deedles46 

You appear to be using the correct API call to generate a test user. As seen below.

![image](https://user-images.githubusercontent.com/35334115/42869410-d98c3600-8a6c-11e8-9ecd-777bd23f0d03.png)

![image](https://user-images.githubusercontent.com/35334115/42869345-aeba84e0-8a6c-11e8-93bb-a38e501dcb1c.png)

The next step is to grant approval for this tax payer (vrn) to your vendor application. We usually do this by hitting this URL on any browser:
```
https://test-api.service.hmrc.gov.uk/oauth/authorize?response_type=code&client_id= <CLIENT_ID> &scope=read:vat+write:vat&redirect_uri=http://localhost:9000&state=12345
```

Finally this will return a code in the URL
```
http://localhost:9000/?code=b283836bc9f3474cb9390bca4aa5395c&state=12345
```

You need to hit the oauth token API, as below
![image](https://user-images.githubusercontent.com/35334115/42869752-dafee478-8a6d-11e8-91ff-ba325c036b41.png)

This will leave you with a vrn and an access token. In this example
vrn: 666888655
access token: bearer 1f2838e23ece00f6e818e8c962669

Try again and let us know if you have any issues

Regards, Jacob

**Comment by KilskyreMan** [comment]
Odd one from me :) - My application has been whitelisted for MTD-Vat and when I request a Test-User using the organisation end-point, using Postman, I get back a Test User with VRN.

Using the same credentials, server token, scope ("mtd-vat") json body etc from my C# Application (using RestSharp) I get a test-user but with no VRN?

**Comment by StuBramley** [comment]
Is there any way to validate that a user is authorised to a VRN other than trying to use it on an API call and catching this error?

**Comment by pwatts001** [comment]
> A 403 CLIENT_OR_AGENT_NOT_AUTHORISED response would be returned if either:
> 
> * the client is not subscribed to MTD
> * the agent is not subscribed to Agent Services
> * the client has not authorised the agent to act on their behalf

@westwater, is it possible to achieve the third point within the Sandbox? I can a) create a new client/organisation which is subscribed to MTD b) create an agent subscribed to Agent Services BUT I can't see how it's possible for the client/organisation to authorise the agent?

Any help would be much appreciated!

Phil

**Comment by pwatts001** [comment]
Thanks @CoppensBart, do you know when it'll be available to us in Beta? 

Can you confirm if an agents access token will be able to access all their clients VAT info (through the API's) in the same way the client would access them with their own access token? (assuming the client has granted the agent to act on their behalf)

Thanks

**Comment by CoppensBart** [comment]
@pwatts001  , I have no idea, I'm not related to HMRC.
You can request access to the API, that's what our QA team did.
Info about the API can be found here:
https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/agent-authorisation-api/1.0

**Comment by lebragan** [comment]
My setup has been autorized by the customer (myself, as developer). Went  thorugh the Client authorization process earlier.

I'm hitting some hard wall where I neither can get the GET of the Obligations nor Post a return.

I'm wondering if below I'm missing Authorization headers, somehow, as indicated under https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0#_retrieve-vat-obligations_get_accordion.

The log I'm getting while trying to get Obligations is:
{
  "Request": {
    "Header": {
      "Accept": "application/vnd.hmrc.1.0+json",
      "Content-Type": "application/json",
      "Gov-Test-Scenario": "QUARTERLY_NONE_MET"
    },
    "URLRequestPath": "/organisations/vat/666469454/obligations?from=2019-01-01&to=2019-03-31",
    "Method": "GET",
    "ServiceURL": "https://test-api.service.hmrc.gov.uk"
  },
  "Response": {
    "Error": {
      "code": "403",
      "name": "Forbidden",
      "description": "Forbidden"
    },
    "Content": {
      "code": "CLIENT_OR_AGENT_NOT_AUTHORISED",
      "message": "The client and/or agent is not authorised."
    }
  }
}


Mind if you could help? Many thanks

**Comment by Byordanova8** [comment]
@lebragan 
Hello there.
These are the steps your should follow in order to Retrieve VAT Obligations.

1) **Create test user organisation** ---> https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/api-platform-test-user/1.0

![1](https://user-images.githubusercontent.com/46526406/50899631-5a1c7e00-141b-11e9-8cd9-75ad2c1a4add.PNG)
![2](https://user-images.githubusercontent.com/46526406/50899634-5e489b80-141b-11e9-93a4-71a3da6a03ca.PNG)

2) **User restricted endpoints** ---> https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints

![3](https://user-images.githubusercontent.com/46526406/50900256-538f0600-141d-11e9-8c04-1951798c6c48.PNG)

(open this in the browser and when you end up in the Example domain copy the string from the URL after "code". **_That_** is your Authorization code)

![url](https://user-images.githubusercontent.com/46526406/50900268-5c7fd780-141d-11e9-996b-92b5dc75f960.PNG)

![4](https://user-images.githubusercontent.com/46526406/50900282-61dd2200-141d-11e9-9a88-28dcb817dff9.PNG)
![5](https://user-images.githubusercontent.com/46526406/50900297-6a355d00-141d-11e9-81f7-057697d7fca5.PNG)

(copy/paste your details --- **_That_** is your Access bearer token)

3)  **Retrieve VAT Obligations** ---> https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0#_retrieve-vat-obligations_get_accordion

![6](https://user-images.githubusercontent.com/46526406/50900176-188cd280-141d-11e9-8464-1252613d73e9.PNG)

(use your User Organisation details **VRN** and User Organisation **Access token**)

**Comment by lebragan** [comment]
@Byordanova8 Many thanks for yur kind and elaborated help. Apologies, last week has been quite frenzy for me, I'll try your suggestions the soonest and will get back with a proper reply.

**Comment by ManishS-OpusVL** [comment]
@Byordanova8 Can you please advise how can we obtain the 'Client ID' and 'Client Secret' for a test user generated through this https://developer.service.hmrc.gov.uk/api-test-user ?

**Comment by Byordanova8** [comment]
Go to [API Documentation](https://developer.service.hmrc.gov.uk/api-documentation)
Then [Using the Developer Hub](https://developer.service.hmrc.gov.uk/api-documentation/docs/using-the-hub)
Then [Register for a developer account](https://developer.service.hmrc.gov.uk/developer/registration)
Then Sign in in HMRC
After that click on **Your Name** in the right corner
You should be able to see [Manage applications](https://developer.service.hmrc.gov.uk/developer/applications)

Then **Add application**
After the creating the application you should find the link **Manage credentials.**

**Comment by ManishS-OpusVL** [comment]
@Byordanova8 Yes, that correct. I am aware about that.
But, for testing in sandbox environment we need to generate the test users using this link https://developer.service.hmrc.gov.uk/api-test-user

And I can see any link between the test user id & password generated through this link 'https://developer.service.hmrc.gov.uk/api-test-user' and the Client ID And Secret which is present in 'Manage credentials' ?

**Comment by Byordanova8** [comment]
@lebragan 

Well, there are two things that I could suggest.

To check whether you have addded your redirect Uri in HMRC:

**Manage redirect URIs**

> https://developer.service.hmrc.gov.uk/developer/application/a605470c-3033-4afa-9be8-4288a4b83f01/redirect-uris

To change your redirect uri as mine:

> https://www.example.com/auth-redirect

**Comment by Byordanova8** [comment]
@ManishS-OpusVL 

You can use the API as well: 
https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/api-platform-test-user/1.0

You need the server token here.

**Comment by ManishS-OpusVL** [comment]
@Byordanova8 Ok, that seems to establish a relation. Another question, what service name should we provide for enrolling the test user for Hello World API when sending the request for creating test user ?

**Comment by Byordanova8** [comment]
None. Hello World API is with unrestricted access. 
[API](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/api-example-microservice/1.0)

**Comment by ManishS-OpusVL** [comment]
@Byordanova8 In hello world API, for endpoint 'Hello User' it is a restricted access which needs auth code & access tokens.

**Comment by Byordanova8** [comment]
@ManishS-OpusVL 

Have not done that. But do you need it really?

**Comment by lebragan** [comment]
@Byordanova8,
> https://www.example.com/auth-redirect

 I had earlier registered at HMRC the redirect URI as ietf:wg:oauth:2.0:oob and was able to authenticate the client id using the secret, and got the autorization token.

However, I'm failing to understand how a straight  **https://www.example.com/auth-redirect**  would work instead, but pardon me, it must be my fault. I'll give it a go when I have a moment with that URL exactly as indicated :)

**Comment by lebragan** [comment]
> * the client is not subscribed to MTD

I'm wondering what's going on while using the test api HMRC service on my side. I authorized the client, got the HMRC autotrization code for my Test User upon "his" login and grantiing access to the VAT data, and still, when trying to request obligations, I get this logged:
![image](https://user-images.githubusercontent.com/40581789/51804915-7cf1c380-225e-11e9-8ed2-6252831b18de.png)

Could anyone help? Starting to feel quite uneasy here :)

**Comment by jacobbrownlow** [comment]
Hi @lebragan 

Your request appears to be missing the _Authorization_ header. Can you double check?

Jacob

**Comment by jacobbrownlow** [comment]
Hi 

You should use the code returned by the "grant authority" journey to call oauth and this will return a bearer token.
<img width="638" alt="screenshot 2019-01-28 at 08 16 34" src="https://user-images.githubusercontent.com/35334115/51826842-efef4e80-22df-11e9-9795-1d27352002ff.png">

The headers necessary to hit vat-api /obligations are:
![image](https://user-images.githubusercontent.com/35334115/51826837-eb2a9a80-22df-11e9-8390-3ae90c8a6dd7.png)

**Comment by lebragan** [comment]
Many thanks Jacob, id rather prefer an actual example, but I’ll do my best to to try your indications.

**Comment by jacobbrownlow** [comment]
Hi @lebragan 

The example log you posted earlier was correct accept for the 1 missing header. If you add the Authorization header you should get a successful response

e.g.
![image](https://user-images.githubusercontent.com/35334115/51833302-f3d69d00-22ee-11e9-895e-751e95dafde1.png)

**Comment by lebragan** [comment]
Thanks for the example, but still we,re not passing the bearer token in that code and didn’t we need to get the period keys first? I’m really confused, apologies.

**Comment by jacobbrownlow** [comment]
@lebragan 

The test user setup should follow this order:
1. setup vendor application for the Sandbox environment (do once)
2. create-test-user API to generate an enrolled tax payer
3. navigate to the grant authority URL and login
4. grant authority at which point a code is returned
5. request bearer token from oauth using this code

Are you correctly retrieving the bearer token in step 5?

e.g.
<img width="638" alt="screenshot 2019-01-28 at 08 16 34" src="https://user-images.githubusercontent.com/35334115/51835222-9fceb700-22f4-11e9-93e3-1e805f93b50e.png">
The client ID and secret are your vendor application credentials from the developer hub.

**Comment by lebragan** [comment]
Yes, I got the bearer token for the simulated user. The issue here is I’m not apparently applying it in the code being sent and if I could see an example of such code (the authorization part) that would be brilliant!


This message is private and confidential. If you received this message in error, please notify me and remove it from your system.

**Comment by lebragan** [comment]
Looking st your screenshot example, sorry missed that earlier.  I’ll embed a similar part on my code and see how it goes. Many thanks!



This message is private and confidential. If you received this message in error, please notify me and remove it from your system.

**Comment by barrychoc** [comment]
Hi - I am working entirely in sandbox just now.

I have (via api) created an organisation and an agent. I want to link the organisation to the agent so that I can use the agent oauth bearer to call mtd vat api on organisation.  Can someone please tell me how i can (in sandbox) link organisation with agent so that hey are basically an agent for the organisation as will be the case with my currnt "real clients"?

**Comment by CoppensBart** [comment]
Hi @barrychoc ,
you need to use the Agent-Authorisation-api:
https://github.com/hmrc/agent-authorisation-api
or
https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/agent-authorisation-api/1.0

**Comment by barrychoc** [comment]
Ok, thanks.

**Comment by barrychoc** [comment]
One question though please - 

Does the usage of this api:
https://github.com/hmrc/agent-authorisation-api)

not depend on HMRC allowing access to the agent authorisation api in the first place?
