### ISSUE TITLE
NOT_FOUND error

### ISSUE THREAD

**Issue by nigelrainer** [hmrc/vat-api#159]
Under what circumstances might we expect to receive the following error on an obligations request:

NOT_FOUND
The remote endpoint has indicated that no data can be found

There is no mention of this error code or circumstances in the API documentation but we are getting it on our production instance.

**Comment by MarkAKelly** [comment]
Hi @nigelrainer,

In this scenario it means that a request we have made to our backend systems has not returned any data.  Therefore in the case of obligations it means that there is no data for the VRN within the date range provided.
 
In relation to the documentation we have a story upcoming in our backlog to review the error messages that we supply, and as a result all domain specific and generic errors will be documented for each API.

Hope this helps,

Mark

**Comment by nigelrainer** [comment]
Thank you.  Can I make the point that the message "The remote endpoint has indicated that no data can be found" is not helpful and not something that we can relay to our end users hence creating more work for us to translate everything into English.  Error reporting currently in MTD is a massive step backwards from what we currently have in the XML gateway service.

**Comment by MarkAKelly** [comment]
You can make that point, and I will pass that onto the architect and content designers who are focussing on this.  It's something as a team sitting between 3rd parties and the tax platform's BLL's that we are very aware of and are taking steps to improve where we can.

**Comment by nigelrainer** [comment]
Thank you.  Much appreciated.
