### ISSUE TITLE
 CLIENT_OR_AGENT_NOT_AUTHORISED 

### ISSUE THREAD

**Issue by khabut** [hmrc/vat-api#170]
I am also getting error CLIENT_OR_AGENT_NOT_AUTHORISED
which was working. I have resubmitted tokens and unsubscribed and subscribed to bat api but keep getting this error. Has something changed or do I need a new vrn number and how do I get this?

**Comment by khabut** [comment]
I created a new test organisation but this also produced the same error

**Comment by khabut** [comment]
I created a new organisation  to get a new vrn number 666793146. I tried using this but got the same message.

Previously once I received  a token I could use the command below to retrieve data

curl -H 'Authorization: Bearer 46c34fbb30f8dc9ca91170e6da4a4191' \
-H 'Accept:application/vnd.hmrc.1.0+json' \
'https://test-api.service.hmrc.gov.uk/organisations/vat/666793146/obligations?from=2017-04-06&to=2018-01-06&status=O' \
-o vatobligation.json

**Comment by MarkAKelly** [comment]
Did you use the Create Test User API or the web service to create this organisation?  We have been advising people to use the API rather than the frontend as there are issues with creating VAT users through the frontend.

**Comment by khabut** [comment]
I have created a new organisation using the API instead and this has worked. Thanks for your help.
