### ISSUE TITLE
REST API, to-be Mandatory Header parameters - Which scheme to follow

### ISSUE THREAD

**Issue by nickfowlie** [hmrc/vat-api#171]
Hi

I want to ensure I'm correctly identifying and supplying the necessary "Header" information in our API requests.

So you can help me assure I have the correct headers, below is a description of our system architecture  - 

.......... our client users run aACESoft, a Desktop or Server or SaaS FileMaker Application (option is dependent on clients needs). The aACESoft  Application does NOT directly "talk" to HMRC or any other API's, but sends requests to a Linux server containing our aACESoft Web- Services Server (AWSS), those requests messages are a generic/standard format.

The AWSS handles multiple Webservice using the generic message format, target webservice API's can be can be one of many protocols eg SOAP, REST, xml-rpc etc so AWSS converts the generic message to the necessary format/Protocol then sends them to the target API. Responses from the API targets are re-formatted to a generic  message response structure and returned to the aACESoft instance to parse as necessary..........

Given the above description I assume of the six  "connection methods" described below (and here) ......
A.	Mobile application direct to HMRC
B.	Desktop application direct to HMRC
C.	Mobile application via third party developer (vendor) server to HMRC
D.	Desktop application via third party developer (vendor) server to HMRC
E.	Web application via vendor's server to HMRC
F.	Batch process direct to HMRC
...the closest description is "D"  - Desktop application via third party developer (vendor) server to HMRC !! Does this  appear appropriate OR should I be using one of the other models described in the list ??
Regards 
Nick.

**Comment by MarkAKelly** [comment]
Hi @nickfowlie, 

All headers that we require to enable access to the VAT API are listed in the 'Request Headers' section of the endpoints in the developer hub documentation.  As far as I am aware, we have vendors who are using a number of the above models to access our API's.  

Out of interest where did you get this list, and how do you think your choice of model will affect your implementation?

Mark

**Comment by nickfowlie** [comment]
Hi

 

Interesting/worrying you don't know of  the documentation .. see  here <https://developer.service.hmrc.gov.uk/api-documentation/docs/reference-guide#versioning>  (under heading Fraud Prevention) and in the VAT API here <https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0>  which references it. The reason I want to add them is because the documentation says they will become "compulsory" for every request hence I'm keen to get this sorted out of the blocks.

 

As regards to what model to use I assume as they are to be compulsory it has to be accurate otherwise access may be denied e.g If I try to use connection method "E" I can't supply some of the information as we don't send requests from  a "web application" !

 

After you have had time to read the docs can you confirm as I requested, that I should be following "connection method D" given our architecture, so we don't have to update our integration once live.

 

Regards

 

Nick

 

 

 

---

Nicholas Fowlie

aACE Software 

Phone: (646) 257-4713

Email:nicholas.fowlie@aacesoft.com <mailto:nicholas.fowlie@aACEsoft.com> 

 <http://www.aacesoft.com/> www.aACEsoft.com

 

Connect with us for news, videos, and tips & tricks:
Facebook <https://www.facebook.com/aacesoft>  / Twitter <https://twitter.com/aACEsoft>  / LinkedIn <https://www.linkedin.com/company/avant-garde-information-solutions-llc>  / YouTube <https://www.youtube.com/channel/UCIn8AqB-zqt8iSpWN-goVpg>

**Comment by MarkAKelly** [comment]
@nickfowlie We are aware of the documentation.  As the delivery team that create and maintain the VAT and SA API's we look after the technical documentation specifically regarding the technical implementation of these - I was simply asking where you had got your information so that our content designers can assess how useful it is.

From your description that does seem to be a suitable option, however it is not really our place to comment on vendor solutions or architecture, so I would suggest that you contact the Software Development support team at SDSTeam@hmrc.gsi.gov.uk who will be able to channel your queries to the teams that are responsible for integration with HMRC's API platform.
