### ISSUE TITLE
Submit VAT Return seems to be reporting false errors

### ISSUE THREAD

**Issue by MKoppJones** [hmrc/vat-api#172]
Hi,

Currently sending the following payload through when submitting a VAT return

```json
{
  "periodKey": "0003",
  "vatDueSales": 142980.12,
  "vatDueAcquisitions": 210234.65,
  "totalVatDue": 353214.77,
  "vatReclaimedCurrPeriod": 210234.65,
  "netVatDue": 142980.12,
  "totalValueSalesExVAT": 750150.12,
  "totalValuePurchasesExVAT": 1149793.32,
  "totalValueGoodsSuppliedExVAT": 750150.12,
  "totalAcquisitionsExVAT": 1149793.32,
  "finalised": true
}
```

It is reporting the following error

```json
{
	"code": "INVALID_REQUEST",
	"message": "Invalid request",
	"errors": [{
		"code": "INVALID_MONETARY_AMOUNT",
		"message": "amount should be a monetary value (to 2 decimal places), between -9,999,999,999,999.00 and 9,999,999,999,999.00",
		"path": "/totalAcquisitionsExVAT"
	},
	{
		"code": "INVALID_MONETARY_AMOUNT",
		"message": "amount should be a monetary value (to 2 decimal places), between -9,999,999,999,999.00 and 9,999,999,999,999.00",
		"path": "/totalValueGoodsSuppliedExVAT"
	},
	{
		"code": "INVALID_MONETARY_AMOUNT",
		"message": "amount should be a monetary value (to 2 decimal places), between -9,999,999,999,999.00 and 9,999,999,999,999.00",
		"path": "/totalValuePurchasesExVAT"
	},
	{
		"code": "INVALID_MONETARY_AMOUNT",
		"message": "amount should be a monetary value (to 2 decimal places), between -9,999,999,999,999.00 and 9,999,999,999,999.00",
		"path": "/totalValueSalesExVAT"
	}]
}
```

Honestly, this doesn't make any sense.

Any known issues here?
Anything glaringly wrong with the payload?

**Comment by MarkAKelly** [comment]
Hi @MKoppJones,

Boxes 6 to 9 of a standard VAT Return (the fields your getting errors for) have only ever accepted whole numbers, so the reason you're getting errors is due to the fact you have decimal values.

We have had to keep the error message in the format shown above, as we have to allow for entry of whole numbers in a decimal format i.e, 500 as 500.00.  

Mark

**Comment by MKoppJones** [comment]
Brilliant, thank you for the prompt response. Will try and close. 

Could I suggest that the documentation is updated to reflect this more clearly?

**Comment by MarkAKelly** [comment]
@MKoppJones 

You certainly can, I'll pass it on to our content designer (I know she's been looking at this specific issue recently).

I'll close this issue but if you have any other issues regarding this feel free to reopen!
