### ISSUE TITLE
In Sandbox when I get the obligations list for VAT I was told to put in a minimum date range of 6 months. Why?

### ISSUE THREAD

**Issue by Deedles46** [hmrc/vat-api#176]
We were told at the Hackathon MTDfB that there were “canned” responses in the Sandbox Test HMRC environment for VAT API and that in the Test environment, to get a list of obligations, we had to query a date range of minimum 6 months. If we did, then we would get the obligations list.  If we did not, we would not get any obligations list.    In live to get a list of obligations for VAT, the user must enter a date range, but is there a minimum date range in Live and if yes, please explain the minimum date range requirement for VAT API?  Also, in Test sandbox, please explain why the minimum date range of 6 months for VAT API is required?

**Comment by jonathanleather** [comment]
Hey @Deedles46 

In live there is **no** minimum date requirement.
In sandbox there is currently an outstanding bug which forces the "minimum date range of 6 months".

This is being looked at but unfortunately we do not have an ETA as to when this limitation will be removed from sandbox.

Hope this clears everything up for you.

Cheers
Jon

**Comment by robd** [comment]
Hi @jonathanleather 

Thanks for the clarification on the production behaviour and working to fix this in sandbox. In the meantime, would you be able to give us some guidance on the following cases:

1) Are the `to` and `from` dates inclusive or exclusive when matching an obligation period?

2) Will partially matched periods be returned? (ie overlapping the beginning / end of a period or completely within a period)

Imagine we wanted to retrieve an obligation for a 3 month VAT period from 1st Jan - 31st March 2018. 
What would the following queries return? (eg would they return the period we want and/or the previous or next periods):

a) `from=2018-01-01&to=2018-03-31` // Exact range match
b) `from=2018-01-01&to=2018-04-01` // Query range fully covers the period plus start of next period
c) `from=2017-12-31&to=2017-03-31`// Query range fully covers the period plus end of the previous period

Single day matches:
d) `from=2018-01-01&to=2018-01-02`// Query range matches the first day of the period
e) `from=2018-03-30&to=2018-03-31` // Query range matches the last day of the period
f) `from=2018-02-05&to=2018-02-06` // Query range matches middle of the period

3) Is there any way for us to get a test company/user on production? This would really help us explore the actual API while the sandbox fixes are in progress.

Thank you,
Rob

**Comment by jonathanleather** [comment]
Hey @robd 

1. The `To` and `From` dates are Inclusive
2. Overlapping - As long as the period `From` or period `To` date falls within selection range, then it would get returned. Which would mean in the example date range you have stated, A-F would be returned.
3. Unfortunately not. Test users are not allowed in production, not even for us.

The canned responses for this endpoint are under review. So if you have any specific scenarios that you would like to test and think would benefit others, then do let us know. One thing to note however is that we cannot provide personalised scenarios and I also cannot guarantee that every scenario you suggest will make it in as a canned response. Although we will try our best to provide as much as possible.

Let me know if you have any other questions.

Cheers
Jon

**Comment by PavithiraS** [comment]
Hi @jonathanleather : Can you please clarify the following : 

From what I understand in the above conversation, if I need to retrieve the obligation for a period, is it enough if I just give a date range containing a day and its very next day?

From the above example by Rob, in the case F, its just 5th and 6th of a month and if that is going to retrieve the period in which both the days follow, will you suggest the softwares to use the data range like the one below :
From date : 1st Jan 2018
To date :  2nd Jan 2018 
and I receive  "2018-01-01 and 2018-03-31" as Response for VAT period.
Then I'll give (based on the end date of previous period), 
From date : 1st April 2018
To date :  2nd April as To date,
to retrieve "2018-04-01 and 2018-06-30"  ?

This way, before every VAT Return, I can hit the obligation API using previous period's end date to retrieve the next obligation and then submit the VAT.

Please clarify.

Thanks in advance.

Best Regards,
Pavithira

**Comment by jonathanleather** [comment]
Hi @PavithiraS 

It's not our place to suggest how you should build your software but based on discussions we have had with the backend teams, the scenarios you have stated will return the obligation. Providing the period From or period To date falls within selection range.

Cheers
Jon

**Comment by Deedles46** [comment]
Hi @jonathanleather 

Because there is an outstanding bug which forces the "minimum date range of 6 months", please tell me what the "canned" responses are in the Sandbox for obligations?  This will help me write a test case which will test the entire VAT API process which is the aim of having the Sandbox "canned" data present.  

We wanted to match 1 obligation from=YYYY-MM-DD&to=YYYY-MM-DD with the from and to date fields in our software so that we can progress to get a test VatReturnResponse.  Thanks

**Comment by jacobbrownlow** [comment]
Hi @PavithiraS 

Jon is on leave. The response in sandbox for GET VAT Obligations appears to be dynamic, and dependant on the dates you enter.

For the following dates `/obligations?from=2017-01-01&to=2017-12-31` ..

The default response is 1 met, 3 open
```{
    "obligations": [
        {
            "start": "2017-01-01",
            "end": "2017-03-31",
            "due": "2017-05-07",
            "status": "F",
            "periodKey": "#001",
            "received": "2017-03-26"
        },
        {
            "start": "2017-04-01",
            "end": "2017-06-30",
            "due": "2017-08-06",
            "status": "O",
            "periodKey": "#002"
        },
        {
            "start": "2017-07-01",
            "end": "2017-09-30",
            "due": "2017-11-06",
            "status": "O",
            "periodKey": "#003"
        },
        {
            "start": "2017-10-01",
            "end": "2017-12-31",
            "due": "2018-02-07",
            "status": "O",
            "periodKey": "#004"
        }
    ]
}```

ALL_MET returns
```{
    "obligations": [
        {
            "start": "2017-04-06",
            "end": "2017-07-05",
            "due": "2017-08-12",
            "status": "F",
            "periodKey": "#001",
            "received": "2017-08-05"
        },
        {
            "start": "2017-07-06",
            "end": "2017-10-05",
            "due": "2017-11-12",
            "status": "F",
            "periodKey": "#002",
            "received": "2017-11-04"
        },
        {
            "start": "2017-10-06",
            "end": "2018-01-05",
            "due": "2018-02-12",
            "status": "F",
            "periodKey": "#003",
            "received": "2018-02-03"
        },
        {
            "start": "2018-01-06",
            "end": "2018-04-05",
            "due": "2018-05-12",
            "status": "F",
            "periodKey": "#004",
            "received": "2018-05-02"
        }
    ]
}```

NONE_MET returns
```{
    "obligations": [
        {
            "start": "2017-04-06",
            "end": "2017-07-05",
            "due": "2017-08-12",
            "status": "O",
            "periodKey": "#001"
        },
        {
            "start": "2017-07-06",
            "end": "2017-10-05",
            "due": "2017-11-12",
            "status": "O",
            "periodKey": "#002"
        },
        {
            "start": "2017-10-06",
            "end": "2018-01-05",
            "due": "2018-02-12",
            "status": "O",
            "periodKey": "#003"
        },
        {
            "start": "2018-01-06",
            "end": "2018-04-05",
            "due": "2018-05-12",
            "status": "O",
            "periodKey": "#004"
        }
    ]
}```

You can limit the number of obligations returned by reducing the to-from range. Currently there is a 6 month minimum, which is a bug and due to be removed soon.

It appears the dates are not 100% accurate based on my 2017 dates. I know there is a plan to improve the test data for VAT and so hopefully this will improve in the near future.

Regards, Jacob
