### ISSUE TITLE
Handling Incorrect Submissions

### ISSUE THREAD

**Issue by MKoppJones** [hmrc/vat-api#177]
Hi,

How would we handle an incorrect submission?

Is there a way to ignore a submission, or a way to correct a submission?

If not, how would we cater for this?

Example,

We make a submission for period 0001, a figure is incorrect and we notice after we hit submit. We now want to correct 0001.

Thanks,
Michael

**Comment by jacobbrownlow** [comment]
Hi Michael

We currently don't provide a way to amend a VAT return, and we have no plans to introduce an amendments API.

My understanding is that, depending on the circumstances, you can adjust the figures on the following period. Else you will need to use an alternative solution, which could involve a phone call or paper form. 

I would advise you to contact SDST. Could you please send your question to this email address SDSTeam@hmrc.gsi.gov.uk and they should be able to provide more information.

Jacob

**Comment by MKoppJones** [comment]
No worries, I will drop them a line, thank you for the help.
