### ISSUE TITLE
Getting 403 on hitting https://api.service.hmrc.gov.uk/oauth/token 

### ISSUE THREAD

**Issue by audupa** [hmrc/vat-api#179]
Hi there,

we are seeing "https://test-api.service.hmrc.gov.uk/oauth/token" return a 403 access denied, only when it's accessed from one of our preprod servers.
Could you please confirm if our IP - 10.158.64.17 is still whitelisted?
Client id - qPaEIsblmFXF8UGm1LtxScKZq4Qa

Let me know if you need any additional info?

Thanks,
Akshatha

**Comment by narendravijayarao** [comment]
Hi Akshatha,

Can you provide me the registered email address and also auth/application code, you can found
https://developer.service.hmrc.gov.uk/developer/applications/{{AUTH_CODE}}/credentials.

Is it only happening from from one of your pre-prod servers??

Thanks,
Naren.

**Comment by audupa** [comment]
Hi @narendravijayarao  

The authcode is - a144b270-c992-4c74-bdee-b9711817ac74 and registered email address is 'Akshatha_Udupa@intuit.com'

Thanks,
Akshatha

**Comment by narendravijayarao** [comment]
Hi Akshatha,

I had a look into the configurations and your auth code is already whitelisted. 
Apologise, I can't help you any further in this as it relates to the wider HMRC API Platform and is not exclusive to the MTD Self Assessment and VAT APIs.

Could you please send your question to this email address SDSTeam@hmrc.gsi.gov.uk and your question will be dealt with.

Thanks and sorry for the inconvenience.
Naren.

**Comment by audupa** [comment]
Thanks @narendravijayarao I have sent an email to SDSTeam@hmrc.gsi.gov.uk
