### ISSUE TITLE
Error 500 on Submit VAT Return

### ISSUE THREAD

**Issue by GarySmithMace** [hmrc/vat-api#181]
I may be missing something, but i am having trouble receiving a valid response from the Submit VAT Return API.

Test User Credentials
{
"userId":"360379281803",
"password":"uwhyndx5hojo",
"userFullName":"Laurie Jackson",
"emailAddress":"laurie.jackson@example.com",
"organisationDetails":
	{"name":"Company SZJNSJ",
	 "address":{"line1":"12 Latimer Place","line2":"Uppingham","postcode":"TS25 1PA"}
	},
"vrn":"666562863"
}

Returned Obligations
{
"obligations":
  [
{"start":"2017-10-01",
"end":"2017-12-31",
"due":"2018-02-07",
"status":"F",
"periodKey":"#001",
"received":"2017-12-26"}
,
{"start":"2018-01-01",
"end":"2018-03-31",
"due":"2018-05-07",
"status":"O",
"periodKey":"#002"}
,
{"start":"2018-04-01",
"end":"2018-04-30",
"due":"2018-06-06",
"status":"O",
"periodKey":"#003"}
]
}

Submit VAT Return Data

Address https://test-api.service.hmrc.gov.uk/organisations/vat/666562863/returns

ContentType "application/json"
Accept "application/vnd.hmrc.1.0+json"
Headers "Authorization" = "Bearer 6a9ec9b8d06a4dc19a6084ecb6d4af83"
Method "POST"

POST Data 

{"periodKey": "#002",
 "vatDueSales": 200.00,
 "vatDueAcquisitions": 0.00,
 "totalVatDue": 200.00,
 "vatReclaimedCurrPeriod": 0.00,
 "netVatDue": 200.00,
 "totalValueSalesExVAT": 1000.00,
 "totalValuePurchasesExVAT": 0.00,
 "totalValueGoodsSuppliedExVAT": 0.00,
 "totalAcquisitionsExVAT": 0.00,
 "finalised": true}

RESPONSE

{"code":"INTERNAL_SERVER_ERROR","message":"An internal server error occurred"}

I have tested with the Gov-Test-Scenario Header and still receive the Error 500

Any help or advice would be much appreciated.

**Comment by MarkAKelly** [comment]
Hi @GarySmithMace,

I'm just looking into this for you.  Everything looks right with the Test User response body - can I just check whether you used the frontend service to create your user or did you hit the API endpoint?

Cheers, 
Mark

**Comment by GarySmithMace** [comment]
I used the API Endpoint and created the User with {"serviceNames": ["mtd-vat"]} as the POST data to enrol the user for Making Tax Digital VAT

**Comment by khabut** [comment]
We are having the exact same issue. Do you know if this has been fixed?

Khalid

**Comment by MarkAKelly** [comment]
Hi @GarySmithMace and @khabut,

Were currently still looking into this - there was a change on the platform and we think that it has changed the way our implementation of Mongo is working.  

I will get to the cause of the problem and keep you updated on a fix as it happens.

Cheers,

Mark

**Comment by MarkAKelly** [comment]
@GarySmithMace and @khabut,

It appears that this could be due to duplicate submissions.  I've posted the same request with the same body and it works fine the first time, and the second time it returns the ISE (500) - can I ask if this is the same case for you both?  Try changing the period key in the body and let us know if you get the same thing.

There is currently a problematic bit of functionality in the simulator we have running in Sandbox which results in the duplicate submission response being converted into a 500 in our API - I'm looking into a fix.

Cheers,

Mark

**Comment by khabut** [comment]
Thanks I will check and let you know if this is the case

Khalid Butt
Senior Development Consultant

COINS
Building value through innovation
T: + 44 (0) 1753 501000   D: + 44 (0) 1753 501057  M: + 44 (0)772 9607964  W: www.coins-global.com<http://www.coins-global.com/>

Address: COINS Building, 11 St Laurence Way, Slough, Berkshire SL1 2EA
Construction Industry Solutions Limited is a company registered in England and Wales.  Company Registration no: 2039252

**Comment by liam-lagay-14** [comment]
@GarySmithMace and @khabut,

I can confirm that this was the same case for me. I got a successful submission first time, then with the same payload and submission dates the second time, I got a 500 error.

Thanks,
Liam

**Comment by kmanish86** [comment]
+1. I am facing the same issue where the first submission works fine and subsequent attempts fails.

**Comment by aroncox** [comment]
+1 - I am getting this issue too. It makes testing hard as I have to pick a new period each time I test.

**Comment by paulvickery** [comment]
What's the status of this? We have been mostly ok, but from the end of last week we have been getting a 500 for all submissions to the sandbox.

**Comment by MarkAKelly** [comment]
Hi @paulvickery,

Apologies for this - there has been a platform issue over the weekend which has meant submisson's don't seem to be working in the sandbox.

A fix has been applied and submissions should now be working again.

Sorry about the inconvenience.

As a general notice to anyone watching this thread - sandbox functionality has been updated so that duplicate submissions now return the expected error with a 409 status.  This will occur where multiple submissions have been made for the same period key, and is the expected behaviour of the API.  POST endpoints do not permit multiple submissions to the same data resource.  

Mark

**Comment by GarySmithMace** [comment]
Apologies for my lack of responses on this issue. I have recently returned to the project, tested and now i correctly receive a successful submission on the first attempt, and a Duplicate Submission error the second attempt.

Many thanks for your help. Will close this issue now

**Comment by andrisskutans** [comment]
With 
` 

$vrn = '391111example';//Here https://developer.service.hmrc.gov.uk/api-test-user i can create test user and get VAT number
$endpoint = 'https://test-api.service.hmrc.gov.uk/organisations/vat/'.$vrn.'/returns'; 

$periodKey = 'A001';


$vatReturnData = array(
    "periodKey" => $periodKey,
    "vatDueSales" => 105.5,
    "vatDueAcquisitions" => -100.45,
    "totalVatDue" => 5.05,
    "vatReclaimedCurrPeriod" => 105.15,
    "netVatDue" => 100.1,
    "totalValueSalesExVAT" => 300,
    "totalValuePurchasesExVAT" => 300,
    "totalValueGoodsSuppliedExVAT" => 3000,
    "totalAcquisitionsExVAT" => 3000,
    "finalised" => true
);

$vatReturnData = json_encode($vatReturnData);

$headers = [
'Accept: application/vnd.hmrc.1.0+json',
'Authorization: Bearer ' . $access_token, // From $response = file_get_contents('https://test-api.service.hmrc.gov.uk/oauth/token', false, $context); 
'Content-Type: application/json', 
'Content-Length: ' . strlen($vatReturnData)
];


$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, $endpoint);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_POSTFIELDS, $vatReturnData);
curl_setopt($ch, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_1);

$response = curl_exec($ch);

if ($response === false) {
echo 'Error: ' . curl_error($ch). ' '. show_line_number();
} else {
echo 'Response: ' . $response. ' '. show_line_number();
}


curl_close($ch);
`
i get "Response: {"code":"INTERNAL_SERVER_ERROR","message":"An internal server error occurred"}" Could someone check if the code correct?
