### ISSUE TITLE
Finalised BUSINESS_ERROR

### ISSUE THREAD

**Issue by MKoppJones** [hmrc/vat-api#182]
I can't seem to see this error documented anywhere.

If finalised is false, should we be getting this error?

Also, what exactly is finalised supposed to tell us?

**Comment by jonathanleather** [comment]
Hi @MKoppJones 

Are you referring to the Submit Vat Return endpoint?
If so, then this is a valid error scenario.

From the documentation under request:
finalised boolean required | Declaration that the user has finalised their VAT return.

From the documentation under error scenarios:
User has not declared VAT return as final | 403 (Forbidden) | NOT_FINALISED


Let me know if you need anymore clarification.
Cheers
Jon
