### ISSUE TITLE
AccessToken: "error":"invalid_request","error_description":"grant_type is required"

### ISSUE THREAD

**Issue by likedustg** [hmrc/vat-api#184]
First I got authorization code by posting request to https://test-api.service.hmrc.gov.uk/oauth/authorize

then using this reponsed code and other information when making request:
curl -X POST https://test-api.service.hmrc.gov.uk/oauth/token --data 'client_secret=f22fd070-957f-3051-ad2d-45620857dfe7&client_id=55RrubIrg_ABQki9kH3jbF7ilWwa&grant_type=authorization_code&redirect_uri=http%3A%2F%2Flocalhost%3A9090%2Foauth20%2Fcallback&code=1234567'

Always got this error..
{"error":"invalid_request","error_description":"grant_type is required"}

what's the problem here?
Thank you.

**Comment by jonathanleather** [comment]
Hi @likedustg 

Unfortunately we cannot answer this as it is related to the user registration and authorisation process. This channel is only for specific questions relating to the MTD VAT APIs.

Could you please send your question to this email address SDSTeam@hmrc.gsi.gov.uk and your question will be dealt with.

Thanks and sorry for the inconvenience
Jon

**Comment by likedustg** [comment]
Hi, jonathanleather 

Thank you for your response. The authorization scope seems doesn't matter. I tried both scope:hello and scope read:vat. 

GetAccessToken works well when I use API testing tool SOAPUI, but it doesn't work with the sample provided in curl. And in my own programming environment I got the same error.

**Comment by likedustg** [comment]
I solved the problem finally. The redirect URI must be the same in both authorization phase and gettoken phase.
