### ISSUE TITLE
Submitting VAT Return - Error 400 (INVALID_MONETARY_AMOUNT)

### ISSUE THREAD

**Issue by LukeHirst** [hmrc/vat-api#185]
I am not sure if I am missing something. However I am receiving a status code of 400 (bad request) when when trying to submit a vat return.

Below is the user I have created from the create-user api to test with:

{  
   "userId":"430875892226",
   "password":"YnwKkw1rk2ub",
   "userFullName":"Adrian Morgan",
   "emailAddress":"adrian.morgan@example.com",
   "organisationDetails":{  
      "name":"Company 6MS73F",
      "address":{  
         "line1":"4 Downing Street",
         "line2":"Glasgow",
         "postcode":"TS19 1PA"
      }
   },
   "vrn":"666316597"
}

Below is the JSON Content added to the request:

{  
   "periodKey":"#006",
   "vatDueSales":3000.38,
   "vatDueAcquisitions":2145.85,
   "totalVatDue":5146.23,
   "vatReclaimedCurrPeriod":4398.27,
   "netVatDue":747.96,
   "totalValueSalesExVAT":4321.11,
   "totalValuePurchasesExVAT":1743.12,
   "totalValueGoodsSuppliedExVAT":2110.13,
   "totalAcquisitionsExVAT":4360.14,
   "finalised":true
}

The content of the response is below:

{  
   "code":"INVALID_REQUEST",
   "message":"Invalid request",
   "errors":[  
      {  
         "code":"INVALID_MONETARY_AMOUNT",
         "message":"amount should be a monetary value (to 2 decimal places), between -9,999,999,999,999.00 and 9,999,999,999,999.00",
         "path":"/totalAcquisitionsExVAT"
      },
      {  
         "code":"INVALID_MONETARY_AMOUNT",
         "message":"amount should be a monetary value (to 2 decimal places), between -9,999,999,999,999.00 and 9,999,999,999,999.00",
         "path":"/totalValueGoodsSuppliedExVAT"
      },
      {  
         "code":"INVALID_MONETARY_AMOUNT",
         "message":"amount should be a monetary value (to 2 decimal places), between -9,999,999,999,999.00 and 9,999,999,999,999.00",
         "path":"/totalValuePurchasesExVAT"
      },
      {  
         "code":"INVALID_MONETARY_AMOUNT",
         "message":"amount should be a monetary value (to 2 decimal places), between -9,999,999,999,999.00 and 9,999,999,999,999.00",
         "path":"/totalValueSalesExVAT"
      }
   ]
}

The errors being returned from the api are for all of figures that exclude VAT. It states that these figures should be entered to a value of 2 decimal places, for which you can see in the request content that they are.

If I changed the values to not have any decimal places (e.g. set  totalValueSalesExVAT from 4321.11 to 4321.00) than the submission is successful. This behaviour seems contrary to the error messages that I had received previously.

Therefore my question is that should the following fields: 

- totValueSalesExtVAT

- totalValueGoodsSuppliedExVAT

- totalValuePurchasesExVAT

- totalAcquisitionsExVAT

Be entered to a value of 2 decimal places or not at all? 

Any help on this would be appreciated.

**Comment by jacobbrownlow** [comment]
Hi Luke

Each of the fields you've mentioned have the following descriptions in the documentation "The value must be between -9999999999999 and 9999999999999". The example request body also shows them without decimals.

Technically they do except decimals, as long as they are .0 or .00 - I recognise this isn't clear from the documentation but we chose to not show the decimals to try and avoid confusion.

As for the error response, this is something I can suggest as an improvement because I can see why it isn't very clear. I'll raise this with the development team.

Regards, Jacob

**Comment by LukeHirst** [comment]
Hello Jacob,

Thank you for the quick and comprehensive reply. 

I did look at the documentation for these fields but did not know whether it was the error message returned that was incorrect or whether it was the documentation itself.

Is there are any reason why these 4 fields do not allow you to specify a pence value? Are these values monetary and isn't there a possibility that users could be entering a pence value for them?

Cheers, Luke

**Comment by jacobbrownlow** [comment]
Hi Luke

To be completely honest I am not aware of the business reasons for why whole pounds are required. It was a requirement for us, so it may be that a back-end system doesn't deal with pence.

If you would like more information then please contact the Software Developers Support Team (SDST) on this email SDSTeam@hmrc.gsi.gov.uk. They should be able to provide more business related information.

Regards, Jacob
