### ISSUE TITLE
Change to VAT API to retrieve obligations returns 500 with new 'A' status option

### ISSUE THREAD

**Issue by paulvickery** [hmrc/vat-api#187]
We are today getting back a 400 response with message INVALID_STATUS from the /organisations/vat/{vrn}/obligations endpoint in the sandbox. We are not specifying the status, as we want all obligations. The documentation now says that the status is required, and should be set to 'A' for all.

We have encountered issues with this:

This is a change that - as far as I can see - we had no notification of, and breaks our application
Not specifying the status gives us the 400 as I've mentioned above
Specifying status=A returns a 500 INTERNAL_SERVER_ERROR
Note that specifying status as O or F gives a 200, and - in the sandbox - returns the stock response.

What I am not currently sure of is whether the change is also in production.

This is causing us a big problem, as we have pilot users trying to use our application.

**Comment by jacobbrownlow** [comment]
Hi Paul

Apologies for this, the wrong version was deployed to ET earlier today. This has now been resolved.

Regards, Jacob

**Comment by paulvickery** [comment]
Thanks - I can now see that it is behaving as we expected :)
