### ISSUE TITLE
Developing for Winforms

### ISSUE THREAD

**Issue by jjppnn** [hmrc/vat-api#190]
Hi there,

I have been advised to post my query on this forum by the folks at sdteam@hm....

Anyway, I have a bespoke winforms application written in C#. The client has instructed myself into bridging the existing application with this API for vat returns. 

So my first questions are....

Is there an API for Winforms or is it just available for browser based applications? And if not, will there be one made available ?

Assuming an answer of 'no' to both of the above, what would be my best option moving forward with this ? I have no experience with JSON and REST and all that web based interfaces. 

Will my client be compelled to submit their online vat returns even if there existing business applications are Winform based ?

Thanks,

J

**Comment by macgrewal** [comment]
Hi @jjppnn, the VAT API work over REST+JSON. Help and guidance on how to interact with HMRC APIs is documented at https://developer.service.hmrc.gov.uk/api-documentation.

As of 6th April 2019 all MTD VAT users will need to submit their returns via software.

**Comment by kaiukdevelopment** [comment]
Hi @jjppnn, I am currently developing in Winforms using the WebBrowser control for the Oauth and the System.Net.Http.HttpClient() that you can get from nuget. (If you are using .Net below 4.5 then it is called Microsoft.Net.Http but uses the same namespace)

**Comment by macgrewal** [comment]
Hi @jjppnn, as @kaiukdevelopment mentioned authorisation via OAuth is possible from a WinForms app using the NuGet package or Microsoft.Net.Http for Pre .NET 4.5 solutions.

I will close this issue but feel free to re-open if you need further assistance.

Regards,

mac
