### ISSUE TITLE
Error on totalValuePurchasesExVAT figure

### ISSUE THREAD

**Issue by kaiukdevelopment** [hmrc/vat-api#192]
I am sending down 38938.83 to the totalValuePurchasesExVAT amount with an amount of 6785.77 in the vatReclaimedCurrPeriod. The API is giving me the following error:

{"code":"INVALID_REQUEST","message":"Invalid request","errors":[{"code":"INVALID_MONETARY_AMOUNT","message":"amount should be a monetary value (to 2 decimal places), between -9,999,999,999,999.00 and 9,999,999,999,999.00","path":"/totalValuePurchasesExVAT"}]}

If I send down 3000 and 600 respectively it allows it through, it seems to be saying that vatReclaimedCurrPeriod must be 20% of totalValuePurchasesExVAT, but I thought that Box 7 should include all purchases whether they are reduced rate or zero rated.

**Comment by jonathanleather** [comment]
Hi @kaiukdevelopment 

totalValuePurchasesExVAT  - only allows whole numbers.
You can pass this value down as 38938 or 38938.00

The documentation states: 
Total value of purchases and all other inputs excluding any VAT (including exempt purchases). This corresponds to box 7 on the VAT Return form. The value must be between -9999999999999 and 9999999999999.

For our own information - would you say the error message is misleading? or that the documentation needs tweaking? or both? Your thoughts on this will allow us to make improvements going forward.

Cheers
Jon

**Comment by LukeHirst** [comment]
Hello Jon, 

I have mentioned this before in a now closed issue:  [](https://github.com/hmrc/vat-api/issues/185)

The error message is most definitely misleading and contradicts the documentation provided. I'm still unsure why all the excluded VAT Values do not allow you to enter pence however.

**Comment by LukeHirst** [comment]
Hello Jon, 

I have mentioned this before in a now closed issue https://github.com/hmrc/vat-api/issues/185

The error message directly contradicts the documentation provided, however I'm still not sure why all the values that exclude VAT don't allow you to input pence.

**Comment by jonathanleather** [comment]
Hey @LukeHirst 

As mentioned in that ticket, it is a backend requirement to not allow pence. I can ask the question as to why but this is something that this team have little control over unfortunately.

I'll chase the ticket raised on the error message by @jacobbrownlow and see if we can remove the ambiguity. If you have any suggestions on what you would expect to see in the documentation then do let me know.

cheers
Jon

**Comment by kaiukdevelopment** [comment]
Removing the .00 from the error message would make it more clear

**Comment by LukeHirst** [comment]
Hello @jonathanleather 

Thank you for the quick reply and following up on this.

As @kaiukdevelopment has said removing the .00 from the error message would make it clearer, either that or it would be beneficial to say that these monetary values only allow .00 if specified to 2 decimal places.

As far as the documentation goes I think it should explicit state that these figures do not allow pence unless .00 is entered.

Regards, Luke

**Comment by LukeHirst** [comment]
Hello @jonathanleather 

Thank you for the quick reply and following up on this.

The message for the error says the following:
"amount should be a monetary value (to 2 decimal places), between -9,999,999,999,999.00 and 9,999,999,999,999.00"

Saying that we should enter a monetary value between these 2 numbers implies that 56.21 is valid when is not, you can only ever enter .00 for these values. 

For me the error message and the documentation either need to explicitly state that these values can only be keyed in to 2 decimal places if the value is .00 or not mention anything about decimal places at all and state that only whole numbers can be entered to avoid confusion in the future.

Regards,
Luke

**Comment by jonathanleather** [comment]
Hey @LukeHirst 

I'll pass your comments onto our Content Designer and we shall get this sorted for you.

Thank you both for the suggestions and feedback it really does help. 
If you find anything else along the way, don't hesitate to come back to us.

Cheers
Jon

**Comment by ma3574** [comment]
The error messages /documentation have been fixed
