### ISSUE TITLE
Obligation Status

### ISSUE THREAD

**Issue by kaiukdevelopment** [hmrc/vat-api#193]
When is the Obligation status meant to change? Is it after a VAT Return has been submitted or after the due date has passed?
At the moment all the future Obligations have the O status whether I have submitted a VAT Return or not.

**Comment by jonathanleather** [comment]
Hi @kaiukdevelopment 

_When is the Obligation status meant to change?_ - Once a Vat Return has been submitted the corresponding obligation / status will update to fulfilled.  

In Sandbox: The Obligations endpoint is stateless and only returns canned responses. These responses are currently under review and will soon change.

Cheers
Jon

**Comment by kaiukdevelopment** [comment]
Thanks for the clarification
