### ISSUE TITLE
Payments/Liabilities

### ISSUE THREAD

**Issue by kaiukdevelopment** [hmrc/vat-api#194]
I am trying to get all the payments and liabilities for the current year so I am calling
https://test-api.service.hmrc.gov.uk/organisations/vat/666576270/liabilities?from=2018-01-01&to=2018-12-31
but every time I am getting the error 
{"statusCode":400,"message":"DATE_TO_INVALID"}
is there a maximum date range that this can be run for.
The same happens on the payments with the same dates.

**Comment by MarkAKelly** [comment]
@kaiukdevelopment Payments and liabilities can't be called with a 'to' date that is in the future.

**Comment by kaiukdevelopment** [comment]
Makes sense, could that be added into the documentation?

**Comment by MarkAKelly** [comment]
I'll pass it on to our content designer, but yes more than likely it can.

**Comment by kaiukdevelopment** [comment]
Also how do I get the sandbox to return data for the payments and liabilities, it always returns with the error {"code":"NOT_FOUND","message":"The remote endpoint has indicated that no data can be found"}.

**Comment by MarkAKelly** [comment]
You will need to use the test headers documented in the test data section of the documentation, along with date ranges that fall within the dates mentioned.

**Comment by Comtass** [comment]
Do you have link with the test headers and things documented? that would be of great assistance to me at the moment

**Comment by MarkAKelly** [comment]
https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0#_retrieve-vat-liabilities_get_accordion

**Comment by kaiukdevelopment** [comment]
I missed that section in the documentation. It works now, thank you.

**Comment by Hollister** [comment]
It is not clear in the documentation, will trying to use a future date when getting liabilities and payments fail with an error even when using the live api?

**Comment by narendravijayarao** [comment]
Hi @Hollister,

Yes, it will fail. As per the documentation, the "to" date description says:

"Liabilities to return up to date, the maximum 'to' date is the current date"

Thanks...
