### ISSUE TITLE
Missing field?

### ISSUE THREAD

**Issue by MKoppJones** [hmrc/vat-api#195]
Hi,

We are not sure if we are missing the point or if there is a missing field.

Recently a document was released 
https://www.gov.uk/government/publications/vat-notice-70022-making-tax-digital-for-vat/vat-notice-70022-making-tax-digital-for-vat#digital-record-keeping

In section 3.3.5 (Summary data) mentions 

> the total tax you are required to pay on behalf of your supplier under a reverse charge procedure

but we can't seem to match up a field for this in the vat return submissions.

**Comment by jacobbrownlow** [comment]
Hi @MKoppJones 

Unfortunately this channel is only for technical questions, and we don't have the information to answer this question. Could you please send your question to SDSTeam@hmrc.gsi.gov.uk and they should be able to help.

Sorry for the inconvenience
Jacob
