### ISSUE TITLE
Post VAT Return not working

### ISSUE THREAD

**Issue by Comtass** [hmrc/vat-api#197]
I have been trying to get the Post Vat return API to work.
I created the test user using the API, and as the Retrieve_VAT_Obligations works in the test scenario I am assuming that the VRN is correct. 
I have loaded it all into postman to show exactly what I am doing.
Have I missed something?

![image](https://user-images.githubusercontent.com/39489338/42765313-aa70649e-890f-11e8-94af-688553535caf.png)

![image](https://user-images.githubusercontent.com/39489338/42765370-c85079f4-890f-11e8-88fd-99fb92895d94.png)

**Comment by jacobbrownlow** [comment]
Hi Comtass

I'll ask the team if using form-data method is invalid, but when I tried it I got a 503
```json
{
    "code": "SERVER_ERROR",
    "message": "Service unavailable"
}
```

I can confirm that using raw JSON works though:
![image](https://user-images.githubusercontent.com/35334115/42766318-14086a26-8912-11e8-8a60-d8d305634fae.png)

Regards, Jacob

**Comment by Comtass** [comment]
The 503 error is exactly what I get when I tried if from my app. I only set up Postman so that you could try it in the same way as I did. This is of some interest though, but I'm unsure how I could post ray Json in my app. I would much appreciate it if you could check about form-data.
Best regards,
Gordon

**Comment by Comtass** [comment]
With that information I was able to resolve the problem and it is now working.
Thanks for your help

Gordon
