### ISSUE TITLE
Why not deal exclusively in pence to avoid rounding?

### ISSUE THREAD

**Issue by kabadisha** [hmrc/vat-api#198]
Have been reviewing this spec in preparation for trying to integrate our business with it - after all this will supposedly be mandatory in less than a year!

Was wondering why you have a load of complexity added for handling decimals (and presumably a load of tedious code behind the scenes to deal with rounding) when the spec could just require all values to be submitted in pence?

For example, for **£10.21** instead of submitting **10.21** one would submit **1021**. This would totally remove the need for the complexity of specifying decimal places and would also avoid rounding issues that are sure to arise if you try to handle this as decimals.

Having built large scale systems for many years, using decimals is a great way to introduce calculation bugs. In my experience, dealing with whole numbers makes it a lot less likely that someone (including the consumers of your API) will introduce a rounding error by mistake, especially as you guys are using Scala and so will have to fiddle about converting to and from BigDecimal like [this](https://stackoverflow.com/questions/11106886/scala-doubles-and-precision).

https://github.com/hmrc/vat-api/blob/cfc230c777da406a0b6f14ff3e9bf2ee7c7ae0f4/public/api/conf/1.0/schemas/VatReturnDeclaration.json#L71

**Comment by kabadisha** [comment]
No worries, glad to help.

Any idea when some official details of this API might be released? I can't find anything specific in all the published info I have found.
Large businesses like ours with bespoke/old accounting systems will be hard pushed to implement this API by April if we don't have the official API specs soon...

Cheers

**Comment by macgrewal** [comment]
The official spec is already available on the [Developer Hub](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0).

However, if you were referring to a spec reflecting a change from ponds and pence to pence only, this would need to be agreed by the project first and then follow the correct process. If agreed, details of the change would be reflected in the documentation on the Developer Hub and comms would be released via SDST.

**Comment by kabadisha** [comment]
I meant the official spec as it is, not with my suggestion :-)

However, that URL you sent me gives me a 404 page and I can't find that API browsing the docs myself. Maybe it hasn't been published to the public yet?

**Comment by macgrewal** [comment]
Hi @kabadisha, please contact SDST via email on SDSTeam@hmrc.gsi.gov.uk requesting to be added to the MTD VAT API whitelist. Once added to the whitelist you should be able to see the documentation.

**Comment by kabadisha** [comment]
@macgrewal Awesome, thanks - I will do that :-)

In the mean time, I figured out that I could generate the docs from the .raml file as a workaround ;-)

**Comment by macgrewal** [comment]
Cool, though I should mention that although we try and keep master and the docs published in sync, it can sometimes be a few commits ahead of the what's deployed.

Having said that we hope to have continuous deployment implemented soon so the caveat mentioned above won't matter. 🤞
