### ISSUE TITLE
Secret key in public source control

### ISSUE THREAD

**Issue by kabadisha** [hmrc/vat-api#199]
It seems that your play framework secret key is hardcoded in source control. This may be on your todo list already and this might not be a production key, but I thought I should make sure someone noticed just in case.

There are several ways to avoid this. Some recommendations can be found [here](https://www.playframework.com/documentation/2.6.x/ApplicationSecret#Best-practices).

https://github.com/hmrc/vat-api/blob/cfc230c777da406a0b6f14ff3e9bf2ee7c7ae0f4/conf/application.conf#L43

**Comment by macgrewal** [comment]
Hi @kabadisha, the key in `application.conf` is simply a generated value and does not reflect the key used in any of our environments.

**Comment by kabadisha** [comment]
Good to know :-)
