### ISSUE TITLE
'Submit VAT return for period' response documentation

### ISSUE THREAD

**Issue by nnotsofun** [hmrc/vat-api#20]
Hi,

I've been testing out the VAT end points in sandbox and found the response for 'Submit VAT return for period' is not documented and so have a few questions:

* What do the properties mean? i.e. formBundleNumber, chargeRefNumber
```
{
    "processingDate": "2018-01-17T23:06:59.035+0000",
    "paymentIndicator": "DD",
    "formBundleNumber": "395256427162",
    "chargeRefNumber": "R4t58D5SlG5vxk3X"
}
```
* Does a successful response change the status in the obligations list for that period from O to F? If not, is there a plan to add an additional status like 'Processing'?

Thanks!

Nick

EDITED to make second point clearer

**Comment by hicnar** [comment]
Thank you for your query. 
The processingDate and paymentIndicator (DD - Direct Debit, BANK - bank account details) are pretty obvious. 
Getting more detailed info on the remaining ones.

**Comment by nnotsofun** [comment]
Hi @hicnar, 

Just noticed the last [commit](https://github.com/hmrc/vat-api/commit/e09cf61306344264df966fd82cbe88ac6f0700ed) into the repo for the updated obligations list example. Based on that and re-reading the [documentation](https://test-developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0#_retrieve-vat-obligations_get_accordion), it seems a successful submission should change the status from O to F. Can you please confirm if that is immediate? i.e. if i get the obligations immediately after a successful submission, that period will have a received date and status of F? 

Thanks,

Nick

**Comment by hicnar** [comment]
Hi @nnotsofun 

We have some more clarification on your question

Q. Does a successful response change the status in the obligations list for that period from O to F? If not, is there a plan to add an additional status like 'Processing'? 

A. yes, as part of successful message processing ETMP will fulfil obligation

Hope that helps!
K.

**Comment by nnotsofun** [comment]
Thanks @hicnar
