### ISSUE TITLE
While fetching VAT obligations, am I right in thinking we cant put a future date?

### ISSUE THREAD

**Issue by SabVat** [hmrc/vat-api#201]

**Comment by narendravijayarao** [comment]
Hi,

For the VAT obligations the FROM_DATE can't be future date, but TO_DATE can be a future. As long as the date from <= today, then we'll return the current open obligation.

Thanks,
Naren

**Comment by macgrewal** [comment]
@SabVat hopefully @narendravijayarao has answered your query so I will close this issue. If you not please feel free to re-open it.
