### ISSUE TITLE
Sumitting VAT returns with multiple VRNs

### ISSUE THREAD

**Issue by skarvm** [hmrc/vat-api#206]
I am trying to handle two VAT Registration Numbers with a single app in the sandbox. Am able to fetch the obligations for the two VRNs - It returns same periodKeys but I guess it is the sandbox behaviour. But submitting VAT Return for one VRN also updates the other VRN - Is this a sandbox issue or multiple VRNs are not supported? As per the documentation (https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints - Section "Agents with multiple accounts")  we should be able to register multiple VRNs with a single app - Please let me know if it is not the case.

**Comment by jonathanleather** [comment]
Hi @skarvm 

We are unable to replicate the behaviour you are seeing.
I have tried 2 VRNs under the same application - and neither VRN is impacted by the other.

Are you attempting to test agents in the sandbox environment?

Cheers
Jon

**Comment by skarvm** [comment]
Hi @jonathanleather 
Yes, testing in the sandbox environment but not through an "agent" account - Just authorized an application with two different VRNs and submitting returns with the respective OAuth tokens as mentioned in the third point of the documentation section.

Could you please tell me on the test you had - was it using multiple OAuth tokens or through an agent account?

**Comment by jonathanleather** [comment]
@skarvm 

2 VRNs with separate OAuth / bearer tokens.
Can you elaborate on the testing scenario that you are trying to run?

Cheers
Jon

**Comment by skarvm** [comment]
Hi @jonathanleather
As per the documentation, below are the approaches we can have for multiple accounts, I am checking with the last option.


Agents with multiple accounts

Some agent organisations have more than one Government Gateway account, and their client relationships are spread across those accounts. There are a few ways to handle this:

    If the accounts belong to the same organisation in Government Gateway, the agent can manage client relationships themselves using the Government Gateway.
    If the accounts belong to different organisations (for example due to a merger), in some cases the agent can ask us to merge their accounts.
    Your application may hold multiple OAuth 2.0 access tokens for the agent, but must take care to use the right token for each client when calling our APIs. Using the wrong access token results in an HTTP status code of 401 (Unauthorized).

Below are the steps I followed:
1. Registered an application in sandbox
2. Created two test users with API
3. Followed OAuth steps to authorize the application with both users. This generates two pairs of access and refresh tokens.
4. Retrieved obligations for both VAT registrations by passing appropriate access token (There is nothing specific to the application to be passed in the GET request - just the access token in the Bearer header. )
5. Submitted returns for only one VAT registration number (Again, nothing specific to the application passed in POST request except the access token in Bearer header)
6. Retrieving obligations for both the VRNs now show both have been submitted (status=F)

**Comment by jonathanleather** [comment]
Hi @skarvm 

Testing with agents on the platform is not currently available in the sandbox.

Step 6 appears to be your problem.
The obligations endpoint returns canned responses - I believe the default response returns obligations with the first fulfilled. 

The test you should try to prove this is:  
1. Submit a vat return for both VRNs with the same periodKey. (differ the bodies slightly)
2. Using the GET VAT Return endpoint - retrieve the VAT submission with both VRNs. They should only return the ones that they submitted.

Cheers
Jon

**Comment by skarvm** [comment]
ah, thanks @jonathanleather 

I tried the Get VAT Return endpoint but getting 404 Not found for both VRNs. Are there any issues with this endpoint or am I missing something?
Request:

GET https://test-api.service.hmrc.gov.uk/organisations/vat/666001202/returns/18A1 HTTP/1.1
Authorization: Bearer ...
Accept: application/vnd.hmrc.1.0+json
Content-Type: application/json

**Comment by jonathanleather** [comment]
Hey @skarvm 

There are no reported issues with either endpoint.
Could you send me a screenshot or details of your submission, including the response returned? 

Cheers
Jon

**Comment by skarvm** [comment]
Hi @jonathanleather 
Just retried and no errors this time. The submissions are reflecting correctly against the VRNs.

Thanks a lot for your support.

**Comment by jonathanleather** [comment]
No worries - I'll close this issue.

If you have any further problems feel free to come back to us.

Cheers
Jon
