### ISSUE TITLE
VAT Obligation periods response

### ISSUE THREAD

**Issue by lukaszszczygiel-sage** [hmrc/vat-api#207]
We spotted that the responses for VAT Obligation has been change and we are now getting only periods for 2017.  Last time the response contains also the 2018 period, so it was more real case and we could include transactions for 2018 year. Could this be fixed and contain only periods for 2018?
Previously we get the Obligation like this and it was OK
"$results": {
   "headers": {
     "X-Correlationid": "5a7ad85f2c00000e006bcb7e"
   },
   "statusCode": 200,
   "payload": {
     "obligations": [
       {
         "start": "2018-01-01",
         "end": "2018-03-31",
         "due": "2018-04-30",
         "status": "F",
         "periodKey": "#001",
         "received": "2018-03-26"
       },{
         "start": "2018-04-01",
         "end": "2018-06-30",
         "due": "2018-07-30",
         "status": "O",
         "periodKey": "#002"
       },{
         "start": "2018-07-01",
         "end": "2018-09-30",
         "due": "2018-10-30",
         "status": "O",
         "periodKey": "#003"
       },{
         "start": "2018-10-01",
         "end": "2018-12-31",
         "due": "2019-01-31",
         "status": "O",
         "periodKey": "#004"
       }]}

**Comment by LukeHirst** [comment]
I am also getting this issue as well. I have sent a web request with the following 'from' and 'to' dates:

https://test-api.service.hmrc.gov.uk/organisations/vat/<VRN>/obligations?from=2018-01-01&to=2018-12-31

and the following response is always returned:

{  
   "obligations":[  
      {  
         "start":"2017-01-01",
         "end":"2017-03-31",
         "due":"2017-05-07",
         "status":"F",
         "periodKey":"18A1",
         "received":"2017-05-06"
      },
      {  
         "start":"2017-04-01",
         "end":"2017-06-30",
         "due":"2017-08-07",
         "status":"O",
         "periodKey":"18A2"
      }
   ]
}

Any update on this would be appreciated.

Regards,
Luke

**Comment by jonathanleather** [comment]
Hi @lukaszszczygiel-sage @LukeHirst 

@lukaszszczygiel-sage The previous testing scenarios for this endpoint dynamically created the obligations based on the date parameters entered. This in turn allowed the possibility of creating unrealistic data and dates / obligations which weren't strictly live like. We have revised the test data to be consistent with current processes (you will only be able to see up to the current period's open obligation). This approach also made it difficult to simulate a journey. 

@LukeHirst We received a lot of feedback from vendors saying that the old solution wasn't working for them. This new approach gives you a lot more options providing you pass in the appropriate Gov-Test-Scenario header. These headers can be found in the **Test Data** section of the documentation. The data returned is based on the header passed, not the dates.

The one draw back with this approach is that all the data is completely canned and no longer dynamically generated- so even if we changed the dates they would eventually all be in the past. 

Cheers
Jon

**Comment by RobertMarczycki** [comment]
Hi,
There are at least a few issues with this approach:
* period date range returned by API is used by applications to select data for submission; as the service returns data for 2017 only it's not longer possible to use this information to filter data or to present a proper form, which makes testing awkward (and might require changes to application code)
* as API returns static data there's no way to test whether query parameters (date range) work correctly
* embedding Gov-Test-Scenario headers requires - again - changes to the application code, not a good pattern
* silent introduction of breaking changes to the HMRC Sandbox environment destroys both automation and manual testing...

I don't believe effort related to returning dynamic data sets is so huge so may I suggest extending the Sandbox with this behaviour - especially that there's no other way to test HMRC API (no test users in Production environment).

Thanks,
Robert

**Comment by MarkAKelly** [comment]
Hi @RobertMarczycki,

Unfortunately, as we have mentioned previously in this channel, and in the numerous hackdays we have held with consumers of our API's, it is simply not possible for us to maintain a stateful test environment for use in the sandbox environment.

The suites of services that sit behind our API run in to the 100's, and to maintain stateful, simulated responses for all scenarios is a situation we can't commit to at present (as is our wish, as well as yours).  The compromise we agreed on was to offer more expansive, and most importantly valid, and realistic responses in the form of extended test scenarios.  

By all means we will take on board your feedback, and I'll pass your comments on to the relevant members of the team and at the platform level to ensure that your we continue to try and deliver what developers are asking for.
