### ISSUE TITLE
Testing in sandbox using Gov-Test-Scenario. Seems to ignore VRN_INVALID on submission of VAT

### ISSUE THREAD

**Issue by mwaters** [hmrc/vat-api#208]
Hi there,

I've been submitting VAT returns via the endpoint /organisations/vat/{vrn}/returns. According to the documentation I should be able to simulate one of five failures using the Gov-Test-Scenario header.

I can of course send an invalid VRN myself, but I thought I'd set the header to INVALID_VRN instead. The process completed normally without error, giving a 201 status. The request and response objects are included in the attached file.

Do these headers not work or am I doing something wrong?

[test_example.txt](https://github.com/hmrc/vat-api/files/2228237/test_example.txt)

**Comment by jonathanleather** [comment]
Hey @mwaters 

By the looks of your test_example you are using the error code (VRN_INVALID) for the Gov-Test-Scenario.
The Gov-Test-Scenario is actually INVALID_VRN as you have mentioned above.

Try switching it round and let me know if it works for you.

Cheers
Jon

**Comment by mwaters** [comment]
I'll try it.

I've been going by the documentation on https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0#_submit-vat-return-for-period_post_accordion.

Under Test Data I should be sending the header as "INVALID_VRN", but I see under the Error Scenarios there's "VRN_INVALID". I wonder if that's a typo somewhere?

Mathew

**Comment by mwaters** [comment]
No, it still submitted the VAT successfully, even with the header switched to VRN_INVALID.

```
$request = new MTDRequest("/organisations/vat/$vatRegistrationNumber/returns", 'POST');
$request->addHeader('Content-Type', 'application/json');
$request->addHeader('Gov-Test-Scenario', 'VRN_INVALID');
```

**Comment by mwaters** [comment]
Oh! My original script was backwards. My apologies, I think I've only tried VRN_INVALID.

I've re-tested using INVALID_VRN and it's giving the expected error. Thanks, and sorry for wasting your time.

Mathew
