### ISSUE TITLE
processingDate timezone

### ISSUE THREAD

**Issue by MKoppJones** [hmrc/vat-api#209]
The documentation for the VAT API shows that a timezone is returned with processingDate.

In reality, we are yet to actually see a timezone returned. What timezone are these timestamps? Will they always be in the same timezone (so we can convert to the timezone we need)?

Currently, all our processingDate timestamps are an hour out.

I am assuming it is UTC, but would like to check.

**Comment by MKoppJones** [comment]
Scrap the above.

I have noticed that the timezone is in the ISO8601 format, but the documentation doesn't explicitly state thing against the field.

Can this be update?

**Comment by MKoppJones** [comment]
Also, could confirm that is in fact ISO8601 and will always be UTC+0 as a timezone?

**Comment by narendravijayarao** [comment]
Hi,

Yes the ISO8601 DateTime notations will be in UTC+0 timezone.

Thanks,
Naren.

**Comment by MKoppJones** [comment]
Brilliant, thank you
