### ISSUE TITLE
Obligation Keys not mandatory

### ISSUE THREAD

**Issue by mathiasbanda** [hmrc/vat-api#210]
By some chance I have noticed posting a vat return on the sandbox doesn't require the obligation key. Granted I will have to get the keys to find out where it actually went but one assumes it was posted to the right period (the current open one). 

Should this be a bug or not?

**Comment by MarkAKelly** [comment]
The body for a VAT Return submission requires a period key to be accepted.  As we have mentioned previously the behaviour in sandbox is not fully stateful - so in this environment this doesn't have to be a period key that matches one in the list of obligations returned.

In reality, a VAT submission must always be made against a valid period key, that is a period key denoting any open period for that VRN.
