### ISSUE TITLE
Hello World - The remote server returned an error: (406) Not Acceptable. 

### ISSUE THREAD

**Issue by jjppnn** [hmrc/vat-api#212]
Hi folks,

I am trying out the first tutorial from https://developer.service.hmrc.gov.uk/api-documentation/docs/tutorials.

I am getting an error message "The remote server returned an error: (406) Not Acceptable. " when I run my code from a Windows Form.

I am simply trying to return the JSON response and display it in a WinForms textbox.

Here is my code:

`           string url = "https://test-api.service.hmrc.gov.uk/hello/world";

            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(url);
            request.Accept = "application / vnd.hmrc.1.0 + json";
            request.Method = "GET";

            using (HttpWebResponse response = (HttpWebResponse)request.GetResponse()) // **Error here
            {

                if (response.StatusCode != HttpStatusCode.OK)
                {
                    throw new Exception("Error code" + response.StatusCode);
                }

                // Process the response stream
                using (Stream responseStream = response.GetResponseStream())
                {
                    if (responseStream != null)
                    {
                        using (StreamReader reader = new StreamReader(responseStream))
                        {

                            txtResponse.Text = reader.ReadToEnd();

                        } // End of response Stream

                    }

                } // End of 

            }`

Any ideas what might be causing this ??

**Comment by obeea** [comment]
Not sure if it makes any difference, but try removing the spaces from the accept string i.e. 
"application/vnd.hmrc.1.0+json"

**Comment by jjppnn** [comment]
Hi obeea,

That solved it.

Thanks,
J
