### ISSUE TITLE
Tutorial # 2. Using Server Token = The remote server returned an error: (403) Forbidden.

### ISSUE THREAD

**Issue by jjppnn** [hmrc/vat-api#213]
Hi folks,

Im trying to do the 2nd tutorial. I have my server token but when I add it to the header, I am getting the error message - "The remote server returned an error: (403) Forbidden."

URL https://test-api.service.hmrc.gov.uk/hello/application

Here is my code. I think I am adding the header correctly.
`public string makeRequest(string authToken)
{
            string strReponseValue = string.Empty;

            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(endPoint);
            request.Accept = "application/vnd.hmrc.1.0+json";

            if (authToken.Length > 0)
            {
                request.Headers.Add("Authorization", "Bearer " + authToken);
            }

            request.Method = httpMethod.ToString();

            using (HttpWebResponse response = (HttpWebResponse)request.GetResponse()) // error here
            {

                if (response.StatusCode != HttpStatusCode.OK)
                {
                    throw new Exception("Error code" + response.StatusCode);
                }

                // Process the response stream
                using (Stream responseStream = response.GetResponseStream())
                {
                    if (responseStream != null)
                    {
                        using (StreamReader reader = new StreamReader(responseStream))
                        {
                            strReponseValue = reader.ReadToEnd();
                        } // End of StreamReader
                    }
                } // End of Response Stream
            }

            return strReponseValue;

        }
`

**Comment by markogrady** [comment]
I had the same issue the other day. I had to create a test user via the API
rather than the Web interface.

**Comment by macgrewal** [comment]
Hi @jjppnn,

Have you subscribed to the Hello World API? To confirm 

1. Go to https://developer.service.hmrc.gov.uk/developer/applications and select your application
2. From the menu select the 'Manage API subscriptions' item
3. Expand the 'Hello World' API and select the 'On' option
4. Retry running your code. 🤞

**Comment by jjppnn** [comment]
Working now.
Thanks,
J
