### ISSUE TITLE
Local Testing Setup

### ISSUE THREAD

**Issue by CapraGenus** [hmrc/vat-api#214]
I am looking to setup a local testing system for the VAT API's so we can test with our product, are you able to offer any instructions on how we can setup this?

Tried to follow what I know and also research how I can do this, but can't for the life of me get it all to run correctly.

**Comment by AbsoluteAccounting1** [comment]
Following as I have the same question.

**Comment by jacobbrownlow** [comment]
Hi @CapraGenus @AbsoluteAccounting1 

We can't advise you how to develop your software, but you will likely need to stub out our services to test locally. We do not offer any solutions for how to do this.

The sandbox (external test) environment is for testing integration with our services, but we try to provide enough test scenarios to give a feel for how the system will behave. We can advise how to setup users in sandbox if this is an issue?

Regards, Jacob

**Comment by CapraGenus** [comment]
I wasn't looking for advice on developing with our software, just want a general idea and guide on how to spin up a copy of what you have here on GitHub, I see various repos come with basic instructions on tests and such but can never get any of them to work.

Basically just wanted a simple small guide on how to get these API's up and running in a state where I can ping them with our software for testing purposes.

The HMRC sandbox is all well and good but for testing purposes, we would really like full control.

I hope that makes sense

**Comment by jacobbrownlow** [comment]
Hi @CapraGenus 

To run the services locally (as we do during development) you would need to be able to spin up various private repos, for example authentication related services. We can't provide this functionality for security reasons, so even if you were to spin up the vat-api locally, it wouldn't work without stubbing out numerous other dependent services.

I can only suggest the approach undertaken by all services on the HMRC Tax Platform (which is made up of hundreds of interdependent services), and that is to mock out our service to give you full control on what your software interacts with.

Regards, Jacob
