### ISSUE TITLE
OAuth2 class for .NET

### ISSUE THREAD

**Issue by jjppnn** [hmrc/vat-api#215]
Can anyone point me in the right direction for handling the OAuth2 for .NET ?

I have managed to get the Tutorials 1 & 2 up and running but am struggling with the 3rd.

I have tried googling it all the best explained examples are non .NET. And I would rather avoid having to learn a new language if possible, and stick with .NET WinForms with C#.

Is there an equivalent JAVA OAuthClientRequest class in .NET that I could make use of ?

Thanks,

J

**Comment by markogrady** [comment]
I just use a mvc controller to handle the the process and host it in a managed Azure/AWS instance.

I would avoid handling your auth on a winform project because it means storing your client secret which means it could probably be reverse engineered to steal your credentials.

Just use a web browser control in your winform app to interact with your mvc app

**Comment by jjppnn** [comment]
Do you use a specific .NET class for handling the OAuth 2 protocol within your controller?

Im not familiar with using Azure or AWS (or MVC for that matter) and would ideally prefer to keep everything inside a WinForms Project. But it would appear there is very little support for this in .NET. I did do some Java when at university but would rather avoid going back to it if possible.

Any other suggestions ??

Thanks,
J

**Comment by obeea** [comment]
As I see it, the OAuth2 protocol is just the process of requesting an authorization code, then exchanging it for an access token.
It seems you have the basics working in .Net anyway, so you just need another two request as per the docs
1) oauth/authorize - passing client_id and server token (in header) and redirect uri.  If all goes well, the redirect will pass you an authcode in the param (make sure redirect uri has been added in the developer portal for your application)
2) oauth/token - (POST) where 'code=authcode', plus client_id etc. as per docs, the response from this should give you an Access Token, Refresh Token and expiry.

The access token can then be used to call the relevant API's.

**Comment by jjppnn** [comment]
Thanks for input everyone.

I have managed to get my token (at the end of the URL from the redirect.

However, when I try and use it ....
`
public string makeRequest(string authToken)
        {
            string strReponseValue = string.Empty;
           // endPoint = "https://test-api.service.hmrc.gov.uk/hello/user"

            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(endPoint);
            
            request.Accept = "application/vnd.hmrc.1.0+json";

            if (authToken.Length > 0)
            {
                request.Headers.Add("Authorization", "Bearer " + authToken);
            }

            request.Method = httpMethod.ToString();  // GET
            HttpWebResponse response = null;
            try
            {
                response = (HttpWebResponse)request.GetResponse();`  // Error here
             }
  }

I get an error message. The remote server returned an error: 401  (Unauthorized)

**Comment by obeea** [comment]
Can you confirm you have received an authcode using the endpoint oauth/authorize, and then exchanged it using oauth/token?

I also noticed your endPoint variable is commented out...

**Comment by jjppnn** [comment]
Hi obeea,

Yes, I have received my authorisation code. Then I exchanged it for token. And yes, the token resembles the one you have shown.

Is is the same endpoint as the one commented out. It is already defined before I make call to makeRequest function...

 ```
RestClient rClient = new RestClient();
 rClient.endPoint = "https://test-api.service.hmrc.gov.uk/hello/user";

string strResponse = string.Empty;
strResponse = rClient.makeRequest(_accessToken);
```

I just dont understand why I am getting the error. Everything looks correct ??
J

**Comment by MKoppJones** [comment]
@jjppnn did you generate your test details using the Create Test User API with the MTD service?

I found that until I did that, I couldn't use any of the VAT API stuff

https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/api-platform-test-user/1.0

**Comment by obeea** [comment]
Yes good point, it only works if you create the user via the API, so maybe that is the problem.

**Comment by jjppnn** [comment]
Hi MKoppJones,

Yes, I created a test user (recieved the ID and password) and used it to log into the HMRC website to grant permission for my application. Then I got the access token.

J

**Comment by obeea** [comment]
Again just to clarify, you created the test user through the 'create-test-user/organisations' endpoint and not through the website?

**Comment by jjppnn** [comment]
I went to https://developer.service.hmrc.gov.uk/api-documentation
I then clicked on Create Test User. I then am given a user ID and a user password. This is what I am using to log into the HMRC website so I can then grant the permission for the app.

Is this the wrong way ??
J

**Comment by obeea** [comment]
That’s right, unfortunately this doesn’t work, you have to create the user via the api as mentioned earlier.

**Comment by jjppnn** [comment]
Hi, thanks again for your help with this. Much appreciated

I cant seem to find the URL for returning a  json response with a test clientID and password.

The on-line help says "/create-test-user/individuals" I tried  "https://test-api.service.hmrc.gov.uk/create-test-user/individual" but got resource not found (error 401).

Any thoughts ??

J

**Comment by jjppnn** [comment]
OK,
I am setting my endpoint to https://test-api.service.hmrc.gov.uk/create-test-user/individuals. This returns a user in json format. I now have the user ID and password.

I now go to https://test-api.service.hmrc.gov.uk/oauth/authorize. I click continue, enter the in the user ID and password given to me from the json. I then grant permission for my application. I am then redirected back to main redirect. The URL is now "https://www.lhdlimited.co.uk/?code=12345678901234567890123456789012" ( A 32 digit code). I assume this is the access token.

My response now has an access token, refresh token ("2eb7429ad629ffa4555ad3b0972e5628", expires(date), state (null).

I now set my end point to https://test-api.service.hmrc.gov.uk/hello/user

```
       string strReponseValue = string.Empty;
       HttpWebRequest request = (HttpWebRequest)WebRequest.Create(endPoint);
       request.Accept = "application/vnd.hmrc.1.0+json";
       request.ContentType = "application/json";

       if (authToken.Length > 0)
       {
           request.Headers.Add("Authorization", "Bearer " + authToken);
       }

       string json = "{\"serviceNames\": [\"national-insurance\",\"self-assessment\",\"mtd-income-tax\",\"customs-services\"]}";
       byte[] postBytes = Encoding.UTF8.GetBytes(json);

       request.Method = httpMethod.ToString(); // POST
       Stream requestStream = request.GetRequestStream();

       // now send it
       requestStream.Write(postBytes, 0, postBytes.Length);
       requestStream.Close();
       HttpWebResponse response = null;
       try
       {
          response = (HttpWebResponse)request.GetResponse(); // error here
       }
`


The error message is The remote server returned an error (404: not found)

Any ideas what could be wrong ?

Thanks J

**Comment by obeea** [comment]
I think you're getting confused with the endpoints, or trying to reuse code which doesn't quite work between endpoints.The endpoint 'hello/user' just accepts an accesstoken (provided by oauth/token), but in your example you seem to be trying to post user information, whereas it should simply return you an 'ok' message.I assume you also provided 'hello' as the scope when requesting the token?You only need to make a simple mistake and it will not work, so double check the docs to see if you are giving it exactly the right information for each endpoint.  

    On Saturday, 11 August 2018, 13:16:37 BST, jjppnn <notifications@github.com> wrote:  
 
 
OK,
I am setting my endpoint to https://test-api.service.hmrc.gov.uk/create-test-user/individuals. This returns a user in json format. I now have the user ID and password.

I now go to https://test-api.service.hmrc.gov.uk/oauth/authorize. I click continue, enter the in the user ID and password given to me from the json. I then grant permission for my application. I am then redirected back to main redirect. The URL is now "https://www.lhdlimited.co.uk/?code=12345678901234567890123456789012" ( A 32 digit code). I assume this is the access token.

My response now has an access token, refresh token ("2eb7429ad629ffa4555ad3b0972e5628", expires(date), state (null).

I now set my end point to https://test-api.service.hmrc.gov.uk/hello/user
       string strReponseValue = string.Empty;
       HttpWebRequest request = (HttpWebRequest)WebRequest.Create(endPoint);
       request.Accept = "application/vnd.hmrc.1.0+json";
       request.ContentType = "application/json";

       if (authToken.Length > 0)
       {
           request.Headers.Add("Authorization", "Bearer " + authToken);
       }

       string json = "{\"serviceNames\": [\"national-insurance\",\"self-assessment\",\"mtd-income-tax\",\"customs-services\"]}";
       byte[] postBytes = Encoding.UTF8.GetBytes(json);

       request.Method = httpMethod.ToString(); // POST
       Stream requestStream = request.GetRequestStream();

       // now send it
       requestStream.Write(postBytes, 0, postBytes.Length);
       requestStream.Close();
       HttpWebResponse response = null;
       try
       {
          response = (HttpWebResponse)request.GetResponse(); // error here
       }
`


The error message is The remote server returned an error (404: not found)

Any ideas what could be wrong ?

Thanks J



—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub, or mute the thread.

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Build software better, together

GitHub is where people build software. More than 28 million people use GitHub to discover, fork, and contribute ...
 |

 |

 |

**Comment by jjppnn** [comment]
Hi Obeea,

Yes, in between posting my last comment and you replying I managed to get the Hello User response. :)
so I just removed my last comment from the thread,

The problem was I was going through the whole process of creating a test user, getting the auth code, exchanging it for access token and so on with each attempt. Somewhere along the line something was going wrong. Still not sure where exactly.

But when I just tried the end point directly with a access code I had got previously received it worked fine. I think I was over complicating things trying to automate the whole procedure.

Thanks again for your help with this. Really is appreciated.

J

**Comment by jjppnn** [comment]
One thing I an still unsure about. 
The tutorials suggest that you need to exchange an authorisation code for an  access token,
But I can go into Postman and retrieve an access token without passing in a authorisation code.

J

**Comment by MKoppJones** [comment]
@jjppnn I would recommend ignoring the postman access token and start passing the authorisation code like part 3 at this link https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints

This will get you the refresh and access token you need. These will be valid for API usage.

**Comment by jjppnn** [comment]
Hi,

So will the access codes from postman not work with the API ? It worked OK when I used it for the "Hello User" in the Tutorial (Part 3)

I was intending using a library from ChilKat for acquiring the access code. Again like the access codes returned by postman, it appears to work very well. See link below. 

https://www.example-code.com/csharp/hmrc_oauth2_access_token.asp

I have used products from Chilkat them before and they work really well. I have not got as far yet as trying out the API for managing Vat returns yet. In fact that was going to be my next question. Where do I get a mock VRN from? I cant seem to find this in any of the documentation.

Thanks,

John

**Comment by MKoppJones** [comment]
@jjppnn 

I've never heard of Postman or Chilkat before, so I am only talking from my experience with HMRC APIs. If your Postman/Chilkat access token doesn't work for the MTD API, I would recommend following the details at https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints

You can get a VRN by using the https://test-api.service.hmrc.gov.uk/create-test-user/organisation endpoint. Make sure you use the serviceNames "mtd-vat". https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/api-platform-test-user/1.0#_create-a-test-user-which-is-an-organisation_post_accordion

**Comment by jjppnn** [comment]
I just used postman for testing outwith my application. But I was intending using the Chilkat library inside my actual program.

I will have a look at the links you gave me for acquiring a VRN and let you know how I get on.

Thanks for your help with this.

J

**Comment by obeea** [comment]
I’ve not seen Chilkat before, but not sure why you need it.
If you have the oauth part working, which it seems you have now, then calling the API’s is the easy bit.
Just trying to save you some money 😀

**Comment by jjppnn** [comment]
I thought I had it working but it's not. I must have used access tokens created by postman to get it to work which I cannot do in production,
Chilkat just makes things a lot easier. It can get access token and refresh them very easily.

Anyway, I have my access token...
{
  "access_token": "3aa03eef3b434a87e3a8be4633c2969",
  "refresh_token": "a09f618e6c8970f3e045b1be11a3b2e",
  "expires_in": 14400,
  "scope": "read:vat",
  "token_type": "bearer",
  "expires_on": "1534257290"
}
 I have set up my company and have the VRN number. 
I am trying to view my vat obligations.
I go to /organisations/vat/{vrn}/obligations passing in ?from2017-01-01%to2017-03-01

But I am getting The remote server returned an error: (403) Forbidden.

How do I link my client to my organisation ?

Thanks,
J

**Comment by MKoppJones** [comment]
Your steps should be

1. Generate test organisation
2. Authorise them to get an access and refresh token
3. To get the obligation, make the call to /organisations/vat/[VRN]/obligations?from=2017-01-01&to=2017-03-01

You don't need to link a client.
Remember an access token only lasts 4 hours.
The responses from the obligations back end are canned, read the documentation for the test scenarios you can perform.

**Comment by jjppnn** [comment]
Thanks, I got the data back..
{"obligations":[{"start":"2017-01-01","end":"2017-03-31","due":"2017-05-07","status":"F","periodKey":"18A1","received":"2017-05-06"},{"start":"2017-04-01","end":"2017-06-30","due":"2017-08-07","status":"O","periodKey":"18A2"}]}

I was logging in using my test user ID and password and NOT the ID and password from the organisation. What is the difference between a user and an organisation then? I just assumed a user acted on behalf of the organisation for submitting vat returns. 

J

**Comment by MKoppJones** [comment]
I'm not sure what the differences are, I just know, for my needs, organisation is what to use. Maybe the documentation or someone else could shed some light on it for you.

Glad you got it working.

**Comment by jjppnn** [comment]
Im glad it's working too!

Although I notice regardless of what dates I pass in, I always get the same data back ?? 
Seems a bit strange...
J

**Comment by macgrewal** [comment]
The difference between a User and an Organisation is that a User is an individual/real person whereas an Organisation is an entity minus real person attributes e.g. National Insurance Number (NINO).

A dog walker who is a sole trader could be a User but *Super Duper Services Ltd.* would be an Organisation.

@jjppnn when testing the MTD VAT APIs users must be created using the https://test-api.service.hmrc.gov.uk/create-test-user/organisation endpoint.

The individual version of create user will create you a user but they will not have the required `mtd-vat` service.  This is implied but the missing `mtd-vat` service in the request section of https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/api-platform-test-user/1.0#_create-a-test-user-which-is-an-individual_post_accordion.

The `mtd-vat` service is however available on the organisation endpoint (https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/api-platform-test-user/1.0#_create-a-test-user-which-is-an-organisation_post_accordion)

I have fed this back to our team an we will see how best to make this clearer in our docs.

Just to be clear, individuals don't work in test but do work in production.

**Comment by MKoppJones** [comment]
@jjppnn When using the obligations back end, the response will be the same, regardless of the dates you supply. They pointed out in a previous issue, I can't find it right now, that this won't change for a while. Just so you are aware, i have included the quote

> Unfortunately, as we have mentioned previously in this channel, and in the
> numerous hackdays we have held with consumers of our API's, it is simply not
> possible for us to maintain a stateful test environment for use in the sandbox
> environment.
> 
> The suites of services that sit behind our API run in to the 100's, and to
> maintain stateful, simulated responses for all scenarios is a situation we
> can't commit to at present (as is our wish, as well as yours). The compromise
> we agreed on was to offer more expansive, and most importantly valid, and
> realistic responses in the form of extended test scenarios.

Look at the test data section here to see how to get different data, https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0#_retrieve-vat-obligations_get_accordion

If you pass in different test scenario headers, you will get different data.

**Comment by jjppnn** [comment]
Hello again, 
I can get the Obligations to work without any problems at ...
https://test-api.service.hmrc.gov.uk/organisations/vat/666284063/obligations?from=2017-01-01&to=2017-01-01

However, when I try and get payments at ..
https://test-api.service.hmrc.gov.uk/organisations/vat/666284063/payments?from=2017-01-01&to=2017-01-01

I am getting "The remote server returned an error: (400) Bad Request". But the parameters are exactly the same as the obligations URI  ???

Any ideas ??

**Comment by MKoppJones** [comment]
@jjppnn In sandbox, I believe you must supply a 6 month date range for payments.

**Comment by jjppnn** [comment]
From and to dates that are the same = Bad Request
From and to dates that are different (1 day || 1 month || 6 month apart) = 404 Not found

**Comment by MKoppJones** [comment]
@jjppnn Last I tried, you must always use a test scenario with payments

**Comment by jjppnn** [comment]
OK. I've got working now.
Thanks again !

**Comment by MKoppJones** [comment]
@jjppnn My best advice would be reference the VAT API documentation and read through the closed issues. A lot of what you have had to go through here is documented by others there. Hope that helps.

**Comment by AbdelrahmanZaghlool** [comment]
@jjppnn  Could you please post example code in C# or VB.Net of getting the authorization code then trading it with access token ? I'm struggling doing this in .Net and it seems you got it working

**Comment by jjppnn** [comment]
I used the code provided by CHillKat.

See link below.

https://www.example-code.com/csharp/hmrc_oauth2_access_token.asp

**Comment by AbdelrahmanZaghlool** [comment]
@jjppnn thanks now I can get the access token but when I call hello user it returns 401 unauthorized any idea why ?

**Comment by jeyakumar777** [comment]
@jjppnn i am working on Digital VAT Submission for my client. Happy to see you have successfully done this one. Could you please share the dot.net code if you don't mind? Thanks in Advance.
