### ISSUE TITLE
Fraud Prevention - Browser headers and installed software.

### ISSUE THREAD

**Issue by MKoppJones** [hmrc/vat-api#218]
This might be the wrong channel to ask in, will we need to include browser based fraud headers, even when running installed software? (as outlined here https://developer.service.hmrc.gov.uk/api-documentation/docs/reference-guide#fraud-prevention)  The link states they are only relevant to browsers, but do we need the there.

If we do, I assume we just include them blank.

Also, is there an ETA for when these will become compulsory?

**Comment by jonathanleather** [comment]
Hey @MKoppJones 

Unfortunately this is question for the platform and isn't something that we can answer.

My advise would be for you to contact SDST at `SDSTeam@hmrc.gsi.gov.uk` and they should be able to put you in touch with someone from the platform.

If you do find out the answer to your question, feel free to post the answer back here to help other vendors in the same situation.

Cheers
Jon

**Comment by MKoppJones** [comment]
No problem, I'll find out from them and will update this issue with it. I think it will be helpful for others.
