### ISSUE TITLE
X-CorrelationId Response Header not present for Payments or Liabilites

### ISSUE THREAD

**Issue by GrahamHDawson** [hmrc/vat-api#222]
The documentation states that both retrieve VAT Payments, and retrieve VAT Liabilities return the 
X-CorrelationId
Response Header - but this isn't currently the case.
Checked with Fiddler 4 and it's definitely not there for the both the above.

Graham

**Comment by jonathanleather** [comment]
Hi @GrahamHDawson 

Thank you for raising this.
You are correct, as per the documentation the X-CorrelationId response header is missing from both endpoints.

I have raised a story for the team to investigate and rectify this in a future sprint. 

Thanks again.
Jon

**Comment by jonathanleather** [comment]
Hi @GrahamHDawson 

Unfortunately I am unable to provide an ETA as to when this fix will be implemented. The story is  currently with the project / programme for them to prioritise.

It is unlikely the fix will be applied in the near future.

Cheers
Jon

**Comment by macgrewal** [comment]
Re-opening this issue and will close once fix has been applied.

**Comment by GrahamHDawson** [comment]
I can't understand why this wasn't done when the test API was updated to change the AccessToken scope needed for the ViewVATReturn end-point.

It's been 2 months now and the CorrelationID is **still** missing on Payments and Liabilities.
Has it simply been overlooked?

Graham

**Comment by jonathanleather** [comment]
Hi @GrahamHDawson 

The CorrelationID is now being returned for these endpoints in Sandbox.

Cheers
Jon
