### ISSUE TITLE
OAuth authorisation scopes

### ISSUE THREAD

**Issue by nnotsofun** [hmrc/vat-api#23]
Hi,

Will there be any errors when requesting authorisation for a scope the user has not been set up for (i.e. not opted into MTD, but we request access for VAT MTD permissions)?

Cheers,

Nick

**Comment by nnotsofun** [comment]
Hi @hicnar, any chance you'd be able to help answer this query?

Thanks!

**Comment by hicnar** [comment]
@nnotsofun 

Currently in the environment you use to run your app against the authentication is not enabled, so you will not get error messages even if you attempt to access endpoints you would normally not have permissions for (ex. scenario where filling only agent is trying to view vat returns etc).

Eventually the authentication will be enabled, so trying to access resources which the caller has no permissions for will result in security related errors.

Hope that helps!
K.

**Comment by nnotsofun** [comment]
Hey @hicnar, 

That is useful information to know, based on my understanding your response is around interacting with the endpoints? My question was more specifically about requesting a [new authorisation code](https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints). Is there a scenario where we would get an error requesting for scopes the user may not have permission/opted in for yet? Or can a software provider put anything in the requested scopes without issues?

Cheers,

Nick
