### ISSUE TITLE
Subscribing to VAT API

### ISSUE THREAD

**Issue by franksmule** [hmrc/vat-api#230]
How do I subscribe to the VAT API in Manage API subscriptions ? I do not have the option of this API.

Thanks

**Comment by pcrozer** [comment]
Hi Frank - did you find how to subscribe to VAT?  Am currently confused myself...  thanks!

**Comment by MKoppJones** [comment]
@pcrozer I think you need to contact SDST and ask to get whitelisted (I am not associated with them, this is based on other issues)
