### ISSUE TITLE
On trying to get access token, received <Error>grant_type is required</Error>

### ISSUE THREAD

**Issue by autiVru** [hmrc/vat-api#232]
Following are the steps been followed for getting access token:
1. composed the authorization URL
https://test-api.service.hmrc.gov.uk/oauth/authorize?response_type=code&client_id=[]&scope=hello&redirect_uri=http%3A%2F%2Flocal-api.kashflow.com%2Fv2%2Fvatsubmissiongateway%2Faccess_token&state=eyJVc2VySWQiOjQ3NiwiUmVmZXJyYWxVUkwiOiJcImh0dHBzOi8vZ29vZ2xlLmNvbVwiIn0=

2. Above flow redirected successfully to the application from where we triggered access token flow
https://test-api.service.hmrc.gov.uk/oauth/token
HTTP Method: POST
Request Payload client_secret=[]&client_id={[]&grant_type=authorization_code&redirect_uri=[same as above]&code=[]

Always getting this error..
{"error":"invalid_request","error_description":"grant_type is required"}

Could you please suggest what might be wrong here?

P.S. : redirect url used for both the request is same as configured in the HMRC sandbox environment. Also, there is only on redirect URL

Thank you.

**Comment by jacobbrownlow** [comment]
Hi @autiVru

It appears you are following the correct method

Your body appears to be correct
```json
{
  "client_id": " ",
  "client_secret": " ",
  "grant_type": "authorization_code",
  "redirect_uri": " ",
  "code": " "
}
```

Are you actually using "&scope=hello" in the first step? Assuming you want to use VAT the correct scope is "&scope=read:vat+write:vat"

I can only get the error 
```json
{
    "error": "invalid_request",
    "error_description": "grant_type is required"
}
```
if I don't include the grant_type item in the body.

Can you double check your application is including the grant_type?

Regards, Jacob

**Comment by autiVru** [comment]
Hey Jacob,

I tried sending exactly this request payload from fiddler as well, but received the same error

`Request Payload client_secret=[]&client_id={[]&grant_type=authorization_code&redirect_uri=[same as above]&code=[]
`
Regards,
Vrushali

**Comment by autiVru** [comment]
Hey Jacob,

I was able to solve it by adding encoding

` var httpClient = new HttpClient();
      var request = new HttpRequestMessage(HttpMethod.Post, AuthUrl);
      request.Content = new StringContent(requestPayload, Encoding.UTF8, "application/x-www-form-urlencoded");
      var response = httpClient.SendAsync(request).Result;`

**Comment by prabhushrikant** [comment]
> Hey Jacob,
> 
> I was able to solve it by adding encoding
> 
> ` var httpClient = new HttpClient(); var request = new HttpRequestMessage(HttpMethod.Post, AuthUrl); request.Content = new StringContent(requestPayload, Encoding.UTF8, "application/x-www-form-urlencoded"); var response = httpClient.SendAsync(request).Result;`

I was able to do it postman using `x-www-form-urlencoded` option forbody and include following keys with their respective values `grant_type, client_id, client_secret, scope`

**Comment by autiVru** [comment]
Hey Jacob,

Thanks for the reply :) we solved it long back. Sorry forgot to reply to
this .

Regards,
Vrushali
