### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by MKoppJones** [hmrc/vat-api#233]
Currently getting a timeout on the Retrieve VAT Obligations and Submit VAT Return (No code changes on my end). Is the service down?

**Comment by aroncox** [comment]
+1 It was working for me about 15 mins ago, but now seems to be down.

I guess this is the time to test what happens when the service is down :)

**Comment by aroncox** [comment]
Seems to be back-up again :)

**Comment by MKoppJones** [comment]
Same on my end, I think I will just close this.
