### ISSUE TITLE
Liabilities end-point: are amount accumulative?

### ISSUE THREAD

**Issue by stuy1974** [hmrc/vat-api#234]
Hi there.

Just wanted to confirm whether the amounts being returned from the Liabilities end-point are accumulative?

Using the example below - the organisation this data is for currently owes HMRC $100 + $1000 = $1100

Is this correct?

e.g.
```
{
  "liabilities": [{
    "taxPeriod": {
      "from": "2017-04-06",
      "to": "2017-07-06"
    },
    "type": "VAT ...",
    "originalAmount": 6000.00,
    "outstandingAmount": 100.00,
    "due": "2017-07-06"
  },
  {
    "taxPeriod": {
      "from": "2017-07-07",
      "to": "2017-10-07"
    },
    "type": "VAT ...",
    "originalAmount": 1000.00,
    "outstandingAmount": 1000.00,
    "due": "2017-10-07"
  }]
}
```

**Comment by jonathanleather** [comment]
Hey @stuy1974 

Short answer:
This may not always be the case.

I would suggest contacting SDST at `SDSTeam@hmrc.gsi.gov.uk` who can put you in touch with someone that can give you a more in depth answer.

Cheers
Jon
