### ISSUE TITLE
503 Service Unavailable, SERVER_ERROR.

### ISSUE THREAD

**Issue by SeenivasanT** [hmrc/vat-api#236]
Hi,
MTD VAT:  Fetching the obligation API through below API link

https://test-api.service.hmrc.gov.uk/vat/666970019/obligations?from=2018-01-01&to=2018-12-31&status=O

Access Token : Bearer 42ef8620d9a1a66f3b88fa54ebea4a21

While fetch Obligations I am facing below error:
Getting the following Error 503 Service Unavailable, SERVER_ERROR.

Any help would be much appreciated.

**Comment by jonathanleather** [comment]
Morning @SeenivasanT 

It's your link thats the problem.

You are missing `/organisations`, try the one below and let me know how it goes.

https://test-api.service.hmrc.gov.uk/organisations/vat/666970019/obligations?from=2018-01-01&to=2018-12-31&status=O

Cheers
Jon
