### ISSUE TITLE
GetVatObligations - always returns Service Unavailable

### ISSUE THREAD

**Issue by JimTurnerAtStirling** [hmrc/vat-api#237]
With a brand new user, a valid access token and vrn and any date range,  a call to GetVATObligations always returns the same error  {Error, Failed with response code SerivceUnavailable}
The specific dates used in my last attempt are 01-01-2018 to 31-03-1028, however any date range gives the same error.

Any idea what the problem might be?

**Comment by MKoppJones** [comment]
If I remember correctly, the date range must be 6 months or more for now. So if you change to 01-01-2018 to 01-07-2018, you might have better luck. You might also need to include one of the test scenarios (this is all from memory, apologies if I lead you down the wrong path here)

**Comment by jonathanleather** [comment]
Hey @JimTurnerAtStirling 

No issues have been raised this morning with the environment.
Could you provide more information on the exact request you are sending? url, headers etc

Cheers
Jon

**Comment by jonathanleather** [comment]
Also just to add.

The 6 month issue has recently been fixed due the addition of the new test responses in sandbox. This enabled us to provide many more Gov Test Scenarios for you to test with.

Thanks for helping out though MKoppJones! The team very much appreciate it!

Cheers
Jon

**Comment by JimTurnerAtStirling** [comment]
A change to date range as suggest makes no difference to the result. The url I am sending to is https://test-api.service.hmrc.gov.uk/.  Since I am calling the HmrcDotNet.Servic library downloaded from NuGet, the headers etc are taken care of by that package.

**Comment by JimTurnerAtStirling** [comment]
Solved.  This base url was incorrect.  It was missing the /organisations/ section.  The library appends /vat/{vrn}/obligations to the BaseUrl,  however, I guess it cannot know that call is for an organisation.

Thanks for your help.
