### ISSUE TITLE
Endpoint error messages not consistent with documentation

### ISSUE THREAD

**Issue by dharma66** [hmrc/vat-api#238]
Documentation for Liabilities and Payments endpoints indicate 400 error responses to have messages:

INVALID_DATE_FROM
INVALID_DATE_TO
INVALID_DATE_RANGE

In fact, these messages appear to be:

DATE_FROM_INVALID
DATE_TO_INVALID
DATE_RANGE_INVALID

**Comment by jonathanleather** [comment]
Hi @dharma66 

Thank you for raising this. I'll get a story raised on the backlog to rectify this.

Cheers
Jon

**Comment by jonathanleather** [comment]
The documentation has now been updated to match the API.

Cheers
Jon
