### ISSUE TITLE
Vat return submission fails with unexpected UNMAPPED_PLAY_ERROR

### ISSUE THREAD

**Issue by JimTurnerAtStirling** [hmrc/vat-api#239]
This is my call:
POST https://test-api.service.hmrc.gov.uk/organisations/vat/666783178/returns failed with status code 400 (Bad Request).
Response body:
{"code":"INVALID_REQUEST","message":"Invalid request","errors":[{"code":"UNMAPPED_PLAY_ERROR","message":"error.expected.jsboolean","path":"/finalised"}]}

And the content (that clearly includes finalised):
{"periodKey":"18A2","vatDueSales":1.5,"vatDueAcquisitions":0.50,"totalVatDue":0.0,"vatReclaimedCurrPeriod":2.0,"netVatDue":2.0,"totalValueSalesExVAT":20,"totalValuePurchasesExVAT":10,"totalValueGoodsSuppliedExVAT":10,"totalAcquisitionsExVAT":5,"finalised":"true"}

This content is one of the samples off the website.

Can you see the error please?  Thanks.

**Comment by MKoppJones** [comment]
"true" should be true (without the speech marks). It is a boolean not a string, looks like they are strict here.
