### ISSUE TITLE
API performance

### ISSUE THREAD

**Issue by nnotsofun** [hmrc/vat-api#24]
Hi,

Are there any performance metrics for how the VAT API will perform? If not, will they be published at a later date?

Cheers,

Nick

**Comment by hicnar** [comment]
@nnotsofun 

We certainly have some metrics that show how the API performs, but according to my best knowledge this is for internal use only and there are no plans for this to be published.

Hope this helps!
K.

**Comment by nnotsofun** [comment]
@hicnar 

No worries! How about SLA's or timeouts on the end points? i.e. how are long are we expecting a submit to take in production or retrieving obligations? The sandbox is pretty fast but somehow I don't think it's representative ;-)

**Comment by nnotsofun** [comment]
@hicnar any chance you'd be able to look at my last comment? thanks!
