### ISSUE TITLE
Refresh Token

### ISSUE THREAD

**Issue by MKoppJones** [hmrc/vat-api#240]
Is anyone else experiencing issues with refresh tokens not working after the first use?

To clarify, I use a refresh token, store the new one, use the new one, get a generic "An unexpected error occurred". This is a new issue, and was working fine yesterday. Any ideas?

This might be one for SDST, but I don't have the best of luck with them right now, so I thought its worth asking here first.

**Comment by MKoppJones** [comment]
Do we now have a limit to how often we can do this in a time period?

**Comment by westwater** [comment]
Hi @MKoppJones, the documentation on refresh tokens (https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints) only mentions that when the access token is refreshed, the original token is invalidated - which isn't your case and there is no mention of a limit either. 

Is this still occurring?

**Comment by MKoppJones** [comment]
No, this stopped not long after, it seemed to be a temporary issue. I forgot to close the issue.
