### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by davidhardie** [hmrc/vat-api#241]
Hi,

The documentation page https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0 seems to 404. 
In addition, https://developer.service.hmrc.gov.uk/api-documentation/docs/api doesn't seem to list the VAT API.

Is there a new docs location I should be looking at?

**Comment by jonathanleather** [comment]
Hi @davidhardie 

That is the correct link.
Has your application been whitelisted? If not then you wont be able to see the VAT-API in the list to subscribe.

To whitelist your app you need to contact SDST at `SDSTeam@hmrc.gsi.gov.uk`.

Cheers
Jon

**Comment by davidhardie** [comment]
Hi,

Thanks for that, Not 100% sure of what you mean by 'whitelisted'. I registered as a developer and registered an application, but also couldn't see the VAT API in the subscriptions list.

I'll send an email off to SDST as you suggest, thanks.
