### ISSUE TITLE
Visual Studio Community - HMRC Tutorials - C# examples (or VB examples)

### ISSUE THREAD

**Issue by PeterGGreen** [hmrc/vat-api#243]
Hi,

I've been trying for a couple of weeks to get the basic HMRC API tutorials working in Visual Studio Community edition.  Using C# and the following modules:

using System.Net.Http;
using Newtonsoft.Json;
using Microsoft.Owin.Security.OAuth;

Does anyone have any fully working code/examples with all 3 end points accessible and working?  I have all my apps and subscriptions set up.  The documentation accompanying these "Tutorials" is woeful.

Not even started looking at the MTD-VAT stuff yet...

Thanks in advance,

Peter

**Comment by jjppnn** [comment]
Hi Peter,
I too have suggested that .NET examples would be highly beneficial. All I can suggest is that you take a look at ChilKat. See https://www.example-code.com/csharp/hmrc_oauth2_access_token.asp. Seems to work very well.

I am using Winforms in C# utilising the NewtonSoft package. I suspect the Chilkat software will be using System.Net.Http namespace internally. I am no where near completing this project as I have been putting it off, hoping that better documentation and .NET examples will come forth. (I agree that the documentation is to be found wanting.) 

Hope this helps.
J

**Comment by obeea** [comment]
@PeterGGreen did you review this thread?
https://github.com/hmrc/vat-api/issues/215

Using standard .Net functions and reading the docs, you can easily call all the relevant endpoints, so shouldn't need anything special to obtain authcodes and access tokens (which is basically OAuth2).

Some .Net examples would certainly be useful though, as it seems to be a common request.

**Comment by PeterGGreen** [comment]
Well, I agree it should be simple, but as with all things to do with HMRC it rarely is.  I've had the invaluable assistance of a colleague but even so, the support from HMRC has been very poor.  When exposing an API, any API, not just a web API, to thousands of developers, there should be full documentation and examples provided.  In all of the anticipated access methods.

I've happily produced XML for various reasons (CIS, RTI etc) and submitted through the Government Gateway so I'm no stranger to working with HMRC, but I do feel this API malarkey, while it may be the future, is a very large step.  And as such the documentation and sample interfaces MUST be improved.

@obeea Thanks for the link to the other issue.  I'll read it and see if it helps.

**Comment by PeterGGreen** [comment]
@jjppnn Thanks for the ChilKat tip.  I have been in touch with them and while this would allow us to maintain our single VB6 environment for development, I suspect MTD VAT is just the tip of the iceberg and I fully expect all submissions to HMRC (CIS, RTI etc) to be via the API at some point and the Government Gateway sent out to pasture on some farm somewhere :-)

So while it's painful now, having to learn a new language and new environment, I think the pain may be worth it.  I don't approve of this move away from the Government Gateway, but they're not likely to listen to us poor developers.

**Comment by MarkAKelly** [comment]
Hi @PeterGGreen,

As this is a direct channel to the delivery team responsible solely for the VAT API, this feedback might be slightly misplaced.  I would suggest sending any suggestions related to accessing the platform to SDST through the normal channel at SDSTeam@hmrc.gsi.gov.uk.

We can make sure at our side that your comments are passed to the teams in charge of the documentation/tutorials related to accessing HMRC API's, although unfortunately as developers on a specific API, I don't think we can give you too much in the way of responding to your issues with the HMRC API migration strategy.

Please let us know if we can help in the future with anything specifically to MTD VAT, or MTD SA.

Many thanks,

Mark

**Comment by PeterGGreen** [comment]
Hi @MarkAKelly 

I've sent at least 5 or 6 emails to the normal email address and the standard response seems to be "go and check out GitHub, you'll get all the help you need".  So here I am.   I'm sure once I get the OAUTH2 endpoint working (tomorrow's job), I'll be moving onto first steps accessing and using the VAT API endpoints.

Can you point me to the document that is the VAT API equivalent of the RTI Spec Doc, the technical document that details in the various stages of communication.  Might as well have it ready for when I get it all working.

Thanks,

Peter

**Comment by jjppnn** [comment]
I too have sent multiple emails to SDSTeam@.... and basically getting the same response.... Go and ask the developers at github. 

I have asked why .NET was overlooked and was told that after research only the top 3 languages were used to give examples. 

.NET not in the top 3. seems unlikely....

John

**Comment by macgrewal** [comment]
Hi All, I appreciate that it can be frustrating to not have code examples in your chosen language but as @MarkAKelly has previously mentioned issues on this repo are for MTD VAT API endpoints.

I'm sure many of you have visited the [Tutorials page on the Developer Hub](https://developer.service.hmrc.gov.uk/api-documentation/docs/tutorials), that page has links to examples in a few languages. I believe requesting C#/.NET examples as issues on those repos may put you into contact with the relevant teams. Our team do not publish any code examples.

Regards,

mac

**Comment by MaxtonSoftware** [comment]
FYI if anyone wants code examples in native VB.net ping me though [here](https://github.com/BusinessMicroSystemsLtd) got the code working for our MVC vb.net project.

**Comment by jeyakumar777** [comment]
> 
> 
> > FYI if anyone wants code examples in native VB.net ping me though [here](https://github.com/BusinessMicroSystemsLtd) got the code working for our MVC vb.net project.
> 
> The ping didn't work.

Hi,
I would like to have the vb.net code for this project. Please let me know how to get it from you.

**Comment by jeyakumar777** [comment]
> 
> 
> FYI if anyone wants code examples in native VB.net ping me though [here](https://github.com/BusinessMicroSystemsLtd) got the code working for our MVC vb.net project.

Hi,
I would like to have the vb.net code for this project. Please let me know how to get it from you.

**Comment by MaxtonSoftware** [comment]
Sure, email me at richard @ businessmicrosystems co uk

**Comment by jeyakumar777** [comment]
Hi Richard , Thanks for your quick  reply. 
Please send me the details to jeyakumar777@yahoo.co.uk.  
Thanks again.  
Jeyakumar 

Sent from Yahoo Mail on Android 
 
  On Fri, 15 Mar 2019 at 10:47, MaxtonSoftware<notifications@github.com> wrote:   
Sure, email me at richard @ businessmicrosystems co uk

**Comment by zico7** [comment]
Example c# code to retrieve authorisation url...

            var query = HttpUtility.ParseQueryString(string.Empty);
            query["response_type"] = "code";
            query["client_id"] = "{YOUR CLIENT_ID}";
            query["scope"] = "hello+write:vat+read:vat";
            query["state"] = Guid.NewGuid().ToString();
            query["redirect_uri"] = "{YOUR REDIRECT URI}";
            string queryString = query.ToString();

            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Add("Accept", "application/vnd.hmrc.1.0+json");
                var response = client.GetAsync("https://test-api.service.hmrc.gov.uk/oauth/authorize?" + queryString).Result;
                string redirect_uri = response.RequestMessage.RequestUri.ToString();
            }
