### ISSUE TITLE
Bearer Authorization for Create Organization endpoint VAT MTD

### ISSUE THREAD

**Issue by simohutcaus** [hmrc/vat-api#244]
Hi there,

I have noticed in another issue that you hit this endpoint to generate a test user for VAT MTD endpoints 

https://test-api.service.hmrc.gov.uk/create-test-user/organisations

I have seen it in the following issue where i was trying to figure out how to gain a test user

https://github.com/hmrc/vat-api/issues/157

In that issue the following screenshot was provided on how to generate the test user, with the Bearer token greyed out for security purposes

![image](https://user-images.githubusercontent.com/16058967/45272504-d5fbcd80-b4f0-11e8-8636-870bd0b2d20b.png)

I am trying to figure out how to get that bearer token. I know typically that is a access code but given that you have to authorise that new test user further into the process to allow a submission or retrieval, what token do you use when generating the test user and how do you generate the token to do so given that the way to get a access token is to go through the oauth procedure of a client allowing a connection to a app, if the client doesn't already exist, how can the chicken exist before the egg so to speak :)

Cheers

**Comment by simohutcaus** [comment]
Of course after i post this i figured it out... (server token) however i am now getting this response

![image](https://user-images.githubusercontent.com/16058967/45272582-6f2ae400-b4f1-11e8-8b85-b9670e93a803.png)

I am using POSTMAN for testing

How do i get our app subscribed to the endpoints?

**Comment by simohutcaus** [comment]
Rubberducked that one too. Jeepers sorry guys :)

**Comment by geoapp80** [comment]
Just wondering Simon, have you got the oauth part to work through postman for the HMRC MTD stuff?
