### ISSUE TITLE
Inconsistency in one of the messages

### ISSUE THREAD

**Issue by seurrep** [hmrc/vat-api#246]
When I try and deliberately pass an invalid value to the 'finalised' parameter when submitting a return, I get this back:

{"code":"INVALID_REQUEST","message":"Invalid request","errors":[{"code":"UNMAPPED_PLAY_ERROR","message":"error.expected.jsboolean","path":"/finalised"}]}

This message seems inconsistent with the other errors being returned (trying the same with a number field for example returns INVALID_REQUEST & in the errors collection you get INVALID_NUMERIC_VALUE if memory serves as well as a slightly more readable message).

**Comment by jacobbrownlow** [comment]
Hi @seurrep 

Yes you are correct, the following bugs are present in Submit VAT Return:

Submitting **"finalised": null** will return
```json
{
    "code": "INVALID_REQUEST",
    "message": "Invalid request",
    "errors": [
        {
            "code": "UNMAPPED_PLAY_ERROR",
            "message": "error.expected.jsboolean",
            "path": "/finalised"
        }
    ]
}
```

Submitting **"finalised": abc** will return
```json
{
    "statusCode": 400,
    "message": "Invalid Json: Unrecognized token 'abc': was expecting ('true', 'false' or 'null')\n at [Source: akka.util.ByteIterator$ByteArrayIterator$$anon$1@2975bacb; line: 12, column: 20]"
}
```

Only submitting with  **"finalised": false** will return the correct error format
```json
{
    "code": "BUSINESS_ERROR",
    "message": "Business validation error",
    "errors": [
        {
            "code": "NOT_FINALISED",
            "message": "The return cannot be accepted without a declaration it is finalised.",
            "path": "/finalised"
        }
    ]
}
```

I will raise a ticket on our backlog, but I'm unable to provide an ETA for when this will be fixed.

Thanks for raising this
Jacob

**Comment by mtd-api-team** [comment]
Unfortunately this change cannot be implemented in the current version of the API due to it being a  breaking change. Thank you for bringing this to our attention and we will be adding it in a future version of the API 🙂
