### ISSUE TITLE
GET /vat/{vrn}/obligations isn't using the date range supplied

### ISSUE THREAD

**Issue by EcoJames** [hmrc/vat-api#247]
Request
`GET https://test-api.service.hmrc.gov.uk//organisations/vat/666446506/obligations?from=2017-06-01&to=2017-12-31`

Response
`{"obligations":[
  {"start":"2017-01-01","end":"2017-03-31","due":"2017-05-07","status":"F","periodKey":"18A1","received":"2017-05-06"},
{"start":"2017-04-01","end":"2017-06-30","due":"2017-08-07","status":"O","periodKey":"18A2"}
]}`

**Comment by EcoJames** [comment]
Ah OK, great, thanks for the swift reply!

**Comment by EcoJames** [comment]
I've found that if I submit a new return for period 18A2, I can retrieve that one successfully despite GET /vat/{vrn}/obligations still saying that period 18A2 is outstanding

**Comment by macgrewal** [comment]
Hi @EcoJames, the GET endpoint is a canned response so this is expected.
