### ISSUE TITLE
Submit VAT return for period - periodKey meaning + lack of submission year

### ISSUE THREAD

**Issue by RobertMarczycki** [hmrc/vat-api#25]
Hi,

The documentation of the periodKey in VAT submission API says: "Identifier for the period of the VAT return, For example: #001".

How the software is supposed to generate the period information? How/ whether is this related to dates i.e. I cannot see any field in the request which says for which range of dates a given submission applies - in the legacy gateway submission there were fields named PeriodStart/ PeriodEnd?

Thanks,
Robert

**Comment by hicnar** [comment]
Robert,

Sorry about the problems you're having. This is again the documentation that needs to clearly mention that the very first thing you need to do is retrieve the VAT obligations. In the array returned by the /obligations endpoint, every entry will have periodKey value assigned. 
Obviously, you will need to use the periodKey value that corresponds with the time period which you are submitting the VAT return for.

Thank you for your remarks, we will use them to improve the documentation so that it is clearer.

Pozdr
K.

**Comment by RobertMarczycki** [comment]
Hi,

Thank you for the response! 

I'd appreciate some clarifications - it's difficult to make assumptions based on sandbox responses ;-):
- assuming a new UK business enrolls VAT scheme, would the HMRC service - for the very first call - respond with:
-- a single obligation record having period set to #1 and reflecting expected range of dates for the nearest submission period due (e.g. quarter, or monthly), 
or 
-- with multiple period records - e.g. reflecting the current/ future obligations?
- assuming existing business enroll MTD for VAT - will the service respond with the data imported from the past?
- how long before due date (or: on what other conditions) new period record will be generated and available from the service?

Thanks,
Robert

**Comment by nnotsofun** [comment]
@hicnar any updates on these questions?

**Comment by hicnar** [comment]
@RobertMarczycki & @nnotsofun

The questions above are not strictly technical, we're waiting for them to be answered by our colleagues from other teams, and once we have the answers they will be posted here.

From what I already know:
The response is defined in a way that it can carry multiple records. If you run the call against the ET environment you can simulate (using the Gov-Test-Scenario header)  three scenarios

1) all obligations returned as opened
2) some obligations fulfilled and the remaining ones opened
3) all obligations as fulfilled

As a general rule it may be good to be prepared that multiple obligations may be returned and also that every scenario that may be simulated (see the three cases above) may also be encountered in the production scenario.

I do not know the answers for the remaining questions, but like I said once we get them, they will be published here

**Comment by hicnar** [comment]
@RobertMarczycki 

I have been advised to inform you that the questions like the ones you asked above (starting with "I'd appreciate some clarifications - it's difficult to make assumptions based on sandbox responses") need to be sent to SDST. They are not strictly technical, so the dev team is not the best contact point to answer them.

Hope this helps!
K.

**Comment by RobertMarczycki** [comment]
Thank you for the update – I’ll chase SDST then!

Cheers,
Robert
