### ISSUE TITLE
Issue with EndDate for retrieve VAT Liabilities and Payments

### ISSUE THREAD

**Issue by AnitaJohny** [hmrc/vat-api#252]
When we tried giving the EndDate as 31/01/2017 for Retrieve VAT Liabilities and Payments in WebAPI for MTD VAT, we could not get any result, but is showing an error stating '**The remote endpoint has indicated that no data can be found**'. This result comes only when this date is given. Else in all other case we are getting the data from HMRC. Could you please help us know the reason for the same?

**Comment by jonathanleather** [comment]
Hi @AnitaJohny 

I can certainly try.
This is all to do with the dates that are returned as part of the liabilities/payments from the backend and how the API filters those liabilities/payments.

Heres a few scenarios that will hopefully explain it a little better.
A particular liability has the following dates:
taxPeriodFrom = 2017-01-01 
taxPeriodTo = 2017-02-01

Below are the requests you make to retrieve the liability:
Scenario A - /liabilities?from=2017-01-01&to=2017-01-17
Outcome - "The remote endpoint has indicated that no data can be found"

Scenario B - /liabilities?from=2017-01-01&to=2017-01-31
Outcome - "The remote endpoint has indicated that no data can be found"

Scenario C - liabilities?from=2017-01-01&to=2017-02-01
Outcome - the above liability is returned

Scenario D - liabilities?from=2017-01-27&to=2017-02-20
Outcome - the above liability is returned

The reason for this is that the taxPeriodTo date of the liability MUST fall within the date range you have provided within the request.  

Hopefully that helps, let me know if you have any further questions.

Cheers
Jon
