### ISSUE TITLE
Source Code to generate OAuth 2.0 Bearer Token for MTD (VAT) Submission using C#.NET

### ISSUE THREAD

**Issue by Pankajkala** [hmrc/vat-api#253]

**Comment by adamdavi3s** [comment]
https://www.example-code.com/csharp/hmrc_oauth2_access_token.asp

**Comment by adamdavi3s** [comment]
No that isn't possible as the user in "live" will need to sign in with their government gateway id and possibly two factor authentication.
If you wanted to be clever you could do this in the app then return the response URL and read that from the DOM, look for the section "OAuth 2.0 for installed applications" in the documentation if you want to know more, assuming that is what you;re doing of course

**Comment by Pankajkala** [comment]
Hi adamdavi3s , but my requirement is that i have to do this through code , not manually opening HMRC gateway.

**Comment by adamdavi3s** [comment]
Someone else may comment but I do not think that is possible

**Comment by ma3574** [comment]
@adamdavi3s is correct as the authorisation flow uses the OAuth 2 flow. It is not possible to do everything programmatically as a user needs to log in and authorise the application. Please see https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation for full authorisation details. This is standard across the platform. Any further questions/clarifications regarding the authorisation element can be clarified by the Software Developers Support Team, please drop them an email on SDSTeam@hmrc.gsi.gov.uk.
