### ISSUE TITLE
Which Period Key to be used from Retrieve VAT obligations to further VAT Submission? 

### ISSUE THREAD

**Issue by Pankajkala** [hmrc/vat-api#254]
/organisations/vat/{vrn}/obligations 
This API returns two period Keys  18A1   & 18A2. 

Out of These two Keys which one we will use which Submission to HMRC API  /organisations/vat/{vrn}/returns ?

**Comment by MKoppJones** [comment]
You will need to use the next open period key. So assuming you are using the test data, that is probably 18A2.

This will be the next period key with a due date in the future. (With the test data, this isn't true as it is all dated 2017)

**Comment by Pankajkala** [comment]
Thanks MKoppJones for the quick response.
