### ISSUE TITLE
How can we have VAT FinalSubmission in MTD VAT ?

### ISSUE THREAD

**Issue by Pankajkala** [hmrc/vat-api#259]

**Comment by jacobbrownlow** [comment]
Hi @Pankajkala 

Currently the _Submit VAT Return_ endpoint is a POST, which means it cannot be amended. In this sense it is final.

Does this answer your question? 

Regards, Jacob

**Comment by adamdavi3s** [comment]
Please can I then ask what the   "finalised": true flag is for on the return? 
If set to false will the API allow an overwrite or is there plans for a PATCH ?

**Comment by macgrewal** [comment]
Hi @adamdavi3s, I believe this is explained in the vendor guide.

![image](https://user-images.githubusercontent.com/7713555/46732934-cc4bbe00-cc86-11e8-951d-bfaa671594e2.png)

Third party vendors are required to display the legal declaration text to the agent/client. The finalised flag represents the agent/clients actual legal declaration. If a return is submitted with a declaration flag of false then our API will reject the submission with a 403 - NOT_FINALISED error.

Regards,

mac
