### ISSUE TITLE
VAT Submissions - Gov-Test-Scenario header values

### ISSUE THREAD

**Issue by RobertMarczycki** [hmrc/vat-api#26]
Hi,

The documentation https://test-developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0#_submit-vat-return-for-period_post_accordion mentions an optional Gov-Test-Scenario (Sandbox only) request header facilitating testing of different HMRC responses. 

Is there any description of available/ planned header values? The site mentions “Test Data table” which should include details but we can’t find this section for VAT Submission API.

Thanks,
Robert

**Comment by hicnar** [comment]
Robert,

I must agree with you that the documentation is a bit vague on that topic.
Currently you can test that endpoint with four values for the Gov-Test-Scenario header. 
They are the following: 

1) INVALID_VRN - Submission has not passed validation. Invalid parameter VRN.
2) INVALID_PERIODKEY - Submission has not passed validation. Invalid parameter PERIODKEY.
3) INVALID_PAYLOAD - Submission has not passed validation. Invalid parameter Payload.
4) INVALID_ARN - The remote endpoint has indicated that the Agent Reference Number is invalid.

Hope it helps
K.
