### ISSUE TITLE
Small issue with documentation

### ISSUE THREAD

**Issue by seurrep** [hmrc/vat-api#262]
When retrieving liabilities & providing an invalid date, the documentation lists the returned error status code as INVALID_DATE_FROM. What seems to be returned at present is DATE_FROM_INVALID.

**Comment by jonathanleather** [comment]
Hi @seurrep 

This issue has already been raised under issue #238 but thank you for raising this.
If you don't mind i'll close this issue down and so we can just track the one above.

Cheers
Jon
