### ISSUE TITLE
Is Create Test User API is available in Production VAT (MTD) also ? 

### ISSUE THREAD

**Issue by Pankajkala** [hmrc/vat-api#265]

**Comment by jacobbrownlow** [comment]
Hi @Pankajkala 

No this is a test-only endpoint

Regards, Jacob

**Comment by Pankajkala** [comment]
Hi Jacob,
Thanks for the Replay.
"If there is no Create Test User API for Production, then how do we create Authentication code as it requires username & password" ?

**Comment by jacobbrownlow** [comment]
Hi @Pankajkala 

In Production you will require a real VAT organisation. The VAT user will need to be subscribed to the MTD-VAT service and your vendor application will also need to be whitelisted. 

I believe the vat-api is still in private beta so it currently isn't open to all public VAT users. For more information please contact the Software Developers Support Team SDSTeam@hmrc.gsi.gov.uk who should be able to advise you further about subscriptions and whitelisting.

Regards, Jacob

**Comment by Pankajkala** [comment]
Thanks Jacob for your quick response.
