### ISSUE TITLE
What is the process to create Access_Token in MTD(VAT) ?

### ISSUE THREAD

**Issue by Pankajkala** [hmrc/vat-api#266]

**Comment by jacobbrownlow** [comment]
Hi @Pankajkala

Assuming you are using External Test (Sandbox)

The steps are as followed:
1. Register vendor application on Developer Hub and get SDST to whitelist your application id.
2. Call create-test-user organisation endpoint https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/api-platform-test-user/1.0 with `mtd-vat` service
3. Hit the grant authority URL https://test-api.service.hmrc.gov.uk/oauth/authorize...
Login with created user's username/password, grant authority to Vendor to act on behalf of the user
4. Copy code provided in response url
5. Call https://test-api.service.hmrc.gov.uk/oauth/token with correct code, which will return a token 

Then use the VRN from create-test-user and the Authorization header with Bearer `tokenValue`

If you need more assistance please review the documentation https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation or contact SDST SDSTeam@hmrc.gsi.gov.uk

Regards, Jacob
