### ISSUE TITLE
Internal Server Error 500 when trying to view or submit VAT Return

### ISSUE THREAD

**Issue by LukeHirst** [hmrc/vat-api#267]
I seem to be running into an issue with the view and submit VAT Return methods of the VAT-API. 

This issue only seems to occur when using the access token I retrieve when refreshing the initial access token which expires after 4 hours.

My steps to recreate are as follows:

1. Authenticate with the vat-api and grant authority to my application
2. Use the access token to get obligations, submit and view VAT Returns (this works OK)
3.  Force token refresh (or wait for 4 hours to elapse) so a new access token is returned
4. Send a request to the view  VAT Return or Submit VAT Return methods, I always get the following response:

{
  "code":"INTERNAL_SERVER_ERROR",
  "message":"An internal server error occurred"
}

The behaviour seems odd as I can return VAT obligations without error but whenever I try to submit or view an existing VAT return through the API, I always get this error.

I try the process from the beginning by granting authority to my application and using the initial access token produced and this works OK.

What seems to be more confusing is that when I use the 'HelloUser' api to test the access token obtained using a refresh token. I get the expected response:

{
  "message":"Hello User"
}

Is there an issue here?

**Comment by MKoppJones** [comment]
How long has this been happening? This happened to be last week for a few hours, but the next day, it was working again.

I'm not in a position to try this out right now to see if it is a problem for others, apologies.

I hope some one can help here though, as this will be very annoying indeed.

**Comment by liam-lagay-14** [comment]
We can replicate this in the sandbox via simply authenticating a user and submitting a VAT return. We've been unable to successfully submit any VAT returns as a consequence.

**Comment by jacobbrownlow** [comment]
Hi @LukeHirst 
This does appear to be an issue in Sandbox. I'm looking into it now.

**Comment by LukeHirst** [comment]
Thank you for the quick response.

I also tried creating a new test organisation and starting from scratch, this also recreates the issue that liam-lagay-14 has stated.

**Comment by jacobbrownlow** [comment]
Hi again @LukeHirst 

The issue appears to resolved. We're keeping an eye on it, let us know if you have any trouble

Regards, Jacob

**Comment by LukeHirst** [comment]
I have re-tested the API using the initial access token and refresh tokens.

It is now working as expected.
