### ISSUE TITLE
Retrieveing vat obligations returns not authorised with valid Token and Vrn

### ISSUE THREAD

**Issue by JimTurnerAtStirling** [hmrc/vat-api#268]
This was working correctly earlier today (called it perhaps 50 times successfully).  We have made no code changes to our application, only swapped to a new user.  The OAuth process with the new user completes successfully.
Has anything changed this afternoon that might explain the sudden failure?  Thanks.

**Comment by jacobbrownlow** [comment]
Hi @JimTurnerAtStirling 

GET VAT Obligations is working for myself, in Sandbox. 
Can you double check your user credentials and Bearer Token are correct. For instance, you aren't using the original Token with a new VRN?

Let me know if you are still unable to call the endpoint.

Regards, Jacob

**Comment by markogrady** [comment]
Hi Jim, How are you creating the user. I found when I was created it via the API it works but when I created a user via the portal, it didn't work.

**Comment by JimTurnerAtStirling** [comment]
I used the Portal.  Thanks, I will try with the api.

**Comment by JimTurnerAtStirling** [comment]
Creating the new user with the API, works.  Thanks.

**Comment by jacobbrownlow** [comment]
To confirm, unfortunately the create-test-user gui (portal) doesn't support mtd-vat at this time. VAT users created on it are only subscribed for non-mtd VAT.

Thanks, Jacob
