### ISSUE TITLE
Obligation for given test user seems to not be updated

### ISSUE THREAD

**Issue by seurrep** [hmrc/vat-api#269]
I tried the following steps:

- Create a test user
- Get obligations for test user
- Submit return for the open obligation
- Get obligations for test user

The 'status' field for the obligation that I just submitted a return for is still showing as 'O', but if I try and submit the same return another time it fails as it has already been submitted (BUSINESS_ERROR and DUPLICATE_SUBMISSION).

**Comment by MarkAKelly** [comment]
Hi @seurrep, 

The test environment is not stateful, so the data will not change for obligations.  As part of the VAT journey the only stateful data will be after a VAT Return submission, where it is possible to retrieve your VAT submissions.  In time this will be removed and canned data will be introduced.

Hope this answers your question.

Mark
