### ISSUE TITLE
Query of NetVatDue figure when Submitting VAT Return

### ISSUE THREAD

**Issue by LukeHirst** [hmrc/vat-api#270]
I have query on how the NetVatDue figure should be calculated when submitting to the VAT API.

Currently the paper copy of the VAT 100 report says the following:

'Take the figures in boxes 3 and 4 and deduct the smaller amount from the larger amount. Enter the difference in box 5. If this amount is under £1 you need not send any payment, nor will any repayment be made to you.'

The developer documentation on the HMRC Developer Hub states the following:

'The difference between totalVatDue and vatReclaimedCurrPeriod. This corresponds to box 5 on the VAT Return form. The value must be between 0.00 and 99999999999.99'

This to me seems conflicting.

If you take the following VAT Return:

 box 1: £20
 box 2: £30
 box 3: £50
 box 4: £130

The total NetVatDue figure would be £80 (taking the smallest value from the biggest) according to the VAT 100. 

The calculation according to the API documentation would be £-80, which you can't submit to the API. 

Also if we're also sending a positive value how do you determine if VAT is paid or reclaimed to the HMRC using the NetVatDue figure? If it is used at all.

Would you be able to give further clarification on this?

**Comment by narendravijayarao** [comment]
Hi,

The value to be entered in box 5 (netVatDue) is always positive (as indicated in the range).  You can choose to follow the "deduct the smaller from the larger" (130-50 = 80) approach, or you can absolute the difference between box 3 and box 4 (i.e. |50-130|= 80).

To identify a repayment due on the 9 box return then box 3 amount will be less than in box 4. Once updated the Liability will have a chargeType of either:

VAT return debit charge or VAT return credit charge.

Thanks,
