### ISSUE TITLE
ERR_CONNECTION_REFUSED_MTD VAT Authorisation

### ISSUE THREAD

**Issue by phani29oct** [hmrc/vat-api#271]
Hi There,

Whilst doing the digital authorisation testing for MTD VAT, we are facing below error after clicking on "Grant Authority":

"This site can’t be reached
localhost refused to connect.
Search Google for localhost 2588 VAT Vat Submit
ERR_CONNECTION_REFUSED"

Is there any downtime for the service?

Any help would be much appreciated.

Thanks

**Comment by jacobbrownlow** [comment]
Hi @phani29oct 

This is what I see in Chrome when clicking "Grant Authority"
![image](https://user-images.githubusercontent.com/35334115/45752134-6f6f6180-bc0c-11e8-9920-eb58d9a5697e.png)

This is expected. The redirect URL contains a code necessary for the next step
For example mine is 
http://localhost:9000/?code=a418c5459a7e5ed4b94f07b49def688e&state=12345

The code `a418c5459a7e5ed4b94f07b49def688e` is used in the oauth call to retrieve a Bearer token

Let me know if you have any issues

Regards, Jacob

**Comment by phani29oct** [comment]
Hi There,

Thanks for the response Jacob.

Here I have added Redirect URI's as "http://localhost:2588/Company/Authcode" and "http://localhost:2588" in  "https://developer.service.hmrc.gov.uk/developer/application" it is working fine in development environment and I have added same URI's with change of PORT number of QA environment, it is not working with QA environment.

Do there is any URI's change for QA environment if so then what would be the URI.

Any help would be appreciated.

Thanks

**Comment by jacobbrownlow** [comment]
Hi @phani29oct 

I am not sure what you mean by Development and QA environments. We only support vendors using our External Test and Production environments.

I'm not very familiar with Redirect URI issues because authentication is outside our scope, so I would advise you to contact the Software Developers Support Team SDSTeam@hmrc.gsi.gov.uk who should be able to give you assistance.

Apologies I couldn't help further
Jacob

**Comment by phani29oct** [comment]
Hi Jacob,

Thanks for your response.
I mean Development and QA environments is where the developers use some url's for development purpose and some url's for QA (Testing) purpose, so my issue is url's using for development is working fine and same url's given for Testing then those were not working.

Any help would be appreciated.

Thanks

**Comment by pp07** [comment]
Hi @phani29oct 
   please change your Redirect_url (replace only port number ) in "https://developer.service.hmrc.gov.uk/developer/application"   and then try i think its works.
