### ISSUE TITLE
Documentation location?

### ISSUE THREAD

**Issue by PhonicUK** [hmrc/vat-api#274]
I cannot find any accessible documentation on using this service.

https://developer.service.hmrc.gov.uk/api-documentation/docs/api does not appear to contain any references to how to submit VAT returns.

The only other page I've found by looking through the issues here is at https://test-developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0#_submit-vat-return-for-period_post_accordion - but this page is inaccessible.

**Comment by PhonicUK** [comment]
Ah it may not have been yet. I've emailed that address already with the application ID for the sandbox application but it is of course the weekend.

As an aside it would be nice if the page I linked actually lists what documentation exists with an extra note saying you have to be whitelisted to view the information.

**Comment by jonathanleather** [comment]
@PhonicUK 
I understand your frustration.

I believe that this is something that will be improved upon in the near future but I'll pass your comments on to the relevant team members. 

If you don't mind i'll close this issue but if you continue to have any problems please do come back to us.

Cheers
Jon
