### ISSUE TITLE
Box 5 value, after calculation if found to be negative, how to proceed

### ISSUE THREAD

**Issue by AnitaJohny** [hmrc/vat-api#275]
If the box 5 value is negative, after getting the difference between box 3 and 4, should we convert it to positive or should we not submit the same? Please let me know how to proceed in such a situation?

**Comment by narendravijayarao** [comment]
Hi,

The box 5 should always be positive, the difference (larger amount - smaller amount) of box 3 and 4.
Consider as positive and enter in the box 5.

Thanks,
Naren.

**Comment by madecca** [comment]
Hi

Can I point out that the value in Box 4 (vatReclaimedCurrPeriod) can be greater than the value in Box 3 (totalVatDue) resulting in a negative number in Box 5 (netVatDue). The netVatDue would then be a refund.

Currently the HMRC API states:

netVatDue is:

"The difference between totalVatDue and vatReclaimedCurrPeriod. This corresponds to box 5 on the VAT Return form. The value must be between 0.00 and 99999999999.99".

Can anyone clarify how a VAT refund is submitted?

Thanks
Nick

**Comment by jacobbrownlow** [comment]
Hi

I believe the answer on this [issue](https://github.com/hmrc/vat-api/issues/270) has more explanation

```The value to be entered in box 5 (netVatDue) is always positive (as indicated in the range). You can choose to follow the "deduct the smaller from the larger" (130-50 = 80) approach, or you can absolute the difference between box 3 and box 4 (i.e. |50-130|= 80).

To identify a repayment due on the 9 box return then box 3 amount will be less than in box 4. Once updated the Liability will have a chargeType of either:

VAT return debit charge or VAT return credit charge.```

Regards, Jacob

**Comment by madecca** [comment]
Hi Jacob
Thanks for your prompt reply. That all makes perfect sense.
Regards
Nick
