### ISSUE TITLE
Test if authorisation is valid

### ISSUE THREAD

**Issue by adamdavi3s** [hmrc/vat-api#276]
Hi All,

Apologies if this has been asked, but is there a way to test if the authorisation from the user to the application has expired or been revoked.
I wondered if it was possible to "test" via say calling the Obligations API but the same response is returned if the authorisation has been revoked or if the bearertoken has expired.
I guess this technically could be done by testing if the refresh token works....

Is there any way to distinguish the two? The end goal is
Test authenticaton -> OK ->Refresh access token
Test authenticaton -> FAIL->Redirect to authentication URL

**Comment by MKoppJones** [comment]
I would do this the other way around. As far as I can tell, if the refresh token doesn't work, it has expired, or has already been used. The below would be a good test, I think.

Refresh access token -> OK -> Proceed with action
Refresh access token -> FAIL -> Redirect for authorisation

**Comment by GrahamHDawson** [comment]
Do we know what the 'lifetime' of the RefreshToken is?
I know the AccessToken has a lifetime of 4 hours but can't seem to find any value for RefreshToken.
