### ISSUE TITLE
write:vat scope required to View VAT Return

### ISSUE THREAD

**Issue by rbs-ben** [hmrc/vat-api#277]
I wanted to reraise issue #151 as I don't think the given answer makes sense. You say "GET requests require read:vat permissions" but this one doesn't, it requires write:vat. The question is, why?

It's true we can request read:vat+write:vat , but this seems like a workaround. To view a VAT return the user will have to grant permission for the software to "Change your VAT information", which isn't appropriate.

**Comment by jacobbrownlow** [comment]
Hi @rbs-ben 

I've tested this and can confirm 'View VAT Return' requires `write:vat` scope.
This seems like a bug and I will get this raised on our backlog if it is.

Regards, Jacob

**Comment by jacobbrownlow** [comment]
_For Internal use:_ JIRA ticket 1965

**Comment by jacobbrownlow** [comment]
Hi @rbs-ben 

A fix for this has been made and it will likely be deployed in ET and Production on Monday 22nd

Regards, Jacob

**Comment by rbs-ben** [comment]
Many thanks!
