### ISSUE TITLE
How to Test Agent - Allowing Agent to file VAT on my behalf

### ISSUE THREAD

**Issue by HidayathS** [hmrc/vat-api#278]
I can test user by call "create-test-user/organisations" API. Through this call, I can get username, password, vrn for test user. How can I test the scenario for Agent to file VAT on my behalf. If I have a VAT Registration Number and  I want Agent to file VAT, I need to authorize the agent. How can I allow that ? Is there any test UI (URL) available ? Are there any test credentials available (for an Agent)? What steps should I follow to test an Agent flow ?

**Comment by jacobbrownlow** [comment]
Hi @HidayathS 

Unfortunately the sandbox environment does not currently support testing with Agents. This is something that has been raised before and I believe they are looking into a solution. But I would encourage you to still raise this with the Software Developers Support Team SDSTeam@hmrc.gsi.gov.uk so the relevant team can be prompted to prioritise it.

FYI, In production the URLs for the vat-api will be the same for Agents or non-Agents. The only difference will be the Bearer Token in the submission headers, which will be linked to the Agent and not the client.

Regards, Jacob

**Comment by pp07** [comment]
Is it true? We can't test agent in sandbox?

**Comment by jacobbrownlow** [comment]
Hi @pp07 

Yes this is true. The VAT-API can handle Agents in the test environments, but the API Platform doesn't currently support them. I would encourage you to raise this with the Software Developers Support Team SDSTeam@hmrc.gsi.gov.uk so they can see this is important to vendors.

Regards, Jacob
