### ISSUE TITLE
Error 404 Exchanging Authorisation Code for Access Token

### ISSUE THREAD

**Issue by gbs-matt** [hmrc/vat-api#279]
I have gone through the process of creating a test organisation using https://test-api.service.hmrc.gov.uk/create-test-user/organisations with service type "mtd-vat".  I have authorised the "read:vat" scope for the test organisation at https://test-api.service.hmrc.gov.uk/oauth/authorize.  Finally, I am trying to exchange the authorisation code for an access token at https://test-api.service.hmrc.gov.uk/oauth/token.

Every time I make a call to https://test-api.service.hmrc.gov.uk/oauth/token I get error 404.  Even going there directly with a browser returns a 404 error page (well, strangely, the HTML of a 404 error page).  I would expect to see something similar to what I get when i go to https://test-api.service.hmrc.gov.uk/create-test-user/organisations with a browser.

I am using C# and dot net 4.7.1.

Can anyone offer any suggestions as to why I'm getting this 404 error?

As an aside, in case it's relevant, when i create a test organisation via the API, the returned JSON doesn't contain a VRN.  If it's not relevant then that'll be my next problem to solve.

**Comment by obeea** [comment]
I just happened to create a test organisation and it returned the following (with a VRN);
`{"userId""870032853940","password":"iXl0nkVc0lor","userFullName":"Vivien Jackson","emailAddress":"vivien.jackson@example.com","organisationDetails":{"name":"Company SAMNG5","address":{"line1":"31 Earl's Court Road","line2":"Slough","postcode":"TS12 1PA"}},"vrn":"666203186"
`
The VRN will be required later on, but not needed when exchanging the auth code for a token.
What are you passing in your header, and I assume you are using 'POST' rather than 'GET'?

**Comment by gbs-matt** [comment]
You're absolutely right, I was GETing instead of POSTing to https://test-api.service.hmrc.gov.uk/oauth/token.  I can't believe I didn't realise that.  Thanks for that!

I still have a problem with the organisation creation though.  I've created an organisation just now with "mtd-vat" and i got:

`{"userId":"136972337137","password":"hohnjEwwohsg","userFullName":"Gabi Quinn","emailAddress":"gabi.quinn@example.com","organisationDetails":{"name":"Company BKAKHA","address":{"line1":"22 Victoria Drive","line2":"Dartford","postcode":"TS8 1PA"}}}`

Did you use "mtd-vat" when you created that organisation?

**Comment by obeea** [comment]
Yes, this is what I'm passing to 'create-test-user/organisations'
```
{
  "serviceNames": [
    "mtd-vat"
  ]
}
```

**Comment by obeea** [comment]
Also, In the header, I pass 'Authorization' with 'Bearer ' + SERVER_TOKEN

**Comment by jacobbrownlow** [comment]
Hi @gbs-matt 

You should get a VRN returned when you create your test organisation
![image](https://user-images.githubusercontent.com/35334115/46020077-67fcfc00-c0d5-11e8-8f50-0005dd31477d.png)

and you will need "write:vat" or "read:vat+write:vat" scope to POST

Regards, Jacob

**Comment by gbs-matt** [comment]
> this is what I'm passing to 'create-test-user/organisations'
> 
> ```
> {
>   "serviceNames": [
>     "mtd-vat"
>   ]
> }
> ```

> Also, In the header, I pass 'Authorization' with 'Bearer ' + SERVER_TOKEN

I've checked again and I'm passing in exactly the same.


> You should get a VRN returned when you create your test organisation

Agreed but it doesn't seem that way.  Clearly I'm doing something wrong but I'm struggling to see it.

> you will need "write:vat" or "read:vat+write:vat" scope to POST

Do you mean 'generally' or are you referring to create-test-user/organisation or oauth/token?

**Comment by jacobbrownlow** [comment]
Hi

I double checked the Sandbox environment
![image](https://user-images.githubusercontent.com/35334115/46022663-f0ca6680-c0da-11e8-9133-e6097f98aa00.png)
It should definitely be returning a VRN

The scope isn't needed for /create-test-user, it's used later on to grant vendor permission to act on behalf of the user. So part of the oauth journey, but specifically for either API you mentioned.

Could you confirm you are getting back a `201`

Regards, Jacob

**Comment by gbs-matt** [comment]
Here's an example from just now, headers included:

`StatusCode: 201, ReasonPhrase: 'Created', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Vary: Accept
  Strict-Transport-Security: max-age=31536000;
  X-Frame-Options: SAMEORIGIN
  X-Content-Type-Options: nosniff
  Connection: keep-alive
  Cache-Control: no-store, no-cache, max-age=0
  Date: Tue, 25 Sep 2018 14:59:26 GMT
  Content-Length: 246
  Content-Type: application/json
}
{"userId":"279081937251","password":"sioyoamdMkhr","userFullName":"Fay Izzard","emailAddress":"fay.izzard@example.com","organisationDetails":{"name":"Company Q4ZVJX","address":{"line1":"29 Chelsea Square","line2":"Swanage","postcode":"TS3 1PA"}}}`

**Comment by gbs-matt** [comment]
I've found the problem.  I had an upper case 'S' at the start of the name: serviceNames.  Sorry for wasting your time.

Thanks to both of you for your help.  Really appreciated.
