### ISSUE TITLE
Submit VAT Return Access Token Problem

### ISSUE THREAD

**Issue by sonicmule** [hmrc/vat-api#28]
I have successfully implemented the Hello User and VAT Obligations api's,
but I am having a problem with the Submit VAT Return function.

I request an authority code with a scope of "write:vat"
I show the HMRC Login page where i enter my test user account number and password.
This redirects me to the page to Grant Authority for my application to 'Change your VAT information'
When I click 'Grant', I receive the access token and refresh token.
But using the access token to submit the VAT return gives me a 401 unauthorized where the whole process of logining is repeated for ever.

Is this a known issue?

**Comment by nnotsofun** [comment]
@sonicmule just tested it with my setup, submission and list is working fine. Might be worth double checking that you're newly requested access/refresh token.

disclaimer: I don't work for the HMRC

**Comment by sonicmule** [comment]
@nnotsofun Thanks for the response, I now have it working.
Needed to create the Authorization header first before writing the data into the request stream.
Now getting 
Status Code : ServiceUnavailable
Message : { "code": "SERVER_ERROR", "message": "Service unavailable"}
Maybe I we'll all get emailed when the service back up ;-) ;-)
