### ISSUE TITLE
Should accountants make use of ASA credentials for submitting their own VAT returns

### ISSUE THREAD

**Issue by kmanish86** [hmrc/vat-api#280]
While accountants have to create new ASA accounts for submitting VAT returns for their clients, should accountant use the same account for submitting their own VAT.

Inherently the question is, will the OAuth token obtained when the accountant uses ASA credentials work for VAT submissions for all clients including their firm?

**Comment by macgrewal** [comment]
Hi @kmanish86, can you explain what you mean by ASA credentials?

**Comment by kmanish86** [comment]
ASA (https://www.gov.uk/guidance/get-an-hmrc-agent-services-account) is a unique gov gateway account which accountants / firms should create to submit returns on behalf of clients and my question was alluding towwards would firms use the same credential to manage their own respective VAT affairs.
I heard back from SDS that it depends on firms. There are firms who may use same account with appropriate accesses, but some who may have different accounts.

Closing this ticket now, as i have got details from SDS.
