### ISSUE TITLE
Retrieve VAT obligations From & To Date Range Limit

### ISSUE THREAD

**Issue by Renu84** [hmrc/vat-api#281]
Currently , we can get Obligations for year 2017 , range from Jan 2017 to Dec 2017.
 Bad request is returned if we pass more than 12 months period or even if we pass June 2017 to June 2018 gets back same 400 response code, is it just issue on Test system and what is maximum period we can ask obligations for ?

Many Thanks

**Comment by macgrewal** [comment]
Hi @Renu84,

You'll receive the 400 response with the `INVALID_DATE_RANGE` error code when the date range exceeds 365 days.

**Comment by Renu84** [comment]
Hi @macgrewal ,

Thanks a lot for responding back with a definitive answer , is this same for Live environment as well ?

**Comment by macgrewal** [comment]
Hi @Renu84, yes this is the same in Live. Apologies for the delayed response.
