### ISSUE TITLE
Lifespan of accesstoken

### ISSUE THREAD

**Issue by AnitaJohny** [hmrc/vat-api#282]
- What is the lifespan of an access token? It is said that lifespan is 14400 sec for access token in test environment and it is 18 months in HMRC site. As a developer we need to finalize the timespan so that we can use it in our application. 
- How can the user know that the access token is expired? 
- What is the purpose of response token?

Please help

**Comment by adamdavi3s** [comment]
You need to read this end to end, trust me it helped a lot:

https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints#user-restricted

**Comment by GrahamHDawson** [comment]
AccessToken lifespan is 4 hours from time of issue.
RefreshToken lifespan is 18 months from time of issue.

>How can the user know that the access token is expired?
You should handle AccessToken renewal automatically within your application by recording the expiry date/time and using the RefreshToken to get a new AccessToken (and RefreshToken) if the original has expired.

Graham
