### ISSUE TITLE
500 error on refresh token

### ISSUE THREAD

**Issue by adamdavi3s** [hmrc/vat-api#283]
I thought this was an issue with my app but I am getting a 500 error when trying to refresh a token.
I've tried via postman and get the same response, also re-authenticated my app with my user and tried that newly generated token but I get the same error.

Only appears to have started happening late last night / this morning

{
    "error": "server_error",
    "error_description": "An unexpected error occurred"
}

**Comment by narendravijayarao** [comment]
Hi,

Thank you for your question, unfortunately we cannot answer this question as it relates to the wider HMRC API Platform.

Please contact SDST team for this auth related issues at SDSTeam@hmrc.gsi.gov.uk.

Thanks and sorry for the inconvenience.

**Comment by adamdavi3s** [comment]
Thanks @narendravijayarao  and not a problem, wasn't sure where the issue sat :)
