### ISSUE TITLE
Access Token for VATMTD 100 validity

### ISSUE THREAD

**Issue by phani29oct** [hmrc/vat-api#284]
Hi There,

We have checked in HMRC website "https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints" for the validity of accesstoken which is valid for "**14400**". Can we know whether this 14400 sec is the user logged-in time duration in the application from the time user receives accesstoken (or) the normal time from which user receives the accesstoken. 

for ex: 
1. User has authorised from HMRC got the access token and user used the application for more than 4 hours, will the accesstoken get expired?

2. User has authorised from HMRC got the access token and user used the application for 2 hours and closed the application and logged in back after 3-4 hrs (previously logged in duration is 2 hrs only), will the access token received earlier will be working fine for the second time logged in (or) the user need to get a new accesstoken by refreshtoken interacting with HMRC?

Any help would be appreciated

Thanks

**Comment by adamdavi3s** [comment]
Based on my testing, the token is valid for 4hrs total regardless of use. But i could be wrong here!

**Comment by MKoppJones** [comment]
From my testing, and my understanding of the documentation, I have to agree with @adamdavi3s

**Comment by phani29oct** [comment]
Hi There,

Thanks for the response @adamdavi3s and @MKoppJones. I too can understand that token will be valid for 4 hrs only. but this 4 hrs count starts from when either from the the time user get authorized or from the time user logged in

Any help would be appreciated.

Thanks

**Comment by adamdavi3s** [comment]
From the time the token is generated I believe

**Comment by phani29oct** [comment]
Thanks for your response @adamdavi3s 

If so then user has logged in and worked for 2 hrs only, after some time it may be a gap of 5 hrs user has logged in again, then the accesstoken which was already generated is going to working fine or not

Any Help would be appreciated.

Thanks

**Comment by adamdavi3s** [comment]
@phani29oct

That depends on your app.
If the token is generated when the user logs in, then yes it will expire 4hours after that point in time. At least that is my understanding.

Grab the time when the token is generated, add the validity (14400 seconds) that’s your expiry time regardless of any other factors at all

**Comment by macgrewal** [comment]
@phani29oct if your token expires you can refresh it (I believe for another 4hrs).

**Comment by GrahamHDawson** [comment]
When you get your AccessToken you'll also receive a RefreshToken 
The RefreshToken has a lifetime of 18 months and can be used to get a new AccessToken (and RefreshToke) when the original one expires (4 hours after the issue time).

So all you need to do is save the expiry Date and Time (issue Date and Time plus 4 hours.
(I use the StarDate format so I don't need to worry about midnight rollover)
then check the current StarDate against that ExpiryStarDate before each API call.

If currentStarDate > ExpiryStarDate 
  use RefreshToken to get new AccessToken and record updated ExpiryDate

Remember you need to do this twice, once for read:vat and once for write:vat

But if you do something like the above then your end-user will only ever need to grant the permissions once as they'll be continually renewed.
Works for me anyway :-)

Graham

**Comment by adamdavi3s** [comment]
Or just cheat and put both scopes in the same token if that is acceptable to the app you're building 

I didn't end up holding the expiry data but do this instead:

Request -> OK then great
Request -> Fail -> Try refresh ->Request ->OK then great
Request -> Fail -> Try refresh -> Request -> Fail -> Send to Reauth screen

**Comment by MIHAllstars** [comment]
@adamdavi3s 

How did you work how that you definitely need to send to reauth as the refresh seems to return 400 and INVALID_REQUEST for multiple reasons?

**Comment by adamdavi3s** [comment]
What instances are you getting a 400? I only get it if my tokens have expired or become unsynced for some reason.
Other 400 errors tend to be invalid parameters etc but that should be avoided within the application

**Comment by MIHAllstars** [comment]
The User Restricted Endpoints page states this 'If the user's refresh_token has expired, when your application calls our token endpoint, it receives a response with an HTTP status code of 400 (Bad Request) and an error code of invalid_request.'.
This doesn't seem very specific to the scenario where the refresh token has expired and you need to start the re-authorisation process all over again?

**Comment by adamdavi3s** [comment]
Yes so you either create a counter to count 4 hours so you know the token has expired or you have to simply assume it has.
The exchange of tokens is pretty arbitrary so I simply assume that the token has expired if I hit a 400 error, if the token exchange fails or the  request fails for a second time then the user is redirected to the authorisation page

**Comment by MIHAllstars** [comment]
Thanks, I was going down the route of just assuming, I was just expecting a specific error for that circumstance but hey, it's good enough for me.

**Comment by adamdavi3s** [comment]
Haha yeah it would have been nice to have!

https://github.com/hmrc/vat-api/issues/276

**Comment by macgrewal** [comment]
@adamdavi3s @MIHAllstars 

Section 5 of the [authorisation documentation](https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints) says if your token expires you will receive a `401` response with an error code of `INVALID_CREDENTIALS` (in the body).

**Comment by MIHAllstars** [comment]
@macgrewal that's when the access token has expired and you need to refresh it but not when the refresh token expires and you need to start the full authorisation process all over again.  There is a very non-specific error when this happens, i.e. a 400 and INVALID_REQUEST.
