### ISSUE TITLE
oauth2 "journey" not starting

### ISSUE THREAD

**Issue by davidpipe58** [hmrc/vat-api#285]
Can anyone suggest where I am going wrong here.

I'm just starting out with the MTD VAT APIs, and all I'm try to do is get the user-restricted HellowWorld example working, but I'm not even managing to get to the HMRC start page.

This is the url I am using:

	https://test-api.service.hmrc.gov.uk/oauth/authorize?
		response_type=code
		&scope=hello
		&redirect_uri=http%3a%2f%2flocalhost%3a8080
		&client_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

	(A valid client id is being sent.)

The returned status code is NotFound.

I've read and re-read the documentation a dozen times and can't see anything I am not conforming to.

Any suggestions will be gratefully accepted.

Thanks

**Comment by seurrep** [comment]
Not sure if this is connected to the same issue but when I go to the following URL:

https://test-api.service.hmrc.gov.uk/oauth/authorize?response_type=code&client_id=[removed]&scope=write:vat%20read:vat&redirect_uri=http://localhost/auth

I get the following JSON spat back:

`{"error":"invalid_request","error_description":"redirect_uri is invalid"}`

This call has worked for the last week or two. Has anything broken on HMRC's side?

**Comment by davidpipe58** [comment]
So. I have just re-read the documentation very slowly and this is what I failed to take in:

Redirect URIs

We use redirect URIs to send the user back to your application after successful (or unsuccessful) authorisation,prior to your application accessing user-restricted endpoints.

**You must specify one or more redirect URIs when you create your application,** and also specify one redirectURI when you send your user to our authorisation endpoint. To protect your application from phishing attacks,the redirect URI used for authorisation must match one of those specified when you created your application

OAuth2 now working.
