### ISSUE TITLE
X-Correlationid missing in the Response Headers of Retrieve VAT Payments and Retrieve VAT Liabilities

### ISSUE THREAD

**Issue by dev-efr** [hmrc/vat-api#287]
The API documentation does indicate that X-Correlationid  will be part of the Response for Retrieve VAT Payments and Retrieve VAT Liabilities, but the Sandbox Test response doesn't seem to have it.

**Comment by macgrewal** [comment]
Hi @dev-efr, issue #222  was previously raised and an item has been added to our backlog.
