### ISSUE TITLE
Starting with MTD and APIs

### ISSUE THREAD

**Issue by dennysfl** [hmrc/vat-api#288]
Hi people,

I am developing a tool where I need to use HMRC APIs to send and receive some information.
The problem is, this is my first contact with it. A have a lot of questions. 
if you can help me I will be eternally grateful.

My client has a company, and he needs to submit VAT data using my tool.
I have my application created on HMRC Developer Hub. I've got a Client ID, Client Secret and I have created a Test User.

- **Client ID**
Is the Client ID mine (what I generated on HMRC Developer Hub) or is it from my client/user/person that will use the tool in her house?

- **Authorisation**
The Client ID I need to pass by parameter is mine or my client?

- **Token**
How to check if the Token is still valid??
To get a token I am using it: https://test-api.service.hmrc.gov.uk/oauth/token&client_id=x&client_secret=x&grant_type=x&code=x&redirect_uri=x

- **VAT Number**
How to link the VAT Number with the Token or the authorisation?

- **Retrieve Obligations/Payments/Liabilities**
To retrieve these information I found it:
https://test-api.service.hmrc.gov.uk/organisations/vat/VAT_NUMBER/obligations?from=2018-01-01&to=2018-07-31&status=O
Do I need to send any token or code?

I apologize for the amount of doubt.
Thank you very much in advance.

Dennys

**Comment by macgrewal** [comment]
Welcome to the MTD APIs @dennysfl. For help around authorisation please have a look at https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation.

For more help regarding Authorisation please contact the Software Developer Support Team (SDST) on SDSTeam@hmrc.gsi.gov.uk, they will be able to point you in the right direction.
