### ISSUE TITLE
Why do we need to submit values for Box 3 and Box 5?

### ISSUE THREAD

**Issue by GrahamHDawson** [hmrc/vat-api#291]
In the current manual online submission process the end-user doesn't enter values for either
TotalVATDue (Box 3) or
NetVATDue (Box 5)

Those values are calculated for them by the submission process.

I'm just wondering why these have been included - seems like an unnecessary potential cause of error.

Graham

**Comment by GrahamHDawson** [comment]
This is the online submission form and as you can see the user doesn't enter Box 3 or Box 5
Maybe these two boxes could be removed from the VAT Submission end point?
![onlinereturn](https://user-images.githubusercontent.com/42624873/46282330-1cc96a00-c569-11e8-8efc-558f5590c284.PNG)

**Comment by rbs-ben** [comment]
Prior to submitting the return the accounts software will have calculated these values and displayed them to the user.  By submitting these figures the software can confirm that they're correct; i.e. if the server returns VAT_TOTAL_VALUE or VAT_NET_VALUE the software will know that an error has occurred and that the wrong figures have been presented to the user, and it can respond accordingly.

**Comment by scottylace** [comment]
@GrahamHDawson The MTD business requirement for the VAT 9 box return agreed last year and delivered into the API sandbox, is that the vendor software must supply all 9 fields via the MTD VAT API, including the calculated figures in boxes 3 (totalVatDue) and 5 (netVatDue).

Regards, 

Scott.

**Comment by GrahamHDawson** [comment]
OK, many thanks.
