### ISSUE TITLE
GET returns- can we have an array of all returns

### ISSUE THREAD

**Issue by adamdavi3s** [hmrc/vat-api#292]
Pretty major change request I guess but is it possible to have an endpoint where we could have all the returns in one hit? I guess the payload gets a bit large for multiple years but what about date ranging it so essentially you end up with something like the obligations but with returns data?

I only ask as we want to cache the data locally for users to view offline but having to loop through every obligation to do a get and check if the data has changed is a pain.

**Comment by macgrewal** [comment]
Thanks for getting in touch @adamdavi3s, I've made our Product Manager aware of this request.
