### ISSUE TITLE
What does response mean when GetObligations provides From To Date parameters with one day difference

### ISSUE THREAD

**Issue by likedustg** [hmrc/vat-api#293]
Hi, 

I tested the Get VAT Obligations API, and found that it accepts any date range when toDate>fromDate (probably the gap should be smaller than 365 days as stated in other thread). 

Because of the canned response data of sandbox environment, I cannot figure out how the obligations are determined. Is it the duedate of the obligation should fall into provided parameter set from-to range? Or is that the whole accounting period should fall into the provided parameter set range?

When from date is 1.Oct 2018, to Date is 2 Oct 2018, should any data be returned? (Sandbox returns data anyway)

Thank you for help.

Regards

**Comment by jonathanleather** [comment]
Hey @likedustg 

Have you had a look at this closed issue #176?
It may have some of the answers you are looking for. 

If not feel free to come back to us.

Cheers
Jon
