### ISSUE TITLE
Accessing a user-restricted endpoint - 403 Error

### ISSUE THREAD

**Issue by alanfinnharris** [hmrc/vat-api#295]
Hi, 
I'm attempting to access the user restricted end point in one of the tutorials (below is my code (PLSQL));

Problem is when I run this program, I get the "HTTP client error 403 - Forbidden" error, can you help me 
solve this please?

I have been successful accessing an application-restricted end-point.

Procedure p_test IS
      http_req          utl_http.req;
      http_resp         utl_http.resp;
      lv_err_msg        tmp_errors.err_text%TYPE;
      token_url         VARCHAR2(1024)   := 'https://test-api.service.hmrc.gov.uk/oauth/authorize';
      client_id         VARCHAR2(100)    := '******$$$#####';
      client_secret     VARCHAR2(100)    := '###@@@###@@@';
      l_server_token    VARCHAR2(200)    := '******###$$$$$';      
      client_credential VARCHAR2(200)    := client_id || ':' || client_secret;
      client_scope      VARCHAR2(100)    := 'hello';
      client_grant_type VARCHAR2(100)    := 'client_credentials';
      req_body          VARCHAR2(1024);
      l_value           VARCHAR2(1024);
      lv_err_point      VARCHAR2(10);

      lv_wallet         VARCHAR2(500);
      lv_password       VARCHAR2(500);
      --      
      lv_ws_url         VARCHAR2(500);
      lv_ws_method      VARCHAR2(50);
      lv_ws_protocol    VARCHAR2(50); 
      lv_response       VARCHAR2(32767);
  begin
    lv_err_point := '1.0.1';
    lv_wallet   := f_get_sys_char('WAL', 'SYS', 'PATH', NULL);
    lv_password := f_get_sys_char('WAL', 'SYS', 'PWD', NULL);
      --
    IF lv_wallet IS NULL OR lv_password IS NULL
    THEN
       dbms_output.put_line('No sys_params entry found for wallet path or wallet password');
       return;
    END IF;
      --
    dbms_output.put_line('Wallet path-'||lv_wallet);
    lv_err_point := '1.0.4';
    --
    lv_err_point := '1.0.8';
    UTL_HTTP.SET_WALLET(lv_wallet, lv_password);
    UTL_HTTP.SET_DETAILED_EXCP_SUPPORT(true);
    UTL_HTTP.SET_RESPONSE_ERROR_CHECK (enable => true );
    UTL_HTTP.SET_DETAILED_EXCP_SUPPORT(enable => true );
  
    req_body := 'grant_type=' || client_grant_type || '&' || 'scope=' || client_scope;
    http_req := UTL_HTTP.begin_request (token_url, 'POST','HTTP/1.1');    
    UTL_HTTP.set_header(http_req, 'Authorization', 'Basic ' ||  client_credential);
    UTL_HTTP.set_header(http_req, 'content-type', 'application/json');
    UTL_HTTP.set_header(http_req, 'Accept-Charset', 'UTF-8');
    UTL_HTTP.set_header(http_req, 'Connection', 'Keep-Alive');
    UTL_HTTP.set_header(http_req, 'Content-Length', LENGTH (req_body));
    UTL_HTTP.write_text (http_req, req_body);
    http_resp := UTL_HTTP.get_response (http_req);
    LOOP
      UTL_HTTP.READ_LINE(http_resp, l_value, TRUE);
      DBMS_OUTPUT.PUT_LINE(l_value);
    END LOOP;
    
    UTL_HTTP.end_response (http_resp);
 
    
  EXCEPTION
  WHEN UTL_HTTP.END_OF_BODY 
  THEN
    UTL_HTTP.END_RESPONSE(http_resp);
  END;

Thanks,
Alan

**Comment by GrahamHDawson** [comment]
Alan have you posted **real** client_id, secret and server tokens?
If so I'd mask them or replace with **** or something.

**Comment by macgrewal** [comment]
@alanfinnharris what's the format of the `Authorization` header you're passing to the API? Does it look like `Bearer xxxx...`?

**Comment by alanfinnharris** [comment]
Hi, thanks for the responses, We got this to work in Oracle PL/SQL eventually, the problem was the format of the body.
First part of Authentication, to get the authorisation code can be done with PL/SQL ... code snippet below shows how to swap the code for a token.

procedure p_test_auth IS
      lv_err_point     VARCHAR2(10);
      lv_wallet        VARCHAR2(500);
      lv_password      VARCHAR2(500);
      --      
      lv_ws_url        VARCHAR2(500);
      lv_ws_method     VARCHAR2(50);
      lv_ws_protocol   VARCHAR2(50);
      req utl_http.req;
      res utl_http.resp;
      token_url           VARCHAR2 (32767)  := 'https://test-api.service.hmrc.gov.uk/oauth/token';
      req_body            VARCHAR2(5000);
      value               VARCHAR2(1024);

begin
    lv_wallet   :=  f_get_sys_par('WAL', 'SYS', 'PATH', NULL);
    lv_password :=  f_get_sys_par('WAL', 'SYS', 'PWD', NULL);
      --
    IF lv_wallet IS NULL OR lv_password IS NULL
     THEN
         dbms_output.put_line('No sys_params entry found for wallet path or wallet password');
         return;
    END IF;

    UTL_HTTP.SET_WALLET(lv_wallet, lv_password);
    UTL_HTTP.SET_DETAILED_EXCP_SUPPORT(true);
    UTL_HTTP.SET_RESPONSE_ERROR_CHECK (enable => true );
    UTL_HTTP.SET_DETAILED_EXCP_SUPPORT(enable => true );
    
    req_body := '{"grant_type":"authorization_code","client_id":  "JJMLz*************","client_secret": "c6fefce8-78b4-4b*********","code": "74d********edbf46ec1172fe6","redirect_uri": "https://www.wherever.com"}';    
    req := UTL_HTTP.begin_request (token_url, 'POST','HTTP/1.1');

    UTL_HTTP.set_header(req, 'content-type: application/json');
    UTL_HTTP.set_header(req, 'Accept-Charset', 'UTF-8');
    UTL_HTTP.set_header(req, 'Content-Length', LENGTH (req_body)); 

    UTL_HTTP.write_text (req, req_body);

    res := UTL_HTTP.get_response (req);
 
    LOOP
        UTL_HTTP.READ_LINE(res, value, TRUE);
        DBMS_OUTPUT.PUT_LINE(value);
    END LOOP;
    UTL_HTTP.end_response (res);

EXCEPTION
  WHEN UTL_HTTP.END_OF_BODY THEN
    UTL_HTTP.END_RESPONSE(res);
end;
