### ISSUE TITLE
Regarding Payment retrievement

### ISSUE THREAD

**Issue by likedustg** [hmrc/vat-api#296]
Hi, 

I have a question about payment retrievement API. This API return list of payment history right?

Can it happen that on some day, there are two payments like the following response?
{
  "payments": [
   {
    "amount": 100.00,
    "received": "2017-04-06"
   },
   {
    "amount": 50.00,
    "received": "2017-04-06"
   }
   ]
}

That is, can we treat receivedDate as a primary key? Can it happen when query the same date, different results can be returned (maybe one payment came in later that day)?

Thank you for help.

Regards,

**Comment by jonathanleather** [comment]
Hey @likedustg 

It is possible that more than one payment can be returned with the same payment received date.

Cheers
Jon
