### ISSUE TITLE
VAT API Documentation

### ISSUE THREAD

**Issue by ntimc** [hmrc/vat-api#297]
Hello,

Could someone kindly point me in the right direction to find the documentation for the VAT API?

So far I've only been able to find a few slides in the VAT Customer Journeys PDF (https://developer.service.hmrc.gov.uk/api-documentation/docs/mtd).

Doesn't seem to have any documentation on the developer hub API documentation page either.

We are trying to connect to the VAT-API using a .NET application and so far have been able to authenticate and generate a test organization. 

Apologies if I'm overlooking something obvious.

Regards,

Niv

**Comment by adamdavi3s** [comment]
You need so sign up an app and have it whitelisted before the documentation is available

**Comment by ntimc** [comment]
Hi @adamdavi3s 

Thank you for your reply. I've added the application in the developer hub, in a "Sandbox" environment. How would I get it whitelisted?

Regards,

Niv

**Comment by adamdavi3s** [comment]
I think it’s via the SDSTeam if memory serves
SDSTeam@hmrc.gsi.gov.uk

**Comment by ntimc** [comment]
Thanks @adamdavi3s,

I will contact them and see. Again thank you for taking the time to help me.

**Comment by adamdavi3s** [comment]
Not a problem at all, we’re all in the same boat!

**Comment by narendravijayarao** [comment]
Hi Niv,

To access the api documentation you need to be register for the MTD VAT API. Once you register (or if you already registered) please contact SDST via email on SDSTeam@hmrc.gsi.gov.uk requesting to be added to the MTD VAT API whitelist. Once added to the whitelist you should be able to see the documentation.

Thanks,
Naren.

**Comment by ntimc** [comment]
Hi Naren,

I've emailed SDST requesting access to the API and the documentation. By "register for MTD VAT API", do you mean registering the application the the developer hub? I can't see anything else there for me to specifically register for MTD VAT?

Regards,
Niv.

**Comment by macgrewal** [comment]
Hi @ntimc, 

You're correct, by _registering_ @narendravijayarao means registering the application the the developer hub and then subscribing to the Self Assessment (MTD) API using the "Manage API subscriptions" feature within your app on the developer hub.

Please be aware the Self Assessment (MTD) API will become visible once your app has been added to the whitelist.

Regards,

mac
