### ISSUE TITLE
Error: invalid_grant, Description: refresh_token is invalid

### ISSUE THREAD

**Issue by mathiasbanda** [hmrc/vat-api#299]
We have a customer who is registered for MTD. Our software appears to get authorized correctly (milt-factor kicks in) but then any subsequent attempts to access and end point for a service yields this error.

Trouble is it's only happening in live production, testing server works fine.

What's going on please

Mathias

**Comment by mathiasbanda** [comment]
Okay thank you @jacobbrownlow 

I have sent them the message

**Comment by mathiasbanda** [comment]
@jacobbrownlow is any insight you guys can give me? The product team are not very helpful. We are now getting error 403 - non of these issues happen when we run tests. Surely it must be straight forward to see why the server is denying us (our customer)  access to the services

**Comment by MarkAKelly** [comment]
@mathiasbanda This now appears to be a separate issue to the one you raised, but still in the realms of authentication for the platform.

As the development team of the VAT API we can only support you so far in the live environments - as all live data is (rightly) protected, we only have access to live logs of traffic through the API.  In that way it is not as straight forward as us looking at the server and digging around to access data.

I'm getting in touch with SDST for you to find out the best solution for you currently.  I'll be in touch soon.

Mark

**Comment by mathiasbanda** [comment]
Thank you Mark

**Comment by Hollister** [comment]
We are getting this same behavior using the Sandbox environment. Initial authorisation works to get the initial access token, but then trying to use the refresh token to generate a new one returns the same error

**Comment by mathiasbanda** [comment]
Once the account was 'fixed' this issue went away
