### ISSUE TITLE
How to set up Agent and associate clients on the test service

### ISSUE THREAD

**Issue by kmanish86** [hmrc/vat-api#30]
I would like to set up an agent and associate clients with this user so that i could test the submissions of VAT returns using agent tokens.

**Comment by jonathanleather** [comment]
Hi @kmanish86 apologies for the delay in replying to your issue. Unfortunately at this point in time it is not possible to test as an agent. In order for this to be possible, some work needs to be carried out by another team. We currently do not possess any timelines for when this will be completed.

Cheers
Jon

**Comment by tahirmughaliris** [comment]
Are we now able to set up an agent and associate clients for testing purposes?

**Comment by jonathanleather** [comment]
Hi @tahirmughaliris 
Thank you for your question, unfortunately we are still unable to answer this question as it relates to the wider HMRC API Plaform and is not exclusive to the MTD Self Assessment and VAT APIs.

Could you please send your question to this email address SDSTeam@hmrc.gsi.gov.uk and your question will be dealt with.

Thanks and sorry for the inconvenience.
Jon
