### ISSUE TITLE
Retrieve VAT Obligations - Error code returning as Message

### ISSUE THREAD

**Issue by KilskyreMan** [hmrc/vat-api#302]
Hi Guys

Whilst testing error conditions for the "Retrieve VAT Obligations" API in sandbox mode, I noticed that error code "INVALID_DATE_FROM" gets returned as a Message and not as an error code as indicated by your [documentation](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0#_retrieve-vat-obligations_get_accordionl).

`"{\"statusCode\":400,\"message\":\"INVALID_DATE_FROM\"}"`

Is this by design or a mistake?

Cheers - Ian.

**Comment by GrahamHDawson** [comment]
Hi Ian,

I think that's correct for common (non VAT API) errors - see this documentation link

https://developer.service.hmrc.gov.uk/api-documentation/docs/reference-guide

and the 'Common API Errors' section.

By the way how did you force INVALID_DATE_FROM - my trials just get INVALID_DATE_RANGE errors.
Graham

**Comment by KilskyreMan** [comment]
Hi Graham,

I can get it at will against the sandbox whilst testing "/organisations/vat/{vrn}/obligations".

I set the "from" period to "999" and set "Gov-Test-Scenario" Header value to "QUARTERLY_FOUR_MET".

**Comment by MeliaDavies** [comment]
Hi @KilskyreMan 

This inconsistent error response is a known bug which the team is aware of. 
Unfortunately, we have been asked by some vendors not to fix it because this would be a breaking change for them.

Thanks
