### ISSUE TITLE
HMRC VAT Tutorial 3 /hello/user  - Delphi

### ISSUE THREAD

**Issue by Yuppski** [hmrc/vat-api#304]
Hi All

I'm trying the:-
Request an OAuth 2.0 authorisation code with the required scope
tutorial from:- https://developer.service.hmrc.gov.uk/api-documentation/docs/tutorials
and I'm using Delphi 10.1 with RESTClient and a Tfrm_OAuthWebForm.
The example says "The user will be redirected to the HMRC login screen. When they've submitted their credentials, they'll be asked to authorise your application to access the requested scope."
I'm not getting the HMRC login page, just a:-

Popup message saying
File download - Security Warning
Do you want to save this file, or find a program online to open it?
Name: http_400_webODC
Type: Unknown File Type, 6.15 KB
From ieframe.dll

FIND SAVE CANCEL

I'm only at the first stage:-
procedure TfrmMain.btnHello_User_RESTClient_Self_Bind_Test_1Click(Sender: TObject);
var
LURL: string;
wv: Tfrm_OAuthWebForm;
LToken: string;
begin
  /// step #1: get the auth-code
  LURL := 'https://test-api.service.hmrc.gov.uk/oauth/authorize';
  LURL := LURL + '?client_id=' + URIEncode (eHello_User_Client_ID.Text);
  LURL := LURL + '&scope=hello';
  LURL := LURL + '&redirect_uri=https://www.example.com/redirect'
  LURL := LURL + '&response_type=code'

  // optional
  // LURL := LURL + '&login_hint=' + URIEncode('user@example.com');

  Add_To_Memo(LURL, False{Clear_Memo});

  wv := Tfrm_OAuthWebForm.Create(self);
  try
    wv.OnTitleChanged := self.OAuth2Authenticator1_Hello_User_BrowserTitleChanged;
    wv.ShowModalWithURL(LURL);
  finally
    wv.Release;
  end;
end;

Any ideas what I've done wrong?
Hope that makes sense.
tia

**Comment by adamdavi3s** [comment]
I get this issue when the redirect URL is missing or incorrect

**Comment by macgrewal** [comment]
@Yuppski based on what @adamdavi3s has said above I'd try encoding the redirect URL so the code reads like this:
```
/// step #1: get the auth-code
LURL := 'https://test-api.service.hmrc.gov.uk/oauth/authorize';
LURL := LURL + '?client_id=' + URIEncode (eHello_User_Client_ID.Text);
LURL := LURL + '&scope=hello';
LURL := LURL + '&redirect_uri=' + URIEncode('https://www.example.com/redirect')
LURL := LURL + '&response_type=code'
```

**Comment by Yuppski** [comment]
Hi all

Thanks for the replies.

I've tried the following code:-
  LURL := 'https://test-api.service.hmrc.gov.uk/oauth/authorize';
  LURL := LURL + '?client_id=' + URIEncode(eHello_User_Client_ID.Text);
  LURL := LURL + '&scope=hello';
  LURL := LURL + '&redirect_uri=' + URIEncode('https://www.example.com/redirect');
  LURL := LURL + '&response_type=code';

and still get the same "File download - Security Warning" popup message.

Thanks

**Comment by Yuppski** [comment]
Just to add to this I've base my code on the project in the samples called"Embarcadero REST-Library - Demos" and the Google (Tasks) option. When that programs fails it does redirect to a Google page:-

"400. That’s an error.

Error: invalid_request
Missing required parameter: client_id
Learn more
Request Detailsresponse_type=code
client_id=
redirect_uri=urn:ietf:wg:oauth:2.0:oob
scope=https://www.googleapis.com/auth/tasks

That’s all we know."

but it uses:-

LURL := LURL + '&redirect_uri=' + URIEncode('urn:ietf:wg:oauth:2.0:oob');


My application problem gives the impression the redirect is not quite right.

**Comment by Yuppski** [comment]
@macgrewal

Thanks for the reply. I have registered and setup an application within the HMRC Developer Hub 

I have been issued the Client ID, Client Secret and Server Token.

I use the correct Client ID when testing but didn't want it published on this site so that's why it reads "1234" on the combined LURL. 

Thanks

**Comment by macgrewal** [comment]
@Yuppski I just used your URL (https://test-api.service.hmrc.gov.uk/oauth/authorize?client_id=1234&scope=hello&redirect_uri=https%3A%2F%2Fwww.example.com%2Fredirect&response_type=code) substituting the `client_id` and `redirect_uri` with values taken from my app (registered in the developer hub) and it works.

Please ensure the redirect url is the one specified in your app.

**Comment by Yuppski** [comment]
@macgrewal

Many thanks for the reply. I wasn't aware I had to add the redirect url to the HMRC Hub application.

Its now been added and I've now got the :-

HM Revenue & Customs
Authority to interact with HMRC on your behalf

page coming up.

I'll try the next stage thanks.

**Comment by macgrewal** [comment]
@Yuppski the issues section for this repo focuses on issues related to APIs related to VAT. Issues related to authorisation should be directed to the Software Developer Support Team (SDST) on SDSTeam@hmrc.gsi.gov.uk, they will be able to point you in the right direction.

**Comment by ABSCoder** [comment]
Hello @Yuppski,
Did you manage to implement all MTD functions? Please do share some of teh codes if possible.
Thanks.

**Comment by Yuppski** [comment]
@ABSCoder 

Are you working through the HMRC MTD tutorials?

https://developer.service.hmrc.gov.uk/api-documentation/docs/tutorials
