### ISSUE TITLE
Fraud prevention - Headers 

### ISSUE THREAD

**Issue by JimTurnerAtStirling** [hmrc/vat-api#305]
Can you tell me which Fraud Prevention header of these will eventually be required for the vat-api.  (From a Desktop application)?

The Gov-Client-Public-IP  is of particular concern because everywhere the application will be used, it will be on a local network without direct access to information about the public IP.

Will it be mandatory to have a value in this header (and indeed the other headers)?

Thanks.

**Comment by rbs-ben** [comment]
Yes I'd second the concern about the Gov-Client-Public-IP header for a desktop application.
Also the port number, which is generally allocated dynamically and so not known at the time the headers are initialised.

**Comment by GrahamHDawson** [comment]
Hi Jim,Ben,

I'm developing a desktop MTD VAT application and use

https://api.ipify.org/

to get the Gov-Client-Public-IP address. It's returned as a simple string eg 2.123.XX.XXX
In my case I'm using a port of LibCurl for Clarion to issue a simple HTTPs GET request to retrieve the string response.
Works well both locally on my development machine and on the work network.

I agree about the Port number though - that's not really retrievable for a desktop application.

Graham

**Comment by GrahamHDawson** [comment]
Just to add that I queried with the SDST on the 8th October asking when and which bits of the anti-fraud headers were going to become compulsory and they forwarded my question to 
**the area responsible for Fraud Prevention Headers**
So even they don't know the details :-(

Graham

**Comment by rbs-ben** [comment]
Thanks Graham, yes I'm using something similar, but it seems wrong to rely on a third party for something intended to prevent fraud (we can't guarantee the accuracy of the response), and besides this will still only give the IP for the network, not "The public IP address of the originating client machine" as per the requirements.

**Comment by JimTurnerAtStirling** [comment]
Thanks guys.  Seems we still don't have an clear answer.
I am aware of Graham's method. I just do not want to rely on the site being active. If https://api.ipify.org/ was unavailable, would calls to the vat-api be rejected?

**Comment by adamdavi3s** [comment]
I have to admit I’ll be building three layers of redundancy in but if the machine is on a local network you don’t have any choice but to go out to the outside world to retrieve the public IP

**Comment by macgrewal** [comment]
Hi All,

We've spoken to SDST and asked that they route your queries to the appropriate team.

Apologies for sending you round the houses but if you contact SDST on SDSTeam@hmrc.gsi.gov.uk they will put you in touch with the correct team.

Regards,

mac

**Comment by adamdavi3s** [comment]
Can we leave this open for one person to update when they hear back? Rather than all of us flooding emails to SDS team!

**Comment by Hollister** [comment]
That would be useful from my point of view. For me, quite a few of the headers seem to not fit. If you are submitting as a batch process for example it doesn't say that the client headers are not required, even though they make little sense

**Comment by Hollister** [comment]
There is a upcoming Q&A webinar on 14th November for the MTD VAT API's; I have raised this as a issue in my booking, referencing this issue and #218. If nothing else it will at least highlight that multiple people are asking the same question with no result

**Comment by GrahamHDawson** [comment]
We don't have (yet) an answer to this so why has it been closed?

Graham

**Comment by gbs-matt** [comment]
I wasn't able to attend the Q&A webinar due to all the slots being taken.  Did you get any answers to these questions?

**Comment by MKoppJones** [comment]
Can we please reopen this until we have a response? Been waiting since August for my response.

**Comment by Hollister** [comment]
The answer given on the Q&A webinar was "we don't know what we require yet", and that there *should* be an answer within the next couple of weeks.

It was a bit woolly how they would be communicated out when they are decided though

**Comment by MKoppJones** [comment]
@Hollister Thank you for an update,  a bit silly we are this far in and don't know this yet though

**Comment by jonathanleather** [comment]
Hi Folks

We can only apologise for the delay regarding the headers. We (the api team) are still waiting for the headers to be finalised by another team within HMRC, as a result we aren't able to progress this issue or share any information until this has happened. We don't currently have an ETA as to when they will be available but this is deemed a top priority by the programme and I have escalated the concerns raised in the various issue threads on here.

I have reopened this issue as it looks to be the most popular thread regarding the headers, keeping all discussions on this topic, in one place. 
@MKoppJones would you mind closing your issue #218 please? That way if other vendors have any issues going forward we can point them to one issue.

As soon as we know more, comms will be sent out through the usual channels (SDST / Github).

Thank you all for your patience with this.

Cheers
Jon

**Comment by davidpipe58** [comment]
Just wanted to add my voice to this - ours is a desktop application and I too am unhappy about relying on 3rd party websites in order to retrieve a public IP. I am also a bit stumped by the port number.

**Comment by PeterGGreen** [comment]
Me too.  Having just completed our MTD VAT work and awaiting production credentials, they have to ensure that these TXM anti-fraud headers work with desktop applications.  And I second the point about being uncomfortable relying on third party websites for live submissions (or at all).  If this is something HMRC deem necessary, then they must provide the service!

**Comment by GrahamHDawson** [comment]
My main worry would be about the Gov-Client-Multi-Factor header which implies our application would itself have to implement a 2-part authorisation procedure in addition to the 2-part authorisation procedure we already have to negotiate to submit to HMRC (see issue 351)

Like others using 3rd party websites to get IP addresses from a desktop application is not ideal.
If it's something HMRC require then **they** aught to provide the website we can use.
The port is just not possible for a desktop application.

Graham

**Comment by davidglassborow** [comment]
Also it feels like some of these headers would be on shaky ground under GDPR (like asking what credentials the user logged into the machine aka their NT username (`Gov-Client-User-ID`) - feels like a horrible security issue), and tracking the `Do Not Track` flag

**Comment by adamdavi3s** [comment]
Probably ok as it’s B2B (rather than B2C) which is no where near as controlled under GDPR (AFAIK!)

**Comment by davidglassborow** [comment]
I certainly wouldn't want my NT username leaked when using some desktop software for the company I work for

**Comment by adamdavi3s** [comment]
I completely agree with you in that sense but under GDPR I don’t think it’s an issue, except maybe for some sole traders / partnerships which are technically B2C (it’s a minefield)

As it’s all https you would hope that it wouldn’t leak!

**Comment by davidglassborow** [comment]
Agreed.  The header requirements seem overly broad and technically hard to implement.  Seems like a project manager copy and pasted it from a spreadsheet somewhere :wink:

**Comment by adamdavi3s** [comment]
Pretty sure it’s just a list of all available headers in the HMRC environment so could be used elsewhere? I’m certainly not doing anything with them until we get the clarification

**Comment by GrahamHDawson** [comment]
Hi Guys,

The MTD VAT documentation Reference section now has a link to a separate page with updated anti-fraud header information.

https://developer.service.hmrc.gov.uk/api-documentation/docs/fraud-prevention

Still going through it at the moment so can't really comment yet - except I notice the requirement for Port information from a desktop application is still there and I've no idea how we can get that.

Graham

**Comment by PeterGGreen** [comment]
Thanks for the link Graham.  My desktop app is working fine now (finally) and these TxM headers are too difficult to get and too "woolly" for my liking.  Why should I list all of the available IP addresses this PC can address?  Do I have to scan my LAN (probably triggering heuristic AV warnings)?  This whole thing needs a rethink from a desktop app point of view.

I have no problem storing a unique ID (I'll just use the PC name) for each client, but some of the information required is impossible/difficult to get.  And to raise the point, if we have a valid access token via OAUTH2 (either grant or refresh), I see little need for extra TxM headers at all...

**Comment by rbs-ben** [comment]
Thanks Graham.  Regarding the port, depending on what you're using to connect with it might be possible to set an explicit port rather that letting the OS choose one, in which case you'd be able to specify that.  But then you have to deal with what happens when the port is in use, which is an unreasonable extra layer of complexity we'd need to implement and maintain.

**Comment by davidglassborow** [comment]
It's nonsense, any local IP and port is going to mean nothing, everybody sits behind multiple levels of NAT these days.

**Comment by adamdavi3s** [comment]
@peterGGreen spot on sir

**Comment by rbs-ben** [comment]
@PeterGGreen - re: Gov-Client-Local-IPs, I read that as meaning they want all IP addresses of the client (so everything returned by a call to ipconfig in Windows for example)

**Comment by PeterGGreen** [comment]
@rbs-ben Fair enough, perhaps I misread that, but if so, what is the point of sending local IP addresses that will invariably be in the 10.x.x.x or 192.168.x.x range.  Seems pointless.

**Comment by rbs-ben** [comment]
Agreed, I've no idea how this could be useful.  Are they just storing it so in the event of an allegation of fraud they can use it as a comparison?  Will MTD calls end up being rejected if a user installs a new network card?  Who knows!

**Comment by MKoppJones** [comment]
At the end of the day, I am just glad we got these clarified, even though some are a little outlandish.

**Comment by adamdavi3s** [comment]
Anyone know if we can use the sandbox to validate what we’re sending in these?

**Comment by GrahamHDawson** [comment]
Although the anti-fraud header information has been clarified we **still** don't have any answer as to when (or if) these headers will be mandatory for MTD VAT.

It's obvious that some applications already have production credentials and are presumably doing live submissions without this information.

And I would have liked/expected developers to be emailed with a link to this updated info rather than having to discover it by chance.

Graham

**Comment by adamdavi3s** [comment]
Oh, this information has been around for ages then hasnt it? I assumed this was the final list for MTD, that’s frustrating

**Comment by rbs-ben** [comment]
This is definitely new/updated, I know because I'd already implemented some of the headers and now they've completely changed them.  And no, unfortunately I don't think there's any way of using the sandbox to validate header values, that would be very useful.

**Comment by adamdavi3s** [comment]
In case anyone hasn't had the email....

_"Dear Developer 
On the 18th October we advised you that we would be making changes to the fraud prevention header specification published on the Developer Hub. We have completed this work and version 2.0 of the fraud prevention header specification is now available on the Developer Hub .
This specification will apply to the MTD VAT API in April 2019. We recommend designing it into your applications now, to allow time to ensure your application is sending us the correct information. Let us know if you have any queries about the contents of the specification, or require any clarification.
We will be following up in January with more information about how we will work with you to ensure your applications are compliant.
Regards,"_

**Comment by GrahamHDawson** [comment]
Hi Adam,

Well I haven't received the email above - when did you get it ?

Graham

**Comment by adamdavi3s** [comment]
@GrahamHDawson  came through from the SDTeam about 30 seconds before I posted it on here!

**Comment by GrahamHDawson** [comment]
This is going to run and run - there's been an update to the Anti-Fraud Headers page today 11/12/2018

DESKTOP_APP_DIRECT applications will not now need to add the

Gov-Client-Public-IP and
Gov-Client-Public-Port

NB There may be other changes too, I've only checked for DESKTOP_APP_DIRECT changes.
Graham

**Comment by adamdavi3s** [comment]
Bah didn't get an email about that!

I'll give it a couple of weeks and then build with the list at that point I think, glad to see that the feedback is being listened to though

**Comment by jchharris** [comment]
Are there plans to update the tutorials (https://developer.service.hmrc.gov.uk/api-documentation/docs/tutorials) to include examples of how to collect the fraud prevention headers?

**Comment by theshillito** [comment]
If you're doing a "WEB_APP_VIA_SERVER", a lot of these fraud prevention headers are going to require JavaScript, especially "Gov-Client-Local-IPs" (where I'm using WebRTC, see https://github.com/diafygi/webrtc-ips for a demo). If someone has JavaScript disabled, does that count as "security measures reasonably beyond your control" 🤔, or should I just deny access 😒

**Comment by stuy1974** [comment]
Regarding the **Gov-Client-Device-ID** header when your connection method is **Web_App_Via_Server**
- Is storing a cookie with a uniqueId (Guid) on a user's machine, then sending this uniqueId as part of this header good enough to satisfy this requirement?

Note:
 - If a user used incognito mode, a new uniqueId would be generated and only used for the current session.
- If a user used a different browser, a new uniqueId would be generated and used for this browser
- A user could always delete this cookie!

**Comment by lukaszszczygiel-sage** [comment]
I got overall questions about the headers. 
1.The documentation state in some cases 
"If you cannot retrieve them due to operating system restrictions, then leave the header empty" Is there an expectation that it would be empty or we can omit sending empty header at all?
2. When the headers become mandatory on sandobx env?

**Comment by theshillito** [comment]
@lukaszszczygiel-sage I can answer your first point from this page https://developer.service.hmrc.gov.uk/api-documentation/docs/fraud-prevention

> If a header is not required for your connection method, then you can leave it out entirely when making your submission, or submit it with an empty header value.

>you might not be able to collect a value because: of operating system or platform restrictions [...] you must submit the header with an empty header value

So I would include all headers with the connection method you're using, but leave them empty if you can't collect the information.

**Comment by lukaszszczygiel-sage** [comment]
@theshillito Thanks for answer. I missed in the documentation. Sorry for that

**Comment by stuy1974** [comment]
It's could be clearer!?!

**Comment by GrahamHDawson** [comment]
We're still awaiting the promised help from the SDST about these headers ie this comment on the email of 10th Dec

> We will be following up in January with more information about how we will work with you to ensure 
> your applications are compliant.

Hopefully this will include making the test url validate the anti-fraud headers and return errors if they're not acceptable.
We also need clarification as to what will happen if a VAT submission doesn't have acceptable anti-fraud headers.

Graham

**Comment by hughfdjackson** [comment]
Hi all,

Thanks for the above questions + discussion.  I believe the original poster (@JimTurnerAtStirling)'s question has been answered: 

> Can you tell me which Fraud Prevention header of these will eventually be required for the vat-api. (From a Desktop application)?
> The Gov-Client-Public-IP is of particular concern because everywhere the application will be used, it will be on a local network without direct access to information about the public IP.
> Will it be mandatory to have a value in this header (and indeed the other headers)?
> Thanks.

For DESKTOP_APP_DIRECT, Gov-Client-Public-IP and Gov-Client-Public-Port are no longer required. 

For others on this thread - I realise there are other unanswered questions in here.  Each of those questions deserve their own issue.  If you feel those questions are still outstanding with the latest spec (https://developer.service.hmrc.gov.uk/api-documentation/docs/fraud-prevention), please raise a new issue and we'll respond to them there.

**Comment by pp07** [comment]
Hi,
 Now i my using Fraud Prevention  header in my Web application, but i can't understand it applying or not because it not reflect anything.

Anyone guide me ?
thanks in advance
