### ISSUE TITLE
HMRC VAT Tutorial 3.2 /hello/user - Delphi

### ISSUE THREAD

**Issue by Yuppski** [hmrc/vat-api#308]
Hi all

I'm working on "2. Exchange the OAuth 2.0 authorisation code for an access token" of the HMRC Tutorial "/hello/user "

I've managed to get the Authorization Code but when running the following code :-

This only occurs when building the Params at runtime.
  RESTClient1.Authenticator := OAuth2Authenticator1_Hello_User;
  RESTClient1.BaseURL := 'https://test-api.service.hmrc.gov.uk/oauth/token';
  RESTRequest1.Method := TRESTRequestMethod.rmGET;
  RESTRequest1.Params.AddItem('grant_type', 'authorization_code', TRESTRequestParameterKind.pkGETorPOST);
  RESTRequest1.Params.AddItem('client_id', eHello_User_Client_ID.Text, TRESTRequestParameterKind.pkGETorPOST);
  RESTRequest1.Params.AddItem('client_secret', eHello_User_Client_Secret.Text, TRESTRequestParameterKind.pkGETorPOST);
  RESTRequest1.Params.AddItem('redirect_uri', eHello_User_Redirect.Text, TRESTRequestParameterKind.pkGETorPOST);
  RESTRequest1.Params.AddItem('authorization_code', eHello_User_Authorization_Code.Text, TRESTRequestParameterKind.pkGETorPOST);
  RESTRequest1.Execute;

1. Enter User ID and Password
2. Click Grant Access
3. I get the Redirect Page and issued a Authorization Code
4. Get a Exception 404 Not found 
•in the 400 to 499 range if it didn't succeed because of a client error by your application

Using the same OAuth2Authenticator I:-
1. Right Mouse click the OAuth2Authenticator
2. Select Configure
3. Press Authorize
4. Enter the User Id and Password
5. Click Grant Access
6. I get issued a Access Token and Refresh Token with no errors.

I have tried the SDSTeam@hmrc.gsi.gov.uk and they suggest I use GitHub.

Any ideas what I'm missing in my code?

Hope that makes sense.
tia

**Comment by Yuppski** [comment]
Just to clarify this code gets called first:- 
  {$REGION '1. Get the the Authorisation Code'}
  wv := Tfrm_OAuthWebForm.Create(self);
  try
    wv.OnAfterRedirect := OAuth2Authenticator1_Hello_User_Redirect;
    wv.ShowModalWithURL(LURL);
  finally
    wv.Release;
  end;
  {$ENDREGION '1. Get the the Authorisation Code'}

Then the sequence from the Tfrm_OAuthWebForm displays:-
1. HM Revenue & Customs. Authority to interact with HMRC on your behalf. Click Continue.
2. HM Revenue & Customs. Sing In. User ID and Password. Sign In.
3. Click Grant Access
4. Issued the Authorization Code in the code on the OAuth2Authenticator1_Hello_User_Redirect Event.
5. Display my Redirect Page.
6. Close the Tfrm_OAuthWebForm. 

Following code is the executed:-
RESTClient1.Authenticator := OAuth2Authenticator1_Hello_User;
 RESTClient1.BaseURL := 'https://test-api.service.hmrc.gov.uk/oauth/token';
 RESTRequest1.Method := TRESTRequestMethod.rmGET;
 RESTRequest1.Params.AddItem('grant_type', 'authorization_code', TRESTRequestParameterKind.pkGETorPOST);
 RESTRequest1.Params.AddItem('client_id', eHello_User_Client_ID.Text, TRESTRequestParameterKind.pkGETorPOST);
 RESTRequest1.Params.AddItem('client_secret', eHello_User_Client_Secret.Text, TRESTRequestParameterKind.pkGETorPOST);
 RESTRequest1.Params.AddItem('redirect_uri', eHello_User_Redirect.Text, TRESTRequestParameterKind.pkGETorPOST);
 RESTRequest1.Params.AddItem('authorization_code', eHello_User_Authorization_Code.Text, TRESTRequestParameterKind.pkGETorPOST);
 RESTRequest1.Execute;

An Exception is raised when calling the RESTRequest1.Execute;

procedure TfrmMain.RESTRequest1HTTPProtocolError(Sender: TCustomRESTRequest);
begin
  // show error
  Add_To_Memo(Sender.Response.StatusText, False{Clear_Memo});
  Add_To_Memo(Sender.Response.Content, False{Clear_Memo});
 // Sender.Response.Content, = <!DOCTYPE html><!--[if lt IE 9]><html class="no-js lte-ie8"   
end;

The Sender.Response.StatusText, is "Not Found"
The Sender.Response.Content, is "<!DOCTYPE html><!--[if lt IE 9]><html class="no-js lte-ie8" 
...
"<title>HMRC Tax Platform - Page not found - 404</title>"
...

HMRC say  
•in the 400 to 499 range if it didn't succeed because of a client error by your application

I've check and re check the application but can see what's upsetting the code when passing the Authorization Code to Get the Access & Refresh Tokens.

**Comment by ma3574** [comment]
Hi @Yuppski 

Authorisation related questions are handled by the Software Developers Support Team, please drop an email to SDSTeam@hmrc.gsi.gov.uk with your specific requirements.

**Comment by highlysceptical** [comment]
Yuppski

Did you find a resolution to this?  You seem to be a few days ahead of me!

**Comment by highlysceptical** [comment]
I have been playing with this some more.  Can you not merely store the authorisation code (FAuthorisationCode in my example), create a new TOAuth2Authenticator and do:-

 with OAuth2_WithAccessToken do
                begin
                  AuthCode := FAuthorisationCode;
                  ChangeAuthCodeToAccesToken;
                  Add_To_Memo('Access Token: ' + AccessToken, False);
                  Add_To_Memo('Refresh Token: ' + RefreshToken, False);
                end;

This seems to work OK.

**Comment by FIFernandes** [comment]
@ghost! 

I'm am working on OAuth 2.0 authorisation code for an access token" of the HMRC Tutorial. I am trying to get an Authorization Code using OAuth2Authenticator, configure and the Authorize button. 

What am I missing?


![2020-08-04_12-27-16](https://user-images.githubusercontent.com/11407431/89288767-1406bb00-d64e-11ea-994f-14a0fa2b80d9.jpg)

**Comment by highlysceptical** [comment]
This might help to get you started ...

First, you need to request an Authorisation Code :-

> with OAuth2 do
  begin
    AccessToken := {Your access token};
    AuthorizationEndpoint := GBaseURL + '/oauth/authorize';
    ResponseType := TOAuth2ResponseType.rtCODE;
    TokenType := TOAuth2TokenType.ttBEARER;
  end;

> with RESTClient do
  begin
    Authenticator := OAuth2;
    BaseURL := URL {The URL you are trying to access};
    ContentType := 'application/json';
  end;

> with RESTRequest do
  begin
    Params.AddItem('scope', 'hello read:vat write:vat', pkGETorPOST);
    Params.AddItem('client_id', OAuth2Authenticator.ClientID, pkGETorPOST);
    Params.AddItem('redirect_uri', {Your Redirect URI}, pkGETorPOST);
    Params.AddItem('response_type', 'code', pkGETorPOST);
  end;

You then need to convert the Authorisation code into a token ...

> with OAuth2 do
  begin
    AccessToken := {Your access token};
    AuthorizationEndpoint := GBaseURL + '/oauth/authorize';
    ResponseType := TOAuth2ResponseType.rtTOKEN;
    TokenType := TOAuth2TokenType.ttNONE;
    AccessTokenEndpoint := GBaseURL + '/oauth/token';
    AccessTokenParamName := 'access_token';
    AuthCode := {Your authorisation code obtained from the previous request}
    RedirectionEndpoint := {Your Redirect URI};
    ChangeAuthCodeToAccessToken; // declared in REST.Authenticator.OAuth
  end;

**Comment by FIFernandes** [comment]
> 
> 
> This might help to get you started ...
> 
> First, you need to request an Authorisation Code :-
> 
> > with OAuth2 do
> > begin
> > AccessToken := {Your access token};
> > AuthorizationEndpoint := 'https://api.service.hmrc.gov.uk/oauth/authorize';
> > ResponseType := TOAuth2ResponseType.rtCODE;
> > TokenType := TOAuth2TokenType.ttBEARER;
> > end;
> 
> > with RESTClient do
> > begin
> > Authenticator := OAuth2;
> > BaseURL := URL {The URL you are trying to access};
> > ContentType := 'application/json';
> > end;
> 
> > with RESTRequest do
> > begin
> > Params.AddItem('scope', 'hello read:vat write:vat', pkGETorPOST);
> > Params.AddItem('client_id', OAuth2Authenticator.ClientID, pkGETorPOST);
> > Params.AddItem('redirect_uri', {Your Redirect URI}, pkGETorPOST);
> > Params.AddItem('response_type', 'code', pkGETorPOST);
> > end;
> 
> You then need to convert the Authorisation code into a token ...
> 
> > with OAuth2 do
> > begin
> > AccessToken := {Your access token};
> > AuthorizationEndpoint := 'https://api.service.hmrc.gov.uk/oauth/authorize';
> > ResponseType := TOAuth2ResponseType.rtTOKEN;
> > TokenType := TOAuth2TokenType.ttNONE;
> > AccessTokenEndpoint := 'https://api.service.hmrc.gov.uk/oauth/token';
> > AccessTokenParamName := 'access_token';
> > AuthCode := {Your authorisation code obtained from the previous request}
> > RedirectionEndpoint := {Your Redirect URI};
> > end;

One thing I am not sure of is the RedirectionEndpoint URI. My application is an MS windows exe not a website.
AccessToken := {Your access token};  on line 3, which token is this if it is to be generated.


Thank you very much for your help.

**Comment by highlysceptical** [comment]
My application is a Windows exe as well. 

If I remember correctly, I selected a port at random and made my RedirectionEndpointURI https://localhost: {my selected port number}.  I then registered the URI on the HMRC Developer Hub (Application Details | Redirect URIs). You then need to set the OAuth2 RedirectionEndpoint to the same value.

There is an error in my code though.  You obviously do not know the Access token where I put {Your access token}, so you do not need to provide that.  You do, however, need to provide your ClientID and ClientSecret like this:-

> with OAuth2 do
begin
AuthorizationEndpoint := 'https://api.service.hmrc.gov.uk/oauth/authorize';
ResponseType := TOAuth2ResponseType.rtTOKEN;
TokenType := TOAuth2TokenType.ttNONE;
AccessTokenEndpoint := 'https://api.service.hmrc.gov.uk/oauth/token';
AccessTokenParamName := 'access_token';
AuthCode := {Your authorisation code obtained from the previous request}
ClientID := {Your client ID}
ClientSecret := {Your client secret}
RedirectionEndpoint := {Your Redirect URI};
end;

This should hopefully get it working for you.

**Comment by FIFernandes** [comment]
> 
> 
> My application is a Windows exe as well.
> 
> If I remember correctly, I selected a port at random and made my RedirectionEndpointURI https://localhost: {my selected port number}. I then registered the URI on the HMRC Developer Hub (Application Details | Redirect URIs). You then need to set the OAuth2 RedirectionEndpoint to the same value.
> 
> There is an error in my code though. You obviously do not know the Access token where I put {Your access token}, so you do not need to provide that. You do, however, need to provide your ClientID and ClientSecret like this:-
> 
> > with OAuth2 do
> > begin
> > AuthorizationEndpoint := 'https://api.service.hmrc.gov.uk/oauth/authorize';
> > ResponseType := TOAuth2ResponseType.rtTOKEN;
> > TokenType := TOAuth2TokenType.ttNONE;
> > AccessTokenEndpoint := 'https://api.service.hmrc.gov.uk/oauth/token';
> > AccessTokenParamName := 'access_token';
> > AuthCode := {Your authorisation code obtained from the previous request}
> > ClientID := {Your client ID}
> > ClientSecret := {Your client secret}
> > RedirectionEndpoint := {Your Redirect URI};
> > end;
> 
> This should hopefully get it working for you.

Thank you very much for this, much appriacted. I will give it a go

**Comment by highlysceptical** [comment]
Let me know how you get on.

**Comment by FIFernandes** [comment]
I am trying to request the AuthorisationCode for hello/application and I get. I have set up the redirect URL.

{"code":"INVALID_CREDENTIALS","message":"Invalid Authentication information provided"}

procedure TForm3.btnReqAuthorisationCodeClick(Sender: TObject);
var
  jValue: TJSONValue;
  sClientID, sClientSecret: string;
  sToken, sAuthCode: string;
begin
  mmJSONmsg.Lines.Clear;
  sClientID := 'XXXX';
  sClientSecret := 'XXXX';

  with OAuth do
  begin
    // AccessToken := {Your access token};
    AuthorizationEndpoint := 'https://test-api.service.hmrc.gov.uk/hello/application';
    RedirectionEndpoint := 'https://localhost:80';

    ResponseType := TOAuth2ResponseType.rtCODE;
    TokenType := TOAuth2TokenType.ttBEARER;

    ClientID := sClientID;
    ClientSecret := sClientSecret;

    // OAuth.ResponseType := TOAuth2ResponseType(TOAuth2ResponseType.rtTOKEN);
    // OAuth.TokenType := TOAuth2TokenType(TOAuth2TokenType.ttNONE);
    // OAuth.AccessTokenEndpoint := 'https://test-api.service.hmrc.gov.uk/oauth/token';
    // OAuth.AccessTokenParamName := 'access_token';

    // OAuth2Authenticator1.AuthCode := sAuthCode;
    // ChangeAuthCodeToAccesToken;
  end;

  with RESTClient do
  begin
    Authenticator := OAuth;

    BaseURL := 'https://test-api.service.hmrc.gov.uk/hello/application'; { The URL you are trying to access };
    ContentType := 'application/json';
  end;

  with RESTRequest do
  begin
    Params.Clear;
    Params.AddItem('scope', 'hello read:vat write:vat', pkGETorPOST);
    Params.AddItem('client_id', OAuth.ClientID, pkGETorPOST);
    Params.AddItem('redirect_uri', 'http://localhost:80', pkGETorPOST);
    Params.AddItem('response_type', 'code', pkGETorPOST);
    Params.AddItem('Accept', 'application/vnd.hmrc.1.0+json');
  end;
  RESTRequest.Execute;

  jValue := RESTResponse.JSONValue;
  mmJSONmsg.Text := jValue.ToString;
end;

**Comment by highlysceptical** [comment]
At the moment, I cannot spot what you are doing wrong.  However, the choice of port 80 seems rather odd, and could be your problem.  That port is generally used for other things, so I would suggest finding a port that is not currently in use, and setting that as your redirectendpoint uri.

Other than that, I cannot currently see why it doesn't work, as I have just successfully run it on my computer - I take it that you have set up some means of getting the authorization code from HMRC - I use the Tfrm_OAuthWebForm (declared in the REST.Authenticator.OAuth unit, I think)

**Comment by FIFernandes** [comment]
OK let's recap
1. I have changed the port 1434 (also changed at HMRC).
2. I use the sandbox https://test-api
3. Ok, I don't have the Tfrm_OAuthWebForm setup, so that's what I am looking at (I was under the assumption that the RESTResponse.Content would hold the authorization code from HMRC).
4. Also I assumed that filling in the configure below would get the authorization code.

Can you send me the sample code you are running?

![2020-08-11_11-55-06](https://user-images.githubusercontent.com/11407431/89889550-b16f6b00-dbc9-11ea-84b4-26a4bf5d4ddc.png)

**Comment by highlysceptical** [comment]
As far as I am aware, the only way to get an Authentication Code is to interract with the HMRC website, hence the requirement to use a mechanism such as Tfrm_OAuthWebForm.

When you issue the RESTRequest above

> with RESTRequest do
begin
Params.Clear;
Params.AddItem('scope', 'hello read:vat write:vat', pkGETorPOST);
Params.AddItem('client_id', OAuth.ClientID, pkGETorPOST);
Params.AddItem('redirect_uri', 'http://localhost:80', pkGETorPOST);
Params.AddItem('response_type', 'code', pkGETorPOST);
Params.AddItem('Accept', 'application/vnd.hmrc.1.0+json');
end;
RESTRequest.Execute;

you should get a RESTResponse StatusCode of 200, which means that it has been successful.  Then, you need to interract with the HMRC website to get the Authorisation Code - something like this - I am using the variable FAuthorisationCode to store the string value returned by the HMRC website.  (I don't understand why the website is not formatting this correctly - the following is all a single block of code that I have tried to include as a quote, but it is not working properly)

> procedure GetAuthorisationCode(const AURL: string; var DoCloseWebView: boolean);
  var
    LATPos: integer;
    LToken: string;

  begin
    LATPos := Pos('code=', AURL);
    if (LATPos > 0) then
      begin
        LToken := Copy(AURL, LATPos + 5, length(AURL));
        if (Pos('&', LToken) > 0) then
          begin
            LToken := Copy(LToken, 1, Pos('&', LToken) - 1);
          end;

        FAuthorisationCode := LToken;
        if (LToken <> '') then
          DoCloseWebView := TRUE;
      end;
  end;


with RESTRequest do
  begin
    Params.Clear;
    Params.AddItem('scope', 'hello read:vat write:vat', pkGETorPOST);
    Params.AddItem('client_id', OAuth.ClientID, pkGETorPOST);
    Params.AddItem('redirect_uri', 'http://localhost:80', pkGETorPOST);
    Params.AddItem('response_type', 'code', pkGETorPOST);
    Params.AddItem('Accept', 'application/vnd.hmrc.1.0+json');
    end;
    RESTRequest.Execute;

    case RESTResponse.StatusCode of
      200:
        begin
          AuthURL := RESTResponse.FullRequestURI;
          WebForm := Tfrm_OAuthWebForm.Create(Self);
          with WebForm do
            begin
              OnAfterRedirect := GetAuthorisationCode;
              Browser.Navigate(AuthURL);
              if (TVarData(Browser.OleObject.Document).VDispatch <> nil) then
                Browser.OleObject.Document.Body.Style.Zoom := 0.75;

              ShowWithURL(AuthURL);

              // interract with HMRC website to get the authorisation code ...
            end;
        end;
    end;
  end;

**Comment by FIFernandes** [comment]
I am getting Error 401 on the RESTRequest.Execute;

{"code":"INVALID_CREDENTIALS","message":"Invalid Authentication information provided"} So I need to find out whats wrong there.

**Comment by highlysceptical** [comment]
As I don't understand what you have created, I cannot really comment on it.  However, I have written a procedure for you, which you can download from ftp://ftp.acousticdesign.co.uk/, which, when used with the GetAuthorisationCode procedure I gave you yesterday should enable you to connect, get an authorisation code and convert it into an access token.  (You will need to provide a username and password, both of which are "Guest")

I have run this procedure today with my Client ID and Client Secret and it works, so if it doesn't work for you, you had better check that you are using the correct ID, Secret etc.

**Comment by FIFernandes** [comment]
Ahh, getting somewhere, I was going wrong with the Tfrm_OAuthWebForm. I will work on it the next few days. 

I owe you are beer.

![2020-08-13_10-14-02](https://user-images.githubusercontent.com/11407431/90238165-5fbf1e80-de1d-11ea-8ccb-8d1b795f2e0b.png)
