### ISSUE TITLE
Change to scope required for viewing VAT Return

### ISSUE THREAD

**Issue by GrahamHDawson** [hmrc/vat-api#309]
Hi There,

I see from https://github.com/hmrc/vat-api/commit/57f0190c071d114f865b219ec222f8473151f799 and
https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0#_view-vat-return_get_accordion
 that the scope for the View VAT Return API has changed from write:vat to read:vat
It may be a good idea to email developers when breaking changes such as this occur.

Graham

**Comment by adamdavi3s** [comment]
It was sent as a notification of a merge via GitHub , as a developer the first thing I did was subscribe to make sure I was notified of changes so it’s worth doing

**Comment by GrahamHDawson** [comment]
Hi Adam,

How do I subscribe to get the change notifications?
I **think** I've done it now but I'm not a GitHub user normally so if you could detail the steps required I'd appreciate it.

Graham

**Comment by adamdavi3s** [comment]
Hi Graham,

It’s simply a case of “watching” the repository, you’ll get a whole bunch of emails about issues etc but it’s the commit notifications you want to keep an eye out for (I use email rules)

Kind regards

Ada

**Comment by GrahamHDawson** [comment]
OK thanks Adam I'm now **watching***

Graham

**Comment by macgrewal** [comment]
Morning @GrahamHDawson, comms will be out shortly (today).

@adamdavi3s watching the commits is good to keep on top of changes but just a word of warning, code deployed to the sandbox is not always representative of master. We are working towards having a CD pipeline that includes the Sandbox but aren't there yet.

**Comment by macgrewal** [comment]
Morning @GrahamHDawson, comms will be out shortly (today).

@adamdavi3s watching the commits is good to keep on top of changes but just a word of warning, code deployed to the sandbox is not always representative of master. We are working towards having a CD pipeline that includes the Sandbox but aren't there yet.

**Comment by macgrewal** [comment]
Morning @GrahamHDawson, comms will be out shortly (today).

@adamdavi3s watching the commits is good to keep on top of changes but just a word of warning, code deployed to the sandbox is not always representative of master. We are working towards having a CD pipeline that includes the Sandbox but aren't there yet.

**Comment by macgrewal** [comment]
Morning @GrahamHDawson, comms will be out shortly (today).

@adamdavi3s watching the commits is good to keep on top of changes but just a word of warning, code deployed to the sandbox is not always representative of master. We are working towards having a CD pipeline that includes the Sandbox but aren't there yet.

**Comment by macgrewal** [comment]
Morning @GrahamHDawson, comms will be out shortly (today).

@adamdavi3s watching the commits is good to keep on top of changes but just a word of warning, code deployed to the sandbox is not always representative of master. We are working towards having a CD pipeline that includes the Sandbox but aren't there yet.
