### ISSUE TITLE
Get VAT obligations - Only want open periods - Getting fulfilled too.

### ISSUE THREAD

**Issue by PeterGGreen** [hmrc/vat-api#311]
Hi,

I construct the request asking for only open periods, like this ...

      // Set up the call
      string sURL = "https://test-api.service.hmrc.gov.uk/organisations/vat/" + sVRN + "/obligations" +
                    "?from=2018-01-01" +
                    "&to=2018-12-31" +
                    "&status=O";

... but the response is this ...

{"obligations":[{"start":"2017-01-01","end":"2017-03-31","due":"2017-05-07","status":"F","periodKey":"18A1","received":"2017-05-06"},{"start":"2017-04-01","end":"2017-06-30","due":"2017-08-07","status":"O","periodKey":"18A2"}]}

... which clearly is including status "F" periods.

Am I missing something or is the response wrong?

Cheers,

Peter

**Comment by PeterGGreen** [comment]
OK, I see that it's because this is the test end point and that leaving the parameter blank returns fixed data (1 fulfilled, 1 open), but I still think even the test service ought to correctly filter based on the request.

**Comment by jonathanleather** [comment]
Hi @PeterGGreen 

The test environment does not have a fully functioning backend, only stubs to support your testing.
This particular end point is stateless, so as a result it relies on the gov-test-scenarios which can be found in the documentation. As a trade off for this solution we do lose the filters as you have mentioned but it does give us much more flexibility with the scenarios that we can provide you.

There should be enough scenarios to test the majority of what you need but if there are others, please do let us know and we can look to improve them for you.

Cheers
Jon

**Comment by PeterGGreen** [comment]
Hi Jon,

Yes I spotted that.  But it would make the development easier/less confusing for developers, if the response matched the filters that were used.  Even if there isn't a full back end, it shouldn't be difficult to filter the results based on the request parameters.

Indeed, looking at the example above, there should be no obligations returned, given the dates of the periods and the start/end dates requested.

Cheers,

Peter

**Comment by jonathanleather** [comment]
I can understand that, unfortunately everything is driven by the gov-test-scenarios.
I'll pass your comments on to the project team. 

Do you mind if I close the issue?
Meanwhile i'll look into your other issue.

Cheers
Jon

**Comment by PeterGGreen** [comment]
Hi Jon,

It's a good idea to have gov-test-scenarios that drive the response, but it's just as important that those responses obey the rules of the submission.  In fact, I'd add more features to the gov-test-scenarios so that you can get a response you need for testing (i.e. dates, period code etc).

Cheers,

Peter
