### ISSUE TITLE
Displaying Period Key

### ISSUE THREAD

**Issue by pharry22** [hmrc/vat-api#312]
On reading through the recent Pre CGL-Exit Event.pdf document.

There is an entry when referring to the Period key it says “Not recommended it is shown to customer”.  
Are you able to explain what is behind this recommendation? At the moment we are displaying this information and we are wondering why we shouldn’t.

**Comment by adamdavi3s** [comment]
This should help:
https://github.com/hmrc/vat-api/issues/294

**Comment by pharry22** [comment]
Thanks that has resolve this for me.
