### ISSUE TITLE
Clarification on `Receipt-ID` and `formBundleNumber`

### ISSUE THREAD

**Issue by kmanish86** [hmrc/vat-api#313]
Hi Team,
On a successful VAT submission we would like to share a confirmation number / acknowledgement number to our users which they can persist for any future communication with HMRC if needed.

Can you please share which of the fields will be ideal for us to share with our users ?
Would it be `Receipt-ID` from the header or the `formBundleNumber` number the response payload.

**Comment by GrahamHDawson** [comment]
Hi kmanish,
Take a look at issue #104 which asked the same question back in April and is still awaiting an answer.

Graham

**Comment by jonathanleather** [comment]
@kmanish86 @GrahamHDawson 

The backend teams have informed me that the `formBundleNumber` would be the best to use.

Cheers
Jon
