### ISSUE TITLE
Clarification for error 403 'CLIENT_OR_AGENT_NOT_AUTHORISED' for Get VAT Obligations

### ISSUE THREAD

**Issue by kmolchawa** [hmrc/vat-api#315]
Hi there,

I receive the error above when attempting to get my vat obligations. The OAuth 2.0 process gives me an access token seemingly without error.

Is this the access token not being authorised? What else could this error be?

**Scope:** read:vat

**Access Token POST**
client id, secret, and code omitted

"grant_type","authorization_code" 
"redirect_uri","urn:ietf:wg:oauth:2.0:oob"

I had used the Test User Service instead of the Test User API to create a test organisation.
User ID
861715043146

Password
xkvgmhpiprKn

Self Assessment UTR
2000073829

Corporation Tax UTR
8000000203

Employer Reference
935/V9PL6C7XBJ

VAT Registration Number
666172698

Gov-Test-Scenario left default.
**params:**
from = "2018-01-01"
to = "2018-12-31"

**Request URI:**
https://test-api.service.hmrc.gov.uk/organisations/vat/666172698/obligations?from=2018-01-01&to=2018-12-31

**Headers:**
Accept: application/vnd.hmrc.1.0+json
Authorization: Bearer (redacted)

**Response payload**
 {"code":"CLIENT_OR_AGENT_NOT_AUTHORISED","message":"The client and/or agent is not authorised."}"

**Comment by khabut** [comment]
Hi,

You have to use the API to create a user because I had the same problem.

Khalid
