### ISSUE TITLE
Length of VRN, UserID, UserPassword, AccessToken and RefreshToken etc

### ISSUE THREAD

**Issue by GrahamHDawson** [hmrc/vat-api#316]
Hi There,

We seem to be missing some basic information about the length of data values.
I know what they *seem* to be in the returned test responses and test users - but it would be good to see documentation stating the lengths that can be expected 'live'.

Items used in request ie
VRN
UserID
UserPassword
AccessToken
RefreshToken

Items returned from a VAT submission ie
FormBundleNumber
ChargeRefNumber
ReceiptID
CorrelationID

We have to store these things in a database and it would be better to be able to assign proper data lengths rather than having to (over) estimate.

Graham

**Comment by MarkAKelly** [comment]
Hi @GrahamHDawson,

I'll do my best with these.

- VRN will always be a 9 digit number.
- Form bundle number should be a 12 digit number.
- Charge ref will be a string between 1 and 16 characters.
- ReceiptID is something we consume from another internal HMRC service.  The creators of this service haven't given us the full specification for that field, although it is declared as a UUID string.  
- Correlation ID is a 36 character string.

Hope this helps,

Mark

**Comment by GrahamHDawson** [comment]
Thank Mark that's great.
Assume ReceiptID is also 36 character string as well (standard UUID format)

Graham

**Comment by GrahamHDawson** [comment]
Obviously this really needs to be documented somewhere.

Graham

**Comment by MarkAKelly** [comment]
Hi Graham,

You are correct the Receipt ID is in the standard UUID format.

We have a technical writer looking at the documentation for this API, and I will pass on the recommendation that these are added where possible.

Mark

**Comment by GrahamHDawson** [comment]
Thanks Mark,

Can I just add that IMHO webpages are **not** documentation.

When I worked on Payroll End of Year submissions using the XML format developers could download a Technical Pack which consisted of several PDF files and XML  example files and XSD schema files.
Those files had detailed descriptions of everything.

Webpages and GitHub issues (difficult to search) are no substitute for proper docs.

Graham

**Comment by GrahamHDawson** [comment]
If you could add the information give above to the FAQ Wiki section ie

VRN will always be a 9 digit number.
Form bundle number should be a 12 digit number.
Charge ref will be a string between 1 and 16 characters.
ReceiptID is a 36 character string.
Correlation ID is a 36 character string.

Then I can close this post.

Graham

**Comment by jonathanleather** [comment]
Hi @GrahamHDawson 

The detail above has now been added to the documentation.
Thanks for raising.

Cheers
Jon
