### ISSUE TITLE
Transition from old to new submissions

### ISSUE THREAD

**Issue by GrahamHDawson** [hmrc/vat-api#318]
Hi There,

Am I correct in thinking that **any** submission made after 1st April 2019 must be via the new API?
Even if that submission covers a VAT period from the previous year?

Most of our users submit quarterly so they'd normally close the last quarter of 2018/19 on the 31st March and report within the next couple of weeks.
So should that submission, covering 1st January 2019 to 31st March 2019 be made using the old or the new submission process?

Graham

**Comment by ma3574** [comment]
Hi Graham, 

Thanks for your question; unfortunately this is more a business decision and not a technical decision. As such we are unable to assist. please raise a query with the Software Developers Support Team at SDSTeam@hmrc.gsi.gov.uk and they will be able to provide an answer. Apologies for not being able to provide a suitable answer.

Kind regards
Muhammed

**Comment by GrahamHDawson** [comment]
Thanks Muhammed,

I've emailed the SDSTeam but they're very slow to respond to such queries.
(understandably as they deal with **all** areas of software and not just VAT)
We really need to be able to get quick answers to queries from a single contact point and not be redirected from one place to another all the time (sorry rant over :-) )

Graham

**Comment by GrahamHDawson** [comment]
Well I've had a very quick initial response from the SDSTeam as follows...

In short, yes, any submission made on or after 1st April must be submitted via the API, therefore your example regarding your submission period ending on 31st March will not be submitted using the new JSON API’s. Please read VAT Notice 700/22 (2.1.1) If you do wish to submit via the API previous to April you’ll have to join the Public BETA. 

Which seem contradictory to me so I've asked for further clarification.

The VAT Notice 700/200(2.1.1) that is quoted says...

2.1 .1 Find out when the Making Tax Digital rules start
The Making Tax Digital rules apply from your first VAT period starting on or after 1 April 2019. A ‘VAT period’ is the inclusive dates covered by your VAT Return.

Which implies that for my example quarterly based user the first new REST API submission will at the end of the 1st April to 30th June VAT period ie 1st July 2019 at the earliest.

Graham

**Comment by ma3574** [comment]
Hi Graham, 

Happy to see you've received the information required. If there is anything further required from the vat-api team on this issue please re-open. 

Kind regards
Muhammed
