### ISSUE TITLE
Could there be an FAQ section here so that issues/queries are not repeated?

### ISSUE THREAD

**Issue by GrahamHDawson** [hmrc/vat-api#319]
As the subject line - I'm sure it would help to avoid repeat questions.

Graham

**Comment by jonathanleather** [comment]
Hey @GrahamHDawson 

This is something we are currently looking into, as we know how beneficial it would be. 
But thank you for the suggestion, keep them coming!

Cheers
Jon

**Comment by GrahamHDawson** [comment]
I see there's now a fledgling FAQ section in the Wiki so I'll close this.
Many thanks.

Graham
