### ISSUE TITLE
HMRC User Auth Request - State Parm Reformat Issue

### ISSUE THREAD

**Issue by acory32590** [hmrc/vat-api#321]
Hello,

This issue was found while testing the VAT API.  While the issue itself pertains to the HMRC website and not this particular API, I'm posting it here as there isn't an Issues tab on the HMRC website github.

Following along with this flow:

https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints

...We pass along an encoded internal redirect URI into the state parameter, and in this internal redirect URI we contain internal parameters separated by special characters such as = and &.  We anticipate the state parameter to remain encoded when sent back to us; however, after logging in on the user authentication step, the two characters '%26' and '%3D' respectively are decoded back to '&' and '='.

I was wondering if this is something the HMRC dev team could look into & let us know if this is something they could address and fix?

Thanks,

-Andrew

**Comment by jonathanleather** [comment]
Hey @acory32590 

I have raised a ticket with the API platform team to get this looked into.
Once it's been investigated, one of the team will come back and update this thread.

Cheers
Jon

**Comment by ma3574** [comment]
Hi @acory32590 

The platform team have identified this as a known issue and have raised it on their backlog to impact and look at potential solutions. Unfortunately there's no ETA on when this will be fixed. 

Thanks

**Comment by acory32590** [comment]
Hi @ma3574 

This is great news, thanks for the information!

Would there be any way to tie our contact info to the backlog issue?  We would need to know of this particular issue's release date (pending it being fixed) as we would need to adjust our application's state parameter constructor.  Otherwise, if the fix for this issue suddenly rolls out, our authentication process will break.

Thanks!

-Andrew

**Comment by mtd-api-team** [comment]
We have spoken to the Platform Team and it looks like there are no plans to implement a change for this issue. Please continue to use the implementation that you have working and it will continue to work. Sorry we were not able to reach a better outcome to this issue.
