### ISSUE TITLE
Bug - API ViewVATReturns endpoint does not format values as stated in documentation

### ISSUE THREAD

**Issue by GrahamHDawson** [hmrc/vat-api#322]
**Note: Please read before raising an issue**. This repository's issues are reserved for **Technical** queries relating to the VAT-API Only. 
If your issue falls into any of the below categories please contact SDST at SDSTeam@hmrc.gsi.gov.uk:
- Issues relating to subscribing/registering to use the API Platform, MTD enrolment / de enrolment  / registration for VAT / BETA etc
- Issues relating to OAuth2
- Issues relating to integrating with the API Platform (setting up an application/access)
- Vendor application software questions (code examples in .NET / VB6 etc.)
- Business related questions
- Scheduled maintenance days / windows
- Onboarding 
- Performance metrics
- Questions relating to the process pre MTD

* **I'm submitting a ...**
  - [x] Bug - API
  - [ ] Bug - Documentation
  - [ ] Improvement
  - [ ] Feature request
  - [ ] Support request

* **What is the current behaviour?**

* **What is the expected behaviour?**

* **Other information** (e.g. detailed explanation, screenshots, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by GrahamHDawson** [comment]
Hi There,
According to the documentation the ViewVATReturn endpoint should format the returned numeric values in exactly the same way that we're required to submit them
ie the first 5 values should show 2 decimal places

But the 'canned' responses show no decimal places and if you submit a return and then view it you get just one decimal place back eg 100.50 is returned as 100.5

The responses should match the documentation.

Graham

**Comment by GrahamHDawson** [comment]
Hi Jacob,

I've no problem with the current return formatting as long as that formatting is fully documented in the text and the examples.

Graham

**Comment by jacobbrownlow** [comment]
Hi Graham

I have just changed the documentation examples for all of vat-api to better represent the decimal places. This will be deployed to Sandbox/Prod as soon as possible.

Regards, Jacob
