### ISSUE TITLE
Invalid format on date errors on obligations, liabilities and payments endpoints

### ISSUE THREAD

**Issue by paulvickery** [hmrc/vat-api#323]
On calling the obligations, payments or liabilities endpoints in cases where the dates are invalid, we are seeing the error returned in an unexpected format. It is not matching the format in the documentation. 

The responses are returned in the format:
```
{
  "statusCode": 400,
  "message": "DATE_FROM_INVALID"
}
```

The documentation states that errors will be returned as:
```
{
  "code": "DATE_FROM_INVALID",
  "message": "Invalid date from",
}
```

This results in our code not being able to report a sensible error message to the user. Can you please tell me whether this is expected for these types of errors?

**Comment by ma3574** [comment]
Hi @paulvickery 

Sorry that this is causing issues. Please see https://github.com/hmrc/vat-api/issues/242 for a full discussion around this topic.
