### ISSUE TITLE
Authorisation URL

### ISSUE THREAD

**Issue by upendra-rathore** [hmrc/vat-api#324]
Hi there,

I'm submitting a support request.

I need the Live Authorisation URL for the Agent and Individual to redirect the user to HMRC portal for login and grant authority process.

Thanks

**Comment by mathiasbanda** [comment]
I believe it is the same for either: https://api.service.hmrc.gov.uk/oauth/token

**Comment by upendra-rathore** [comment]
Thanks, @mathiasbanda,

I have this above URL on developers hub.
however, when I googled some of the things related to MTD VAT, I have navigated to **Guidance for MTD VAT: Service availability and issues** and there I click the hyperlink sign in to **Making Tax Digital for VAT** and it redirects me to below link.

Sign in to MTD VAT: https://www.tax.service.gov.uk/gg/sign-in?continue=%2Fvat-through-software%2Fsign-up%2Fresolve-vat-number&origin=vat-sign-up-frontend

Guidance for MTD VAT: Service availability and issues: https://www.gov.uk/government/publications/making-tax-digital-for-vat-service-availability-and-issues/making-tax-digital-for-vat-service-availability-and-issues

Please advise how shall we proceed.

Awaiting the positive response

Thanks

**Comment by mathiasbanda** [comment]
@upendra-rathore have you signed up as a developer? If not that would be the starting point. Then use your developer / product credentials for MTD-related activities using the published API
