### ISSUE TITLE
How can we tell Access Code is for an Agent or Not

### ISSUE THREAD

**Issue by mathiasbanda** [hmrc/vat-api#325]
This is the text on the authorisation journey

Apparently the declaration needs to be relevant for an Agent or non agent. You guys haven't said anything about this. Are we suppose to be scrapping the screen to figure this out? 

If I know the access code was for an agent I can store that data somewhere but right now I have no clue have to determine that. Can u guys point me in the right direction please.

This authority will last for 18 months. You can remove this authority at any time.
▼I'm an agent, which account do I sign into? 

If you’re signing in to use the Self Assessment Pre-Population APIs, use the account that’s enrolled for Self Assessment for Agents - that’s the same account you use to access the HMRC Agent Portal.

If you’re signing in to use the Making Tax Digital for Business APIs, use your Agent Services account.

**Comment by macgrewal** [comment]
@mathiasbanda Can you post a link to the text you're referring to? I'm having difficulty on locating it.

**Comment by mathiasbanda** [comment]
That first page of the authorisation journey there an a button to say I am an agent. click on it. I would have to ward through code to give you the link as we have to include out product credentials to navigate to it in the first place.

The complete text here. 
HM Revenue & Customs 




Authority to interact with HMRC on your behalf

Farmplan Business Manager needs permission to interact with HMRC on your behalf. To grant this authority, you'll need to: 
1.Sign in to your Government Gateway account.
2.Enter the 6 digit access code we'll send to your mobile phone, landline or other device.
3.You might need to confirm who you are by answering some security questions on, for example, your passport, P60 or other documents.
4.Grant authority to interact with HMRC on your behalf.

This authority will last for 18 months. You can remove this authority at any time.
▼I'm an agent, which account do I sign into? 

If you’re signing in to use the Self Assessment Pre-Population APIs, use the account that’s enrolled for Self Assessment for Agents - that’s the same account you use to access the HMRC Agent Portal.

If you’re signing in to use the Making Tax Digital for Business APIs, use your Agent Services account.

Continue

**Comment by macgrewal** [comment]
Hi @mathiasbanda,

Below is some guidance when creating new issues. Your issue relates to OAuth2 (mentioned in the list). Please contact SDST at SDSTeam@hmrc.gsi.gov.uk

> **Note: Please read before raising an issue**. This repository's issues are reserved for **Technical** queries relating to the VAT-API Only. 
> If your issue falls into any of the below categories please contact SDST at SDSTeam@hmrc.gsi.gov.uk:
> - Issues relating to subscribing/registering to use the API Platform, MTD enrolment / de enrolment  / registration for VAT / BETA etc
> - Issues relating to OAuth2
> - Issues relating to integrating with the API Platform (setting up an application/access)
> - Vendor application software questions (code examples in .NET / VB6 etc.)
> - Business related questions
> - Scheduled maintenance days / windows
> - Onboarding 
> - Performance metrics
> - Questions relating to the process pre MTD

**Comment by mathiasbanda** [comment]
Hi @macgrewal 

I notice you closed my question. If you want to be pedantic everything on VAT API relates to the list you've put up. My question is how can I tell a given code is for an agent? So which one of those things you've listed does my question fall under?

**Comment by macgrewal** [comment]
@mathiasbanda I'm not being pedantic, your question relates to the auth flow that has been developed by another team. If your question was related to one of the APIs we developed, cool, but it's not so I'm telling you where to go to get your issue resolved.

**Comment by mathiasbanda** [comment]
Fine
