### ISSUE TITLE
Retrieve VAT liabilities - variable lengths

### ISSUE THREAD

**Issue by MrNicks** [hmrc/vat-api#326]
The retrieve VAT liabilities Json response will contain:

liabilities array:

   taxPeriod object:

      from - string
      to - string

   type - string
   originalAmount - number [decimal]
   outstandingAmount - number [decimal]
   due - string

The 'from', 'to', and 'due' strings representing dates in the format: YYYY-MM-DD I presume will always be size 10 bytes.  Please advise what maximum length the 'type' string will be?  Also, what type is the 'originalAmount' abd 'outstandingAmount'  numbers, double or decimal; if decimal what upper and lower bounds will it be and what is the precision?

**Comment by macgrewal** [comment]
Hi @MrNicks 

* `from`/`to`/`due` properties will be in the format `YYYY-MM-DD`
* `originalAmount` and `outstandingAmount `
    * numbers with 2 decimal places
    * min value: -9999999999999.99
    * max value: 9999999999999.99
* `type` is a string with a max length of 30 characters

Hope that helps.

**Comment by jonathanleather** [comment]
Where appropriate, these have now been added to the documentation.

Cheers
Jon
