### ISSUE TITLE
Retrieve VAT payments - variable lengths

### ISSUE THREAD

**Issue by MrNicks** [hmrc/vat-api#327]
The retrieve VAT payments Json response will contain:

payments array:

   amount - number
   received - string

The 'received' string representing a date in the format YYY-MM-DD I presume will always be size 10 bytes.  Please advise what maximum length the 'received' string will be?

**Comment by macgrewal** [comment]
Hi @MrNicks 

* `received ` will be in the format `YYYY-MM-DD`
* `amount` will be a number with 2 decimal places
    * min value: -9999999999999.99
    * max value: 9999999999999.99

Hope that helps.

**Comment by jonathanleather** [comment]
Where appropriate, these have now been added to the documentation.

Cheers
Jon
