### ISSUE TITLE
Size of OAUTH2 access token and refresh token

### ISSUE THREAD

**Issue by PeterGGreen** [hmrc/vat-api#334]
What is the maximum size of the OAUTH2 access token and refresh token?  I've scoured here, the develop hub and the size is never discussed.  We need to store these in databases (encrypted obviously) but I assumed they were 36 chars (given the initial responses from the API) but I'm getting 32/31 chars now.

Other services (ala Facebook, FitBit etc) say their token length should accommodate 1024 characters.

**Comment by macgrewal** [comment]
@PeterGGreen I have forwarded this question onto the platform team. They will either respond to me so I can respond here or they will updated the issue themselves.

**Comment by macgrewal** [comment]
Hi @PeterGGreen,

The response I've had from the platform is that there is no maximum length defined. I appreciate this isn't the answer you were looking for.

As per the webinar earlier this week you can raise this platform issue with SDST via email at SDSTeam@hmrc.gsi.gov.uk.

Regards,

mac
