### ISSUE TITLE
Create Test Organisation  End Point

### ISSUE THREAD

**Issue by KieranSmith78** [hmrc/vat-api#335]
When trying to crate a test organisation at

https://test-api.service.hmrc.gov.uk/create-test-user/organisations

The response is: A resource with the name in the request can not be found in the API
As others have obviously got this working in the past - has there been a change in the endpoint address?

Thanks

**Comment by mathiasbanda** [comment]
Post the line of code here just in case it's something else. I haven't had issues creating new organisations except when the service is down

**Comment by GarySmithMace** [comment]
Also, make sure the your application has been subscribed to the Create Test User API as well as the VAT(MTD) API.

**Comment by ma3574** [comment]
@KieranSmith78 If there are still issues please contact SDST at SDSTeam@hmrc.gsi.gov.uk and they will be able to help. Thanks
