### ISSUE TITLE
MTD VAT scope issue

### ISSUE THREAD

**Issue by kostaa** [hmrc/vat-api#336]
I have created a MTD VAT test user and during the OAuth 2.0 flow I ask for both 'write:vat' and 'read:vat' scopes (`scope=write:vat read:vat`). When the server replies with the tokens it returns only a single scope and it is always the first one I have asked for. I have swapped them round added a dummy scope and it is always the first one that is returned.

Is this expected behaviour? Does it mean I need to ask for read and write authorisation separately?
Could you clarify this for me please?

**Comment by kostaa** [comment]
This is the snapshot of the web page that I get: 

![image](https://user-images.githubusercontent.com/7585117/48316824-5073c700-e5e0-11e8-84e5-7649caadff0e.png)

So far I have tested the read access only so you might be right that the token is for both read and write access. Nonetheless if I remember correctly the server has an option of not returning back the scope in which case it is assumed that the scope was granted as requested. Alternatively it can reject or narrow down the scope in which case it should return the scope that was actually granted. 

So in this case it looks like the latter scenario that the server is rejecting part of the requested scope which is a bit confusing/misleading.

Adam

**Comment by kostaa** [comment]
I just authorized a test user with  `scope=write:vat read:vat` and I got back  `scope=write:vat` from the server as I described above. After that I run a get obligations test `/organisations/vat/$vatNumber/obligations` and got `403 Forbidden`.

Then I swapped the scopes around `scope=read:vat write:vat` and I got back  `scope=read:vat` from the server. I have re-run the get obligations test as above and got a valid reply.

I do not have a write test as yet so I cannot confirm this for the other scenario but it looks like only one scope is actually granted to the client.

**Comment by GrahamHDawson** [comment]
Well there's something wrong with your request for the authorisation code.
Ignoring the potential language differences (I'm using Clarion) - you should have something like this...

   httpWebAddress = 'https://test-api.service.hmrc.gov.uk/oauth/authorize' & | 
            '?response_type=code&client_id=' & glo:clientID & '&scope=read:vat write:vat'  & |
            '&state=' & glo:GUID & '&redirect_uri=' & redirectUri 

And the resultant screen (once the user has enter their userID and userPassword should be this...

![readwriteauthority](https://user-images.githubusercontent.com/42624873/48318351-3691ae80-e5f7-11e8-8624-eb8c4213e4ba.PNG)

Graham

**Comment by Hollister** [comment]
The documentation says that the scopes should be space delimited, but after seeing other implementations on here I have them delimited with +, which seems to work for me.

C# implementation:

public string GetRequestAuthorisationUrl(bool sandboxEnvironment)
        {
            var builder = new UriBuilder(sandboxEnvironment ? HMRCApiBaseAddress_SANDBOX : HMRCApiBaseAddress_PRODUCTION);
            builder.Path = "oauth/authorize";

            var query = HttpUtility.ParseQueryString(builder.Query);
            query["client_id"] = sandboxEnvironment ? ClientID_SANDBOX : ClientID_PRODUCTION;
            query["scope"] = "read:vat+write:vat";
            query["response_type"] = "code";
            query["redirect_uri"] = "urn:ietf:wg:oauth:2.0:oob";

            builder.Query = query.ToString();
            return builder.ToString();        
        }

**Comment by kostaa** [comment]
I found the problem. I added the scope as the last one in the url `... &scope=read:vat write:vat`. That means that the space separated last part gets lost. Once I move it into the middle all is fine. Which brings me to the real problem and that is that I have not encoded the url ... hmm.

@GrahamHDawson @Hollister -  thanks for your help and apologies for confusion.
