### ISSUE TITLE
Data type for headers

### ISSUE THREAD

**Issue by mathiasbanda** [hmrc/vat-api#338]
I am converting all the data going into the fraud detection headers to string. Is that what's expected or can should it be left in whatever format the header type comes in? For example port number is "1234" rather than 1234

**Comment by adamdavi3s** [comment]
I wouldn’t go to to much effort yet as I don’t think we even know what headers are required yet

**Comment by markogrady** [comment]
Off topic @Adamdavi3s do you have some contact details? Mine are Mark@markogrady.com

**Comment by mathiasbanda** [comment]
Will wait thank you
