### ISSUE TITLE
VAT return payload - finalised flag meaning

### ISSUE THREAD

**Issue by RobertMarczycki** [hmrc/vat-api#34]
Hi,

When I try sending the request having finalised flag set to false the service responds with an error below; is this a feature of Sandbox API only or not finalised returns are not permitted at all? If the latter then what's the intention of having the flag?

`{
    "code": "BUSINESS_ERROR",
    "message": "Business validation error",
    "errors": [
        {
            "code": "NOT_FINALISED",
            "message": "The return cannot be accepted without a declaration it is finalised.",
            "path": "/finalised"
        }
    ]
}`

Thanks,
Robert

**Comment by hicnar** [comment]
Robert,

The flag itself is introduced for the purpose of implementing non repudiation. 
In a html form analogy that would be a tick box somewhere at the end of the form. Checking of that tick box means that you confirm that "According to my best knowledge the details in the form are accurate, complete and correct".

Hope this helps

**Comment by nnotsofun** [comment]
hey @hicnar so in reality, you would expect this to be true 100% of the time?

**Comment by hicnar** [comment]
@nnotsofun yes

**Comment by nnotsofun** [comment]
thanks @hicnar for clarifying

**Comment by nigelrainer** [comment]
How will the new API support the situation when a return is actually a final return (ie the last ever return for a registration) which is currently supported in the existing XML API with the <vat:VATDeclarationRequest finalReturn="yes"> attribute.  The use of this "finalise" flag appears to me to be pointless and ambiguous.

**Comment by nnotsofun** [comment]
@nigelrainer i agree, at an api level it doesn't make much sense to be there if it's expected to be true all the time. Is the scope of that flag expected to be expanded in the future? @hicnar

**Comment by nigelrainer** [comment]
Comment removed and raised as a separate issue #44
