### ISSUE TITLE
test Vat Api returns - the 'vat' api is unavailable

### ISSUE THREAD

**Issue by daveowensuk** [hmrc/vat-api#342]
I have an issue when I try and get obligations from the test vat api. I can authorize ok using ChilKat code and get a Bearer token BUT in my APP and in Postman I always get:

![image](https://user-images.githubusercontent.com/11569617/48472769-e2511f00-e7ee-11e8-92bb-f66d20845a22.png)

My Code is below and all works up until the last part where I do a request to obiligations:

`       
 //Submit to HMRC!

                Global glob = new Global();
                bool success = glob.UnlockBundle("Anything for 30-day trial");
                if (success != true)
                {
                    throw new Exception(glob.LastErrorText);
                }

                int status = glob.UnlockStatus;
                if (status == 2)
                {
                    //Purchase Version
                }
                else
                {
                    //Trial Mode
                }

                OAuth2 oauth2 = new OAuth2();
                
                //  This should be the port in the localhost callback URL for your app.
                //  Important: Make sure the callback URI in your HMRC developer app is exactly "http://localhost:3017/".  Don't forget the ending "/" char.
                //  The callback URL would look like "http://localhost:3017/" if the port number is 3017.

                //  IMPORTANT: Don't forget to setup your HMRC application to use the Redirect URI "http://localhost:3017/" as shown
                //  here: Configure Redirect URI for HMRC application
                oauth2.ListenPort = 3017;

                oauth2.AuthorizationEndpoint = "https://test-api.service.hmrc.gov.uk/oauth/authorize";
                oauth2.TokenEndpoint = "https://test-api.service.hmrc.gov.uk/oauth/token";

                //  Replace these with actual values.
                oauth2.ClientId = "[Removed from Code]";
                oauth2.ClientSecret = "[Removed from Code]";

                //  The scopes are documented in the HMRC reference documentation for each API.
                oauth2.Scope = "read:vat+write:vat";

                //  Begin the OAuth2 three-legged flow.  This returns a URL that should be loaded in a browser.
                string url = oauth2.StartAuth();
                if (oauth2.LastMethodSuccess != true)
                {
                    throw new Exception(oauth2.LastErrorText);
                }

                //  We can pre-check the URL by sending a GET to catch any up-front errors.
                //  If we receive JSON with an error in response, then we don't proceed any farther.
                //  For example, a JSON error response would look like this:
                //  {"error":"invalid_request","error_description":"redirect_uri is invalid","state":"kk1e0ZXS-rlC_SFgHh5qBMSVbvonC9SE8Q-GXCQNDRo"}

                //  If we receive an HTML response, and the response status = 200, then all should be OK.
                //  We can proceed by displaying an interactive browser loaded with the url.
                Chilkat.Http http = new Chilkat.Http();
                Chilkat.StringBuilder sbPreCheck = new Chilkat.StringBuilder();
                success = http.QuickGetSb(url, sbPreCheck);
                if ((http.LastStatus != 200) || (sbPreCheck.StartsWith("{", true) == true))
                {
                    throw new Exception(("JSON Error Response:" + sbPreCheck.GetAsString()));
                }

                //  If the HTTP request itself failed, then examine the error.
                if (success == false)
                {
                    throw new Exception(http.LastErrorText);
                }

                //  OK.. the pre-flight check seems OK, go ahead with getting the interactive user authorization..

                //  At this point, your application should load the URL in a browser.

                //  Add the code to load the url in a web browser here...

                System.Diagnostics.Process.Start(url);
                
                //  Now wait for the authorization.
                //  We'll wait for a max of 120 seconds.
                int numMsWaited = 0;
                while ((numMsWaited < 1200000) && (oauth2.AuthFlowState < 3))
                {
                    oauth2.SleepMs(100);
                    numMsWaited = numMsWaited + 100;
                }

                //  If there was no response from the browser within 120 seconds, then
                //  the AuthFlowState will be equal to 1 or 2.
                //  1: Waiting for Redirect. The OAuth2 background thread is waiting to receive the redirect HTTP request from the browser.
                //  2: Waiting for Final Response. The OAuth2 background thread is waiting for the final access token response.
                //  In that case, cancel the background task started in the call to StartAuth.
                if (oauth2.AuthFlowState < 3)
                {
                    oauth2.Cancel();
                    throw new Exception("No response from the browser!");
                }

                //  Check the AuthFlowState to see if authorization was granted, denied, or if some error occurred
                //  The possible AuthFlowState values are:
                //  3: Completed with Success. The OAuth2 flow has completed, the background thread exited, and the successful JSON response is available in AccessTokenResponse property.
                //  4: Completed with Access Denied. The OAuth2 flow has completed, the background thread exited, and the error JSON is available in AccessTokenResponse property.
                //  5: Failed Prior to Completion. The OAuth2 flow failed to complete, the background thread exited, and the error information is available in the FailureInfo property.
                if (oauth2.AuthFlowState == 5)
                {
                    throw new Exception("OAuth2 failed to complete." + oauth2.FailureInfo);
                }

                if (oauth2.AuthFlowState == 4)
                {
                    throw new Exception("OAuth2 authorization was denied." + oauth2.AccessTokenResponse);
                }

                if (oauth2.AuthFlowState != 3)
                {
                    throw new Exception("Unexpected AuthFlowState:" + Convert.ToString(oauth2.AuthFlowState));
                }

                Debug.WriteLine("OAuth2 authorization granted!");
                Debug.WriteLine("Access Token = " + oauth2.AccessToken);

                //  Get the full JSON response:
                JsonObject json = new JsonObject();
                json.Load(oauth2.AccessTokenResponse);
                json.EmitCompact = false;
                Debug.WriteLine(json.Emit());

                //  If an "expires_on" member does not exist, then add the JSON member by
                //  getting the current system date/time and adding the "expires_in" seconds.
                //  This way we'll know when the token expires.
                if (json.HasMember("expires_on") != true)
                {
                    CkDateTime dtExpire = new CkDateTime();
                    dtExpire.SetFromCurrentSystemTime();
                    dtExpire.AddSeconds(json.IntOf("expires_in"));
                    json.AppendString("expires_on", dtExpire.GetAsUnixTimeStr(false));
                }

                Debug.WriteLine(json.Emit());

                string strReponseValue = string.Empty;
                string endPoint = "https://test-api.service.hmrc.gov.uk/vat/666471423/obligations?from=2017-01-01&to=2017-03-01";

                HttpWebRequest request = (HttpWebRequest)WebRequest.Create(endPoint);

                request.Accept = "application/vnd.hmrc.1.0+json";
                request.ContentType = "application/json";

                if (oauth2.AccessToken.Length > 0)
                {
                    request.Headers.Add("Authorization", "Bearer " + oauth2.AccessToken);
                }

                request.Method = "GET";  // GET
                HttpWebResponse response = null;
                try
                {
                    **_response = (HttpWebResponse)request.GetResponse();  // Error here_**
                }
                catch (Exception ex)
                {
                    throw ex;
                }
        `

The error that appears in Postman appears here in the APP:

**_response = (HttpWebResponse)request.GetResponse();  // Error here_**

I have asked the SDSTeam but they say the test API is working for them, so I presume that something in my request is incorrect!

Any ideas?

Many thanks,

Dave

**Comment by narendravijayarao** [comment]
Hi Dave,

As per the postman image you haven't selected/sending the "Authorisation" header key, that has the "Bearer token" value.

Thanks,
Naren.

**Comment by daveowensuk** [comment]
Hi @narendravijayarao 

Thanks for a prompt response, however it is included in the request from the Authorization Tab automatically by Postman and in my code I am definitely adding it into the Header per:

`
  if (oauth2.AccessToken.Length > 0)
            {
                request.Headers.Add("Authorization", "Bearer " + oauth2.AccessToken);
            }
`
 - but to prove the point I manually added it and I still get the same issue:

![image](https://user-images.githubusercontent.com/11569617/48478153-5db8cd80-e7fb-11e8-9e34-4b05c9158e0a.png)

So I don't think that is the issue.

Dave

**Comment by narendravijayarao** [comment]
Dave,
 
I just tried on my side and it is working fine. Is this happening when you hit the VAT-API directly or through your application?

Thanks,
Naren.

**Comment by daveowensuk** [comment]
Hi,

In both scenarios - I can auth in the APP using the code supplied BUT whenI try and get obligations from either the app or in Postman using the Bearer Token generated I get the error.

Do you have a valid current Token and string to that api for a VRN I can test from here in Postman that you know works?

Seems very odd to me?

Dave

**Comment by GJustas** [comment]
Hi @daveowensuk 

As I can see your URL is bad. You forgot **/organisations/** before /vat/... .
Maybe this is why it's not working.

**Comment by daveowensuk** [comment]
> Hi @daveowensuk
> 
> As I can see your URL is bad. You forgot **/organisations/** before /vat/... .
> Maybe this is why it's not working.

@Justas - you are a star - of course I have - works now!!!

**Comment by daveowensuk** [comment]
Hopefully the code I posted will enable others using .NET and Chilkat to make a start :-)
