### ISSUE TITLE
Submit negative due VAT return

### ISSUE THREAD

**Issue by njacobs-winman** [hmrc/vat-api#344]
I'm trying to work out how to submit a negative due VAT return. I can see the netVatDue prop must be greater than zero and I was told by yourselves to use a zero value for netVatDue when it is negative and it will be sorted at the back end.
However, if I do this I get an error on submitting that the values do not agree.

This is a sample submission

{{"periodKey":"18A2","vatDueSales":0.00,"vatDueAcquisitions":0.00,"totalVatDue":0.00,"vatReclaimedCurrPeriod":438.20,"netVatDue":0.00,"totalValueSalesExVAT":0,"totalValuePurchasesExVAT":2194,"totalValueGoodsSuppliedExVAT":0,"totalAcquisitionsExVAT":0,"finalised":true}}

Is it possible to submit negative due returns and if so how?

Many thanks
Nick

**Comment by GarySmithMace** [comment]
From what i recall, netVatDue needs to be the difference between totalVatDue and vatReclaimedCurrPeriod.  Deducting the smaller from the larger and entering the difference in netVatDue.

So in your example the netVatDue should be 438.20. And as totalVatDue is less than vatReclaimedCurrPeriod, the backend should treat it as a negative.

**Comment by markogrady** [comment]
3.6 Filling in box 5
Box 5 net VAT to pay to HMRC or reclaim
Take the figures in boxes 3 and 4. Deduct the smaller from the larger and enter the difference in box 5.

This figure will be calculated automatically if you’re completing your return online.
https://www.gov.uk/guidance/how-to-fill-in-and-submit-your-vat-return-vat-notice-70012#section3 

3.6
If the figure in box 3 is more than the figure in box 4, the difference is the amount you must pay. If the figure in box 3 is less than the figure in box 4 we’ll credit your account and repay the balance, subject to any enquiries we may need to make.

**Comment by njacobs-winman** [comment]
Many thanks for the advice.
I can confirm 'Take the figures in boxes 3 and 4. Deduct the smaller from the larger and enter the difference in box 5' works.
