### ISSUE TITLE
Getting an access Token

### ISSUE THREAD

**Issue by ShoLongBruce** [hmrc/vat-api#347]
I'm submitting a Support request. Apologies if I'm using the wrong forum, I have submitted a couple of email support to SDSTeam@hmrc.gsi.gov.uk but have not had a response so far.

I have created a test user using the api and authorised it. I am now trying to get an access token but keep getting and invalid uri (400) error. I have used the same URI as used to get Authorisation.

my querystring is 
grant_type=authorization_code&client_id=myclientID&client_secret=myclient_secret&redirect_uri=http://localhost:3017/&code=9739b7fa94ea4abcb7dc33342120abae

Thanks.

**Comment by GarySmithMace** [comment]
My first thought was this.

"When calling our authorisation endpoint, your redirect URI must be percent-encoded, for example: 

https%3A%2F%2Fwww.example.com%2Fauth-redirect"

https://developer.service.hmrc.gov.uk/api-documentation/docs/reference-guide#redirect-uris

**Comment by MeliaDavies** [comment]
We normally submit oauth token requests as a http POST request
e.g. POST https://test-api.service.hmrc.gov.uk/oauth/token
```json
{
  "client_id": "client id",
  "client_secret": "client secret",
  "grant_type": "authorization_code",
  "redirect_uri": "http://localhost:9000",
  "code": "8eefab0c99ee4ceebb022c25473024e0"
}
```
I am not familiar with using query parameters for a POST request but it may be worth trying the suggestion above. 
Let us know if it doesn't work.

**Comment by ShoLongBruce** [comment]
> 
> 
> My first thought was this.
> 
> "When calling our authorisation endpoint, your redirect URI must be percent-encoded, for example:
> 
> https%3A%2F%2Fwww.example.com%2Fauth-redirect"
> 
> https://developer.service.hmrc.gov.uk/api-documentation/docs/reference-guide#redirect-uris

I have tried both encoded and un-encoded and variations.

**Comment by ShoLongBruce** [comment]
> 
> 
> We normally submit oauth token requests as a http POST request
> e.g. POST https://test-api.service.hmrc.gov.uk/oauth/token
> 
> ```json
> {
>   "client_id": "client id",
>   "client_secret": "client secret",
>   "grant_type": "authorization_code",
>   "redirect_uri": "http://localhost:9000",
>   "code": "8eefab0c99ee4ceebb022c25473024e0"
> }
> ```
> 
> I am not familiar with using query parameters for a POST request but it may be worth trying the suggestion above.
> Let us know if it doesn't work.
I am using a POST, code below
            Dim sbQuery As StringBuilder = New StringBuilder()
            sbQuery.Append("grant_type=" & HttpUtility.UrlEncode("authorization_code"))
            sbQuery.Append("&client_id=" & HttpUtility.UrlEncode(_mstrCliendID))
            sbQuery.Append("&client_secret=" & HttpUtility.UrlEncode(_mstrClientSecret))
            sbQuery.Append("&redirect_uri=" & HttpUtility.UrlEncode(_redirectURi))
            sbQuery.Append("&code=" & HttpUtility.UrlEncode(authcode))

 Dim strGetString As String = sbQuery.ToString
            Dim byteData() As Byte
            byteData = UTF8Encoding.UTF8.GetBytes(strGetString)
            Dim endPoint As String = "https://test-api.service.hmrc.gov.uk/oauth/token"

            makeRequest = DirectCast(WebRequest.Create(endPoint), HttpWebRequest)
            makeRequest.ContentType = "application/x-www-form-urlencoded"
            makeRequest.Method = "POST"
            makeRequest.ContentLength = byteData.Length
            makeRequest.GetRequestStream().Write(byteData, 0, byteData.Length)
            makeRequest.GetRequestStream.Close()

            response = DirectCast(makeRequest.GetResponse(), HttpWebResponse)

**Comment by ShoLongBruce** [comment]
> 
> 
> Have you added the redirect uri to your application in the developer hub?

Hi, yes. Tried http://localhost:3017/  (ends with /) 
and http://localhost:3017/ (no /), even tried urn:ietf:wg:oauth:2.0:oob (the last one errors when I tried authorising it)

Not sure if its relevant, but my scope is read:vat write:vat when authorising.

**Comment by gbs-matt** [comment]
I don't think query parameters will work.  The final endpoint should be only:
`https://test-api.service.hmrc.gov.uk/oauth/token`
not this, for example:
`https://test-api.service.hmrc.gov.uk/oauth/token?client_id=xxxx&client_secret=xxxx&...etc etc`

The parameters you're trying to place in the querystring should actually be the JSON object that MeliaDavies mentioned and the content-type should be `application/json`, not `application/x-www-form-urlencoded`.

**Comment by GarySmithMace** [comment]
Rather than using HttpUtility.UrlEncode for the Redirect URI, try using System.Uri.EscapeDataString

This will encode all reserved characters to the %-encoded format. (UrlEncode doesn't necessarily %-encode the : and / )

**Comment by ShoLongBruce** [comment]
> 
> 
> Rather than using HttpUtility.UrlEncode for the Redirect URI, try using System.Uri.EscapeDataString
> 
> This will encode all reserved characters to the %-encoded format. (UrlEncode doesn't necessarily %-encode the : and / )

tried that and still getting error. The string i'm getting now is 
grant_type=authorization_code&client_id=myClientID&client_secret=myClient_secret&redirect_uri=http%3A%2F%2Flocalhost%3A3017&code=fdf62422e2f1462b80910aa2054ac85c

**Comment by ShoLongBruce** [comment]
> 
> 
> I don't think query parameters will work. The final endpoint should be only:
> `https://test-api.service.hmrc.gov.uk/oauth/token`
> not this, for example:
> `https://test-api.service.hmrc.gov.uk/oauth/token?client_id=xxxx&client_secret=xxxx&...etc etc`
> 
> The parameters you're trying to place in the querystring should actually be the JSON object that MeliaDavies mentioned and the content-type should be `application/json`, not `application/x-www-form-urlencoded`.

 My final endpoint IS https://test-api.service.hmrc.gov.uk/oauth/token na dmy post data is the string I built up. I have tried both application/json and and a couple of others (can't remember), whichever one I used, i get the same error. 
Tried omitting the URI and the error i got back was uri needed

**Comment by gbs-matt** [comment]
> My final endpoint IS https://test-api.service.hmrc.gov.uk/oauth/token

I misunderstood.  My apologies.

I don't know whether the method you're trying is meant to work but I could only get it working as a JSON object.  That way I didn't need to encode the redirect uri.

The way I do it, the post data looks like this (using the example above):


```
{
  "client_id": "client id",
  "client_secret": "client secret",
  "grant_type": "authorization_code",
  "redirect_uri": "http://localhost:9000",
  "code": "8eefab0c99ee4ceebb022c25473024e0"
}
```

not like this:

`grant_type=authorization_code&client_id=myClientID&client_secret=myClient_secret&redirect_uri=http%3A%2F%2Flocalhost%3A3017&code=fdf62422e2f1462b80910aa2054ac85c`

**Comment by ShoLongBruce** [comment]
> 
> 
> > My final endpoint IS https://test-api.service.hmrc.gov.uk/oauth/token
> 
> I misunderstood. My apologies.
> 
> I don't know whether the method you're trying is meant to work but I could only get it working as a JSON object. That way I didn't need to encode the redirect uri.
> 
> The way I do it, the post data looks like this (using the example above):
> 
> ```
> {
>   "client_id": "client id",
>   "client_secret": "client secret",
>   "grant_type": "authorization_code",
>   "redirect_uri": "http://localhost:9000",
>   "code": "8eefab0c99ee4ceebb022c25473024e0"
> }
> ```
> 
> not like this:
> 
> `grant_type=authorization_code&client_id=myClientID&client_secret=myClient_secret&redirect_uri=http%3A%2F%2Flocalhost%3A3017&code=fdf62422e2f1462b80910aa2054ac85c`

The problem with that is I have to work with VB.NET and can't use the same syntax.  This link uses a similar method to what I'm doing, which works for them 
https://integrate.hubspot.com/t/cant-get-oauth-2-0-access-refresh-tokens-vb/3217

**Comment by GarySmithMace** [comment]
I also use VB.NET and mine has had no problems.

`        
        Dim OauthCall As HttpWebRequest
        Dim postData As String = "client_secret=" & ClientSecret & "&client_id=" & ClientID & "&grant_type=authorization_code&redirect_uri=" & System.Uri.EscapeDataString(redirectURI) & "&code=" & authCode
        OauthCall = HttpWebRequest.Create(HMRC_Token_URI)
        OauthCall.Method = "POST"
        OauthCall.ContentType = "application/x-www-form-urlencoded"
        Dim encoding As New System.Text.ASCIIEncoding()
        Dim byte1 As Byte() = encoding.GetBytes(postData)

        Dim newStream As Stream = OauthCall.GetRequestStream()
        newStream.Write(byte1, 0, byte1.Length)
        newStream.Close()

        Dim objStream As Stream
        objStream = OauthCall.GetResponse.GetResponseStream()
`
Except for the general method of building the string and writing to the stream, the only other difference i see between our code that could make any difference is that I am using ASCII encoding to measure the string length in bytes.

**Comment by ShoLongBruce** [comment]
I have changed the encoding to System.Text.ASCIIEncoding and still errors with invalid uri.
Just to summarise, I have subscribed to the following APIs (Hello world, VAT MTD and create test user)
I have 1 redirect URL and created a test user using the the create user API. I have successfully maged to authorise the user but can't get the token. Am I missing a step somewhere?

**Comment by gbs-matt** [comment]
If you haven't already, it would be worthwhile testing the API outside of your program with a tester such as [Insomnia](https://insomnia.rest/),  At the very least it will rule out any problems with your configuration on the development hub.

I tried your situation (Form URL Encoded) in Insomnia just now and it worked.  The only time I got the error you get was when I mistakenly used my normal redirect uri for the authorisation process but used yours for getting the access token.

![image](https://user-images.githubusercontent.com/30410184/48718038-833a4280-ec12-11e8-96a4-4951defb8c3d.png)

**Comment by ShoLongBruce** [comment]
Ok, Thanks for that. Tried Insomnia (first time I've heard of it), tried the same process as you and still got the invalid uri error, HOWEVER, I did try something different. I went through the authorisation process using a normal internet (firefox) browser (I was using an embedded web browser control on my winform). I copied the auth code from the url, and used it on my POST in my app and it works?

Didn't realise there was a difference?

**Comment by gbs-matt** [comment]
[This](https://developer.service.hmrc.gov.uk/api-documentation/docs/reference-guide#oauth-2.0-browser-support) might be of some help.

**Comment by CiprianSavoiu** [comment]
I'm having the same problem with the redirect_uri.
I'm able to retrieve the auth code (where the redirect _uri works) but when trying to get the token I'm getting invalid Uri error

**Comment by CiprianSavoiu** [comment]
Solved

    when requesting access code the redirect_uri should be percent-encoded : http%3A%2F%2Flocalhost%3A3017%2F
    when requesting token the redirect_uri should be in normal format: http://localhost:3017/
