### ISSUE TITLE
How to Add Client

### ISSUE THREAD

**Issue by jjppnn** [hmrc/vat-api#349]
Hi there,

Can someone point me in the right direction on how to add a client (Company name and VRN) to the list of  companies that I would be an agent for ? I cant see anything in the API for this. I can only see API's for handling the vat returns at a company level.

Thanks,

John

**Comment by jacobbrownlow** [comment]
Hi jjppnn

Are you trying to setup an agent in the Sandbox?
There is a solution for this in VAT but we are just finalising the journey before making it available to vendors.

I imagine this will be available soon.

Jacob

**Comment by jjppnn** [comment]
HI Jacob,

Yes, I was looking in the API to see if there was an event call for this but could not see anything.

On a slightly different matter, I have seen a working version of the MTD solution provided by Vital Tax. See https://www.youtube.com/watch?v=Z55G5Ce5X14

In their solution, a client can be added to an agent. So how are they available to provide this function if it is not available in the sandbox for testing?

J

**Comment by jacobbrownlow** [comment]
Hi John

The video appears to be only a demo of how this software package will look. Agent client relationships have only been enabled in Sandbox for a week or more.

Unfortunately at present there is not an agent API to call. The solution at present will involve an agent stub frontend. Again, we are just finalising the journey before making it available to vendors. Expect something very soon.

Jacob

**Comment by jjppnn** [comment]
Are you saying that no companies are in a position to offer a "live" solution right now ?

J

**Comment by jacobbrownlow** [comment]
Hi John

The VAT-API supports Agent users, in all environments including Production. 

There just wasn't a solution to setup a test Agent in the Sandbox environment until very recently.

Jacob

**Comment by jjppnn** [comment]
Hi,

 

Am I looking in the wrong place ??

 

https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0

 

I cant see calls for adding clients.

 

J

**Comment by jacobbrownlow** [comment]
Hi John

Agent Client relationships are not managed by the VAT-API. 

We only do auth calls to ensure a user is authorised. The service accepts the affinity group "Agent" and ensures the Agent bearer token is valid for the VRN (which is checked by auth calls).

We are only interested in the Sandbox environment setup for the purpose of supporting testing of our service. If you have more general questions about Agents you will need to contact the Software Developers Support Team by emailing SDSTeam@hmrc.gsi.gov.uk.

Jacob
