### ISSUE TITLE
GET /vat/{vrn}/obligations date range 

### ISSUE THREAD

**Issue by DJonesKamarin** [hmrc/vat-api#350]
Hi,

I have been reading several of the posts about the From and To Date range, but I can't find a simple answer,
I know that the return data is static and so just would like something confirmed please.

If I request the obligations with a From date of 2018-10-01 and a To date of 2018-10-31, will I get outstanding obligations for before 2018-10-01 or not?
e.g. outstanding obligation for 2018-06-01 (will or will not be included)

Thanks

**Comment by GrahamHDawson** [comment]
Are you talking about in the sandbox or 'live'?

In the sandbox all that matters is that the date range is less than a year - the O(utstanding) F(ullfilled) parameter is currently ignored.

In 'live' I don't think I'd use such a narrow date range.
For the first year I'm planning on using 01/04/2019 to current date as the range and showing all results.
(only the outstanding ones will lead to a submission process)

Graham

**Comment by DJonesKamarin** [comment]
Hi Graham,

I am interesting in Live, as you have said in the sand box so long as it is less that 1 year I get a result back (static data), as well as the O and F are ignored,

I was thinking that for Live I should use the current year and either 01/01 or as you say 01/04 or maybe the last submit date to yesterday, I am then looking at the oldest open in the returned list and using the start and end date that are returned.

the info on the API page just has date to return, there was a thread that talks about inclusive but does not say if outstanding obligations will be included as well or not.

Thanks
David

**Comment by jacobbrownlow** [comment]
Hi David

In sandbox the responses are completely static, so they won't take into account the date range parameters in the request.

In production it is our understanding that if the "end" date of the obligation falls within the date range provided, it will be returned. However we don't have visibility of this code because it is handled by a backend service.

Jacob

**Comment by DJonesKamarin** [comment]
Hi Jacob,

Thanks for the information, I think based on that (Live System), I need to look at the date range of the request for the obligations, I think something Like Graham was saying, use 01/04/2019 as a start point and then use my last submit date - a month or 2, to make sure I get the earliest obligation.

Thanks
David
