### ISSUE TITLE
Fraud Prevention Gov-Client-Multi-Factor

### ISSUE THREAD

**Issue by MIHAllstars** [hmrc/vat-api#351]
How is a desktop application meant to obtain the information required for the Gov-Client-Multi-Factor fraud prevention header?

I know that these headers are still yet to be finalised but I can't see anywhere in the documentation that will return this information from the OAUTH process.

If we don't receive it, how can we send it back?

**Comment by GrahamHDawson** [comment]
I **think** the idea is that the application (desktop or Web) should **itself** implement a 2-part authorisation process before the application can be used.

From the docs with my emphasis...
Details about the multi-factor authorisation that the **vendor** requires **their user** to pass before using their application. 

I think this is **way** over the top as the end-user already has to negotiate a 2-part authorisation process to access HMRC - so asking for another 2-part authorisation process for the end-user to use the application that talks to HMRC is (IMHO) too much.

Certainly it's not something we could implement easily (with a desktop application here)

Graham

**Comment by MIHAllstars** [comment]
@GrahamHDawson 

Having re-read it for probably the 100th time to understand what was being said, I have to say I agree with you, it does seem to suggest that our application will also have to provide 2-part authorisation to use it, which is on top of the 2-part process for accessing HMRC.

We've certainly no plans to add this kind of functionality to our software.

I hope they drop this as I assume otherwise it will become part of the approval process to be able to use the production APIs!

**Comment by hughfdjackson** [comment]
Hi @MIHAllstars , @GrahamHDawson 

Thanks for raising this issue, and apologies for the delayed response.  We've been working on clarifying the requirements of the fraud prevention headers in general. 

> How is a desktop application meant to obtain the information required for the Gov-Client-Multi-Factor fraud prevention header?

The Gov-Client-Multi-Factor fraud prevention header is for capturing details about MFA the user establishes with the vendor - so not the MFA the user does as part of the HMRC oauth process. 

> Having re-read it for probably the 100th time to understand what was being said, I have to say I agree with you, it does seem to suggest that our application will also have to provide 2-part authorisation to use it, which is on top of the 2-part process for accessing HMRC.

We do not expect you to provide MFA for your application if you do not already have it.  If you do have it or develop it in future, then the Gov-Client-Multi-Factor header is the right place to let us know about the MFA status that a user has with your application or service. 

I hope that clarifies the above - let me know if you have any further questions.
