### ISSUE TITLE
Retrieving both Payments & Liabilities

### ISSUE THREAD

**Issue by MrNicks** [hmrc/vat-api#352]
When receiving the response to either a request for payments or liabilities, is the CorrelationId always going to be unique, or if we receive a record previously received will the CorrelationId be the same as when received before?

**Comment by jacobbrownlow** [comment]
Hi MrNicks

The CorrelationId should be unique per each request, so it will change each time you repeat a request.

Jacob

**Comment by GrahamHDawson** [comment]
Hi Jacob,

In what circumstances would we use the CorrelationId?

Graham

**Comment by jacobbrownlow** [comment]
Hi Graham

The CorrelationId would help track a request in the event of a Live issue. You may want to make a record of it, but there isn't any requirement to do so.

Regards, Jacob

**Comment by GrahamHDawson** [comment]
OK thanks Jacob.

Graham
