### ISSUE TITLE
Submit VAT Return - MATCHING_RESOURCE_NOT_FOUND

### ISSUE THREAD

**Issue by eanguscameron** [hmrc/vat-api#354]
I am unable to submit VAT data either via CURL or Postman. In postman I am using Headers:
Accept: application/vnd.hmrc.1.0+json
Authorization: Bearer - My token
Content-Type: application/json

The Post URL is https://test-api.service.hmrc.gov.uk/create-test-user/organisations/vat/666938460/returns

The body is:
{
        "periodKey": "18A2",
        "vatDueSales": 65569.07,
        "vatDueAcquisitions": 294.20,
        "totalVatDue": 65863.27,
        "vatReclaimedCurrPeriod": 36326.49,
        "netVatDue": 29536.78,
        "totalValueSalesExVAT": 419276,
        "totalValuePurchasesExVAT": 373370,
        "totalValueGoodsSuppliedExVAT": 2780,
        "totalAcquisitionsExVAT": 147,
        "finalised" : "true"
}

I know that the Token is valid because I am able to Retrieve VAT Obligations and get two periods, the second of which is 18A2

However, the result is invariably: "code": "MATCHING_RESOURCE_NOT_FOUND",
    "message": "A resource with the name in the request can not be found in the API"

What resource could that be please?

**Comment by GarySmithMace** [comment]
You POST URL is incorrect

you have put

https://test-api.service.hmrc.gov.uk/create-test-user/organisations/vat/666938460/returns

The correct URL is

https://test-api.service.hmrc.gov.uk/organisations/vat/666938460/returns
