### ISSUE TITLE
How long to wait before doing View VAT Return after Submit VAT return for period?

### ISSUE THREAD

**Issue by Renu84** [hmrc/vat-api#357]
Hi ,

I have a Support request.

After Submit Vat return call , how long should we wait  before doing a View VAT Return  on Production API?

(On Canned data, View VAT Return  is very  spontaneous but need a time frame if possible .)

Thanks!

**Comment by GrahamHDawson** [comment]
Similar query applies to Submit VAT return and View Obligations
After submitting a VAT return how long before View Obligations will show that PeriodKey as being Fullfilled

Graham

**Comment by jonathanleather** [comment]
Hi @Renu84 @GrahamHDawson 

I have pinged a question to one of the backend teams for clarification on the above.
I'll let you know when I have a response.

Cheers
Jon

**Comment by obeea** [comment]
I'm glad this has been raised because we have just been discussing the same thing.
At first, we thought about updating our internal copy of the obligation record to Fullfilled, but decided against it, as we don't know if there is a time lag or additional approval required before going to Fullfilled, and in the sandbox we can't tell if reading the obligation straight afterwards will reflect the new status.
Instead, we are thinking of adding a new status of 'Submitted', so the user can see it was submitted and we can check the real status, next time the obligation API is called.

**Comment by sparkz42** [comment]
I agree it would be nice to know this. I'm assuming the worst at the moment, like @obeea, and having an interim status of "submitted" until an obligation update shows otherwise.

**Comment by jonathanleather** [comment]
Hey folks

Just as an update, I am still chasing definitive answers to the scenarios raised above. If there are any other scenarios you require, please do let me know.

Cheers
Jon

**Comment by MeliaDavies** [comment]
Hi guys,

When checking if an obligation is fulfilled following a submission it can take a few seconds (around 5) for the obligation to be marked as fulfilled in backend systems.

**Comment by jonathanleather** [comment]
Hey All

Apologies for the delay with this. Following on from the update from @MeliaDavies I have now received an answer to the other scenario requested. Answers to both can be found below.

1. After a Submit Vat return call , how long should we wait before doing a View VAT Return on Production API?

`This information should be available almost immediately, please allow a couple of seconds`

2. After submitting a VAT return how long before View Obligations will show that PeriodKey as being Fullfilled? 

`when checking if an obligation is fulfilled following a submission it can take a few seconds (around 5) for the obligation to be marked as fulfilled in backend systems.`

I'll close the issue but if you require anything else please do come back to us.
The above information will also be available in the FAQ for future reference.

Cheers
Jon

**Comment by jonathanleather** [comment]
Hey folks 

The back end teams have came back to us with another scenario regarding timings for **Hybrid Customers only**.

Following the same line as scenario 2 above.

3. As A Hybrid Customer - After submitting a VAT return how long before View Obligations will show that PeriodKey as being Fullfilled?

`If a submission is made Monday to Thursday during normal working hours, the obligation will be updated by the following morning, this will be earlier in some cases. If the return is received after 6pm on a Friday, then it is possible that their obligation will not be marked as fulfilled until the following Tuesday (or maybe Wednesday if there is a bank holiday). The obligation will be marked as met on the date it is received from the software, so a customer will not receive a penalty if the return was provided within the required time.`

I'll update the FAQ.

Cheers
Jon

**Comment by jonathanleather** [comment]
Hey folks,

Unfortunately, due to new information received from the downstream services the answer to the following scenario has changed.

2.	After submitting a VAT return how long before View Obligations will show that PeriodKey as
being Fulfilled?

> As previously stated the vast majority of transactions will be completed within 5 seconds however in some cases the delay may be a lot longer. 
> In the event that this happens the process is as follows: If a submission is made Monday to Thursday during normal working hours, the obligation will be updated by the following morning, this may be earlier in some cases. If the return is received after 6pm on a Friday, then it is possible that their obligation will not be marked as fulfilled until the following Tuesday (or maybe Wednesday if there is a bank holiday). The obligation will be marked as met on the date it is received from the software, so a customer will not receive a penalty if the return was provided within the required time.


This has changed due to new information provided by one of the downstream services. Please ensure that you build your software to cater for this. For anymore information regarding production timings or clarification on the above, please contact SDST at SDSTeam@hmrc.gsi.gov.uk.

Cheers
Jon

**Comment by DigitalDan1** [comment]
Just for info, as it may be helpful to others trying to work around this:

We designed our software to GET the VAT Return for the period key returned by the Obligations end point. If the return exists it means it was successfully submitted (so shouldn’t be submitted again). Whether the Obligation is fulfilled or not is just a secondary status for the user’s info.

I may add a note on the UI saying it can take a few days for Obligations to be updated by HMRC.

**Comment by GrahamHDawson** [comment]
What about the duplicate submission error response?

If the end user mistakenly submits a return that is still marked on the Obligations list as 'Outstanding' will they receive a duplicate submission error response in all cases, or is that time dependant as well?

Graham

**Comment by cb-rfk** [comment]
@GrahamHDawson 

Hi Graham,
When I submit a return on the test-api via postman and then immediately submit it again, I get the Duplicate Submission Error straight away:

{
    "code": "BUSINESS_ERROR",
    "message": "Business validation error",
    "errors": [
        {
            "code": "DUPLICATE_SUBMISSION",
            "message": "The VAT return was already submitted for the given period."
        }
    ]
}

**Comment by GrahamHDawson** [comment]
Hi cb-rfk,

Yes, but that's the test-api - what's important is how the live url behaves.

Graham

**Comment by jacobbrownlow** [comment]
Hi all

I have asked the question to the backend services, regarding the DUPLICATE_SUBMISSION error.

Following on from what was said earlier:
>As previously stated the vast majority of transactions will be completed within 5 seconds however in some cases the delay may be a lot longer.
In the event that this happens the process is as follows: If a submission is made Monday to Thursday during normal working hours, the obligation will be updated by the following morning, this may be earlier in some cases. If the return is received after 6pm on a Friday, then it is possible that their obligation will not be marked as fulfilled until the following Tuesday (or maybe Wednesday if there is a bank holiday). The obligation will be marked as met on the date it is received from the software, so a customer will not receive a penalty if the return was provided within the required time.

The answer is much the same for the response from _View VAT Return_. The DUPLICATE_SUBMISSIONS error will only be returned from _Submit VAT Return_ once the return is processed.

If the return has not yet been processed the API may allow multiple submissions, however any subsequent submissions will be ignored by the backend. 

The recommendation from the backend services is not to retry _Submit_ if a success message is returned from the original submission.

Regards, Jacob
