### ISSUE TITLE
Expected SCHEDULED_MAINTENANCE error not returned from APIs

### ISSUE THREAD

**Issue by sueking00** [hmrc/vat-api#358]
I'm submitting a Bug - API

The API documentation states that during scheduled system maintenance the HMRC system will return

code: SCHEDULED_MAINTENANCE 

The current behaviour (as we are in a scheduled maintenance window until tomorrow) is that the API's are returning the following:

code: SERVER_ERROR
message: The 'organisations/vat' API is currently unavailable

**Comment by jonathanleather** [comment]
Hi @sueking00 

In this scenario, where we (the VAT API project team) have shuttered the service, the code / message you are seeing is expected.

Only the API Platform are able to use maintenance mode. 

Where in the documentation did you see this? was it part of the "Reference Guide"?

Cheers
Jon

**Comment by GrahamHDawson** [comment]
Hi Jonathan,

https://developer.service.hmrc.gov.uk/api-documentation/docs/reference-guide

503 (Service Unavailable) shows 
Service unavailable => SERVER_ERROR
Scheduled maintenance => SCHEDULED_MAINTENANCE

Graham

**Comment by jonathanleather** [comment]
Thanks @GrahamHDawson I had a suspicion that was where it was. 
If either of you feel that the documentation is not clear enough i'm happy to raise this with our User Researcher / Technical Writer?

However, as this sits outside of our API documentation we won't be able to make any change, that responsibility will fall to the platform team. I would expect that their advice to you would be to not code to a specific error message, but there shouldn't be an issue in making the documentation clearer.

It would be worth also sending this issue to SDST so they can also relay the issue directly to the platform.

Cheers
Jon

**Comment by sueking00** [comment]
Thanks for the response.
Yes that is the document I saw it in Graham -  the reference guide. We were
hoping to display an applicable maintenance message given that the outage
was known. We were not expecting to get a server error response which is
currently just handled as a generic error in our system where we encourage
the user to retry. Presumably Service unavailable => SERVER_ERROR would be
returned whenever the system is down at your end. Under what circumstance
will the Scheduled maintenance => SCHEDULED_MAINTENANCE be returned then?

Regards,
Sue

**Comment by jonathanleather** [comment]
Hey @sueking00 

It is quite rare for the platform to use SCHEDULED_MAINTENANCE, the platform try very hard to minimise downtime and not shutter the platform. 

In the event that the platform is shuttered, the platform teams try and provide vendors with as much notice as possible before shuttering. That also applies if the VAT API is shuttered. Generally all shuttering is planned and communications are sent out, if you aren't receiving these I would speak to SDST. 

The obvious time when notice probably isn't provided is when there is a major issue with our service or a downstream service.

Cheers
Jon
