### ISSUE TITLE
Grant authority suggestion

### ISSUE THREAD

**Issue by PeterGGreen** [hmrc/vat-api#360]
Dear HMRC,

It's not a stumbling block, but it does seem odd that we can't grant authority for both retrieve and submit VAT with one visit the HMRC website.  So I would suggest a change whereby instead of submitting a "Scope" of read:vat or write:vat as part of the submission, we submit some JSON similar to CreateTestUser telling you what we're requesting authorisation for.  That way we can get both read and write authorisation in 1 token (and more importantly in one "log in" to HMRC).  Having to go through the same procedure twice for authorisation seems wasteful and fussy.

Perhaps too late now, but maybe for the future?

Cheers,

Peter

**Comment by adamdavi3s** [comment]
Hi Peter,

Is this in live?
I have no problem getting a read write scope in one token in the sandbox and am relying on it!

**Comment by PeterGGreen** [comment]
Hi Adam,

When you construct the URL, the scope is either read:vat or write:vat.  How can it be both?

Cheers,

Peter

**Comment by adamdavi3s** [comment]
Hi Peter,

Take a look here: https://github.com/hmrc/vat-api/issues/336

Adam

**Comment by PeterGGreen** [comment]
Hi Adam,

Thanks for the info and link.  It would've been nice to have had proper documentation for this project from the outset.  At no point was it made clear that you could request both scopes in one request.  Might as well start again.

Thanks again,

Peter

**Comment by PeterGGreen** [comment]
I've gone back to reread the documentation and it was there.  So it's definitely me at fault, ah well.   Feel free to close this issue (and quickly) :-)
