### ISSUE TITLE
If requesting open obligations only, remove the need for a date range.

### ISSUE THREAD

**Issue by PeterGGreen** [hmrc/vat-api#361]
Dear HMRC,

Just another suggestion.  But if the retrieve VAT obligations is requesting only open obligations, it removes the need for a date range.  I'd make the date range only needed if requesting all obligations.

Regards,

Peter

**Comment by markogrady** [comment]
I would second this

**Comment by adamdavi3s** [comment]
Third

**Comment by stuy1974** [comment]
Fourth!

**Comment by sparkz42** [comment]
It would probably be safer to always return all open obligations up to the one which is currently due. I know we don't want to make unnecessary work for the HMRC servers but for most users there would only be one open obligation.

So I fifth that!

**Comment by MarkAKelly** [comment]
Hi folks, 

This is a piece of functionality we are wanting to bring in, and is in our backlog - we are just waiting for the thumbs up from our downstream services.  I'll take the enthusiastic response to the rest of the team, and make sure that the story is prioritised accordingly.  

Many thanks,

Mark

**Comment by markogrady** [comment]
@MarkAKelly Out of interest how would you write the code at the moment to pull open returns. I have code that just searches from september last year til april this year on the first call. I did find with one client if I put the start date any earlier then I received a 404.

**Comment by james-work-account** [comment]
This has now been implemented - from & to dates are now ignored when you supply `status=O` (see the query parameters here: https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0#_retrieve-vat-obligations_get_accordion)

Thanks
James
