### ISSUE TITLE
API doesn't allow retry following possible failure scenario

### ISSUE THREAD

**Issue by simoncrabtree** [hmrc/vat-api#362]
I'm submitting a Support request;

If we submit a return for a period and then some error occurs before we receive the response or as part of updating our systems with the response result, then we cannot be sure whether that return has been received by HMRC. So our only option is to assume that it did not work and submit again. But if the original submission had actually worked, then we receive a 403 (Forbidden) response - indicating that this is a duplicate submission. But we never received (or managed to store) the first submission, and now we have no way of showing our user the usual success details for this submission (i.e. formBundleNumber, chargeRefNumber etc).

It seems that the process is fine as long as everything succeeds end-to-end, but it doesn't allow us to handle the inevitable failures which are bound to occur in distributed systems?

I have the same problem with the refresh_token part of the OAuth process (I do realise this is a different team's responsibility). It seems that a refresh_token can only be used once, but HMRC have no way to know whether we successfully received and stored the new token details. So if an error occurs, we are left with a permanently invalid token and no ability to retry.

Both of these processes appear to assume that it's possible to make API calls, over a potentially unreliable network, "exactly once" - am I missing something?

**Comment by GrahamHDawson** [comment]
What might work is if the ViewVATReturn endpoint returned the header details from the submission 
ie the processingDate, paymentIndicator, formBundleNumber and ChargeRefNumber.

I **think** the current idea is that a failed submission can be followed up using the CorrelationID - but if the end-user application fails to get that then we're really sunk :-)

In the case of the VAT API it only really matters for the submission endpoint - that really **is** critical and we need a way of recovering if things (as they inevitably will) go wrong.

Graham

**Comment by DigitalDan1** [comment]
> it doesn't allow us to handle the inevitable failures which are bound to occur in distributed systems

> we need a way of recovering if things (as they inevitably will) go wrong

I have the same concerns (although I don't think the refresh_token is a problem, it's easy enough to re-start the OAuth journey).

I'd also like to see the `/organisations/vat/{vrn}/returns/{periodKey}` endpoint return the same body as the response after a sucessful post to /organisations/vat/{vrn}/returns (in addition to the vat return body of course).  I'd go even further and say it should include the `Receipt-ID` and `Receipt-Timestamp` headers too.

This would allow us to consume the API using the following (pseudo code):

```
Submit VAT Return
if (ok) {
  store processingDate, formBundleNumber, X-CorrelationId, Receipt-ID, etc. in source system
}
else {
  Lookup VAT Return
  if (exists) {
    store processingDate, formBundleNumber, X-CorrelationId, Receipt-ID, etc. in source system
    return ok
  }
  else {
    throw error
  }
}
```

or even...

```
Submit VAT Return
if (ok) {
  return ok
}
else {
  Lookup VAT Return
  if (exists) {
    return ok
  }
  else {
    throw error
  }
}
```

...because we can always lookup the receipt/correlation details later if needed.

**Comment by jacobbrownlow** [comment]
Hi @simoncrabtree 

Sorry for the delay

You are correct that there is no way to retrieve the success responses once the VAT return has been submitted. Additionally in Production there is a delay before the backend will process the return and so 'View VAT return' will return 404 for a short while.

I not sure this vendor need has been raised before so I will have to feed this back to the team and follow up with any responses.

Jacob

**Comment by jonathanleather** [comment]
There is an issue already open regarding production timings #357. We are currently awaiting a definitive answer from the backend teams.

Cheers
Jon
