### ISSUE TITLE
Test Users Created through the 'Create a test user' page don't work with VAT API

### ISSUE THREAD

**Issue by DigitalDan1** [hmrc/vat-api#364]
Test users can be created through the web page on the developer hub (https://developer.service.hmrc.gov.uk/api-test-user) but these users can't be used with the Sandbox VAT API.  The API calls fail with CLIENT_OR_AGENT_NOT_AUTHORISED.

Only test users that were created through the create test user rest API work correctly (i.e. using https://test-api.service.hmrc.gov.uk/create-test-user/organisations instead).

This has been spotted by others (https://github.com/hmrc/vat-api/issues/154 and https://github.com/hmrc/vat-api/issues/157#issuecomment-441386266 and https://github.com/hmrc/vat-api/issues/315 and https://github.com/hmrc/vat-api/issues/170 and https://github.com/hmrc/vat-api/issues/131#issuecomment-386013486 and https://github.com/hmrc/vat-api/issues/191#issuecomment-404844680) but I think it needs a separate issue to track it.

This look like a bug to me, especially because the user (organisation user) that's created using the web page has a VAT Registration Number generated for it, so it's got all the details needed by the VAT API.

Obviously the preferred fix would be to make sure test users created through the web page work with the VAT API.  Alternatively, don't provide the web page for creating test users for the VAT API and make it clear that users should be created through the api instead.

**Comment by paulmowat** [comment]
I've also had this issue. The test page working would be very handy for non technical test users so they don't have to run scripts etc to get a new test account.

**Comment by OakleyLeon** [comment]
The api is the only way to create test users for VAT-MTD. the manual test user page does not work.

**Comment by AndyYouens** [comment]
It's very poor to expect us to have to write these features.  The web page needs changing the achieve this.

**Comment by marinalevit** [comment]
This is very helpful, thank you for posting as I could not figure out why the test user was not working.

Trying to use the API to create one, but getting server error with Service unavailable. Just me or is the create test user service down?

**Comment by jacobbrownlow** [comment]
Hi @marinalevit 

It appears to be working fine for me
![image](https://user-images.githubusercontent.com/35334115/50777031-675a3100-1292-11e9-93bb-e8bc3b010efe.png)

Do you have any more details?

**Comment by marinalevit** [comment]
Turns out error on my part - I guess some parameter checking missing that resulted in server error instead of a more helpful message. Thanks!

**Comment by lukeskinner** [comment]
Any update on this one? We were hoping to provide this URL to our testers but it looks like we're going to have to write a program to call the API (to make test users) for our testers instead.

**Comment by jacobbrownlow** [comment]
Apologies for the late reply

This issue has been raised before so we are aware of the frustration being caused.

Unfortunately the _Create Test User_ API, Frontend and Documentation is owned by another platform team. We appreciate that it is not clear the Frontend doesn't support mtd-vat.

We are in discussions with the other team to get this updated, but previously they were not interested in adding functionality to the Frontend and instead were directing us to the API.

I will give them another nudge today and see if I can get this resolved or at least improve the documentation to show mtd-vat isn't available for the Frontend.

Jacob

**Comment by shunty-gh** [comment]
Why did I have to dig into GitHub issues to find this! The create test user page specifically states "submit VAT returns". 
I don't mind having to use the API - I just want the docs to tell me that I need to instead of wasting hours trying to figure out why "documented" methods don't work.

**Comment by jacobbrownlow** [comment]
Hi @shunty-gh 

Unfortunately the _Create Test User_ API, Frontend and Documentation is owned by another platform team. We appreciate that it is not clear the Frontend doesn't support mtd-vat.

We have added the following to our documentation:
https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0
![image](https://user-images.githubusercontent.com/35334115/52650820-de629500-2ee2-11e9-8c2d-bd426fa97d67.png)

We have raised this with the other team and hopefully the Frontend will be enhanced soon to work with the MTD vat-api. We will let you know when we know anything.

Jacob

**Comment by shunty-gh** [comment]
@jacobbrownlow Thanks for that. And fair enough, yes, I now see those words. 

Unfortunately there are many twisty turny ways to get to different bits of the docs (I have 9 gov tabs open at this moment not counting the GitHub ones) and I guess it's mighty easy to overlook that bit when all the other bits keep pointing you towards the Create User page.

Nevertheless, it's sorted now, we know where we're going (I think). Thank you.
Steve

**Comment by paulmowat** [comment]
Has this been fixed to work with the MTD vat-api now since it's been closed?

**Comment by jacobbrownlow** [comment]
Hi everyone

I can confirm that the Create Test User Frontend now works for mtd vat-api, for both Individuals and Organisations

Regards, Jacob

**Comment by AndyYouens** [comment]
Better late than never :-)
