### ISSUE TITLE
Consistent naming of date/time fields

### ISSUE THREAD

**Issue by DigitalDan1** [hmrc/vat-api#366]
I'm submitting a suggestion for an improvement.

All of the API field names that expect/return a date are named as `to`, `from`, `due`, etc.  There's only one field in the whole VAT API that holds a date _and time_, it's `processingDate` in the response after submitting a VAT Return.

For consistency it would be good if it was called `processed` instead.  Or it could be more explicitly named `processingDateTime` (although that would suggest the other API fields should change to `dueDate`, `fromDate`, etc. which is a bigger change).

I understand this would be a breaking change but I thought it would be worth suggesting as the API is still in beta.

**Comment by macgrewal** [comment]
Thanks for the improvement @DigitalDan1. I've informed the Digital Service Manager and Product Manager who will decide if this is implemented.

**Comment by MKoppJones** [comment]
Can we have this issue updated if this gets implemented?

At this point, this would be a breaking change for us, so it would be nice to know.

I agree with the suggestion though.

**Comment by macgrewal** [comment]
Will do @MKoppJones though any breaking change will be communicated via SDST comms.
