### ISSUE TITLE
VBA interaction with sandbox

### ISSUE THREAD

**Issue by janeegrundy** [hmrc/vat-api#368]
I'm looking for advice on how to get my excel vba macro to interact with the hmrc vat sandbox. In the absence on other help hmrc suggested that I post on here.
I can get excel to populate a webform with the required definition but cannot get it to call the sandbox to test it and work through the authentication journey. Can anyone help?

**Comment by ma3574** [comment]
Hi @janeegrundy 

For issues relating to authentication (OAuth2) and for language specific queries please contact the SDST at SDSTeam@hmrc.gsi.gov.uk and inform them that you have been sent to them by the vat-api team. They should be able to help with your queries.

Kind regards
Muhammed

**Comment by davidglassborow** [comment]
@janeegrundy I suspect it will be very hard to get an Excel VBA macro to work with the hmrc vat sandbox. There are various technical things that need to be done, and I'm not sure they are possible in VBA, including:

- Sending and receiving data in JSON format
- Implementing the oauth2 security standard 
- Having an embedded webbrower for the user to login to (as part of the oauth authentication)

**Comment by janeegrundy** [comment]
@ma3574 hmrc sdsteam suggested I post on here. :(

@davidglasborow that's what I'm finding. I can fill a web form to the same spec quite easily and sure it could be a possible solution for those using spreasheets for their accounts.  Before we roll it out to customers I'd like to test it...

**Comment by adamdavi3s** [comment]
Quick bit of googling says it should all be possible? I don’t think you need to embed the web browser, they can authenticate and bring the auth code back to excel manually 

 I can’t imagine trying to code this myself but good luck to you!

**Comment by GrahamHDawson** [comment]
Hi Jane,

It's certainly possible - see the Neilson James Technology website and you can download their demo
https://www.neilsonjamestech.co.uk/vat-demo.php
It's a xlsb file with no supporting DLLs etc ie it's all done in VBA code.

Graham

**Comment by jacobbrownlow** [comment]
Hi Jane

We do leave these type of questions open so that other developers can contribute but it seems like this conversation has ended. So I will close the issue but feel free to re-open it if you need further assistance.

Regards, Jacob

**Comment by janeegrundy** [comment]
Hi. Could you leave it open as no one has cone up with an answer yet. 

 I was advised by HMRC to ask here as they monitor responses although their developers have been pulled onto Brexit projects so not currently responding.

**Comment by janeegrundy** [comment]
Could you reopen as I don't have the permissions.

**Comment by JoaStrzy** [comment]
HI, I am also interested in the subject and would be grateful for any help. I fail in trying to receive access and refresh tokens.

**Comment by SystemsModelling** [comment]
This is now April and so may be too late for any enquirer above but I have a working demo of the Hello demos (eg Hello User) in Excel VBA, It uses IEDialog for user authentication and a public domain JSON parser. If there is interest, I can post it for review.

**Comment by JeeBeePee** [comment]
I don't see how you could do it standalone, as you need to configure redirects for OAuth to work. You'd need to either run a service for each Excel user to connect to, or maintain a redirect URI for each user.

**Comment by SystemsModelling** [comment]
I posted my VBA code for the Hello World demos here:
https://sysmod.wordpress.com/2019/04/16/uk-hmrc-mtd-oauth2-excel-vba-demo/

That should be enough to get started.
