### ISSUE TITLE
Txm Headers - Desktop Installed App

### ISSUE THREAD

**Issue by PeterGGreen** [hmrc/vat-api#369]
Dear HMRC,

It looks like you're planning to go ahead and force us to implement these ridiculous TxM Headers.  These are the ones I'll need to implement for my Desktop Installed App:

Gov-Client-Public-IP
Gov-Client-Public-Port
Gov-Client-Device-ID
Gov-Client-User-IDs
Gov-Client-Timezone
Gov-Client-Local-IPs
Gov-Client-Screens
Gov-Client-Window-Size
Gov-Client-User-Agent
Gov-Client-Multi-Factor
Gov-Vendor-Version
Gov-Vendor-License-IDs
Gov-Client-MAC-Addresses

Some of these I get, Device ID, User ID etc.  But screen size?  App window size?  What relevance can these possibly have to the security of a submission?

The other problem is the public IP address and port.  Local IP address.  MAC addresses.  Elsewhere on this GitHub, people have requested that if this is absolutely required by HMRC, then you should provide another API which we can interrogate and receive this information to be put into the submission.  But the question begs, if the API has accepted the connection, then the API server/process already KNOWS the public IP and port that the client has used to make the connection.  Why not simply store this information along with the actual submission from the client?  Why include it at all in the headers of the submission?

Also, due to Cyber Security and GDPR, a lot of our customers PCs are now locked down very tightly and I very much doubt I'll be able to make Windows API calls to get local IP address and MAC addresses.  FYI, some network drivers allow you to change the MAC address, so it's particular irrelevant to store the MAC address.  And there is freely available MAC spoofing software readily downloadable.

Finally, feel free to supply some Visual Studio 2017 code which gathers all of the above information and I will happily use it, but having spent the better part of 3 months getting it working without these headers, I'm very reluctant to spend MORE time on this.  Especially as it's the time of year I have to start work on the payroll changes.

**Comment by ma3574** [comment]
Hi Peter

Sorry to hear that the headers are causing issues. Unfortunately the headers are mandated on the platform level and hence as the Vat-Api Team we have no control over them. Any changes would have to come from the platform. As such I would strongly recommend all interested parties to get in touch with SDST at SDSTeam@hmrc.gsi.gov.uk and explain the issues that these headers will cause and hopefully a resolution can be reached. For any vendors who have similar concerns, I would strongly recommend they get in touch with SDST too. 

I hope the SDST are able to resolve this in a manner that is pleasing to all parties involved. 

Kind regards
Muhammed

**Comment by KenRandall** [comment]
Couldn't agree with Peter more. Are these headers going to be available for testing in the Sandbox?

I can also see no mention of what responses will be given for missing headers!

**Comment by LukeHirst** [comment]
I would also like to know if these fraud prevention headers will be available for testing within the Sandbox? 

I have looked at the documentation on the developer hub and nothing has seemed to be updated in relation to the actual response returned if the Fraud Prevention headers are rejected or whether this is something that will be flagged up after a successful VAT Submission.

Furthermore if we can test these TxM headers in the sandbox than it is vital that the responses returned are stateful (not using the GOV-TEST-SCENARIO header) and represent what will actually be returned in production.

**Comment by Hollister** [comment]
Many of them are "if you can't get these due to security or other limitations then leave them blank". In practice, due to running code in secure sandboxes or not as a result of direct user interaction, this is likely to be the case, so I am leaving a lot of them blank

**Comment by GrahamHDawson** [comment]
Hi Peter,

Well you can knock 2 items off your list above as there's been an update today 11/12/2018 to the Anti-Fraud Headers page.
DESKTOP_APP_DIRECT applications will not now need to add the

Gov-Client-Public-IP and
Gov-Client-Public-Port

Graham

**Comment by PeterGGreen** [comment]
Result!!! :-)

**Comment by Yottskry** [comment]
I have a problem sending empty headers though - the HTTP library I'm using (Indy) does not allow the sending of empty headers. Trying to set a header value to a blank string ("") omits the header entirely, and there's nothing I can do to change that behaviour.

Does anyone know if there's a character I can send that will be functionally equivalent to a blank header?

**Comment by MKoppJones** [comment]
Could a zero-width-space work here? `\u200B`

**Comment by GrahamHDawson** [comment]
Don't know about Indy - but using LibCurl to send a blank header you use a semi-colon instead of a colon
eg 'Gov-Client-Device-ID;' instead of 'Gov-Client-Device-ID:'

Graham

**Comment by KenRandall** [comment]
I'm also using Indy but haven't got around to doing these headers yet. I thought I'd let the dust settle first and see if they remove any more of them :)

**Comment by Yottskry** [comment]
Right, the problem with Indy is that its idHeaderList inherits from TStringList, and TStringList doesn't allow key-value pairs with no value, so it straight-up isn't possible to send empty headers with Indy.
I've tried WinInet and that has the same problem: empty headers are stripped when the header is sent. So it looks like this idea of sending empty headers for uncollectable values is going to be problematic. 
I've emailed the SDS team at HMRC to ask for more information. I can't imagine I'm the only person who's going to struggle with this.

**Comment by MayaCKS** [comment]
I also use Delphi so will be running in to the same problem too probably



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by GrahamHDawson** [comment]
Maybe for Delphi users one of the solutions offered here could help...

https://stackoverflow.com/questions/33893377/can-i-prevent-tstringlist-removing-key-value-pair-when-value-set-to-empty

Graham

**Comment by Yottskry** [comment]
Thanks Graham, but a ClassHelper would change behaviour everywhere that a StringList is used, and superclassing TStringList isn't an option as we would then have to modify Indy to use this new class.

**Comment by hughfdjackson** [comment]
> Some of these I get, Device ID, User ID etc.  But screen size?  App  window size?  What relevance can these possibly have to the security of a  submission? 

All of the headers required have been specifically formulated in collaboration with HMRC's security departments, and are designed to mitigate against the risk of fraud specifically.  I'm sure you can appreciate we can't be more specific about this in public. 

> The other problem is the public IP address and port.  Local IP  address.  MAC addresses.  Elsewhere on this GitHub, people have  requested that if this is absolutely required by HMRC, then you should  provide another API which we can interrogate and receive this  information to be put into the submission.  But the question begs, if  the API has accepted the connection, then the API server/process already  KNOWS the public IP and port that the client has used to make the  connection.  Why not simply store this information along with the actual  submission from the client?  Why include it at all in the headers of  the submission? 

We agree - in the case of DESKTOP_APP_DIRECT and MOBILE_APP_DIRECT, the Gov-Client-Public-IP and Gov-Client-Public-Port are available to the API gateway, and not easily available to the application itself.   The latest spec (https://developer.service.hmrc.gov.uk/api-documentation/docs/fraud-prevention) therefore does not require those headers in the case of direct connections.

> Also, due to Cyber Security and GDPR, a lot of our customers PCs are  now locked down very tightly and I very much doubt I'll be able to make  Windows API calls to get local IP address and MAC addresses.  FYI, some  network drivers allow you to change the MAC address, so it's particular  irrelevant to store the MAC address.  And there is freely available MAC  spoofing software readily downloadable. 

Thanks for raising this issue - we had anticipated that type of behaviour may exist for some clients.  Having reviewed with our security departments, we still feel that it is useful data to have in order to fight fraud against HMRC.  As with the above, I'm afraid we don't intend to disclose the rationale behind these decisions to the public or third-party vendors.

We have stated in the documentation in the case of `Gov-Client-MAC-Addresses` that " If you cannot retrieve them due to operating system restrictions, then leave the header empty. "  Therefore if you make the appropriate Windows API calls, but security prevents you from getting those details, you may submit an empty header. 

> Finally, feel free to supply some Visual Studio 2017 code which  gathers all of the above information and I will happily use it, but  having spent the better part of 3 months getting it working without  these headers, I'm very reluctant to spend MORE time on this.   Especially as it's the time of year I have to start work on the payroll  changes.

We understand that it's extra work to provide these headers on behalf of vendors such as yourselves.  The API Platform serves a great range of developers using a range of different platforms.  Since we cannot know all of the platforms as well as the developers themselves, we're not looking to produce code examples specific to a platform.  

We're happy to hear feedback on what has been difficult in your platform and environment to implement the spec (you can find the current version - 2.1 - at https://developer.service.hmrc.gov.uk/api-documentation/docs/fraud-prevention).  If we can make it easier to implement in future, we'd be keen to do so.

**Comment by hughfdjackson** [comment]
Hi all - 

I believe the above post answers the original poster's question.  I noticed that there are other questions in this thread.  If those questions are still relevant (having read the latest spec - https://developer.service.hmrc.gov.uk/api-documentation/docs/fraud-prevention), please open issues on this github project and we'll answer them.

**Comment by hughfdjackson** [comment]
@Hollister 

Although the above comment about raising separate issues for separate questions applies, I noticed you made more of a comment: 

> Many of them are "if you can't get these due to security or other limitations then leave them blank". In practice, due to running code in secure sandboxes or not as a result of direct user interaction, this is likely to be the case, so I am leaving a lot of them blank

It will come as probably not much as a surprise that HMRC expects vendors to make a good-faith, best-effort attempt to collect this information _in every case_.  Even if you believe from prior business experience that your applications will send blank headers in practice, your application must attempt to collect + send the information.

**Comment by hughfdjackson** [comment]
@PeterGGreen  I'm going to have this topic closed.  If the response I gave above doesn't adequately answer your questions, we can re-open it later.
