### ISSUE TITLE
503 received for missing Content-Type header

### ISSUE THREAD

**Issue by scottylace** [hmrc/vat-api#374]
"I developed a test app that makes a VAT return with the VAT API. I got a HTTP status code of 503 service unavailable and I thought the VAT API is down. Eventually I figured out that only the Content-Type header was missing. I would expect a 4XX code, e.g. 415. Is it meant to return 503 in such a case?"

**Comment by london-coder** [comment]
Hi Scott,
Your assumption is correct, that a 400 or 415 would be more informative and accurate. However, the 5xx are the default errors returned by the back-end systems, that sit behind the VAT-API application, and are "passed through", for the most part uncorrected, by the VAT-API. This is a recurring topic of conversation among the team and, hopefully, we will be moving to return more accurate and HTTP status errors in the future.
