### ISSUE TITLE
Client Secret - Manual entry

### ISSUE THREAD

**Issue by PeterGGreen** [hmrc/vat-api#375]
Rather than maintain two client secret ID's (they're stored encrypted on our website), assumed I would be able to keep the client secret ID synchronized with a manual entry.  But when you add a new client secret, it generates a new random one.

Is it possible to add the client secret ID manually?

**Comment by GrahamHDawson** [comment]
Each application communicating with the MTD API has a clientID and a clientsecret which you get when your application is registered.
 (In our case the clientID and clientsecret strings are embedded within the application - but they could be stored in a database)

Why would you need to manually change either of these?

**Comment by PeterGGreen** [comment]
Hi Graham,

You get different Client ID per registered application, so 1 for Dev and 1 for Live.  I had planned to use the same client secret for both Dev and Live, but you can't do this.  I've sorted it now, but it was a small spanner in the works.

For reference, I wouldn't store the client secret in a compiled EXE, at least not without some obfuscation.  My solution is to force the program to download a small file from our website which contains both Dev and Live client secrets (again obfuscated), but every periodically I will be changing the client secret IDs for both Dev and Live and updating this file.

**Comment by GrahamHDawson** [comment]
Hi Peter,

Thanks for the information about Dev and Live clientID/clientSecret - is was wondering about that.

I remember reading in one of the docs about 'rotating' the clientID/clientSecret but couldn't find any information about how we're supposed to obtain the new clientID/clientSecret - how do we do that?

Graham
PS our embedded ID/Secrets are encoded.

**Comment by GrahamHDawson** [comment]
Ah OK thanks Peter.

Graham
