### ISSUE TITLE
Question Regards Sandbox Submit Return Response

### ISSUE THREAD

**Issue by sparkz42** [hmrc/vat-api#376]
Hi

Can someone please tell me if something changed with regards to the responses for submitting a return in the sandbox?

At the moment the response seems to be the opposite to what I got a week ago? i.e. for a debit return with net VAT to pay, I'm getting a response with "BANK" as the PaymentIndicator (for credit) and no chargeRefNumber. Similarly, with a credit return I'm getting "DD" and a chargeRefNumber as for a debit?

Example (credit):
`{"periodKey": "18A3", "vatDueSales": 200.00, "vatDueAcquisitions": 0.00, "totalVatDue": 200.00, "vatReclaimedCurrPeriod": 2000.00, "netVatDue": 1800.00, "totalValueSalesExVAT": 1000, "totalValuePurchasesExVAT": 10000, "totalValueGoodsSuppliedExVAT": 0, "totalAcquisitionsExVAT": 0, "finalised": true}

{"processingDate":"2018-12-17T23:53:48.361Z", "paymentIndicator":"DD", "formBundleNumber":"874847833440", "chargeRefNumber":"L7GvVMMR492bbSgH"}`

Thanks
Mark

**Comment by GrahamHDawson** [comment]
The paymentindicator in the test environment is random. I've just submitted the same vat figures several times and some came back as DD and some as BANK

**Comment by ma3574** [comment]
@GrahamHDawson is correct, the `paymentIndicator` is random and changes between `DD` and `BANK`

**Comment by sparkz42** [comment]
Ok, thanks. Guess I must have been lucky before as they always seemed to match what I expected.
