### ISSUE TITLE
Product demo to HMRC

### ISSUE THREAD

**Issue by Hollister** [hmrc/vat-api#377]
Hi

I was wondering if anyone who has had their production app approved and gone through the demo with HMRC has any insight into what they want to see during the demo.

The only thing we have really got from them is that it is a half hour informal demo, showing the end to end process. But as you can't actually do an end to end demo in the sandbox system I was wondering if anyone had any more detail having already experienced it.

Thanks

**Comment by GrahamHDawson** [comment]
I did our demo yesterday !

What they want to see is the whole user journey  from user authorisation to retrieving obligations and submitting returns, retrieving liabilities and payments as well (if your app will support those end points)

All done using the testing URL and a test user created from scratch and authorised during the demo.

It helps if you read the various end-to-end journey docs and do what they say (like providing a link so the user can access their HMRC business account, and providing the specific legal warning message before posting a VAT return)

You **can** actually mimic the end-to-end process by using the various obligations scenarios eg
Select Quarterly None met and submit a return (with memorable figures) for that 18A1 period
Select Quarterly One met and retrieve the values you've just submitted by retrieving the VAT return fro 18A1 (the figures **are** statefull and will reflect what you posted earlier)

We displayed the Period Keys on our windows and **that** was the only thing they asked us to change.
So if you are displaying Period Keys then remove them.

Graham

**Comment by GrahamHDawson** [comment]
I should add that they're **very** helpful.
We did the demo yesterday (successful) and today the application was listed on the  'software suppliers with VAT compatible products in development' web page !

Graham

**Comment by GrahamHDawson** [comment]
> The only thing we can't show in the end to end process is the submitted obligation changing from open to closed after the submission, as the response from the obligations API is stateless.

That's OK - they know the limitations of the sandbox system.

There's also the point raised in another issue that the changing from Outstanding to Fulfilled can take around 5 seconds to happen - so it will never immediately change (or rather cannot be relied upon to do so) - best to just display a message saying it's been submitted but may take some time to be reflected in the displayed Obligations.

Graham

**Comment by GrahamHDawson** [comment]
See Issue 357 for comment about Obligations delay changing from Outstanding to Fulfilled.

**Comment by mathiasbanda** [comment]
They wanted to see a receipt ID for related VAT submission

**Comment by Hollister** [comment]
Thanks for all the information. Our product team did the demo to HMRC and everything went smoothly

**Comment by lovleensony** [comment]
Hi Graham, Hollister, Mathiasbanda,

From the time you approached HMRC digital relationship manager, with your business details, to your demo, how much time did it take?

As in, it has been more than one week we submitted our company details and have requested to present a demonstration of our app but we have not heard back from the HMRC team.

Does it take so much time? Just curious. 

I even dropped a follow-up email (drm.service@hmrc.gov.uk), but no response yet.

I am sure they must be busy but just wanted to check if this is normal. 

Can you guys please share your experience and time it took for the whole process (not just the demo).


Thank you!

Lovleen

**Comment by cb-rfk** [comment]
Hi Lovleen,

I completed the online application on Thursday (28th) and followed it up with an email to the drm team the same time, and heard back yesterday with an appointment time for next Monday (11th).

Hope this helps.

**Comment by lovleensony** [comment]
Hi Cb-rfk,

Thanks for the information.

Is there an online application? Can you please share the link?

When I dropped an email to DRM team requesting to demo our product, they responded back with an email which had a questioner.

I just reverted to the same email responding to all the questions. Here are the first two questions:
------------------------------------------
What is your Company name?
.
.
What is your Company Registration Number (if you have one)? 
------------------------------------------
I received the set of questions on 25th and I responded on 26th. 

I followed up on 28th Feb, 4th Mar and today again over email (drm.service@hmrc.gov.uk)

I have not heard back from the DRM team. Is there any other email address of the DRM team?

Regards,
Lovleen

**Comment by mathiasbanda** [comment]
Hi Lovleen

Apologies for the delay the approval process took roughly 2 weeks. But there was only a small fraction of the number of developers ready to demo at the time. We are lucky enough to have a dedicated person who relentlessly chases hmrc for answers so that helped

**Comment by lovleensony** [comment]
Thanks, Mathiasbanda. I guess I will have to follow-up more often :-). 

I just got anxious because Cb-rfk emailed on 28th and heard back yesterday and we reverted to HMRC on 26th and still waiting for the reply.

**Comment by cb-rfk** [comment]
Hi @lovleensony ,

From memory, you need to log into the developer hub and set up the new application there. Once you've done that there is a link to get approval and you'll need to enter a description of the application and links to your terms of use and privacy policy etc...

Richard

**Comment by lovleensony** [comment]
Fantastic! Thanks for the information, Richard! Thanks a ton! Filling the form now :-)

I wonder why the DRM did not guide me to this process, instead, I was asked to respond to the email.
