### ISSUE TITLE
Retrieve submitted returns

### ISSUE THREAD

**Issue by JeeBeePee** [hmrc/vat-api#382]
Is it possible to view a list of returns previously submitted via the API in the test environment?  While it's possible to retrieve the detail of a return, if you know its periodKey, it doesn't seem possible to list submitted returns; the various test scenarios all return canned data.

Thanks
Charlie

**Comment by adamdavi3s** [comment]
Hi Charlie,

This is something I have requested:
https://github.com/hmrc/vat-api/issues/292

**Comment by AndyYouens** [comment]
The limited data provided makes testing pointless. Only providing 2 obligations is very poor

**Comment by jonathanleather** [comment]
Hi @JeeBeePee 

As @adamdavi3s has pointed out this has already been raised, I'll let the project know that it has been raised again so that they can prioritise accordingly. 

@AndyYouens We are currently reviewing the testing scenarios, there is also a Webinar planned for next week in order to get some more feedback on how we can improve them. If you are signed up for the webinar already please do share your feedback there. If not, could you raise a separate issue detailing as much as possible so we can take a look for you.

Cheers
Jon

**Comment by AndyYouens** [comment]
When is the webinar Jon?

Regards

Andy Youens
IBM Consultant
T | 03300 010958
M | 07770 380276
W | www.formaserve.co.uk<https://urldefense.proofpoint.com/v2/url?u=http-3A__www.formaserve.co.uk_&d=DwMFAg&c=tviVv7QE1Z3xlo0vK5KDZA&r=3t4NnSGZG4zeIOYT44tSVfwLEAu4Q1GtvSeCbNIHSVg&m=y8nW-hm0hVPUk0gUnuFsG37Tl2Acz9gJ1fPChAjpgtk&s=9rzKSftpf5wVJ1a98Cha-3Ax370ys2DmYiyMI-7OAf4&e=>

Twitter<https://urldefense.proofpoint.com/v2/url?u=https-3A__twitter.com_FormaServe&d=DwMFAg&c=tviVv7QE1Z3xlo0vK5KDZA&r=3t4NnSGZG4zeIOYT44tSVfwLEAu4Q1GtvSeCbNIHSVg&m=y8nW-hm0hVPUk0gUnuFsG37Tl2Acz9gJ1fPChAjpgtk&s=9XEJ_yU81yf-N5Pg4SPV8vDESP0Nf5X_NE3r86zcqeA&e=> | LinkedIn<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.linkedin.com_company_formaserve-2Dsystems&d=DwMFAg&c=tviVv7QE1Z3xlo0vK5KDZA&r=3t4NnSGZG4zeIOYT44tSVfwLEAu4Q1GtvSeCbNIHSVg&m=y8nW-hm0hVPUk0gUnuFsG37Tl2Acz9gJ1fPChAjpgtk&s=4J7nN5_D1kmpzjJl8vtpDYTTIhQM1VzFHJ101K_V6RA&e=> | YouTube<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.youtube.com_channel_UCGtM6gju0xr0GbSNDFsjT6w&d=DwMFAg&c=tviVv7QE1Z3xlo0vK5KDZA&r=3t4NnSGZG4zeIOYT44tSVfwLEAu4Q1GtvSeCbNIHSVg&m=y8nW-hm0hVPUk0gUnuFsG37Tl2Acz9gJ1fPChAjpgtk&s=0U-LFqIbzNWbcQuVl2kjaJbWYGW9JwmVgbTJTs9Ay4I&e=> | Facebook<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.facebook.com_Formaserve&d=DwMFAg&c=tviVv7QE1Z3xlo0vK5KDZA&r=3t4NnSGZG4zeIOYT44tSVfwLEAu4Q1GtvSeCbNIHSVg&m=y8nW-hm0hVPUk0gUnuFsG37Tl2Acz9gJ1fPChAjpgtk&s=9ra6HQn6O9csSjf1PmNnWycAZGXr8bhYNEoOz6CUR7E&e=>

Check out my PowerWire Articles<https://urldefense.proofpoint.com/v2/url?u=http-3A__powerwire.eu_author_andy-2Dyouens&d=DwMFAg&c=tviVv7QE1Z3xlo0vK5KDZA&r=3t4NnSGZG4zeIOYT44tSVfwLEAu4Q1GtvSeCbNIHSVg&m=y8nW-hm0hVPUk0gUnuFsG37Tl2Acz9gJ1fPChAjpgtk&s=hhyKTvKWLYw1tVyhU6FGQ4xLX_z18gSO2y7O1m53ADs&e=>
[---]
Disclaimer: This email and any attachments may contain confidential material and is solely for the use of the intended recipient(s). If you have received this email in error, please notify the sender immediately and delete this email. If you are not the intended recipient(s), you must not use, retain or disclose any information contained in this email. Any views or opinions are solely those of the sender and do not necessarily represent those of the FormaServe Systems. FormaServe does not guarantee that this email or any attachments are free from viruses or 100% secure. Unless expressly stated in the body of the text of the email, this email is not intended to form a binding contract - a list of authorised signatories is available from FormaServe Systems. FormaServe Systems is a limited company registered in England and Wales in 1990. Registered number: 2458169. Registered office: 91 Redland Drive Loughton Milton Keynes Bucks MK5 8FL. Website: www.formaserve.co.uk<https://urldefense.proofpoint.com/v2/url?u=http-3A__www.formaserve.co.uk_&d=DwMFAg&c=tviVv7QE1Z3xlo0vK5KDZA&r=3t4NnSGZG4zeIOYT44tSVfwLEAu4Q1GtvSeCbNIHSVg&m=y8nW-hm0hVPUk0gUnuFsG37Tl2Acz9gJ1fPChAjpgtk&s=9rzKSftpf5wVJ1a98Cha-3Ax370ys2DmYiyMI-7OAf4&e=>

[a]

**Comment by jonathanleather** [comment]
Tuesday 15th - I believe there is a morning and afternoon session.

Cheers
Jon
