### ISSUE TITLE
Submit VAT return for period - Response headers don't match documentation for sandbox

### ISSUE THREAD

**Issue by lukeskinner** [hmrc/vat-api#383]
* **I'm submitting a ...**
  - [ ] Bug - API
  - [x] Bug - Documentation
  - [ ] Improvement
  - [ ] Feature request
  - [ ] Support request

According to https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0#_submit-vat-return-for-period_post_accordion for the "Submit VAT return period" it will return the following response headers:
- X-CorrelationId
- Receipt-ID
- Receipt-Timestamp
- Receipt-Signature

When I use use the sandbox environment I see the following:

![image](https://user-images.githubusercontent.com/7475696/50895896-5844c180-13ff-11e9-8feb-e779ee08c303.png)

The casing doesn't match the documentation for both Receipt-ID and X-CorrelationId. 
Should we be ignoring case of these headers? Or is this a sandbox problem?

**Comment by MarkAKelly** [comment]
Hi @lukeskinner,

I'm looking into this one for you and I can recreate your problem in the sandbox environment but none of our other test environments, so I'm led to believe this might be a quirk of the environment or the API platform services that sit before us.

I will carry on digging and get back to you with an answer shortly.

Cheers, Mark

**Comment by MarkAKelly** [comment]
Hi @lukeskinner,

We've been having a conversation with the HMRC API gateway teams for the last couple of days about this, as it appears its happening as it travels through the platform gateway before it reaches our API.  Their judgment is 'that header names should be case insensitive according to W3 RFC261, therefore those header names are logically the same. https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2'.

I appreciate this is not ideal, and I will be pushing to make sure this is explained in the documentation.  The conversation is ongoing as we will be pushing to make sure headers remain the same as the documentation, so I will keep this issue open and update in here if we make any headway.

Thanks,

Mark

**Comment by lukeskinner** [comment]
Thanks for looking into this, happy to go with the case insensitive matching.
