### ISSUE TITLE
Submit VAT return for period - INVALID_ARN Scenario returns 500 error in Sandbox

### ISSUE THREAD

**Issue by lukeskinner** [hmrc/vat-api#384]
* **I'm submitting a ...**
  - [x] Bug - API
  - [ ] Bug - Documentation
  - [ ] Improvement
  - [ ] Feature request
  - [ ] Support request

* **What is the current behaviour?**

I'm currently testing the different Gov Test Scenarios for the Submit VAT return for period API call in the Sandbox environment. 

The [INVALID_ARN](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0#_submit-vat-return-for-period_post_accordion) scenario returns a 500 internal server error: 
`{"code":"INTERNAL_SERVER_ERROR","message":"An internal server error occurred"}`

INVALID_VRN, INVALID_PERIODKEY and INVALID_PAYLOAD all return a 404 code with a response like:
`{"code":"VRN_INVALID","message":"The provided VRN is invalid"}`

Raw request:
```
POST https://test-api.service.hmrc.gov.uk/organisations/vat/666493909/returns HTTP/1.1
Authorization: Bearer removed
Gov-Test-Scenario: INVALID_ARN
Accept: application/vnd.hmrc.1.0+json
Content-Type: application/json; charset=utf-8
Host: test-api.service.hmrc.gov.uk
Cookie: mdtp=4xijSnpZP1Ih09UfnzFKzYmdl3YZkkqWO6ojSegexJDC4cSmYyOguE9uzRcvFQ4tvBmIx4E6ebz9/lV5BhozZvNjhjgO5pe7WWjFzBJT2hKXZQ+P+u5viuM=; mdtpdi=mdtpdi#87091807-e6da-48b8-b348-2771e3995287#1547125839399_GIQNhSvk7Te9iUIdlMHAbA==
Content-Length: 274
Expect: 100-continue

{"periodKey":"18A2","vatDueSales":0.00,"vatDueAcquisitions":0.00,"totalVatDue":0.00,"vatReclaimedCurrPeriod":0.00,"netVatDue":0.00,"totalValueSalesExVAT":0.00,"totalValuePurchasesExVAT":0.00,"totalValueGoodsSuppliedExVAT":0.00,"totalAcquisitionsExVAT":0.00,"finalised":true}
```

Raw Response:
```
HTTP/1.1 500 Internal Server Error
Content-Type: application/json
Content-Length: 78
Cache-Control: no-cache,no-store,max-age=0
Vary: Accept
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=31536000;
Date: Thu, 10 Jan 2019 13:39:33 GMT
Connection: close

{"code":"INTERNAL_SERVER_ERROR","message":"An internal server error occurred"} 

```
Should this be returning an internal server error? I saw #290 says agents aren't supported in the Sandbox so I'm assuming it's related to me using an organisation.

**Comment by jonathanleather** [comment]
Hey @lukeskinner 

Short answer?...No, it should not be returning an internal server error. As it should not even be there.
We shall get this cleared up and removed for you.

Thank you for raising!

Jon
