### ISSUE TITLE
Retrieve VAT payments date range problem

### ISSUE THREAD

**Issue by AndyYouens** [hmrc/vat-api#385]
Trying to use the Retrieve VAT payments endpoint, but never getting actual data returned for any dates I supply.

I have 2 obligations dated 01/01/17 to 30/06/17, if i pass the date range of payment from these dates i get 

 ERROR Text:  {"code":"NOT_FOUND","message":"The remote endpoint has indicated that no data can be found"}

this is using;
 https://test-api.service.hmrc.gov.uk/organisations/vat/666512732/payments?from=2017-01-01&to=2017-06-30

If i use their example of 2017-01-25 as both dates, it returns 'Invalid date range'

Anyone else had this issue?

**Comment by jonathanleather** [comment]
Hey @AndyYouens 

For the payments endpoint you need to pass in one of the gov-test-scenarios along with your request in order to get data back. There is a gov-test-scenario which returns 1 payment and another that returns multiple payments. 

If you user either of those gov-test-scenarios with the dates you have been using you should be returned data.

I must point out though that this endpoint is not linked to the obligations endpoint, as both endpoints are stateless and return canned data in the sandbox environment.

Let me know if you need any more help.

Cheers
Jon

**Comment by AndyYouens** [comment]
Thanks Jon

What is the format of the accept header with the test scenario?  cant find it anywhere in the documentation.

I'm sending
application/vnd.hmrc.1.0+json/SINGLE_LIABILITY

thanks for your help, appreciated.

**Comment by jonathanleather** [comment]
I see your issue. The Gov-Test-Scenario is its own header and should look like the image below.

<img width="910" alt="headers" src="https://user-images.githubusercontent.com/19834448/51020605-f0b18200-1576-11e9-98f7-d4234366686d.png">

Just as a side note - There are a range of Gov-Test-Scenarios for each endpoint, the details of each scenario can be found in the documentation under the Test Data section (endpoint specific). The Obligations, Payments and Liabilities endpoints are stateless so have more gov-test-scenarios. Submit VAT Return and View VAT Return are stateful so you should be able to do the majority of your testing without the need for the header.

Cheers
Jon

**Comment by MeliaDavies** [comment]
Has this been resolved? 

If so I will close the issue.

Thanks

**Comment by AndyYouens** [comment]
Yes, it has thanks.

Regards

Andy Youens
IBM Consultant
T | 03300 010958
M | 07770 380276
W | www.formaserve.co.uk<https://urldefense.proofpoint.com/v2/url?u=http-3A__www.formaserve.co.uk_&d=DwMFAg&c=tviVv7QE1Z3xlo0vK5KDZA&r=3t4NnSGZG4zeIOYT44tSVfwLEAu4Q1GtvSeCbNIHSVg&m=y8nW-hm0hVPUk0gUnuFsG37Tl2Acz9gJ1fPChAjpgtk&s=9rzKSftpf5wVJ1a98Cha-3Ax370ys2DmYiyMI-7OAf4&e=>

Twitter<https://urldefense.proofpoint.com/v2/url?u=https-3A__twitter.com_FormaServe&d=DwMFAg&c=tviVv7QE1Z3xlo0vK5KDZA&r=3t4NnSGZG4zeIOYT44tSVfwLEAu4Q1GtvSeCbNIHSVg&m=y8nW-hm0hVPUk0gUnuFsG37Tl2Acz9gJ1fPChAjpgtk&s=9XEJ_yU81yf-N5Pg4SPV8vDESP0Nf5X_NE3r86zcqeA&e=> | LinkedIn<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.linkedin.com_company_formaserve-2Dsystems&d=DwMFAg&c=tviVv7QE1Z3xlo0vK5KDZA&r=3t4NnSGZG4zeIOYT44tSVfwLEAu4Q1GtvSeCbNIHSVg&m=y8nW-hm0hVPUk0gUnuFsG37Tl2Acz9gJ1fPChAjpgtk&s=4J7nN5_D1kmpzjJl8vtpDYTTIhQM1VzFHJ101K_V6RA&e=> | YouTube<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.youtube.com_channel_UCGtM6gju0xr0GbSNDFsjT6w&d=DwMFAg&c=tviVv7QE1Z3xlo0vK5KDZA&r=3t4NnSGZG4zeIOYT44tSVfwLEAu4Q1GtvSeCbNIHSVg&m=y8nW-hm0hVPUk0gUnuFsG37Tl2Acz9gJ1fPChAjpgtk&s=0U-LFqIbzNWbcQuVl2kjaJbWYGW9JwmVgbTJTs9Ay4I&e=> | Facebook<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.facebook.com_Formaserve&d=DwMFAg&c=tviVv7QE1Z3xlo0vK5KDZA&r=3t4NnSGZG4zeIOYT44tSVfwLEAu4Q1GtvSeCbNIHSVg&m=y8nW-hm0hVPUk0gUnuFsG37Tl2Acz9gJ1fPChAjpgtk&s=9ra6HQn6O9csSjf1PmNnWycAZGXr8bhYNEoOz6CUR7E&e=>

Check out my PowerWire Articles<https://urldefense.proofpoint.com/v2/url?u=http-3A__powerwire.eu_author_andy-2Dyouens&d=DwMFAg&c=tviVv7QE1Z3xlo0vK5KDZA&r=3t4NnSGZG4zeIOYT44tSVfwLEAu4Q1GtvSeCbNIHSVg&m=y8nW-hm0hVPUk0gUnuFsG37Tl2Acz9gJ1fPChAjpgtk&s=hhyKTvKWLYw1tVyhU6FGQ4xLX_z18gSO2y7O1m53ADs&e=>
[---]
Disclaimer: This email and any attachments may contain confidential material and is solely for the use of the intended recipient(s). If you have received this email in error, please notify the sender immediately and delete this email. If you are not the intended recipient(s), you must not use, retain or disclose any information contained in this email. Any views or opinions are solely those of the sender and do not necessarily represent those of the FormaServe Systems. FormaServe does not guarantee that this email or any attachments are free from viruses or 100% secure. Unless expressly stated in the body of the text of the email, this email is not intended to form a binding contract - a list of authorised signatories is available from FormaServe Systems. FormaServe Systems is a limited company registered in England and Wales in 1990. Registered number: 2458169. Registered office: 91 Redland Drive Loughton Milton Keynes Bucks MK5 8FL. Website: www.formaserve.co.uk<https://urldefense.proofpoint.com/v2/url?u=http-3A__www.formaserve.co.uk_&d=DwMFAg&c=tviVv7QE1Z3xlo0vK5KDZA&r=3t4NnSGZG4zeIOYT44tSVfwLEAu4Q1GtvSeCbNIHSVg&m=y8nW-hm0hVPUk0gUnuFsG37Tl2Acz9gJ1fPChAjpgtk&s=9rzKSftpf5wVJ1a98Cha-3Ax370ys2DmYiyMI-7OAf4&e=>

[a]
