### ISSUE TITLE
Sandbox testing

### ISSUE THREAD

**Issue by scottlarge** [hmrc/vat-api#388]
**Note: Please read before raising an issue**. This repository's issues are reserved for **Technical** queries relating to the VAT-API Only. 
If your issue falls into any of the below categories please contact SDST at SDSTeam@hmrc.gsi.gov.uk:
- Issues relating to subscribing/registering to use the API Platform, MTD enrolment / de enrolment  / registration for VAT / BETA etc
- Issues relating to OAuth2
- Issues relating to integrating with the API Platform (setting up an application/access)
- Vendor application software questions (code examples in .NET / VB6 etc.)
- Business related questions
- Scheduled maintenance days / windows
- Onboarding 
- Performance metrics
- Questions relating to the process pre MTD

When submitting an issue please try to provide the following information:

* **I'm submitting a ...**
  - [ ] Bug - API
  - [ ] Bug - Documentation
  - [ ] Improvement
  - [ ] Feature request
  - [x] Support request

* **What is the current behaviour?**

* **What is the expected behaviour?**

* **Other information** (e.g. detailed explanation, screenshots, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Find answers to common questions [here](https://github.com/hmrc/vat-api/wiki/FAQ)

**Comment by scottlarge** [comment]
Hello,

I understand creating test agents and authorising test users for those agents isn't possible at the moment in Beta but can you use "live" details in Sandbox? Could an agent test against using their login details and submitting test returns for their clients using live VRNs? 

Thanks.

**Comment by MeliaDavies** [comment]
Hi Scott,
The sandbox environment is entirely separate from the live environment and so you will not be able to use live credentials. 
We are currently reviewing the process for creating agents in sandbox with a view to creating a simple way to do this. 
Comms will be sent out when this has been completed.

**Comment by kityasisrishu** [comment]
Hi,
How to do Agent Authorization in Sandbox?
If possible then please help the steps to file behave of client .
Thanks

**Comment by MeliaDavies** [comment]
Hi @kityasisrishu 
There is currently no way to test agents in Sandbox, as I said previously, we are currently reviewing this process and we will send out comms when this is completed.

**Comment by scottlarge** [comment]
Thanks for your help

**Comment by kityasisrishu** [comment]
Now I am getting below exception:
{ "code" : "RESOURCE_FORBIDDEN", "message" : "The application is not subscribed to the API which it is attempting to invoke" }

when trying to link ARN to VRN(/agents/{arn}/invitations)

**Comment by Veenaadepu** [comment]
Hi ,
I am trying to approve agent invitation , and current status is pending only.. can anyone help on this.

{"_links":{"self":{"href":"/agents/YARN0950056/invitations/CL8LFNZOCXUOM"}},"created":"2019-02-05T12:42:16.228Z","expiresOn":"2019-02-15T00:00:00.000","arn":"YARN0950056","service":["MTD-VAT"],"status":"Pending","clientActionUrl":"https://test-www.tax.service.gov.uk/invitations/CL8LFNZOCXUOM"}
