### ISSUE TITLE
The client and/or agent is not authorised.

### ISSUE THREAD

**Issue by AndyYouens** [hmrc/vat-api#390]
Getting a 'The client and/or agent is not authorised.'  all of a sudden??

Have tried creating a new user, no difference.  Tried users that were working, but still not authorised.

All been working fine up to now :-(

What am I missing?

{"status":403,"response":{"req":{"method":"GET","url":"https://test-api.service.hmrc.gov.uk/organisations/vat/666041662/liabilities?from=2017-04-05&to=2017-12-21","headers":{"user-agent":"node-superagent/4.0.0","accept":"application/vnd.hmrc.1.0+json","gov-test-scenario":"MULTIPLE_LIABILITIES","authorization":"Bearer 363137db31cb66751e2e5ef9e262a4b"}},"header":{"content-type":"application/json","content-length":"96","cache-control":"no-cache,no-store,max-age=0","vary":"Accept","x-content-type-options":"nosniff","strict-transport-security":"max-age=31536000;","date":"Wed, 16 Jan 2019 08:07:27 GMT","connection":"close"},"status":403,"text":"{\"code\":\"CLIENT_OR_AGENT_NOT_AUTHORISED\",\"message\":\"The client and/or agent is not authorised.\"}"}}

Thanks for your help.

**Comment by narendravijayarao** [comment]
Hi Andy,

Morning... We had a look and tried on our side, everything is working fine with the auth process.

Is it possible to give the information about how you are creating the user and tokens?

Thanks,
Naren.

**Comment by AndyYouens** [comment]
Hi there

the new user is created by 'Create Test User'  API  giving the VAT MTD authority.

has been working fine up to 1500 yesterday.  User created previously were working, but have now stopped.

**Comment by narendravijayarao** [comment]
Hi Andy,

We just created a new user and hit the VAT API and it is working fine. So there may be some issue on your side. 

We need more information to help you with!!! Whats steps? Also make sure you are using the right Bearer token.

Thanks...

**Comment by AndyYouens** [comment]
Thanks for your help.

yes, ours is working too now :-)

What did you change - LOL!
