### ISSUE TITLE
Submit VAT Return POST call returns 406 Not acceptable

### ISSUE THREAD

**Issue by CB-Stuart** [hmrc/vat-api#391]
* **I'm submitting a ...**
  - [ ] Bug - API
  - [ ] Bug - Documentation
  - [ ] Improvement
  - [ ] Feature request
  - [*] Support request

Hi,

We are adding MTD functionality to one of our applications, which is used by a number of retailers to do their accounting with, but have hit a brick wall trying to get the VAT Return to submit.

Unfortunately due to the older architecture of this application we are currently required to use the basic jax rs classes to interface with the api.  This works perfectly fine for authenticating, getting the obligations and liabilities etc, but we simply cannot get a return to submit.

`

	Client client = ClientBuilder.newClient();				
	Form form = new Form();
	form.param("periodKey", searchParams.getPeriodKey());
	form.param("vatDueSales", vatReturn.vatDueSales);
	form.param("vatDueAcquisitions", vatReturn.vatDueAcquisitions);
	form.param("totalVatDue", vatReturn.totalVatDue);
	form.param("vatReclaimedCurrPeriod", vatReturn.vatReclaimedCurrPeriod);
	form.param("netVatDue", vatReturn.netVatDue);
	form.param("totalValueSalesExVAT", vatReturn.totalValueSalesExVAT);
	form.param("totalValuePurchasesExVAT", vatReturn.totalValuePurchasesExVAT);
	form.param("totalValueGoodsSuppliedExVAT", vatReturn.totalValueGoodsSuppliedExVAT);
	form.param("totalAcquisitionsExVAT", vatReturn.totalAcquisitionsExVAT);
	form.param("finalised", "true");
				
	Response response = client.target(targetURI)
	               .request(MediaType.APPLICATION_JSON_TYPE)
	               .header("Accept", "application/vnd.hmrc.1.0+json")
	               .header("Content-Type", "application/json")
	               .header("Authorization", "Bearer " + token.accessToken)
	               .post(Entity.form(form));

`
No matter what we do, we always get the following response:

`

	InboundJaxrsResponse{ClientResponse{method=POST, uri=https://test-api.service.hmrc.gov.uk/organisations/vat/_vat id_/returns, status=406, reason=Not Acceptable}} with the error code: ACCEPT_HEADER_INVALID and message: The accept header is missing or invalid

`

We know the values are acceptable as they work when submitted via Postman and have used what we believe to be exactly the same headers as well.

The data has also been submitted as raw JSON string data with the same result.

`

	StringBuilder JSONString = new StringBuilder();
		JSONString.append("{");
		JSONString.append("\"periodKey\":\"" + searchParams.getPeriodKey());
		JSONString.append("\",");
		JSONString.append("\"vatDueSales\":" + vatReturn.vatDueSales);
		JSONString.append(",");
		JSONString.append("\"vatDueAcquisitions\":" + vatReturn.vatDueAcquisitions);
		JSONString.append(",");
		JSONString.append("\"totalVatDue\":" + vatReturn.totalVatDue);
		JSONString.append(",");
		JSONString.append("\"vatReclaimedCurrPeriod\":" + vatReturn.vatReclaimedCurrPeriod);
		JSONString.append(",");
		JSONString.append("\"netVatDue\":" + vatReturn.netVatDue);
		JSONString.append(",");
		JSONString.append("\"totalValueSalesExVAT\":" + vatReturn.totalValueSalesExVAT);
		JSONString.append(",");
		JSONString.append("\"totalValuePurchasesExVAT\":" + vatReturn.totalValuePurchasesExVAT);
		JSONString.append(",");
		JSONString.append("totalValueGoodsSuppliedExVAT\":" + vatReturn.totalValueGoodsSuppliedExVAT);
		JSONString.append(",");
		JSONString.append("totalAcquisitionsExVAT\":" + vatReturn.totalAcquisitionsExVAT);
		JSONString.append(",");
		JSONString.append("\"finalised\":" + "true");
		JSONString.append("}");
			
		Response response = client.target(targetURI)
			.request(MediaType.APPLICATION_JSON)
			.header(HttpHeaders.ACCEPT, HMRCApiInterfaceProperties.apiVersion)
			.header(HttpHeaders.CONTENT_TYPE, HMRCApiInterfaceProperties.acceptContentType)
			.header(HttpHeaders.AUTHORIZATION, "Bearer " + token.accessToken)
			.post(Entity.entity(JSONString.toString(), MediaType.APPLICATION_JSON), Response.class);

`
Would be really grateful if someone could point out any potential errors we have made, or suggest how we can troubleshoot this further, as it has us totally stumped at present!!

**Comment by ShoLongBruce** [comment]
I use VB.NET and hit a similar brickwall. But I think your problem lies with this line
form.param("finalised", "true");
Finalised needs to be a true boolean (true/false) and NOT "true" or "false"

my code used to be like this which didn't work
Add("finalised", IIf(VATObj.finalised, "True", "False"))

But when I changed it to this Add("finalised", IIf(VATObj.finalised, True, False))
it works. So I'm guessing that you somehow need to amend your code to add a "proper" boolean?

**Comment by CB-Stuart** [comment]
Thanks. I'll check that out.

**Comment by GrahamHDawson** [comment]
Hi Stuart,

We use Fiddler 4 to see exactly what headers etc are posted to the endpoints.

As for the finalised parameter we're sending the string value 'true' with no issues here (using curl).

Graham

**Comment by CB-Stuart** [comment]
Thanks Graham. I tried WireShark but couldn't decrypt the data to view it. We have made successful calls using Postman but not via the Java application.

**Comment by GrahamHDawson** [comment]
Hi Stuart,

Fiddler lets you decrypt https data and headers
 https://www.telerik.com/fiddler

Graham

**Comment by CB-Stuart** [comment]
Hi,
I manage to get the submit call to work by reworking the code to have a similar format as the get calls

`

				Client client = ClientBuilder.newClient();
				
				StringBuilder JSONString = new StringBuilder();
				JSONString.append("{");
				JSONString.append("\"periodKey\":\"" + searchParams.getPeriodKey());
				JSONString.append("\",");
				JSONString.append("\"vatDueSales\":" + vatReturn.vatDueSales);
				JSONString.append(",");
				JSONString.append("\"vatDueAcquisitions\":" + vatReturn.vatDueAcquisitions);
				JSONString.append(",");
				JSONString.append("\"totalVatDue\":" + vatReturn.totalVatDue);
				JSONString.append(",");
				JSONString.append("\"vatReclaimedCurrPeriod\":" + vatReturn.vatReclaimedCurrPeriod);
				JSONString.append(",");
				JSONString.append("\"netVatDue\":" + vatReturn.netVatDue);
				JSONString.append(",");
				JSONString.append("\"totalValueSalesExVAT\":" + vatReturn.totalValueSalesExVAT);
				JSONString.append(",");
				JSONString.append("\"totalValuePurchasesExVAT\":" + vatReturn.totalValuePurchasesExVAT);
				JSONString.append(",");
				JSONString.append("\"totalValueGoodsSuppliedExVAT\":" + vatReturn.totalValueGoodsSuppliedExVAT);
				JSONString.append(",");
				JSONString.append("\"totalAcquisitionsExVAT\":" + vatReturn.totalAcquisitionsExVAT);
				JSONString.append(",");
				JSONString.append("\"finalised\":" + "true");
				JSONString.append("}");
				
				Builder builder = client.target(targetURI).request();
				builder.header(HttpHeaders.CONTENT_TYPE, HMRCApiInterfaceProperties.acceptContentType);
				builder.header(HttpHeaders.ACCEPT, HMRCApiInterfaceProperties.apiVersion);
				builder.header(HttpHeaders.AUTHORIZATION, "Bearer " + token.accessToken);

				Response response = builder.post(Entity.json(JSONString.toString()));
`

I'm not sure why this works and the original didn't as that worked successfully for other APIs.

Many thanks for everyone's suggestions.
