### ISSUE TITLE
Fraud Prevention Headers - blank header values

### ISSUE THREAD

**Issue by Yottskry** [hmrc/vat-api#393]
Hi,

I've asked this twice by email but not had a response:

The documentation says that where a header is applicable for a particular app type (for example, DESKTOP_APP_DIRECT) but no value can be collected, an empty header value should be sent and values such as "nil", "null", "unassigned" are not acceptable.

The problem I have is that the HTTP library I'm using (Indy) does not allow the sending of headers with no values; they are simply stripped out. I have also tried using the lower-level WinInet library and this too strips out empty header values. 

My question is: is it acceptable to send a different character (a space, a semicolon, etc) as a substitute for a properly empty value? I simply cannot send a value of zero-width, and I'm sure I won't be alone in this. The revevant RFC does seem to imply that empty headers are not valid.

Thanks.

**Comment by GrahamHDawson** [comment]
See issue 369 for more on this problem with Indy (no solution I'm afraid)

Graham

**Comment by Yottskry** [comment]
> 
> 
> See issue 369 for more on this problem with Indy (no solution I'm afraid)
> 
> Graham

It's not just Indy, Graham. The same problem occurs using WinInet. I'm *fairly* sure sending of blank header values is not part of the RFC!

**Comment by KenRandall** [comment]
I'm currently not submitting any of the fraud prevention headers and the Sandbox is not rejecting any submissions!

Ken

**Comment by adamdavi3s** [comment]
The sandbox isn’t configured to test these headers frustratingly

**Comment by obeea** [comment]
Our solution currently does not supply any fraud prevention headers and we are able to submit VAT returns in the production environment.
Maybe one day it will stop working, but until then we don't intend adding them, they are just too difficult to implement.

**Comment by Yottskry** [comment]
I'd be very wary of not implementing *any* of the headers; they do state they are mandatory.

**Comment by adamdavi3s** [comment]
^ this

They are coming
They will cause your app to fail when they get switched on
While I agree some of them seem a little redundant and hard to collect, most of them are ok and indeed a lot of them can be left blank if you’re unable to collect the information.

**Comment by GrahamHDawson** [comment]
I think you should at least add the easier headers.
When they do become mandatory the first thing you'll know about it is your end-users won't be able to submit their returns and you'll have very limited time to fix things.

I'm sure one of the emails from the SDST stated they would be mandatory from 1st April.

**Comment by KenRandall** [comment]
Does anyone have an example of a a header showing how they are combined as the documentation doesn't show real examples.

Thanks,

Ken

**Comment by london-coder** [comment]
At this point in time, the VAT-API team are not progressing the proposed fraud prevention headers. It might be the case that this issue will "come around" again. For the time being, please address your concerns or enquiries to the Software Developers Support Team, their email is: SDSTeam@hmrc.gsi.gov.uk

**Comment by adamdavi3s** [comment]
Sorry can we have clarification please, that’s a very important statement you’ve just made there and it is not totally clear 

Are you saying that the headers are now NOT being implemented as a requirement for the VAT API 

Or are you saying that you’re unable to provide assistance in progressing them?

**Comment by adamdavi3s** [comment]
@London-coder thank you for the clarification!

**Comment by Yottskry** [comment]
> 
> 
> At this point in time, the VAT-API team are not progressing the proposed fraud prevention headers. It might be the case that this issue will "come around" again. For the time being, please address your concerns or enquiries to the Software Developers Support Team, their email is: [SDSTeam@hmrc.gsi.gov.uk](mailto:SDSTeam@hmrc.gsi.gov.uk)

@london-coder We don't get any replies from SDSTeam. I've emailed THREE times, before and after Christmas, with the same question and haven't received a reply. They changed the fraud prevention headers in December, then changed them again after feedback, and now it's not possible to get responses to very simple questions regarding them. What happens if headers are missing or invalid? Is the submission rejected? Is there a specific error message to inform the user which header was rejected and why? For those of us using libraries that can't send empty headers, what are the consequences of missing out a particular header? These shouldn't be hard questions for the team that is implementing the headers to answer, but we're not even getting acknowledgment that our emails are received. 

It's **really** not good enough. HMRC say they want to engage with developers but, apart from the responses here, we're met with a wall of silence.

**Comment by KenRandall** [comment]
It is nonsensical that we cannot test the fraud prevention headers.

Ken

**Comment by hughfdjackson** [comment]
@Yottskry - Hi.  As @london-coder commented above, we understand your frustration with the slow response.  My apologies on that front. 

In regards to your original question:

> Hi,
> I've asked this twice by email but not had a response:
> The documentation says that where a header is applicable for a particular app type (for example, DESKTOP_APP_DIRECT) but no value can be collected, an empty header value should be sent and values such as "nil", "null", "unassigned" are not acceptable.
> The problem I have is that the HTTP library I'm using (Indy) does not allow the sending of headers with no values; they are simply stripped out. I have also tried using the lower-level WinInet library and this too strips out empty header values.
> My question is: is it acceptable to send a different character (a space, a semicolon, etc) as a substitute for a properly empty value? I simply cannot send a value of zero-width, and I'm sure I won't be alone in this. The revevant RFC does seem to imply that empty headers are not valid.
> Thanks.

As you've seen, you're not the only developer who has had this issue.  We will be releasing an updated spec soon that allows an _alternative_ value for those cases we've asked for empty headers.  We will let you know - either here or by email - when that specification is released. 

I'm going to keep this ticket open until that new version of the specification is released.

**Comment by hughfdjackson** [comment]
Hi All - for all other questions, as I've commented on prior issues responded to today - please open a separate issue for anything you'd like to be addressed. 

If there is already an issue that describes the problem you're facing or the query you have, please add your voice or your :+1: to that.

**Comment by MayaCKS** [comment]
I also use Delphi so will more than likely run into the same problem as well.

I see the API notes are saying to “just leave the header out” so it looks like we can just omit the entire thing now instead of passing in ‘’?

Not sure how we test if our headers are suitable or not..

**Comment by hughfdjackson** [comment]
Hi @MayaCKS - hopefully the update we'll provide with an alternative empty value will help with your situation also. 

However, I do not see anywhere in the spec where we say "just leave the header out".  The only time a header may be absent (according to the spec) is if the header is not required for your connection method.  This is true as per version 2.1.

**Comment by hughfdjackson** [comment]
Hi @KenRandall  - while I appreciate the comment, since it's not specifically related to the original post (as far as I can tell) in this issue, could you raise a separate issue about that concern?

**Comment by mathiasbanda** [comment]
If you've got the application working with or without these fraud prevention headers well done. The application will not suddenly stop working while this area is still work in progress on both sides. Relax. Do what needs doing now. Lets get to the bridge first.

**Comment by Chrissi223** [comment]
The issue for most software suppliers is that HMRC's side is a work in progress and we need to release a product to our customers which is stable.  We can't wait any longer for the final solution and also can't risk having to ship a patch release this side of April either (costly and time consuming when we'll all have moved on to new projects).  HMRC need to understand that software suppliers (even those with cloud based products) have deadlines and in the main will not be releasing an update that solely contains MTD, our own also contains Payroll changes (one of which, disguised remuneration, is needed for the final pay period of this tax year - another very late notification of change from HMRC).  This means we have to sign off our software in the next few days and we can't because of the MTD question.

**Comment by Yottskry** [comment]
> 
> 
> If you've got the application working with or without these fraud prevention headers well done. The application will not suddenly stop working while this area is still work in progress on both sides. Relax. Do what needs doing now. Lets get to the bridge first.

You miss the point. These headers should have been finalised **months** ago and guidance issued accordingly. It's currently February with this going live in April. Software developers, like us, are **right up to the deadline** for getting changes tested thoroughly before releasing. 

If you're an HMRC developer than your comment is patronising, unhelpful and shows how thoroughly out of touch you are with both the development process and the developer community.

**Comment by Yottskry** [comment]
> 
> 
> The issue for most software suppliers is that HMRC's side is a work in progress and we need to release a product to our customers which is stable. We can't wait any longer for the final solution and also can't risk having to ship a patch release this side of April either (costly and time consuming when we'll all have moved on to new projects). HMRC need to understand that software suppliers (even those with cloud based products) have deadlines and in the main will not be releasing an update that solely contains MTD, our own also contains Payroll changes (one of which, disguised remuneration, is needed for the final pay period of this tax year - another very late notification of change from HMRC). This means we have to sign off our software in the next few days and we can't because of the MTD question.

We're in exactly the same situation, Chris. We also have Disguised Remuneration and all the other statutory changes to develop, test and release. It's reassuring to see we're not alone!

**Comment by mathiasbanda** [comment]
The truth is headers are still work in progress. Pardon my ignorance but I am not expecting things to change overnight. You are welcome to wait if you want. I real life you just do the best with what you've got.  If you find that offensive then my apologies.

**Comment by Yottskry** [comment]
> 
> 
> The truth is headers are still work in progress. Pardon my ignorance but I am not expecting things to change overnight. You are welcome to wait if you want. I real life you just do the best with what you've got. If you find that offensive then my apologies.

It's not offensive, it just shows a complete ignorance for the software development process. We have hundreds of customers. We can't simply wait for HMRC to get its act in gear and then issue a patch - that's hugely inconvenient for our customers and our support staff.

I have implemented what I can with the headers and we will have to release shortly. What I don't want is the situation that in June or July HMRC finally decide on the shape of these headers and we have to issue a patch to 400+ customers.

And the **truth** is that the headers **shouldn't be a work in progress**. They should have been finalised MONTHS ago, specifications issued, and testing should be available in the sandbox.

**Comment by mathiasbanda** [comment]
Pardon my ignorance but I don't expect a responsible HMRC to deliberately shift the goal post knowing full well it would break deployed applications. What's the sense in that?

**Comment by Yottskry** [comment]
> 
> 
> Pardon my ignorance but I don't expect a responsible HMRC to deliberately shift the goal post knowing full well it would break deployed applications. What's the sense in that?

There's no sense in that. As I've said at least twice now, the issue is that these headers **should have been finalised months ago**. They shouldn't be messing around this close to April *still* trying to decide what format they should take and still making changes.

**Comment by konradwudkowski** [comment]
hi @Yottskry, thank you for the feedback about inability to provide empty headers. The spec has been updated on 12th Feb and now if you cannot provide the required values you can submit the header with an empty value (as before) or omit it entirely (new). This applies to all headers where empty value was previously required and is explicit in the spec.

Later this week we'll close this issue if there are no additional comments

**Comment by sonicmule** [comment]
Our software runs as a desktop app and we are being asked to collect information such as user name, network ip addresses, mac addresses etc.  Should we inform our customers that we are collecting information from their computer system and passing on to a third party?  Could we be breaching any GDPR rules here?

**Comment by GrahamHDawson** [comment]
Good question !
Normally such a message would have an opt out button.
But the Anti-Fraud headers will be mandatory - so do we submit without the headers and wait for HMRC to contact the software vendor asking why the headers were not included or what.
Will 'user refused permission to submit the requested information' be a valid excuse?

**Comment by hughfdjackson** [comment]
Hi @sonicmule - I understand your concern, but I don't think this question is on-topic for this issue.  Could you open an issue specifically for those questions?

**Comment by konradwudkowski** [comment]
We will be closing this issue now as the problem of not being able to submit empty headers has hopefully been resolved.
