### ISSUE TITLE
Sandbox problems?

### ISSUE THREAD

**Issue by AndyYouens** [hmrc/vat-api#394]
Anyone having problems connecting to the sandbox test today?

Was all working fine up to yesterday, now getting a bad request error when attempting to create a new user via the API.

It gets the token correctly, then fails on the callback.

The log shows the following:
We need to request token - redirecting
Authorization URI details: https://test-api.service.hmrc.gov.uk/oauth/authorize?response_type=code&client_id=vXZJCWxKAlnm_oPjW3WgLOfM31Qa&redirect_uri=https%3A%2F%2Fgalatea%3A1234%2Foauth20%2Fcallback&scope=read%3Avat
2019-01-17 11:46:23 info [open.js]: -> Into Callback ...
2019-01-17 11:46:23 info [open.js]: Callback Options: {"redirect_uri":"https://galatea:1234/oauth20/callback","code":"25b1400f0dd74082b2b468068cdc6ffc"}
(node:18472) UnhandledPromiseRejectionWarning: Error: Response Error: 400 Bad Request

Any help appreciated.
Cheers

**Comment by AndyYouens** [comment]
Do you have a status page for the sandbox?

**Comment by GrahamHDawson** [comment]
Just created a test user, authorised, retrieved obligations and submitted a return without problems - so all seems to be working as it should.

Is your problem with the creation of a test user, or with the authorisation process?

**Comment by AndyYouens** [comment]
Getting the same 400 bad request for both a new user & retrieve obligations.  All working fine up to yesterday :-(

**Comment by AndyYouens** [comment]
We noticed yesterday when creating a new user it now asks for a HMRC user & password. Has this changed your end?

**Comment by GrahamHDawson** [comment]
No creating a new test user hasn't changed for us.
Are you using the create test user API ie this

https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/api-platform-test-user/1.0

Using the url that ends with /create-test-user/organisations and with your ServerToken in the header

'Authorization: Bearer ' & glo:serverToken)

Graham

**Comment by AndyYouens** [comment]
Yes have been using the create test user API for the past month. 

Its not getting as far as the url you stated above. it fails in the oauth2 when trying to get the auth token. Its strange it now prompts for a test user Id & password to generate a new user??  This wasnt happening prior to yesterday.

**Comment by jacobbrownlow** [comment]
Hi

We had an issue raised yesterday for a similar issue, but whenever we run the test suite we have for Sandbox, the tests pass successfully.

I can confirm there's no current issue with Create Test User or the Sandbox environment.

I am not aware of any status page for environment issues sorry.

Regards, Jacob

**Comment by AndyYouens** [comment]
What was the issue yesterday?

Has this been resolved?

What is the ticket number of that problem?

**Comment by jacobbrownlow** [comment]
Hi Andy

It wasn't exactly the same sorry, just re-read it. It was your own issue that I was referring to https://github.com/hmrc/vat-api/issues/390

**Comment by AndyYouens** [comment]
Hi there

After spending over a day on this, I re-wrote the get test user API calling program.  it still fails with the same error above. (404 Bad request)

When calling my script it prompts me for a test user ID & password - this has only happened in the last day.
https://test-www.tax.service.gov.uk/oauth/start?auth_id=5c40a7792600000d00b92087 
Authority to interact with HMRC on your behalf
f_MTD VAT needs permission to interact with HMRC on your behalf. To grant this authority, you'll need to: 
Sign in to your Government Gateway account.
Enter the 6 digit access code we'll send to your mobile phone, landline or other device.
You might need to confirm who you are by answering some security questions on, for example, your passport, P60 or other documents.
Grant authority for this software to interact with HMRC on your behalf.
This authority will last for 18 months. You can remove this authority at any time.
If you’re an agent
To use the Making Tax Digital APIs, sign in with the user ID and password for your agent services account.
To use the APIs that pre-populate a Self Assessment return, sign in with the account that’s enrolled for Self Assessment for Agents - it’s the same account you use to access the HMRC agent portal.
Continue

Pressing continue directs to https://test-www.tax.service.gov.uk/api-test-login/sign-in?continue=%2Foauth%2Fgrantscope%3Fauth_id%3D5c40a7792600000d00b92087&origin=oauth-frontend 

Sign in
Enter your Test User credentials to sign in.
User ID  
Password  
Sign in

Why?? I havent got a user yet??

Any help appreciated.
Cheers.

**Comment by GrahamHDawson** [comment]
Hi Andy,

You get a test user first (which returns the UserID and UserPassword) - does **that** bit work for you?

**Comment by AndyYouens** [comment]
No, it asks for the user id & password

**Comment by jacobbrownlow** [comment]
Hi Andy

The first step of creating a test user is hitting the Create Test User API

For organisations you should get back:
```json
{
    "userId": "572179374931",
    "password": "ZzgdyzMHgixr",
    "userFullName": "Dale Owen",
    "emailAddress": "dale.owen@example.com",
    "organisationDetails": {
        "name": "Company 1ZRW6N",
        "address": {
            "line1": "48 Virgil Street",
            "line2": "Grantham",
            "postcode": "TS16 1PA"
        }
    },
    "vrn": "666400427"
}
```

**Comment by AndyYouens** [comment]
thanks Jacob

Yes I realise what I should be getting back. the create test user API has been working here fine for the past month. its only in the last couple of days I'm getting back a 404 bad request error from you.  there have been no changes to the code here.

**Comment by jacobbrownlow** [comment]
Andy

My first step would be to use the Create Test User API
![image](https://user-images.githubusercontent.com/35334115/51376765-0982e000-1b01-11e9-8e99-31fa30a03166.png)

My second step would be to hit the grant authority URL
e.g. https://test-api.service.hmrc.gov.uk/oauth/authorize?response_type=code&client_id=CLIENTID&scope=read:vat+write:vat&redirect_uri=http://localhost:9000
![image](https://user-images.githubusercontent.com/35334115/51376655-c0329080-1b00-11e9-8c52-ca42c30428ed.png)

This takes you to the login screen where you need to use the creds from Create Test User response
![image](https://user-images.githubusercontent.com/35334115/51376739-fb34c400-1b00-11e9-8d83-7d8c49b7b529.png)

This is working for me 
![image](https://user-images.githubusercontent.com/35334115/51376829-3636f780-1b01-11e9-9c8a-166e5bb70581.png)

**Comment by AndyYouens** [comment]
hi Jacob

I cannot get to the new user details as I get a 404-bad request when getting the oauth token :-(

**Comment by AndyYouens** [comment]
Hi Jon

Trying Postman now.

Quick question does our server token ever expire for our application?
