### ISSUE TITLE
Creating Test User Fail

### ISSUE THREAD

**Issue by MrACP** [hmrc/vat-api#397]
I have already wasted some time finding that test users created via the https://developer.service.hmrc.gov.uk/api-test-user page don't work for MTD.  So I'm trying to create a user via the API, but get a 404 error MATCHING_RESOURCE_NOT_FOUND.

I also get the same response entering https://test-api.service.hmrc.gov.uk/create-test-user/organisations in a browser.  Has this API been removed?  Or am I doing something wrong?

**Comment by jacobbrownlow** [comment]
Hi 

Sorry about the frontend GUI not working for mtd-vat. This has been raised and we are pushing for a resolution from the team who owns the service.

The API is working https://test-api.service.hmrc.gov.uk/create-test-user/organisations
![image](https://user-images.githubusercontent.com/35334115/51331431-a6963800-1a71-11e9-9df2-ac28b9e0f24a.png)

**Comment by jacobbrownlow** [comment]
Headers required:
<img width="1042" alt="screenshot 2019-01-17 at 16 06 29" src="https://user-images.githubusercontent.com/35334115/51331776-5e2b4a00-1a72-11e9-898c-cd6e1a6ebe71.png">

**Comment by MrACP** [comment]
Yes, it's working now, thank you.  Was using a GET not a POST
