### ISSUE TITLE
Testing in the production environment

### ISSUE THREAD

**Issue by Yottskry** [hmrc/vat-api#402]
Is there any facility to test the production environment? Other posts I've seen suggest not, but if this is the case it's really not acceptable. How are we supposed to guarantee to our customers that our software works as expected if we can't test it until it reaches them and they try to use it?

I'm sure the response will be that if the sandbox works, the test environment will work too, and yet we've already seen there are some discrepencies between the two environments, even if they're as subtle as different character cases in the JSON response text.

I'm sorry to say it, but I think HMRC are making a complete pig's ear of this entire exercise. There has been too little consultation with software providers, too few answers to questions, and too short a timescale for implementation given the last changes to their ridiculous fraud prevention headers only hit us in December.

**Comment by GrahamHDawson** [comment]
As I understand it there is no testing using the production URL.
Basically Authorising the end-user and calling the Obligations endpoint successfully is the only way you'll know it's working.

**Comment by jonathanleather** [comment]
Hi @Yottskry 

We understand your frustration but unfortunately there is no facility to test in production. This is a HMRC decision, not one made by the API team.
For your first production submission, SDST do offer a "handholding" exercise, where the relevant teams will be available to support you in case you hit any issues. (This must be organised by contacting SDST.)

If you have any issues or questions related to the VAT-API, please do contact us on here so we can support you. This also applies if you encounter any differences in the API between sandbox and production.

For items such as the Fraud Prevention Headers or issues not related to the API themselves, please contact SDST so they can put you in touch with the relevant team.

I will pass your comments on to the wider programme to highlight the current pain points for vendors.

Software Developers Support Team: SDSTeam@hmrc.gsi.gov.uk.

Cheers
Jon

**Comment by daniel-andrews1994** [comment]
Hi @Yottskry 

I am sorry that you are having trouble with contacting SDST for answers regarding your issue. I will contact their team to let them know that there are vendors who are not receiving the support which they require.

Thanks,
Daniel

**Comment by Yottskry** [comment]
> 
> 
> Hi @Yottskry
> 
> We have spoken to SDST for you.
> They are extremely busy at the moment but if you send through an email to them with the following subject "github – Fraud Prevention Headers", they will look into it as quick as they can.
> 
> Cheers
> Jon

Thanks Jon. Much appreciated.

**Comment by JeeBeePee** [comment]
A better solution would be for the sandbox to contain some data that vaguely resembles production.
