### ISSUE TITLE
Going live with software using the VAT API

### ISSUE THREAD

**Issue by scottlarge** [hmrc/vat-api#408]
The test scenarios are great and useful but can anyone confirm how the API responds when used in production? For example, without the test scenario header, the obligations always return the same response in sandbox. It is difficult to go live with an API that hasn't been tested without test scenario headers and see how it reacts in a live scenario.

EDIT:

Also, does anyone know if it is possible to run a test in production without trying to use real user details?

**Comment by MeliaDavies** [comment]
@scottlarge 

Please could you explain what the issue is?

Thanks

**Comment by scottlarge** [comment]
@MeliaDavies sorry submitted before updating the question
