### ISSUE TITLE
HMRC - Retrieve Obligations

### ISSUE THREAD

**Issue by MichelleDowden** [hmrc/vat-api#410]
**Note: Please read before raising an issue**. This repository's issues are reserved for **Technical** queries relating to the VAT-API Only. 
If your issue falls into any of the below categories please contact SDST at SDSTeam@hmrc.gsi.gov.uk:
- Issues relating to subscribing/registering to use the API Platform, MTD enrolment / de enrolment  / registration for VAT / BETA etc
- Issues relating to OAuth2
- Issues relating to integrating with the API Platform (setting up an application/access)
- Vendor application software questions (code examples in .NET / VB6 etc.)
- Business related questions
- Scheduled maintenance days / windows
- Onboarding 
- Performance metrics
- Questions relating to the process pre MTD

When submitting an issue please try to provide the following information:

* **I'm submitting a ...**
  - [ ] Bug - API
  - [ ] Bug - Documentation
  - [ ] Improvement
  - [ ] Feature request
  - [ ] Support request

* **What is the current behaviour?**

* **What is the expected behaviour?**

* **Other information** (e.g. detailed explanation, screenshots, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Find answers to common questions [here](https://github.com/hmrc/vat-api/wiki/FAQ)

**Comment by MeliaDavies** [comment]
@MichelleDowden 

Please could you explain the issue you're having?

Thanks

**Comment by MichelleDowden** [comment]
Hi,

I have some questions actually. Please let me know if I should post elsewhere. 

I am currently developing software to run inside SAP Business One to allow companies to submit tax digitally. Organizations will be submitting tax directly, not through an agent, with this software. 

Will company users need to create a Government Gateway account to get Client Id, Server Token, Redirect Uri etc. for live the same way we have on the developer hub? 

The user that was created didn’t work when testing the API and we were required to create a user in code. I assume that won’t be the case in live? 

When you retrieve open obligations only with a date range is an array of open obligations returned in live? How can we determine which is the next obligation? What is the response when there is no open obligation for the date range submitted?

Is there a link to documentation describing what a user is required to do that we can provide in our solution for first time users?

What is the process if we want to test in live?

Thanks,
Michelle

**Comment by Yottskry** [comment]
@MeliaDavies the problem with emailing SDSTeam@hmrc.gsi.gov.uk is that **we don't get a reply**. I have asked them the same question regarding headers on three occasions over the past month and I've not yet had a single reply. It's a joke and completely unprofessional.

**Comment by MarkAKelly** [comment]
Hi @MichelleDowden,

Lets see if we can get a couple of these answered for you.

**Will company users need to create a Government Gateway account to get Client Id, Server Token, Redirect Uri etc. for live the same way we have on the developer hub?**

Client ID, redirect URI, server token are all application credentials created when registered in the developer hub.  It is your application which interacts with the API and not the user.

**The user that was created didn’t work when testing the API and we were required to create a user in code. I assume that won’t be the case in live?**

We might need a bit more information on what you mean here.  The create test user API that we surface for the Sandbox environment should give you the test data needed to test against the API.  In live you would use the credentials of the organisation that is using your software.

**When you retrieve open obligations only with a date range is an array of open obligations returned in live?**

If you call the Retrieve Obligations endpoint with just a date range, it will return all 'open' and 'fulfilled' obligations that lie in that date range.  If you call it with the status parameter set to 'O', then you will receive only open obligations.

**How can we determine which is the next obligation?**

I assume when you say next obligation you mean the most recent? In this case it will always be the one with the most recent date. Obligations aren't created until the first day of the next obligation period, so there won't be X many spanning into the future. 

**What is the response when there is no open obligation for the date range submitted?**

As no data will be returned, the API returns a 404 with the NOT_FOUND error code.  This is testable using the Test Scenario headers we provide in the sandbox environment.

**Is there a link to documentation describing what a user is required to do that we can provide in our solution for first time users?**

Other than the MTD guide (which is designed for you as vendors) found [here](https://developer.service.hmrc.gov.uk/api-documentation/docs/mtd), there is nothing that we as the API producers give out to end users about what they need to do.  If you need any more information on the VAT MTD process then we can look at finding a few things for you.

**What is the process if we want to test in live?**
HMRC Digital as a platform have indicated that they do not offer a test in live service - that is they will not be making data available that is not 'real' customer data for test purposes.  Many of our vendors have had assistance on their first interaction with the live environment, and if you feel this would be helpful then this can be arranged by contacting the SDS Team ([SDSTeam@hmrc.gsi.gov.uk](mailto:SDSTeam@hmrc.gsi.gov.uk))
