### ISSUE TITLE
Submit VAT Return - TAX_PERIOD_NOT_ENDED

### ISSUE THREAD

**Issue by GrahamHDawson** [hmrc/vat-api#414]
It appears the Submit VAT Return endpoint has a new check and returns an error if the return period has not ended TAX_PERIOD_NOT_ENDED
A new scenario TAX_PERIOD_NOT_ENDED has also been added.

How does this work?

I always assumed that the Obligations endpoint would only return Open Obligations that are ready for submission ie the VAT period has ended and the submission can be made.

It appears from the new return error and testing scenario that this is **not** the case and that users will see Obligations before they can submit them.

A secondary point here is that other than continually monitoring the API Code section change log and the documentation there's no way for developers to know when changes like the above happen.
This is really not **good** (I'm trying to be polite here and understating my annoyance).

At a minimum the documentation should have an extra line under the 'Version and Status' - say 'Last Updated' giving the date and time so we know at a glance that somethings changed without having to examine the whole page.

**Comment by adamdavi3s** [comment]
Graham- I was working on the assumption that all obligations would be returned for the date range chosen so this is good for us

However I do completely agree with your comments regarding the API changes

**Comment by london-coder** [comment]
Hi Graham,
Thanks for your post. 
I can appreciate you find it irritating that the software, business rules and their implementations are evolving. The changes were indicated in the HMRC Developer Hub -> Documentation -> API documentation -> VAT (Making Tax Digital) -> VAT (MTD) -> Endpoints -> Submit VAT return for period
It is neither ideal, nor entirely unexpected that "Beta" versions of software might evolve. As the API team are primarily responsible for implementation of stated need; your enquiry will probably be more satisfactorily answered by the SDST Team, whose email is: SDSTeam@hmrc.gsi.gov.uk
You suggestion for improvement to the documentation is welcome, and we'll look into providing more assistance in that regard.
