### ISSUE TITLE
Production Retrieve Liabilities

### ISSUE THREAD

**Issue by KenRandall** [hmrc/vat-api#415]
When there are no liabilities a response status code of 404 is returned. Is 404 only used in this instance so that I can interpret this properly?

It would be much better to return a atatus of 200 with an empty array!

Ken

**Comment by jonathanleather** [comment]
Hi @KenRandall 

We are aware of this as you as not the first person to request this change. Unfortunately changing this now would be deemed a breaking change. This is unlikely to change in version 1 of the API but I will pass your comments onto the project if / when version 2 makes and appearance. 

Thanks for raising.
Cheers
Jon
