### ISSUE TITLE
Production Retrieve VAT Obligations

### ISSUE THREAD

**Issue by KenRandall** [hmrc/vat-api#416]
Even if a States of 'O' for open obligatins is included both open and fulfilled obligations are returned.

Ken

**Comment by GrahamHDawson** [comment]
The testing url ignores the status 'O' or 'F' parameters - it always returns all obligations.

**Comment by GrahamHDawson** [comment]
Re-reading your issue, are you saying that the 'live' url ignores the 'O' and 'F' status as well?

**Comment by KenRandall** [comment]
Yes, I am talking about the live system. It ignores the 'O' status.

**Comment by MarkAKelly** [comment]
Hi @KenRandall,

Can you give us some more information around this please?  What date and at what time were these requests made?

We have not received any other issues regarding filtering of Open or Fufilled obligations for any other users in the live environment.  As Graham has mentioned the obligations resource in the sandbox environment will return all obligations. 

Cheers,
Mark

**Comment by KenRandall** [comment]
I'm not using the sandbox. It was on Saturday at about 2pm however I cannot replicate it now. It was with a company that had only just signed up for MTD. But now if I set from to as '2018-01-01' and to as '2018-12-31' and status as 'F' I get nothing returned.

Ken

**Comment by GrahamHDawson** [comment]
Hi Mark,

Am I correct in saying that if we have issues with the live environment and give you the CorrellationID then you can trace the 'conversation' ?

**Comment by MarkAKelly** [comment]
That is correct.  If you have a X-CorrelationID then we can track it through our API and into the downstream systems.

**Comment by jonathanleather** [comment]
@KenRandall 

I'll close this issue for now. If you experience the same issue again please raise a new issue providing the correlation ID or as many details as possible so we can trace the request and investigate for you.

Cheers
Jon
