### ISSUE TITLE
What to POST when exchanging token

### ISSUE THREAD

**Issue by shaunl23** [hmrc/vat-api#418]
Hi,
I have my own system that is in VB.NET.
I'm trying to keep the system and make it MTD compliant.
I'm new to json and the APIs but I have managed to get an oauth token.
I'm struggling with exchanging the token (the 2nd step).

` Try
            Dim request As HttpWebRequest =
      HttpWebRequest.Create(New Uri("https://test-api.service.hmrc.gov.uk/oauth/token"))
            request.Credentials = CredentialCache.DefaultCredentials
            'Dim para As String = "{" & Chr(13) & """client_secret"":""" & clientSecret & """" & Chr(13) & """client_id"":" & """" & clientID & """" & Chr(13) & """grant_type"":""authorization_code""" & Chr(13) & """redirect_uri"":" & """" & redirectURI & """" & Chr(13) & """code"":" & """" & MTD_FRM.txtTOKEN.Text & """" & Chr(13) & "}"
            Dim para As String = "client_secret=" & clientSecret & "&client_id=" & clientID & "&grant_type=authorization_code&redirect_uri=" & redirectURI & "&code=" & MTD_FRM.txtTOKEN.Text
              
            Dim buf = Encoding.UTF8.GetBytes(para)
            MsgBox(request.RequestUri.OriginalString)
            MTD_FRM.TextBox1.Text = ((request.RequestUri.OriginalString))
            request.Method = "POST"
            request.AllowAutoRedirect = True
            request.ContentLength = para.Length

            Dim writer As New StreamWriter(request.GetRequestStream)

            Using writer
                writer.Write(para)
            End Using

           
            Dim response As WebResponse = request.GetResponse()
            ' Display the status.
            MsgBox(CType(response, HttpWebResponse).StatusDescription)
            ' Get the stream containing content returned by the server.
            Dim dataStream As Stream = response.GetResponseStream()

            ' Open the stream using a StreamReader for easy access.

            Dim reader As New StreamReader(dataStream)
            ' Read the content.
            Dim responseFromServer As String = reader.ReadToEnd()
            ' Display the content.
            MsgBox(responseFromServer)
            MTD_FRM.TextBox1.Text = responseFromServer.ToString

            ' Clean up the streams and the response.
            reader.Close()
            response.Close()

        Catch EX As Exception
            MsgBox(EX.Message)
        End Try`

I have tried 2 different data to write:
One as code=###&uri=###
and the other in json format 
Both are in my code, but I switch between them by commenting one out
I've also tried converting the strings to bytes before writing

I keep getting a 400 response and I cannot figure out why.

Could someone please clarify what data to write and what format it needs to be in?

Thanks

**Comment by ShoLongBruce** [comment]
How did you authorise your user? did you use an embedded webbrowser, if so try authorising in a seperate browser and use that authorisation code instead. I had a similar problem you 
https://github.com/hmrc/vat-api/issues/347
When I used a separate web browser, it all works.

**Comment by shaunl23** [comment]
Hi ShoLongBruce,

I saw your similar issue when I was searching for an answer. I do have an embedded browser, but I got it working now by using your text encoding method rather than the one I used.
I'm not sure what was wrong with it, but it all works now :)

Thanks for responding, and so quickly, the help is appreciated

**Comment by CiprianSavoiu** [comment]
I'm having the same problem with the redirect_uri.
I'm able to retrieve the auth code (where the redirect _uri works) but when trying to get the token I'm getting invalid Uri error

**Comment by mtd-api-team** [comment]
Hi @CiprianSavoiu 

Our own guidance on creating test users is available here:
https://github.com/hmrc/vat-api/wiki/Creating-Test-Users-in-the-Sandbox
See step 3.

Here's an example in Postman:
<img width="556" alt="Screenshot 2020-03-11 at 10 10 32" src="https://user-images.githubusercontent.com/49438676/76405872-be6d0180-6380-11ea-805b-ef2866cf4a52.png">

Hope this helps, if you are still struggling with Auth related issues please contact the Software Developers Support Team at SDSTeam@hmrc.gov.uk

Regards

**Comment by CiprianSavoiu** [comment]
thank you for the quick answer.
I found out what I was doing wrong :)
For others reference:
1. when requesting access code the redirect_uri should be percent-encoded : http%3A%2F%2Flocalhost%3A3017%2F
2. when requesting token the redirect_uri should be in normal format: http://localhost:3017/

**Comment by CiprianSavoiu** [comment]
sadly it worked once and now getting back the same error "error_description": "redirect_uri is invalid"

**Comment by CiprianSavoiu** [comment]
![image](https://user-images.githubusercontent.com/20278263/76408319-aeefb780-6384-11ea-8195-4eb94d2e5d95.png)

**Comment by CiprianSavoiu** [comment]
![image](https://user-images.githubusercontent.com/20278263/76408380-c6c73b80-6384-11ea-8d5f-18ffcf0d2fc8.png)
