### ISSUE TITLE
Header Value (Gov-Test-Scenario)

### ISSUE THREAD

**Issue by kontrasenyas** [hmrc/vat-api#419]
Can anyone enlighten me with what is **Header Value (Gov-Test-Scenario)** under  Retrieve VAT liabilities or Retrieve VAT payments? I know that this header can retrieve the data from the sandbox environment, but do I need to put this header in production environment or what is the equivalent header for this in production environment? 
 
The problem is, if this is only for test environment my code will behave differently in production environment if this header is not needed anymore in production.

If I remove this header in my test environment, how can I assure that my code works in production? 

Do you have an environment that is similar to the production environment to test if our code works?

Thank you.

Header Value (Gov-Test-Scenario) | Scenario

SINGLE_LIABILITY | Returns a single valid liability when used with dates from 2017-01-02 and to 2017-02-02.
MULTIPLE_LIABILITIES | Returns multiple valid liabilities when used with dates from 2017-04-05 and to 2017-12-21.

**Comment by jacobbrownlow** [comment]
Hi @kontrasenyas 

The optional header **Gov-Test-Scenario** is for testing only, and is only used in the Sandbox. 

The Sandbox environment is for integration testing, so the purpose of the headers is to simulate a response from backend systems. This enables you to test connectivity with our vat-api and also ensure you are able to process the various responses and errors that are returned.

I would suggest that your tests are configured to add the additional header values, whilst the Production code shouldn't use them.

Unfortunately there is no Production like testing environment.

Regards, Jacob

**Comment by ArcComing2021** [comment]
Under '' Retrieve obligations'' should all the Gov-Test-Scenario be tested? How do you select which scenario to test ? Do you test based on your stagger groups ? Thank you!

**Comment by ArcComing2021** [comment]
How do use those  Gov-Test-Scenario to test whether your application is working correctly?
