### ISSUE TITLE
Error 503 Submitting VAT Return

### ISSUE THREAD

**Issue by Andy-Meikle** [hmrc/vat-api#420]
Hi, I've getting a 503 error when trying to submit a VAT return through Postman, here's a log of the raw request and response (vrn and access token values removed):

POST
https://test-api.service.hmrc.gov.uk/organisations/vat/{vrn}/returns

**Request Headers:**
Accept:"application/vnd.hmrc.1.0+json"
Content-Type:"application/x-www-form-urlencoded"
Authorization:"Bearer {access_token}"
Gov-Test-Scenario:"INVALID_VRN"
cache-control:"no-cache"
Postman-Token:"79f3ba3a-7148-403d-8c84-e7b50f7142f4"
User-Agent:"PostmanRuntime/7.6.0"
Host:"test-api.service.hmrc.gov.uk"
cookie:"mdtp=YIsy5mH/Ha+ZKoYaGIgOMTCpebb0mN/J0zY6negd/ZB4lyAJ0S+LSsYfIHq3hr8FE4wPIKiBdr6hYdEkvDbsMbxOARDlNc7nNcOc+UDsKcRcp3jpziCeTsS2y8We94i8vU8nK/fzSz5pbEK8cNf2XfkklZeXt1qhQdpdKSIUKBFLB+4rSu+UgA6SkfAKqIi/wtYpAIl58OaGgDW+RxM5rGWpng7ylGvWa8noiZIr4AE9P9g=; mdtpdi=mdtpdi#4bc42022-e9e6-4796-84ce-abe26ddbbcb3#1547573209368_gZEX8m5cMAyiP32XKazL+A=="
accept-encoding:"gzip, deflate"
content-length:255

**Request Body:**
periodKey:"A001"
vatDueSales:"105.50"
vatDueAcquisitions:"-100.45"
totalVatDue:"5.05"
vatReclaimedCurrPeriod:"105.15"
netVatDue:"100.10"
totalValueSalesExVAT:"300"
totalValuePurchasesExVAT:"300"
totalValueGoodsSuppliedExVAT:"3000"
totalAcquisitionsExVAT:"3000"
finalised:"true"

**Response Headers:**
Content-Type:"application/json"
Content-Length:"59"
Strict-Transport-Security:"max-age=31536000;"
Date:"Wed, 30 Jan 2019 15:27:20 GMT"
Connection:"close"

**Response Body:**
code:"SERVER_ERROR"
message:"Service unavailable"

No matter what Gov-Test-Scenario header I pass in (or if i don't pass it in at all) I get the same response after it hangs for around a minute.

**Comment by jacobbrownlow** [comment]
Hi Andy

You need to submit your body in `json` format

e.g.
Content-Type:"application/json"
```json
{
  "periodKey": "1AA1",
  "vatDueSales": 100.00,
  "vatDueAcquisitions": -100.00,
  "totalVatDue": 0,
  "vatReclaimedCurrPeriod": 100,
  "netVatDue": 100,
  "totalValueSalesExVAT": 100,
  "totalValuePurchasesExVAT": 100,
  "totalValueGoodsSuppliedExVAT": 1000,
  "totalAcquisitionsExVAT": 1000,
  "finalised": true
}
```

Also note that you don't need to use the invalid VRN header to cause this error. You can just manipulate the vrn to make it invalid e.g. `abc` and trigger the errors manually.

Regards, Jacob

**Comment by Andy-Meikle** [comment]
Hi Jason,

Thanks for getting back to me so quickly, and yes I've amended the format and its now working correctly. Noted about triggering errors manually too.

Cheers,
Andy.
