### ISSUE TITLE
Fraud prevention header specification – compliance support for 3rd party software development

### ISSUE THREAD

**Issue by SDST-HMRC** [hmrc/vat-api#423]
Dear Developer,

On 11th December we advised that we would let you know how we would work with you to ensure that your software is compliant to the requirement of the fraud prevention header specification, currently v2.1. 

We will help you to build and manage software that is compliant to the HMRC fraud prevention header specification, by: 
•	Providing support and guidance to your questions sent to sdsteam@hmrc.gsi.gov.uk or posted to GitHub https://github.com/hmrc/vat-api/issues .
•	Checking your software compliance. This will either be as a review before software production credentials are approved, or arranged with you if production credentials have already been granted.  
•	Conducting post production checks on live transactions from customers using your software and work with you to resolve any issues.

If you require any further information in respect of compliance support for the collection of fraud prevention headers, please contact the sdsteam@hmrc.gsi.gov.uk or post on GitHub https://github.com/hmrc/vat-api/issues 

Regards,

Dennis Dawkins
Software Developers Support Team 
HM Revenue & Customs 
Email: sdsteam@hmrc.gsi.gov.uk  
Website: www.gov.uk/topic/dealing-with-hmrc/software-development

**Comment by Yottskry** [comment]
@SDST-HMRC This is possibly the single most useless response you've yet given us. It answer none of the questions and is of no help to any of us. If HMRC is serious about wanting to cooperate with the development community you could start be actually answering the many, many questions about these stupid headers posted on this forum.

**Comment by adamdavi3s** [comment]
I absolutely second this and have made this request before.

We must have these in the sandbox

**Comment by markogrady** [comment]
+1

**Comment by KenRandall** [comment]
Yes, I too have raised this!

**Comment by Chrissi223** [comment]
Please give an indication of when this will be answered.  Emails were sent out from HMRC over a week ago indicating we'd have responses week commencing 25th Feb, but nothing so far.  This is preventing completion of software updates by a number of companies.  An update on when HMRC will reply to those waiting for answers is the least we should be able to expect.

**Comment by Chrissi223** [comment]
Still no indication of when we will have answers?  This is incredibly disappointing as we've always had a really fast response from the SDS team (RTI related queries, throughout the pilot and up to present day).  This is causing me a massive headache as I need to sign-off software for an imminent release but am unable to do so until we can prove MTD communications (we had sign-off from HMRC on our solution quite a while ago).  Please can HMRC give us a deadline for when we will receive the information we require (my colleague Yottskry, along with our Product Manager, has been in contact with the team regarding these issues since mid December and this is certainly beyond a joke.

**Comment by konradwudkowski** [comment]
hi @GrahamHDawson / @adamdavi3s we've responded to your questions under another github issue. I will repeat here for better visibility.

We are looking at the best solution for allowing you to test your header compliance. We will update here as soon as we know the details. If you have specific concerns about your header compliance please contact SDST and we will arrange a session to provide feedback on your header compliance.

We do not plan, immediately after April, to reject messages at API level for noncompliance with this requirement. But we expect all vendors to be compliant, and we will identify and work with any non-compliant vendors to ensure services are made compliant as quickly as possible. We will, later in the year, consider whether we will reject messages for noncompliance with the fraud prevention headers at API level.

**Comment by Yottskry** [comment]
> We do not plan, immediately after April, to reject messages at API level for noncompliance with this requirement. But we expect all vendors to be compliant, and we will identify and work with any non-compliant vendors to ensure services are made compliant as quickly as possible. We will, later in the year, consider whether we will reject messages for noncompliance with the fraud prevention headers at API level.

@konradwudkowski This is encouraging, Konrad. I have done my best to provide the header information as requested. The only circumstance that is holding us up is that we cannot send blank header values as none of the libraries available to us allows it. In most cases this won't be a problem as we can provide values for virtually all the headers apart from the multi factor authentication. Can I confirm, then, that if this header is *missing entirely* at present it won't prevent the submission of data in the near future?

Can I also confirm that if you decide to reject headers for non-compliance later in the year that this change will be publicised far in advance of it going live?

**Comment by SDST-HMRC** [comment]
Email below issued from SDST this morning to all registered MTD VAT developers to clarify position with regards to fraud prevention header compliance from April. To add the behaviour of Sandbox and Production environments are the same. HMRC  will advise ( by SDST email) before updating the Sandbox environment in advance of any change to enforce fraud prevention header requirement in the Production environment for MTD VAT messages. 

Dear Developer 

Further to our communication on 01 February 2019, some of you have asked us about our policy over non-compliance with this requirement from the 1st April 2019. We do not plan, immediately after April, to reject MTD VAT messages from software applications that are non-compliant with the requirement. However, we expect your software applications to be compliant, and we will identify and work with you as necessary to ensure your software applications are made compliant as quickly as possible. We will, later in the year (2019), consider whether we will reject MTD VAT messages for non-compliance with the fraud prevention headers at the point of receipt. 

Regards

Dennis Dawkins
Software Developers Support Team 
HM Revenue & Customs 
Email: sdsteam@hmrc.gsi.gov.uk 
Website: www.gov.uk/topic/dealing-with-hmrc/software-development

**Comment by konradwudkowski** [comment]
hi @Yottskry

Dennis Dawkins probably answered the question already above but to be explicit:

> Can I confirm, then, that if this header is _missing entirely_ at present it won't prevent the submission of data in the near future?

Yes - that is correct provided you've attempted to collect the data but were unable to for reasons given in the spec.

> Can I also confirm that if you decide to reject headers for non-compliance later in the year that this change will be publicised far in advance of it going live?

Yes - that is also correct

> The only circumstance that is holding us up is that we cannot send blank header values as none of the libraries available to us allows it.

The spec has been updated on 12th Feb and now if you cannot provide the required values you can submit the header with an empty value (as before) or omit the header entirely (new). 

https://developer.service.hmrc.gov.uk/api-documentation/docs/fraud-prevention

**Comment by Yottskry** [comment]
Thanks for the reply, Konrad. Yes, I've seen the new specification and it's much more helpful than the previous one as it solves our problem of empty headers. We're attempting to capture all the required data and should have no problem with most of it, but multi factor authentication will always be blank for us, so will now be omitted. As long as that doesn't cause a problem, we're good to go.

**Comment by Shivapalle** [comment]
Does HMRC support the the data encryption? Now that sensitive data will be transmitted to HMRC, data encryption is far more important to us.
