### ISSUE TITLE
Inconsistent processingDate format between production and sandbox VAT submission

### ISSUE THREAD

**Issue by Chris-Goddard** [hmrc/vat-api#424]
* **I'm submitting a ...**
  - [x] Bug - API
  - [ ] Bug - Documentation
  - [ ] Improvement
  - [ ] Feature request
  - [ ] Support request

* **What is the current behaviour?**
Submit VAT Return for period.
Sandbox returns processingDate in yyyy-MM-ddThh:mm:ss.SSSZ format.
Production returns processingDate in yyyy-MM-ddThh:mm:ssZ format (no milliseconds)

* **What is the expected behaviour?**
Sandbox ties in with documented example.

**Comment by jonathanleather** [comment]
Hi @Chris-Goddard 

Thanks for raising.
We will get this investigated for you.

Cheers
Jon

**Comment by MarkAKelly** [comment]
Hi @Chris-Goddard,

We have noticed that one of HMRC's backend systems has stopped returning the processingDate in the yyyy-MM-ddThh:mm:ss.SSSZ format in Production, and as such you are seeing the differing format between environments.

To prevent this from being an issue, we will be making a change to the VAT API in the next few days to ensure that it will always be returned in the format defined in our documentation - even if this may more often than not prepend 0 values in place of the milliseconds.  

Hope this helps, and if you have further comments or questions feel free to reopen this issue and we will get back to you.

Cheers,
Mark

**Comment by Chris-Goddard** [comment]
Hi @MarkAKelly 
Thanks for this.  You say you are making a change to the API in the next few days.  Does that mean you are making the code changes within the next few days or that the API change will be put live in Production in the next few days?  If the former, do you have an ETA when this will be available in Production?

Thanks

Chris

**Comment by MarkAKelly** [comment]
Hi @Chris-Goddard,

Good point - once the code changes are made they will be within Production within a few hours.  I'm hesitant to say exactly when, although its looking like it should be available before the end of our sprint on Tuesday, however we are aiming to get it in before the end of this week.  We will let you know through here when that fix is going in.

Cheers,

Mark

**Comment by Chris-Goddard** [comment]
Hi @MarkAKelly 

Can you reopen the issue, and then close it when the change is made to the production environment - the issue is not closed until the fix is available in Production.

Regards

Chris

**Comment by Chris-Goddard** [comment]
Hi @MarkAKelly 

Has this been resolved in Production yer?

Regards

Chris

**Comment by Chris-Goddard** [comment]
Hi @MarkAKelly, @jonathanleather 

Has this been resolved in Production yer?

Regards

Chris

**Comment by jonathanleather** [comment]
Hey @Chris-Goddard 

Apologies, we have been dealing with a few environmental issues which delayed the deployment. 
I can confirm that this change is now in production. 

If you have any more issues please do come back to us.

Cheers
Jon
