### ISSUE TITLE
Refunds not appearing in Payments

### ISSUE THREAD

**Issue by KenRandall** [hmrc/vat-api#425]
When submitting an issue please try to provide the following information:

* **I'm submitting a ...**
  - [ x] Improvement
  - [ x] Feature request

* **What is the current behaviour?**
They do not appear in the production system.

* **What is the expected behaviour?**
They should appear.

Regards,

Ken

**Comment by ma3574** [comment]
Hi @KenRandall 

Could you please supply us with some requests/responses along with what you expect to come back. As the requests/responses contain sensitive data, can you please email the SDS Team at SDSTeam@hmrc.gsi.gov.uk and reference this issue (https://github.com/hmrc/vat-api/issues/425) in your email. They will pass on the data to us and it will allow us to investigate it and get back to you. 

Kind regards
Muhammed
