### ISSUE TITLE
Anti-Fraud Headers - when will these be testable in the sandbox environment

### ISSUE THREAD

**Issue by GrahamHDawson** [hmrc/vat-api#426]
* **I'm submitting a ...**
  - [x] Improvement
  - [x] Feature request

Currently the anti-fraud headers don't seem to be checked in the sandbox.
When will this be available along with documentation detailing the responses that we'll receive when submitted anti-fraud headers and missing or invalid.

**Comment by konradwudkowski** [comment]
hi @GrahamHDawson We are looking at the best solution for allowing you to test your header compliance. We will update here as soon as we know the details.

We do not plan, immediately after April, to reject messages at API level for noncompliance with this requirement. But we expect all vendors to be compliant, and we will identify and work with any noncompliant vendors to ensure services are made compliant as quickly as possible. We will, later in the year, consider whether we will reject messages for noncompliance with the fraud prevention headers at API level.
