### ISSUE TITLE
Sandbox Fraud prevention Headers

### ISSUE THREAD

**Issue by adamdavi3s** [hmrc/vat-api#428]
* **I'm submitting a ...**
  - [ ] Bug - API
  - [ ] Bug - Documentation
  - [ ] Improvement
  - [ X] Feature request
  - [ ] Support request

* **What is the current behaviour?**
Sandbox doesn't check headers

* **What is the expected behaviour?**
Implementing the fraud headers is a breaking change and developers need a proper way of testing their applications are compatible

**Comment by shaunl23** [comment]
I'm also very keen to test my application with the fraud headers included

**Comment by konradwudkowski** [comment]
Hi @adamdavi3s / @shaunl23 thank you for telling us that tools to verify the headers is needed. We are looking at the best solution for allowing you to test your header compliance. We will update here as soon as we know the details.

We do not plan, immediately after April, to reject messages at API level for noncompliance with this requirement. But we expect all vendors to be compliant, and we will identify and work with any noncompliant vendors to ensure services are made compliant as quickly as possible. We will, later in the year, consider whether we will reject messages for noncompliance with the fraud prevention headers at API level.

**Comment by konradwudkowski** [comment]
Closing the issue for now
