### ISSUE TITLE
Productions System: Can not access the required resource, Ensure this token has all the required scopes.

### ISSUE THREAD

**Issue by markogrady** [hmrc/vat-api#431]
I have contacted SDS and they weren't sure, so I thought I would post the issue here to see if anyone else has had it.

I have now sent plenty of live VAT returns without a problem. Although from last Friday a number of users received the error "Can not access the required resource, Ensure this token has all the required scopes."
They had Granted access weeks beforehand and after granting access again it has worked. I track the scopes and they had all asked for read-write permissions.

It looks to me like something was deployed at that time and the existing tokens lost their scope to submit.

Has anyone had a similar issue? I want to try and track this down because I have lots of users submitting very soon and I want to see whether it is something my end.

**Comment by london-coder** [comment]
Hi @markogrady,

Thank you for raising this issue. We will look into this, to understand the cause and find a solution. If it is an authentication problem, we may need to pass the enquiry on to a different team for a definitive solution. If you could provide a VRN for which this error occurred, it may make it easier to trace through the logs to aid with the investigation. Please do not post any identifiable information here. Instead, please email SDST, [SDSTeam@hmrc.gsi.gov.uk] and they will pass the information on to us, to scan the logs.

**Comment by markogrady** [comment]
I have sent the mail to SDS. I havent had the issue since.
