### ISSUE TITLE
Redirect URLs

### ISSUE THREAD

**Issue by njacobs-winman** [hmrc/vat-api#434]
Can anybody help here? I'm trying to find a solution when authorizing the user for VAT.

We have a web-based software solution. We host it for our customers. Each customer has a completely separate instance from the other hosted on a unique URL.
So 
Company1.mycloudapp.cloud
Company2.mycloudapp.cloud
Company3.mycloudapp.cloud
Etc. etc.

Each will, therefore, need to have its oauth redirect url added to the HMRC app. With only 5 entries allowed on each HMRC app this is not possible.

What's everyone else doing?

Thanks.
Nick

**Comment by Yottskry** [comment]
Could you not have the callback return to one central location with a parameter to indicate the company, and then further redirect from there?

The HMRC documentation at https://developer.service.hmrc.gov.uk/api-documentation/docs/reference-guide#redirect-uris shows an example redirect URL as:

https://www.example.com:8080/auth-redirect?some_parameter=some_value

Couldn't you include ?company_name=Company1 (for example) as the parameter? I don't know how your specify that in the application setup on HMRC's website though. Obviously "company_name" will be constant, but I'm not sure how you'd indicate that "Company1" is variable.

**Comment by Yottskry** [comment]
I've also seen that oAuth2 supports the "state=xxxxx" parameter that simply gets returned from the server as part of the redirect:

https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints

Specifically: 

```
Syntax

GET  https://test-api.service.hmrc.gov.uk/oauth/authorize?response_type=code
&client_id=[YOUR-CLIENT-ID]
&scope=[REQUESTED-SCOPE]
&state=[STATE]
&redirect_uri=[YOUR-REDIRECT-URI]

Example

GET  https://test-api.service.hmrc.gov.uk/oauth/authorize?response_type=code
&client_id=Hf8sfkiUkYp9I3_R10qSnZ2ZUvoa
&scope=scope_1+scope_2+scope_3
&state=30de877c-ee2f-15db-8314-0800200c9a66
&redirect_uri=https://www.example.com/auth-redirect
```

and


```
state (optional) | An opaque value used to maintain state between the request and callback and to prevent tampering as described in the OAuth 2.0 specification (opens in a new tab). This is passed back to your application via the redirect_uri.
-- | --
```

So perhaps you could include the company there, and in your controller interpret that value to make the final redirect?

**Comment by hbr245b** [comment]
My company is in the same boat - web application which we host for our clients.

The callback URL can be specified without any parameters on the HMRC website but you can append parameters at runtime which will return you to the correct company.:

HMRC callback URL https://x.y.com/application/HMRCCallback

Callback sent to HMRC in your app:

https://x.y.com/applicationHMRCCallback?company=X
https://x.y.com/applicationHMRCCallback?company=Y

as long as you do some checking that the user has returned to the correct company on the callback.

**Comment by njacobs-winman** [comment]
Thanks for the advice. I thought I may have to go down the middleware route. It just seems to me that it increases the security footprint. Good to know I can pass some parameters. I will give that a try,

**Comment by ma3574** [comment]
Hi @njacobs-winman 

I hope you have reached a suitable resolution to your query. Should you require further assistance with regards to redirect uris please contact the SDS Team at SDSTeam@hmrc.gsi.gov.uk as they are the best team within HMRC to answer queries relating to this. 

Kind regards
Muhammed

**Comment by njacobs-winman** [comment]
I tried the SDS Team. There were no help.

**Comment by steveblamey** [comment]
@njacobs-winman did you find a solution to this? Wondering if @hbr245b's suggestion worked.

**Comment by hbr245b** [comment]
It works in the test sandbox;  clients have not yet submitted a live return as first eligible vat period ends today.

**Comment by njacobs-winman** [comment]
In the end I used the state object to hold the actual url to redirect to. I encrypted the value. The url redirect was directed to a serverless Azure function that decrypts the response and redirects the response. Seems to work well.

**Comment by steveblamey** [comment]
Thanks for your feedback @njacobs-winman and @hbr245b, that is very helpful.
