### ISSUE TITLE
How do the fraud prevention headers prevent fraud?

### ISSUE THREAD

**Issue by osrec** [hmrc/vat-api#435]
Given that most of the headers can be manipulated by the client, what value do they provide in the prevention of fraud? What kind of fraud are we guarding against?

We would like to understand how the data that is being sent in these headers would be used to support a fraud case? We don't think you can realistically ever say that the information is accurate or indeed reliable, especially in cases where the Gov-Client-Connection-Method is not via a server. And even if via a server, such a large subset of the information can be manipulated by the client, that we really question the value in these headers altogether.

**Comment by Yottskry** [comment]
I can't see that they do. There is nothing stopping a client from saying that every user has a resolution of 1024x768, a random local IP address in the range 192.168.x.x, and a timezone of GMT. Who's going to go to every company and check?

**Comment by konradwudkowski** [comment]
hi @osrec / @Yottskry We've worked in collaboration with our fraud investigation colleagues to define the spec and whilst we cannot disclose publicly how the header data will be used we will expect vendors to provide them and this will be verified.

As this is not a strictly technical question I'm going to close this issue.
