### ISSUE TITLE
Retrieve Obligations - MATCHING_RESOURCE_NOT_FOUND

### ISSUE THREAD

**Issue by HARVS1789UK** [hmrc/vat-api#437]
* **I'm submitting a ...**
  - [✔] Bug - API

**What is the current behaviour?**

Calling the VAT return obligations endpoint with a valid bearer token (with `read:vat` scope) and a valid VRN (that of a 'Test User' which represents an organisation), I always get the response:

> `404` Not Found

and the response body:

```
{
    "code": "MATCHING_RESOURCE_NOT_FOUND",
    "message": "A resource with the name in the request can not be found in the API"
}
```

Which seems to suggest (form other research) that the obligations endpoint is not getting hit (as opposed to there being no obligations to return, which would return the code `NOT_FOUND` instead)

**What is the expected behaviour?**

As per the [documentation](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0#_retrieve-vat-obligations_get_accordion) I am expecting to hit the VAT return obligations endpoint and if I pass no `gov-test-scenario` header see:

> the scenario where the client has quarterly obligations and one is fulfilled

or if I pass `"gov-test-scenario": "QUARTERLY_NONE_MET"` to see:

> the scenario where the client has quarterly obligations and none are fulfilled

**Other information**

I am using the sandbox API

I have tried various valid and invalid VRN's and to/from date ranges, I never get any alternative responses like `VRN_INVALID` or `INVALID_DATE_RANGE`

The VRN was generated as part of a 'Test User' (organisation) as is the set of credentials used to login and generate an oAuth access token.

** Request / Response Data **
```
{
    "status": 404,
    "response": {
        "req": {
            "method": "POST",
            "url": "https://test-api.service.hmrc.gov.uk/organisations/vat/666653988/obligations",
            "data": {
                "from": "2019-01-01",
                "to": "2019-03-31"
            },
            "headers": {
                "user-agent": "node-superagent/3.3.1",
                "content-type": "application/json",
                "accept": "application/vnd.hmrc.1.0+json",
                "gov-test-scenario": "QUARTERLY_NONE_MET",
                "authorization": "Bearer 43222c605f5e57b553ccd26f9d75854"
            }
        },
        "header": {
            "content-type": "application/json; charset=UTF-8",
            "content-length": "125",
            "accept-encoding": "gzip",
            "cache-control": "no-cache, max-age=0",
            "gov-test-scenario": "QUARTERLY_NONE_MET",
            "pragma": "no-cache",
            "strict-transport-security": "max-age=31536000;",
            "date": "Fri, 08 Feb 2019 12:21:06 GMT",
            "connection": "close"
        },
        "status": 404,
        "text": "{ \"code\" : \"MATCHING_RESOURCE_NOT_FOUND\", \"message\" : \"A resource with the name in the request can not be found in the API\" }"
    }
}
```

**Comment by cb-rfk** [comment]
Hi Harv,

You need to do a GET, not a POST.  The Submit VAT Return endoint is the only one you POST to :)

**Comment by HARVS1789UK** [comment]
Hi @cb-rfk,

Where is the facepalm emoji when you need it, 🤦🏼‍♂️there we go!

Good spot, thank you, I was actually setting up to submit VAT returns but modified things to list obligations first and forgot to change the HTTP verb/method back :-(

Could I suggest an improvement would be to make the HTTP response code in this instance `405` Method Not Allowed rather than `404` Not Found?

Cheers,

HARVS

**Comment by daniel-andrews1994** [comment]
Hi Joe,

Thanks for the suggestion, we will pass this on to the the API Gateway team who will look into this for you.

Thanks,
Daniel
