### ISSUE TITLE
How to Link a API Created Organisation to API Created Agent in the sandbox

### ISSUE THREAD

**Issue by barrychoc** [hmrc/vat-api#439]
Hi - I am working entirely in sandbox just now.

I have (via api) created an organisation and an agent. I want to link the organisation to the agent so that I can use the agent oauth bearer to call mtd vat api on organisation. Can someone please tell me how i can (in sandbox) link organisation with agent so that hey are basically an agent for the organisation as will be the case with my current "real clients"?

**Comment by Byordanova8** [comment]
You need to make a request to HMRC support to give you access to Agent Authorisation API. It is in private alpha version.

**Comment by barrychoc** [comment]
Thank,s Any idea how I go about doing that, email address for example?

**Comment by Byordanova8** [comment]
@barrychoc HMRC Support:
SDSTeam@hmrc.gsi.gov.uk

**Comment by shaunl23** [comment]
On this topic, does anyone know how long the wait is to do the demo with the team at HMRC? I sent them my full details, as they requested, a week ago and haven't heard back with a time to do a demo with them yet. Thanks

**Comment by Byordanova8** [comment]
@shaunl23 
I have waited for two weeks as well. I have contacted them via + 44 300 200 3311

**Comment by shaunl23** [comment]
@Byordanova8 Thanks for replying. Have you been able to sort it by calling them? I don't like pestering people

**Comment by Byordanova8** [comment]
@shaunl23
That is how I have approached them.

**Comment by shaunl23** [comment]
@Byordanova8 Ah, so you contacted them by phone to go live but haven't heard back for 2 weeks? I'm disappointed that it takes so long and there is nothing but silence in the mean time. I know they are busy but it's a short demo that would then enable us to make the changes to move to production and get any issues sorted in time for MTD coming into effect.

**Comment by Byordanova8** [comment]
Maybe I have not explain it clearly.
I have tried to approach them by email, but since it was during the holidays (one month and a half ago), I have not get a response. 
That is why I have called them in order to establish some contact.

**Comment by shaunl23** [comment]
I understand. What was their response to you in the phonecall please?

**Comment by Byordanova8** [comment]
They gave me another phone, but I have received a response via email as well.

**Comment by barrychoc** [comment]
....I have emailed them, but how can the real world setup be simulated if there is no access to the API linking agents to Organisations?
