### ISSUE TITLE
"Finalised" flag versus actual final return

### ISSUE THREAD

**Issue by nigelrainer** [hmrc/vat-api#44]
How will the new API support the situation when a return is actually a final return (ie the last ever return for a registration) which is currently supported in the existing XML API with the <vat:VATDeclarationRequest finalReturn="yes"> attribute. 

In the Sandbox documentation, the "finalised" field is described as:
“Declaration that the user has finalised their VAT return.”
However the relevant error code is described as:
User has not declared VAT return as final	403 (Forbidden)	NOT_FINALISED
These descriptions are ambiguous and initially I thought this was how a final return might be filed.  However, as there appears to be an expectation that the "finalised" field will be true 100% of the time, it appears pointless.

**Comment by nvasilev-hmrc** [comment]
@nigelrainer thank you very much for raising these questions. 
We would need to follow up with some of our colleagues in HMRC in order to get back to you with an answer.

**Comment by MarkAKelly** [comment]
Hi @nigelrainer, I appreciate the ambiguity in this scenario.

The 'finalised' flag in this instance is an explicit declaration by the customer, confirming that their return is complete and accurate. 

I mentioned to your colleague (tim-xero) on [another issue](https://github.com/hmrc/vat-api/issues/42) about a program of work that should cater for change of circumstances, which would presumably encompass supporting a return when it is the final (last ever) return.  Again, we will update and advise when this comes through.
