### ISSUE TITLE
Manual check of TxM anti-fraud errors in the Sandbox

### ISSUE THREAD

**Issue by PeterGGreen** [hmrc/vat-api#442]
Dear HMRC,

I've successfully retrieved obligations and submitted a VAT return with TxM Headers.  Is there any way "you" can check submissions to the sandbox and give me a clue whether they're correct or not?

Cheers,

Peter

PS. I second the extremely important point that's been raised here, that it's unacceptable to not have either a valid test environment or some kind of test in live scenario to ensure the TxM headers we add to our submissions are correct and would be accepted for a live submission.

**Comment by hughfdjackson** [comment]
Hi @PeterGGreen, 

We currently cannot check submissions made to the sandbox, but that is an item that we're presently working towards. 

As a quick check in the meantime, if you send us an example request with the headers intact, then we'll be happy to review them and let you know if we notice any non-compliance in the headers. 

If you could email to SDSTeam@hmrc.gov.uk with a text file attachment containing the example HTTP request and a title starting "Example Header Check Request", that would be fantastic.
