### ISSUE TITLE
Script error when starting OAUTH

### ISSUE THREAD

**Issue by PeterGGreen** [hmrc/vat-api#443]
Dear HMRC,

Just completed work on our TxM headers and I'm receiving a script error when starting the OAUTH process.  
![image1](https://user-images.githubusercontent.com/43069040/52645286-63947c80-2ed8-11e9-8d3e-05298a08824c.jpg)

Cheers,

Peter

**Comment by nickcable** [comment]
Hi,
I have also been getting these over the last week too and could not find any Internet Options to turn these off easily. I have manged to get around this by suppressing the script errors in my WinForm browser control window but this is not really fixing the issue just hiding the annoying dialog boxes while customers test.

I'm also getting :
![image](https://user-images.githubusercontent.com/47362850/52648179-f97ed600-2edd-11e9-8da0-794fcf4848ad.png)

on different servers but adding the URL to the Trusted Site Zones makes no difference.

Does anybody have a good solution for this please ? 
Thanks
Nick

**Comment by GrahamHDawson** [comment]
If you're using an embedded WebBrowser control you can set the Silent property to True to hide those script errors, or use the ScriptErrorsSuppred method depending on how you're doing things eg

Webbrowser1.Silent = True

or

WebBrowser1.ScriptErrorsSuppressed() = True

**Comment by nickcable** [comment]
Hi @GrahamHDawson, thanks for your reply. I am using the second method to suppress the messages, but wasn't sure if there was a better way to do it ! I wasn't aware of the Silent option though so will read up on this.
Cheers,
Nick

**Comment by PeterGGreen** [comment]
Hi Graham,

Thanks for the info.  I know you can suppress the messages, but I'd rather they didn't occur at all.  They didn't happen a couple of months ago.  And if no-one lets HMRC know, they can't fix it :-)

Cheers,

Peter

**Comment by LukeHirst** [comment]
I am also experiencing this issue recently and would like a reply on this by someone at HMRC

**Comment by nickcable** [comment]
Hi, Please can we have an update to this from HMRC.
Many thanks,
Nick

**Comment by brucemcmillan** [comment]
I have seen this issue appear recently too

**Comment by ma3574** [comment]
Hi @nickcable 

With regards to an update from HMRC this would not be something the VAT API team can update on as we only manage the API and not the platform/OAuth. The best way to receive answers to this type of query is to email SDSTeam@hmrc.gov.uk
