### ISSUE TITLE
How to clear VAT Submissions

### ISSUE THREAD

**Issue by profteck** [hmrc/vat-api#445]
When submitting an issue please try to provide the following information:

* **I'm submitting a ...**
  - [x ] Support request

I'm using Sandbox for testing my submissions.  But how do I clear a submission so I can test again - I only get one open vat obligation so once I submit once, I can't test again.

Thanks.
Ann

**Comment by GrahamHDawson** [comment]
Use the testing header scenarios ie Gov-Test-Scenario and you can look at none met, one met, two met, three met etc etc.
So submit to none met, then you can submit to one met using the Outstanding obligation, then to two met etc etc

**Comment by profteck** [comment]
Graham
Thanks for the info.  Much appreciated.
Ann

**Comment by profteck** [comment]
Is there any way to delete a submission once it has been uploaded to HMRC ?
If the user had made a mistake and they wanted to delete the submission - I don't see any API for doing this.

**Comment by ma3574** [comment]
Hi @profteck 

It is not possible to delete or amend a VAT submission via the API once it has been submitted. If the user has made a mistake they will not be able to update the info via the API. Please contact the SDS Team at SDSTeam@hmrc.gsi.gov.uk and they will be able to advise you of the best process to follow in that instance. 

Also for future reference, please open a new issue for a new question. This helps you and other developers when searching the past issues in the future :)

Kind regards
Muhammed
