### ISSUE TITLE
CLIENT_OR_AGENT_NOT_AUTHORISED

### ISSUE THREAD

**Issue by heythisiskishore** [hmrc/vat-api#446]
I already authorized a Trader and also retrieved obligations from the Sandbox user, while submitting the VAT it is showing 'CLIENT_OR_AGENT_NOT_AUTHORISED' and getting the status code as 'StatusCode: Forbidden'. But this is happening only for some Test Users only. For some Sandbox users it is getting an response from HMRC like 'Duplicate_Submission' but i didn't submitted any VAT for that VRN.

**Comment by ma3574** [comment]
Hey @heythisiskishore 

We are not seeing any such issues within the sandbox with other users. Please provide more details with exact steps to reproduce the issue you are having. 

Kind regards
Muhammed

**Comment by EwanReid** [comment]
Hi @ma3574 
I seem to be experiencing this too. Going through the OAuth process using Postman. 
The first accessToken I retrieve from the authorization_code grant_typeis valid. But as soon as I refresh it using the refresh_token grant_type, I get CLIENT_OR_AGENT_NOT_AUTHORISED. This is for users created through the test user api endpoint. 

1. Generate Test User with mtd-vat service :
![hmrc - create organisation user1](https://user-images.githubusercontent.com/32311819/52709930-fb03d900-2f85-11e9-9d04-f442459bff57.PNG)
![hmrc - create organisation user2](https://user-images.githubusercontent.com/32311819/52709969-1242c680-2f86-11e9-8e73-07c56fe2e2c5.PNG)


2. Request authorisation and retrieve authorisation code:
![hmrc - auth link 1](https://user-images.githubusercontent.com/32311819/52710068-4d44fa00-2f86-11e9-9f3c-8e2dfc107b69.PNG)
![hmrc - auth link 2](https://user-images.githubusercontent.com/32311819/52710071-4f0ebd80-2f86-11e9-89a7-b87e75542d16.PNG)

3. Exchange authorisation code for access token
![hmrc - token auth 1](https://user-images.githubusercontent.com/32311819/52710208-b298eb00-2f86-11e9-9761-865918737ee1.PNG)

4. Get Obligations with access token
![hmrc - getobligations before](https://user-images.githubusercontent.com/32311819/52710304-ed028800-2f86-11e9-817f-33042bcf4236.PNG)

5. Refresh access token using refresh_token grant_type
![hmrc - token auth 2 refresh](https://user-images.githubusercontent.com/32311819/52710362-0c99b080-2f87-11e9-8b56-1f302f722e05.PNG)

6. Get Obligations with new access token
![hmrc - getobligations after](https://user-images.githubusercontent.com/32311819/52710443-394dc800-2f87-11e9-9c52-0d7a638560d0.PNG)

Maybe I'm missing something, but this was working fine until yesterday.

**Comment by DarrenHeaton** [comment]
I agree, It was working yesterday, I've just spent the last 2 hours because I thought code that had previously been working for weeks had stopped working :-) 

I've the same issue as EwanReid.

**Comment by ma3574** [comment]
We are currently investigating this issue and have contacted the relevant teams. We will update you as soon as possible. 

In the mean time if it is having an adverse impact on your team I recommend emailing SDSTeam@hmrc.gsi.gov.uk and highlighting the issue as this may expedite things.

**Comment by ma3574** [comment]
This issue should now be resolved. If you refresh your access tokens now, the new tokens will work. I've gone through the process myself and used the new `access_token` successfully. Please let us know if there are any further issues with this. In the mean time we'll continue to monitor it from this end.

**Comment by likedustg** [comment]
We again get the problem on sandbox environment this morning. Can anybody please check it?

**Comment by heythisiskishore** [comment]
Getting the same issue, not resolved up to now.
