### ISSUE TITLE
CLIENT_OR_AGENT_NOT_AUTHORISED using newly refreshed access_token

### ISSUE THREAD

**Issue by glidester** [hmrc/vat-api#447]
- [*] Bug - API
  - [*] Support request

* **What is the current behaviour?**
In sandbox environment my application:-

1. forwards user to authenticate on HMRC site
2. retrieves authorisation code from callback 
3. exchanges authorisation code for access token and refresh token
4. uses access token to get obligations for user (works fine, 200 received with data as expected)
5. user restarts application 
6. app refreshes access token by calling:
`https://test-api.service.hmrc.gov.uk:443/oauth/token
Data: client_secret=xxxxxx&client_id=xxxxxx&grant_type=refresh_token&redirect_uri=http://localhost:8888/mtd&refresh_token=ac9fa2a8de62e5733a502f9dca6f1`

7. app receives 200 response:
`{"access_token":"8b2a92fcbaec1c37fbb7f8428bac69d3","refresh_token":"6216574cbbf068e9d75570f864453730","expires_in":14400,"scope":"read:vat write:vat","token_type":"bearer"}`

8. app attempts to get obligations for user using new access token '8b2a92fcbaec1c37fbb7f8428bac69d3', but gets response 403:
'{"code":"CLIENT_OR_AGENT_NOT_AUTHORISED","message":"The client and/or agent is not authorised."}' 

* **What is the expected behaviour?**
The access token returned by the refresh call should work when used to retrieve obligations.

* **Other information** (e.g. detailed explanation, screenshots, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Find answers to common questions [here](https://github.com/hmrc/vat-api/wiki/FAQ)

**Comment by shaunl23** [comment]
I'm getting this also. Was panicking and looking through my code for problems

**Comment by EwanReid** [comment]
I am recieving this aswell. 
See here for screenshots: https://github.com/hmrc/vat-api/issues/446#issuecomment-463174513

**Comment by shanepilkington** [comment]
I'm also receiving this error.

**Comment by ma3574** [comment]
We are currently investigating this issue and have contacted the relevant teams. We will update you as soon as possible. 

In the mean time if it is having an adverse impact on your team I recommend emailing SDSTeam@hmrc.gsi.gov.uk and highlighting the issue as this may expedite things.

**Comment by glidester** [comment]
Ok, I've sent them an email referencing this issue.

Can you confirm @ma3574 that you are seeing the same behaviour as the rest of us? 

Thanks.

**Comment by mathiasbanda** [comment]
we are getting that :(

**Comment by ma3574** [comment]
I can confirm that we are seeing the same behaviour. It is currently being investigated. Apologies for the issues this is causing.

**Comment by JoaStrzy** [comment]
HI, the same error I have in testing environment.

**Comment by ma3574** [comment]
This issue should now be resolved. If you refresh your access tokens now, the new tokens will work. I've gone through the process myself and used the new `access_token` successfully. Please let us know if there are any further issues with this. In the mean time we'll continue to monitor it from this end.

**Comment by glidester** [comment]
Thanks @ma3574  looks like it is working now at my end.
