### ISSUE TITLE
503 Service Unavailable from Agent Invitation Service

### ISSUE THREAD

**Issue by WarrenQuill** [hmrc/vat-api#448]
Hi,

I've created a test agent user using the createuser api, and used their details to create an invitation for a user created following the instructions at https://test-www.tax.service.gov.uk/agents-external-stubs/help/agent-authorisation-api. 

When I post to https://test-api.service.hmrc.gov.uk/agents/myAgentServicesAccountNumber/invitations I get 503 service unavailable. When I do a get on https://test-api.service.hmrc.gov.uk/agents/myAgentServicesAccountNumber/invitations I get a 403 forbidden. 

Does this mean I need to contact the SDS team to get access to this api as per https://github.com/hmrc/vat-api/issues/439?

Cheers

**Comment by Deedles46** [comment]
When we create an agent authorisation we are get an error 403 (Forbidden) VAT_REG_DATE_DOES_NOT_MATCH.

We would like to know if the maintenance on Agent authorisation api is occuring now, and if yes, when will it be finished?  We ask this because we have been getting this result since 2 days ago.

**Comment by jonathanleather** [comment]
Hi @WarrenQuill 

Unfortunately we do not own this API, so aren't in a position to answer.
Your best bet is to contact SDST (SDSTeam@hmrc.gov.uk) so they can put you in touch with the relevant team.

Cheers
Jon
