### ISSUE TITLE
Please add an 'Updated On' line to the documentation when the API changes

### ISSUE THREAD

**Issue by GrahamHDawson** [hmrc/vat-api#449]
* **I'm submitting a ...**
  - [X] Bug - Documentation
  - [X] Feature request

I know the API is Beta - but we need to know when changes are made.
Currently the only way we can do that is to continuously monitor the Code section here on Github looking for changes.

Today a change to retrieval of Obligations has been implemented such that if the Status is set to 'O' (Outstanding) we can omit the 'From' and 'To' date query parameters.

The documentation has been updated...

https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0#_retrieve-vat-obligations_get_accordion

but there's no way of us knowing this change has been made.

Please, **Please** add a line to the documentation indicating when the page was last updated - similar to the 'Version 2.2 issued 12 February 2019' line that appears on the Anti-Fraud information page.
(Which has been updated yet again)

Preferably we should be emailed when either of the above pages are changed even if the API is Beta.

I can't speak for other developers but in my case MTD VAT is just a small part of my workload and I really can't (and don't expect to have to) continuously monitor HMRC websites for changes.

**Please**

**Comment by ma3574** [comment]
Thanks for this feedback @GrahamHDawson. I see what you mean about not having clarity over what has changed. 

With this specific change we are trialing a new way of updating the change log to make it clear what has changed. Please see here: https://github.com/hmrc/vat-api/blob/master/CHANGELOG.md 

Would this work for you as a format for changes?

In addition to this our User Researcher is currently gathering feedback from vendors such as your self with regards to how HMRC should send out communication regarding changes. An email with the questionnaire has gone out already. I urge as many vendors as possible to reply as this feedback will be used to decide how we communicate going forward.

**Comment by GrahamHDawson** [comment]
Well the CHANGELOG.md idea is fine - **but** it still requires developers to regularly check for changes.
Personally I think a short email with the link to the changelog.md and perhaps the latest change would be better.

There needs to be a similar change log on the Anti-Fraud headers page also.
Currently it indicates something changed on 12th February - but **what** was changed is anyone's guess - I still haven't worked it out :-)

**Comment by ma3574** [comment]
I will forward this feedback to our User Researcher. Thank you for putting it forward :)

**Comment by konradwudkowski** [comment]
hi @GrahamHDawson regarding anti-fraud headers, the change from 12th Feb is that if you tried but were unable to obtain data for a given header you can either submit it with an empty value or omit it entirely. Before the spec said you always had to provide a header and shouldn't omit.

**Comment by GrahamHDawson** [comment]
Thanks Konrad for the change info.

**Comment by ma3574** [comment]
For anyone that finds this issue going forward. The changelog is now located in the wiki here: https://github.com/hmrc/vat-api/wiki/Changelog and specifies what changes have taken place.

You are able to subscribe to the RSS for the wiki here: https://github.com/hmrc/vat-api/wiki.atom to stay informed.
