### ISSUE TITLE
AAS balancing payments

### ISSUE THREAD

**Issue by nigelrainer** [hmrc/vat-api#45]
Will the new API support AAS (annual accounting scheme) balancing payments, currently supported in the existing XML API in the &lt;vat:AASBalancingPayment&gt; element?

**Comment by hicnar** [comment]
@nigelrainer thank you for your question. 

The question you sent is not strictly a technical one, therefore may I ask you to re-send it to SDST as they are in a better position to answer queries regarding "if/when particular features will be supported in the new API".
