### ISSUE TITLE
Request to re-open #255

### ISSUE THREAD

**Issue by JeeBeePee** [hmrc/vat-api#450]
The message body of the 404 returned when a return is requested for a non-existent period key is empty, which does not square up with the API doc.  The sandbox returns an empty 404 when requesting return 18A3, despite that period key being returned when listing fulfilled obligations.

**Comment by AndrewMCoates** [comment]
We are getting the same issue.  Please re-open.  Is this related to issue #451 referred to in #458 about test user vrn numbers not having linked data?

**Comment by jonathanleather** [comment]
Hi @JeeBeePee 

If I understand you correctly I believe you are referring to 2 things here. I'll try and explain both as best I can.

1) **The empty body when a 404 is returned not following the documentation**
We are aware of this but unfortunately we are not in a position to change it (even though we would really like to). Changing this now would be a breaking change for a lot of other vendors. Which is something the programme are very hesitant to do so close to April. If / when a version 2 of the API is released, this will most certainly be fixed then.

2) **The sandbox returning a 404 even though the obligations endpoint displays them as fulfilled** 
Obligations is a stateless endpoint and only returns canned data. It doesn't matter what VAT return you submit, the obligations data will not change.

@AndrewMCoates this issue referenced in issue 451 is slightly different but should now be fixed. If you are still running into problems could you raise a new issue for us to investigate for you?

Cheers
Jon
