### ISSUE TITLE
Issue submitting VAT Return for quarterly period 18A2 

### ISSUE THREAD

**Issue by LukeHirst** [hmrc/vat-api#451]
I currently have an issue with the test api when submitting A VAT return for a quarterly obligation. 

I am unable to submit a return for period key 18A2, I always get a duplicate submission error even though I have not submitted yet.

18A2 relates to the following obligation: 

{
 "start":"2017-04-01",
 "end":"2017-06-30",
 "due":"2017-08-07",
 "status":"O",
 "periodKey":"18A2"
}

What is even more surprising is that this only occurs after I submit the VAT return 18A1 first. 

If I were to create a test organisation and submit VAT returns for the following period keys: 

18A2
18A1
18A3
18A4 

Then this works completely fine. 

Then If I create another organisation and submit in sequential order: 

18A1
18A2
18A3
18A4 

For the following request: 

{
 "periodKey":"18A2",  
 "vatDueSales":##.##,
 "vatDueAcquisitions":##.##, 
 "totalVatDue":##.##,
 "vatReclaimedCurrPeriod":##.##,
 "netVatDue":##.##
 "totalValueSalesExVAT":##.##,
 "totalValuePurchasesExVAT"##.##,
 "totalValueGoodsSuppliedExVAT"##.##,
 "totalAcquisitionsExVAT"##.##,
 "finalised":true
}

(I have blanked out the monetary values)

I always get the following response: 

{
 "code":"BUSINESS_ERROR",
 "message":"Business validation error",
 "errors":[{
                 "code":"DUPLICATE_SUBMISSION",
                 "message":"The VAT return was already submitted for the given period."
                }]
}

Is this a known issue? Can anybody else recreate this behaviour?

**Comment by LukeHirst** [comment]
Some more information, 

this occurs only when I do the calls in the following order to the api with the 'GOV-Test-Data' header: 

VAT obligations QUARTERLY-NONE-MET
Submit VAT return 18A1
VAT Obligations - QUARTERLY_ONE_MET
Submit VAT return 18A2 

If I were to return the VAT obligations without supplying the GOV test header **first** and then go through the above process it all seems to work fine. 

I do not understand how I am getting this issue as I am sending the correct period key, which has never been submitted to before for the organisation I am testing with.

**Comment by nickcable** [comment]
Hi Luke, amazingly, I have just logged the same issue on the forums. We have the same issue and is driving me crazy. Perhaps it is a bug in the API afterall ??

**Comment by jacobbrownlow** [comment]
Hi everyone, I'm currently looking into this
Jacob

**Comment by profteck** [comment]
I set up a new user for testing in the sandbox - before I submit any return - I used the api to view returns and there is a return there for 18A2

**Comment by nickcable** [comment]
Hi @profteck , good thinking. That would explain why we sometimes get a duplicate submission, but sometimes it does work and I can submit 18A2 correctly most of the time so there must be another underlying issue as well. Thanks
Nick

**Comment by profteck** [comment]
Even though I don't have 18A1 submitted for the new user company - it is telling me when I try to submit (using the quarterly-none-met - which is period key 18A1), that it is a duplicate submission.  It did let me submit 18A3.

**Comment by jacobbrownlow** [comment]
Hi everyone

I can confirm this is a test environment issue. There was a change to the way in which VRNs are generated in the test environment and it is causing duplicate VRNs to be used more frequently than we would desire.

We are going to contact the team who own the create-test-user API and try to resolve this. 

Please note you can use any `periodKey` to test Submit VAT return. You do not need to use 18A1 or 18A2, these are just example responses from the Obligations endpoint.

Regards, Jacob

**Comment by nickcable** [comment]
Hi @jacobbrownlow  Many thanks for confirming. I understand it does not stop us testing, however, some of us have scripted our application to work in test mode for our HMRC demo and therefore  when we move through QUARTERY_NONE_MET, _ONE_MET, TWO_MET etc.  we would expect it to work as the demo is quite important to us. Perhaps you could make the approving team aware of this please so that if anybody encounters this during their demo it will not prevent them being approved.
Many Thanks
Nick

**Comment by profteck** [comment]
@jacobbrownlow - thanks for confirming.  As nickcable a problem with a demo is a major issue.  Scheduled for next week and it was only when we were doing a test run with a new company that this appeared.  I'll try changing the period key to see what happens.  
Thanks again
Ann

**Comment by LukeHirst** [comment]
Hello Jacob, 

Thanks for getting back to us on this. 

Is there an eta on when this issue will be fixed?

**Comment by jacobbrownlow** [comment]
Hi all, the VRN generator has been updated and this problem should now be resolved

Jacob

**Comment by LukeHirst** [comment]
I have tested the api with a brand new organisation and I get the behaviour I expect now.

**Comment by AbsoluteAccounting1** [comment]
Has anybody had experience of this happening live?
