### ISSUE TITLE
403 Duplicate Submission errors on sandbox but only submitted once

### ISSUE THREAD

**Issue by nickcable** [hmrc/vat-api#452]
Hello,
I have been testing our MTD software in the test sandbox for a few weeks now and part of this testing has been to submit VAT returns. Whilst this testing has generally proved very successful, occasionally we are getting a '403 Duplicate Submission' error eg :

403 (Forbidden)

{"code":"BUSINESS_ERROR","message":"Business validation error","errors":[{"code":"DUPLICATE_SUBMISSION","message":"The VAT return was already submitted for the given period."}]}"

What concerns me is that as we have looked at the trace logs and **we are only making one call 
to the submit VAT return API** - so we have not sent it twice to cause a duplication !

Has anybody else come across this at all in there testing ?

Could it be possible that the VRNs on the test sandbox still have submission data recorded against the period key for that VRN ? Surely not.

We are using the gov-test-scenario headers to move from QUARTERLY_NONE_MET to QUARTERLY_ONE_MET, _TWO_MET, _THREE_MET and _FOUR_MET in the test scenario.

This is so random and we have to try over a dozen or so submissions  (with several different VRN's) which all work correctly until the same error re-appears. It seems to occur more frequently later in the day ie 4pm onwards and happens mainly for the period key '18A2' which is the second submission ie. _ONE_MET in the sequence.

Whilst we can't rule out it is some sort of software issue (?!), the fact that we are making one call to the API and getting a response saying it the VAT has already been submitted seems... well, head scratchingly weird !

I'm hoping somebody else has come across similar symptoms ! Would like to get to the bottom of this.

Thanks in advance,
Nick

**Comment by LukeHirst** [comment]
Hello Nick, 

I have also opened an issue relating to this. 

#451 

I am also experiencing this behaviour as well

**Comment by nickcable** [comment]
Thanks Luke, that really helps to know that somebody else is experiencing this.  I wonder if HMRC could please comment on this issue ? 
Thanks
Nick

**Comment by lukaszszczygiel-sage** [comment]
Hi Nick,
I also encounter this issue. Using different VRN for first time I get DUPLICATE_SUBMISSION or the submission is passing

**Comment by jacobbrownlow** [comment]
Hi everyone, I am currently looking into this issue. Can I ask that we close this one and I'll respond in https://github.com/hmrc/vat-api/issues/451 

Thanks Jacob
