### ISSUE TITLE
View more than one VAT return at a time

### ISSUE THREAD

**Issue by profteck** [hmrc/vat-api#453]
When submitting an issue please try to provide the following information:

* **I'm submitting a ...**
  - [ ] Improvement

* **What is the current behaviour?**
For the "View Returns" API - currently a request is put in for one period key

* **What is the expected behaviour?**
Would it be possible to request more than one period key - e.g. to see the returns for a range of dates the HMRC have on file for the company.  I can't find that anyone has requested this.  There is an issue this morning to do with submissions that are on the MTD system that our systems say we haven't submitted.  I had to go through each period key to determine which key had a return.  It would have been nice to get a full list for the year.
Only a suggestion

Thanks
Ann

**Comment by GrahamHDawson** [comment]
Can't you get that information via the Obligations endpoint?
ie request Obligations for the full year and each entry in the list will be either F(ullfilled) or O(utstanding)

In our case we always use a full year date range for the Obligations endpoint ie from current date - a year, to current date, and display all the obligations returned with the F or O status.
Clicking on an obligation with the F status will retrieve the submitted return via the View Return endpoint.
Clicking on an obligation with the O status will start the submission process.

**Comment by jacobbrownlow** [comment]
Hi @profteck 

There are no plans to implement a view multiple returns endpoint at this time.

As Graham has suggested the best solution may be to retrieve obligations and from there link to view VAT return for any obligation that is Fulfilled.

Thanks for your feedback though, I'll pass this onto the team for consideration.

Jacob

**Comment by profteck** [comment]
Graham
I am providing the option you suggest - list of obligations - click on them and view return.  I was just wondering if you could returns for all the fulfilled obligations.  
I suppose I could just take the list of obligations and the vat return end point for each and then display the full list.
Thanks to everyone who left a comment
Ann
