### ISSUE TITLE
Gov-Test-Scenario: MULTIPLE_PAYMENTS amount with no date?

### ISSUE THREAD

**Issue by ruffle-b** [hmrc/vat-api#454]
Using the sandbox and getting multiple payments (Gov-Test-Scenario: MULTIPLE_PAYMENTS) I'm getting an amount of £91 with no received date attached. Is this some kind of test we're meant to do something special with? or just a bug in the sandbox data?

Here's the JSON the API returns:

{"payments":[{"amount":5,"received":"2017-02-11"},{"amount":50,"received":"2017-03-11"},{"amount":1000,"received":"2017-03-12"},{"amount":321,"received":"2017-08-05"},{"amount":91},{"amount":5,"received":"2017-09-12"}]}

Look at the fifth element... it's only got the amount and no received date.

**Comment by GrahamHDawson** [comment]
Yeah, it's just a crazy test environment thing.
It's been mentioned several times (I pointed this out to the DRM people when we did our approval demo)
In practice in the production system you'd never get this - I mean how can there be a payment without a received date :-)

**Comment by jacobbrownlow** [comment]
Hi @ruffle-b

This is intentional. For some VAT users there is a chance that the `received` date will not be returned from the backend. We do not expect this to be a common occurrence, but because it is a possibility we included this example in the test data.

Regards, Jacob

**Comment by GrahamHDawson** [comment]
Hi Jacob - Are you saying the received date will be there, but just not returned?

**Comment by jacobbrownlow** [comment]
Hi Graham

We've been made aware that there are some edge case users where the `received` date will not be returned by the backend systems. Unfortunately we do not have further details as to which users this impacts or why.

Regards, Jacob

**Comment by ruffle-b** [comment]
OK.... thanks. As it is both intentional in the sandbox and possible in the Real World I'll just show it to my users as "Unknown" and let them argue with HMRC :-)

Having said that. I am struggling to comprehend a financial system that records an incoming payment without an associated date of receipt. If our accounts package did that, our users would have us working night and day until it was fixed!
