### ISSUE TITLE
Inconsistent Method of Identifying Tax Periods

### ISSUE THREAD

**Issue by HARVS1789UK** [hmrc/vat-api#455]
**I'm submitting a ...**
  - [ ✔️] Bug - Documentation
  - [ ✔️] Improvement
  - [ ✔️] Support request

Possibly more a question rather than a suggested improvement (for the moment at least) but why does `/organisations/vat/{vrn}/liabilities` return a `taxPeriod` object with `from` and `to` dates, instead of just returning the associated `periodKey` like all other VAT API methods use to reference tax periods?

This is based on the below assumptions (bearing in mind that I live in Jersey, Channel Islands, so do not pay tax to HMRC in any way, let alone VAT returns as an organisation):

- `periodKey` is a 1 - 1 representation of a tax period?
- Tax periods are quarterly?
- There are no methods to look up `periodKey` by date, nor `from` and `to` dates by `periodKey`?

Can anyone provide some clarification/justification to this design decision (or my incorrect assumptions)?

**Update**: Any progress made on this similar request - https://github.com/hmrc/vat-api/issues/83

**Comment by jacobbrownlow** [comment]
Hi Joe

My understanding is that the periodKey is for internal use and should ideally not be presented to the end users. With this in mind, the liabilities endpoint returns the dates rather than the periodKey.

To answer your other questions:

- A tax period will have a periodKey, but there are transactions that have a periodKey but are not associated with a tax period. For example a penalty.
- Tax periods are not necessarily quarterly. We've given monthly examples, and there are annual periods and other non-standard periods.
- There is no facility to look up periodKey by date. However you can retrieve VAT obligations by date, which will provide the periodKey.

Jacob

**Comment by HARVS1789UK** [comment]
Hi @jacobbrownlow,

Thank you for your response and for confirming/correcting my assumptions.

I do not intend to display the `periodKey` to end users, but I was planning to use it as part of my data model/structure within my application. I planned to store `periodKey` in my data models for a return and an obligation but am not easily able to do the same for a liability because it is the one method which returns period `to` and `from` dates instead of a `periodKey`.

Thanks for correcting me to confirm that return periods are not necessarily quarterly (they could be monthly, annually or any other arbitrary period I guess), this is good to know however, it does mean that your suggestion of using the 'Retrieve Obligations' API call with the `to` and `from` dates returned by 'Retrieve Liabilities' will not really be a solution for looking up `periodKey` by dates as presumably (based on the fact that tax periods can be say a date range of 1 year), I could make a call to 'Retrieve Obligations' passing a 1 year date range and I would get back > 1 obligation (each with it's own period ID) and not have anyway of identifying which of the multiple `periodKeys` my liability relates to.

Unless I am mistaken, this means I can neither:

- Consistently link the VAT entities of (obligation, return and liability) to a tax period using the data returned by the 'Retrieve'  methods for each of them
- I cannot consistently model `Tax Period` in my own application and store `periodKey`, `to` and `from` data for each of them because it these two methods of representing a tax period cannot be accurately inferred from one another

I suppose this is not really a show stopping issue because once I have reached the stage of listing liabilities, I cannot do anything else programatically with them which would strictly require me to know what the related tax period is. It just seems a bit inconsistent and makes my OCD tendencies itch :-(

**Comment by jonathanleather** [comment]
Hey @HARVS1789UK 

I have passed your comments on to the project for future consideration.
I'll close this issue but if you have any more queries do not hesitate to come back to us.

Cheers
Jon
