### ISSUE TITLE
Getting Business Validation Error

### ISSUE THREAD

**Issue by heythisiskishore** [hmrc/vat-api#458]
Dear all,

I have created a Test User record from Sandbox given by HMRC. I have completed the Authorisation and also retrieved the VAT Obligations for one VRN 666192413. I have tried to Submit the VAT for that VRN with the given period but it is throwing an error like "{"code":"BUSINESS_ERROR","message":"Business validation error","errors":[{"code":"DUPLICATE_SUBMISSION","message":"The VAT return was already submitted for the given period."}]}" but i didn't submitted this.

When i am trying to fetch this record from VAT Return unable to fetch it and throwing the message like "{"code": "MATCHING_RESOURCE_NOT_FOUND", "message": "A resource with the name in the request can not be found in the API"}".

For some times it is showing like 'Fobidden' error like 'Business Validation Error'.

Waiting for the Reply.

**Comment by GrahamHDawson** [comment]
See issue 451 - it seems there's currently a problem with the pseudo-random VRN numbers

**Comment by jonathanleather** [comment]
Hey @heythisiskishore 

Are you still experiencing this issue? Or has it been resolved following the fix mentioned in issue #451?

Cheers
Jon

**Comment by james-work-account** [comment]
Hi @heythisiskishore - due to the lack of response I am assuming that this issue has now been resolved. Please feel free to re-open if you are still experiencing this issue.

Thanks,
James

**Comment by heythisiskishore** [comment]
Sorry James for the Late reply.

I am facing the same issue again in the Sandbox environment.
