### ISSUE TITLE
Re-Authorisation before 18 months

### ISSUE THREAD

**Issue by upendra-rathore** [hmrc/vat-api#459]
Hi there,
I'm submitting a support request.

I have a small query whether HMRC will accept the user to "Re-authorise the software to interact with HMRC" before 18 months?

Is there any restriction for this process from HMRC's end?

**Comment by GrahamHDawson** [comment]
There's certainly no restriction in the test environment.
We plan to ask users to re-authorise at the VAT year start ie once every 12 months

Users can also remove authorisation at any point, so I guess the ability to re-authorise **your** application or switch to another vendors application is required.

**Comment by cb-rfk** [comment]
Hi @GrahamHDawson 

Is it necessary to explicitly ask the users to re-authorise?  

Maybe I've got this all wrong, but what I've inferred while developing against the sandbox is that the user will log into our (web) application, go to the "Vat Return" module, do the HMRC OAuth redirect and enter their GGW username and password.

At that point, if they have not authorised our application to access their Vat details, they will be asked to do so, but if they've done that in the past 18 months this step will be skipped..?

So, from our side, there is no difference in the processes or workflow for a user who has: 
* never authorised our application; 
* has authorised it in the last 18 months; 
* has authorised it more than 18 moths ago.

Cheers,
Richard

**Comment by GrahamHDawson** [comment]
Hi Richard,

As I understand it you only need to do the oAuth granting authority steps once every 18 months for each users.

So in any given VAT year they'll grant authorisation once and that will be it.
They get an Access Token and a Refresh Token and (by using the Refresh Token) they can continue for the whole year without having to go through the oAuth steps again.

ie you don't do the oAuth bit every time - just once a year (or once every 18 months if you like)
At some point the ability to use the Refresh Token will expire and **then** you need to do the oAuth steps again.
