### ISSUE TITLE
Lost Access Token

### ISSUE THREAD

**Issue by upendra-rathore** [hmrc/vat-api#460]
Hi there,
I'm submitting a support request.

In case a user lost the latest Access Token and Refreshed Token then is there any chance that HMRC will provide us the new refreshed Access Token based on Original Access Token? or is there any other option available in case of loss of Access Token?

Any guidance will be much appreciated!

**Comment by GrahamHDawson** [comment]
As I understand it each token has a lifetime...
Access Token - lifetime of 4 hours
Refresh Token - lifetime of 18 months

So when your user grants your application authorisation you get your first Access Token and Refresh Token 'pair' and record the expiry times.
When the Access Token expires you use the Refresh Token to get a fresh Access/Refresh Token pair.

If somehow you 'lose' the tokens then the end-user will need to grant authorisation again.

**Comment by jonathanleather** [comment]
Hi @upendra-rathore 

If you require further information in addition to that provided by @GrahamHDawson I would suggest contacting SDST (SDSTeam@hmrc.gov.uk), so they can put you in touch with the relevant team.

Cheers
Jon
