### ISSUE TITLE
Fraud Prevention Headers: Gov-Vendor-Forwarded

### ISSUE THREAD

**Issue by cb-rfk** [hmrc/vat-api#461]
* **I'm submitting a ...**

  * Support request

We have a web application (apache/tomcat) hosted behind a WAF and accessed directly by our users via a web browser. 

Can anyone explain what this header is supposed to contain in our circumstances (other than a list of IP addresses!).

Many thanks,
Richard

**Comment by GrahamHDawson** [comment]
According to the documentation it's a list of 'by' 'for' IP address pairs eg

Gov-Vendor-Forwarded: by=33.252.57.234&for=57.4.28.41,by=188.87.76.95&for=209.210.136.84,by=176.30.57.118&for=150.94.192.63

https://developer.service.hmrc.gov.uk/api-documentation/docs/fraud-prevention

right at the very bottom of the page.

**Comment by cb-rfk** [comment]
Hi @GrahamHDawson ,

Sorry, yes I should have said in my original post that I had seen the details there, but they didn't make much sense to me!

Cheers,
Richard

**Comment by cb-rfk** [comment]
Hi everyone,

Just a shout out asking if anyone can help us understand the requirements for this header.

Our service is a web based accounting package used by our customers, so they will log into our website and, when required, submit their vat returns via it.

We own the full stack and have, in order of closeness to the end user, a WAF, a web server and an application server.

So, what are the IP addresses we are supposed to be reporting in this scenario?

Thanks.

Richard

**Comment by GrahamHDawson** [comment]
Doesn't the documentation example show exactly what you have ie a WAF,a web server and an application server - and details the required 3 hops output?

**Comment by cb-rfk** [comment]
Hi again,

Yes, maybe it does... it refers to Vendors A and B and uses external IP addresses for everything, which is what was confusing me...

I can certainly look at including our WAF address (that's already being reported in the Gov-Vendor-Public-IP header) and the couple of internal IP addresses, though I'm not sure how to get those dynamically in the back end (Java) code!

**Comment by hughfdjackson** [comment]
Hi @cb-rfk ,

As the documentation states, the Gov-Vendor-Forwarded header is expected to contain: 

> A list that details hops over the internet between services that terminate TLS.

From this comment: 

> I can certainly look at including our WAF address (that's already being reported in the Gov-Vendor-Public-IP header) and the couple of internal IP addresses, though I'm not sure how to get those dynamically in the back end (Java) code!

It seems that: 

- your WAF communicates to your web server via a private network
- your web server communicates to your application server via a private network

If that's the case, then neither your application server nor your web server needs to be included in Gov-Vendor-Forwarded.  

In your description, that leaves just the WAF.  In which case, your Gov-Vendor-Forwarded header would include one key-value pair, with: 
- the `by` field containing the same value as Gov-Vendor-Public-IP
- the `for` field containing the same value as Gov-Client-Public-IP

**Comment by hughfdjackson** [comment]
@cb-rfk 

I hope the above answers your question - we'll be closing this ticket shortly, but please let us know if you have outstanding questions specifically about this header, and we'll re-open if necessary.

**Comment by cb-rfk** [comment]
Hi @hughfdjackson 

Yes, that's the confirmation I was after, thanks very much.

Happy to close the call now.

Richard

**Comment by PavithiraS** [comment]
@hughfdjackson : I have a concern. It would not really be possible to capture the public IP (and the hops to) of an application that a client request hits. It would only be possible for the application itself to do a nslookup and traceroute respectively and get the IP that it sees for itself.
We have a web application where the Public IP might sometimes vary when the ISP is changed suddenly for an issues/maintenance.
In such cases, the incoming client request could have come through a different IP and the IP which is obtained during processing the request might be different (a very rare edge case).
Is this fine and acceptable (having said that, both the IPs belong to our application and the identity would remain unchanged).

Thanks in advance.

Pavithira
