### ISSUE TITLE
Production API Libilities/Payments Date Range

### ISSUE THREAD

**Issue by AndyYouens** [hmrc/vat-api#462]
Trying the production APi for the first time, but getting date range errors for both the libilities & payments endpoint.

Tried various date ranges without joy.

URL is  https://api.service.hmrc.gov.uk/organisations/vat/536497706/payments?from=2018-02-18&to=2019-02-18

Have taken out the test-scenerios needed for the testing API

Any ideas what the date range should be for production?  Nothing in the documentation????

**Comment by jacobbrownlow** [comment]
Hi Andy

I've just been trying dates in the Sandbox environment.

The `from` date must be 2017-12-01 or later.
The `to` date must be _today_ or before.
The date range must be less than 1 year.

`?from=2018-02-19&to=2019-02-18` should work. Let us know if you still have errors.

Regards, Jacob

**Comment by AndyYouens** [comment]
Ah 'date range must be less than 1 year' - that fixed it

Didnt see that in the documentation??

Is there any documentation on values/date ranges required for use in production??

Should live payments prior to MTD be retreived by the API?

**Comment by jacobbrownlow** [comment]
Hi Andy

The documentation does seem a little lacking. I will raise a ticket to get some more info included.

The date ranges used in Production are entirely up to the vendor. You should provide the dates for the time period you wish to return data for.

Any liability or payment created in MTD can be returned. For historic VAT data please contact the Software Developers Support Team SDSTeam@hmrc.gsi.gov.uk who will be able to provide information on how to best access that data.

Regards, Jacob

**Comment by AndyYouens** [comment]
Hi Jacob

In production the date range has to be one year of the current date.  Every other date fails with an invalid date

for example -> https://api.service.hmrc.gov.uk/organisations/vat/536497706/payments?from=2017-01-01&to=2019-02-19"

"status":400,"text":"{\"statusCode\":400,\"message\":\"DATE_FROM_INVALID\"}"}}

**Comment by jacobbrownlow** [comment]
Hi Andy

> the date range has to be one year of the current date

I'm not sure what this means sorry.

`from=2017-01-01` won't work because it is before 2017-12-01.
`from=2017-01-01&to=2019-02-19` won't work because it is over 1 year.

Regards, Jacob

**Comment by AndyYouens** [comment]
ah yea, apologies

**Comment by AndyYouens** [comment]
so >> The date ranges used in Production are entirely up to the vendor.

isnt correct

**Comment by jacobbrownlow** [comment]
Sorry Andy I meant that the vendor can decide what dates to use, within the rules stated.

So any range between `2017-12-01` and `today`, provided it's under 1 year in length.

Jacob

**Comment by AndyYouens** [comment]
ah got there, thanks Jacob
