### ISSUE TITLE
Fraud Headers and Access Tokens

### ISSUE THREAD

**Issue by anyolejoe** [hmrc/vat-api#464]
I understand that all HMRC APIs will require the fraud prevention headers, which is fine technically for most calls. However, when we are getting an access token using oauth/token after we get the OAuth Response following the user granting our application access on their behalf, we don't have easy access to all the client-side data we're normally passing in html headers, as the post comes from your page.

Therefore can you confirm that anti-fraud headers will never be required for this call, or are you expecting us to somehow cache the necessary values between forwarding to the oauth uri and receiving the callback?

**Comment by nickcable** [comment]
Hi, I would also like clarification please. 

Are the fraud headers just for Obligation, Liability and Payment API's or the end user authentication process as well ? There is no mention of fraud headers for the later authentication process at the following link :

https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints 

Please could HMRC clarify ?
Thanks
Nick

**Comment by hughfdjackson** [comment]
Hi @anyolejoe (and @nickcable),

You are _not_ required to send the Fraud Prevention Headers on calls to the oauth endpoints (oauth/token and oauth/authorize). 

Hope that helps!

**Comment by nickcable** [comment]
Hi @hughfdjackson , 
Many thanks, that makes sense.

Regards
Nick
