### ISSUE TITLE
VAT Scheme Verification

### ISSUE THREAD

**Issue by sonicmule** [hmrc/vat-api#465]
Just a little feedback from the experiences in supporting our customers:-
Some of our customers are not entirely sure which VAT scheme they are using when they start using our software. Or worse still, they think they are on Standard VAT but tell us months later that they are on Cash Accouting.

I know other developers will groan at this suggestion, but when submitting a VAT Return, would it be prudent to include the VAT Scheme being used and block it if there is a mismatch?

**Comment by JeeBeePee** [comment]
...as long as there is a way to retrieve the VAT scheme for a given VRN.

**Comment by jacobbrownlow** [comment]
Hi @sonicmule 

There are no plans at this time to validate the VAT Scheme on submission. We'll refer this onward for consideration.

Regards, Jacob
