### ISSUE TITLE
Improve documentation to make it clear what number types are accepted

### ISSUE THREAD

**Issue by danherd** [hmrc/vat-api#466]
* **I'm submitting a ...**
  - [ ] Bug - API
  - [x] Bug - Documentation
  - [ ] Improvement
  - [ ] Feature request
  - [ ] Support request

* **What is the current behaviour?**

Boxes 6-9 only accept whole numbers. This is unclear in the documentation.

* **What is the expected behaviour?**

The documentation should make it **very** clear that boxes 1-5 accept decimal values and boxes 6-9 **only** accept whole number values. As the documentation is aimed at developers, I think it reasonable to change the type of the value from the generic 'number' to something more representative of the accepted data - i.e. 'integer' or 'float'/'decimal'.

* **Other information** (e.g. detailed explanation, screenshots, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

This is related to #107 and #307.

![screencapture-developer-service-hmrc-gov-uk-api-do](https://user-images.githubusercontent.com/659658/53081652-2ee57e00-34f3-11e9-951d-a493484981e9.png)

**Comment by narendravijayarao** [comment]
Hi,

All these fields represents £ currency values, so they can be with and without decimals numbers (boxes 6 to 9 should only have decimal zeros). We therefore have to cater for submissions that could include either £150 or £150.00.

Thanks...

**Comment by AndyYouens** [comment]
How are the first 4 boxes allowing negative numbers?

Dont get how they can be negative, box 5 can be calcuated as negative, but can only be submitted as positive??

Very confusing!

**Comment by danherd** [comment]
> Hi,
> 
> All these fields represents £ currency values, so they can be with and without decimals numbers (boxes 6 to 9 should only have decimal zeros). We therefore have to cater for submissions that could include either £150 or £150.00.
> 
> Thanks...

That's fine, but it should be made clear that boxes 6-9 **must** be rounded to the nearest GBP - whether '.00' is appended to the end or not.

**Comment by jacobbrownlow** [comment]
Hi Andy @AndyYouens 

This is how box 5 works on the VAT return
https://www.gov.uk/guidance/how-to-fill-in-and-submit-your-vat-return-vat-notice-70012#section3
see guidance 3.6

Hi Dan @danherd 

We'll give this feedback to our technical writer and try to make it clearer.

Thanks, Jacob

**Comment by ruffle-b** [comment]
I must admit that I missed the requirement for zero pence on the first reading (the 9999999's with/without the decimal are not obvious).

It would be clearer if it said "The value must be in pounds (no pence) between 9999...".

**Comment by daniel-andrews1994** [comment]
Hi, thanks for the suggestions, we are currently amending the documentation to reflect these. I will now close this issue, please feel free to open a new one for any other suggestions or queries.
