### ISSUE TITLE
VAT API test not working in asp.net

### ISSUE THREAD

**Issue by vinodmuthoor** [hmrc/vat-api#467]
when we try to call  /organisations/vat/{vrn}/obligations  API it returns 
{ "code": "SERVER_ERROR", "message": "Service unavailable"} .please guide to fix this issue.

we are using ASP.NET MVC

if it is possible please provide .net code examples

**Comment by jonathanleather** [comment]
Hi @vinodmuthoor 

We (the API team) are happy to assist with your connection issues however we would need more information to investigate e.g. details of the full request / headers sent, times, VRNs etc.

Please note: We are unable to provide any code examples. I will put a label on this issue of "Help Wanted" and leave this issue open for now in case any of the vendor community have experienced similar issues and can assist with ASP.NET. 

Cheers
Jon

**Comment by vinodmuthoor** [comment]
hi jonathanleather 
thank you for your reply 
this is the code i am using 

string MyContent = "";            string _url = "https://test-api.service.hmrc.gov.uk/organisations/vat/653793013/obligations";            string authcode = "c2df1d8d1f68c06734e915e0bd55503c";            using (HttpClient client = new HttpClient())            {                client.BaseAddress = new Uri(_url);                client.DefaultRequestHeaders.Add("Accept", "application/vnd.hmrc.1.0+json");                client.DefaultRequestHeaders.Add("Authorization", "Bearer " + authcode);                var result = client.PostAsync("",                    new FormUrlEncodedContent(new List<KeyValuePair<string, string>>()                   {                    new KeyValuePair<string, string>("Content-Type", "application/json"),                    new KeyValuePair<string, string>("from", "2019-01-01"),                    new KeyValuePair<string, string>("to", "2019-07-10"),                    new KeyValuePair<string, string>("status", "F")                   })).Result;                if (result.IsSuccessStatusCode)                {                    string data = (result.Content.ReadAsStringAsync().Result);                    data = JsonConvert.DeserializeObject(data).ToString();                    string[] arrayResponse = data.Split(':');                    string[] arr = arrayResponse[1].Split('\"');                    MyContent = arr[1];                }                else                {                    string data = (result.Content.ReadAsStringAsync().Result);                    data = JsonConvert.DeserializeObject(data).ToString();                    string[] arrayResponse = data.Split(':');                    string[] arr = arrayResponse[1].Split('\"');                    MyContent = arr[1];                }            }        




    RESPONSE TEXT : { "code" : "MATCHING_RESOURCE_NOT_FOUND", "message" : "A resource with the name in the request can not be found in the API" }

**Comment by vinodmuthoor** [comment]
hi jonathanleather
thank you for your reply

this is the code i am using asp.net

string MyContent = "";            string _url = "https://test-api.service.hmrc.gov.uk/organisations/vat/653793013/obligations";            string authcode = "c2df1d8d1f68c06734e915e0bd55503c";            using (HttpClient client = new HttpClient())            {                client.BaseAddress = new Uri(_url);                client.DefaultRequestHeaders.Add("Accept", "application/vnd.hmrc.1.0+json");                client.DefaultRequestHeaders.Add("Authorization", "Bearer " + authcode);                var result = client.PostAsync("",                    new FormUrlEncodedContent(new List<KeyValuePair<string, string>>()                   {                    new KeyValuePair<string, string>("Content-Type", "application/json"),                    new KeyValuePair<string, string>("from", "2019-01-01"),                    new KeyValuePair<string, string>("to", "2019-07-10"),                    new KeyValuePair<string, string>("status", "F")                   })).Result;                if (result.IsSuccessStatusCode)                {                    string data = (result.Content.ReadAsStringAsync().Result);                    data = JsonConvert.DeserializeObject(data).ToString();                    string[] arrayResponse = data.Split(':');                    string[] arr = arrayResponse[1].Split('\"');                    MyContent = arr[1];                }                else                {                    string data = (result.Content.ReadAsStringAsync().Result);                    data = JsonConvert.DeserializeObject(data).ToString();                    string[] arrayResponse = data.Split(':');                    string[] arr = arrayResponse[1].Split('\"');                    MyContent = arr[1];                }            }        




    RESPONSE TEXT : { "code" : "MATCHING_RESOURCE_NOT_FOUND", "message" : "A resource with the name in the request can not be found in the API" }

**Comment by jonathanleather** [comment]
Hey @vinodmuthoor 

I can't comment on your code but the URI (separate parts of it), headers and query parameters do look correct.
Have you considered trying to hit the API using something like POSTMAN? This will allow you to see where the issue is.

I have also checked the logs - this VRN has hit the obligations API once and the submit VAT return API multiple times.

Cheers
Jon

**Comment by anyolejoe** [comment]
I think the problem might be that you're doing a POST request rather than a GET request to obligations and you should be using query string parameters rather than form encoded content.

**Comment by ma3574** [comment]
Hi @vinodmuthoor 

Hope this resolves your issue. If you require any further assistance with this specific issue please reopen. 

Kind regards
Muhammed
