### ISSUE TITLE
Net VAT Due is Negative

### ISSUE THREAD

**Issue by AndyYouens** [hmrc/vat-api#468]
Trying to submit VAT in production.

The Net VAT due is calcuated as negative.  

this throws the following error:
amount should be a monetary value (to 2 decimal places), between 0 and 99,999,999,999.99

How do we submit a negative amount?

**Comment by ruffle-b** [comment]
You don't. It's an absolute number (no minus sign).

**Comment by AndyYouens** [comment]
Daft! - Why calc boxes 3 & 5 then??

**Comment by GrahamHDawson** [comment]
Hi Andy,
I asked that way back in September - see closed issue 291.
The response was...

> @GrahamHDawson The MTD business requirement for the VAT 9 box return agreed last year and 
> delivered into the API sandbox, is that the vendor software must supply all 9 fields via the MTD VAT API, including the calculated figures in boxes 3 (totalVatDue) and 5 (netVatDue).

Graham

**Comment by jacobbrownlow** [comment]
Hi Andy

Further information on how to populate the field can be found
https://www.gov.uk/guidance/how-to-fill-in-and-submit-your-vat-return-vat-notice-70012#section3
see guidance 3.6

If you need more information on how to fill in a VAT return please contact the Software Developers Support Team on SDSTeam@hmrc.gsi.gov.uk

Regards, Jacob
