### ISSUE TITLE
Fraud Prevention Headers: Gov-Vendor-Forwarded

### ISSUE THREAD

**Issue by widley** [hmrc/vat-api#469]
* **I'm submitting a ...**
  - [ ] Support request

You are saying we need to supply the Gov-Vendor-Forwarded header when the request is tracked through our systems for fraud prevention.  We have an issue in that our ip address through our system will not be static but a range of IP addresses.  Will this be an issue?

Thanks

**Comment by hughfdjackson** [comment]
Hi @widley 

Thanks for the query.  From your question, I believe you're intending in providing multiple 'for' or 'by' addresses for a single hop, to represent the range of IP addresses the request could have come from or gone to? 

Rather than reporting the expected ranges, we expect to see the actual IP addresses involved in the specific request. Therefore we expect to see exactly one 'by' and one 'for' ip address for each hop, as the spec requests. 

> The by field must be the server’s public IP address where it received the request.
> The for field must be the requestor’s public IP address from which the vendor received the request.

I hope that helps.

**Comment by IainWardle** [comment]
Hi @hughfdjackson 

The issue is that our infrastructure is serverless so each call can be a different outgoing ip address from a range of ip addresses, we will only put 1 ip address in there as per the spec but it can be a different ip address everytime.

Thanks

**Comment by hughfdjackson** [comment]
Hi @IainWardle, 

When you say 'each call can be a different outgoing ip address', is this the call directly from your serverless workers to HMRC's API?  Or is the call going from your serverless workers to a non-HMRC service?

**Comment by IainWardle** [comment]
Hi @hughfdjackson 
Yes, our call is directly from our serverless workers to HMRC API, there are prior hops too with forwarding information on but the last hop is the serverless workers.
Thanks

**Comment by hughfdjackson** [comment]
Hi @IainWardle,

aha - reading the spec, I think I can see the source of confusion.  We *_do not_* expect you to provide a 'for' and 'by' pair for the last hop (from your servers/serverless workers direct to HMRC's APIs).  As you're experiencing, it's difficult for you as a client to give an accurate answer to that. 

I'm raising this issue internally - I think the specification itself could do with some clarification on this point.

**Comment by cb-rfk** [comment]
Hi @hughfdjackson 

I opened #461 relating to the same header and still don't fully understand what hops we should be providing details for.

We have a traditional web application with web/app servers behind the WAF.  Would you just expect to see entries for the hops between the web server and WAF?  Those are internal addresses...

Cheers,
Richard

**Comment by hughfdjackson** [comment]
Hi @cb-rfk,

we'll be getting in touch in #461 to clarify in that case too.
