### ISSUE TITLE
OS Version in Fraud Headers - query

### ISSUE THREAD

**Issue by nickcable** [hmrc/vat-api#470]
Hi, Some advice please.
I am currently building data for the fraud headers, however I am having problems formatting the info as required by HMRC. 

For example the User-Agent header I need to grab OS Family, OS Version, Device Manufacturer and Device Model info. Some of this is easy but when it comes to say OS Version it doesn't just say 'XP' like the examples given eg. :

**Gov-Client-User-Agent: Windows/XP (/)**

So how fussy is the header, could I instead use a value obtained directly from System Information  eg. 5.1.2600 which would give **Gov-Client-User-Agent: Windows/5.1.2600 (/)**

or do i really have to extract the letters 'XP' from the OS Name field 'Microsoft Windows XP Professional' as I am limited to the number of OS versions I can test this on before deploying and the formatting could be completely different on other Windows versions.

Does it matter what is sent as long it is consistent ??

Has anybody any tips on where to find the OS Version more easily ?? 

Thanks 
Nick

**Comment by GrahamHDawson** [comment]
Hi Nick,
For our desktop application I'm using two calls to WMIC to get the information eg
To get the Name 
wmic /output:stdout os get Caption

Outputs...
Caption
Microsoft Windows 8.1

To get the Version
wmic /output:stdout os get Version

Outputs...
Version
6.3.9600

In both cases it retrieves two lines of data and I split them and parse out the bits I need.
I send 'Microsoft Windows 8.1/6.3'

Of course whether that's correct or not is anyone's guess, given that the headers aren't validated in the sandbox environment.

Graham

**Comment by nickcable** [comment]
Thanks @GrahamHDawson for the information. It certainly is NOT clear what HMRC are expecting us to send. It would have been helpful if the format required exactly matched what we can retrieve from the OS in the first place without us having to guess what might be accepted !

Also, I would like to know if we should be sending the fraud headers for the Oauth user API's as well as for obligations,liabilities and payments etc.

Perhaps HMRC could comment on this please ??

Thanks again,
Nick

**Comment by nickcable** [comment]
@hughfdjackson Please could you confirm whether the fraud headers are required for the Oauth API's ?? We need to know quite quickly before we start deploying to customer sites.
Many thanks
Nick

**Comment by hughfdjackson** [comment]
Hi @nickcable: 

> So how fussy is the header, could I instead use a value obtained directly from System Information eg. 5.1.2600 which would give **Gov-Client-User-Agent: Windows/5.1.2600 (/) or do i really have to extract the letters 'XP' from the OS Name field 'Microsoft Windows XP Professional' as I am limited to the number of OS versions I can test this on before deploying and the formatting could be completely different on other Windows versions.

**Gov-Client-User-Agent: Windows/5.1.2600 (/)** is acceptable to us.  Thanks for the question! :)

**Comment by hughfdjackson** [comment]
> @hughfdjackson Please could you confirm whether the fraud headers are required for the Oauth API's ?? We need to know quite quickly before we start deploying to customer sites.
> Many thanks
> Nick

I believe this issue is being addressed as part of https://github.com/hmrc/vat-api/issues/464.  Please see the replies.
