### ISSUE TITLE
Testing VAT Libilities API in the sandbox

### ISSUE THREAD

**Issue by Robbrom** [hmrc/vat-api#472]
I'm testing against the VAT Liabilities API in the sandbox and calling:
https://test-api.service.hmrc.gov.uk/organisations/vat/875140814/liabilities?from=2017-04-05&to=2017-12-21

The to/from dates are taken form the MULTIPLE_LIABILITES section on:
https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0#_retrieve-vat-liabilities_get_accordion

The response is:
{"code":"NOT_FOUND","message":"The remote endpoint has indicated that no data can be found"}

What's wrong?

* **I'm submitting a ...**
  - [ ] Bug - API
  - [ ] Bug - Documentation
  - [ ] Improvement
  - [ ] Feature request
  - [x] Support request

**Comment by jonathanleather** [comment]
Hey @Robbrom 

Are you passing in the MULTIPLE_LIABILITES gov-test-scenario header along with your request?
The payments and liabilities endpoints depend on these headers for testing in the sandbox.

Cheers
Jon

**Comment by Robbrom** [comment]
Thanks for the advice.
Adding the header "Gov-Test-Scenario: MULTIPLE_LIABILITIES" produced a response with data but this leads me to a subsidiary question:
Can you only get a response when either the header MULTIPLE_LIABILITIES or SINGLE_LIABILITY are used with the to/from dates specified in the documentation or can you specify any range of dates and get a canned response back?

**Comment by jonathanleather** [comment]
Hey @Robbrom 

You do always need to supply one of the gov-test-scenarios for this endpoint in the sandbox.
You can however manipulate the dates to return a smaller or larger subset of that data (or none at all).

For example, when using MULTIPLE_LIABILITIES-
If you supply the following dates: /liabilities?from=2017-04-05&to=2017-04-06
You would only be returned 1 Liability. 

If you expanded the dates to /liabilities?from=2017-04-05&to=2017-04-30
You would be returned 2 liabilities.

The filtering is done on the taxPeriod To date.

Cheers
Jon

**Comment by Robbrom** [comment]
Thanks, appreciate it (especially as it's a Friday afternoon!)
I'll close this thread and go and update my test documentation.
