### ISSUE TITLE
cannot submit negative value in netvalue field

### ISSUE THREAD

**Issue by brucemcmillan** [hmrc/vat-api#477]
**Note: Please read before raising an issue**. This repository's issues are reserved for **Technical** queries relating to the VAT-API Only. 
If your issue falls into any of the below categories please contact SDST at SDSTeam@hmrc.gsi.gov.uk:
- Issues relating to subscribing/registering to use the API Platform, MTD enrolment / de enrolment  / registration for VAT / BETA etc
- Issues relating to OAuth2
- Issues relating to integrating with the API Platform (setting up an application/access)
- Vendor application software questions (code examples in .NET / VB6 etc.)
- Business related questions
- Scheduled maintenance days / windows
- Onboarding 
- Performance metrics
- Questions relating to the process pre MTD

When submitting an issue please try to provide the following information:

* **I'm submitting a ...**
  - [X] Bug - API
  - [ ] Bug - Documentation
  - [ ] Improvement
  - [ ] Feature request
  - [ ] Support request

* **What is the current behaviour?**

cannot submit negative value to in netValue field when submitting VAT return

The following values cause an error

VAT Due Sales |   | 3066.34 |
VAT Due Acquisitions |   | 4870.46 | 
Total VAT Due |   | 7936.8 | 
VAT Reclaimed Current Period |   | 8492.63 | 
Net VAT Due |   | -555.83 | 
Total Value Sales Ex VAT |   | 98131.78 | 
Total Value Purchases Ex VAT |   | 120343.24 | 
Total Value Goods Supplied Ex VAT |   | 52204.52 | 
Total Acquisitions Ex VAT |   | 24352.24 | 

* **What is the expected behaviour?**

should be able to submit -ve value as per written form

* **Other information** (e.g. detailed explanation, screenshots, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Find answers to common questions [here](https://github.com/hmrc/vat-api/wiki/FAQ)

**Comment by MarkAKelly** [comment]
Hi Bruce,

Please see threads #468 and #291 relating to this issue.  The documentation states that NetVatDue should be a positive number, and existing VAT guidance instructs users that this is an absolute value.

I will look at adding something to the documentation to make this clearer.

Thanks,

Mark

**Comment by maxigit** [comment]
I stumble the same problem today. It is indeed clear on the VAT guidance instructions, but it is not clear at all on the API documentation stating 

> The difference between totalVatDue and vatReclaimedCurrPeriod. This corresponds to box 5 on the VAT Return form. The value must be between 0.00 and 99999999999.99

In fact, in is more than not clear, it is contradicting the VAT guidance telling to take the absolute value.
I think is should be clearly stated in the API, otherwise, as it is can be seen as a corner case, people will just discover the bug live in production.
