### ISSUE TITLE
mulitple fields report wrong error message in validation

### ISSUE THREAD

**Issue by brucemcmillan** [hmrc/vat-api#478]
**Note: Please read before raising an issue**. This repository's issues are reserved for **Technical** queries relating to the VAT-API Only. 
If your issue falls into any of the below categories please contact SDST at SDSTeam@hmrc.gsi.gov.uk:
- Issues relating to subscribing/registering to use the API Platform, MTD enrolment / de enrolment  / registration for VAT / BETA etc
- Issues relating to OAuth2
- Issues relating to integrating with the API Platform (setting up an application/access)
- Vendor application software questions (code examples in .NET / VB6 etc.)
- Business related questions
- Scheduled maintenance days / windows
- Onboarding 
- Performance metrics
- Questions relating to the process pre MTD

When submitting an issue please try to provide the following information:

* **I'm submitting a ...**
  - [ X] Bug - API
  - [ ] Bug - Documentation
  - [ ] Improvement
  - [ ] Feature request
  - [ ] Support request

* **What is the current behaviour?**

the following fields report value out of range when submitting values with decimal places

  "totalValueSalesExVAT":
  "totalValuePurchasesExVAT":
  "totalValueGoodsSuppliedExVAT": 
  "totalAcquisitionsExVAT": 

The following values cause an error

VAT Due Sales |   | 3066.34 |
VAT Due Acquisitions |   | 4870.46 | 
Total VAT Due |   | 7936.8 | 
VAT Reclaimed Current Period |   | 8492.63 | 
Net VAT Due |   | -555.83 | 
Total Value Sales Ex VAT |   | 98131.78 | 
Total Value Purchases Ex VAT |   | 120343.24 | 
Total Value Goods Supplied Ex VAT |   | 52204.52 | 
Total Acquisitions Ex VAT |   | 24352.24 | 

API reports values should be between -999999 and 9999999

* **What is the expected behaviour?**

either the API should accept  decimal places or / and  the error messages in the response node need to be updated

* **Other information** (e.g. detailed explanation, screenshots, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Find answers to common questions [here](https://github.com/hmrc/vat-api/wiki/FAQ)

**Comment by MarkAKelly** [comment]
Hi again @brucemcmillan,

The API documentation originally matched the error message returned from the API - that we only accept integer values within the range of -9999999999999 and 9999999999999.

Some vendors found this problematic, as their software submitted values as currency and whole currency values were prepended with `.00`, so we modified the API to accept values with decimal 0's.  The business rules for these fields however still apply - they should be whole number values with no 'pence', but we accept these represented with decimalised 0's.

If we were to improve the documentation, what would make this clearer for you?  We are constantly looking to improve the documentation so if you have feedback please let us know so we can pass it on our content designers.

Thanks,

Mark

**Comment by brucemcmillan** [comment]
Hi,

All we are looking for is consistency.. If the API can accept decimal values of pounds and pence then if should not error.

If the  API cannot accept decimal values then the error should be along the lines of "parameter XXX must be an integer value. and have no decimal places" - I believe that there is  one value that is submitted that does check for this type of value.

If the value is less than -99999999999 or greater than 9999999999 then it should the respond with that message.

This should take into account what the user is going to submit in the real world. If they have a calculation that returns a two decimal place result that they would manually declare on a return then the aPI should / must be able to accept that same type of value

**Comment by MarkAKelly** [comment]
Hi @brucemcmillan,

Our documentation states that boxes 1 to 4 can be -9999999999999.99 and 9999999999999.99.  Box 5 (netVatDue) must be between 0 and 9999999999999.99.  

The remaining fields must be integers.  The documentation in the specification states the following `The value must be in pounds (no pence) between -9999999999999 and 9999999999999.`.  Would you like this detail in the error response as well as in the specification for these fields?

Cheers,

Mark

**Comment by brucemcmillan** [comment]
Hi,

Please., the error message should reflect the error :-)  

Rgds...

B....
