### ISSUE TITLE
Problems with Authorising and 403 Error

### ISSUE THREAD

**Issue by aaronmowla** [hmrc/vat-api#479]
Using Visual Basic 2017 with chilkat
I have successfully requested and received an OAuth2 Code, and then try to use it to submit a dummy VAT Return.
I only receive 403 errors when doing this, and am sure I am doing it correctly!?! Can anyone help.
Here is my subroutine code:

    Private Sub Button9_Click(sender As Object, e As EventArgs) Handles Button9.Click
        Unbundle_Chilkat()
        Dim rest As New Chilkat.Rest
        Dim status As Long

        '  URL: https://test-api.service.hmrc.gov.uk/organisations/vat/MY_HMRC_VRN/returns

        status = rest.Connect("test-api.service.hmrc.gov.uk", 443, True, True)

        'Error trap if connection fails
        If (status <> True) Then
            MsgBox("ConnectFailReason: " & rest.ConnectFailReason & vbCr & rest.LastErrorText,, "A")
            Exit Sub
        End If

        '  See the Online Tool for Generating JSON Creation Code
        Dim json As New Chilkat.JsonObject
        status = json.UpdateString("periodKey", "A001")
        status = json.UpdateNumber("vatDueSales", "105.50")
        status = json.UpdateNumber("vatDueAcquisitions", "-100.45")
        status = json.UpdateNumber("totalVatDue", "5.05")
        status = json.UpdateNumber("vatReclaimedCurrPeriod", "105.15")
        status = json.UpdateNumber("netVatDue", "100.10")
        status = json.UpdateNumber("totalValueSalesExVAT", "300")
        status = json.UpdateNumber("totalValuePurchasesExVAT", "300")
        status = json.UpdateNumber("totalValueGoodsSuppliedExVAT", "3000")
        status = json.UpdateNumber("totalAcquisitionsExVAT", "3000")
        status = json.UpdateBool("finalised", 1)

        status = rest.AddHeader("Content-Type", "application/json")
        status = rest.AddHeader("Authorization", "Bearer " & authcode)
        status = rest.AddHeader("Accept", "application/vnd.hmrc.1.0+json")

        Dim sbRequestBody As New Chilkat.StringBuilder
        status = json.EmitSb(sbRequestBody)
        Dim sbResponseBody As New Chilkat.StringBuilder
        status = rest.FullRequestSb("POST", "/organisations/vat/984539565/returns", sbRequestBody, sbResponseBody)
        If (status <> 1) Then
            MsgBox(rest.LastErrorText)
            Exit Sub
        End If

        Dim respStatusCode As Long
        respStatusCode = rest.ResponseStatusCode
        If (respStatusCode >= 400) Then
            MsgBox("Response Status Code = " & respStatusCode)
            MsgBox("Response Header:")
            MsgBox(rest.ResponseHeader)
            MsgBox("Response Body:")
            MsgBox(sbResponseBody.GetAsString())
            Exit Sub
        End If

        Dim jsonResponse As New Chilkat.JsonObject
        status = jsonResponse.LoadSb(sbResponseBody)

        '  See the Online Tool for Generating JSON Parse Code
        Dim processingDate As String
        Dim paymentIndicator As String
        Dim formBundleNumber As String

        processingDate = jsonResponse.StringOf("processingDate")
        paymentIndicator = jsonResponse.StringOf("paymentIndicator")
        formBundleNumber = jsonResponse.StringOf("formBundleNumber")
    End Sub

**Comment by GrahamHDawson** [comment]
You say 'I have successfully requested and received an OAuth2 Code' .
Have you exchanged the authorisation code for an Access Token ?

It's the Access Token that needs to be submitted, and that Access Token needs to have at least read:vat scope (you can request read:vat+write:vat when you exchange the authorisation code for an Access Token)

**Comment by aaronmowla** [comment]
Hello Graham, thanks so much for the advice. I am actually working on it now, and I seem to have spotted a bit of a glaring error on my part... I was requesting a new test user in the API using the ServerToken given by HMRC. What I did not appreciate was that every time they issue a new test user they also issue a brand new VAT number to go along with it, and so I think the issue may be that I am using a valid OAuth2 Access Token generated from the test user, but I have not updated the VAT number on my calls to reflect the change in this number! I'll report back via the thread if this proves to be the case. Thanks again - Aaron
