### ISSUE TITLE
400 Bad Request  on oAuth Token Endpoint

### ISSUE THREAD

**Issue by faizanaliasghar** [hmrc/vat-api#483]
Hi,

I am trying to develop an application for MTD API using Angular 7. I am trying to get a token on the sandbox for the vat api. I can get the code from the api endpoint: https://test-api.service.hmrc.gov.uk/oauth/authorize but when I try to get the token using the code received I get 400 Bad Request error given below. I have tried different different browsers and changing the Content-Type header but nothing seems to work. The request I am sending is also given below. Can you please check to see what the issue is?

**Error Response:**
message: "Http failure response for https://test-api.service.hmrc.gov.uk/oauth/token: 0 Unknown Error"
name: "HttpErrorResponse"
ok: false
status: 0
statusText: "Unknown Error"  

**Request:**

**Headers**

Provisional headers are shown
Accept: application/json, text/plain, */*
Content-Type: application/x-www-form-urlencoded
Origin: http://localhost:8080
Referer: http://localhost:8080/?code=xxxxxxx&state=xxxxxxx
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36

**Data:**

grant_type=authorization_code&code=xxxxxxxxxxxxx&redirect_uri=http://localhost:8080&client_id=xxxxxxxxxxxxx&client_secret=xxxxxxxxxxx

**Token Url:**
https://test-api.service.hmrc.gov.uk/oauth/token

**Comment by faizanaliasghar** [comment]
Hey,

more update on this. If I try to send a request with Content-Type set to 'application/json' the OPTION call fails with a 404. It even fails when I try it from Postman using the same details. The POST call succeeds in Postman but in my angular application the post call is not made as the OPTION call fails.

**Comment by daniel-andrews1994** [comment]
Hi
As this is an OAuth issue the best way to solve this would be to contact SDST. From having a quick look at this, the problem may be that the redirect uri needs encoding, have a look at the link below for more information.

https://developer.service.hmrc.gov.uk/api-documentation/docs/reference-guide#redirect-uris

Thanks,
Daniel

**Comment by faizanaliasghar** [comment]
Dont think its an issue with redirect_uri encoding as I can use the same url in postman successfully when using Content-Type: application/json and method POST. The issue seems to be that the OPTIONS call is failing. I have already contacted SDST but still waiting for their reply. Is there anything I can do in the meantime to help resolve the problem?

**Comment by jibranishtiaq** [comment]
Hi @faizanaliasghar ,
I am getting the same error on authorisation token end point.
You able to resolve the issue, if yes can you please share with me how you resolved it.
Just for reference I encode the redirect uri.

**Comment by faizanaliasghar** [comment]
I had to run chrome with web security disabled to allow the browser to send the response back to my angular spa. The issue seems to be due to X-Permitted-Cross-Domain-Policies header is set to master-only in the response message and I dont think my redirect url http://localhost:8080 is added as a allowed host on the server.

**Comment by ma3574** [comment]
Hi 

I hope you were able to resolve your issue. If there are still issues around the OAuth flow please get in touch with the SDS Team at SDSTeam@hmrc.gov.uk *please note the change in email address*. Our team deals with the VAT API and is unable to assist in regards to OAuth hence If there are continuing issues please contact the email address provided.
