### ISSUE TITLE
Code Versions

### ISSUE THREAD

**Issue by AndyYouens** [hmrc/vat-api#484]
Hi all

A general question this time for all the developers.

How do you all keep control of versions going forward with the MTD API?

We had to hard code so many variables to get through the sandbox testing & getting approval from HMRC.  We had to hard code dates, test scenerios etc etc and now need to remove all these when using in production. 

So we now have development versions & production versions.

How are you all keeping up with not being able to have identical test & production versions?

**Comment by nickcable** [comment]
Hi @AndyYouens we just have the one version and implemented a series of switches to control whether the application is in Test mode or Live mode and use of gov-test-headers etc. We never had to hard code dates as you can just pick these up from the obligations and work with them.
Cheers
Nick

**Comment by GrahamHDawson** [comment]
We just have a single version with a global setting determining whether it's being run in testing or production mode.
That global variable then is used in IF statements to set which URL to use, whether to display the testing menus (create test user etc etc), whether to display the testing scenarios etc etc

Far easier than maintaining 2 separate versions IMHO

**Comment by adamdavi3s** [comment]
Yeah we have a single version now, we did have two but it was MUCH easier to implement a switch based on the URL the user has chosen in our case!
We did hard code dates and test scenarios but we just wrap these in an if(istest){} statement to only pick them up when we need to.
