### ISSUE TITLE
Possible causes for 404 NOT_FOUND response to Retrieve Obligations

### ISSUE THREAD

**Issue by sjjeffery** [hmrc/vat-api#485]
A customer has signed up to MTD earlier this week and received confirmation that they're registered. 
They submitted their last XML return (for November/December/January) on February 25th.
They've authorised our software to access their data using OAuth, but on attempting to Retrieve VAT Obligations the API returns 404 NOT_FOUND.
What are the possible causes for this?
The date range I pass as standard is for the past year in order to catch everything, so today's date less 365 days, up to today, however this has worked fine for other customers so I don't imagine that's relevant.

**Comment by nickcable** [comment]
I had the same problem in the test sandbox with 365 days but 364 days seemed to work ?!

**Comment by sjjeffery** [comment]
I'll have to cook up a beta version for the customer to test that, which isn't a job for a Friday night. 
If the date range is bad, I'd have thought 400 INVALID_DATE_RANGE would be a more suitable response.

**Comment by rosco1974** [comment]
We have signed up a client to use the Pilot MTD scheme as well last week and we too are unable to retrieve any open obligations even though they submitted a VAT quarter on 1 Nov to 31 Jan.  I'd have thought the new quarter would show after 1st Feb.

"The remote endpoint has indicated that no data can be found" is the error message we receive.  Also when you go onto the VAT website for client, it also shows no return periods available.

Viewing old returns, does show the quarters submitted but when you view details on the new website, it says page not found.

![image](https://user-images.githubusercontent.com/48205990/53729180-71e90f00-3e6c-11e9-957d-d3738c5796fd.png)

**Comment by sjjeffery** [comment]
Did you get anywhere with this? Our client is seeing the same thing on the VAT website. It's like there's a disconnect between VAT returns submitted pre-MTD and anything going forward.
In the absence of any official response here I dropped an email to SDSTeam and got the following,

> A 404 error can be generated when a call is made to an endpoint for which there is no MTD data.  This can occur for example when a Liabilities call is made when no Liability has been created since entering MTD or an obligation call is made for a date parameter prior to entering MTD.

If the issue is with the date range being outside permitted or valid ranges then those ranges need to be more rigorously defined as the API definition just refers to start and end date with no stated restrictions. This would be the first I've heard of any issue with entering a date prior to the customer starting MTD.

Also
> this issue is most likely related to the individual VAT entity & whether they are correctly set up for MTD.

which is something SDSTeam can't check, apparently.

**Comment by rosco1974** [comment]
Hi,

Thanks for the update, we are able to retrieve "closed" VAT obligations but when we view the submission using the period key provided, we get the 404 error.  The test environment, we had no issue with viewing VAT submissions.  Unfortunately, no further forward.  

We helped our customer sign up to the pilot and they received an email that they had access to MTD.  I know with another client who is willing to do the pilot, you will receive client/agent not authorised error.

So who can we ask to check the customer is set up correctly?

**Comment by GrahamHDawson** [comment]
As I understand it the MTD endpoints will only return MTD data.
(it's in the documentation somewhere :-) )

So viewing the returns via MTD will only show returns submitted via MTD - so for new users that endpoint won't (or shouldn't) return anything.

As for the Obligations - I don't think we've ever been told when these appear.
I seem to remember seeing a statement saying you don't get forward Obligations retrieved
ie you won't see a full years Obligations as soon as you register for MTD

Returns cannot be submitted for VAT periods that haven't closed - so it probably makes sense not to display Obligations for a period too early.

We could do with official answers on these points though.

**Comment by sjjeffery** [comment]
Yes, our issue is with retrieving obligations via the API, not with viewing submissions. The customer's issues with viewing returns on the website suggests to me that all is not entirely as it should be behind the scenes.

As you say, some official response would be useful. If "that's just the way it works" I can modify our software to cope.

**Comment by markogrady** [comment]
I have had the same issue in the last few days which I have never had before and I have had over a hundred users go live. I have tried using both the status and multiple date ranges

One of them seemed to resolve itself . I think there must be a delay with a system that creates the new obligations.

I have messaged support.

**Comment by JeeBeePee** [comment]
> Thanks for the update, we are able to retrieve "closed" VAT obligations but when we view the submission using the period key provided, we get the 404 error.

Also seeing this behaviour with only one user. Additionally, when querying for open obligations, the endpoint returns an obligation that has actually been fulfilled and can be retrieved from the returns endpoint, so the user is left thinking that their return has not been filed.

Emailed SDS, no response in over 24 hours.

**Comment by JeeBeePee** [comment]
I now have three users experiencing this issue. Could someone from SDS team respond?  Customers report poor experience contacting the MTD Helpdesk.

**Comment by mtd-api-team** [comment]
Hopefully your issue is resolved. If it is still persisting please contact the SDS Team again and chase it up (SDSTeam@hmrc.gov.uk). The MTD-API-Team are not able to assist with live support issues due to not having access to the data in question. Please note that the SDS Team do not actively monitor this repository for issues; hence there will be no reply from them here. Please use the email provided in order to get in touch with them.

**Comment by mathiasbanda** [comment]
Some of our customers are getting this even when they have successfully submitted a vat return in the past. This happening when they try to get obligations in the current vat period. Is this because the server is busy at the moment ?
