### ISSUE TITLE
Fraud Prevention - Gov-Client-Local-IPs header - Clarification Needed

### ISSUE THREAD

**Issue by sonicmule** [hmrc/vat-api#487]
I'm looking for a little clarification on the Gov-Client-Local-IPs header.

Our app is a Windows desktop app, so we need to provide this header.
The documentation states:
_A list of all local IP addresses (IPv4 and IPv6) available to the originating device. If local device IP addresses cannot be discovered – for example, through a web browser due to permissions or lack of WebRTC – then submit the header with an empty value or omit it entirely._ 

Am I right in thinking that this is all the other IP addresses available on the users network?

This could be huge! - Run the command _netsh int ipv6 show neighbors_  on a Windows network to see what I mean.  Is there a maximum header size we can submit?

Also, how will this help in fraud protection?
If a user accesses the VAT APIs at work, there will be one list of addresses.
Then they access the VAT APIs at home, there will be another list of addresses.
Does this trigger a fraud event?

Also, if the network is using DHCP, devices will come and go, so the list could change every time.

If the customer's ISP does not support IPv6, then you'll just get a list of 192.168.100.xxx - nearly everyone uses this IPv4 range on their local netowrk.

I think this needs some more examples here, otherwise we could be sending very large headers with every request.

**Comment by sjjeffery** [comment]
My understanding of that wording was that they want IP addresses assigned to the current device, e.g. those reported by 'ipconfig'. I agree that expecting all those addresses accessible by the current device would be excessive.

**Comment by dsrobinson** [comment]
@sonicmule - @sjjeffery is correct. We don't expect you to provide all the IP addresses in your local area network.

**Comment by paulfeakins** [comment]
"they want IP addresses assigned to the current device, e.g. those reported by 'ipconfig'."
Ok but how can you get those from a web browser?

**Comment by ys00065** [comment]
did anyone manage to get ip addresses from web browser?
