### ISSUE TITLE
When refresh token expires after 18 months what response do we get

### ISSUE THREAD

**Issue by JohnAherne** [hmrc/vat-api#488]
I have not found any information about the response we can expect when the refresh token has expired after 18 months and we try to refresh the token.

At this point we should go through the authentication process again.

It would be good to know what response we should be expecting so it makes it easier to work out what to do.

Thanks for any info

**Comment by cb-rfk** [comment]
Hi @JohnAherne ,

Don't know if we are doing this right or not, but our approach is to:
a) see if we have a token for the user
b) if we do, test if it is still valid
c) if not valid, try and refresh it
d) if we can't refresh it for any reason (or we never had one), re-authenticate

Also look forward to hearing what others are doing.

**Comment by JohnAherne** [comment]
OK. Found it in the reference guide.
The response is INVALID_CREDENTIALS

when you do the following request:


Invalid OAuth token supplied for user-restricted or application-restricted endpoint (including expired token)
