### ISSUE TITLE
Fraud Prevention Header: Gov-Client-Public-IP, Gov-Client-Public-Port Clarification Needed

### ISSUE THREAD

**Issue by likedustg** [hmrc/vat-api#493]
Hi,

Our architecture is DESKTOP_APP_VIA_SERVER. The desktop app on a computer inside intranet submits the VAT report to a server which is also inside the intranet. Then the server forwards the report to HMRC. Then in this case, should Gov-Client-Public-IP be the computer's (where the desktop app is running) public IP? 

Should it be the IP address shown when visiting http://ip4.me/ (or other websites providing similar service)? Do you have list of websites how this public IP should be got? How can I get my public port then?

Can I just leave these fields empty? 
thank you.

**Comment by konradwudkowski** [comment]
hi @likedustg 

in this case please omit the following headers or submit them with an empty value: `Gov-Client-Public-IP`, `Gov-Client-Public-Port`, `Gov-Vendor-Public-IP`. We expect to see `Gov-Vendor-Forwarded` populated with any other hops directly over the internet, but we do not expect to see the one made over local network.
