### ISSUE TITLE
Access HMRC via iframe

### ISSUE THREAD

**Issue by justinkelly** [hmrc/vat-api#496]
Hi HMRC,

Our accounting app is used in an iframe in the parent apps browser window
When the user tries to login to HMRC (in the accounting apps iframe) we get a `test-www.tax.service.gov.uk refused to connect.` error message

I am assuming this comes from the `X-Frame-Options: SAMEORIGIN` policy on test-www.tax.service.gov.uk 

Please can you let me know if its possible to log into HMRC via an iframe in our parent app
- or if there are workarounds

Cheers

Justin

**Comment by adamdavi3s** [comment]
I had this same problem although I swear it worked at one point!
I had to go with providing a link to open a new window rather than opening it within an iframe

**Comment by justinkelly** [comment]
@adamdavi3s thanks - ive emailed hmrc team as well - will post hear if there is a solution

**Comment by farjadab** [comment]
I have the same problem.

**Comment by justinkelly** [comment]
I haven't heard back from the HMRC - so have to do a work-arournd and break the app out of the iframe and into a new tab - for the HMRC login

once the user logs into HMRC in the new tab - they can close the tab and back in the original tab they will be logged in correctly within the iframe

not the best but only thing that can be done - at the moment

**Comment by justinkelly** [comment]
HMRC got back to me and said the user should be"directed out of the software package"

i take that they wont support in iframe auth

will close this issue now
