### ISSUE TITLE
HMRC MTD contact

### ISSUE THREAD

**Issue by mathiasbanda** [hmrc/vat-api#497]
One of our customers is getting a 'denied authorization' error when they try to first authorize our application for MTD. I just asked them to call HMRC seeing there isn't much else I think we can do.

Is there a dedicated MTD number for the end user or not?

Thanks

Mathias

**Comment by james-work-account** [comment]
Hi @mathiasbanda - you will need to contact the Software Developers Support Team to take this further. Please contact them at SDSTeam@hmrc.gov.uk.

Thanks,
James
