### ISSUE TITLE
What next after creating a test agent?

### ISSUE THREAD

**Issue by PeterGGreen** [hmrc/vat-api#498]
OK, I've created a test agent, and a test organisation.  I "expected" to be able to log in to HMRC sandbox with a browser (not our MTD product), as the agent, enter the VRN of the test organisation to send a link request (think Facebook friend request).  Then log into the HMRC sandbox as the test organisation, confirm (or deny) the agent link and then submit the MTD VAT figures as usual, except that this time I would log in to our MTD VAT product as the agent, submitting VAT for the organisation VRN.

However, after creating the 2 users as above, I can find no link or URL to continue?

If it's not as simple as I've described above, I have 2 further questions:

a) why isn't it as simple as I've described?
b) how do I link the test agent and test organisation together?

**Comment by cb-rfk** [comment]
As far as I've determined, it's simply not possible to do this on the sandbox test system - one of its many limitations!

We have developed and tested our solution by creating ad-hoc agent and organisation users and testing them in isolation on the assumption that the linking process will all work once we move to production.

Obviously once we move to production we can't test that either as we a re just the software company and don't have access to organisation or agent accounts of our own!

Anyway, hoping to do product demo on Monday so will update the post if I hear anything relevant.

**Comment by mathiasbanda** [comment]
@cb-rfk spot on

**Comment by markogrady** [comment]
I couldn't test it either, so I just did it in production. With agent it
just gives you a token that can be used against any of their VRNs.

**Comment by jacobbrownlow** [comment]
Apologies for the late reply

We are not aware of a way to test agents in Sandbox at present. As you have said, the create an agent API does not create the relationship between an Agent and a Client.

We are continuing to push for this capability but unfortunately can't guarantee if and when it will be available. We'll be sure to update you if we find out anything though.

Jacob

**Comment by ddaddy** [comment]
I was just looking for this same information this morning. I have my application complete for Individuals and Organisations but don't know the best way to implement Agent use.

I'm thinking it will work like this:
Agent logs into HMRC just like any other user to grant authority to the application.
The agent doesn't have a VRN registered, so the agent must enter individual VRN's of companies/individuals they represent into the application.
The application can fetch obligations and submit returns using the agents authorisation token and the users VRN.

This should just work as it does with any individual/organisation, but there is no way to test any of it, apart from the Agents login works.

Please correct me if I am wrong.
Thanks

**Comment by cb-rfk** [comment]
@ddaddy 

Yes, that's more or less what we have done.

We have a screen in our system with customer details, one bit of which is their VRN, so when the agent logs in, they select which customer they are working with and the VRN is pulled from their records and used in the api calls.

Then you just go for it and either your calls with the agent bearer token will work or they will return an "unauthorised" error...

Have you seen the documentation on how the Agent gets the user/organisation to sign up to MTD and delegate access? It's in several of the HMRC customer journey documents and you might need to refer to those when designing release notes/user guides for both types of the end users.

Richard

**Comment by PeterGGreen** [comment]
I also received this reply from the SDST.

--------------------------------------------------
The process to test the API is as follows:

Create test agent user
Create test user API
Use the ‘Create a new authorisation’ endpoint
Use the ‘Get an invitation by ID’  to generate the URL for the client to accept
Login to the Agent Services UI as the client and accept or reject the invitation
You can also cancel or check status of a relationship
 
Hope this helps.
--------------------------------------------------

So perhaps we're a step closer.

Peter

**Comment by PeterGGreen** [comment]
I haven't had the time to try this yet as I means developing an interface for the new endpoint, but I'd like to hear if anyone manages to get this working...

Peter

**Comment by cb-rfk** [comment]
@PeterGGreen 

Oh, thanks for that - hadn't seen there was a new api!

Anyone else get the feeling that keeping up with the MTD requirements is going to be a full-time ongoing job!

**Comment by ddaddy** [comment]
Thanks @cb-rfk I missed all documentation on agents as it was a bit of an afterthought/oversight. I’ll go back and have a re-read.

@PeterGGreen are you saying to use the Agent Authorisation Online XML API?
It specifically says ‘This API is not part of the Making Tax Digital initiative’ 🤔

**Comment by PeterGGreen** [comment]
@ddaddy I'm not saying anything, I've just posted HMRC's response to my email.  I simply haven't had the time to have a look at testing this and thought the information may be useful...

Peter

**Comment by ddaddy** [comment]
@PeterGGreen Sorry, I hope you don't think I was being rude. Thank you for the information.

@cb-rfk I'm not sure it's a new API, the API documentation was published in 2013 and makes no mention of VAT.

**Comment by ddaddy** [comment]
Looking at the `/create-test-user/services` endpoint (Get available services), it returns MTD VAT `allowedUserTypes` as only `INDIVIDUAL` & `ORGANISATION`, not `AGENT`.
Creating a test agent user and attempting to log in gives the notice `You cannot access client data at the moment
Agents are currently not able to authorise software applications to act on their client's behalf.

This will become available at a later date.`

![Screenshot 2019-03-15 at 13 20 49](https://user-images.githubusercontent.com/1425808/54434034-316b7a00-4725-11e9-94fa-299e97242b5e.png)

So i'm totally unclear as to whether this is just disabled for the sandbox, or live too 😕

**Comment by PeterGGreen** [comment]
Good job testing it.

I worry about the future direction we're heading in with the new team at HMRC.  Whatever happened to multiple test avenues?  Where are the replacements for VSIPS and LTS?  Why can't we Test in live (never going to happen apparently), even though it's the simplest thing in the world to simply discard the submission instead of posting it to their records (if so marked).

**Comment by ddaddy** [comment]
I got a response today from SDST which seems to contradict what @PeterGGreen was told but seems to be more accurate:

> Whilst the Sandbox environment may support this function for other API’s it does not support testing on behalf as an agent for the VAT (MTD) API. The main reason being the agent journey is identical to the user journey, the only difference being HMRC’s back end goes through the process of checking if the agent has the rights to submit on behalf of a user.
>  
> You need to create a test user who is an organisation.

So basically there is no need to test as an agent as it's no different to an organisation. (My testing also shows Individual user is exactly the same journey as Organisation).

**Comment by mathiasbanda** [comment]
Only if it was really identical then agents could be factorized out of the equation. The issue not to ignore about agents is how a single 'agent' access token is linked to more than one vrn. If you are an agent and 50 of your customers are using the same package then a single authorization is enough. (or let me say should be enough).

**Comment by mtd-api-team** [comment]
Hi all, if you have any further queries please refer to https://github.com/hmrc/vat-api/issues/565.

**Comment by mtd-api-team** [comment]
Hi all

We have created our own internal guide for creating a test agent in the sandbox. This guide is not designed to cover the entire oauth flow but instead gives enough detail to show the necessary steps to create an agent.

Please find it on our wiki
https://github.com/hmrc/vat-api/wiki/Creating-Test-Agents-in-the-Sandbox

Regards
The MTD-API Team
