### ISSUE TITLE
Query regarding format of VRN

### ISSUE THREAD

**Issue by seurrep** [hmrc/vat-api#500]
I need something clarified: we have encountered cases where customers have been provided with VRNs that begin with 'GB'. Passing these VRNs to the API however results in 400 being returned. Presumably the value with the GB is strictly speaking valid as it was what was provided by HMRC to the customer.

Is a value that starts with GB then is followed with the usual 9 numbers still valid for the purposes of API calls? Or does any prefix need to be stripped from the VRN before passing it across in any call to your API end points?

**Comment by daniel-andrews1994** [comment]
Hi,
The 'GB' will need to be stripped from the VRN before calling our endpoints. The standard UK VRN is composed of 9 digits and is currently the only format we accept.

Thanks,
Daniel

**Comment by seurrep** [comment]
Thanks for the information.
