### ISSUE TITLE
Live - Obligations with date range

### ISSUE THREAD

**Issue by KenRandall** [hmrc/vat-api#502]
Hi,

1. On the live system what is the valid date range for obligations. I get an error if the date range spans more than a year?

2. Is there a way of getting all obligations, not just open ones?

Thanks,

Ken

**Comment by daniel-andrews1994** [comment]
Hi Ken,

1. A valid date range is a time period which is 366 days or less.
2. If you don't include the 'status' query parameter, all open and fulfilled obligations will be returned.

Thanks,
Daniel

**Comment by aamirshakil** [comment]
Dear Daniel,
What should be the valid date range? because i am getting this error
code: "MATCHING_RESOURCE_NOT_FOUND"
message: "A resource with the name in the request can not be found in the API"

**Comment by KenRandall** [comment]
Hi Daniel,

Thanks. So if I want to get all historic obligations I presume that I can submit multiple requests decrementing the date range until it fails?

Regards,

Ken

**Comment by daniel-andrews1994** [comment]
Hi Ken,

That is correct, but you will only be able to retrieve obligations which have been created since joining MTD.

Thanks,
Daniel

**Comment by KenRandall** [comment]
Hi Daniel,

I was afraid of that. Is their any way of getting info on returns submitted prior to using MTD?

Regards,

Ken

**Comment by daniel-andrews1994** [comment]
Hi Ken,

The user would need to login to their online HMRC service to access any information prior to joining MTD. We are unable to surface this information through our MTD VAT service.

Thanks,
Daniel

**Comment by KenRandall** [comment]
One further question. It seems a bit strange that obligations can have a date range of 366 days but liabilities can only be 365 days!

Thanks,

Ken

**Comment by narendravijayarao** [comment]
Hi Ken,

Thank you... it should be 366 days. We will look into this and fix as soon as we can.

Thanks,

**Comment by KenRandall** [comment]
You have closed this without giving any details. Is this now fixed?

**Comment by mtd-api-team** [comment]
Hi Ken,

These may be a breaking change for some users, further investigation will be needed before continuing. This issue has been closed as it is part of an ongoing conversation, we will update everyone when we have a solution.

Thanks
