### ISSUE TITLE
Clarification regarding first possible submission period

### ISSUE THREAD

**Issue by cb-rfk** [hmrc/vat-api#503]
Hi all.

We have completed our MTD development (add-on to b2b accountancy package) and are now looking to onboard our first live users.  However I can't find any documentation detailing which the first obligation they will be able to submit a return for will be.

Essentially, do users have to wait for their next full obligation period to pass before they can submit their first return via MTD, or, if they are part way through an obligation period right now (e.g. the 2019Q1 period), will they be able to submit this current one via MTD once the end of that obligation period is passed, despite only signing up to MTD part way through the period??

Thanks for any pointers.
Richard

**Comment by daniel-andrews1994** [comment]
Hi, 

Please contact the Software Developers Support Team SDSTeam@hmrc.gsi.gov.uk who will be able to provide information on first submission return periods in MTD.

Thanks,
Daniel

**Comment by cb-rfk** [comment]
hi @daniel-andrews1994 ,

Thought that would be the answer - get quicker responses here though so thought it was worth a shot ;)

Richard

**Comment by GrahamHDawson** [comment]
Richard if you get an answer could you update this issue please as it's of interest to a lot of people.

Daniel - isn't that email address wrong now?
I thought all the addresses should have the 'gsi' bit removed ie

[SDSTeam@hmrc.gsi.gov.uk](url)

becomes

[SDSTeam@hmrc.gov.uk](url)

**Comment by james-work-account** [comment]
Hi @GrahamHDawson and @cb-rfk - both email addresses will work for a short time, but you are correct that SDST is moving to the new SDSTeam@hmrc.gov.uk. It is recommended that you use the email address with the `.gsi` dropped.
