### ISSUE TITLE
Flat Rate Scheme (FRS) MTD VAT submission ?

### ISSUE THREAD

**Issue by justinkelly** [hmrc/vat-api#505]
Hi All,

Can businesses using the Flat Rate Scheme (FRS) submit VAT returns/obligations via MTD (these APIs)?

Cheers

Justin

**Comment by james-work-account** [comment]
Hi @justinkelly - yes they should be able to submit through MTD.

Thanks,
James

**Comment by justinkelly** [comment]
thanks @james-work-account
