### ISSUE TITLE
No Deal Brexit changes documentation

### ISSUE THREAD

**Issue by GrahamHDawson** [hmrc/vat-api#507]
Is it possible to provide documentation of the changes required in the event of a 'No Deal' Brexit.
I can't seem to find the email that was sent months ago and there doesn't seem to be any info on the website(s).

**Comment by ma3574** [comment]
Hi @GrahamHDawson 

I am sorry we do not have any further information about Brexit. Please visit the following link for the most up to date information: https://euexit.campaign.gov.uk
