### ISSUE TITLE
What government gateway to be used by Business to Sign up for MTD VAT?

### ISSUE THREAD

**Issue by upendra-rathore** [hmrc/vat-api#510]
Hi there,

Could you please advise for below:

1. Can a business use its existing Government Gateway User ID and Password to Sign up for MTD VAT or they have to get new Government Gateway User ID and Password?

**Comment by markogrady** [comment]
It is the same credentials but they need to sign up to MTD.

Agents need a new account

**Comment by ma3574** [comment]
Hi @upendra-rathore 

Hopefully your question is now answered. If not please contact SDSTeam@hmrc.gov.uk at they will be able to answer authentication related questions.
