### ISSUE TITLE
Retrieve VAT obligations endpoint doesn't require json

### ISSUE THREAD

**Issue by ddaddy** [hmrc/vat-api#511]
**This bug is related to the**

- [ ] Documentation

**Describe the bug**
The documentation says the `/organisations/vat/{vrn}/obligations` endpoint requires the `Content-Type=application/json` header which is usually only needed with `POST` requests. This `GET` request expects the data as part of the URL string and not in JSON format.

**Comment by daniel-andrews1994** [comment]
Hi,

You are correct, thank you for contacting us regarding this, we will look into this and resolve the issue soon.

Kind Regards,
Daniel
