### ISSUE TITLE
Payments single date range

### ISSUE THREAD

**Issue by theshillito** [hmrc/vat-api#512]
* **I'm submitting a ...**
  - [x] Bug - API
  - [ ] Bug - Documentation
  - [ ] Improvement
  - [ ] Feature request
  - [ ] Support request

* **What is the current behaviour?**
Submitting a request to "payments" with the "from" and "to" date the same returns the following error:  
`{ ["statusCode"]=> int(400) ["message"]=> string(18) "DATE_RANGE_INVALID" } `
* **What is the expected behaviour?**
A response with any payments received on that day.
* **Other information** 
This issue occurs with both the "SINGLE_PAYMENT" or "MULTIPLE_PAYMENTS" test scenarios. Expanding the range to two days at least returns data as expected. I appreciate that picking a single date is very specific and in production is more likely to return nothing. However, if someone knows the date an amount was submitted, and then selected that single date to check the amount later on, this would fail. I am unable to test on production as our product is not yet finished, so I'd appreciate it if someone could reproduct this issue on production. Thank you.

**Comment by jacobbrownlow** [comment]
Hi 

Currently the date range between `from` and `to` must be a minimum of 1 days and a maximum of 365 days.

e.g.
Min: `?from=2018-01-01&to=2018-01-02`
Max: `?from=2018-01-01&to=2018-12-31`

However we are currently reviewing this. We are aware that the max range doesn't cater for leap years.

Jacob
