### ISSUE TITLE
POST to submit VAT return error 400

### ISSUE THREAD

**Issue by anikrooz** [hmrc/vat-api#513]
I'm submitting a return to the test service - https://test-api.service.hmrc.gov.uk/organisations/vat/159406745/returns

I get the error:
```
Array
(
    [result] => Array
        (
            [statusCode] => 400
            [message] => Invalid Json: Unrecognized token 'periodKey': was expecting ('true', 'false' or 'null')
 at [Source: (akka.util.ByteIterator$ByteArrayIterator$$anon$1); line: 1, column: 11]
        )

    [code] => 400
    [content_type] => application/json
)
```

My POST body is json encoded:
`
{"periodKey":"18A2","finalised":true,"vatDueSales":376.37,"totalValueSalesExVAT":1886.0,"vatDueAcquisitions":0.0,"totalAcquisitionsExVAT":0.0,"totalVatDue":376.37,"vatReclaimedCurrPeriod":93.75,"totalValuePurchasesExVAT":468.0,"netVatDue":282.62,"totalValueGoodsSuppliedExVAT":0.0}
` 
(okay it may be missing some trailing zeros at this point but that's not what the error is about)

I'm pretty sure that's what ends up at the other side, but the error suggests it's possibly missing quotes by the time it arrives at the API. Perhaps I'm just doing something silly, but I can't figure out what could be removing the quotes.

Here's the result of curl_getinfo with my headers, etc. :
```
Array(
    [url] => https://test-api.service.hmrc.gov.uk/organisations/vat/159406745/returns
    [content_type] => application/json
    [http_code] => 400
    [header_size] => 274
    [request_size] => 1303
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 0.132299
    [namelookup_time] => 0.024289
    [connect_time] => 0.029348
    [pretransfer_time] => 0.044178
    [size_upload] => 245
    [size_download] => 205
    [speed_download] => 1549
    [speed_upload] => 1851
    [download_content_length] => 205
    [upload_content_length] => 245
    [starttransfer_time] => 0.132253
    [redirect_time] => 0
    [redirect_url] => 
    [primary_ip] => 104.111.230.165
    [certinfo] => Array
        (
        )

    [primary_port] => 443
    [local_ip] => xx.xx.xx.xx
    [local_port] => 39084
    [request_header] => POST /organisations/vat/159406745/returns HTTP/1.1
Host: test-api.service.hmrc.gov.uk
Gov-Client-Connection-Method: WEB_APP_VIA_SERVER
Gov-Client-Public-IP: xx.xx.xx.xx
Gov-Client-Public-Port: 63922
Gov-Client-User-IDs: xxxxxx
Gov-Client-Timezone: UTC+00:00
Gov-Client-Screens: width=1680&height=1050&scaling-factor=1&colour-depth=24
Gov-Client-Window-Size: width=1680&height=939
Gov-Client-User-Agent: Windows /  (/Desktop)
Gov-Client-Browser-JS-User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
Gov-Client-Browser-Do-Not-Track: false
Gov-Client-Multi-Factor: type=AUTH_CODE&timestamp=2019-02-24T19:48:53Z&unique-reference=f2dfc4c0axxxxxx
Gov-Vendor-Version: Stuff
Gov-Vendor-Public-IP: xx.xx.xx.xx
Gov-Vendor-Forwarded: for=xx.xx.xx.xx
Authorization: Bearer 1ecaf21e...
Accept: application/vnd.hmrc.1.0+json
Content-Type: application/json
Content-Length: 245


)
```

**Comment by ma3574** [comment]
Hi @anikrooz 

I have used the JSON payload you provided and submitted against a test user in the sandbox suggesting the problem lies somewhere in the code/library being used to make the call to the API. 

It would require more investigation on your side unfortunately

**Comment by anikrooz** [comment]
> Hi @anikrooz
> 
> I have used the JSON payload you provided and submitted against a test user in the sandbox suggesting the problem lies somewhere in the code/library being used to make the call to the API.
> 
> It would require more investigation on your side unfortunately

Thank you. Got it working now... I shall hang my head in shame
