### ISSUE TITLE
Fraud Preventation

### ISSUE THREAD

**Issue by heythisiskishore** [hmrc/vat-api#514]
Dear Team,

We have to implement Fraud Prevention in our Application. Should we add the Fraud Prevention Headers for all the API's like 'Retrieve VAT obligations', 'Submit VAT return for period','View VAT Return','Retrieve VAT liabilities','Retrieve VAT payments'. If it is necessary for all the API's can you please suggest how to do it.

Thanks in advance.

**Comment by ma3574** [comment]
Please see https://developer.service.hmrc.gov.uk/api-documentation/docs/fraud-prevention
