### ISSUE TITLE
Fraud prevention

### ISSUE THREAD

**Issue by heythisiskishore** [hmrc/vat-api#515]
Dear Team,

For all the API's like 'Retrieve VAT obligations', 'Submit VAT return for period','View VAT Return','Retrieve VAT liabilities','Retrieve VAT payments'.
There  are Request headers like ‘Accept’,’ Content-Type’,’ Authorization’ which are sent at the time of Request. 
Should we add Fraud prevention Header contents like Gov-Client-User-IDs or Gov-Client-Local-IPs or Gov-Client-MAC-Addresses to this Request headers ?
 is it necessary for all the API's can you please suggest.

Thanks in advance.

**Comment by ma3574** [comment]
Please see https://developer.service.hmrc.gov.uk/api-documentation/docs/fraud-prevention

**Comment by heythisiskishore** [comment]
Dear ma3574,

I already know about the information what you have shared in the link. I had previously gone through that link but i didn't understood what it is there in it. I asked for some more clear cut information like the information given in MTD VAT 

https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0
