### ISSUE TITLE
Obligation data sets

### ISSUE THREAD

**Issue by COLASYSTEMS** [hmrc/vat-api#516]
Hi,
With respect to behaviour in live.

Will a call to  /organisations/vat/{vrn}/obligations with status O and no data criteria always return at least 1 obligation?   

In other words if there is currently 1 "O" obligation and the VAT return is then submitted for that obligation, will the next call to /organisations/vat/{vrn}/obligations with status O return the obligation for the next VAT period even if that is in the future ? or will it return an empty set or some sort of error ?

thanks
Shaun.

**Comment by MarkAKelly** [comment]
Hi @COLASYSTEMS,

The steer we have got is that the next obligation is created on the first day of that obligation period, so if you had submitted returns for all previous periods and you weren't in the next period then you could potentially not yet have any open obligations.

If this were the case, calling the endpoint for 'open' obligations would result in a 404 NOT_FOUND - we would never return an empty list.

Hope this helps,

Mark
