### ISSUE TITLE
Vrn number for VAT Return

### ISSUE THREAD

**Issue by wmnewage** [hmrc/vat-api#517]
HI there,
We are integrating VAT return api into our application. We created sandbox,client id,server token and all is done. but when we use vat return, vrn number is mandatory. We have vrn number for production. but for developing/testing what will be the vrn number, where can i get that number.

**Comment by markogrady** [comment]
You get it via the API when you create an organisation user

**Comment by rajitha0007** [comment]
This will provide a test user with VRN and username and PW for Test HMRC gateway account for Authentication in sandbox environment.

https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/api-platform-test-user/1.0

**Comment by jeremystone** [comment]
Further to @rajitha0007 make sure that you: 
- Have created an application in the HMRC Developer Hub and have enabled subscriptions for the Create Test User API.
- Use the server token (under Manage Credentials) for the application as the Authorization Bearer token.
- Post a body that includes the service that you require - so for MTD VAT: 
`{
  "serviceNames": [
    "mtd-vat"
  ]
}`

**Comment by wmnewage** [comment]
hi there,
Thanks for your help. it works fine. Now am facing one more issue. When i try to get authorization token ,am getting empty reply. Attached screenshot for your reference with inputs
![authtoken](https://user-images.githubusercontent.com/48719612/54866936-cebb5380-4da0-11e9-9267-8985e88bc110.jpg)
. Thanks in advance. i have hide client id.

**Comment by ddaddy** [comment]
Are the headers empty as shown in the image?
I send `Accept: application/vnd.hmrc.1.0+json`

Also, make sure your redirect_uri is also listed under your application on the HMRC web for your application.
