### ISSUE TITLE
PHP example?

### ISSUE THREAD

**Issue by youriv2019** [hmrc/vat-api#518]
Does anyone have a working PHP example for MTD VAT?

**Comment by jeremystone** [comment]
For issues relating to authentication (OAuth2) and for language specific queries please contact the SDST at SDSTeam@hmrc.gsi.gov.uk and inform them that you have been sent to them by the vat-api team. They should be able to help with your queries.

**Comment by youriv2019** [comment]
// Include our server token as a header.
	$headers = [
		'Accept: application/vnd.hmrc.1.0+json',
		'Authorization: Bearer ' . $token,
		'vrn: 643159930',
		'Content-Type: application/json'
	];
	
	// Call the hello application API.
	$ch = curl_init();
	curl_setopt($ch, CURLOPT_URL,"https://test-api.service.hmrc.gov.uk/organisations/vat/{vrn}/obligations");
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    	curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
	$server_output = curl_exec ($ch);
	curl_close ($ch);

	// Print what we get.
	print  $server_output;

I have this but I am receiving { "code" : "INVALID_SCOPE", "message" : "Can not access the required resource. Ensure this token has all the required scopes." } ??

**Comment by jeremystone** [comment]
The invalid scope refers to the scopes specified when you created your OAuth token. See https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints.

The required scopes are documented against the endpoints. So for VAT obligations see https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0#_retrieve-vat-obligations_get_accordion

**Comment by youriv2019** [comment]
> The invalid scope refers to the scopes specified when you created your OAuth token. See https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints.
> 
> The required scopes are documented against the endpoints. So for VAT obligations see https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0#_retrieve-vat-obligations_get_accordion

thank you. How do I set a scope for the specific API? The scope is receive back is for the Hello API but I want the MTD VAT?

**Comment by jeremystone** [comment]
You need to specify the scope you want when you request the OAuth token.

**Comment by youriv2019** [comment]
ah thanks!

**Comment by youriv2019** [comment]
does anybody have a PHP example for posting a VAT return? This is what I have but I am receiving error: { "code" : "MISSING_CREDENTIALS", "message" : "Authentication information is not provided" }

`$post_field_string = '';
	$post_field_string .= "client_secret=$client_secret";
	$post_field_string .= "&client_id=$client_id";
	$post_field_string .= "&grant_type=authorization_code";
	$post_field_string .= "&redirect_uri=$redirect_uri_encoded";
	$post_field_string .= "&code=".$access_token;
	
	$ch = curl_init();
	curl_setopt($ch, CURLOPT_URL, "https://test-api.service.hmrc.gov.uk/organisations/vat/643159930/returns");
	curl_setopt($ch, CURLOPT_POSTFIELDS, $post_field_string);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
	$server_output = curl_exec ($ch);
	curl_close ($ch);
	
	echo $server_output;
	`

**Comment by ma3574** [comment]
For issues relating to authentication (OAuth2) and for language specific queries please contact the SDST at SDSTeam@hmrc.gsi.gov.uk and inform them that you have been sent to them by the vat-api team. They should be able to help with your queries.

**Comment by steveblamey** [comment]
For PHP you can use this library https://github.com/thephpleague/oauth2-client. The generic provider works with HMRCs Oauth and you can follow the example in the README with a few tweaks.

Our implementation uses it: https://github.com/uzerpllp/uzerp/blob/master/lib/classes/standard/MTD.php

**Comment by crazypabs** [comment]
> does anybody have a PHP example for posting a VAT return? This is what I have but I am receiving error: { "code" : "MISSING_CREDENTIALS", "message" : "Authentication information is not provided" }
> 
> `$post_field_string = '';
> $post_field_string .= "client_secret=$client_secret";
> $post_field_string .= "&client_id=$client_id";
> $post_field_string .= "&grant_type=authorization_code";
> $post_field_string .= "&redirect_uri=$redirect_uri_encoded";
> $post_field_string .= "&code=".$access_token;
> 
> ```
> $ch = curl_init();
> curl_setopt($ch, CURLOPT_URL, "https://test-api.service.hmrc.gov.uk/organisations/vat/643159930/returns");
> curl_setopt($ch, CURLOPT_POSTFIELDS, $post_field_string);
> curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
> $server_output = curl_exec ($ch);
> curl_close ($ch);
> 
> echo $server_output;
> `
> ```

Did you ever get this sorted? I have the exact same issue and I have tried more ways than there are Dalmatians in the file 101 Dalmatians.

Cheers 

TIA

M@

**Comment by youriv2019** [comment]
I got it working yes. 

Did you create an authorisation first with the test user? That seems to be the problem.

$code = $_GET['code'];

 // Build a query string of POST data.
 $post_field_string = '';
 $post_field_string .= "client_secret=$client_secret";
 $post_field_string .= "&client_id=$client_id";
 $post_field_string .= "&grant_type=authorization_code";
 $post_field_string .= "&redirect_uri=$redirect_uri_encoded";
 $post_field_string .= "&code=$code";

 // POST the data to HMRC to get an access token.
 $ch = curl_init();
 curl_setopt($ch, CURLOPT_URL, 'https://api.service.hmrc.gov.uk/oauth/token');
 curl_setopt($ch, CURLOPT_POSTFIELDS, $post_field_string);
 curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
 $response = curl_exec($ch);
 curl_close ($ch);

 // Convert from JSON to PHP.
 $response = json_decode($response, true);
 //print_r($response);exit;
 // Check to see if we have an access token.
 if(!isset($response['access_token'])) {
 // We couldn't get an access token.
 echo 'No access token.';exit;
 } else {
 $access_token = $response['access_token'];
 session_start();
 $_SESSION['access_token'] = $access_token;
 $redirectAfterLogin = 1;
 }

Then once you have that, send headers like this:

$headers = [
 'Accept: application/vnd.hmrc.1.0+json',
 'Authorization: Bearer ' . $access_token.'',
 'Content-Type: application/json',
 ...

 ];
Kind regards, 

 Youri 
	 (https://www.liminicoffee.co.uk/) 
	01274 911 419 
	please tell us how we did today... (https://www.liminicoffee.co.uk/review_service.php)

On Wed, Jan 20, 2021 at 20:29, "crazypabs"  wrote:
	does anybody have a PHP example for posting a VAT return? This is what I have but I am receiving error: { "code" : "MISSING_CREDENTIALS", "message" : "Authentication information is not provided" } 

	`$post_field_string = '';
 $post_field_string .= "client_secret=$client_secret";
 $post_field_string .= "&client_id=$client_id";
 $post_field_string .= "&grant_type=authorization_code";
 $post_field_string .= "&redirect_uri=$redirect_uri_encoded";
 $post_field_string .= "&code=".$access_token; 

	$ch = curl_init(); curl_setopt($ch, CURLOPT_URL, "https://test-api.service.hmrc.gov.uk/organisations/vat/643159930/returns"); curl_setopt($ch, CURLOPT_POSTFIELDS, $post_field_string); curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE); $server_output = curl_exec ($ch); curl_close ($ch); echo $server_output; `   

	Did you ever get this sorted? I have the exact same issue and I have tried more ways than there are Dalmatians in the file 101 Dalmatians. 

	Cheers 

	TIA 

	M@

**Comment by crazypabs** [comment]
Hi Youri,

That's  interesting, I am using a test user when I get this response. I didn't know that there was an issue with the test users in the API that posts the returns. That's awkward.

So did you use your above code to work on the test user?

Cheers

M@

**Comment by youriv2019** [comment]
I have not tried with sandbox just yet, will do soon as they want more and more fraud headers! 

But my code worked fine with the live API yes.

Kind regards, 

 Youri 
	 (https://www.liminicoffee.co.uk/) 
	01274 911 419 
	please tell us how we did today... (https://www.liminicoffee.co.uk/review_service.php)

On Thu, Jan 21, 2021 at 12:32, "crazypabs"  wrote:
	Hi Youri, 

	That's interesting, I am using a test user when I get this response. I didn't know that there was an issue with the test users in the API that posts the returns. That's awkward. 

	So did you use your above code to work on the test user? 

	Cheers 

	M@

**Comment by youriv2019** [comment]
I managed to get it all fixed now. Let me know if you need some help
Kind regards, 

 Youri 

  (https://www.liminicoffee.co.uk/)
	01274 911 419
	please tell us how we did today... (https://www.liminicoffee.co.uk/review_service.php)
On Thu, Jan 21, 2021 at 12:32, "crazypabs"  wrote:
 Hi Youri,
 That's interesting, I am using a test user when I get this response. I didn't know that there was an issue with the test users in the API that posts the returns. That's awkward.
 So did you use your above code to work on the test user?
 Cheers
 M@

**Comment by andrisskutans** [comment]
Please, advice where to see scopes? Here https://developer.service.hmrc.gov.uk/api-documentation/docs/api?filter=vat i can not find. If i use $scope = 'hello'; then get Array
(
    [code] => INVALID_SCOPE
    [message] => Can not access the required resource. Ensure this token has all the required scopes.
). But what is valid scope?
