### ISSUE TITLE
Post not working

### ISSUE THREAD

**Issue by youriv2019** [hmrc/vat-api#519]
`
$access_token = $_SESSION['access_token'];
	
	$handle = curl_init();
 
	$url = "https://test-api.service.hmrc.gov.uk/organisations/vat/643159930/returns";
 
	$postData = array(
	  'Accept' => 'application/vnd.hmrc.1.0+json',
	  'Authorization'  => 'Bearer '.$access_token,
	  'Content-Type'    => 'application/json'
	);
	
	print_r($postData);
 
	curl_setopt_array($handle,
	  array(
		 CURLOPT_URL => $url,
		 // Enable the post response.
		CURLOPT_POST       => true,
		// The data to transfer with the response.
		CURLOPT_POSTFIELDS => $postData,
		CURLOPT_RETURNTRANSFER     => true,
	  )
	);
 
	$data = curl_exec($handle);
 
	curl_close($handle);
 
	echo $data;
`

Array ( [Accept] => application/vnd.hmrc.1.0+json [Authorization] => Bearer 3f69148194dfd7dffddc237cc1388df [Content-Type] => application/json ) { "code" : "MISSING_CREDENTIALS", "message" : "Authentication information is not provided" }

Why is this happening? I have provided the token and used the correct scope.

**Comment by ma3574** [comment]
Hi @youriv2019 

As the VAT API team we are only able to provide technical assistance with the API and not with specific code that calls our API as we are agnostic about what language vendors use. As such we are not able to assist with this. 

We can only point you to the platform documentation: https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation

FYI The Headers need to be part of the header in the `POST` and not as part of the body. 

If you continue to face issues please get in touch with SDST for more specific help: SDSTeam@hmrc.gov.uk

**Comment by narendravijayarao** [comment]
Hi @youriv2019,

You are setting the headers using CURLOPT_POSTFIELDS, basically, this will mainly use to set the body/data contents.

Try using CURLOPT_HTTPHEADER.

$headers[] = 'Accept: application/json';
$headers[] = 'Content-Type: application/json';
$headers[] = ''Authorization: Bearer '.$access_token';

curl_setopt($curlHandle, CURLOPT_HTTPHEADER, $headers); 

OR

$headerData = array(
  'Accept' => 'application/vnd.hmrc.1.0+json',
  'Authorization'  => 'Bearer '.$access_token,
  'Content-Type'    => 'application/json'
);

print_r($headerData);

curl_setopt_array($handle,
  array(
	 CURLOPT_URL => $url,
	 // Enable the post response.
	CURLOPT_POST       => true,
	// The data to transfer with the response.
	//CURLOPT_POSTFIELDS => $postData,
	CURLOPT_RETURNTRANSFER     => true,
        CURLOPT_HTTPHEADER => $headerData
  )
); 

Thanks,

**Comment by youriv2019** [comment]
thanks guys all sorted
