### ISSUE TITLE
INVALID_DATE_RANGE for list obligations

### ISSUE THREAD

**Issue by nnotsofun** [hmrc/vat-api#52]
Hi,

I wanted to clarify how the INVALID_DATE_RANGE validation works for list obligations. It seems that you can only request for one year of returns based on [this code](https://github.com/hmrc/vat-api/blob/20ba9b7c3b17406312d3a31f60cde0096d787cb8/test/uk/gov/hmrc/vatapi/models/ObligationsQueryParamsSpec.scala#L68). 

Based on a) the above and b) my understanding you can only submit VAT returns in sequential order:
* How does software work out what date range it should retrieve? If the next 'open' return falls outside a year, is it expected that we'd have to allow making lists requests till the year with the earliest 'open' VAT return? Not sure how often this scenario would occur but could potentially impact the 150 requests/minute limit.
  * Example: In April 2019, a quarterly VAT business hasn't submitted any VAT returns for more than a year. We'd have to make two requests one for period 31/03/2018-31/03-2019 and 28/02/2017-28/02/2018 assuming the last completed VAT return was 30/09/2017.
* Ideally there would be an endpoint that lets us know what the next 'open' VAT return for submission is so we can adjust the date range relative to that.
* In the reverse scenario, do we know how far into the future from 'today's' date the VAT obligations list will return us an open VAT return? Think it's been asked a few times earlier so a few of us must be keen for this answer :slightly_smiling_face:

If assumption b) is not right - please let me know. Hope that's clear!

On a side note, I found the validation didn't work as I expected (1/1/2017-1/1/2018 works - I'd expected it to error out! (greater than a year)).

Cheers,

Nick

EDITED - updated example for clarity

**Comment by narendravijayarao** [comment]
Thanks... We are looking into this and will get back to you asap.

**Comment by narendravijayarao** [comment]
We have created a story to handle these scenarios. https://jira.tools.tax.service.gov.uk/browse/MTDSA-1398

**Comment by nnotsofun** [comment]
Thanks @narendravijayarao, I can't view your jira - for good reason! Do you have any more info on how it'll be addressed or will we have to wait till the card is worked on?

**Comment by narendravijayarao** [comment]
Sorry :)... 
We are addressing this case by relaxing the requirement for From & To Date parameters in the Get Obligations request, where the Display request (Status) value is set to O (open obligations only).

This will allow you to see all open obligations without any date range. If you provide the dates it will results the same as existing API

**Comment by nnotsofun** [comment]
:+1: Thanks @narendravijayarao - exactly what we'd need for this scenario, looking forward to the PR.
