### ISSUE TITLE
Fraud Prevention Header

### ISSUE THREAD

**Issue by heythisiskishore** [hmrc/vat-api#521]
Hi,

can any one give some explanation about Fraud Prevention Headers
Gov-Vendor-Forwarded,Gov-Client-Multi-Factor,Gov-Client-Screens,Gov-Client-Window-Size.
How to use it in our software.

Thanks.

**Comment by ma3574** [comment]
Please refrain from opening multiple issues on the same topic. 

Please see the documentation link provided in your other issue: https://github.com/hmrc/vat-api/issues/520

**Comment by heythisiskishore** [comment]
Hi there,

Thanks for your response!

Could you please clarify what details we need to send to HMRC for below three headers.

1. Gov-Vendor-License-IDs
2. Gov-Client-Multi-Factor
3. Gov-Vendor-Forwarded

In HMRC documentation it is not clear what details to be included in the header.

Awaiting your response!
