### ISSUE TITLE
Issue in Oauth authorisation token

### ISSUE THREAD

**Issue by wmnewage** [hmrc/vat-api#522]
HI, 
Am in generating oauth token. When i tried it is saying scope is mandatory. What i need to give in scope.

**Comment by ma3574** [comment]
Please see the provided documentation on the Developer Hub: https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints which covers scopes. 

If this does not resolve your issue please contact SDSTeam@hmrc.gov.uk as the VAT-API team do not deal with auth related queries.

**Comment by wmnewage** [comment]
Hi there,
I got empty response when I tried to get auth token. Let me know if am doing anything wrong. Attached screenshot for your reference. For security reason I have commented client id in attached image.

Regards,
[logo]

Rajasekar | Team Lead
NewAge Software & Solutions
Super A7,Rathna Towers, Thiru Vi Ka Industrial Estate, Chennai 600 032 India
Office: +914443454805 | rajasekar_nass<mailto:rajasekar_nass>
Mobile: +919894585861
Skype: rajasekar_nass | Website: www.newage-global.com<http://www.newage-global.com>



[fb]<https://www.facebook.com/newagesoftwareandsolutions/>[in]<https://www.linkedin.com/company/Newage-software-&-solutions>[play]<https://www.youtube.com/channel/UCuc8KANi5fqJW59fbeI0HOw>


________________________________
DISCLAIMER:
The information contained in this communication is intended solely for the use of the individual or entity to whom it is addressed and others authorized to receive it. It may contain confidential or legally privileged information. If you are not the intended recipient you are hereby notified that any disclosure, copying, distribution or taking any action in reliance on the contents of this information is strictly prohibited and may be unlawful. If you have received this communication in error, please notify us immediately by responding to this email and then delete it from your system. The firm is neither liable for the proper and complete transmission of the information contained in this communication nor for any delay in its receipt.
