### ISSUE TITLE
Issues surrounding expired users

### ISSUE THREAD

**Issue by seurrep** [hmrc/vat-api#524]
I've been told there's an issue surrounding the VAT API sandbox and wondering if this is something others have seen:

- Create a new user
- Use the user name and password generated to log in
- Authorise our application with read vat & write vat privileges.
- Leave the user for a while (in this case longer than the time period where the users and VRNs are recycled)
- Attempt to use the refresh token for that user to obtain a new bearer token
- The attempt to get a new bearer token appears to succeed

...but...

Any attempt to submit fails with INVALID_CREDENTIALS despite the API sandbox being content to provide the payments, liabilities and obligations for that user (although I'm guessing those last three are canned data).

**Comment by mdsystems** [comment]
I have seen an occasional requirement to re-authorise though have not yet observed a pattern. If I do, I will post back here.

**Comment by sparkz42** [comment]
Yes, I've seen the same problem in the sandbox environment. I haven't done tests although it seems to happen every time I haven't accessed a test user for a day?

**Comment by mdsystems** [comment]
Just tested myself and it was fine yesterday but today I was required to re-authorise. It would be useful to know if others experience this pattern.

**Comment by narendravijayarao** [comment]
Hi,

We tested on our side and able to create the user and can access the obligations, payments and liabilities endpoints. 

Are you still facing the problem? if yes, can you provide any more details?

Thanks,

**Comment by mdsystems** [comment]
For me, I am seeing a response that the refresh token is invalid. This only appears to occur after a significant amount of time has passed. It appears to be valid if I test the same day and refresh the token. I will do some more testing but it would be interesting to hear if others have a similar issue.

**Comment by mtd-api-team** [comment]
As this hasn't been replied to in a while, we will close this issue for now.  If you are still experiencing issues then feel free to reopen the issue at a later date.
