### ISSUE TITLE
Obligations Testing in the Sandbox

### ISSUE THREAD

**Issue by SheepShearer** [hmrc/vat-api#525]
Is the response from a Retrieve VAT Obligations in the Sandbox fixed to always return sample data from 2017?

It doesn't seem to matter what From and To dates I request I always get 2017 dates back in the response examples so I'm just wondering if this is normal or if its me. Presumably in the real environment I'll get back the dates between the requested dates?

Thanks

**Comment by cb-rfk** [comment]
Yes, that's correct.  Make sure you use the Gov-Test-Headers to return a wider selection of values, even if they are still all canned responses from the same period...

Richard

**Comment by SheepShearer** [comment]
Thanks Richard, that's what I was hoping to hear.

**Comment by MikeCongdon1** [comment]
It would make a lot more sense (and it seems that it would be more consistent with the other endpoints) if the date from / to would filter properly within the 2017 sample date range.
