### ISSUE TITLE
Liabilites test end point query not working

### ISSUE THREAD

**Issue by maxdarque** [hmrc/vat-api#526]
**This bug is related to the**

- [ ] Documentation
- [x] API 

**Describe the bug**
I query the test api endpoint for liabilities within a certain date range and for open obligations. The response is outside the date range and includes fulfilled obligations. 

```
Get URL: https://test-api.service.hmrc.gov.uk/organisations/vat/240097975/obligations?from=2018-12-01&to=2019-03-03&status=O
{"obligations":[{"start":"2017-01-01","end":"2017-03-31","due":"2017-05-07","status":"F","periodKey":"18A1","received":"2017-05-06"},{"start":"2017-04-01","end":"2017-06-30","due":"2017-08-07","status":"O","periodKey":"18A2"}]}

```

When I request obligations with no query parameters, it returns an error:

`Get URL: https://test-api.service.hmrc.gov.uk/organisations/vat/240097975/obligations
{"statusCode":400,"message":"INVALID_DATE_FROM"}`

**To Reproduce**
Use a get request with the above parameters on test data.

**Expected behavior**
The query parameters should be taken into account.

The request parameters are optional so why is an error given when they are not included?

**Comment by maxdarque** [comment]
Question, is the HMRC VAT endpoint ready for release in a few weeks? This feels like fairly basic issue...

**Comment by james-work-account** [comment]
Hi @maxdarque - in the Sandbox environment, we use a stateless stub to return canned data so unfortunately any valid request will return the same data. When we release, we will be hitting the real backend systems so real data will be returned. In the mean time, you can simulate different responses by providing different Gov-Test-Scenario header values. [Please see the docs for more information on these](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0#_retrieve-vat-obligations_get_accordion).

Regarding your second request (without any query parameters), the `from` and `to` parameters are mandatory unless status is `O`. Not providing them will return an error.
