### ISSUE TITLE
Add CORS support to API endpoints to support pure browser apps/PWAs

### ISSUE THREAD

**Issue by moonlitknight** [hmrc/vat-api#527]
**Is your feature request related to a problem? Please describe.**
Progressive Web Apps are increasing in popularity, and take the place of local desktop/mobile installs. However, such apps are unable to access the VAT API because browser restrictions will only allow the endpoints to be accessed if those endpoints support CORS.

**Describe the solution you'd like**
The API endpoints should support CORS by adding a `Access-Control-Allow-Origin` header, either to *, or to a configured origin.

**Describe alternatives you've considered**
This is a show stopper for PWAs. There are no workarounds.

**Comment by james-work-account** [comment]
Hi @moonlitknight - this isn't something we're currently working on but I'll raise it with the API Platform team. Thank you for your suggestion.

**Comment by james-work-account** [comment]
Hi @moonlitknight - I've had a word with the API Platform team and they have stated that they will not be supporting CORS.

OAuth allows users to delegate authority to a third-party service, so CORS is not essential (even if you are making a PWA). They have recommended that you should look into the delegated authority model offered by OAuth, which allows your system to interact with HMRC on behalf of the users instead of the users' browsers interacting with us directly.

**Comment by moonlitknight** [comment]
Hi @james-work-account .Thanks for following up on this. Unfortunately, the response doesn't make sense. I'm very experienced with OAuth in all its options (I'm a top answerer on StackOverflow). Support for CORS and the use of OAuth are unrelated. 

The issue is this...
Let's assume that I have successfully obtained an Access Token, and made that available to my browser client to include in an `Authorization: Bearer xx` header. So that's OAuth done and dealt with. My browser app now tries to make an API call to the HMRC API, but the standard browser security model rejects the HTTP call because it's cross origin. In order to enable the call, the HMRC API should include a single header (`Access-Control-Allow-Origin`) in response to an OPTIONS request. 

My understanding is that HMRC wishes to encourage businesses to embrace digital record keeping. As such, one would reasonably expect that HMRC would want to make their APIs available to the widest possible range of deployment architectures, and specifically to encourage the architecture that is the easiest for businesses to deploy as its only dependency is a web browser. 

Installable Progressive Web Apps are the future of local applications. They don't depend on any specific local OS, they don't depend on an intermediate server being available, and they don't expose private data to any third party. If any given PC breaks, the user can simply. Given these highly desirable characteristics, it's anomalous that HMRC wouldn't want to embrace this technology in order to allow businesses the fullest flexibility in how they structure their IT, especially given it's such a simple  facility to enable.

**Comment by james-work-account** [comment]
Hi @moonlitknight - I understand your frustration, that is just the message I was asked to pass on. If you contact the Software Development Support Team directly via SDSTeam@hmrc.gov.uk or through https://developer.service.hmrc.gov.uk/developer/support, they will be able to advise further. I'm sorry that we can't be much more help at this stage.

**Comment by KenRandall** [comment]
Hi @moonlitknight - Did you manage to resolve this in the end as I am having the same problem!

**Comment by moonlitknight** [comment]
@KenRandall My understanding from the comments above is that HMRC don't want to implement CORS. I had no choice but to totally re-architect my app to be server based :-(

**Comment by KenRandall** [comment]
@moonlitknight I was afraid of that. I guess I'll have to use PHP. Can I ask what HTTP Client library you used?

**Comment by moonlitknight** [comment]
Our server app is written in Java. We just used the standard Java HttpClient. There's no need for anything more elaborate as it's only a couple of REST endpoints.

**Comment by robertsmccann** [comment]
I've just come to the same conclusion having read this:

"The API Platform does not support cross-origin resource sharing (CORS) (opens in a new tab)link opens in a new window. It is therefore not possible to call our APIs from client-side code within a web browser, for example using Ajax"
(Source:  https://developer.service.hmrc.gov.uk/api-documentation/docs/reference-guide).

I guess I'll have a go at doing it in PHP. Has anyone had any success this way who would be willing to share a sample PHP code for submitting XML to HRMC Corporate Tax Transaction Engine?

Thanks in advance!

Rob.
