### ISSUE TITLE
Some Clarity is needed on Fraud Prevention Headers

### ISSUE THREAD

**Issue by Roger1952** [hmrc/vat-api#528]
• All the HMRC API web site says is “we expect it will become compulsory to supply header information for this API from April 2019 to prevent fraud”. A week before this is supposed to go live a definitive statement is required, “expect” is not good enough, will it or won’t it?

• As the sandbox has not bothered to provide a test environment for the headers how is it possible to know if an implementation is correct? Trying to capture a packet and email its content is not very accurate, especially as some of the header content will vary from call to call.

• Judging from some of the questions and comments about the fraud headers in GITHUB the definition is not as clear and unambiguous as it should be. This makes the need for a proper test environment even more important.

• The description of the headers contains no information about errors. If a header is not as expected how will an application know, what errors will be returned?

• Will an incorrect header result in a rejected submission?

• If a submission is rejected, who then will arbitrate as to whether the fault lies with user application or an ambiguous API definition, and who will pick up the tab for any late submission penalties?

• What will be the response if the HMRC site actually looks at the headers and decides the message is fraud?

**Comment by ddaddy** [comment]
I totally agree. We have 6 days until these headers are mandatory with no way of testing them.
What is going to happen after April 1st?

**Comment by Roger1952** [comment]
An email from HMRC today about fraud prevention has now clarified that:

"a software supplier who fails to comply with regulation 3(2) is liable to a penalty of £3,000"

Could be a nice little earner. They fail to clarify what's needed and then fine people for not doing it.

**Comment by MKoppJones** [comment]
The last I remember hearing is, while the headers are mandatory, they won't be validated yet. They will then get in touch with vendors who are not complying and help them comply, then the validation will be added. I haven't got the email to hand where I read this, so apologise for no source, anyone able to confirm this?

**Comment by AndyYouens** [comment]
So we have to use these header from 1/4 but no checking will be performed.  We cannot test these in the sandbox??

Some of the headers are unworkable & not related to security at all - Screen size & resolution????

**Comment by shaunl23** [comment]
Has anyone had a manual check of their headers yet??
They emailed advising we can send a sample of our headers to them and they will check them.
I did this on 07/03 which they acknowledged on 11/03, but I am yet to hear back any feedback.
It takes such a long time chasing anything as well with replies taking days/weeks.
Like others I'm concerned about the looming deadline and am finding very little support with the headers.

**Comment by mdsystems** [comment]
From my reading, the regulations covering this came into force on 19th March this year. Is there any clarity on exactly what is required to comply? (http://www.legislation.gov.uk/uksi/2019/360/made)

**Comment by Roger1952** [comment]
It's been 2 days now and I was wondering when/if any of the HMRC folks are going to respond to each of the original 7 points?

**Comment by adamdavi3s** [comment]
> Has anyone had a manual check of their headers yet??
> They emailed advising we can send a sample of our headers to them and they will check them.
> I did this on 07/03 which they acknowledged on 11/03, but I am yet to hear back any feedback.
> It takes such a long time chasing anything as well with replies taking days/weeks.
> Like others I'm concerned about the looming deadline and am finding very little support with the headers.

Same, three weeks and no response.

However there is no "deadline" as such yet as the headers are not mandatory until *maybe* later in the year sometime

**Comment by AndyYouens** [comment]
Adam - did you send the headers to the SDSTeam@hmrc.gsi.gov.uk team?

**Comment by AndyYouens** [comment]
Are these headers needed for the submission only, or all API calls?

**Comment by SDST-HMRC** [comment]
> The last I remember hearing is, while the headers are mandatory, they won't be validated yet. They will then get in touch with vendors who are not complying and help them comply, then the validation will be added. I haven't got the email to hand where I read this, so apologise for no source, anyone able to confirm this?


Hi the following message was issued by HMRC Software Developers Support Team (SDST) to all registered developers on the 8th Feb 2019:
Dear Developer 
Further to our communication on 01 February 2019, some of you have asked us about our policy over non-compliance with this requirement from the 1st April 2019. We do not plan, immediately after April, to reject MTD VAT messages from software applications that are non-compliant with the requirement. However, we expect your software applications to be compliant, and we will identify and work with you as necessary to ensure your software applications are made compliant as quickly as possible. We will, later in the year (2019), consider whether we will reject MTD VAT messages for non-compliance with the fraud prevention headers at the point of receipt. 
Regards

**Comment by ddaddy** [comment]
Thank you for the clarification @SDST-HMRC . I registered as a developer after 8th Feb, so I never got that message. Maybe you should add it to the documentation?

**Comment by AndyYouens** [comment]
@SDST-HMRC  that email not received here :-(

**Comment by rajitha0007** [comment]
https://developer.service.hmrc.gov.uk/api-documentation/docs/fraud-prevention
It’s mandatory from 1st April as per the above link; (updated on 22 March )
“It is mandatory to provide header information when using the following APIs:
VAT (MTD) from 1st April 2019”

 & as per the related legislation,if not comply, liable for £3000
http://www.legislation.gov.uk/uksi/2019/360/made

**Comment by Roger1952** [comment]
Dear SDST team

Thank you for your generic response. It would however be really helpful if you would read and then respond to the points in the original post.

Thank you.

**Comment by shaunl23** [comment]
> > The last I remember hearing is, while the headers are mandatory, they won't be validated yet. They will then get in touch with vendors who are not complying and help them comply, then the validation will be added. I haven't got the email to hand where I read this, so apologise for no source, anyone able to confirm this?
> 
> Hi the following message was issued by HMRC Software Developers Support Team (SDST) to all registered developers on the 8th Feb 2019:
> Dear Developer
> Further to our communication on 01 February 2019, some of you have asked us about our policy over non-compliance with this requirement from the 1st April 2019. We do not plan, immediately after April, to reject MTD VAT messages from software applications that are non-compliant with the requirement. However, we expect your software applications to be compliant, and **we will identify and work with you as necessary to ensure your software applications are made compliant as quickly as possible.** We will, later in the year (2019), consider whether we will reject MTD VAT messages for non-compliance with the fraud prevention headers at the point of receipt.
> Regards

Would this mean that we can submit headers and we'll be actively notified that there is something wrong and needs fixing if there is? This would be good to know, that way if we don't hear any complaints we know our headers are correct.

**Comment by Roger1952** [comment]
HMRC make the following comment:

"However, we expect your software applications to be compliant"

It's all very well having an expectation but unless they start paying attention to these comments it's not going to happen.

**Comment by dsrobinson** [comment]
I'm part of the transaction monitoring team at HMRC. I'll try to respond to the original post to provide some clarity:

> • All the HMRC API web site says is “we expect it will become compulsory to supply header information for this API from April 2019 to prevent fraud”. A week before this is supposed to go live a definitive statement is required, “expect” is not good enough, will it or won’t it?

From April 1, headers will be compulsory. We have communicated this to an developer subscribed to MTD VAT API. We do not plan immediately after April 2019 to reject MTD VAT messages from software applications that are non-compliant with the specification. We update the wording on the developer documentation once arrive at April 1.

> • As the sandbox has not bothered to provide a test environment for the headers how is it possible to know if an implementation is correct? Trying to capture a packet and email its content is not very accurate, especially as some of the header content will vary from call to call.

Test tools are coming, but in the interim we have offered to provide feedback on your specific case. Please send request for a review to SDSTeam@hmrc.gov.uk.

> • Judging from some of the questions and comments about the fraud headers in GITHUB the definition is not as clear and unambiguous as it should be. This makes the need for a proper test environment even more important.

There are many scenarios for how each developer will submit headers. Like any new documentation, we are working to clarify the specification based on questions developers raise. We do not want to simply increment the specification version which would change the goal posts for developers already submitting headers. We are focusing effort on providing test tools.
 
> • The description of the headers contains no information about errors. If a header is not as expected how will an application know, what errors will be returned?

Automated header validation is not in place. We are focusing on providing some test tools. The main way to know if you are submitting headers correctly is to submit a request for a review to SDSTeam@hmrc.gov.uk. 

> • Will an incorrect header result in a rejected submission?

No, we will not reject header submissions at present. We do not plan immediately after April 2019 to reject MTD VAT messages from software applications that are non-compliant with the specification.

> • What will be the response if the HMRC site actually looks at the headers and decides the message is fraud?

We will identify and investigate fraud following our already existing processes.

I hope that helps.  Again, I would encourage developers to submit there specific headers to SDSTeam@hmrc.gov.uk and we will help to feedback.

**Comment by sonicmule** [comment]
We sent an example of headers to the SDSTeam back on the 7th March.
We got an acknowledgement back informing us that it will be passed on to the relevant department, but heard nothing back since.

To see that there could be a fine imposed on developers who do not comply is very poor service and surely not enforceable if hmrc can't get back to developers in a timely manor!

**Comment by dsrobinson** [comment]
@sonicmule Yes, we have had a high volume of requests for reviews, but we are working through them.  As I have said, HMRC does not plan to reject MTD submissions. Please do email SDSTeam@hmrc.gov.uk to follow up your request and we can give you status where you are in the queue.

**Comment by sonicmule** [comment]
> 
> 
> @sonicmule Yes, we have had a high volume of requests for reviews, but we are working through them. As I have said, HMRC does not plan to reject MTD VAT API messages. Please do email [SDSTeam@hmrc.gov.uk](mailto:SDSTeam@hmrc.gov.uk) to follow up your request and we can give you status where you are in the queue.

Thanks for responding, we have not released our update to our customers as yet until we receive confirmation that the headers are ok.  Does this mean that we will not receive a fine if customers are submitting with the old headers before we get the new update to them?

**Comment by dsrobinson** [comment]
@Roger1952 The main way to get feedback is through the manual review process described above. Github comments should not really be relied upon as a main source of information, as it is not really designed to be our help desk.

**Comment by dsrobinson** [comment]
@sonicmule I'm not in a position to give you a clarity on when fines might be imposed for non-compliance. I'll re-direct you to my earlier statement that we do not plan immediately after April 2019 to reject MTD VAT messages from software applications that are non-compliant with the specification.

**Comment by Yottskry** [comment]
> Test tools are coming

MUCH, MUCH too late. I can't stress enough how pathetic HMRC have been regarding these fraud prevention headers. Your communication has been nothing short of woeful.

**Comment by sonicmule** [comment]
We will submit headers as per the specification to the best of our understanding - at least we are trying :-).
As our app is a desktop app and every users needs to contact our server to obtain the application key, we will block any user who is on an outdated version and provide a message informing them to obtain an update.

**Comment by Roger1952** [comment]
In the HMRC reply to the original question about error responses to bad fraud headers they state:

"Automated header validation is not in place."

This may well be the case, but even if it was the specification at https://developer.service.hmrc.gov.uk/api-documentation/docs/fraud-prevention DOES NOT DEFINE SPECIFIC ERROR RESPONSES TO BAD FRAUD HEADERS.

As the only thing developers have to go on is this specification it can only be assumed that if a fraud header in in someway unacceptable either:

1. One of the existing errors responses to an endpoint will be returned and the request will fail. 
2. Or, as per the specification no error will ever be returned and the request will never fail.

They can't have it both ways. You cannot implement proper software without a precise and unambiguous specification.

**Comment by dsrobinson** [comment]
@Roger1952  Appreciate you are frustrated. At this point, it's unlikely we will fail a request so no data can be submitted for the given request. We will provide feedback, however. For example, we will provide error and warning feedback.

**Comment by Roger1952** [comment]
Just received the following response which for some reason isn't shown here.

"Appreciate you are frustrated. At this point, it's unlikely we will fail a request so no data can be submitted for the given request. We will provide feedback, however. For example, we will provide error and warning feedback"

Yet again HMRC are using words like "unlike;y". This is not good enough. Will they fail a request or won't they. If they are not going to do it why not just say "no we will not fail a request"? 

Back to the point above and the original question, "error feedback" is not good enough. Error responses need to be defined part of the specification. This is a fairly simple but fundamental concept. 

Is there any chance of getting a definitive, non-ambiguous answer? Please?

**Comment by shaunl23** [comment]
I have now received feedback on my headers!!
In any cases where I haven't been able to provide a value and the specification says to "leave it empty" I have been asked on the feedback why I haven't included the header. This worries me in terms of rejection with the headers blank

**Comment by Yottskry** [comment]
> 
> 
> I have now received feedback on my headers!!
> In any cases where I haven't been able to provide a value and the specification says to "leave it empty" I have been asked on the feedback why I haven't included the header. This worries me in terms of rejection with the headers blank

We had the same thing for some of the values we *did* provide! They wanted me to clarify how the Device ID was generated and how it was guaranteed to be persistent and unique (hint: there is no guarantee and HMRC should know that); they wanted me to explain why we weren't including a Windows user name for the user (my fault, I overlooked it); and they wanted me to explain why we didn't include the scale factor of the display devices (god knows why they want this information).

**Comment by shaunl23** [comment]
I'm having trouble getting the scale factor and MAC addresses in VB.NET.
Can't think of a way to get scaling factor, and I don't think NetworkInterface.GetAllNetworkInterfaces, .GetPhysicalAddress() is what they are looking for. The example give %3A in the string which is ":" and GetPhysicalAddress() does't have any colons in it!

If anyone has any ideas to share?

**Comment by Roger1952** [comment]
The scaling factor is easy. Set it to 1.

**Comment by Roger1952** [comment]
IPv6 addresses contain ":"

Just a thought, but for addresses do they want IPv4 or IPv6 or both?

**Comment by shaunl23** [comment]
Thanks ;)
I think it's 4 and 6, according to the documentation:
A list of all local IP addresses (IPv4 and IPv6) available to the originating device.

**Comment by Yottskry** [comment]
> The scaling factor is easy. Set it to 1.

The scaling factor on my primary monitor is 1.25.

**Comment by Roger1952** [comment]
Pretend it's 1.

**Comment by Yottskry** [comment]
> 
> 
> Pretend it's 1.

Fortunately we have a desktop app and I can calculate the scale factor fairly easily, but your response highlights exactly my problem with these stupid headers: we could all lie to make most of the values believable and HMRC would be none the wiser. I could say that every screen has a resolution of 1280x1024 and a colour depth of 32 bits. Or I could pick a size at random for any given machine and maintain it for that machine. Anyone who wants to play the system can do it. These headers are just so ill-conceived it would be funny if it weren't such a pain in the ass to implement them.

Isn't it funny how HMRC take so long to respond about them too? It's like every issue we raise they have to go off and have a meeting and discuss it.

**Comment by Roger1952** [comment]
All but one of the examples for Gov-Client-User-Agent use XP as the OS. Do HMRC know how old and unsupported that system is? Two examples have a computer running two operating systems, one with XP and 98 and the other with XP and NT! How can this be?

Why not include some realistic examples and also some examples that will match reality with respect to percent encoding.

**Comment by KenRandall** [comment]
I asked the SDSTeam to check the fraud headers I was submitting to th live system on 6th March. I then had to chase them again on 21st March. They responded on 29th March with some changes I needed to implement (mainly that I was escaping the headers). They said that I needed to make the changes by 10th April. I changed them accordingly and the very next day I sent them an email asking them to check them again. so far I have had no response!

**Comment by shaunl23** [comment]
I think this highlights the frustration we experience. We're more than willing to change our headers to get them compliant, but it takes so long to get any feedback that it makes things difficult. It's like a one sided conversation some times

**Comment by Yottskry** [comment]
Any comment, @SDST-HMRC ? We're getting seriously fed up with your lack of communication. We are asking the right questions and getting no answers. If you don't have the staff or expertise to back up the implementation of these headers, don't implement them!! We are doing our best to be compliant, but it's taking a ridiculous amount of time to get feed back. Meanwhile, time is marching on. Customers will be using the systems soon and any significant changes get harder to implement.

**Comment by Roger1952** [comment]
The number of comments here, saying that folks who have managed to get a response have had to make changes, would tend to confirm that the specification is of very poor quality. If it was any good, nobody would be misinterpreting it.

P.S. If HMRC ever read this, I've STILL not had definitive answer about error returns (point 4 of the original post).

**Comment by adamdavi3s** [comment]
A month on and I've still not had a response from the SDSTeam about whether my headers are acceptable....

**Comment by AndyYouens** [comment]
Got no chance with ours then, we sent last week :-(

**Comment by cb-rfk** [comment]
Also sent ours last week and I had a reply today saying that they've received the email but are working through a considerable backlog at present and would appreciate my patience while they reply...

**Comment by Yottskry** [comment]
> 
> 
> A month on and I've still not had a response from the SDSTeam about whether my headers are acceptable....
> This is despite me "doing the right thing" and building the headers and immediately responding to their email on 6th March asking people to validate them

I must have got lucky with ours then, as I sent ours for verification on the 11th of March and had a reply about a week later.

**Comment by mtd-api-team** [comment]
Hi all, if you have any further questions that require HMRC support, please email SDSTeam@hmrc.gov.uk directly and they will be able deal with your queries. Otherwise, please refer to https://github.com/hmrc/vat-api/issues/565.
