### ISSUE TITLE
 Revocation of Authority

### ISSUE THREAD

**Issue by Roger1952** [hmrc/vat-api#529]
The sandbox authorisation page has a link to revoke authority.

“This authority will last for 18 months. You can remove this authority at any time”

The page at the end of the link does not recognise sandbox user login credentials. 

1.	If it’s not designed to work why include it?
2.	If it is meant to work and it doesn’t can it be fixed please?
3.	Without this link working how can  revocation of authority be properly tested without some sort of bodge to the software?

**Comment by james-work-account** [comment]
Hi @Roger1952 - unfortunately this is an auth issue and is out of our scope. Please contact SDSTeam@hmrc.gov.uk for further queries around this issue.

**Comment by Roger1952** [comment]
I would have thought that this was an HMRC problem and if this site is not for getting answers to HMRC API problems what is it for?

**Comment by james-work-account** [comment]
Hi @Roger1952 - this is the VAT API Issues page where you should raise issues you have specifically with the VAT API. Anything related to auth is out of scope of this Issues page, because our team doesn't maintain any auth-related functionality.
Please raise non-technical or platform-related issues with the Software Development Support Team via SDSTeam@hmrc.gov.uk or through https://developer.service.hmrc.gov.uk/developer/support

**Comment by Roger1952** [comment]
A proper joined up approach to defining and supporting this API would really help. Different bits of HMRC passing responsibly to other bits of HMRC is not helpful, but if that's the way things are we all will just have to live with it. Thanks for your comments.

**Comment by Roger1952** [comment]
For anybody who is interested I got this response.

While we do not publish or support a ‘TEST’ revoke scenario, I can confirm it is possible to view the process in the test area via the actual process of ‘Granting Authority’

1. When you redirect out of your software to perform the initial Grant Authority you are provided a basic page with a continue button (the link to revoke on that page directs to the live service not our test area).
2. If you log in with your previously used TEST ID & PASSWORD you will be asked if you want to Grant authority again and provided a 2nd link to remove authority and this will link you to the test server.
3. When you select the ‘remove this authority’ link you will be shown a START now button
4. When you log in at this stage you will see your test product named and if you expand this you will be provided a remove authority 
5. Once selected you will be asked to Confirm and this will remove authority for the product. 

As I say, this is not a published scenario but I hope it helps

Only one small problem. I get error ”HTTP 501 Not Implemented” when you select the Start Now in step 3?

I'm waiting for an explanation
