### ISSUE TITLE
Negative Box 5

### ISSUE THREAD

**Issue by SheepShearer** [hmrc/vat-api#530]
I've read the closed threads on this subject, but just so I'm clear could someone please confirm my understanding that if BOX 5 results in a negative number we still submit it as a positive number (making sure our user is aware of this impending refund) and then rely on HMRC to notice the negative result of Box 3 and 4 and issue the refund. 

Is it correct that the refund is acknowledged somewhere in the 'Retrieve VAT Payments' end point  - I cant see anything mentioning a VAT type of 'VAT return credit charge' in the documentation? Maybe its in the 'type' field?

Thanks,

**Comment by rajitha0007** [comment]
Yes, that’s correct. Otherwise you’ll get an error, if you submit the value as a negative number.

**Comment by SheepShearer** [comment]
Thanks rajitha0007,
Yes, I do get an error if I submit a negative number, as I also do if the numbers do not add up.  
Do you know if a refund due will be marked in the Retrieve VAT endpoint somehow? 

Thanks

**Comment by rajitha0007** [comment]
@SheepShearer  Answer is 'Yes' as per my previous investigations, they will validate the Box 3 & 4 values to identify the box 5 is a refund or a payment. 
HMRC API team can further confirm this.

Please see the below given Box 5 explanation from HMRC website. (https://www.gov.uk/guidance/how-to-fill-in-and-submit-your-vat-return-vat-notice-70012 ) 
**Box 5 net VAT to pay to HMRC or reclaim**
"Take the figures in boxes 3 and 4. Deduct the smaller from the larger and enter the difference in box 5.
This figure will be calculated automatically if you’re completing your return online.
If the figure in box 3 is more than the figure in box 4, the difference is the amount you must pay. If the figure in box 3 is less than the figure in box 4 we’ll credit your account and repay the balance, subject to any enquiries we may need to make."

**Comment by MikeCongdon1** [comment]
Hopefully the paymentIndicator field in the /organisations/vat/{vrn}/returns response will help answer your question Sheep.
https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0#_submit-vat-return-for-period_post_accordion

paymentIndicator
Is DD if the netVatDue value is a debit and HMRC holds a Direct Debit Instruction for the client. Is BANK if the netVatDue value is a credit and HMRC holds the client’s bank data. Otherwise not present.

**Comment by narendravijayarao** [comment]
Hi SheepShearer,

The value to be entered in box 5 (netVatDue) is always positive (as indicated in the range), the absolute difference between totalVatDue and vatReclaimedCurrPeriod.

You can choose to follow the "deduct the smaller from the larger" (130-50 = 80) approach, or you can absolute the difference between box 3 and box 4 (i.e. |50-130|= 80).

To identify a repayment based on the 9 box return, box 3 (totalVatDue) amount will be less than in box 4 (vatReclaimedCurrPeriod). Once updated the Liability will have a chargeType of either:
VAT return debit charge (or) VAT return credit charge.

Thanks,

**Comment by SheepShearer** [comment]
Thanks all,
