### ISSUE TITLE
Fraud Prevention

### ISSUE THREAD

**Issue by heythisiskishore** [hmrc/vat-api#531]
Dear Team,

	We are developing a Web Application for the MTD VAT software. As it is mandated to implement the Fraud Prevention for the MTD VAT submissions but you didn't gave any clear information regarding this. I need to get some information regarding the following headers that from where do I get the information.

	Can any one suggest that from where do we get the information for the below headers.

Gov-Client-Public-Port:
	What do you mean by Client-Public-Port, from where do I get this information.
	
Gov-Vendor-Version:
	What do you mean by Vendor-Version, from where do I get this information. What type of details that I need send for the WEB_APP_VIA_SERVER.

Gov-Vendor-License-IDs:
	What do you mean by Vendor-License-IDs, from where do i get this information.

Gov-Vendor-License-IDs: my-licensed-software=8D7963490527D33716835EE7C195516D5E562E03B224E9B359836466EE40CDE1

Gov-Vendor-Forwarded:
	Can any one suggest that from where do we get the information for the above header.

And also I am getting lots of confusions over the 'Gov-Vendor-Forwarded' like what type of IP addresses we need to pass for the given example

Gov-Vendor-Forwarded: by=33.252.57.234&for=57.4.28.41,by=188.87.76.95&for=209.210.136.84,by=176.30.57.118&for=150.94.192.63

From where do I get all those 3(by) + 3(for) IP addresses and also can you please explain in detail about those IP addresses.

Thanks in advance.

**Comment by ma3574** [comment]
# Please see: 
https://developer.service.hmrc.gov.uk/api-documentation/docs/fraud-prevention

As the documentation is quite large please use the search functionality of your browser to find the relevant guidance on the header you would like more information on. E.g. Searching for `Client-Public-Port` leads to the following info:

# Client-Public-Port is: 
> The public TCP port that the originating device uses when initiating the request.
e.g. `Gov-Client-Public-Port: 12345`

As the Fraud Prevention Headers are not managed by the VAT API team we are not able to assist further. Any further queries should be directed to SDSTeam@hmrc.gov.uk who will be able to liaise with the relevant team to help you reach a resolution. 

We are also unable to assist with specifics oh how you should implement the headers in your chosen programming language/framework as we are agnostic and simply provide the VAT API.

**Comment by heythisiskishore** [comment]
Dear Team,

Sorry to say this. We are not satisfied with the response what you have given.

Looking forward to the above query.

In addition to this we also need to get clear information about the 'Gov-Client-Multi-Factor' also.

Awaiting for your reply.

**Comment by heythisiskishore** [comment]
Hi there,

Thanks for your response!

Could anyone please clarify on what details we need to send to HMRC for below two headers.

1. Gov-Vendor-License-IDs
2. Gov-Client-Multi-Factor
3. Gov-Vendor-Forwarded

In HMRC documentation it is not clear what details to be included in the header.

Awaiting your response!

**Comment by paulfeakins** [comment]
Also awaiting a response on this.

**Comment by hmrc-api-team** [comment]
Hi @paulfeakins 

As previously stated, the Fraud Prevention Headers are not managed by the VAT API team so we are not able to assist further. Any further queries should be directed to SDSTeam@hmrc.gov.uk who will be able to liaise with the relevant team to help you reach a resolution.

Kind regards

**Comment by paulfeakins** [comment]
Thanks, have emailed.
