### ISSUE TITLE
What happens when a user ceases to trade mid period?

### ISSUE THREAD

**Issue by GrahamHDawson** [hmrc/vat-api#532]
The API now prevents submissions before the VAT period has ended.
So what happens in cases where a user ceases to trade mid period.
How will that final submission be done?

**Comment by daniel-andrews1994** [comment]
Hi Graham,

As part of VAT De-registration, the user's current obligation would have the periodTo date automatically adjusted.

Thanks,
Daniel

**Comment by GrahamHDawson** [comment]
Thanks for that Daniel.

Maybe this is something that could be added to the Wiki?
