### ISSUE TITLE
Obligations not updating in sandbox mode

### ISSUE THREAD

**Issue by youriv2019** [hmrc/vat-api#535]
I have successfully submitted a VAT return in the Sandbox mode. The obligations are still the same however with one with a status of outstanding even though it has been submitted.

Is this normal behaviour in sandbox?

**Comment by GrahamHDawson** [comment]
Yes - it's normal for the sandbox.

**Comment by AndyYouens** [comment]
Not a great dev/testing environment 😒

**Comment by GrahamHDawson** [comment]
Actually, in this case it does mimic the production environment.
See the Wiki - Production Timings section for details, but basically you can't assume even in 'live' that the Obligations will be updated immediately - so have to provide other means of letting end-users know that the submission has been successful and not to repeat it.

**Comment by AndyYouens** [comment]
how can we then, check if an obligation has been submitted, but you havent updated the status?

**Comment by cb-rfk** [comment]
We do it by storing the VAT receipt when the submission is made, and when we subsequently display the list of obligations to the user (seconds or days later), we cross check if we have a receipt for any "Open" obligations and display them with a "Being Processed" label.

**Comment by ddaddy** [comment]
If you use the header `Gov-Test-Scenario = QUARTERLY_NONE_MET` and submit the obligation, then switch to use the header `Gov-Test-Scenario = QUARTERLY_ONE_MET` it'll show your submitted figures as the one that shows as fulfilled.
You can keep going through `QUARTERLY_TWO_MET` `QUARTERLY_THREE_MET` & `QUARTERLY_FOUR_MET`
