### ISSUE TITLE
CLIENT_OR_AGENT_NOT_AUTHORISED recuring

### ISSUE THREAD

**Issue by COLASYSTEMS** [hmrc/vat-api#536]
Hi,
I know this is an oft visited issue but I'm stumped (or just tired).
We have a functioning application in the sandbox successfully submitted a VAT return, getting obligations etc. However today created a new user using the web page tool NOT the API and successfully logged in and obtained Access Token as usual but get CLIENT_OR_AGENT_NOT_AUTHORISED error when trying get obligations.  
Just a few minutes earlier we were happily using a previous user to get obligations and view previously submitted return.
yes we updated tour system with he VRN from the newly created user.
I have deja vu a little on this as I think I've had the error before but did it just go away ?

**Comment by les-portugal** [comment]
@COLASYSTEMS we had the same problem yesterday, but this seems to have just started working for us again.
