### ISSUE TITLE
Allow Resubmitting / Amending Returns

### ISSUE THREAD

**Issue by MikeCongdon1** [hmrc/vat-api#537]
**Is your feature request related to a problem? Please describe.**
Please allow for a way to amend submitted returns. With this, increment an index, view updated_on, see historical returns submission data for a given periodKey. This is a feature request along the lines of: #106 

**Describe the solution you'd like**
I would like to see a flag (this_is_a_resubmit : true), or header set.header(this_is_a_resubmit, true) that allows for the more recent submission to be accepted as the new Returns submission for a given period.

It would be nice if:
- The HMRC API would store/track "updated on" timestamps on returns submitted
- revision index for returns (blank for first submit, then increment an integer with each subsequent submission.
- track the historical values with each submission so a user can see all the values for when they submitted a return for 18AD on <timestamp>, then resubmitted 18AD with a new gross sales value. (this would be rev_1 updated_on <timestamp_new>. It'd be nice for the user to be able to look at 18AD rev_0 at this time to make sure the other values didn't change.

**Describe alternatives you've considered**
Submitting it right the first time is the alternative I presented to my client. They weren't exactly thrilled with this proposition. Perhaps there is an alternative through HMRC MTD I should be aware of?

**Additional context**
Sometimes Returns are not submitted properly the first time. It would be nice to be able to have recourse within the software.

**Comment by narendravijayarao** [comment]
Hi @MikeCongdon1,

This is not likely to become a consideration of the MTD programme as the VAT 100 submission includes an explicit declaration that it is correct (represented in the Submit VAT Return API endpoint by the boolean "finalised", which must be set to *true* ).
The onus being on the user to satisfy themselves that the data is correct, before submitting.

The following webpage includes advice on error correction of MTD VAT submissions:

https://www.gov.uk/government/consultations/making-tax-digital-reforms-affecting-businesses/making-tax-digital-for-vat-legislation-overview 

Thanks,

**Comment by ma3574** [comment]
I hope this resolves your issue. If not please contact SDSTeam@hmrc.gov.uk for further clarification.
