### ISSUE TITLE
Choosing the correct Gov-Client-Connection-Method

### ISSUE THREAD

**Issue by arbogastr** [hmrc/vat-api#538]
Hello!
Please help me to identify the correct connection method for the application for which I am implementing fraud prevention headers. Software is a multi-tier system, where the user interacts with the system using the thin client installed on his desktop. This client in turn interacts with application object server located in the organization environment, and all the the requests are being sent from this application object server directly to HMRC. Application object server is a windows service. 

The question: is this DESKTOP_APP_DIRECT or DESKTOP_APP_VIA_SERVER?
 
Description for the DESKTOP_APP_VIA_SERVER says: "Installed desktop application connecting through intermediary servers to HMRC". What are these intermediary severs? Can you give an example? Are they some third-party servers?

**Comment by mtd-api-team** [comment]
Hi @arbogastr, if you have any questions that require HMRC support, please email SDSTeam@hmrc.gov.uk directly and they will be able deal with your queries. Otherwise, please refer to https://github.com/hmrc/vat-api/issues/565.
