### ISSUE TITLE
End point for healthcheck

### ISSUE THREAD

**Issue by nnotsofun** [hmrc/vat-api#54]
Hi,

Is there an endpoint you'd advise we can use to to see if the MTD VAT service is down? i.e. a ping endpoint? We'd like to incorporate it into our health checks - and hopefully one that doesn't use up one of our client requests (impacting 150 requests/minute)?

AFAIK - only hello world can do this but will there be one for VAT?

Cheers,

Nick

**Comment by hicnar** [comment]
Thank you for your query.
It has been escalated and as soon as we have the answer it will be published in this thread.

**Comment by hicnar** [comment]
@nnotsofun 

Currently there is no provision for API specific health check endpoints. In the case that the service goes down then we will reply with a relevant, descriptive status code (typically in the scenario above 503 Service Unavailable). Clients should build there applications to handle with these codes in a graceful manner.
