### ISSUE TITLE
invalid_grant refersh_token is invalid

### ISSUE THREAD

**Issue by JohnAherne** [hmrc/vat-api#540]
The docs say that refresh tokens are valid for 18 months.

But I am getting random but fairly frequent invalid grant responses. This suits me since I was wondering how I could test for this scenario.

This makes me wonder if this is meant to happen and if so, how frequently will it occur, so I can check that my code is handling the event properly.

Of course if this is not to happen I need to see why it is occurring and check what the problem is.

Also is there a way to trigger the invalid_grant response to create the required response.

**Comment by ma3574** [comment]
Hi, the VAT API team do not own/manage the Auth side of the API as such we are not able to directly assist.

Please contact SDSTeam@hmrc.gov.uk notifying them that you have been sent to them by the VAT API team.

**Comment by mathiasbanda** [comment]
Failing to submit VAT this morning with this error again. Appears to get obligations okay but failing to submit - Just this morning was okay yesterday
