### ISSUE TITLE
Fraud Header : Gov-Vendor-Forwarded and how to construct it

### ISSUE THREAD

**Issue by COLASYSTEMS** [hmrc/vat-api#542]
Hi,
I'm sure I'm over thinking all this but here goes ...
I'm thinking by now that there must be some standard pattern for how to approach this.  Reading the requirement for this in https://developer.service.hmrc.gov.uk/api-documentation/docs/fraud-prevention it states that it requires "A list that details hops over the internet between services that terminate TLS."

Is there devil in the detail in this statement.  Is it saying that it only wants those specfic hops subsequent to an initial TLS termination that go over the internet.  I know we live in a world of hyper connectivity where it is feasible that a router terminates TLS at a domain boundary and then re-encrypts and routes off somewhere over the internet e.g. to a cloud provider but even in that scenario it seems to me the only information available to the programmer is the X-Forwarded-For HTTP header which MAY contain a list of IP addresses hops of client -> app server via various networking kit, but is the requirement really asking us to look at at IP address subnet masks to see if any of the hops were outside of the "local" network. 

Looking at the example in the section in the fraud prevention link above it seems to be very much suggesting that is what we need to be doing.

Why doesn't the requirement just ask us to provide the content if any of the  X-Forwarded-For header  
Thanks, 
Shaun.

**Comment by mtd-api-team** [comment]
Hi @COLASYSTEMS, if you have any questions that require HMRC support, please email SDSTeam@hmrc.gov.uk directly and they will be able deal with your queries. Otherwise, please refer to https://github.com/hmrc/vat-api/issues/565.
