### ISSUE TITLE
Uniqueness and permanence of Gov-Client-Device-ID

### ISSUE THREAD

**Issue by Yottskry** [hmrc/vat-api#543]
We have recently had correspondance from HMRC to say that our Gov-Client-Device-ID is not sufficiently permanent or unique as we're just sending the machine name. The suggestion from HMRC is to "generate a UUID that is permanently stored in a hidden file or in the registry".

I would be interested to know how HMRC can guarantree permanence of ANY file or registry entry on a customer's machine. Could someone from HMRC's Fraud Prevention Header team please explain how permanence or uniqueness can be guaranteed in the following scenarios:

1. The user runs the MTD software and generates a UUID and then subsequently rolls their OS back to previous date. Any registry setting will be lost and a new UUID will be different to the first.

2. The user's machine's OS is erased and re-installed, losing any files and registry settings.

3. A user runs the MTD software and generates a UUID stored in the registry and their OS is subsequently imaged and used on other machines. The UUID is now not unique.

A further issue occurs in that writing to HKEY_LOCAL_MACHINE requires elevated privileges that a user may not have, and writing to HKEY_CURRENT_USER will only be unique for a specific user on a machine and NOT to the machine itself. 

I do not believe that HMRC have fully thought these header requirements through. There has not been enough engagement with developers and the information on them is still filtering through VERY late in the day for an April start. 

If developers here sound like they're getting frustrated IT'S BECAUSE WE ARE. We are fed up with being drip-fed snippets of information for headers that have been changed numerous times since initially announced and contain information that can be very difficult to obtain. The lack of facilities to confirm header compliance in the Sandbox is the icing on the cake of how thoroughly disorganised HMRC have been on this issue.

**Comment by cb-rfk** [comment]
Well said.  

What's even more crazy is that they expect to receive that info for browser-based requests too.  Sure, we could store a cookie on the user's PC, but that would be even less permanent or unique than a registry value!

We submitted our headers for review this week so I'm waiting with interest on what feedback we get...

**Comment by JeeBeePee** [comment]
We do store a cookie on the user's machine for our browser based app. I can't see what else you can do.

**Comment by Yottskry** [comment]
> We do store a cookie on the user's machine for our browser based app. I can't see what else you can do.

That wouldn't meet the "permenance" requirement though. I have no idea how web apps like yours are supposed to meet HMRC ridiculous requirements. It's hard enough with a desktop app. The fact that any developer (or anyone in IT in general) can think there's any way to guarantee permanence is laughable.

I'm absolutely convinced that HMRC's FPH team don't know what they're doing. These headers are the so badly thought through, yet it's us who whill be liable if we can't adequately implement them!

**Comment by ruffle-b** [comment]
Storing a cookie is useless as folk are very likely to erase them, use a different browser or a different machine/phone/device.

**Comment by Yottskry** [comment]
The lack of response from HMRC seems to suggest that the realisation these headers are ill-conceived is starting to dawn on them...

**Comment by Yottskry** [comment]
11 days ago someone was first assigned to this from HMRC. 11... and counting.

I cannot believe the staggering ineptitude from HMRC. Departments don't seem to talk to each other; one department will refer us to another who will refer us back to the first department; no one seems to take responsibility for these ridiculous headers; people are assigned to forum posts, then other people are assigned. Meanwhile no one actually deals with the issues, and all the time the clock is ticking. **This API is now live and our customers are expected to use it, yet the specification is inadequate and, seemingly, incomplete and answers to questions are not forthcoming**.

**Comment by mtd-api-team** [comment]
Hi all, if you have any Fraud Prevention questions that require HMRC support, please email SDSTeam@hmrc.gov.uk directly and they will be able deal with your queries. Otherwise, please refer to https://github.com/hmrc/vat-api/issues/565.
