### ISSUE TITLE
Issue when make request to HMRC API. It trigger a CORS preflight.

### ISSUE THREAD

**Issue by Saipalazhy** [hmrc/vat-api#544]
My browser  tries to make an API call to the HMRC API,  but when the request is generated, it rejects the HTTP call because  it's cross origin.
 I wish to know is it any possible way to solve this issue with any other methods.
So if there is any better way please help me.

**Comment by james-work-account** [comment]
Is the call being made client-side or server-side? There are currently no plans for MTD to support CORS.
