### ISSUE TITLE
Retrieve Obligations - Date Parameters have no effect

### ISSUE THREAD

**Issue by highlysceptical** [hmrc/vat-api#545]
I am trying to develop a bridge in the Sandbox environment (using Delphi / REST components), but am having issues with retrieving obligations.

By trial and error, I have worked out that if use "from" and "to" parameters that are more than 365 days apart, I get an HTTP/1.1 400 Bad Request error.  Is this by design?

However, provided "from" and "to" are not more than 365 days apart, it doesn't matter what values I provide, as the query returns all obligations anyway, irrespective of whether they are within the date range I have chosen or not.  Again, it this by design?

If these issues are by design, they don't make much sense to me from a logical point of view.  Conversely, if this is not what is supposed to happen, are the issues due to the platform I am using?

Can anyone throw any light on this?

Thanks in advance.

Andrew

**Comment by adamdavi3s** [comment]
Yes if you read the documentation you will see there is a maximum time span of 365 days on that end point. However you can just leave the date from / to off and request status O to return all open obligations.

The sandbox data is ropy at best and returns canned data which I don't think reflects the dates but someone else might clarify

**Comment by james-work-account** [comment]
Hi @highlysceptical - the `from` & `to` dates can only span up to a year, so when you provide dates greater than a year you'll get an `INVALID_DATE_RANGE` error. If you just want all open obligations though, you can omit the `from` & `to` dates and set status to `O`.

If your request is successful, you'll always get the same data back - the stub we have built just returns dummy data. There are some things you can do to change the data returned (e.g. set `status=O`) but for the most part, to simulate different responses you'll need to provide different Gov-Test-Scenario headers (see here under "Test data": https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0#_retrieve-vat-obligations_get_accordion).

I hope this answers your queries. If you need further assistance, please reply to this thread.

**Comment by highlysceptical** [comment]
James

Thanks for your helpful comments.
