### ISSUE TITLE
Requests failing for non pilot businesses 

### ISSUE THREAD

**Issue by JeeBeePee** [hmrc/vat-api#546]
It's April 1st but we are still seeing client or agent not authorised errors for non pilot VRNs.

Shouldn't it now be possible to make an MTD request for all VRNs now?

Of course it may be the user has typed in the wrong VRN, but I can't be sure done you've used the same error message for two different scenarios.

**Comment by markogrady** [comment]
All companies must sign up to MTD

**Comment by ma3574** [comment]
@markogrady is correct. 

If you face issues with customers in production please contact SDSTeam@hmrc.gov.uk

**Comment by JeeBeePee** [comment]
Tried the SDS email yesterday for a production issue.  Still awaiting a response 24 hours later.  Issue: obligations endpoint returns an "open" return which has actually been filed and can be retrieved from the return endpoint.  End user worried that the return hasn't been filed.  Deadline in a few days.  Is email the only way to raise production issues?

**Comment by adamdavi3s** [comment]
If you read the documentation you will see it can take up to five days for it to update, although it’s usually pretty instant.
Did you get the form bundle number back? If so then give them a call

**Comment by JeeBeePee** [comment]
Didn't get a response from the endpoint when filing, so no form bundle number. The peculiar thing is that the obligations endpoint returns 3 fulfilled, 1 open. The returns endpoint returns nothing for the period keys of the 3 supposedly fulfilled obligations, but does return the correct data for the 1 supposedly open obligation. Anyway, getting O/T, and this one's closed anyway... my (secondary) point was that the SDS email for prod issues is not as responsive as the GitHub for dev questions.
