### ISSUE TITLE
When should VAT returns be populated in production?

### ISSUE THREAD

**Issue by markogrady** [hmrc/vat-api#547]
I have now had hundreds of people sign up but occasionally I get a 404 and the customer has no vat returns on the API or in their dashboard on the HMRC portal. One customer has had confirmation and been signed up for a week. The customer previous return ended on the 28th Feb. I would have thought looking at the documentation that 1st March would mean his returns returns should be automatically populated.

I have contacted the SDSteam they have told me the returns should populate in 72 hours (which it hasn't) and to contact live services. The customer contacted live services and they said come back later.

As we seem to get better answers here I thought I would add it. I have other issues with other peoples accounts and it's getting tough to answer the questions and spend so much time contacting people. Could at least in this interim period the SDSteam have access to coordinate these type of calls?

**Comment by ma3574** [comment]
Hi @markogrady 

Sorry to hear you are facing issues but unfortunately SDST are the ones best placed to help resolve the issue. If you contact them again with specific details such as the VRN, timelines of when things happened, the exact data you are expecting (obligations/returns/etc.). They can then follow up with the relevant teams and help to reach a resolution.
