### ISSUE TITLE
Self Assessment Making Tax Digital UTR wrong format

### ISSUE THREAD

**Issue by phani29oct** [hmrc/vat-api#548]
Hi Team,

While I am working with Self Assessment Making Tax Digital and fetching Test Users using SandBox API. I am able to fetch the user details in that UTR format is "Y596379780" but in the test result it is displaying as "1000057161" 

After using this UTR I am getting response as "SA_UTR_INVALID"

Can anyone help me on this

Thanks for the help in advance

**Comment by james-work-account** [comment]
Hi @phani29oct - please raise any problems with the Self Assessment API in https://github.com/hmrc/self-assessment-api/issues where they will be addressed. This Issues page is for issues specifically with the VAT API.
