### ISSUE TITLE
Manual editing of fraud prevention headers before submission

### ISSUE THREAD

**Issue by arbogastr** [hmrc/vat-api#549]
Hello!
Is it allowed to provide an opportunity of manual editing of fraud prevention headers before submitting the request to HMRC? Since there are still some questions about how to obtain some of the headers, can we as software developers give an opportunity of manual editing these headers by the user before sending?

It would help to:
- Submit headers that can be determined by external tools, but can't be easily obtained automatically inside the system.
- Support sending headers which became mandatory after changes in our software were released.

**Comment by GrahamHDawson** [comment]
Wouldn't allowing manual entry defeat the purpose of the anti-fraud headers?

Maybe if you state your application type (desktop, web etc) and which specific header(s) you have problems with someone can suggest a solution.

**Comment by JeeBeePee** [comment]
Downvote for this suggestion; disregarding the fact that it would render the headers pointless, I don't want to build and support a UI for this sort of thing.

**Comment by arbogastr** [comment]
Thank you for your inputs, GrahamHDawson and JeeBeePee. I agree with you, that it is not a good idea to edit these headers manually.

As for the particular headers, I have a question regarding the Gov-Client-Connection-Method which should be chosen for the system I am working in. I asked this question in another thread but still got no response:

https://github.com/hmrc/vat-api/issues/538

**Comment by mtd-api-team** [comment]
Hi all, if you have any Fraud Prevention questions that require HMRC support, please email SDSTeam@hmrc.gov.uk directly and they will be able deal with your queries. Otherwise, please refer to https://github.com/hmrc/vat-api/issues/565.
