### ISSUE TITLE
HTTP Headers for Fraud Prevention

### ISSUE THREAD

**Issue by arun-arunramesh** [hmrc/vat-api#550]
I am from the development team of our company, who is part of building the Product to submit VAT via MTD. We are building a product that will be available to and used by our company only to submit quarterly VAT returns. There will be no other users apart from the one user (Government Gateway user ID) that is already available today. This will not be publicly available and is for the internal use of our company.

Our product will be Mule based and will be hosted on the AWS platform. The product on AWS-Mule will directly invoke HMRC APIs for getting a token and submitting VAT return. There will no intermediate hops or any vendor involved in between. The product will again be used by only our company and no third party or vendor is involved.

We were working on the http headers for Fraud Prevention and had questions for the below headers. We determined our Application Connection Method as OTHER_VIA_SERVER and so the headers look like below:

**Gov-Client-Connection-Method**: OTHER_VIA_SERVER

**Gov-Client-Public-IP**: IP of the integration product deployed on AWS-Mule (we have this info)

**Gov-Client-Public-Port**: We are finding out this info

**Gov-Client-Timezone**: UTC-7/UCT-8

**Gov-Client-User-Agent**: We are finding out if we can get this info from AWS-Mule. Can it be " / / ()" if we are unable to get this info?

**Gov-Vendor-Public-IP**: Since we are the vendor ourselves, we think this will be the same as Gov-Client-Public-IP 

**Gov-Vendor-Forwarded**: As we are product owner as well as product user without any hops, will the by and for will be the same "Gov-Client-Public-IP" like by=x1.x2.x3.x4$for=x1.x2.x3.x4?

Do these headers look correct for our use case?

**Comment by cb-rfk** [comment]
I'm not going to comment directly on the headers as you guess is as good as mine basically (though your timezone one doesn't look like it matches the exampes to me...).

However, I really wonder whether you wouldn't be better off buying in third party bridging software, or something you can export your data into, for what appears to be your small use of the system.

My feeling is that he api will evolve quite substantially over the next couple of years and you'll find it an ongoing job to keep up to date with it...

**Comment by Yottskry** [comment]
"Gov-Client-User-Agent: We are finding out if we can get this info from AWS-Mule. Can it be " / / ()" if we are unable to get this info?"

If you cannot retrieve anything, the advice is to leave the header blank or omit it entirely. So rather than "/ (/)" it should probably be left out.

**Comment by arun-arunramesh** [comment]
> I'm not going to comment directly on the headers as you guess is as good as mine basically (though your timezone one doesn't look like it matches the exampes to me...).
> 
> However, I really wonder whether you wouldn't be better off buying in third party bridging software, or something you can export your data into, for what appears to be your small use of the system.
> 
> My feeling is that he api will evolve quite substantially over the next couple of years and you'll find it an ongoing job to keep up to date with it...

Mule is our enterprise integration platform and so we are not using any third party software or bringing anything new into the mix, as long as Mule can support the integration.

On the timezone, I think I pasted the wrong value. It should be UTC-07:00/UTC-08:00

**Comment by arun-arunramesh** [comment]
> "Gov-Client-User-Agent: We are finding out if we can get this info from AWS-Mule. Can it be " / / ()" if we are unable to get this info?"
> 
> If you cannot retrieve anything, the advice is to leave the header blank or omit it entirely. So rather than "/ (/)" it should probably be left out.

We are not able to find out the complete information. And as per the guidelines, looks like this header cannot be omitted.

**Comment by Yottskry** [comment]
> And as per the guidelines, looks like this header cannot be omitted.

The guidelines specify that where a value cannot be obtained the header can be omitted.

> Header values cannot be collected

>In some cases, while the header itself is required for your connection method, we anticipate you might not be able to collect a value because:

>>    of operating system or platform restrictions
    of security measures reasonably beyond your control
    the header is not applicable, as called out explicitly by the header documentation

> Only in these cases, you must submit the header with an empty value or omit it entirely. You must not supply null values.

**Comment by mtd-api-team** [comment]
Hi all, if you have any Fraud Prevention questions that require HMRC support, please email SDSTeam@hmrc.gov.uk directly and they will be able deal with your queries. Otherwise, please refer to https://github.com/hmrc/vat-api/issues/565.
