### ISSUE TITLE
Agent authorisation - Why unauthorised?

### ISSUE THREAD

**Issue by PeterGGreen** [hmrc/vat-api#552]
![AgentAuth](https://user-images.githubusercontent.com/43069040/55474061-2b700700-5608-11e9-9b0f-9d37984d5541.jpg)

OK, so I've updated my create test user/agent app with an attempt to link the test user with a test agent using the information here: https://github.com/hmrc/agent-authorisation-api

I click create user OK, create agent OK.  This populates the centre section with the required details.  I set up the POST and all I ever get is 401 Unauthorised.

Full log text at bottom.

But why?  As far as I can see, I'm doing everything correctly and expected to get a link to follow and log in with the test user credentials to authorise the link and then I was going to submit some VAT figures as the agent.

Any ideas?

Peter

--------------------------------
User ID: 916251081543
Password: b8ft0boluyNp
VRN: 323366865
--------------------------------
User ID: 347112399444
Password: cdrfb9nttvel
User Full Name: Adrian Felix
Email Address: adrian.felix@example.com
Agent Services Account Number: CARN0609726
--------------------------------
sRequestBody: {   "service": ["MTD-VAT"],  "clientType": "business",  "clientIdType": "vrn",  "clientId": "323366865",  "knownFact": "TS18 1PA" }
--------------------------------
sURL: https://test-api.service.hmrc.gov.uk/agents/CARN0609726/invitations
--------------------------------
System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.GetResponse()
   at MTDCreateTestUser.MTDCreateTestUser1.CMD_CreateAgentAuthorisation_Click(Object sender, EventArgs e) in M:\708_Src\VB.Net\WinUtil\MTDCreateTestUser\MTDCreateTestUser1.vb:line 333

**Comment by jeremystone** [comment]
For authorisation issues you should contact SDSTeam@hmrc.gsi.gov.uk who should be able to help you.

**Comment by SDST-HMRC** [comment]
SDST email address is now sdsteam@hmrc.gov.uk 

We've removed the 'gsi'

**Comment by Yottskry** [comment]
Are you sending the Authorization header?

Authorization: Bearer <token>

Where <token> is your application's server token.

**Comment by PeterGGreen** [comment]
@Yottskry Yes the server token is included (obviously not including this sensitive information in this post).  But it's definitely added when I construct the POST request.

**Comment by Yottskry** [comment]
@PeterGGreen What's the body of the error response? You should get an actual description back as well as the code. I don't know how it works in the language you're using, but in Delphi the actual error description is in the Message property of the Exception object.

**Comment by PeterGGreen** [comment]
This is the actual error.
![image](https://user-images.githubusercontent.com/43069040/55551563-072d2c80-56d3-11e9-83bc-c33c5d95d719.png)

**Comment by PeterGGreen** [comment]
Actually, server token is not required, so removed that and now getting:
![image](https://user-images.githubusercontent.com/43069040/55551676-4b203180-56d3-11e9-9c53-2507b57f81ad.png)

**Comment by PeterGGreen** [comment]
Well, I'm obviously missing something as the HMRC page I listed above doesn't contain any information about adding authentication information...  Check the README.md.

**Comment by Yottskry** [comment]
Sounds to me like you're using the server token when perhaps it should be a proper access token, i.e. you need to do the whole authentication route as you would for MTD.

**Comment by PeterGGreen** [comment]
So when getting an OAUTH token for MTDVAT, these are the scopes I'm using:

scope=read:vat+write:vat

But these aren't relevant to logging in as an agent and setting up a new relationship.  There is no information about the scope on the original page.  I give up !!!  AWFUL documentation.

**Comment by si458** [comment]
make sure you have permission in your sandbox app to use the new agent autherisation api
https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/agent-authorisation-api/1.0

also i think you have to create users using this url for agents
https://test-www.tax.service.gov.uk/agents-external-stubs/help/agent-authorisation-api

BUT ive yet to get it working! ive been bashing my head against the wall for weeks now...

**Comment by mtd-api-team** [comment]
We've recently published the following Wiki page to try and help clear up how to create Test Agents in the Sandbox: https://github.com/hmrc/vat-api/wiki/Creating-Test-Agents-in-the-Sandbox

**Comment by si458** [comment]
@mtd-api-team this DOESNT WORK!!!
every time i try logging in i keep getting

'You cannot access client data at the moment
Agents are currently not able to authorise software applications to act on their client's behalf.
This will become available at a later date.'

**Comment by si458** [comment]
@mtd-api-team  you are taking the micky! if you add the scope ``hello`` into it you get this error but if you remove it it works! how stupid!

**Comment by mtd-api-team** [comment]
Adding an additional scope should not impact the request. This would imply that either the scope string you are sending is likely not encoded properly.

Please see the following guidance around auth/scopes and how to use them:
https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints
https://developer.service.hmrc.gov.uk/api-documentation/docs/reference-guide#scopes

Although unlikely, if there is still an issue, please raise it with SDSTeam@hmrc.gov.uk and they will be able to liaise with the relevant parties to assist with your scopes.

**Comment by ricnic** [comment]
@mtd-api-team we ran into the same issue as @si458 when moving from sandbox to production.

The two scopes we were using were `read:vat` and `hello`. This configuration was encoded correctly and tested successfully in the sandbox. But when moving to production, after trying to authorise our application using an Agent login we were faced with a page showing:

> You cannot access client data at the moment. Agents are currently not able to authorise software applications to act on their client's behalf. This will become available at a later date.

This was resolved for us by removing the `hello` scope. Which was, for us, a succinct way of verifying in a general sense that the agent credentials we currently hold are valid.

Thanks

**Comment by theshillito** [comment]
I've ran into the same issue and removing the `hello` scope fixed things. We have `&scope=hello+read:vat+write:vat` and all three are correctly detected on the authorisation screen. Sadly, I'm going to have to figure out a different way of checking if a user's `access_token` needs refreshing (for agent users, I was hoping to have a VRN-independent method for checking this).

**Comment by KenRandall** [comment]
I am having the same problem with agents. Does removing the hello scope have any problems with non-agents?

**Comment by theshillito** [comment]
I don't think so. It just means you have to find an alternative scope to do whatever the hello scope was doing for you. In my case I'm having to change when calls to the VAT API are made so I can refresh the tokens rather than rely on the hello user API to check if it needs refreshing.

**Comment by KenRandall** [comment]
Thanks Peter. I'll try that.
