### ISSUE TITLE
Fraud Prevention Headers

### ISSUE THREAD

**Issue by SheepShearer** [hmrc/vat-api#554]
Just when I thought I'd got everything working I read the fraud prevention info. There seems to be more work in data mining this info for HMRC than submitting a few numbers for a VAT return. There's some quite incredibly obtuse personal & PC info requests, but I guess HMRC know what they are doing......

The docs at https://developer.service.hmrc.gov.uk/api-documentation/docs/fraud-prevention are  pretty sparse so specifically to get going I'm trying to discover:

1) Which API endpoints do we have to submit which headers with? All of them for all the Endpoints? As far as I can see the link on API Endpoint info page just sends you to the Fraud prevention page without any info about which headers to send to which endpoints. Can we chuck everything at all endpoints or will this get bounced?

2) How and when do we test these? Reading the posts thus far, the Sandbox doesn't check these and sending by email doesn't seem particularly effective. 

My boss is hopping mad at the cost of all this MTD.......... and I've just had break the bad news to her that its not finished yet after all.

**Comment by GrahamHDawson** [comment]
You send the anti-fraud headers to all endpoints.

First step is to determine what type of application yours is
ie the value of Gov-Client-Connection-Method

Then each of the other headers has a section in the documentation called
'Required for connection methods'
with a list of connection methods for which **that** particular header must be provided.

As for testing as you say the Sandbox doesn't currently check the headers.
The other options are to capture a sample set of headers and hope that you'll get a reply from the SDST, or to ask for a test session with them.

**Comment by SheepShearer** [comment]
> You send the anti-fraud headers to all endpoints.
.....
> The other options are to capture a sample set of headers and hope that you'll get a reply from the SDST, or to ask for a test session with them.

Thanks Graham, all endpoints it is then. Mine is just a desktop app and I'm wrestling with things like mining out MAC, IP addresses, screen details, PC/OS info logons etc. etc. which is much more time consuming than just posting VAT Boxes 1-9.  HMRCs instructions seem a bit vague with all the 'just leave it blank' if you cant find it option. 
Its feels like I'm climbing another false summit  :(

**Comment by GrahamHDawson** [comment]
Desktop app here too.

For MAC and IP addresses I'm using the Windows API - GetAdaptersInfo

For PC details I'm using 2 calls of WMIC and capturing the output (Standard Output in my case - but you could output to a file if that's easier for you)
wmic /output:stdout computersystem get manufacturer
wmic /output:stdout computersystem get model

For OS another call of WMIC
wmic /output:stdout os get Caption

Screen details come from 3 Windows APIs GetSystemMetrics for screen resolution, width and height,
GetDC to get the desktop device context and then GetDeviceCaps to get the colour depth info.

Time Zone info comes from the GetTimeZoneInformation API call

**Comment by SheepShearer** [comment]
> Desktop app here too.
> 
> For MAC and IP addresses I'm using the Windows API - GetAdaptersInfo
> 
> For PC details I'm using 2 calls of WMIC and capturing the output (Standard Output in my case - but you could output to a file if that's easier for you)
> wmic /output:stdout computersystem get manufacturer
> wmic /output:stdout computersystem get model
> 
> For OS another call of WMIC
> wmic /output:stdout os get Caption
> 
> Screen details come from 3 Windows APIs GetSystemMetrics for screen resolution, width and height,
> GetDC to get the desktop device context and then GetDeviceCaps to get the colour depth info.
> 
> Time Zone info comes from the GetTimeZoneInformation API call

Hey thanks Graham, that's really helpful, particularly the GetSystemMetrics tip as I was struggling with that tonight.

much obliged

**Comment by Yottskry** [comment]
> 
> 
> Desktop app here too.
> 
> For MAC and IP addresses I'm using the Windows API - GetAdaptersInfo
> 
> For PC details I'm using 2 calls of WMIC and capturing the output (Standard Output in my case - but you could output to a file if that's easier for you)
> wmic /output:stdout computersystem get manufacturer
> wmic /output:stdout computersystem get model
> 
> For OS another call of WMIC
> wmic /output:stdout os get Caption
> 
> Screen details come from 3 Windows APIs GetSystemMetrics for screen resolution, width and height,
> GetDC to get the desktop device context and then GetDeviceCaps to get the colour depth info.
> 
> Time Zone info comes from the GetTimeZoneInformation API call

Reassuringly, you're doing almost the same thing I am, although I'm accessing WMI via COM:

```
FSWbemLocator := CreateOleObject('WbemScripting.SWbemLocator');
FWMIService := FSWbemLocator.ConnectServer('localhost', 'root\CIMV2', '', '');
WBemObjectSet := FWMIService.ExecQuery('SELECT * FROM Win32_ComputerSystem', 'WQL', $20);
```
And then iterating through the results.

**Comment by GrahamHDawson** [comment]
@Yottskry Thanks for the WMI COM tip. I wasn't aware of that route.

**Comment by adamdavi3s** [comment]
If anyone is using C# I ended up using the system.management reference and something like this

ManagementClass man = new ManagementClass("Win32_ComputerSystem");
				ManagementObjectCollection moc = man.GetInstances();
				if (moc.Count != 0)
				{
					foreach (ManagementObject mo in man.GetInstances())
					{
						 make = mo["Manufacturer"].ToString();
					}
				}


				ManagementClass mod = new ManagementClass("Win32_ComputerSystemProduct");
				ManagementObjectCollection modmoc = mod.GetInstances();
				if (modmoc.Count != 0)
				{
					foreach (ManagementObject model in mod.GetInstances())
					{
						 modelno = model["Name"].ToString();
						
					}
				}

**Comment by ramanbatra152** [comment]
As we cannot test these headers on the Sandbox, whats the way to test these headers?

**Comment by Yottskry** [comment]
> 
> 
> As we cannot test these headers on the Sandbox, whats the way to test these headers?

HMRC have an email address you can send the headers to and get feedback. Send an example of your raw headers as a txt file to SDSTeam@hmrc.gov.uk with a subject of "Example Header Check Request" and they'll eventually get back to you.

**Comment by ramanbatra152** [comment]
What all headers are mandatory for a web application?

**Comment by Yottskry** [comment]
> 
> 
> What all headers are mandatory for a web application?

As stated several times here and in the documentation, **if you cannot provide a header because you are unable to retrieve a value for it, you should leave the header empty or omit it entirely.**

**Comment by mtd-api-team** [comment]
Hi all, if you have any Fraud Prevention questions that require HMRC support, please email SDSTeam@hmrc.gov.uk directly and they will be able deal with your queries. Otherwise, please refer to https://github.com/hmrc/vat-api/issues/565.
