### ISSUE TITLE
Fraud Prevention Headers

### ISSUE THREAD

**Issue by ramanbatra152** [hmrc/vat-api#555]
We are developing a Web Application for the MTD VAT software. As it is mandated to implement the Fraud Prevention for the MTD VAT submissions but you didn't gave any clear information regarding this. I need to get some information regarding the headers :

Is it mandatory to pass all the headers? If not , please give give us list of all mandatory headers.
As of now , i tried testing in sandbox urls, when I am passing some of the these random headers with some random values, still sandbox is accepting all my requests and i am getting desired results. So, i am able to identify the difference of passing headers or not passing headers in Sandbox.

If anyone can give some relevant information, it will be useful.

Thanks in advance.

**Comment by cb-rfk** [comment]
Hi @ramanbatra152 

Take a look through the current set of open issues - there are half a dozen posts asking the same thing that you are with plenty of discussion about what's available and what isn't.

You won't get a direct response from HMRC here.

Hope this helps.

Richard

**Comment by GrahamHDawson** [comment]
Hi @ramanbatra152 
See issue 554 for details of how you identify the anti-fraud headers that are mandatory for you particular application type.

**Comment by ramanbatra152** [comment]
@GrahamHDawson  : I have gone through issue 554 , still I haven't got my answers.

1. What all headers are mandatory?
2. How to test them? as sandbox is not supporting these headers as of now.

**Comment by slczyk** [comment]
My understanding is as follows:

1. Mandatory headers:
- Gov-Client-Connection-Method
- Any other headers that are required for the connection method
- If you cannot provide a header leave the value blank or not supply it
see https://developer.service.hmrc.gov.uk/api-documentation/docs/fraud-prevention

1. I'm afraid you can't test them by yourself. The only thing you can do is email SDSTeam@hmrc.gov.uk to review the headers you are sending.

**Comment by ramanbatra152** [comment]
@cb-rfk 
For "Gov-Vendor-Forwarded" header,what we need to pass in case  we do not have any 'WAF-owned IP address'?

**Comment by mtd-api-team** [comment]
Hi all, if you have any Fraud Prevention questions that require HMRC support, please email SDSTeam@hmrc.gov.uk directly and they will be able deal with your queries. Otherwise, please refer to https://github.com/hmrc/vat-api/issues/565.
