### ISSUE TITLE
INVALID_DATE_RANGE When retrieving VAT Obligations

### ISSUE THREAD

**Issue by LukeHirst** [hmrc/vat-api#556]
I currently have an issue with the Sandbox where retrieving VAT obligations using the following request: 

https://test-api.service.hmrc.gov.uk/organisations/vat/#########/obligations?from=2016-12-31&to=2017-12-31

(I have intentionally blanked out the VRN)

Returns the following error:

{
"statusCode":400,
"message":"INVALID_DATE_RANGE"
}

This code has worked previously and has only started to error in the sandbox recently. Issue #217 states that this error is returned when the 'from' and 'to' range supplied is more than 366 days. 

I believe the range I have supplied is 365 days. 

Is this a known issue?

**Comment by GrahamHDawson** [comment]
@LukeHirst 

AFAIK the date range is inclusive - so 2016-12-31 to 2017-12-31 is actually 366 days
Looking at the latest code update log it appears that 366 days **is** valid when the year is a leap year - but 2017 isn't one.

**Comment by LukeHirst** [comment]
Hello @GrahamHDawson, thanks for replying. 

Just to double check do you have a git issue or any api documentation that specifically states the date range is inclusive?

Looking at the changelog it does seem to suggest that the obligations request I sent will work on a leap year but not for any other year. 

Can someone from HMRC confirm that this is correct? The changelog also states that this change is now in production, is this also true?

**Comment by GrahamHDawson** [comment]
@LukeHirst 

See the Wiki - FAQs - Obligations section...

https://github.com/hmrc/vat-api/wiki/FAQ

definately states dates are inclusive.

**Comment by GrahamHDawson** [comment]
NB I'll always play safe with the range and set it to say 364 days (rather than complicate things with checking for leap years etc etc)

**Comment by RobertMarczycki** [comment]
There are multiple issues with this code change:
- this is a breaking change introduced silently to Test environment - with no notification in advance, and with no explanation of the change; the change log note about adding _"consistency"_ does not state what the change was - and that it would break applications
- please note the validation rule is not documented in HMRC API documentation pages
- there is no way to test against Production endpoint - even if the code is not _"consistent"_ the connecting applications were deployed to production already, it's not a good practice to force changes in connecting apps
- if the change propagates to Production it may break many applications tested against the test environment - up to yesterday 366 days were working OK in this environment

I suggest you revert the change in test environment. 

Can you please block the deployment of the change to production? It will enforce all apps developed/ tested against previous version of the code to release the fix!

If you still plan to deploy the change to production can you please ensure this change is communicated in advance? When it would apply?

**Comment by LukeHirst** [comment]
@GrahamHDawson thanks for the link to the FAQ. 

IMO important information such as that should be in the api documentation rather than an FAQ.

I agree with @RobertMarczycki and suggest a revert on this change and prior warning given as this clearly affects some software vendors who have integrated to the api.

**Comment by alex1987** [comment]
@RobertMarczycki @LukeHirst It seems that they deployed the change to production, without notice, yesterday afternoon - our app had been using date ranges deemed valid by the previous version but invalid by the new one, and we were forced to release a hotfix at short notice...

**Comment by JeeBeePee** [comment]
Also had to hotfix after customer complaints. Deployment of breaking changes without notice in production is frankly unforgivable.

**Comment by LukeHirst** [comment]
Can we get a response on this by someone at HMRC on this? There is clearly a workflow issue here if we have to deploy hotfixes for changes that we are made unaware of.

**Comment by MarkAKelly** [comment]
Hi all,

Our apologies about the problems caused by this - a slight change in one of the HMRC backends around handling of leap year ranges had enforced us to make a change to the ranges allowed across our API's.

For the time being, we are going to revert the change and put in a workaround our side so that the behaviour stays the same for you.  We will negotiate a way soon about the best way to implement these date range changes - for now we will update the specs with the ranges previously allowed by the  existing code.

Regards,

Mark

**Comment by LukeHirst** [comment]
Hello @MarkAKelly, thanks for the response

Can you give us an eta on when this workaround will be done? 

Just to confirm will this workaround deployed to both the sandbox and in production?

**Comment by MarkAKelly** [comment]
@LukeHirst 

This will be deployed into both environments within the hour.

Does that work for you?

Mark

**Comment by LukeHirst** [comment]
That will work fine for me. 

I will close the ticket once I have tested the fix in the sandbox.
