### ISSUE TITLE
Fraud P Header: Gov-Client-Timezone

### ISSUE THREAD

**Issue by SheepShearer** [hmrc/vat-api#558]
For the FP Header 'Gov-Client-Timezone' do we (here in the UK) submit :

Gov-Client-Timezone: UTC+01:00   'in the summer daylight saving
and
Gov-Client-Timezone: UTC+00:00  'in the winter

or is it always just UTC+00:00?

TIA

**Comment by cb-rfk** [comment]
It's always UTC+00:00 as we do not change timezone when switching from GMT to BST...

**Comment by SheepShearer** [comment]
Thanks........
