### ISSUE TITLE
Running on localhost

### ISSUE THREAD

**Issue by jmc420** [hmrc/vat-api#563]
Please could someone document what servers and services need to be run in order to run the VAT API on a local development machine.

**Comment by cb-rfk** [comment]
Err.. not really!  The API is just a set of public URIs that you reach from whatever interface you choose to contact them from. Regardless of whether you run on your localhost or on a production system, you'll be hitting the same URI endpoints on either the test-api sandbox environment or the live environment, both hosted by HMRC.

We use a Java based solution, others are using .NET, Ruby and a whole host of higher level frameworks.

Not being rude, but have you developed against an API service before?  You might need to do some background research on that before starting with MTD.

**Comment by jmc420** [comment]
>We use a Java based solution, others are using .NET, Ruby and a whole host of higher level >frameworks.

I have been a Java developer for 20 years so know how to run JVM based software. 

>Not being rude, but have you developed against an API service before?

Yes

>You might need to do some background research on that before starting with MTD.

I have been looking at MTD and trying to get the simple NodeJS example running without success - nobody replies to issues in that github repo hence the request in this repo. The SDSTeam cannot run the example themselves.

There has been a recent commit by Darren Walker saying that "You will need to add the Redirect URI 'http://localhost:8080' to your application ('https://developer.service.hmrc.gov.uk/developer/applications/')."

https://github.com/hmrc/api-example-nodejs-client/commit/0fb8be2d63c44924c5d97608b0926e246e3503e4

The only way that the OAuth redirect url http://localhost:8080 will work is if the OAuth server is running on the same machine using the loopback adapter.

Can you set out what needs to be done to run the "Hello world" servers that interact with this NodeJS example:

https://github.com/hmrc/api-example-nodejs-client/issues/8

**Comment by cb-rfk** [comment]
Hi James,

Sorry, I've not used node.js so can't comment much on that. However I can say that we simply added our local host servlet urls to our application registration on the HMRC Developer Hub site and the OAuth redirects were fine:

![image](https://user-images.githubusercontent.com/46710197/55736646-a1ff7100-5a1b-11e9-8b4a-a202aa08bbd9.png)

We converted our local workspaces to use HTTPS but I think that's actually unnecessary to run against the sandbox apps (only need HTTPS on the live api).

**Comment by jmc420** [comment]
Ok thanks that works with both the java and nodejs clients locally.
