### ISSUE TITLE
gov-client-multifactor

### ISSUE THREAD

**Issue by JohnAherne** [hmrc/vat-api#564]
This repository's issues are reserved for **Technical** queries relating to the VAT-API Only.

If your issue falls into any of the below categories please contact the SDST at SDSTeam@hmrc.gov.uk:

- Subscribing/registering to use the API Platform, MTD enrolment / de enrolment  / registration for VAT / BETA etc
- Issues relating to OAuth2
- Issues relating to integrating with the API Platform (setting up an application/access)
- Code examples in programming language x
- Business related questions
- Scheduled maintenance days / windows
- Onboarding 
- Performance metrics
- Questions relating to the process pre MTD

Please see answers to common questions in the [VAT API Wiki](https://github.com/hmrc/vat-api/wiki/FAQ) and see if anyone has previously encountered the issue by searching [here](https://github.com/hmrc/vat-api/issues?utf8=%E2%9C%93&q=).

**Comment by Roger1952** [comment]
The above list of "not supported here" subjects does not seem to include Fraud Prevention Headers. This then seems to have been immediately contradicted by the following post (565) saying don't ask about FPH as they will be ignored.

**Comment by mtd-api-team** [comment]
Hi @Roger1952 

Thanks for catching that. We've updated the support ticket template 👍
