### ISSUE TITLE
Fraud Prevention Headers - Support

### ISSUE THREAD

**Issue by Yottskry** [hmrc/vat-api#566]
Some bright spark has seen fit to close the thread I started asking about the uniqueness and permenance of the client ID on the basis that I should email the SDS team directly to receive support for fraud prevention headers.

Well silly me. If only I'd thought of that!

I emailed with the same question I posted in the, now closed, thread on March 28th and AGAIN on March 29th. I have had no response.

HMRC, if your idea of dealing with support questions is to close threads and ignore emails, you're doing a bang up job. I am seriously pissed off at the moment. Your support and developer engagement are pathetic. You clearly are not taking the issues thrown up by your ill-conceived FP headers seriously, and you treat those of us asking questions in order to be compliant with outright contempt.

**Comment by GrahamHDawson** [comment]
The SDS Team seem seriously understaffed or overworked (probably both)

I appreciate that this repository is for MTD VAT API issues only - but surely the **implementation** of the Anti-Fraud headers **is** specific to MTD VAT and fast track support is badly needed.

**Comment by GrahamHDawson** [comment]
It's also worth adding that the SDSTeam (AFAIK) have no GitHub repository of their own.
So what that means is  that Anti-Fraud header queries will be endlessly repeated, with new developers asking over and over the same questions adding even more work.

**Please** if this **is** to be effective create some sort of Anti-Fraud Headers repository that people can use to communicate to the SDSTeam direct.

**Comment by Roger1952** [comment]
They are probably short staffed because of IR35.

Why they can't set up one stop shopping for support I don't understand. Everbody passing responsibly to everybody else may be simple for HMRC but it doesn't work ever so well for the poor suckers trying to write software communicate to an API that is ambiguously specified.

**Comment by mtd-api-team** [comment]
Closing this issue to consolidate all fraud prevention headers discussions to be in #565
