### ISSUE TITLE
500 internal error on production when submitting a return.

### ISSUE THREAD

**Issue by markogrady** [hmrc/vat-api#569]
I have sent a mail to SDSteam but I find here much more proactive. Is anyone else on here getting a 500 internal error when submitting through production. I have sent loads of returns that were fine although today there seems to be issues.

On a side note is there any service status pages, I know there was talk of them but I haven't seen anything more about them

**Comment by GrahamHDawson** [comment]
Service status page is
https://www.gov.uk/government/publications/making-tax-digital-for-vat-service-availability-and-issues

(you should be getting emails from SDSTeam about downtime - latest one was only yesterday)

> Due to essential upgrade taking place tonight the VAT Making Tax Digital service will be temporarily unavailable on 10th April at 22.00 to 23.00.

**Comment by KenRandall** [comment]
This was also happening throughout the day on the 10th.

**Comment by markogrady** [comment]
Yes I had one on the tenth fail then go through. Now I have 5 that are
failing.

**Comment by KenRandall** [comment]
Unfortunately there is no way of testing this in production unless one of your own companies is due a return. Only the government would have a sandbox that is totally different to production!

**Comment by pwatts001** [comment]
We've had 5 failed returns since yesterday.

**Comment by markogrady** [comment]
I have tried submitting them again at different times and they do seem to be eventually going through but there doesn't seem to be a consistent reason why.

**Comment by KenRandall** [comment]
Strangely getting the access code always seems to work but any other call is intermittently failing. I have had to change the application with error messages saying this, but have already lost a couple of clients!

**Comment by markogrady** [comment]
I have changed the error message and contacted all the clients personally.

**Comment by JeeBeePee** [comment]
Also seeing intermittent HTTP 500 in production, for all endpoints, so it's not just you.

**Comment by markogrady** [comment]
Also it only seems to be the Submission API not the GET obligations or the Auth APIs

**Comment by KenRandall** [comment]
I've had problems with obligations today

**Comment by KenRandall** [comment]
Just got a message I've never seen before when requesting obligations This came up after a long delay:

"The request for the API is throttled as you have exceeded your quota."

**Comment by markogrady** [comment]
Yes that has been there for a while, you can make a 150 requests per minute.

There are a number of ways of dealing with throttles, 

Some people just keep hitting and re queuing it so it carry's on hitting it through out the throttle period. I feel it defeats the point although it is taking the burden off API getting the data.

Some people always put a delay in to all requests which means all requests take longer.

When I hit the throttle count,  I just add the job back on the queue with a delay and only process a certain amount of queued jobs at a time, this way you can throttle all API requests over multiple services/nodes. Which also means normally when it is not sending lots of requests, it is still fast

**Comment by KenRandall** [comment]
There is no way that count was exceeded as this is a desktop application unless the throttling is applied to the developer thather than the submitter!

**Comment by markogrady** [comment]
It is applied to your client application in your developer hub. So if all your desktop apps use the same client id then it will count all the desktop app use. I prefer Xero and Quickbooks' API which throttle per organisation per application. It still stops someone constantly hitting their system pointlessly but if you have lot of users it doesn't degrade everyones experience.

**Comment by markogrady** [comment]
Back to the topic of the 500 issue, I have had confirmation that there is an issue and they are working on it.

**Comment by KenRandall** [comment]
Crazy. 150 requests per minute is far too low for a desktop application with potentially thousands of users. I don't think it is possible to use different client ID's.

**Comment by JeeBeePee** [comment]
I think everyone has been incredibly kind and patient with HMRC, however my patience has run out. The implementation is shoddy and the support response is slower than an asthmatic ant with some heavy shopping. If only we could change providers...

**Comment by JeeBeePee** [comment]
@markogrady Would you mind posting SDS team's response here please?

**Comment by JeeBeePee** [comment]
SDS Team, for the love of God please update your service status page https://www.gov.uk/government/publications/making-tax-digital-for-vat-service-availability-and-issues/making-tax-digital-for-vat-service-availability-and-issues

**Comment by markogrady** [comment]
I just got this response from my developer relations person.

"yes there is an issue that’s just been flagged and its being worked on."

Like with any massive project/organisation we will receive these issues, and to be honest it is always to be expected.  I think they are under a lot of pressure with Brexit looming which may have a big effect, I know resource has been moved on to it. Personally I think the developer support needs a lot more resource and tools to help us. They need to add some more devops so when they receive multiple 500 errors in their logs it will flag something up on the developer service availability site straight away. There also just needs to be communication even to set expectations. All that said I think we need to support the project as much as possible because effectively it supports our tax system.

**Comment by JeeBeePee** [comment]
They don't help themselves though. They could cut the traffic on here, reduce the number of emails the SDS team have to answer and give us lot an easier time explaining the numerous issues to our customers, simply by adding "an issue has been flagged and it's being worked on" to the service status page. But for some reason, it remains blank and we instead get an email about TLS version changes in October.

It's that refusal to do the obvious thing that riles people.

**Comment by JeeBeePee** [comment]
Service seems to be OK now - several returns submitted without issue - do other vendors concur or have we just been lucky this morning?

**Comment by markogrady** [comment]
Yes, I will close the case I saw a commit that was reversed which I think was the culprit.

**Comment by JeeBeePee** [comment]
@markogrady Thanks for the info Mark. We lost a customer over this one. Yes, I know it's like changing energy supplier because you've had a power cut, but the lack of any update on the status page meant we were asking customers to take our word for it that the issue was on your side.

Would be nice to have a statement by HMRC to try to win them back.  Well, I say it would be nice - any other API provider and I wouldn't have to ask for it, they'd automatically release a statement after any significant issue or outage.
