### ISSUE TITLE
MISSING_CREDENTIALS when posting VAT Return

### ISSUE THREAD

**Issue by redware** [hmrc/vat-api#573]
Hi
I am trying to post a VAT return for the first time but getting MISSING_CREDENTIALS error.
I am pushing the authorisation header as for the gets which work OK.
This is the URL - {https://test-api.service.hmrc.gov.uk/organisations/vat/871162726/returns}
Note that on the documentation you are also passing the periodKey in the URL but that not working.
Elsewhere I have seen that some values are integers but I have them as decimals.
I understand that we are supposed to get the period key somehow from obligations but cannot quite work that out so the periodkey is random.
I have the following headers including the accept, content type and authorisation.

Accept: application/vnd.hmrc.1.0+json
Content-Type: application/json
Host: test-api.service.hmrc.gov.uk
Content-Length: 339
Expect: 100-continue
Authorization: Bearer 515f559c11fa8e6656c7a76c9024ccf
Gov-Test-Scenario: VRN_INVALID
Gov-Client-Connection-Method: WEB_APP_VIA_SERVER
Gov-Vendor-Version: DIYACCOUNTS%26V0.1

But I am getting this error message - MISSING_CREDENTIALS Authentication information is not provided. My GETS are working with the same headers.

Please point me in the right direction or let me know if further information required and thank you.

This is the JSON payload.
[
  "periodKey",
  "17A3",
  "vatDueSales",
  0.00,
  "vatDueAcquisitions",
  0.00,
  "totalVatDue",
  0.00,
  "vatReclaimedCurrPeriod",
  0.00,
  "netVatDue",
  0.00,
  "totalValueSalesExVAT",
  0.00,
  "totalValuePurchasesExVAT",
  0.00,
  "totalValueGoodsSuppliedExVAT",
  0.00,
  "totalAcquisitionsExVAT",
  0.00
]

**Comment by mtd-api-team** [comment]
Hi @redware

The required headers for the `POST /organisations/vat/{vrn}/returns` endpoint are:

- Accept: `application/vnd.hmrc.1.0+json`
- Content-Type: `application/json`
- Authorization: {your access token}

The Gov-Test-Scenario headers are all listed under **Test data**, towards the bottom of each endpoint's section of the documentation. To simulate the VRN_INVALID scenario for this particular endpoint, you need the Gov-Test-Scenario header `INVALID_VRN`.

Another issue is that the body needs to be a JSON object, not an array. An example request body is:

```
{
  "periodKey": "A001",
  "vatDueSales": 105.50,
  "vatDueAcquisitions": -100.45,
  "totalVatDue": 5.05,
  "vatReclaimedCurrPeriod": 105.15,
  "netVatDue": 100.10,
  "totalValueSalesExVAT": 300,
  "totalValuePurchasesExVAT": 300,
  "totalValueGoodsSuppliedExVAT": 3000,
  "totalAcquisitionsExVAT": 3000,
  "finalised": true
}
```

I hope this clears things up for you. If you have any further questions, please first read the documentation for this endpoint at https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0#_submit-vat-return-for-period_post_accordion and if you need any further assistance please respond to this thread.

Many thanks
