### ISSUE TITLE
Can we retrieve VRN or does user have to enter it ?

### ISSUE THREAD

**Issue by redware** [hmrc/vat-api#574]
Sorry if this is a silly questions.
In production use the user will authorise the application but I do not see anywhere that returns the VAT Number (VRN) for a user.
Presumably then we need to prompt the user for a VRN and store permanently alongside the access codes. That would then be good for 18 months until the token expires.
Then we display obligations to find periodKey and submit VAT return.

Sorry if this is obvious - I am near the end of development but only just worked this out - is it correct or can we retrieve the VRN for a user we have not created ourselves ?

Thank you.

**Comment by AndyYouens** [comment]
Our clients VAT number is stored in their configuration file.

**Comment by mtd-api-team** [comment]
@redware there is currently no endpoint across MTD available that allows you to retrieve a users VRN, although this may be available in the future.  Current process dictates that you must have access to and provide the VRN.
