### ISSUE TITLE
Improve the README

### ISSUE THREAD

**Issue by lukepuplett** [hmrc/vat-api#575]
Hello, I think the README is lacking basic information and hand-holding.

- Am I even at the right place? Is this the source code for the API at the receiving end of the MTD system?

- Is it a hypertext API, driven by contextual links and forms?

- If so, add a link to the media-type spec.

- If not, add a link to the Swagger/OpenAPI or API Blueprint doc.

- If neither, perhaps a Postman collection that exercises some common user journeys?

- What's the URL of the production API root?

- And the sandbox I see people mentioning?

- How can we clear out our sandbox?

- What sort of contributions are you looking for, issues, fixes, design and API UX improvements?

Thanks!

**Comment by GrahamHDawson** [comment]
You're not really at the right place, or at least here is not the right place to start your MTD API journey.
The HMRC website is the place to begin, not here, this is for issues specifically with the API. 

https://developer.service.hmrc.gov.uk/api-documentation/docs/reference-guide
gives you the basic information about the oAuth process etc - and on the left-hand side you'll see links to Using the Developer Hub, Anti-Fraud Headers etc etc

The API is documented here...
https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0

**Comment by lukepuplett** [comment]
Thanks for the prompt response, Graham. Good info, but I guess that's my point. The README doesn't allow me to work this out for myself. So I've interrupted your Sunday afternoon :)

**Comment by GrahamHDawson** [comment]
Hi Luke,

Well that's what I meant about you not starting at the right place.
Most developers get into this via the HMRC website **first** and only later discover the GitHub page.
This site assumes you already know about the API from the documentation - that's why there's limited info in the readme.

No worries though, I got to watch Tiger win that's the important bit :-)

**Comment by lukepuplett** [comment]
Thought I'd leave you to the golf. So I guess what I'm saying is that your reply here.

https://github.com/hmrc/vat-api/issues/575#issuecomment-482988797

...should be reworded a little and added to the readme to save people the confusion and interruptions on a Sunday.

I landed here from Google, perhaps Google bumps up GitHub results higher than the hmrc.gov.uk site results for devs like me.

**Comment by mtd-api-team** [comment]
@lukepuplett please refer to the appropriate API documentation found [here](https://developer.service.hmrc.gov.uk/api-documentation/docs/api).  This is currently a public repository, so searching the internet will likely stumble across this when really you need the defined docs.

Hope this helps.
