### ISSUE TITLE
Gov-Vendor-Forwarded value : In case of multiples IPs

### ISSUE THREAD

**Issue by ramanbatra152** [hmrc/vat-api#577]
HI Team, we are about to send an email to SDSTeam@hmrc.gov.uk for verification of fraud prevention headers, but we got stuck in one of the header which is "**Gov-Vendor-Forwarded**" header,  the issue is : through our system request to HMRC will not be coming from a static IP, in fact it will be a  range of IP addresses. In the above the scenario  what values we need to provide 'for' and 'by' pair. Can we pass multiple IP values?

**Comment by mtd-api-team** [comment]
As the fraud prevention headers are managed by the platform team and not the MTD-API we can only provide the information that we have from: https://developer.service.hmrc.gov.uk/api-documentation/docs/fraud-prevention. 

Our assumption as the MTD API Team would be that this header would be populated dynamically depending on the server it is coming from. The final decision would be the one provided by SDST. We hope they respond to your query and provide the necessary information. 

<img width="744" alt="Screenshot 2019-04-24 at 12 23 11" src="https://user-images.githubusercontent.com/49438676/56655815-c1d59c80-668b-11e9-9e0c-bf643587469e.png">
