### ISSUE TITLE
No receipt id header

### ISSUE THREAD

**Issue by seurrep** [hmrc/vat-api#579]
Previously the receipt-id was being returned as one of the headers when submitting a return. This currently does not seem to be the case. Is this being done intentionally?

**Comment by Senthil-9111** [comment]
I am receiving similar message in the sandbox test environment as well. any one else facing this?? is this happening in the live setup as well?

**Comment by tim-jackson** [comment]
Yes, we had confirmation in a reply from HMRC yesterday that they accept there is an issue, which has been escalated internally.
I'm no Scala expert, but this commit looks suspiciously like it could be the culprit: https://github.com/hmrc/vat-api/commit/90d3ce57978af198371deac99ff4f13d85129a87

**Comment by nickcable** [comment]
@HMRC- any idea when this will be fixed please ? I am doing a webinar to some customers tomorrow and this is one thing they will definitely want to see ! Thanks

**Comment by nickcable** [comment]
It seems to be working again now ! Thanks

**Comment by mtd-api-team** [comment]
HMRC have accepted that there was an issue with a dependent service that returns the Receipt ID to the API.  

For further live support we suggest that for the time being you contact SDST at SDSTeam@hmrc.gov.uk.
