### ISSUE TITLE
Error where MTD user attempts to submit via gateway

### ISSUE THREAD

**Issue by PaulTaylorSage** [hmrc/vat-api#58]
I am creating user stories covering users who are taking part in the MTD for VAT beta and have a couple of scenarios where I need to know the errors that will be returned from HMRC.

1 - User of accounting software has been accepted onto the beta
2 - The user submits a VAT return via the new API and is accepted by HMRC 
3 – User remains on the BETA but attempts to submit the next VAT return via the previous system (Government Gateway)
4 – What error will be returned by the government gateway ?

**Comment by scottylace** [comment]
Thank you for your question, unfortunately we cannot answer this question as it relates to the wider programme. This channel is only of specific questions relating to the MTD VAT APIs.

Could you please send your question to this email address SDSTeam@hmrc.gsi.gov.uk and your question will be dealt with.

Thanks and sorry for the inconvenience
