### ISSUE TITLE
Filing vat MTD Blank Receipt-ID

### ISSUE THREAD

**Issue by starappsolutions** [hmrc/vat-api#584]
**This bug is related to the**
- [ ] API 

**Describe the bug**
In the Vat submission API in the Sandbox environment, I am receiving blank Receipt-ID.
earlier I was able to receive Receipt-ID and I was saving that for further reference or Need.
Can anyone tell me what the issue or do we need to save Receipt Id or not?

**To Reproduce**
Create Test User
File Vat for the same and check Response Headers Received.

**Expected behavior**
I am expecting value in Receipt-Id header as I was receiving earlier.

**Comment by nickcable** [comment]
Hi, I believe this was fixed in a previous call #579. I had this issue too but it was fixed and working on 17th April. Not sure why nobody has replied :-) Unless it the bug has come back again...
