### ISSUE TITLE
Production 403: CLIENT_OR_AGENT_NOT_AUTHORISED error retrieving obligations

### ISSUE THREAD

**Issue by Chris-Goddard** [hmrc/vat-api#588]
We are having multiple customers reporting 403 errors when trying to Retrieve Obligations.  At this point they have already been through the process of authorising our software.

I have been advising customers on the following timeline:
1. They sign up to Making Tax Digital on the HMRC website.
2. When they receive an email confirmation from HMRC that they are signed up, they can then authorise our software.
3. At that point they should be able to retrieve obligations.

Is there any way in which this timeline can get mixed up?  For example, can a customer authorise software for MTD before actually signing up?

Comments appreciated.

**Comment by LukeHirst** [comment]
Just to double check has the application asked for and retrieved a refresh token as part of the oAuth process? 

each access token comes with a refresh token which needs to be used after 4 hours to get a new access token.

**Comment by Chris-Goddard** [comment]
Yes, a refresh token has been retrieved,

**Comment by dbaq** [comment]
We are facing the same issue. It is not a token issue, it is a user role issue. What's the best way to approach that?

**Comment by timcrampton** [comment]
We have the same issue in production. Customer has successfully authenticated and received an access token and refresh token but get CLIENT_OR_AGENT_NOT_AUTHORISED when making a request. Works ok in the sandbox system.

**Comment by Chris-Goddard** [comment]
@timcrampton - had a message directly from you that you are experiencing the same problem - can you please post a comment against this issue so HMRC can see others are having the problem.

Thanks

Chris

**Comment by JJPreston** [comment]
We are also experiencing the same issue.

CLIENT_OR_AGENT_NOT_AUTHORISED error code response from Retrieve VAT obligation, after already authorising. Strange that the client is successfully allowed to authorise through the HMRC, just the obligation endpoint where the issue arrives.

**Comment by LukeHirst** [comment]
I can confirm that we are also experiencing this issue in production. 

Has there been a response to this?

**Comment by mtd-api-team** [comment]
Apologies but we can't deal with live issues, as much as we would like to be of more help, we do not have access to the information in order to diagnose this. Queries of this nature should directed to the SDS team SDSTeam@hmrc.gov.uk.

**Comment by Chris-Goddard** [comment]
@mtd-api-team - can you please comment on the timeline in the original question,

Thanks

Chris

**Comment by Chris-Goddard** [comment]
We seem to have got to the bottom of this.  We have had two reasons for this problem:
1. Customer had incorrect VRN on our system, corrected this and it was all OK.
2. Customer had not actually signed up for MTD (we had them check through their account pages on HMRC website).  

The second one is more interesting.  The customer had been able to authorise the software before signing up to Making Tax Digital.  The key point here is the HMRC systems do allow them to do this.

We have been using the sandbox for testing and used generated test users.  When you create a test user, they are already signed up for MTD, so there was no actual way to test the workflow of a customer authorising the software without actually being signed up to MTD for VAT.

@mtd-api-team - can you please confirm that the authorisation process is independent of actually signing up to MTD.  Or should there be a step in the authorisation process which checks the user's account, to see if they have any businesses signed up to MTD?

Thanks

Chris

**Comment by LukeHirst** [comment]
@Chris-Goddard 

I have emailed MTD about the issue wherein a user can retreive an access token without actually being subscribed and got the following response: 

Hi,

It is not possible to provide an error message stating that the user is not registered as there are various different reasons for that particular error being returned such as:

our systems don’t recognise there is an agent/client authorised relationship in place
the user is not signed up for MTD
the wrong user ID & Password has been used for the OAuth journey

I will pass your feedback on to our developers however.

A user will successfully be able to retrieve a token as the checks for agent/client relationship & MTD sign up etc are performed after the token has been returned.  The 403 error can only be returned once a call is actually made to the API.

Kind regards,

Tina Thompson
Software Developer Support Team
Email: sdsteam@hmrc.gov.uk

**Comment by mtd-api-team** [comment]
Hi @Chris-Goddard - we cannot comment on the authorisation process as a different team within MTD handles this. Hopefully @LukeHirst's comment answers your question. If not, please email SDST at SDSTeam@hmrc.gov.uk and they will answer any further queries you have.

**Comment by AlexJSH** [comment]
(Appreciate this thread is closed but seemed a better place than opening a new one - is it possible to reopen a closed thread?)

A number of our clients are also struggling with this error - generally it has been because the VAT Number is set wrong in our software which can easily be checked by getting them to login to the HMRC website and viewing their record. 

I note @Chris-Goddard says that it is possible to see if signed up for MTD via the HMRC website - I have tried this using our own company details but not found a positive identifier for the fact we are signed up to MTD - does anyone have any details on where to look for 'proof' that the current account is signed up - the email received from HMRC for MTD is shockingly short on detail and with the strapline "You’ve signed up to use software to submit your VAT Returns" causing great confusion - our clients were already using software to submit VAT Returns!

Thanks

Alex

**Comment by Chris-Goddard** [comment]
@AlexJSH - If the user is signed up for MTD, when they log into HMRC and go to a page entitled "Your Business Taxes", there will be a section "VAT - Making Tax Digital" which has an option to "View VAT Returns".  If they are not signed up, they instead see a section "VAT", which includes an option to "Complete VAT Return".

That's what we've found anyway, this is not something we have been advised of officially by HMRC.

Regards

Chris

**Comment by AlexJSH** [comment]
@Chris-Goddard

Thanks for the swift response - we have just proved the Client who was kicking and screaming to can us and go to another software company had actually not signed up to MTD and therefore was getting the 403 error!

Cheers

Alex
