### ISSUE TITLE
404 returned on sandbox for liabilities and payments. Obligations works fine

### ISSUE THREAD

**Issue by JohnAherne** [hmrc/vat-api#590]
Just started getting 404s for Liabilities and payments on the sandbox.

Obligations and viewing returns and sending new returns works fine.

So is there a known problem for these apis

**Comment by jacobbrownlow** [comment]
Hi John

I have just tried this in Sandbox and it's working for me. Are you using the dates specified in the Gov-Test-Scenarios?

e.g.
**SINGLE_LIABILITY** | Returns a single valid liability when used with dates from 2017-01-02 and to 2017-02-02.
**MULTIPLE_LIABILITIES** | Returns multiple valid liabilities when used with dates from 2017-04-05 and to 2017-12-21.

Regards, Jacob

**Comment by JohnAherne** [comment]
Yes. Thanks. I refactored some stuff away and forgot about the test scenario. 

Once I put that back in all works.

John
