### ISSUE TITLE
Urgent - Obligations showing status Open but have received date ?

### ISSUE THREAD

**Issue by nickcable** [hmrc/vat-api#592]
Hi 
One of our customers has just signed up to MTD and about to submit a VAT return for Mar 2019. 

I am surprised to see that they can see all the obligations for year 2018 (monthly) from 01/04/18 to 01/02/19 all showing as 'Fulfilled but with a Received date = Start date of the period, the last obligation for Mar 2019 is shown as 'Open'.

Very strange as I had understood : 

1) that Obligations before MTD would not be shown (especially before 1st April 19)
2) Why is the received date = start date of the period ?

Has anybody else seen something strange like this.

Many thanks
Nick

**Comment by nickcable** [comment]
To clarify, this is the API response received on the live system : 

200 (OK) responseBody :   {"obligations":[{"start":"2018-04-01","end":"2018-04-30","due":"2018-06-07","status":"F","periodKey":"0418","received":"2018-04-01"},

{"start":"2018-05-01","end":"2018-05-31","due":"2018-07-07","status":"F","periodKey":"0518","received":"2018-05-01"},

{"start":"2018-06-01","end":"2018-06-30","due":"2018-08-07","status":"F","periodKey":"0618","received":"2018-06-01"},

{"start":"2018-07-01","end":"2018-07-31","due":"2018-09-07","status":"F","periodKey":"0718","received":"2018-07-01"},

{"start":"2018-08-01","end":"2018-08-31","due":"2018-10-07","status":"F","periodKey":"0818","received":"2018-08-01"},

{"start":"2018-09-01","end":"2018-09-30","due":"2018-11-07","status":"F","periodKey":"0918","received":"2018-09-01"},

{"start":"2018-10-01","end":"2018-10-31","due":"2018-12-07","status":"F","periodKey":"1018","received":"2018-10-01"},

{"start":"2018-11-01","end":"2018-11-30","due":"2019-01-07","status":"F","periodKey":"1118","received":"2018-11-01"},

{"start":"2018-12-01","end":"2018-12-31","due":"2019-02-07","status":"F","periodKey":"1218","received":"2018-12-01"},

{"start":"2019-01-01","end":"2019-01-31","due":"2019-03-07","status":"F","periodKey":"0119","received":"2019-01-01"},

{"start":"2019-02-01","end":"2019-02-28","due":"2019-04-07","status":"F","periodKey":"0219","received":"2019-02-01"},



{"start":"2019-03-01","end":"2019-03-31","due":"2019-05-07","status":"O","periodKey":"0319","received":"2019-03-01"},

{"start":"2019-04-01","end":"2019-04-30","due":"2019-06-07","status":"O","periodKey":"0419","received":"2019-04-01"}]}


The last two for Mar 2019 and Apr 2019 say status = Open but Received date is filled

**Comment by mtd-api-team** [comment]
Hi @nickcable 

We are unable to assist with live service queries as we do not have access to the data in question. The channel to raise a live service support request is via the SDSTeam at SDSTeam@hmrc.gov.uk 

Please notify them that you were sent to them by the MTD API Team. Sorry we couldn't be of more help.

**Comment by nickcable** [comment]
Hello, I have already raised this with SDSTeam, Please could you leave this call open as I would like to know if anybody else (developers) have experienced the same issue. It is a question for anyone really... Thanks

**Comment by mtd-api-team** [comment]
Hi @nickcable 

We will reopen this for a short period of time. Please update the issue if you receive a reply so others can benefit 👍

**Comment by nickcable** [comment]
@mtd-api-team Thank you.

Also just to clarify that the customer has submitted a March return and received the submission ref (Receipt id) but the obligation still shows as 'Open' but has a Received date = start date of period = 01/03/19.

Has anybody seen these symptoms please ?? Thanks

**Comment by nickcable** [comment]
Update FYI, I received an email from SDSTeam last night which I presume has been sent to everyone. Looks like there is an issue.

Dear Developer, 
 
As you may already be aware, software will see different period key formats for different customers in MTD, depending on where their records are held in HMRC’s systems. The majority of customers will have alpha numeric period keys (e.g. 18A1) and will not have any open obligations for periods prior to joining MTD.  However, customers with a fully numeric period key e.g. 0419 will be able to see open obligations for periods both before they have signed up to MTD and since joining MTD. 
 
We are aware that some software products are experiencing problems where the ‘Get Obligations’ API end point is showing these numeric period keys as open, despite the VAT return having been submitted and the software having received a success message. HMRC are working to update these obligations at the earliest opportunity. Users should not attempt to make a further submission for a period already submitted, as this will not resolve the issue. We are also aware of some instances, where the obligation for a numeric period key is not viewable. We are urgently reviewing requirements and will provide you with a full response as soon as our investigation is complete. 
 
When the period key is in an alphanumeric format, which is the case for the majority of customers, you should not encounter any problems. 
 
Kind Regards

**Comment by JeeBeePee** [comment]
Also received this email. Asked SDS Team to put it somewhere public like the service status page and also if means we can now show period keys to our users (previously forbidden by the digital journey doc).

I stopped short of asking how we can test it in the sandbox

**Comment by KenRandall** [comment]
Any updates on this issue?

**Comment by mtd-api-team** [comment]
Hi @KenRandall - The SDS Team are the point of contact for this issue and will update software vendors accordingly. If you have any further questions, you should email them directly at SDSTeam@hmrc.gov.uk.

**Comment by KenRandall** [comment]
Hi **MTD API Team** Do you communicate  with the SDS Team over issues raised here? If not, why not, as none of us can get a timely response from them!

**Comment by JeeBeePee** [comment]
I can't get any contact details for SDS other than the shared mailbox which is a black hole.

They're keeping up the pretence that there's nothing wrong with the service so that us mugs will deal with the fallout for them.

**Comment by nickcable** [comment]
I chased SDS and got a response yesterday that there is no further update at present. They are still working on resolving this.

**Comment by KenRandall** [comment]
I see an email has been sent to us all saying this will be fixed mid-June!!!

**Comment by nickcable** [comment]
Yes, received the same email this morning !

**Comment by RichardTaxaddict** [comment]
Hi - we have 1 user with same problem today.

Showing 2018 obligations and successfully filed. Although filing date is wrong and is actually in the return period!

No 2019 obligations showing.

Will this be fixed in mid-June fix?

**Comment by junglistloydee** [comment]
We have seen issues where an Obligation has been returned when its status is 'O', but its not returning the obligation after it has been filed - where this was returning the obligation with the status of 'O' previously. We are getting a NOT_FOUND error. Have you prevented the endpoint returning data if its been filed and the status is set to 'O'?

**Comment by richratt** [comment]
We're getting a 500 error when Getting obligations with a status of Open for customers with fully numeric period keys (i.e. 0419). 
This is the first step in our app's VAT return submission process, so these customers with the fully numeric period keys are unable to make a submission. Their due date is in 7 days. How are we supposed to handle this situation?

**Comment by mtd-api-team** [comment]
As indicated above we are unable to directly assist in live issues as we do not have access to the data. 

You should certainly contact the SDSTeam at SDSTeam@hmrc.gov.uk who will be able to investigate the reason for failure.

However, if you already know the obligation period key, and while this is clearly less than ideal, is it possible/reasonable for you to work around this and submit the returns using it on this occasion (while any issue is investigated by the SDSTeam)?

**Comment by KenRandall** [comment]
That is not a sensible answer. It sounds like richratt does things the same way as I do. You have to get the obligations first in order to see whiat the period keys are that need submitting!

**Comment by nickcable** [comment]
Hello All, 
Is anybody still having issues with this ? We have a customer who can still see pre-MTD obligations and obligations have the wrong received date and  their April obligation which was submitted ans we received a submission ref is now not viewable.

Thanks

**Comment by hmrc-api-team** [comment]
Hello, we are closing this issue due to age. If you still have any persisting issues please feel free to open a new issue.
