### ISSUE TITLE
MTD VAT Fraud prevention

### ISSUE THREAD

**Issue by Mushtaq009** [hmrc/vat-api#594]
hy i am creating web application for MTD VAT now i am facing little problem.Can anyne tell me that when and how to pass fraud prevention headers with api call to HMRC in MTD VAT. i have read the fraud prevention documention ( https://developer.service.hmrc.gov.uk/api-documentation/docs/fraud-prevention ) but i am still not clear about it...

**Comment by GrahamHDawson** [comment]
First step is to read the 'Header Contents' section of the documentation and determine which connection method applies to your specific application.
Then work through each header identifying which apply for that connection method.

Anti-Fraud headers are mandatory from 1st April 2019 - but HMRC have stated that they won't reject submissions etc immediately. Instead they will contact the developer and advise them where they need to fix things.

If you checkout the Fraud Prevention Header pinned topic #565 you'll have access to a lot of info from previous now closed issues.

**Comment by mtd-api-team** [comment]
Hi @Mushtaq009 

As suggested by @GrahamHDawson please have a look through #565.
You can view the past issues [here](https://github.com/hmrc/vat-api/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Afraud-prevention-headers)

If this does not help, please email SDSTeam@hmrc.gov.uk and ask for their assistance as we do not manage the Fraud Prevention Headers.

Thanks
