### ISSUE TITLE
 Electronic VAT Submission Failed.  Http Status Code: BadRequest, Code: PERIOD_KEY_INVALID, Message: Invalid period key

### ISSUE THREAD

**Issue by PhilDOakley** [hmrc/vat-api#595]
All our tests against the sandbox have worked but now moving to live all the current customers are getting the same error as above. We are happy that we are using the correct period key on the submission. We have taken some client data and submitted this via the sandbox and it was accepted without a period key error. What could be wrong here?

**Comment by mtd-api-team** [comment]
Hi @PhilDOakley 

Sorry you are having trouble with this, it looks to be an error returned from a back-end service.
Please ensure that you are using a period key which has been provided from retrieving an obligation. 
If you are still having trouble with this please contact SDSTeam@hmrc.gov.uk as they will be able to help.

Thanks

**Comment by PhilDOakley** [comment]
Thanks very much for the swift reply.
We have looked at the view obligations. The period key for the next submission is showing as 19C1.  We were under the impression from the documentation we should submit a period key of 19A1 given the examples in the docs.  We did email SDSTeam@hmrc.gov.uk last week on thursday but have not recvd a reply. My feeling is that we have to retrieve obligations and present these to allow the user to select the period and then submit using the period key given to us by the retrieve obligations. This was not obvious in the docs we worked with 4 months ago and this would explain why the sandbox worked fine as the period keys in there have constantly been ending A1 etc.

**Comment by mtd-api-team** [comment]
> My feeling is that we have to retrieve obligations and present these to allow the user to select the period and then submit using the period key given to us by the retrieve obligations.

That is correct.

The period keys used in the documentation are just examples and will not necessarily be the same in live.

Please see here for more information https://developer.service.hmrc.gov.uk/guides/vat-mtd-end-to-end-service-guide/documentation/obligations.html#receive-obligations-and-submit-a-vat-return

>The period key is the ID code for the period that this obligation belongs to.

Thanks
