### ISSUE TITLE
Obligations end point mistakenly showing numeric period keys as open

### ISSUE THREAD

**Issue by mtd-api-team** [hmrc/vat-api#596]
As you may already be aware, software will see different period key formats for different customers in MTD, depending on where their records are held in HMRC’s systems. The majority of customers will have alpha numeric period keys (e.g. 18A1) and will not have any open obligations for periods prior to joining MTD.  However, customers with a fully numeric period key e.g. 0419 will be able to see open obligations for periods both before they have signed up to MTD and since joining MTD. 

 
We are aware that some software products are experiencing problems where the ‘Get Obligations’ API end point is showing these numeric period keys as open, despite the VAT return having been submitted and the software having received a success message. HMRC are working to update these obligations at the earliest opportunity. Users should not attempt to make a further submission for a period already submitted, as this will not resolve the issue. We are also aware of some instances, where the obligation for a numeric period key is not viewable. We are urgently reviewing requirements and will provide you with a full response as soon as our investigation is complete.

When the period key is in an alphanumeric format, which is the case for the majority of customers, you should not encounter any problems.

This relates to HMRC systems out of control of the API Team. This is currently being looked at, for any further questions please contact the SDS Team SDSTeam@hmrc.gov.uk.

**Comment by JeeBeePee** [comment]
Please put this info somewhere linked from the status page - you don't seem to know where it is, so I'll post the link **https://www.gov.uk/government/publications/making-tax-digital-for-vat-service-availability-and-issues/making-tax-digital-for-vat-service-availability-and-issues**

...or tell us why you're not making this info public via your status page.  Don't just ignore the request.

Thanks

**Comment by mtd-api-team** [comment]
@JeeBeePee that page is not owned by us.  I'm sure it will be updated in due course.

This message has been sent out to all developers registered to the API, and as a courtesy we have included it here as well so that anyone coming in to look at this public space is also aware.

Thanks

**Comment by JeeBeePee** [comment]
> @JeeBeePee that page is not owned by us. I'm sure it will be updated in due course.

Who is it owned by, and do you have contact details for them?

**Comment by JeeBeePee** [comment]
@mtd-api-team Should customers affected by this simply go ahead and make payment for returns that have been submitted but still show as Open?

**Comment by mtd-api-team** [comment]
@JeeBeePee The MTD-API-Team is only able to answer questions relating to the development of the APIs. The SDS Team should be contacted with any further questions SDSTeam@hmrc.gov.uk.

**Comment by KenRandall** [comment]
Any idea when this is going to be sorted!

**Comment by JeeBeePee** [comment]
I have a customer suffering this issue who called the MTD VAT online services helpdesk who said A) they had never heard of this issue and had no idea what the customer was talking about - and B) suggested they submit the return again!

Are comms within HMRC so pitiful?  Should I call the helpdesk and explain the issue to them?

**Comment by JeeBeePee** [comment]
Another customer yesterday reporting online services helpdesk having not heard of this.

How long are we supposed to wait for a status page update and a communication to the helpdesk?

**Comment by KenRandall** [comment]
We were promised feedback on this and other issues. I thought this issue was meant to be resolved last weekend?

**Comment by mtd-api-team** [comment]
Hi @KenRandall,

As we already mentioned this before, the MTD-API-Team can answerable to the questions related to the development issues. All the live issues should go through the SDS Team. 

Please contact them @ SDSTeam@hmrc.gov.uk

Thanks...
