### ISSUE TITLE
How is HMRC securing the data 'Gov-Client-Browser-JS-User-Agent' ?

### ISSUE THREAD

**Issue by WorkdayDeveloperHMRC** [hmrc/vat-api#598]
We are a Cloud ERP company and hence we are concerned about the security of the data collected by HMRC for fraud prevention purposes. Specifically, we would like HMRC to provide details on how you secure browser JS user agent data. We are aware that HMRC encrypt at the transport level using TLS but may not encrypt the received data at rest. Given that such information would have practical reconnaissance value to a potential adversary if it could be correlated to a specific user and device, We would like understand the potential risks involved in the way that HMRC processes the data.

**Comment by mantis-simon** [comment]
Just a heads-up that you'll probably get a better response by asking the SDS Team directly (see https://github.com/hmrc/vat-api/issues/565)

> Questions about Fraud Prevention Headers that require HMRC support should be referred directly to SDSTeam@hmrc.gov.uk. They will not be answered by a member of HMRC on GitHub.
> 
> As the MTD API team cannot directly answer any Fraud Prevention questions, this repository will not be monitored for issues related to Fraud Prevention, and any new Issues raised around these Headers will be directed to this Issue and closed.
> 
> Please use this Issue instead for any discussion related to Fraud Prevention that does not require immediate HMRC support.

Si

**Comment by mtd-api-team** [comment]
Hi @WorkdayDeveloperHMRC - as @mantis-simon has stated, you need to contact the Software Developer Support Team at SDSTeam@hmrc.gov.uk for support related to Fraud Prevention Headers.

**Comment by WorkdayDeveloperHMRC** [comment]
Thanks responding github team. I already contacted at SDSTeam@hmrc.gov.uk<mailto:SDSTeam@hmrc.gov.uk> and send them couple of reminders but no response from them yet.

Thanks
Shiva Palle
Tax, Product Manager.
