### ISSUE TITLE
The reason why sometimes obligation are not created in production 404

### ISSUE THREAD

**Issue by markogrady** [hmrc/vat-api#599]
Hi 

I know of a few people who have had similar issues and I found out some additional information today. 

So I've had a number of people who have received confirmation they are on MTD and when they have connected to our software to HMRC there are no obligations so I get a 404 not found, there are also no obligations in their portal.

One of my clients was told he had an inhibitor/block on his account because his new office account did not match theirs and it would take a couple of days to resolve. In his current case it won't be resolved by the time his return need submitting. So he will receive an obligation later on in the year in which he will combine this period and the new periods data (Please get your customers to check with HMRC first). He was also told that obligations are populated on the 3rd Friday of the month, which maybe worth knowing because I think it slightly contradicts the documentation.

FEATURE REQUEST

If there is an inhibitor on the account could we get a warning message?

**Comment by mtd-api-team** [comment]
Hi @markogrady,  

That's useful information so I will leave this issue open, thanks for that.

We will definitely pass this request on and look to see how we could best relay this information.

**Comment by KenRandall** [comment]
Thanks for the info Mark, very useful. Seems to be a lot wrong with obligations currently. I hope they manage to sort it out soon. I'm getting tired of explaining to users that it's not our fault!

Regards,

Ken

**Comment by RichardTaxaddict** [comment]
Hello - we are still seeing this in some cases, but not all.

The first tip is to ensure that users aren't using future dates in the obligations range they pick.
Some can use future dates successfully; but most cannot it seems in our experience.

**Comment by junglistloydee** [comment]
We have also seen this in a few cases, previously it looks like it was filing the return and returning the obligation with an 'O' status. Now its returning a 'NOT_FOUND' error. It takes some time for this to be returned.

**Comment by jordanshep** [comment]
I have a scenario where when using state as O or F for Obligations I am receiving response 404 NOT_FOUND but when using a blank state I receive 404 resource not found - is this likely to be similar to the above in that the account has a block?

**Comment by hmrc-api-team** [comment]
Hello, we are closing this issue due to age. If you still have any persisting issues please feel free to open a new issue.
