### ISSUE TITLE
User reporting their MTD registration not being accepted

### ISSUE THREAD

**Issue by RichardTaxaddict** [hmrc/vat-api#600]
We have two clients using our Excel-API tool saying they have received their MTD registration email. But when they attempt to authorise, the return message is not recognised.

They are all newly registered, so wish to confirm is any delay?

**Comment by RichardTaxaddict** [comment]
All our other clients are proceeding without problems today.

**Comment by LukeHirst** [comment]
Do you know what specific error that is returned? Is it a CLIENT_OR_AGENT_NOT_AUTHORISED when retrieving obligations or does this occur when retrieving an access token?

**Comment by RichardTaxaddict** [comment]
Yes, CLIENT_OR_AGENT_NOT_AUTHORISED

**Comment by RichardTaxaddict** [comment]
We normally tell clients to MTD register. But two today said they already had their confirmation email back. Just checking if there is a delay. Thanks

**Comment by GrahamHDawson** [comment]
Hi Richard,

> But two today said they already had their confirmation email back. 

Are you saying that two of your clients got confirmation emails **before** they actually signed up for MTD VAT?

**Comment by RichardTaxaddict** [comment]
Hi - they received their HMRC MTD email notification. But then when our tool authorised them, HMRC give a CLIENT_OR_AGENT_NOT_AUTHORISED

The good news is that one of the users just reported that they were able since to get authorisation.

So there clearly is a (small?) delay between the email going to taxpayers and it being fully processed.

**Comment by mtd-api-team** [comment]
Please report live issues via the SDS Team at SDSTeam@hmrc.gov.uk as they will be able to liaise with the relevant teams to reach a resolution as the MTD API Team do not have access to the data required to resolve this query.
