### ISSUE TITLE
Fraud Header Reviews

### ISSUE THREAD

**Issue by AndyYouens** [hmrc/vat-api#603]
How long are you all waiting for getting your fraud headers reviewed?

Been 3 weeks now, not a dicky bird from them??

**Comment by cb-rfk** [comment]
Sent ours second week of March...

**Comment by AndyYouens** [comment]
wow nothing at all from them?

**Comment by cb-rfk** [comment]
Not that I recall...

**Comment by stuy1974** [comment]
It took about 3.5 weeks to reply but the reply was helpful and succinct

**Comment by IanAppleby** [comment]
Just got this back from SDSTeam re Fraud Header ..

Regrettably, we are no longer in a position to manually review headers. This service was only ever intended as a temporary measure and we have now taken the difficult decision to move away from manual reviews and focus our efforts on more efficient methods to help. Feedback received has clearly indicated a number of ways in which we could improve and we intend to shortly conduct user research to help prioritise these. For example we have already started improving the specification for some headers.

**Comment by cb-rfk** [comment]
Well, if that means they are not going to censor us for submitting returns with incorrect headers then I guess we have to wait in the hope they are producing an automated testing service, but if we do get penalised in any way for not meeting the specs, I'll either be sharpening my pitch-fork or speaking with our friendly lawyer!

**Comment by JeeBeePee** [comment]
Yet more evidence for an unforgivable lack of preparation for MTD go live. We won't be launching any more products that connect to HMRC's APIs.

**Comment by GrahamHDawson** [comment]
They should **never** have made the headers mandatory without first providing validation in the sandbox.

I expect the user research, improved specifications, implementing of validation in the sandbox etc will take place gradually.
In contrast I expect notification of invalid headers in production will be immediate (sigh)

**Comment by adamdavi3s** [comment]
Wow.

**Comment by AndyYouens** [comment]
What a mess!

**Comment by nickcable** [comment]
Our review took about 6 weeks before we received feedback. Not surprisingly, we have to make a few changes as we were unable to test (at all) in the sandbox. Now we will have to redeploy the software again to all our customers which more time spent without any commercial gain. This could have all been prevented by careful planning.

**Comment by AndyYouens** [comment]
just had this back from HMRC

At this moment, there is no validation against the Fraud Header Prevention in any environment and no errors will be returned for invalid or erroneous headers.

**Comment by mtd-api-team** [comment]
Please use #565 for further discussion
