### ISSUE TITLE
Live -> CLIENT_OR_AGENT_NOT_AUTHORISED

### ISSUE THREAD

**Issue by COLASYSTEMS** [hmrc/vat-api#604]
is this an api issue or HMRC operations issue.  ?

Client successfully authenticates but when our system tries to getObligations get this error.  This is our first client to attempt using our system and is small business with history of previous vat submissions via the portal and has apparently registered for MTD VAT.

They said that the Govt Gateway ID has not changed i.e. a new ID was not provided when they requested MTD.  Is that correct ?

I have emailed the SDS team but based on previous questions they can take a long time to get back so I didn't want to rely on them as the only source of help.

**Comment by GrahamHDawson** [comment]
See issue #600 - it seems there's sometimes a delay between when the user gets their confirmation email and when they can successfully use the system.

**Comment by COLASYSTEMS** [comment]
Hi Graham,
Sorry I did see that issue and I should have said. ...
Well the thing about this customer is they have already submitted a previous MTD VAT return via bridging software in lieu of coming on our platform so that shouldn't be the issue.
I am assuming and that is a big one I know that you can swap providers with no issues.  
Thanks, Shaun.

**Comment by mathiasbanda** [comment]
Just to add to the confusion we've had customers who submitted April VAT returns on the new platform (MTD) only to realise they hadn't submitted March. HMRC have told them the manual submission even to March is now closed. They've got to use their MTD compliant software to submit the March return. I am sure these holes will soon be sealed but it gets really messy

**Comment by theparker** [comment]
@COLASYSTEMS is this situation still pending? If not, did you have to do anything to resolve it?
My clients are experiencing same issue, they've signed up to use MTD and registered with our software but requests to retrieve obligations consistently returns HTTP 403 CLIENT_OR_AGENT_NOT_AUTHORISED. I cannot even tell if it is a delay that is causing this.

At this stage, I don't know if making them reset their authorisation token will help plus the no response from the [SDS team email](mailto:SDSTeam@hmrc.gov.uk) is shocking. Not even an autoresponse to say the issue has been logged. @mtd-api-team is this something you can help with?

**Comment by mtd-api-team** [comment]
Hi @theparker,

Unfortunately, we can't help as it is related to the authorization issue based on the data you submitted and we don't deal with the data. So you have to go via SDS Team.

Thanks...

**Comment by theparker** [comment]
Thanks @mtd-api-team . Can I know what sort of data the SDS team would require to respond appropriately? I sent an email couple of days back and still no response.

**Comment by AlexJSH** [comment]
@theparker

Have a look at #588 also - I've just added some extra details - 2 critical things to get your client to check before you enter into talking to the live team or SDSTeam:

1) Is the VAT Number correct in your software for the Gateway ID used to "Grant Authority"
2) Is the VAT Account signed up, and accepted, for MTD reporting

Item 1 has been the issue for 95% of our clients with this error...

We don't have any Agent/Client relations at the moment so that might add another twist if your client is in that situation.

Good luck...

Alex

**Comment by COLASYSTEMS** [comment]
A day after I posted this issue the account was able to login and see live obligations.  Great. But ...
However on generating the VAT return data for the account within our software and retrying to login to HMRC in order to post it we are being redirected back to the HMRC login screen and seeing INVALID_CREDENTIALS
We have actually watched the client try to login and they are using the exact same credentials that previously worked.

**Comment by COLASYSTEMS** [comment]
UPDATE.  We found the problem.  Sorry - Bug in our system - we have a toggle in the user's profile to switch to LIVE HMRC but it didn't work so the testing we previously did against sandbox wasn't flipped back to live.  So now all working. We have finally submitted our 1st VAT return :-)

**Comment by mathiasbanda** [comment]
> 
> 
> UPDATE. We found the problem. Sorry - Bug in our system - we have a toggle in the user's profile to switch to LIVE HMRC but it didn't work so the testing we previously did against sandbox wasn't flipped back to live. So now all working. We have finally submitted our 1st VAT return :-)

Well done. Just watch out for customers signing up for MTD before they submit their last manual return. It's safer the other way round. Submit the last manual, leave it a couple of days then signup for MTD. Signing up for MTD too soon invalidates the last VAT return. It then needs resubmitting with the MTD app.

**Comment by AlexJSH** [comment]
@mathiasbanda

When you say invalidating the last VAT return can you clarify please? Are you describing the following chain:

1) Client has a return to submit but is not yet signed up for MTD
2) Client signs up for MTD on HMRC webpage
3) Client submits VAT return (either by webpage or software using the XML route) and receives confirmation that return has been submitted
4) Client receives confirmation they are now signed up for MTD and starts authorising software etc
5) Client then discovers that the previous return has been binned by HMRC (with warning to client?)

Or at step 3 is the VAT return rejected?

Thanks

Alex

**Comment by mathiasbanda** [comment]
Yes so do 3 first. Then (even after confirmation wait for) 72 hours later do 2. Otherwise you end up with 5. 
 
After 2, 4 is non-negotiable

**Comment by mathiasbanda** [comment]
> 
> 
> Yes so do 3 first. Then (even after confirmation wait for) 72 hours later do 2. Otherwise you end up with 5.
> 
> After 2, 4 is non-negotiable

No warning at all then just receive the standard letter from HMRC about not submitting VAT (when in fact they did)

**Comment by AlexJSH** [comment]
How do I do an @ Everybody???!!!
Thanks for the update @mathiasbanda 

If this is not just an unfortunate incident affecting a couple of accounts but is a hole in the system then this is quite shocking....Suggest anyone else who experiences this posts here also so everyone has 'evidence' if they need it in any discussions with HMRC - particularly if we start seeing threats of fines/interest charges to clients.

**Comment by mathiasbanda** [comment]
> 
> 
> How do I do an @ Everybody???!!!
> Thanks for the update @mathiasbanda
> 
> If this is not just an unfortunate incident affecting a couple of accounts but is a hole in the system then this is quite shocking....Suggest anyone else who experiences this posts here also so everyone has 'evidence' if they need it in any discussions with HMRC - particularly if we start seeing threats of fines/interest charges to clients.

We've had a dozen+ in april alone we had 2 or 3 per week!

**Comment by theparker** [comment]
I have been informed that this issue occurs mainly because clients don't follow the steps outlined in this [link religiously](https://developer.service.hmrc.gov.uk/guides/vat-mtd-end-to-end-service-guide/documentation/set-up.html#business-journey-overview).

It seems the main issue could be related to the time it takes to be set up for MTD after signing up with HMRC. Looks like there should be 2 emails after sign up: 1 to acknowledge receipt of your request and the other to confirm you've been successfully set up. Can someone confirm this?

**Comment by mfigueiredo-odoogap** [comment]
Hi everyone!

I currently have a client that, can not access obligations in order to make the VAT Return for this month. He is getting the error "403: client or user unauthorized".
Could you please tell me when is this going to be solved? the user can not operate with our application with this issue.

**Comment by mtd-api-team** [comment]
Please note that the MTD API Team are not able to assist with LIVE issues as we do not have access to the data or systems for authorisation. 

On a separate note, it is possible for a client to authenticate and grant permission to the software provider they wish to use before they have been enrolled on MTD VAT. 

Please contact SDSTeam@hmrc.gov.uk to raise a support request with them please.
