### ISSUE TITLE
Getting error "NOT_FOUND" while getting obligations.

### ISSUE THREAD

**Issue by ramanbatra152** [hmrc/vat-api#605]
Hi Team, one of our client getting the below error when they are E-Filing. The error is when we are trying to get obligations.
 Call : /organisations/vat/{vrn}/obligations
Error:NOT_FOUND The remote endpoint has indicated that no data can be found

Can someone help us getting the probable reason for the above error.

**Comment by cb-rfk** [comment]
Hi @ramanbatra152 ,

There are several threads outlining where other people have seen similar issues.

How long was it between the user registering for MTD and trying to obtain their obligations? You may need to wait 24 hours or more before the obligations are available.

Richard

**Comment by RichardTaxaddict** [comment]
Hello

I have two users reporting the same problem. Can't retrieve obligations.

**Comment by cb-rfk** [comment]
We've just had a user log in, get an error locating obligations, wait ten minutes and successfully get their obligations and make their return, then 3 minutes later get an error looking for obligations again... 

Make of it what you will, but if this was a commercial 3rd party supplying the service I'd be hitting them over the head with their SLA documents by now!

**Comment by RichardTaxaddict** [comment]
It's not all users. We have others passing through OK.

**Comment by RichardTaxaddict** [comment]
It could be because you are selecting the current month for obligations date. It seem to work OK if you use only past months

**Comment by ramanbatra152** [comment]
Yeah It was the date issue, we were using wrong dates. Thanks everyone for your help. I am closing the issue now.
