### ISSUE TITLE
Gov-Vendor-Version Gov-Vendor-License-IDs

### ISSUE THREAD

**Issue by Mushtaq009** [hmrc/vat-api#606]
hey sir i am confused about these headers can you please guide me that what value we have to pass in these headers
Gov-Vendor-Version
Gov-Vendor-License-IDs

**Comment by cb-rfk** [comment]
Gov-Vendor-Version needs to contain the version number of your application. Can be a auto-generated build number or a manually defined string in your application properties etc.

The Gov-Vendor-Licence-IDs is a bit more vague but I think it is for installed (e.g. desktop) software where each instance has a unique licence code specified by you, the vendor. You would need to include this licence code in the header. For web based systems I believe you can leave it blank.

**Comment by Mushtaq009** [comment]
Thanks sir i got your point thanks alot.....
