### ISSUE TITLE
Gov-Client-Device-ID  Gov-Client-User-IDs

### ISSUE THREAD

**Issue by Mushtaq009** [hmrc/vat-api#607]
hey sir i am confused about these headers can you please guide me that what value we have to pass in these headers
Gov-Client-Device-ID
Gov-Client-User-IDs

**Comment by mtd-api-team** [comment]
Hi @Mushtaq009 

The Fraud Prevention Headers are not managed by the MTD API Team hence we are unable to provide specific guidance on them. We will however try and point you in the right direction where we can 😊

Please try and see if any of the following help:
- The guidance on the Developer Hub [here](https://developer.service.hmrc.gov.uk/api-documentation/docs/fraud-prevention)
- Discussions in the previous `fraud-prevention-header` issues [here](https://github.com/hmrc/vat-api/issues?utf8=%E2%9C%93&q=label%3Afraud-prevention-headers+)

If you still require further info please contact the SDS Team at SDSTeam@hmrc.gov.uk as they are the point of contact for such issues. 

All the best
