### ISSUE TITLE
Unable to retrieve token from code

### ISSUE THREAD

**Issue by khabut** [hmrc/vat-api#61]
I have been able to send authorization and received a code back but I am not able to then retrieve the token. I am using curl with example below where I enter my client_id and client_secret and redirect_uri. 

curl -X POST --data 
'client_secret=[]&client_id=[]&grant_type=authorization_code&redirect_uri=[]&code=[]' \ https://test-api.service.hmrc.gov.uk/oauth/token

Any ideas or guidance would be appreciated

**Comment by khabut** [comment]
ok a update for some reason I was able to get this working if I ran this in a without any line breaks. Not sure  why \ did not work when splitting the lines.

**Comment by khabut** [comment]
but would be very useful if I can get  example of submitting the token via a  GET using the token. The example below I cannot get to work via Linux with substitutions. Just returns HTML page.

curl -X GET \
https://test-api.service.hmrc.gov.uk/oauth/token \
-H ‘Accept: application/vnd.hmrc.1.0+json’ \
-H ‘Authorization: Bearer [ACCESS-TOKEN]’

**Comment by scottylace** [comment]
Hi @khabut, 

As recommended by the Developer Hub documentation, only a POST is allowed to the URI /oauth/token. A GET is not possible. 

Scott.
