### ISSUE TITLE
Timed Out, then 503 message and then it worked ?!?!?

### ISSUE THREAD

**Issue by vremeni4** [hmrc/vat-api#610]
Hi ,

We use Microsoft Dynamics Business central 365 for our client to submit VAT returns.
The code was extensively tested by Microsoft and works for many other clients.

Anyhow for one particular client based in South of France, we have very strange issues.
Last week, they ran "Get VAT periods" to get the obligations and this worked fine.
After that they tried to submit the VAT return but we got the error message
"The operation has timed out".

So yesterday evening (06/05/2019 between 20-22h) I investigated this issue.
I noticed (Wireshark) that the system got connected to
https://api.service.hmrc.gov.uk
and it was waiting for a reply.
As timeout was set to 1 minute, as soon as 1 minute hit I got the above error message.
Hence I increased the timeout to 5 minutes.

I ran the "submit the VAT return" again and I got the error message 503 Service unavailable.
To check if service is available I ran again "Get VAT periods" to get the obligations.
This worked fine, so something else was the issue.
I checked the messages, header all was fine. 

So I tried again to submit the VAT return, and it failed again 503 Service unavailable.
Then all of a sudden on third attempt in worked ?!?!?!
I stress, nothing was changed in the mean time. 

I am not sure if the issue is caused by "slow" internet connection as  the server of our client is based outside the UK or is there some restrictions for IP's coming from outside the UK ? 
On the other hand the messages exchanged are rather small, so this should work fine, regardless of internet connection. 

This is the URL for 
https://api.service.hmrc.gov.uk/organisations/vat/183495475/returns

Did someone else had similar issue in the past ?
More importantly what is the reason/cause of this issue  ?

Thanks for your help.

**Comment by mtd-api-team** [comment]
Hi @vremeni4 - for live queries, please email SDSTeam@hmrc.gov.uk and inform them that you have been sent to them by the vat-api team. Intermittent 503 responses sound like a wider API Platform issue, so if you send an email to SDST they will be able to liaise with the relevant teams and look into this issue for you.

**Comment by MatthewHill44712** [comment]
vremeni4: Are you able to comment on how you increased the timeout?

**Comment by vremeni4** [comment]
In the application that we use, there was option to do this. Also I am not sure if this resolved the problem, or might be I was just lucky.  Also refreshing the access token before submitting the message might be also an option. Sorry I cannot help you more.

**Comment by MatthewHill44712** [comment]
I'm a Dynamics NAV Developer, struggling to understand why we are getting timeouts in the standard MTD offering, like you appear to be using.  I'm desperate to be able to demonstrate to management why I think this is an issue with HMRC's API, but I need the info. to be able to prove that.

**Comment by vremeni4** [comment]
I was also working in Dynamics NAV 2017. The timeout was set in the codeunit, that makes the API call, there is a parameter for timeout. Have a look if you cannot find it let me know and I will double check.   
In NAV you can only make production calls to MTD only, so make sure that your HMRC access code is working, (user should be able to login on the HMRC portal, access token refresh in NAV has to work) 
Also very important,  one username/pas per company, so do not use the same one for different companies. With fiddler to see something you have to change the NAV Service to your username, otherwise it is not going to show much.

**Comment by MatthewHill44712** [comment]
I don't know what it was, but I refreshed the Token and increased the timeout and the submission was accepted.  I suspect it was the Token refresh, as it was instantaneous.

Many thanks!
