### ISSUE TITLE
Only getting 3-digit period key

### ISSUE THREAD

**Issue by RichardTaxaddict** [hmrc/vat-api#611]
We have two users who are only receiving 3 of the 4 digits in their period key. All other users are receiving the four digits correctly.

**Comment by RichardTaxaddict** [comment]
We have two users who are only receiving 3 of the 4 digits in their period key. All other users are receiving the four digits correctly.

**Comment by RichardTaxaddict** [comment]
I have one more user reporting this again to day. But all others filing fine.

**Comment by mtd-api-team** [comment]
Hi @RichardTaxaddict 

Occasionally, the periodKey can contain the `#` symbol - are you stripping off any non-alphanumeric characters (e.g. `#001` -> `001`)?

If not and the backends are in fact returning three-digit period keys, please email SDSTeam@hmrc.gov.uk and inform them that you have been sent to them by the vat-api team - they will be able to liaise with the relevant teams and look into this issue for you.

**Comment by RichardTaxaddict** [comment]
HI

I believe we have been doing this. If the period contains # we replace the symbol with “%23”. 
Our MTD Excel tool is doing precisely what was suggested as part of the development by HMRC as per the below:
The period key is the ID code for the period that this obligation belongs to. The format is a string of four alphanumeric characters. Occasionally for special periods, the format includes a # symbol (e.g. #001), so the period key must be percent-encoded, for example 18AD, 18A1, %23001.

So we presume it is at HMRC's side, as you suggest.

We have only seen four such cases out of about 300.

**Comment by RichardTaxaddict** [comment]
Any update on this?

**Comment by mtd-api-team** [comment]
Hi @RichardTaxaddict,

The MTDAPI team don't have any control with the data. Please contact SDSTeam @ SDSTeam@hmrc.gov.uk, they will direct you to the relevant team.

Thanks

**Comment by RicStrang** [comment]
Shouldn't that be SDSTeam@hmrc.gsi.gov.uk ?

**Comment by RichardTaxaddict** [comment]
We raised with SDS and are awaiting an answer.

I understand there is a major reconfiguration this weekend? Hopefully this will include this issue.

We have now filed hundreds, and still only seen this four times.

**Comment by cb-rfk** [comment]
> Shouldn't that be [SDSTeam@hmrc.gsi.gov.uk](mailto:SDSTeam@hmrc.gsi.gov.uk) ?

No, the gsi part of the email domain has recently been dropped across gov email systems :)

**Comment by RicStrang** [comment]
> > Shouldn't that be [SDSTeam@hmrc.gsi.gov.uk](mailto:SDSTeam@hmrc.gsi.gov.uk) ?
> 
> No, the gsi part of the email domain has recently been dropped across gov email systems :)

Ah..
We got a bounce back on Tuesday from SDSTeam@hmrc.gov.uk, has it been changed since then?

**Comment by RichardTaxaddict** [comment]
Fixed this one. Thanks. Closing

**Comment by AlexJSH** [comment]
@RichardTaxaddict - Would it be possible to let us know what the fix was please? Was your software inadvertently culling the # or was it an issue HMRC side?

Useful for anyone hunting on this subject who finds this thread :-) Thanks....
