### ISSUE TITLE
MAC Address Format

### ISSUE THREAD

**Issue by shaunl23** [hmrc/vat-api#612]
After a month I have feedback on my AF Headers.

Could anyone help me with MAC Addresses please?

The example on the documentation (Gov-Client-MAC-Addresses: ea%3A43%3A1a%3A5d%3A21%3A45,10%3A12%3Acc%3Afa%3Aaa%3A32)
uses %3A which indicates a ';'

When I retrieve them they use '-' where the example has a semi-colon. 
Does anyone else's use a dash, and is that ok or should I replace the dash with a semi-colon?

Thanks

**Comment by GrahamHDawson** [comment]
Yeah I use IPConfig to get the MAC addresses and just replace all the '-' characters with semi-colons before URL Encoding.
Seems that's what they expect.

**Comment by shaunl23** [comment]
@GrahamHDawson I'll do that as well then!
Thank you for your help :)
