### ISSUE TITLE
Gov-Client-User-Agent - No Manufacturer or Model

### ISSUE THREAD

**Issue by shaunl23** [hmrc/vat-api#613]
Hi All,

I've had feedback for my headers and have now implemented some changes.

I have re-submitted headers for review but have had to explain something to them, and wondered if anyone else is seeing this:

Using command prompt, and in my app, I can retrieve the device manufacturer and model on a PC. I have a second PC though, and it always returns nothing:
![image](https://user-images.githubusercontent.com/47116717/57312702-fadb2b80-70e5-11e9-929e-012e3ff7b9d0.png)

It is generic / custom built and so returns nothing. I therefore cannot send the information in fraud headers.

Has anyone else come across this situation?

Thanks

**Comment by mtd-api-team** [comment]
Hi @shaunl23 

Please refrain from opening new Issues regarding Fraud Prevention Headers, and instead use #565 if you want input from other developers. This Issues page is for questions about the code in this repository; the MTD API Team cannot answer questions regarding these headers as they are not managed by us. If you require HMRC support, please contact SDST at SDSTeam@hmrc.gov.uk.
