### ISSUE TITLE
Sandbox app removed or wider issue?

### ISSUE THREAD

**Issue by ddaddy** [hmrc/vat-api#614]
This seems the only place to get some pretty quick feedback, so I am getting Error 500 response from the Sandbox when trying to login. I noticed that my Sandbox app is no longer listed in my list of apps in the developer portal!
Initially I thought maybe it had been deleted by HMRC as my app is now live, but surely not?!

Then I looked again at the MTD API docs and it says `Available In Sandbox: NO`

I can’t remember if it used to say Yes and it’s changed because of a server issue, or whether it always said NO and it’s a typo I’m reading too much into?
![DC30E3BB-2AF5-4C47-8D5D-41F33C95EBC2](https://user-images.githubusercontent.com/1425808/57335179-b7021980-7119-11e9-9d32-94358ea4c316.png)

**Comment by heythisiskishore** [comment]
Hi Folks,

We are also facing the same issue 500 internal server message.

**Comment by stuy1974** [comment]
We are also experiencing the same issue.

Any idea when the Sandbox will be back online?

Regards, Stuart

**Comment by Saipalazhy** [comment]
Hi guys,
we are facing same issue, Internal server error [500].

**Comment by ddaddy** [comment]
Well that’s slightly comforting. Have your sandbox apps also disappeared from your app list?

**Comment by stuy1974** [comment]
Yes.  We only have our PRODUCTION application listed now!  No Sandbox :-(

**Comment by coderms** [comment]
Hi. I'm encountering issues with HMRC test-api authorize endpoint. It's outputing error:
{"error":"server_error","error_description":"unexpected error occurred","state":"XG4biLy0UqLEOYnX2kWoA"}

**Comment by msinga** [comment]
Same here - this caused all my nightly automation to fail 😢 😞

**Comment by LukeHirst** [comment]
I am also getting the same issue with following response: 

{"error":"server_error","error_description":"An unexpected error occurred"}

**Comment by paulmowat** [comment]
I'm also getting the above when trying to communicate with the sandbox.

**Comment by mtd-api-team** [comment]
HMRC is aware of an issue with test application deployment. This is affecting the VAT MTD Sandbox. It is currently investigating the issue.

**Comment by paulmowat** [comment]
@mtd-api-team thanks for letting us know. is there anywhere that can be checked to see the status of these environments?

**Comment by ddaddy** [comment]
@mtd-api-team Why does the service status not reflect this at https://api-platform-status.production.tax.service.gov.uk/

**Comment by mathiasbanda** [comment]
So if the support team is aware there is an issue why does the service availability page say all systems are running fine? WHY????

**Comment by mathiasbanda** [comment]
> 
> 
> HMRC is aware of an issue with test application deployment. This is affecting the VAT MTD Sandbox. It is currently investigating the issue.

So if the support team is aware there is an issue why does the service availability page say all systems are running fine? WHY????

**Comment by mtd-api-team** [comment]
We’ve raised this with the team who look after that page and they’re looking into why it is misreporting. They are looking into it.

**Comment by mathiasbanda** [comment]
> 
> 
> We’ve raised this with the team who look after that page and they’re looking into why it is misreporting. They are looking into it.

I don't mean to be funny we are all very supportive of the efforts you guys are making to make MTD work but I am finding it hard to appreciate why that should be an issue. This isn't the first time it's happened on live as well. We were pulling hairs customer complaining they cannot submit vat returns. that page was all green yet there was an issue. Not good enough I am sorry.

**Comment by mtd-api-team** [comment]
All APIs should now be available. Thank you for your patience.

**Comment by NavadaHarsha** [comment]
Hi there, has this issue resurfaced again? We are getting the same errors as yesterday since few minutes.

**Comment by ramanbatra152** [comment]
I guess services are stopped again, could anyone please check and confirm

**Comment by ddaddy** [comment]
Very odd. I had an email earlier (register for notifications at https://api-platform-status.production.tax.service.gov.uk) to say the Sandbox was down again although it worked fine for me.
I've since had one saying its all fixed yet you say it's down.
