### ISSUE TITLE
Link to Business Tax Account without requiring username/password

### ISSUE THREAD

**Issue by cb-rfk** [hmrc/vat-api#616]
Hi,

Does anyone know if you can link to the user's Business Tax Account without them needing to log in again?  I.e. can we pass the same AOuth token as we use accessing the api?

URL we are currently sending the user to is this:

https://www.tax.service.gov.uk/account

but they get redirected to this:

https://www.access.service.gov.uk/login/signin/creds

Thanks.

Richard

**Comment by GrahamHDawson** [comment]
You can't do this AFAIK.

Originally we had code to auto-fill the user credentials in the MTD VAT Authorisation webpage and HMRC asked us to remove it.
They want end-users to fill in their own credentials and don't want software bypassing these screens or automating them in any way.

**Comment by cb-rfk** [comment]
Okay thanks @GrahamHDawson . Will close the call in that case.
