### ISSUE TITLE
Live Environment agent check relationship not working using existing token

### ISSUE THREAD

**Issue by ramanbatra152** [hmrc/vat-api#618]
Hi Team, we have faced an issue recently when we tried to E-File for a company as an agent. We have completed the grant authority part ,got an agent token along with the refresh token.When we tried E-Filing after the token got expired i.e after 4 hours , we got the new set of {token,refreshToken} using refresh token request. Using this new token when we are trying to check agent-client relationship we got the below error :

**NOT_AN_AGENT** This user does not have a Government Gateway agent account. They need to create an Government Gateway agent account before they can use this service.

And strange part is when we do the grant authority again and use the fresh token, the relationship check API call is successful and even we are able to submit the payload using same token.
Issue is only when the use the token we received as a response of refresh token call response.
We are only facing the issue with the live APIs, Sandbox it is working fine.

**Comment by mtd-api-team** [comment]
Unfortunately problems relating to authorisation and authentication are outside the scope of this respository and its issues channel. They should be addressed to SDSTeam@hmrc.gov.uk who hopefully will be able to help you.
