### ISSUE TITLE
PeriodKey format

### ISSUE THREAD

**Issue by MrNicks** [hmrc/vat-api#619]
I hope you can answer a question on the format of the periodKey in the list of obligations you return.

The sandbox currently returns the following two obligations:

{
    "obligations": [
        {
            "start": "2017-01-01",
            "end": "2017-03-31",
            "due": "2017-05-07",
            "status": "F",
            "periodKey": "18A1",
            "received": "2017-05-06"
        },
        {
            "start": "2017-04-01",
            "end": "2017-06-30",
            "due": "2017-08-07",
            "status": "O",
            "periodKey": "18A2"
        }
    ]
}

Can you please confirm the format of the periodKey is as follows:

18           -              the id of the VAT Year, so all obligations for the same VAT year will have this same id, in this example 18?
A1           -              the sequence of the obligations in the VAT Year, A1 being the first, followed by A2, A3, and A4 for quarterly obligations?
What is the significance of the ‘A’ in the second part of the periodKey?

If we had obligations in the previous VAT Year hopefully the first part of the periodKeys in those obligation records would be 17?  So we would then have obligations with the following periodKeys:

17A1
17A2
17A3
17A4

If a year had 12 obligations that the keys would range from for example 17A1 to 17A12?

**Comment by cb-rfk** [comment]
The API documentation contains this:

_The ID code for the period that this obligation belongs to. The format is a string of four alphanumeric characters. Occasionally the format includes the # symbol.

For example: 18AD, 18A1, #001_

To be honest, you are probably best off not trying to work out what it means, but give the user a way to select the obligation they are interested in working with and then use the start and end dates associated with the selected obligation to do your local processing, and then just use the period key as given when you submit the return.

**Comment by MrNicks** [comment]
Thanks for your reply.  I was hoping to use the PeriodKeys to locate records in our own database for associated obligations in the current VAT Year and then to also locate obligations in the previous VAT Year for the matching period.  Example if the obligation in the current VAT Year had the periodKey 18A1, then I can then lookup a record with the periodKey 17A1.

**Comment by cb-rfk** [comment]
Are you going to store the HMRC period keys alongside your own data? Doesn't sound like good practice, and you won't be able to look up pre-2019 obligations via the HMRC website to get the associated dates for them anyway.  You'd be far better off (in my opinion!!) getting the start and end dates of the user-selected obligation and then manipulating those dates to do your database look-ups.

Also, I can't really think why you would be looking up previous year tax information in the context of viewing/submitting the current return, but maybe you do in fact have a reason for this..  :D

**Comment by GrahamHDawson** [comment]
Hi @MrNicks 
Just treat the period keys as a unique, for the particular VRN, but otherwise random string of 4 characters - that's the only **safe** way to approach it IMHO.
Remember you can't show the user the period key (if you have done this then when you do your acceptance demo they'll ask you to remove them)

**Comment by MrNicks** [comment]
Thanks for your responses both @cb-rfk and @GrahamHDawson I'll leave the periodKeys and not expect any particular format and will use the period start and end dates to do what I require.

**Comment by jordanshep** [comment]
Does anyone know if it is normal for periodKey formats to change for MTD? We have a company that has always submitted their VAT returns using numeric format (e.g. 0419) but the retrieve obligations endpoint is showing the latest open period in alphanumeric format (e.g. 19A1). Obviously we do not want the company to submit a return for an incorrect period. I have contacted SDS Team with this but just curious if anyone else has seen this?

**Comment by mtd-api-team** [comment]
It is normal for the periodKey formats to change. You should use periodKeys from retrieved obligations as a basis for submissions.

**Comment by GrahamHDawson** [comment]
Hi @mtd-api-team 

Are we correct to assume the Period Key is **unique** for a particular user ie it will not be used again?

**Comment by GrahamHDawson** [comment]
Found this in close issue #80 from a contributor...

> @swdatatracks A unique period key is created for each obligation, and in the same way the period key is unique to the VRN, so think of it as an 'ID' for a particular obligation period for particular VAT customer. This period key should be used as the period key included in your Vat Submission for that period.

**Comment by mtd-api-team** [comment]
Advice from the business is as follows:
>1. For VAT, each instance occurs unique to the VRN (there are many 19A1 but only one occurrence for a given VRN)
>2. Monthly and Quarterly periodKeys _are_ structured (Year, Stagger,Period) but this should not be considered by you, who should only use it as a unique ID (see 1).
>3. Yes periodKeys can - and will - switch from numeric to alphanumeric format. The obligation will detail the period coverage, represented by the periodKey.  A check should be made to ensure that the correct periodKey is used in any submission.
