### ISSUE TITLE
INTERNAL_SERVER_ERROR for /vat/{vrn}/obligations 

### ISSUE THREAD

**Issue by karthikaharidas** [hmrc/vat-api#62]
Getting the Internal server error {"code":"INTERNAL_SERVER_ERROR","message":"An internal server error occurred"}  .
We are getting the Internal server error whenever the from and to dates are less than 6 months apart( E.g.:- from=2017-01-01 , to=2017-06-30 ). Is this a requirement on the dates ? If this is a valid error which we might have to consider for the PROD environment , is there a way to provide a more detailed / readable error message pointing to the actual issue ?

**Comment by jonathanleather** [comment]
@karthikaharidas 
We are looking into this issue, we will get back to you asap.

Cheers
Jon

**Comment by jonathanleather** [comment]
Hi @karthikaharidas 
This is not a valid error, it appears to be a limitation in the canned responses provided.
There are no restrictions on dates other than those specified in the documentation. For example if the From and To dates were 1 month apart, that would be a valid request.

I have raised a story for the team to review the current responses and amend accordingly. 

Cheers
Jon

**Comment by karthikaharidas** [comment]
Thanks Jon.

**Comment by audupa** [comment]
@jonathanleather Thanks for the response.
Could you please let us know when this would be fixed in the sandbox, so that we aren't blocked on our e2e testing using the sandbox api's.
If there is issue/story logged, could you send us that so that we could watch it?

**Comment by jonathanleather** [comment]
Hi @audupa 
Unfortunately I am unable to provide specific date as the story is currently being prioritised by the project.
Our Jira boards are internal only so you wouldn't be able to view the story.
Sorry that I can't be of any more help!

Cheers
Jon
