### ISSUE TITLE
Delay in filed VAT return being acknowledge?

### ISSUE THREAD

**Issue by RichardTaxaddict** [hmrc/vat-api#620]
Hi. We have two users today reporting their successfully filed returns aren't being acknowledged when they check in their Gateway account. And known delays or reasons?

**Comment by mtd-api-team** [comment]
Hi @RichardTaxaddict,

That's not something we would normally be able to assist with, although this is the guidance we have been given by the business:

>If the software submitted a VAT Return from Monday to Friday during normal working hours, you can use the API to provide a view of the return by the following morning or earlier. If the software submitted a return after 6pm on a Friday, then the return might not be viewable until the following Tuesday, or Wednesday if a bank holiday weekend. If the return was received within the required time frame, no penalty should have occurred, because the obligation would have been marked as met on the date it was received.

More information can be accessed [here](https://developer.service.hmrc.gov.uk/guides/vat-mtd-end-to-end-service-guide/documentation/obligations.html#receive-obligations-and-submit-a-vat-return).

Hope this helps.

**Comment by RichardTaxaddict** [comment]
Hello - we have 3 users who filed but still not showing in HMRC Gateway. (We have filed many more with no problems). We are getting the endpoint message from HMRC as filed. But it is not being shown by HMRC Gatway
