### ISSUE TITLE
User not showing any obligations

### ISSUE THREAD

**Issue by RichardTaxaddict** [hmrc/vat-api#621]
A user is showing no current obligations.

Their 2018 filings are showing. As an aside, the filing date received is wrong in each of the three 2018 filings. Showing dates prior to the period endings.

But nothing for 2019

**Comment by AlexJSH** [comment]
Are they numeric period keys? If so then this is a known bug....

(Sorry can't remember the issue number but has been noted in quite a few places - supposedly there will be a fix in June for it)

**Comment by AlexJSH** [comment]
@RichardTaxaddict
#592 and #596 are some of them...

**Comment by RichardTaxaddict** [comment]
Yes, sounds like #592

**Comment by RichardTaxaddict** [comment]
I will close this and add to #592
