### ISSUE TITLE
New problem since yesterday of zero return retrieved by 'View VAT Return' API even though 'Submit VAT return for period' succeeded with correct figures.

### ISSUE THREAD

**Issue by obbc** [hmrc/vat-api#625]
In addition to the other problems reported here, is anyone else currently experiencing this new problem?

This is very disconcerting for our users as it's another case where it looks as if the return has not been received successfully.  One customer has phoned HMRC and after many hours was told that the return with figures has been received and by implication, the 'View VAT Return' API obviously isn't working properly.  They wouldn't however be receiving their refund before the maximum 28 days even though they would usually receive within a few days.  Our customers are predominantly on refund for VAT so timely payments are critical to cash flow.

Grateful for any feedback.

**Comment by mtd-api-team** [comment]
Morning @obbc 

The API team are aware of this issue, and are currently waiting on SDST to investigate the backend systems in order to identify a fix.

**Comment by obbc** [comment]
Thank you for the response.  Can HRMC please update their service status page with all these problems as this will help us manage the considerable fallout with our customers.

https://www.gov.uk/government/publications/making-tax-digital-for-vat-service-availability-and-issues/making-tax-digital-for-vat-service-availability-and-issues

**Comment by obbc** [comment]
HMRC also need to publish details of what these faults will mean for end users.  For example, does a zero return mean that they need to phone HMRC in order to make sure their correct return has been received or are they safe in the knowledge that the return will have gone through?  

The same information is required for the scenario where the obligation is missing completely under 'Retrieve VAT obligations'.  What if they submitted two different returns for the same period (it shouldn't have been possible but it was allowed) – which one will stand?  We don't have answers to these questions yet.

At the moment the HMRC helpline is turning everyone away due to volume of calls.  These API / system faults all require some published information so the end user understands what they can expect to happen and what they need to do.

**Comment by mtd-api-team** [comment]
We are in contact with the team who own the "Making Tax Digital for VAT: service availability and issues" page in order to get this updated.

**Comment by obbc** [comment]
Thank you.  A list of current and historical problems together with what the end user can expect under those scenarios would be very helpful.

**Comment by GrahamHDawson** [comment]
Hi @obbc 

Could you explain the issue a little more please.
What is meant by a **zero return** ?

**Comment by obbc** [comment]
The 'View VAT Return' endpoint is returning HTTP status 200 but the "vatDueAcquisitions",
  "totalVatDue",  "vatReclaimedCurrPeriod",  "netVatDue",  "totalValueSalesExVAT",
"totalValuePurchasesExVAT",  "totalValueGoodsSuppliedExVAT" & "totalAcquisitionsExVAT" fields are either returning zero values or missing from the root of the JSON object.  

I haven't yet been able to debug what JSON payload is being returned but will try to find out on Tuesday with the help of a customer who's having this issue.

**Comment by GrahamHDawson** [comment]
Thanks @obbc - lets hope they sort this ASAP

**Comment by obbc** [comment]
Just to confirm that HMRC are indeed returning data in the correct format with this scenario, it's just that every box has a zero value as per:

2019-05-29 10:07:57: The VAT return received from HMRC for period 01/04/19 to 30/04/19 does not match the locally stored VAT return
Last Response: {"periodKey":"19AD","vatDueSales":0,"vatDueAcquisitions":0,"totalVatDue":0,"vatReclaimedCurrPeriod":0,"netVatDue":0,"totalValueSalesExVAT":0,"totalValuePurchasesExVAT":0,"totalValueGoodsSuppliedExVAT":0,"totalAcquisitionsExVAT":0}

Haven't had any more customers reporting this problem so far this week.  Our information indicates the problem might only relate to MTD-VAT submissions on or around 14th / 15th May 2019.

Perhaps HMRC can give us an update on the status of this one?

**Comment by mtd-api-team** [comment]
Hi @obbc,

We are still waiting for an update from our backend teams, and they are investigating this as a high priority.
Actually, this is not the main source of communication for production issues, but we will definitely update you as soon as we receive an update.

Thanks,

**Comment by mtd-api-team** [comment]
Hi @obbc,

We have been informed that this has now been resolved, so this is issue will now be closed. If you find that this reoccurs please reopen this issue or create a new one.

Thanks
