### ISSUE TITLE
API  does not allow a submission if the return is a credit value

### ISSUE THREAD

**Issue by brucemcmillan** [hmrc/vat-api#628]
**Describe the bug**
The API  does not allow a submission if the return is a credit value. 

Some companies are actually owed money from HMRC after their tax return. Ironically most customers ive been dealing with today have this issue. Im being pushed by the customers to get this resolved asap as they are now overdue for their return

**Expected behavior**
API should accept values for credits

**Screenshots / Requests / Responses**

![API Error](https://user-images.githubusercontent.com/4041335/58343749-b96baf80-7e4b-11e9-8f35-736ad210f9d9.png)

**Comment by rajitha0007** [comment]
We had the similar issue few months back during our testing in the sand box.
For this vat box, HMRC still expect you to send a positive (+) value. Based on the values in ‘totalVatDue’ and’ ‘vatReclaimedCurrPeriod’ Vat boxes HMRC will determine HMRC has to pay back or VAT entity has to to pay. So this box accepts positive values only.

Given below is the explanation provided in the API documentation in the HMRC Dev Hub;
netVatDue
number
required
The difference between totalVatDue and vatReclaimedCurrPeriod. This corresponds to box 5 on the VAT Return form. The value must be between 0.00 and 99999999999.99

**Comment by LukeHirst** [comment]
It is my understanding that you should send the absolute value of the result of your calculation as box 5. 

I have asked this question before as part of this ticket #270

**Comment by mtd-api-team** [comment]
As stated above, the value for box 5 is always the _absolute difference_ between the two values, and should always be a positive value.
