### ISSUE TITLE
Agent Authorisation API

### ISSUE THREAD

**Issue by KenRandall** [hmrc/vat-api#629]
Hi,

What is the status of the the Agent Authorisation API both in the sandbox and production?

Thanks,

Ken

**Comment by mtd-api-team** [comment]
Hi @KenRandall,

Can you explain what you mean by the status of it? This team do not own this service, although the following was sent out to developers in April.

>We are pleased to advise that Agent Authorisation API v1.0 is now available in the HMRC Developer Hub as public beta. This version remains unchanged from our private beta version deployed on 14 March 2019.
>
>This API allows agents to create a relationship with their clients within the scope of MTD SA and VAT. It also allows an agent to cancel and check the status of the relationship.
>
>Since our Private Alpha launch on 12 October 2018, we've tested the Agent Authorisation API extensively to make sure it meets user needs. We will like to thank those who provided invaluable insights to help us develop the API.
>
>Whitelisting
>
>Please note that you do not need to be whitelisted to subscribe to the API in production. If you have any questions on how to subscribe your production application to the API, please contact Software Developer Support Team.
>
>Technical Support
>
>If you have any technical query about the API, please do not hesitate to contact us through Github. Alternatively, you can contact Software Developer Support Team and we will be happy to assist you.
>
>Live Support
>
>To use the API, agents will need to have registered for an Agent Services Account and their clients subscribed to MTD. You can find more information on this on Gov.uk.  Please follow appropriate sections within the guidance for live support.
>
>Thank you for your continued support.
