### ISSUE TITLE
Application Approval

### ISSUE THREAD

**Issue by AndyYouens** [hmrc/vat-api#630]
Hi all

How long is it taking to get an application appoved by HMRC? on  their application page it says 10 working days, been waiting 3 weeks now to get a new client registered,  How long can it take them??

Our application was approved by HMRC in March so dont understand their issues.

Tried emailing, tried emailing again, but no response whatsoever!  This client needs to submit his return. he's getting nervous now & so am I :-(

**Comment by mtd-api-team** [comment]
Hi @AndyYouens,

Sorry that you are having problems with this - can we just clarify, is your software already authorised in Live and have you got clients already using your software, or is this the first client that you are putting through and you are still waiting for approval after signoff from HMRC?

This is not normally our area but we can probably try and look into this for you.

**Comment by AndyYouens** [comment]
thanks for the reply mtd-api-team

Yes it is the same application/software that has been approved by HMRC in March and is currently is use by other clients.

This new client needs the application credentials, secret key etc, so he can run it on his server.

Appreciate your help with this.

**Comment by mtd-api-team** [comment]
Ok, thanks for that @AndyYouens.  

Our understanding is that you would continue using the existing application credentials.  These are for your application itself, so should be used for all instances of it.

Is this a one off install on a new client site or is there likely to be more as time goes by?  We're just awaiting some further clarification and advice from one of the teams on the platform about this.

**Comment by AndyYouens** [comment]
thanks for the reply @mtd-api-team 

The problem with using only one application for all our clients is that you can only specify 5 callback URLs per application.  Our application will be running on our clients server so needs their URL calback details.

Please let us know if there is a better way of doing this.

**Comment by mtd-api-team** [comment]
We will pass this on @AndyYouens.  We will get back to you when we have some guidance.

**Comment by JeeBeePee** [comment]
@AndyYouens I raised this during my demo and was told that there are two options:

- Every client who wants to deploy the software has to do the demo, get their own credentials and manage their own callback URIs. I suppose you could call it a conformance test, if the demo process was at all rigorous.

- You have to run a publicly-available authentication service; all client deployments send authentication requests to that service, which calls HMRC, gets a bearer token and returns it to the client instance. You then own the security on the auth service.

**Comment by AndyYouens** [comment]
@JeeBeePee thanks for your reply.

We expected to get our software approved by HMRC, which we did, sell it to our clients, they loaded it on their server & away they go!

This would work fine for us if you could put multiple URL callbacks in the HMRCs applications details.

This really hasnt been thought thro by HMRC.

Anyone else got any suggestions/how they deal with this?

**Comment by mtd-api-team** [comment]
@AndyYouens the feedback we have had from the API platform team is below.

>They either need to use some DNS entries which are common across all of their clients (like making use of an internal DNS entry for the re-direct and then making an entry for this on each clients DNS server) or hosting something externally which forwards to all their clients.

At the moment this is not a common pattern across our 3rd party clients, which is why it may seem to you that it hasn't been given much thought.  What I would suggest, is that if this is a model that is important for you as vendors that we support in the future that you contact SDST (SDSTeam@hmrc.gov.uk) who are in the best place to triage the requests and drive future changes on the platform.

**Comment by mtd-api-team** [comment]
Closing this for now.  There is some feedback coming around that I know you were involved in @AndyYouens, where more information of will be provided about the status of this.

Feel free to open the issue again if there is further conversations to be had in the future.
