### ISSUE TITLE
#419 Period Key not filing returns at HMRC

### ISSUE THREAD

**Issue by RichardTaxaddict** [hmrc/vat-api#633]
Hello

We have 6 users who have #419 Period Keys. When they file, HMRC is not recognising the filing even after waiting a week.

We have tried the affected returns on two independent and recognised MTD solutions our company provides (one Excel bridging; one API) which have both filed hundreds of MTD returns in the past weeks. Both solutions produce dummy VAT 100's when the filing happens, and this relies on them receiving the endpoint filing. So it's unclear why HMRC is not recognising the filings - we are unsure if configuration problem at HMRC's end? The two tools were built be independent teams so we cannot follow why we would have the same problem.

Any guidance?

**Comment by mtd-api-team** [comment]
We are unable to help you with this other than to suggest that you double check these period keys. Should they be 0419?

You should contact SDSTeam@hmrc.gov.uk who will be able to look into this in more detail.

**Comment by RichardTaxaddict** [comment]
We have contacted SDS and waiting on their response.

An interesting development is that we operate another recognised MTD filing solution, aimed at Enterprise. We tried 4 of the problem returns with the #419 Period Key. One went through; but the other 3 were not recognised. Very curious.

**Comment by RichardTaxaddict** [comment]
All resolved. Thanks

**Comment by AlexJSH** [comment]
@richardtaxaddict
Hi Richard - can you clarify if this was solved by HMRC or by software changes?
Thanks
Alex

**Comment by RichardTaxaddict** [comment]
Hi - yes, solved. I closed the ticket.

Kind regards

Richard Asquith | 
VP, Global Indirect Tax   

 
e: Richard.Asquith@avalara.com
Avalara | Tax compliance done right 

On 19 Jun 2019, at 15:13, AlexJSH <notifications@github.com<mailto:notifications@github.com>> wrote:


@RichardTaxaddict<https://github.com/RichardTaxaddict>
Hi Richard - can you clarify if this was solved by HMRC or by software changes?
Thanks
Alex
