### ISSUE TITLE
Not getting charge reference number when submitting VAT return in the live enviroment.  

### ISSUE THREAD

**Issue by Cheviwa** [hmrc/vat-api#635]
# Bug report

You must read the information below before you submit a bug report. 

The MTD API team cannot help if your bug report is about:

- Fraud Prevention Headers
- Issues relating to OAuth2
- Subscribing or registering to use the API Platform, MTD enrolment, de-enrolment, registration for VAT, Beta services, etc.
- Issues integrating with the API Platform (e.g. setting up an application/access)
- Code examples in a given programming language
- Business-related questions or processes pre MTD
- Scheduled maintenance windows and days
- Onboarding (e.g. registering, obtaining keys)
- Performance metrics

For any of the above, you **must** contact the Software Developer Support Team directly at SDSTeam@hmrc.gov.uk.  The SDS Team do not monitor this repository.

This repository is for bug reports relating to VAT API code in this repository only.

Fill in the sections below to submit your bug report:

- [ ] Documentation
- [ ] API 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots / Requests / Responses**

**Additional context**

**Comment by mtd-api-team** [comment]
Thank you for your bug report. 

Please can you give more information about exactly what happens and what you expect to happen (as indicated in the bug template, above) so that we can determine who can best support you with this.

**Comment by GrahamHDawson** [comment]
Hi @Cheviwa 

According to the documentation...

> The charge reference number is returned, only if the netVatDue value is a debit. 

So maybe that's why you're not having it returned?

**Comment by Cheviwa** [comment]
Our customer submitted a VAT Return in production environment. 

However they didn’t received a charge reference number back. 

We were under the impression that they would get one back each they submit. 

 

Regards

Chevaun

**Comment by Cheviwa** [comment]
Hi Graham

 

Alright thank you for this clarification.

 

Regards

Chevaun
