### ISSUE TITLE
The remote server returned an error: (401) Unauthorized

### ISSUE THREAD

**Issue by OladotunO** [hmrc/vat-api#636]
Hello Guys

1, This is an installed application
2,the root url is to
https://test-api.service.hmrc.gov.uk/

2b,  endpoint
/organisations/vat/{vrn}/returns

3,I created a test user and can login

3, I get the Authorisation code scope= write:vat+read:vat
4, I get the obligation
5, When I run the file vat POST, I get the error below
System.Net.WebException: The remote server returned an error: (401) Unauthorized

6, my headers are
Accept
Authorisation
contenttype
Gov-Test-Scenario

7,Code is c#, using webclient

Can I have some pointers on what might be going wrong please

Regards

Ola

**Comment by AndyYouens** [comment]
VRN Correct?

**Comment by mtd-api-team** [comment]
Hi Ola,

Can you clarify a couple of things, maybe it's just a typo error "contrnttype", if not please correct it. And for which "Gov-Test-Scenario" you are getting this error?

Thanks...

**Comment by OladotunO** [comment]
@AndyYouens 
yes it is VRN vat return

@MTD team
I am actually using just the  "-"

**Comment by OladotunO** [comment]
I removed Gov-Test-Scenario from all POST and GET requests from the sequence,
And get the same error

**Comment by mtd-api-team** [comment]
Hi @OladotunO 

`401 Unauthorized` is usually only returned if something is wrong with the access token provided. 401 is an API Platform response, which suggests you weren't able to hit the vat-api because you failed authentication.

Usually Gov-Test-Scenarios that are not recognised are ignored, and no scenario is required on Submit VAT Return to test a successful submission.

It seems strange if you are able to GET Retrieve Obligations, but cannot POST to Submit VAT Return. Can you confirm this is the case?

**Comment by OladotunO** [comment]
Yes, I can GET The obligations, 

Then I insert the retrieved obligation, status “o” into the POST , programmatically, then send POST to file the VAT return

**Comment by mtd-api-team** [comment]
Hi

Assuming you're doing this in the Sandbox, could you provide us with your request URL, Headers and Body. This will help us diagnose the issue.

**Comment by OladotunO** [comment]
Here they Are

These are 
"https://test-api.service.hmrc.gov.uk/organisations/vat/747373702/returns"


Content-Type  "application/x-www-form-urlencoded"
Accept         "application/vnd.hmrc.1.0+json"
Authorization    "Bearer 43cb3f828b1c7baf45385f7a52a5f"

"periodKey=18A2&vatDueSales=200&vatDueAcquisitions=41.8&totalVatDue=200&vatReclaimedCurrPeriod=200&netVatDue=158.2&totalValueSalesExVAT=1000&totalValuePurchasesExVAT=209&totalValueGoodsSuppliedExVAT=0&totalAcquisitionsExVAT=0&finalised=true"

**Comment by mtd-api-team** [comment]
@OladotunO it appears you are sending your payload as a form-urlencoded string.

These are Json API's that need the application/json content type.  Please try sending them with the correct payload type and let us know what you see.

Cheers

**Comment by OladotunO** [comment]
@MTDTEAM
Hi Chaps
I replace the Content-type with
Application/Json

Same error, 401 Unauthorised

**Comment by MarkAKelly** [comment]
@OladotunO have you actually supplied a Json body for the request or have you still used the encoded string?

**Comment by OladotunO** [comment]
@mtd-api-team 
Hi Guys
I was sending encoded URL, but I changed it to a json body, and I still get error 401 Unauthorised

Json below

"{\"periodKey\":\"18A2\",\"vatDueSales\":200,\"vatDueAcquisitions\":41.8,\"totalVatDue\":200,\"vatReclaimedCurrPeriod\":200,\"netVatDue\":158.2,\"totalValueSalesExVAT\":1000,\"totalValuePurchasesExVAT\":209,\"totalValueGoodsSuppliedExVAT\":0,\"totalAcquisitionsExVAT\":0,\"finalised\":true}"

**Comment by OladotunO** [comment]
@mtd-api-team 

Thanks for your help, I found the solution:

It was an access token issue, Coding error, namely, I was using refresh token  and using it as the 
access token
