### ISSUE TITLE
In production, 'Get VAT Obligation' Start and End Dates are not the First and Last Dates of the month or quarter

### ISSUE THREAD

**Issue by dev-efr** [hmrc/vat-api#637]
* **I'm submitting a - [Support request] **

* **What is the expected behaviour?**
Is it correct that the Response Start and End Dates are not First and Last Dates of the month or quarter ?

* **Other information**
1) Live X-Correlationid=[737f5f7d-3bb8-4e74-9faa-ab3fa07fa732] on 29 May 2019
{
  "obligations": [
    {
      "start": "2019-03-31",
      "end": "2019-04-27",
      "due": "2019-06-03",
      "status": "O",
      "periodKey": "19AD"
    }
  ]
}
2) Live X-Correlationid=[c8b8207b-0ebe-49e6-bce8-ee609983dee4] on 03 June 2019
{
  "obligations": [
    {
      "start": "2019-04-01",
      "end": "2019-05-05",
      "due": "2019-06-12",
      "status": "O",
      "periodKey": "19AD"
    }
  ]
}

**Comment by mtd-api-team** [comment]
Hi @dev-efr 

These examples could be correct in the case of non-standard filers. 

There should be no issue if you continue to submit against the obligations returned by the backend, but if you or your client are concerned, I would advise them to contact HMRC and confirm the dates.

Regards
