### ISSUE TITLE
Sandbox - submit VAT return - apparently valid endpoint returns 404

### ISSUE THREAD

**Issue by jjammybiskit** [hmrc/vat-api#638]
# Support request

When submitting a VAT return for a test user (2 users tried so far) in the sandbox I get the MATCHING_RESOURCE_NOT_FOUND response.

The app first gets the VAT obligations for the user
Period Start	Period End	Period Code	Return Due	Status
2017-01-01	2017-03-31	18A1	2017-05-07             Final	 
2017-04-01	2017-06-30	18A2	2017-08-07	       Open
Completed on Tuesday, 04-Jun-2019 08:58 (GMT)

A dummy return is then submitted for period 18A2 to
https://test-api.service.hmrc.gov.uk/organisations/vat/867038304/returns/18A2
where 867038304 is the test user's VRN.

Request:
{
 'content-type' => 'application/json',
 'accept' => 'application/vnd.hmrc.1.0+json',
 'authorization' => 'Bearer 9b14565fb47640615b0484ae09fa355'
}
(Content)
{
 "periodKey": "18A2",
 "vatDueSales": 200.00,
 "vatDueAcquisitions": 0.00,
 "totalVatDue": 200.00,
 "vatReclaimedCurrPeriod": 100.00,
 "netVatDue": 100.00,
 "totalValueSalesExVAT": 1000.00,
 "totalValuePurchasesExVAT": 500.00,
 "totalValueGoodsSuppliedExVAT": 0.00,
 "totalAcquisitionsExVAT": 0.00,
 "finalised": true
}

The response is
{
 "code" : "MATCHING_RESOURCE_NOT_FOUND",
 "message" : "A resource with the name in the request can not be found in the API"
}

I assume the resource referred to is
https://test-api.service.hmrc.gov.uk/organisations/vat/867038304/returns/18A2

I must be doing something daft but I can't see what it is! Anyone got any ideas?

Thank you

**Comment by RalphCPA** [comment]
try removing the periodKey from the endpoint 
https://test-api.service.hmrc.gov.uk/organisations/vat/867038304/returns

also note that below are without decimals (i.e. -9999999999999 to 9999999999999)
totalValueSalesExVAT
totalValuePurchasesExVAT
totalValueGoodsSuppliedExVAT
totalAcquisitionsExVAT

**Comment by mtd-api-team** [comment]
Thanks RalphCPA

Note the fields mentioned will work with whole pounds, but will accept zero decimals `.00`

**Comment by jjammybiskit** [comment]
Many thanks for your rapid response RalphCPA - I was running out of ideas to try.

Looking at the documentation again I must have misread the submitVATReturnForPeriod endpoint with the viewVATReturn endpoint.
