### ISSUE TITLE
Unexpected http status code (201) when sending VAT submission

### ISSUE THREAD

**Issue by RobertMarczycki** [hmrc/vat-api#64]
Hi,

We started experiencing issues when sending VAT submission - it looks like the Sandbox API responds with http status code 201 and empty content instead of 200 and submission response. It happened for VAT no 666807229 and application id 82d3cdb5-85cd-45b8-870b-7246a18ab0c5.

Trying to re-submit data for a VAT no/ period already sent in the past generates expected 403 error and business errors.

Thanks,
Robert

**Comment by jonathanleather** [comment]
Hi @RobertMarczycki 
Thank you for notifying us. 
I have managed to replicate the issue on our end. We are looking into fixing this asap.

Cheers
Jon

**Comment by jonathanleather** [comment]
Hi @RobertMarczycki 
We are currently in the process of pushing through a change for this. Looking to deploy later today or early tomorrow.

Cheers
Jon

**Comment by jonathanleather** [comment]
@RobertMarczycki 
A fix has been deployed for the above issue.
Can you please retest and let us know if you have any further problems.

As a side note - there was another issue whereby the RAML was stating that a success for the 9 box return should respond with a 200. This was incorrect and has been updated to a 201 as per the code.

Cheers
Jon

**Comment by RobertMarczycki** [comment]
👍 It's working, thanks!
