### ISSUE TITLE
INTERNAL_SERVER_ERROR for GET obligations

### ISSUE THREAD

**Issue by jordanshep** [hmrc/vat-api#641]
For a GET obligation request to the endpoint /organisations/vat/{vrn}/obligations, for one client we are getting a 500 INTERNAL_SERVER_RESPONSE when trying to see the next available open period. We are able to get a successful response when looking back at last month's fulfilled return but it seems we are unable to view future periods. This is strange as for several other clients we are able to successfully view future open periods. For the client with unsuccessful response, I have tried using a variety of dates (including the dates I know the next period will be for). Is this simply a case where for this client we are only able to see open periods when we are physically in that period?

**Comment by mtd-api-team** [comment]
What is likely happening is that the MTD registration processing is incomplete for this client. This can sometimes take a few days and can result in future obligations not being available.

We suggest waiting a day before retrying. If it still not working for this client, please update this issue as well as raising this with SDSTeam@hmrc.gov.uk who will be able to look into this in more detail.

**Comment by jordanshep** [comment]
Tried again this morning and receiving the same response; it's strange as this client has successfully retrieved obligations in the past; will raise this issue with the SDSTeam.

**Comment by mtd-api-team** [comment]
Hi @jordanshep,

We are closing this issue as our team are unable to help you further. 

Thanks,
Team MTDAPI
