### ISSUE TITLE
MTD Submision for multiple vat registrations for same client

### ISSUE THREAD

**Issue by khabut** [hmrc/vat-api#643]
We have noticed a issue where a client has made a submission for two vat registrations and the nare unable to make subsequent ones for at least 15 minutes and then the whole process starts again with allowing 2 submissions. 

Is there a time delay on HMRC and why are we not getting a error back. We just get request waiting and timing out.

**Comment by mtd-api-team** [comment]
There is no time delay of this kind built in. 

Can you give us some times when this has happened so we can check our logs to see where the timeout may be.

**Comment by mtd-api-team** [comment]
Hi we're going to close this ticket unless you have any further info for us. Let us know if you are still seeing any issues. Thanks
