### ISSUE TITLE
Issue in Connecting UK VAT site using API

### ISSUE THREAD

**Issue by Ruchi139** [hmrc/vat-api#645]
We are trying to setup VAT returns through our ERP using the API provided by you. We are facing issues in connectivity as our internal security team has blocked access to unwanted sites. They have requested us to provide specific URLs/or IP addresses, so that they can whitelist these URLs & IP addresses for accessing the VAT site.
Request you to provide help.

**Comment by mtd-api-team** [comment]
Hi @Ruchi139 

The MTD API Team do not manage the hosting / network / infrastructure that the code runs on hence we are unable to provide this information. Please contact the Software Developers Support Team at  SDSTeam@hmrc.gov.uk and they will be able to obtain the relevant information for you.
