### ISSUE TITLE
Sequence contains no elements

### ISSUE THREAD

**Issue by syedmasum** [hmrc/vat-api#646]
Trying to submit MTD from cloud platform, using test user generated from HMRC website, returns Sequence contains no elements error when I file.

**Comment by mtd-api-team** [comment]
Hi @syedmasum - so that we can diagnose what's going on, please could you provide:

- The request (including URI, request body and headers) that you used
- The response (including status code and any body you got back) that you received

Many thanks

**Comment by syedmasum** [comment]
[QueryVatObligations.Response.txt](https://github.com/hmrc/vat-api/files/3309588/QueryVatObligations.Response.txt)
[MTD_File_Simple.xlsx](https://github.com/hmrc/vat-api/files/3309591/MTD_File_Simple.xlsx)

XLSX is the data which was tried in submission, as the software I am using asks just this information
TXT is actually the JSON which was returned with the error message. 
Software I am using is the Sovos Compliance so their URL is www.sovos.com 
Company setup has VAT code corresponding to the User I generated using User Generator by HMRC
Software is able to process other users submissions successfully

**Comment by syedmasum** [comment]
Are you able to elaborate on this issue, if this is a recognised error previously with your API and any work arounds etc?

**Comment by mtd-api-team** [comment]
Hi @syedmasum 

Please try your failing request in an HTTP client like Postman, so we can diagnose what is wrong with the request itself.

In the Sandbox environment, you will need to hit the `/{vrn}/obligations?from={from}&to={to}` endpoint with valid Authorization and Accept headers, and by default you should receive a 200 response with the data: 
```
{
  "obligations": [
    {
      "start": "2017-01-01",
      "end": "2017-03-31",
      "due": "2017-05-07",
      "status": "F",
      "periodKey": "18A1",
      "received": "2017-05-06"
    },
    {
      "start": "2017-04-01",
      "end": "2017-06-30",
      "due": "2017-08-07",
      "status": "O",
      "periodKey": "18A2"
    }
  ]
}
```

Looking at your TXT file, it looks like you got that exact response body. What error are you referring to exactly?

**Comment by syedmasum** [comment]
Upon submission of the return, the tool usually displays a success message, for some reason my user returns Sequence contains no elements, and submission fails. Other users in same tool, for same company can submit without errors they get a success message!

**Comment by mtd-api-team** [comment]
@syedmasum it sounds like the issue is with the third party tool you are using. The MTD API team cannot help with any third party tools; please contact the developers of that tool if you need help using it.
