### ISSUE TITLE
sandbox - Submit Return - Returned Headers are not documented correctly

### ISSUE THREAD

**Issue by Soldering-Stan** [hmrc/vat-api#647]
This is an annoying documentation error.
The API document says tha (among others) the following headers are returned when a return is accepted (201 code)

X-CorrelationId
Receipt-ID

These headers actually come back as
X-Correlationid
Receipt-Id

Are there similar differences with the live service ?

Can somebody update the documentation to reflect reality (or update reality to reflect the documentation) please.  It's annoying having to fold the headers.

Regards,

D

**Comment by mtd-api-team** [comment]
Hi @Soldering-Stan,

As per W3 standards, headers should be considered case insensitive. Please go through the URL
https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2

This is happening at the API platform level. This issue has been raised before, have a look, it might help. 
https://github.com/hmrc/vat-api/issues/383 

Thanks...

**Comment by Soldering-Stan** [comment]
Hi,
Thanks for the link to #383 - I hadn't seen that - I wouldn't have bothered raising the ticket if I had :-)
I fully understand the case insensitive issues and am tolowering the headers because of this, however just because they are considered case insensitive doesn't mean that they can be carelessly specified.
The documentation not reflecting reality looks like shoddy workmanship and this is not what is expected from HMRC of all people.
D
