### ISSUE TITLE
Scheduled maintenance overrun?

### ISSUE THREAD

**Issue by ddaddy** [hmrc/vat-api#649]
The scheduled maintenance that was supposed to finish at 5am, is it still ongoing?
I’m getting 500-Internal Error responses now at 1pm Sunday 23rd!

**Comment by JeeBeePee** [comment]
Same. And no update to the service status page despite repeated promises to start doing so in situations like this.

**Comment by ddaddy** [comment]
It’s working now, well at least for my account anyway.
The system status page is pointless. If it says all systems are fine when they’re not then something isn’t working!
