### ISSUE TITLE
Zero value submission error

### ISSUE THREAD

**Issue by sonicmule** [hmrc/vat-api#65]
We are in the final testing stages of our product,.
We are testing a zero value submission, ie all 9 boxes are zero.
When submitting this, we get an INTERNAL_SERVER_ERROR.

Data we submit:-
{"periodKey":"#001","vatDueSales":"0.00","vatDueAcquisitions":"0.00","totalVatDue":"0.00","vatReclaimedCurrPeriod":"0.00","netVatDue":"0.00","totalValueSalesExVAT":"0","totalValuePurchasesExVAT":"0","totalValueGoodsSuppliedExVAT":"0","totalAcquisitionsExVAT":"0","finalised":true}

So, is this a valid submit?
If not, should there not be a more fitting response returned rather than an INTERNAL_SERVER_ERROR?

**Comment by jonathanleather** [comment]
Hi @sonicmule 
The scenario you have suggested is 100% valid. 
I am unable however to replicate the issue you are seeing. Using the data you provided my response = 201 created.

Just as an FYI, there is another issue with the 9 box return that we are currently pushing through a fix for. This can be tracked on issue #64 

Cheers
Jon

**Comment by sonicmule** [comment]
Thanks for clearing that up Jon.
Actually I am getting INTERNAL_SERVER_ERROR on non-zero vat return submits too.
This was working for me before?

**Comment by sonicmule** [comment]
Now resolved see #69
