### ISSUE TITLE
Invalid grant

### ISSUE THREAD

**Issue by mathiasbanda** [hmrc/vat-api#653]
![Capture](https://user-images.githubusercontent.com/17194441/60506413-b02cf880-9cbd-11e9-9071-597d4dd9747f.PNG)
refresh_token is invalid

**Comment by mtd-api-team** [comment]
Hi @mathiasbanda 

This looks like an issue with the OAuth flow, which our team does not manage. I suggest you read through https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation and contact SDSTeam@hmrc.gov.uk if you have any further problems.

Just to clarify, you commented on #540 that you are able to get obligations but unable to submit - you will need both `read:vat` _and_ `write:vat` access if you want to do this within the same application. Did you definitely request both of these OAuth scopes when generating your bearer token?

**Comment by mathiasbanda** [comment]
What i did or what i have done several times is to authorize the application again when the error has come up. Now as part of our side of program flow after authorization we make a call to get obligations and save them to the client machine. To the user it looks and feels like one thing (though we display a progress message to say Getting Obligations. This is passing. It gets obligations. Which makes sense as the user is signed it (no refresh token required). It's when we try using the refresh token to log back in later to do a submission when that error comes up
