### ISSUE TITLE
Unable to Access Developer Hub

### ISSUE THREAD

**Issue by AndyYouens** [hmrc/vat-api#657]
Not API related but need help!

I need to login into the developer hub to register a new client for our application.

My account is setup with 2SV authenication & my mobile has died!!  How can I get the QR code up again to access my account?

Any help appreciated.

**Comment by markogrady** [comment]
Contact support it took me about a week to get mine removed to be able to
add it again.

**Comment by adamdavi3s** [comment]
I think you'd have to ask HMRC to remove it?

**Comment by AndyYouens** [comment]
thanks for the replies @markogrady & @adamdavi3s 

More delays!!

**Comment by mtd-api-team** [comment]
HI @AndyYouens, 

As @markogrady has mentioned, please contact SDSTeam@hmrc.gov.uk as they will be able to assist you further.

Thanks, 
@mtd-api-team

**Comment by AndyYouens** [comment]
@mtd-api-team 

And we all know how long they take to reply!

I'll let my client know he cant submit his vat return until they respond.  There had to be a better way of doing this these days!
