### ISSUE TITLE
INVALID_MONETARY_AMOUNT /netVatDue

### ISSUE THREAD

**Issue by vremeni4** [hmrc/vat-api#659]
Hi,

When I submit following file 
{
  "Request": {
    "Header": {
      "Accept": "application/vnd.hmrc.1.0+json",
      "Content-Type": "application/json"
    },
    "URLRequestPath": "/organisations/vat/*******/returns",
    "Method": "POST",
    "Content": {
      "periodKey": "19C2",
      "vatDueSales": 4006.59,
      "vatDueAcquisitions": 0.0,
      "totalVatDue": 4006.59,
      "vatReclaimedCurrPeriod": 5279.39,
      "netVatDue": -1272.8,
      "totalValueSalesExVAT": 20033.0,
      "totalValuePurchasesExVAT": 26397.0,
      "totalValueGoodsSuppliedExVAT": 0.0,
      "totalAcquisitionsExVAT": 0.0,
      "finalised": true
    },
    "ServiceURL": "https://api.service.hmrc.gov.uk"
  },
  "Response": {
    "Error": {
      "code": "400",
      "name": "BadRequest",
      "description": "Bad Request"
    },
    "Content": {
      "code": "INVALID_REQUEST",
      "message": "Invalid request",
      "errors": [
        {
          "code": "INVALID_MONETARY_AMOUNT",
          "message": "amount should be a monetary value (to 2 decimal places), between 0 and 99,999,999,999.99",
          "path": "/netVatDue"
        }
      ]
    }
  }
}
I get that the netVatDue should be a positive number?!?!?!
In this case we claim the VAT back, hence minus, so not sure what is wrong here. 

Thanks. 
Kind regards,
Ivan

**Comment by GrahamHDawson** [comment]
Box 5 netVatDue                    CALCULATED difference between totalVatDue and vatReclaimedCurrPeriod (ie ABS(totalVatDue - vatReclaimedCurrPeriod) ALWAYS POSITIVE

HMRC will examine totalVatDue and vatReclaimedCurrPeriod and decide if the amount in netVatDue is a payment or a refund - but you must always send it as a positive value.

**Comment by mtd-api-team** [comment]
Hi,

We have already addressed this in issue #270 but the figure is the difference between the two values and represents either the loss _or_ the gain and will therefore never be negative. The HMRC will address which it represents when they analyse the rest of the data.

Thanks.

**Comment by vremeni4** [comment]
thanks for your quick reply.
You have to admit, this is very counterintuitive.
If it is a difference between these two numbers box 3 and 4, why then taking ABS from it, is just crazy. :-)

Anyhow I will correct this on our side. 
Thanks again.

**Comment by casesolved-co-uk** [comment]
> You have to admit, this is very counterintuitive. If it is a difference between these two numbers box 3 and 4, why then taking ABS from it, is just crazy. :-)

Agreed - I guess they will argue that "Due" should be interpreted from either end, but for the user submitting the return, due means "I need to pay it".
Just like the rest of the government, HMRC have to ensure as many people as possible are on the payroll by making everything as complex and regulated as possible. Good old socialism.
