### ISSUE TITLE
Charge Ref Number not getting from HMRC even having negative netVatDue value.

### ISSUE THREAD

**Issue by heythisiskishore** [hmrc/vat-api#660]
Hi there,

Just for further clarification on the original query.

Whilst using the Submit VAT API and the NET VAT DUE value is debit then as per the HMRC API document user must get the Charge reference number and Payment Indicator as DD.

However, when we are submitting the net vat due value as debit then we are getting blank Charge Reference Number and Payment Indicator as BANK.

Net VAT DUE as Debit: As we understand, it would be the case when we get a box 5 value if Box 4 is greater than box 3. Please clarify if we have our wires crossed on this explanation.

Any help or guidance would be much appreciated!

Regards

**Comment by mtd-api-team** [comment]
Hi @heythisiskishore 

The value to be entered in box 5 (netVatDue) is always positive (as indicated in the range). You can choose to follow the "deduct the smaller from the larger" (130-50 = 80) approach, or you can absolute the difference between box 3 and box 4 (i.e. |50-130|= 80).

This issue is discussed at:
https://github.com/hmrc/vat-api/issues/275

Hope this helps

**Comment by heythisiskishore** [comment]
Thanks for your response!

Yes, we are following same approach whilst submitting the VAT return.

Could you please elaborate the attached details mentioned on the developers hub MTD VAT Submit VAT end points regarding:

1. Payment Indicator: We are not getting this indicator even when the box 5 value is debit .
2. Charge reference number: We are not getting this reference even when the box 5 value is debit.

Note: We are getting above two number only in few chances (lets just say 3/10). 

![Submit VAT](https://user-images.githubusercontent.com/47594030/61627859-7472c680-ac9e-11e9-85b8-cb4bf0a7eb99.png)

**Comment by mtd-api-team** [comment]
Hi @heythisiskishore 

Can you confirm if this is happening in the Sandbox or in Production?

My understanding is that the response in Sandbox is randomised and shows the response variations you may see in Production.

Regards

**Comment by heythisiskishore** [comment]
Thanks for your response

This is happening in the sandbox only.

Could you please assure that we are going in correct direction as in sandbox it is not clear as you have stated in your previous email?

**Comment by mtd-api-team** [comment]
Hi @heythisiskishore 

I have doubled checked the code in the Sandbox environment and I can confirm the field `paymentIndicator` is randomised and `chargeRefNumber` will only be returned in the case of 'Direct Debit'.

Sorry for the confusion

**Comment by heythisiskishore** [comment]
Hi MTD API Team,

We need confirmation that in a Production environment we will get the Payment Indicator as DD and Charge Reference number in case the : 

1. Payment indicator: Is DD if the netVatDue value is a debit and HMRC holds a Direct Debit Instruction for the client.

2. Charge Reference Number: The charge reference number is returned, only if the netVatDue value is a debit.

What if the Net VAT due values is a debit and HMRC holds **do not** a Direct Debit Instruction for the client then what we will get in Payment Indicator?

Awaiting your response!

Thanks

**Comment by mtd-api-team** [comment]
Hi @heythisiskishore

In regards to 1 and 2 yes, I can confirm those are the case.

For your other query no paymentIndicator value will be returned if netVatDue is a debit and we do not hold a current DD instruction.

Regards
