### ISSUE TITLE
Server Error 500 When customer tries to log in before signing up to MTD

### ISSUE THREAD

**Issue by sonicmule** [hmrc/vat-api#661]
We've had a phone call from a customer's accountant who has tried to submit their first VAT return, but they are unable to proceed due to a Internal Server Error 500.

They enter their gov gateway details
Enter the security code
Grant permissions for our software to accessd their VAT
Then before the current obligations can be shown they get Internal Server Error 500.
After some retrying and the customer trying different login details, the customer finally informs our support member that they may have not signed up to MTD yet.

Is this the expected response for this scenario?
Would a retrurn code 401 Not Authorised be a better response?

The customer is going to sign up and try again next week.

**Comment by GrahamHDawson** [comment]
I guess it would be better if there was a specific 'Not Signed Up for MTD VAT' error available.

**Comment by mtd-api-team** [comment]
Hi sonicmule

Unfortunately we can only advise vendors to ensure clients are fully enrolled for mtd-vat before attempting to use the VAT API.
