### ISSUE TITLE
New obligations still not being created in production

### ISSUE THREAD

**Issue by AlexJSH** [hmrc/vat-api#663]
You might refer me back to SDSTeam - but posted this here so at minimum other developers can see there are still issues....

We still have live clients (only seen with those that have numeric period keys) that are not getting new obligations created in a timely fashion.

The document @ https://developer.service.hmrc.gov.uk/guides/vat-mtd-end-to-end-service-guide/documentation/obligations.html#receive-obligations-and-submit-a-vat-return specifically says:

"A new obligation is generated on the first day of the period, whether the previous obligation has been fulfilled or not. Software can search for previous open or fulfilled obligations within a 366 day date range but can only call the next obligation."

We regularly see clients successfully submitting a return after the period end date and there not being a new open obligation available for us to store the dates from. Eventually (up to 2 months after the period start date) the obligation appears. We have not had to contact HMRC to make them 'force' it to appear - it just appears!

**Comment by RichardTaxaddict** [comment]
Hi - HMRC are saying they are still having challenges on hybrid users

**Comment by mtd-api-team** [comment]
Hi Alex

Apologies for the issues you are experiencing. As you have guessed, we are unable to provide any further assistance with this and can only advise you to contact SDST.

In case anyone is not aware, we can only provide help with using the VAT API and cannot access any of the data being held on backend systems. 

I'll close this issue now, but please comment if you need any technical assistance with the API itself. 

Regards
