### ISSUE TITLE
API Status

### ISSUE THREAD

**Issue by AndyYouens** [hmrc/vat-api#665]
Does anyone know of where I can pick up the status of the VAT API - Currently shown as down at https://www.gov.uk/government/publications/making-tax-digital-for-vat-service-availability-and-issues/making-tax-digital-for-vat-service-availability-and-issues 

This will allow us to show the API status on our application.

Thanks for your help.

**Comment by JeeBeePee** [comment]
You can't. It has been requested a few times but we've heard nothing from HMRC so far.

We used to include a link to the service status page in our app, but that proved to be a double edged sword, as quite often there'll be a service issue but the status page will report that everything is fine.

**Comment by JeeBeePee** [comment]
Case in point - just had an email from a customer who I'd previously advised that MTD VAT would be down until 4pm. After 2 days of downtime (a business that planned that would haemorrhage customers) it's not back up on time. Service status page says everything is fine!
