### ISSUE TITLE
Automating user generation and login

### ISSUE THREAD

**Issue by jasonab** [hmrc/vat-api#669]
Has anyone managed to automate the OAuth login process, such that I can use the User API to create a new test user, then log that user in programmatically and submit a VAT return for that user?

I would like to be able to write an automated test that validates my submission API, but it appears that the OAuth screens require Javascript to get past the first button, which a test would not have without a full-blown embedded browser. Can I just take the parameters off the URL, or do I need to actually execute the Javascript?

**Comment by hmrc-api-team** [comment]
Hello, we are closing this issue due to age. If you still have any persisting issues please feel free to open a new issue.
