### ISSUE TITLE
Strange StatusCode 500 Repsonse : vat/{vrn}/liabilities NoClassDefFoundError: Could not initialize class uk.gov.hmrc.vatapi.models.FinancialDataQueryParams$

### ISSUE THREAD

**Issue by sonicmule** [hmrc/vat-api#67]
Testing out the VAT liabilities function returns a strange response.
Request URL 		https://test-api.service.hmrc.gov.uk//vat/666926395/liabilities?from=2017-02-01&to=2018-02-01

Gives the response -
StatusCode : 500
Content : html document
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Execution exception</title>
        <link rel="shortcut icon" href="data:image/png;
.
.
.
.
NoClassDefFoundError: Could not initialize class uk.gov.hmrc.vatapi.models.FinancialDataQueryParams$
</html>

I'm expecting a json response here, so no real error message can be found.

**Comment by jonathanleather** [comment]
Hi @sonicmule 
This should be fixed now.
Let us know if you have anymore issues.

Cheers
Jon
