### ISSUE TITLE
PERIOD_KEY_INVALID when submitting VAT return

### ISSUE THREAD

**Issue by dawnvf** [hmrc/vat-api#670]
I have recently had two MTD submissions fail for two different clients with the error PERIOD_KEY_INVALID period key should be a 4 character string.  I am able to view the VAT obligations successfully but not submit the VAT return.

**Comment by GrahamHDawson** [comment]
What period key value are you using when submitting the return?
The idea is you retrieve the outstanding obligation and use the period key value returned in the response to submit the return.

**Comment by dawnvf** [comment]
This was caused by a user who instead of setting himself up as an agent continually re-authorises the software with different government gateway credentials so the software tried to pick up the period key for the previous client whose credentials he had entered.  There is no outstanding problem now
