### ISSUE TITLE
Gov-Client-Browser-Plugins

### ISSUE THREAD

**Issue by AndyYouens** [hmrc/vat-api#671]
Morning all

any node.js developers out there had any luck getting correct values for the security header Gov-Client-Browser-Plugins?

TIA
Cheers
Andy

**Comment by AndyYouens** [comment]
For the record we used an Ajax call to retrieve these details.  Contact me if you need more details.

Cheers

**Comment by ys00065** [comment]
How did you get the Gov-Client-Browser-Plugins using ajax please?

**Comment by AndyYouens** [comment]
we used navigator.plugins
 
$(document).ready(function() {
      var len = navigator.plugins.length;
      // check if we have any plugins
      if (len < 1) {
        var qs = '' ;
      } else {
        var qs ="?p=";
        for (var i = 0; i < len; i++) {
          if (i == 0) {
            qs = qs + navigator.plugins[i].name;
          }else{
            qs = qs + "," + navigator.plugins[i].name;
          }
        }
      }

      $.get("ajax_headers"+qs, function(data, status){
      });
    });

hope this helps @ys00065

**Comment by ys00065** [comment]
Thank you Andy.

I know this is not the thread for 'Gov-Client-Local-IPs' but can you please let me know what did you do for this in web browser? 

Thanks

**Comment by AndyYouens** [comment]
We did not have to supply the local IPs for our connection method.  Sorry, cannot help.

**Comment by markogrady** [comment]
@ys00065 The only way you can get local IPs is to use WebRTC as far as I know. I think HMRC are being quite pragmatic about it and realise this is hard to get so may be it can't be supplied. I get the impression they are trying to gather as much data as possible to do finger printing incase there is something common and dodgy across multiple accounts for fraud that it can be identified and stopped.
