### ISSUE TITLE
Retrieve formBundle and chargeRef if there is a network failure

### ISSUE THREAD

**Issue by peterBowenCC** [hmrc/vat-api#672]
I'm not sure where this falls, so here goes:

We are concerned that there is no way to get the formBundleNumber and the chargeRefNumber if there is a data failure after the return is processed, but before we get the response.  I know that this is an edge case, but since it is a financial transaction, and the user needs a record of the submission for any correspondence, what is the process to be able to retrieve these values.  I looked and I didn't see them returned on any but the submit endpoint.

This is the data that I would like to be able to come back to retrieve for a submitted return:
```
{
  "processingDate": "2018-01-16T08:20:27.895+0000",
  "paymentIndicator": "BANK",
  "formBundleNumber": "256660290587",
  "chargeRefNumber": "aCxFaNx0FZsCvyWF"
}
```

**Comment by GrahamHDawson** [comment]
Hi Peter,
This has been raised before without a satisfactory resolution see issue #362 

We really should get those extra details back from the View VAT Return endpoint.

**Comment by hmrc-api-team** [comment]
Hello, we are closing this issue due to age. If you still have any persisting issues please feel free to open a new issue.
