### ISSUE TITLE
User names

### ISSUE THREAD

**Issue by rick1c** [hmrc/vat-api#674]
Do any of the tokens contain user information such as a user name?
I am writing a client in .NET, and have successfully called the 'obligations' end point, but all I have is an access token which can be used for requests, but have no other information about the user, so can't even display their user name when they have successfully logged in.

**Comment by kingstonrk** [comment]
No, you can't get anything like that back from HMRC.  Has the user not signed into your own application first though?

**Comment by rajitha0007** [comment]
the tokens ( access and refresh) are generated for the combination of HMRC Dev hub client ID, Secret, VRN of the firm and HMRC gateway account credentials. 
We stored the received tokens against VRN and the login user of the local system

**Comment by rick1c** [comment]
Do you store the tokens in a cookie?  Just trying to figure out how to do the AddAuthentication in my .NET Core application

**Comment by hmrc-api-team** [comment]
Hello, we are closing this issue due to age. If you still have any persisting issues please feel free to open a new issue.
