### ISSUE TITLE
How does Developer Account 2 Step Verification work?

### ISSUE THREAD

**Issue by GrahamHDawson** [hmrc/vat-api#675]
It seems 2SV is to be mandatory from 15th October - but currently there's no information on the HMRC website as to exactly how this works and what the recovery methods are (if any)

There's a closed issue that suggests this is done via a QR code - and if your mobile dies you're in trouble - see

https://github.com/hmrc/vat-api/issues/657

Yes I know this is strictly outside the scope of the Issues page but I'm unable to get a response from the SDSTeam.

**Comment by cb-rfk** [comment]
Yes, I had some of the same queries! 

Set up is quite easy - install e.g. Duo app and just follow onscreen directions.

However there don't seem to be any reset options or one-time passwords available. (These are useful if the primary account holder is out of the office and a colleague needs to log in on your behalf... )

Logged a call via the support page of the website asking for further info so I'll update this page if I hear back.

Having said that, when I got locked out after replacing my phone earlier this year, it just took a brief email conversation with the dev team to get 2FA removed so I could set it up again.  Not a viable long term solution though!

**Comment by cb-rfk** [comment]
Hi Graham,

Your point is well taken and I agree you shouldn't have to have a smart phone if you don't want one.

However, it does seem to be the way the whole authorisation market is going, as, apparently, it is too easy to intercept/spoof SMS messages.

App based authentication is now mandatory on at least 3 or 4 of the 3rd party tools we use, and we are a very small team!

Richard

**Comment by GrahamHDawson** [comment]
Well I've had to setup other people as Administrators for our applications as it seems the only 2-SV option is via Google Authenticator with a smartphone (I've been re-added as a Developer)

What will happen when **everyone** has to use 2-SV is anyone's guess.
Crazy, just crazy.

**Comment by GrahamHDawson** [comment]
Received email response from SDSTeam basically saying 2-SV is a standard process and if I want to know **exactly** how it works I should Google.

**Comment by TS-grantlebrun** [comment]
The 2SV will be based on the "Time-Based One-Time Password Algorithm" See https://tools.ietf.org/html/rfc6238

The QR code contains the per-user secret used by the algorithm (with the current time) to generate the OTP. See https://github.com/google/google-authenticator/wiki/Key-Uri-Format

There's no reason this *has* to be used on a mobile phone, I'm sure you could save the secret into a suitable desktop-based TOTP App if want to extract it from a the QR code. This isn't what HMRC have in mind I'm sure, but there's nothing technical stopping you :-)

**Comment by adamdavi3s** [comment]
I use Authy for my developer account and have done since 2FA first came online for the developer portal. They also have a desktop app 

> Thanks cb-rfk for the response.
> 
> My issue is simple - I have a **'mobile phone'** that's just a phone - it'll do texts but it's **not** a smartphone so I can't install an app or scan/recognise QR codes with it.
> Nor do I have a tablet.
> 
> I can't be the only Luddite around that doesn't have these things.
> It's crazy that they've introduced this with just a weeks notice and when we have hundreds of end-users using our MTD VAT application.
> 
> If they need 2 SV then surely it should be along the same lines end users ie a phone call back or text message.

I use Authy for my developer account and have done since 2FA first came online for the developer portal, while I do use it on a smartphone, they also have a desktop app

**Comment by paulfeakins** [comment]
I'm trying to log in here: https://developer.service.hmrc.gov.uk/developer/login/. 

I've got this stupid Google Authenticator app, but it needs a code or QR code to generate my code ... and the link above doesn't have any such thing.

I only need to log in to agree to some stupid terms update anyway. Why do they make it harder and harder? Why do they waste all our time?
