### ISSUE TITLE
UK VAT Number lookup API where's the documentation?

### ISSUE THREAD

**Issue by GrahamHDawson** [hmrc/vat-api#678]
From an SDSTeam email this morning...

The Check a UK VAT Number API is now published on the HMRC Developer Hub and available for sandbox testing. 
  
The API enables your application to: 
  
?	Check if a UK VAT number is currently valid 
?	View the name and address of the business associated with the VAT number, if the number is currently valid 
?	Get a reference number that you can use to prove you checked a UK VAT number 

I can't seem to find this new API documented anywhere (doesn't appear as one of the MTD VAT API endpoints) - so where does the documentation live?
Anyone got a link?

**Comment by GrahamHDawson** [comment]
Apparently this is Beta (unlike the MTD VAT API which is...) and so only available if you register with the SDSTeam.
Weird given that **if** it needs to be used it could be as early as 1st November.

**Comment by aarshaw** [comment]
> Any idea if you can use it in reverse and present a company number and get the VAT number returned back?

This would be amazing

**Comment by Thomas-Schubert** [comment]
Does anybody have an update or URL regarding an API to check the validity of UK VAT numbers after December 2020?

**Comment by cb-rfk** [comment]
We had the following email yesterday:

Dear Developer, 

On 1st December 2020 the Check a UK VAT Number API will be released into the live Production environment. 

We have decided to release the API ahead of the scheduled EU Transition of 31st December, as this will allow new users time to consume the API and many of you have expressed an interest in using the functionality as soon as possible.

For this service you can use either the user interface or the API look-up functionality. 

Once live on 1st December, you must still subscribe to the API and your Production Credentials request will be forwarded to SDST for us to approve. 

Please be aware that our standard SLA (Service Level Agreement) of 10 days (maximum) for granting Production Credentials is applied to all APIs. However, the release will be given Priority Status and as such approvals will be actioned as a priority to support all those who apply.

In the meantime if you are interested in testing this API in Sandbox please contact SDST. 


Guess you just need to email them at: SDSTeam@hmrc.gov.uk

**Comment by adrianlawrence** [comment]
Oh great 1st December release then up to a 10 day wait (working days presumably) for approval and only then can we start testing ahead of a 1st January go live, not to mention Xmas shut down / holiday in between.  Not the best planning or preparation and as the Brexit negogiations are still ongoing can still change at any time..

**Comment by isham-iqbal** [comment]
Hi is this API production ready yet? 

> We had the following email yesterday:
> 
> Dear Developer,
> 
> On 1st December 2020 the Check a UK VAT Number API will be released into the live Production environment.
> 
> We have decided to release the API ahead of the scheduled EU Transition of 31st December, as this will allow new users time to consume the API and many of you have expressed an interest in using the functionality as soon as possible.
> 
> For this service you can use either the user interface or the API look-up functionality.
> 
> Once live on 1st December, you must still subscribe to the API and your Production Credentials request will be forwarded to SDST for us to approve.
> 
> Please be aware that our standard SLA (Service Level Agreement) of 10 days (maximum) for granting Production Credentials is applied to all APIs. However, the release will be given Priority Status and as such approvals will be actioned as a priority to support all those who apply.
> 
> In the meantime if you are interested in testing this API in Sandbox please contact SDST.
> 
> Guess you just need to email them at: [SDSTeam@hmrc.gov.uk](mailto:SDSTeam@hmrc.gov.uk)

**Comment by hmrc-api-team** [comment]
Hi @isham-iqbal,

The team which looks after the [VAT (MTD) API](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0) is not the team which looks after the [Check a UK VAT number API](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-registered-companies-api/1.0). Since they do not have a Support section in their documentation, I recommend emailing SDSTeam@hmrc.gov.uk with any support queries you have.

Kind regards
