### ISSUE TITLE
MTD VAT beta/ pilot questions. 

### ISSUE THREAD

**Issue by tim-xero** [hmrc/vat-api#68]
If a business qualifies for the MTD VAT beta / pilot and they want to opt out of MTD VAT during the pilot phase, what do they do? 

If a business opts out of the MTD VAT Pilot, is the MTD VAT access/refresh token 'dropped' preventing them from attempting use MTD VAT? What would they experience? 

During MTD Pilot if someone attempts to submit VAT return(s) via MTD and the portal (or software via the existing gateway) , what will they experience? Will the systems prevent them doing the same thing by MTD and existing channels? 

If someone signs up for pilot, but they do not qualify at that time they sign up, what will they experience? 

When will there be automated systems/UI  to support people signing up to MTD 
I see on the roadmap the self assessment UI to enable a new business to register and signup for MTD has been pushed out from March, but do not see anything for VAT?  Am I missing something? 

Thank you!

**Comment by scottylace** [comment]
Thank you for your question, unfortunately we cannot answer this question as it relates to the wider programme. This channel is only of specific questions relating to the MTD Self Assessment and VAT APIs.

Could you please send your question to this email address SDSTeam@hmrc.gsi.gov.uk and your question will be dealt with.

Thanks and sorry for the inconvenience

**Comment by tim-xero** [comment]
OK, thanks for the feedback. will raise with SDSTeam. 
I am surprised though, because I'd think some of the questions at least would directly impact/relate to experiences of people using MTD API's.
