### ISSUE TITLE
INVALID-DATE-TO

### ISSUE THREAD

**Issue by daveincov** [hmrc/vat-api#681]
# Support request

Hi I’ve had a client ring this morning trying to file there VAT return for the quarter up to September but get the following message “INVALID_DATE_TO” when trying to retrieve the VAT obligation. I cannot see anything wrong and the date is formatted correctly 2019-09-30, other clients have had no problems up to now and not sure what the problem is?
Can you help as this requires urgent attention?

**Comment by mtd-api-team** [comment]
@daveincov you will only get that error message in the following two cases:
- the 'to' date has been supplied but it is in an invalid format
- a valid 'from' date has been supplied but the 'to' date has not

The format of the date above is correct, so can you confirm that both dates are supplied?

**Comment by daveincov** [comment]
Thanks for the prompt reply, both dates supplied, and as I say has worked fine on previous returns. The from date was 30/06/2019 formatted to 2019-06-30.

**Comment by mtd-api-team** [comment]
I think I can see your requests in the logs, can you check that the url is encoded correctly?

It looks like for some requests the ampersands are appearing like this :point_right: `from=2019-06-30&amp;to=2019-09-30&amp;status=O`

**Comment by daveincov** [comment]
When gettting the VAT obligation the ampersands are encoded as &amp; in the URL, are you saying it needs to change to not be encoded? IE from=2019-06-30&to=2091-09-30&status=O Confusing as its been this way for just under a year and worked.

**Comment by daveincov** [comment]
Further testing in the sandbox reveals the problem relates only with the ampersands for the to date, &status=O and &amp;status=O both work.
I need to know whether or not I should be updating our software from &amp; to just & as right now our clients will not be able to submit a return and why this has changed within the last two weeks.

**Comment by mtd-api-team** [comment]
Yes. You should always be using a plain `&` as the query parameter separator when you make an API call.

Some of the API platform infrastructure is in the process of changing, with some traffic load balanced, which may explain intermittent failures.
