### ISSUE TITLE
2 issues with viewing submitted returns

### ISSUE THREAD

**Issue by kolonuk** [hmrc/vat-api#682]
# Bug report

- [ ] Documentation
- [X] API 

**Describe the bug**
2 issues in one:
* Requesting to view the data from periods that haven't a return submitted sends blank 404 response.
* Every 2nd request to view a return submission (regardless whether it's been submitted or not) returns 400 html response:

```
<HTML>

<HEAD>
	<TITLE>Bad Request</TITLE>
</HEAD>

<BODY>
	<H1>Bad Request</H1>
	Your browser sent a request that this server could not understand.<P>
		Reference&#32;&#35;7&#46;ac8e7b5c&#46;1572436986&#46;0
</BODY>

</HTML>
```

(This is in the production environment, I haven't checked the test environment)

**To Reproduce**
Get VAT period key from: `https://{{url}}/organisations/vat/{{vrn}}/obligations?from=2019-01-01&to=2019-12-31`
View VAT return: `https://{{url}}/organisations/vat/{{vrn}}/returns/{{periodkey}}`

**Expected behavior**
Either:
* Submission values as per API documentation
* 404 NOT_FOUND error response (or something else suitable) when no return has been submitted yet

**Screenshots / Requests / Responses**
n/a

**Additional context**
n/a

**Comment by mtd-api-team** [comment]
Hi @kolonuk :wave: 

I'm just trying to pick apart some of the information here.  Are you requesting submission data for periods that haven't been submitted against?  In this case, there will be no data on record in HMRC so the response is a correct one.

You are correct in that the 404 in this case would be better with a body and the `NOT_FOUND` error code.  This is a known behaviour, but as the API is live some vendors considered changing it a breaking change, meaning we can't change it without effecting working applications.

The HTML response you are getting is an interesting one.  This is not something that our API would ever return - it is a response from a proxy sitting in front of the API platform.  At the moment I can only suggest sanitising the second request before you send it down and trying again.

**Comment by mtd-api-team** [comment]
We are going to close this issue, hoping that you managed to resolve your query.  If you need further support feel free to reopen this issue.
