### ISSUE TITLE
Can I Submit all the VAT 9 Boxes data as zero

### ISSUE THREAD

**Issue by heythisiskishore** [hmrc/vat-api#683]
Dear Team,

Can I Submit all the VAT 9 Boxes data as zero in the VAT Returns.

**Comment by GrahamHDawson** [comment]
Works in the sandbox - so **should** be OK in production (although none of **our** users have submitted such a return)

**Comment by mtd-api-team** [comment]
Hi @heythisiskishore,

>although none of our users have submitted such a return

Just to confirm, the VAT API will accept 0 values for all fields, but it is an edge case.
