### ISSUE TITLE
Boxes 6 to 9 - Negative Values

### ISSUE THREAD

**Issue by LukeHirst** [hmrc/vat-api#685]
I have a question regarding negative values for boxes 6 to 9.

According to HMRC these values need to be rounded down to the nearest pound. 

Therefore: 

50.66 = 50 or 50.00

I am not sure whether this is valid but if box 6 is negative which of the circumstances below is correct?

-50.66 = -50 or -50.00 

Or: 

-50.66 = -51 or -51.00

**Comment by mtd-api-team** [comment]
Hi @LukeHirst,

We'll check with HMRC policy about that for you.  We will have an answer for you shortly.

**Comment by LukeHirst** [comment]
Hello @mtd-api-team 

Has there been any movement on this?

**Comment by mtd-api-team** [comment]
Hello, @LukeHirst, 
We are still waiting on the official response. We will let you know as soon as we have an answer. Thanks for your patience

**Comment by LukeHirst** [comment]
I am just checking to see if this query has been answered yet?

**Comment by mtd-api-team** [comment]
Hello @LukeHirst, 

Sorry for the delay. Below is the response we received:

Re #685 (rounding of negative values) :  
The figures entered in Boxes 6 – 9 are whole pounds only, i.e. no pence values included
Figures are rounded down even in a negative value (credit note), e.g. if the value was £10000. 25 or £10000.99 the value to be input would be £10000.

Hope this is helpful and thank you for your patience.

**Comment by LukeHirst** [comment]
Thanks, I take from this answer that if any value were to be negative than it will round back to 0 (e.g. -100.19 would be -100.00)
