### ISSUE TITLE
Issue connecting to api.service.hmrc.gov.uk

### ISSUE THREAD

**Issue by Hollister** [hmrc/vat-api#687]
We have occasional problems in production, across different customers and different environments where we are unable to connect to the HMRC api.
 
"A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because because connected host has failed to respond XXX.XXX.XXX.XXX:443"

I suspect this is because of something to do with load balancing/DDoS protection HMRC is using which causes the IP address resolved for the host to be incorrect and out of date. It tends to fix itself eventually, but it is not a very good experience for customers.

My question to other developers is if anyone else has had similar issues when deployed in production, and any tips or advice in resolving it.

**Comment by GrahamHDawson** [comment]
**Maybe** this is similar to the closed issue 569 which describes the throttling applied to MTD VAT client applications?
Or it could be simply connected to the fact 7th November was a cut-off date for some submissions and therefore the server load was exceptionally high?

**Comment by AndyYouens** [comment]
or maybe the changes made by HMRC to the OAUTH2 in production, but not in the sandbox??

**Comment by AndyYouens** [comment]
https://github.com/hmrc/vat-api/issues/680 ??

**Comment by mtd-api-team** [comment]
Hi @Hollister 

Unfortunately this is an issue we are not able to provide support for. Please contact SDST for support on this SDSTeam@hmrc.gov.uk 

I can say that we haven't experienced this issue in the Sandbox environment, but we are unable to test or replicate this in Production.

Regards

**Comment by hmrc-api-team** [comment]
Hello, we are closing this issue due to age. If you still have any persisting issues please feel free to open a new issue.
