### ISSUE TITLE
False Open Obligations 'Appearing' on Live Server

### ISSUE THREAD

**Issue by AlexJSH** [hmrc/vat-api#688]
Reporting a live issue so all can see and not waste time - if anyone hears when a solution is applied maybe they could reply so we can all see? I'm assuming the solution is HMRC need to flush these false obligations out again...

This afternoon we have multiple clients reporting they cannot submit returns and our software says that they can't update the current period as HMRC are expecting the 31/04/2019 period to be submitted.

Looking at the full list of obligations on the live server we can see that sometime recently an open obligation has been added for April 2019, and in the case we have fully analysed, for May 2019 also.

Might be something to do with swap over from numeric to alpha keys as you can see in the following listing that numeric keys were successfully used up to, and including, the march return and then alpha keys were successfully used for April through to September submissions.

Start: 01/01/2019
End: 31/01/2019
Due: 07/03/2019
Status: F
Period Key: 0119
Received: 14/02/2019
 
Start: 01/02/2019
End: 28/02/2019
Due: 07/04/2019
Status: F
Period Key: 0219
Received: 18/03/2019
 
Start: 01/03/2019
End: 31/03/2019
Due: 07/05/2019
Status: F
Period Key: 0319
Received: 16/04/2019
 
Start: 01/04/2019
End: 30/04/2019
Due: 07/06/2019
Status: O
Period Key: 0419
Received: 00:00:00
 
Start: 01/04/2019
End: 30/04/2019
Due: 07/06/2019
Status: F
Period Key: 19AD
Received: 15/05/2019
 
Start: 01/05/2019
End: 31/05/2019
Due: 07/07/2019
Status: O
Period Key: 0519
Received: 00:00:00
 
Start: 01/05/2019
End: 31/05/2019
Due: 07/07/2019
Status: F
Period Key: 19AE
Received: 12/06/2019
 
Start: 01/06/2019
End: 30/06/2019
Due: 07/08/2019
Status: F
Period Key: 19AF
Received: 16/07/2019
 
Start: 01/07/2019
End: 31/07/2019
Due: 07/09/2019
Status: F
Period Key: 19AG
Received: 15/08/2019
 
Start: 01/08/2019
End: 31/08/2019
Due: 07/10/2019
Status: F
Period Key: 19AH
Received: 20/09/2019
 
Start: 01/09/2019
End: 30/09/2019
Due: 07/11/2019
Status: F
Period Key: 19AI
Received: 05/10/2019
 
Start: 01/10/2019
End: 31/10/2019
Due: 07/12/2019
Status: O
Period Key: 19AJ
Received: 00:00:00
 
Start: 01/11/2019
End: 30/11/2019
Due: 07/01/2020
Status: O
Period Key: 19AK
Received: 00:00:00

If, like us, you are searching for the earliest open obligation as the next to be submitted (as per HMRC Documentation) then you will be a bit stuck with these clients for the moment....

VAT help desk are finally not saying "it's your software" and have escalated the matter. I have emailed SDSTeam to request it goes up on the MTD status page also.

Thanks

Alex

**Comment by AlexJSH** [comment]
@mtd-api-team can you mark this as live issue please?

**Comment by JeeBeePee** [comment]
Also got spurious obligations appearing in production.

**Comment by AlexJSH** [comment]
@narendravijayarao why is this not a live issue? (or are you not allowed to mark it yet?)

**Comment by AlexJSH** [comment]
We have more than 20 clients reporting this error in the last 24 hours. Thanks @JeeBeePee for also confirming sighting of this error.

Slightly easier format to see the issue:

14 Obligations Found

Start		End		        Due		        Status	Key	        Received
~~~		~~~		~~~		~~~~	~~~	~~~~~~~
01/01/2019	31/01/2019	07/03/2019	F	0119	21/02/2019
01/02/2019	28/02/2019	07/04/2019	F	0219	12/03/2019
01/03/2019	31/03/2019	07/05/2019	F	19AC	06/05/2019
01/03/2019	31/03/2019	07/05/2019	O	0319	00:00:00
01/04/2019	30/04/2019	07/06/2019	F	19AD	09/05/2019
01/04/2019	30/04/2019	07/06/2019	O	0419	00:00:00
01/05/2019	31/05/2019	07/07/2019	F	19AE	17/06/2019
01/05/2019	31/05/2019	07/07/2019	O	0519	00:00:00
01/06/2019	30/06/2019	07/08/2019	F	19AF	17/07/2019
01/07/2019	31/07/2019	07/09/2019	F	19AG	15/08/2019
01/08/2019	31/08/2019	07/10/2019	F	19AH	18/09/2019
01/09/2019	30/09/2019	07/11/2019	F	19AI	17/10/2019
01/10/2019	31/10/2019	07/12/2019	O	19AJ	00:00:00
01/11/2019	30/11/2019	07/01/2020	O	19AK	00:00:00

All clients with issue are following the same pattern but most have April 2019 as the first 'false' period generated (unlike above that starts in March). 

SDSTeam are requesting VRN's of affected clients - so feel free to send them in!

**Comment by AlexJSH** [comment]
Thank you for marking that as live @mtd-api-team

**Comment by JeeBeePee** [comment]
PR686 looks like a prime candidate.

**Comment by mtd-api-team** [comment]
Just a reminder to all that reporting of live issues relating to data need to go through SDST, as I can see you are doing.

@JeeBeePee its great that you guys can look through the codebase that you are interacting with, and we fully endorse the Coding in the Open principle that allows you to do so.  We should clarify though that the issues you have noted aren't caused PR that you pointed out.  

Any code changes we make to the VAT API now it is in live are purely to align to any changes made to HMRCs backend systems, and are thoroughly tested to ensure that there are no behavioural changes to our service.

The issues you are facing will be explained in due course, through SDST.

Thanks

**Comment by AlexJSH** [comment]
We have received notification from SDSTeam that this issue has now been resolved and we have had a few clients successfully submit this am. I don't believe a fix was applied on a per client basis so if you have any clients still with this issue then suggest you contact SDSTeam with VRN's

**Comment by mtd-api-team** [comment]
Hi all,

Hopefully, you should have all now received communications from SDST relating to this issue, but if not, it appears that this problem has been resolved. If you have any additional questions or problems on this topic feel free to re-open this thread.

- MTD team
