### ISSUE TITLE
Negative Box 5 - Undefined Payment Indicator in Production

### ISSUE THREAD

**Issue by AndyYouens** [hmrc/vat-api#690]
if the amount due to HMRC in box 5 is negative, in the sandbox,a submission will return the payment indicator as Bank, where as in production the payment indicator is not return (therefore undefined)

can you get these environments to work in the same way, to give us developers a chance??

**Comment by AndyYouens** [comment]
any update?

**Comment by hmrc-api-team** [comment]
Hello, we are closing this issue due to age. If you still have any persisting issues please feel free to open a new issue.
