### ISSUE TITLE
Duplicate period keys leading to return submission failure

### ISSUE THREAD

**Issue by JeeBeePee** [hmrc/vat-api#692]
LIVE ISSUE

Reported to SDS Team but posting here in case others have seen it in production.

Seeing responses like this from the obligations endpoint:

{  
   "obligations":[  
      {  
         "start":"2019-08-01",
         "end":"2019-10-31",
         "due":"2019-12-07",
         "status":"O",
         "periodKey":"1019"
      },
      {  
         "start":"2019-11-01",
         "end":"2020-01-31",
         "due":"2020-03-07",
         "status":"O",
         "periodKey":"19A4"
      },
      {  
         "start":"2019-08-01",
         "end":"2019-10-31",
         "due":"2019-12-07",
         "status":"O",
         "periodKey":"19A3"
      }
   ]
}

Note that period keys 1019 and 19A3 pertain to the same period. Submission against 1019 returned invalid period key. Submission against 19A3 worked.

I notice it's the numeric period key causing the issue again. When will the problems with numeric period keys be resolved?

**Comment by AlexJSH** [comment]
I suspect 1019 is falling into the same category as the old false periods generated in #688 

We haven't seen any current duplicates (all march/April/May 2019) so far

**Comment by AlexJSH** [comment]
@JeeBeePee - #688 looks to be resolved so hopefully this issue is now resolved?

**Comment by mtd-api-team** [comment]
Hi all,

Hopefully, you should have all now received communications from SDST relating to this issue, but if not, it appears that this problem has been resolved. If you have any additional questions or problems on this topic feel free to re-open this thread.

- MTD team
