### ISSUE TITLE
Obligations endpoint returning pre-MTD obligations that can't be retrieved from the returns endpoint

### ISSUE THREAD

**Issue by JeeBeePee** [hmrc/vat-api#693]
LIVE ISSUE 

Yet another "numeric period key" issue, which has started since the weekend.  Reported to SDS Team but wanted to share with other software providers. I'll update the issue when the SDS Team replies next month.

Obligations endpoint returns a fulfilled obligation from pre-MTD times (period key 1218):

{  
   "obligations":[  
      {  
         "start":"2018-10-01",
         "end":"2018-12-31",
         "due":"2019-02-07",
         "status":"F",
         "periodKey":"1218",
         "received":"2018-12-31"
      },
      {  
         "start":"2019-07-01",
         "end":"2019-09-30",
         "due":"2019-11-07",
         "status":"F",
         "periodKey":"19C3",
         "received":"2019-10-30"
      },
      {  
         "start":"2019-04-01",
         "end":"2019-06-30",
         "due":"2019-08-07",
         "status":"F",
         "periodKey":"19C2",
         "received":"2019-07-12"
      },
      {  
         "start":"2019-01-01",
         "end":"2019-03-31",
         "due":"2019-05-07",
         "status":"F",
         "periodKey":"19C1",
         "received":"2019-03-31"
      }
   ]
}

Trying to retrieve the associated return results in a 404:

1 > GET https://api.service.hmrc.gov.uk/organisations/vat/264829***/returns/1218
1 > Accept: application/vnd.hmrc.1.0+json
1 > Authorization: Bearer deleted
1 > Content-Type: application/json
Response status code: 404

Feels like something changed at the weekend re numeric period keys. It's not the only new issue we've seen this week...

**Comment by hmrc-api-team** [comment]
Hello, we are closing this issue due to age. If you still have any persisting issues please feel free to open a new issue.
