### ISSUE TITLE
Two returns due showing

### ISSUE THREAD

**Issue by RichardTaxaddict** [hmrc/vat-api#694]
Hello

We have seen some users in the past week showing two returns due for the same period. When we check their Gateway login, it shows the same.

They can successfully file against one of them. But not the other (told incorrect Period Key).

**Comment by AlexJSH** [comment]
@RichardTaxaddict - check out #688 & #692 - something has triggered a lot of false obligations to be generated

**Comment by AlexJSH** [comment]
@RichardTaxaddict - #688 looks to have been resolved so hopefully your issue is too

**Comment by mtd-api-team** [comment]
Hi all,

Hopefully, you should have all now received communications from SDST relating to this issue, but if not, it appears that this problem has been resolved. If you have any additional questions or problems on this topic feel free to re-open this thread.

- MTD team
