### ISSUE TITLE
I have a valid token but /organisations/vat/{vrn}/obligations endpoint returns not authorised

### ISSUE THREAD

**Issue by BorisKalyaev** [hmrc/vat-api#695]
**I do a request:**
POST https://test-api.service.hmrc.gov.uk/oauth/token HTTP/1.1
Accept: application/json
Content-Type: application/x-www-form-urlencoded
Host: test-api.service.hmrc.gov.uk
Content-Length: 161
Expect: 100-continue
Connection: Keep-Alive

grant_type=refresh_token&refresh_token=f31b87fb4ba1df6adccee1c0388ebd58&client_id=CX03VfmaDf2yyB4XEfp6glwnVFwa&client_secret=*****
**Then I got a responce:**
{"access_token":"978240f0aae3ac4827bd25f9eace231f","refresh_token":"a5756d36d35685485d81ee65edf93b","expires_in":14400,"scope":"read:vat write:vat","token_type":"bearer"}

**Ok I have access token, then I do next request:**
GET https://test-api.service.hmrc.gov.uk/organisations/vat/908894181/obligations?from=2019-06-01&to=2019-06-30 HTTP/1.1
Accept: application/vnd.hmrc.1.0+json
Authorization: Bearer 978240f0aae3ac4827bd25f9eace231f
Gov-Test-Scenario: MONTHLY_OBS_06_OPEN
Host: test-api.service.hmrc.gov.uk
Connection: Keep-Alive

**Then I got a responce:**

{"code":"CLIENT_OR_AGENT_NOT_AUTHORISED","message":"The client and/or agent is not authorised."}

**Comment by hmrc-api-team** [comment]
Hello, we are closing this issue due to age. If you still have any persisting issues please feel free to open a new issue.
