### ISSUE TITLE
After acquiring a new access token, POST VatReturn, returns Unauthorized. 401. Where as not the case of View VAT Information such as obligations

### ISSUE THREAD

**Issue by divyabattoju** [hmrc/vat-api#696]
When submitting an issue please try to provide the following information:

* **I'm submitting a ...**
  - [ ] Bug - API
  - [ ] Bug - Documentation

* **What is the current behavior?**
As part of our app flow, when we acquire a new access token from HMRC and hit POST Vat return endpoint with the newly acquired access token, HMRC sends us 401. Unauthorized. Interestingly this is not the case for GET Obligations. 

* **What is the expected behaviour?**
POST-VatReturn systems should return OK  when called with a newly acquired access token.

Find answers to common questions [here](https://github.com/hmrc/vat-api/wiki/FAQ)

**Comment by mtd-api-team** [comment]
Hi,

Which environment are you seeing this issue currently i can see this is working in sandbox. It sounds like there may be an issue with the scope being used it should be `write:vat`.

**Comment by divyabattoju** [comment]
thanks!
