### ISSUE TITLE
POST VAT submission returns 500(INTERNAL_sERVER_ERROR)/ 503 ( SERVER_ERROR), however when user retries, hmrc tells DUPLICATE_SUBMISSION

### ISSUE THREAD

**Issue by divyabattoju** [hmrc/vat-api#697]
# Bug report
Fill in the sections below to submit your bug report:
- [ ] Documentation
- [x] API 

**Describe the bug**
**SCENARIO 1:**
1. HMRC returns 500(INTERNAL_SERVER_ERROR) / 503(SERVER_eRROR) when submitting VAT Return.
2. User retries submission gets DUPLICATE_SUBMISSION.
**SCENARIO 2:**
1. HMRC returns 500(INTERNAL_SERVER_ERROR) / 503(SERVER_eRROR) when submitting VAT Return.
2. User retries submission gets 500(INTERNAL_SERVER_ERROR) / 503(SERVER_eRROR) 
3. User retries get DUPLICATE_SUBMISSION
4. In this scenario, even view VAT Return endpoint throws an exception( when asked sds team, we were told, that HMRC had duplicate entries for the submission, hence view VAT Return endpoint throws an error)

**Expected behavior**
For software systems, HMRC is single source of truth. When a POST VAT Return is 200, we show success to the user. When POST VAT Return is not 200, we show the relevant error and user can retry submission.

**Additional context**
Unfortunately for the internalservererror/server error responses on POST, we do not receive X-CorrelationId header. Hence can't provide additional info.

**Comment by hmrc-api-team** [comment]
Hello, we are closing this issue due to age. If you still have any persisting issues please feel free to open a new issue.
