### ISSUE TITLE
Broken Test User link in the Sandbox logon page (=cannot create test users)

### ISSUE THREAD

**Issue by RobertMarczycki** [hmrc/vat-api#70]
Hi,

The "Don't have Test User credentials?" link on https://test-www.tax.service.gov.uk/api-test-login/sign-in points to http://localhost:9680/api-test-user so we're unable to generate test users from HRMC Sandobox UI. It used to work last week, can you please fix?

Thanks,
Robert

**Comment by jacobbrownlowhmrc** [comment]
Hi Robert

The VAT API development team do not maintain the login page, but I will contact the API Platform team.
For now you can access the correct link here https://test-www.tax.service.gov.uk/api-test-user

Jacob

**Comment by RobertMarczycki** [comment]
Thanks!

**Comment by jacobbrownlowhmrc** [comment]
This has now been fixed, although the URL it directs to is https://developer.service.hmrc.gov.uk/api-test-user. I am unfamiliar with this part of the service so perhaps this is the correct URL. If not let me know! 

Jacob

**Comment by edjannoo** [comment]
Hi Jacob, the URL it is now directing to is correct - we have been merging the Developer Sandbox into the Developer Hub so that developers only need to go to one place to view API documentation and manage both production and sandbox apps. As part of that we have deployed the page for creating test users onto the Developer Hub and updated the link to point to it.

**Comment by youriv2019** [comment]
I am trying to create a test user organisation but it is not working. I think the service is down?

Sorry, we’re experiencing technical difficulties

Please try again in a few minutes.

**Comment by jacobbrownlow** [comment]
Hi

I have just checked. The APIs appear to be working fine, but the GUI is timing out with the error `Sorry, we’re experiencing technical difficulties` for both Individuals and Organisations.

Link for reference: https://developer.service.hmrc.gov.uk/api-test-user

We'll contact the team who own this service.

Jacob

**Comment by jeremystone** [comment]
The front end team is aware of the issue and is currently investigating.

**Comment by jeremystone** [comment]
It should be working again now.
