### ISSUE TITLE
VAT Payments and Liabilities return 404 in response

### ISSUE THREAD

**Issue by Monica938** [hmrc/vat-api#701]
I have submitted my VAT return through MTD software for July to Sept Quarter on November 6th and the submission was successful. When I tried making calls to payments and liabilities on November 6th I got the response 404, because the payments was not updated. If we make calls to payments or liabilities now the response is still 404 error. It should have been updated by now right.Even the VAT liabilities API return 404 in response.
These are the different date ranges I passed to fetch payments and liabilities.
![image](https://user-images.githubusercontent.com/58852780/70805475-0199f180-1ddf-11ea-9762-bfb2c2e07b51.png)

Other than Payments & Liabilities all other APIs work perfectly fine.

**Comment by mtd-api-team** [comment]
Hi,

we are unable to assist with this issue please contact SDST by emailing SDSTeam@hmrc.gov.uk, and they should be able to see the state of your liability . 

Regards

**Comment by Monica938** [comment]
I have already posted in their support portal (Reference: QGYE-5529-XEVV) & their response was to try shortening the date ranges.Then I contacted their VAT online service Helpline but their response was to mail SDSTeam@hmrc.gov.uk with the issue I was facing but still the APIs return 404.

**Comment by hmrc-api-team** [comment]
Hello, we are closing this issue due to age. If you still have any persisting issues please feel free to open a new issue.
