### ISSUE TITLE
Why can't my output tax be greater than my input tax when I file in the UK

### ISSUE THREAD

**Issue by duoduoCain** [hmrc/vat-api#704]
Why can't my output tax be greater than my input tax when I file in the UK

**Comment by jordan-dimov** [comment]
It can. You're just not filing it right. Read the documentation carefully, particularly around Field 5 (net vat due). This should be the absolute value of total vat minus reclaimed vat. HMRC backend then figures out the right thing to do based on the other fields, even though Field 5 on its own is ambiguous. 

Doesn't make much sense to me either, to be honest, but that's how it is.

**Comment by mtd-api-team** [comment]
Hi @duoduoCain - as Jordan pointed out, the vat-api requires that you file the absolute difference between two values in the `netVatDue` field; HMRC will work out how much the filer owes/is owed based on the other fields submitted. Please see #270 for more information on this field.

**Comment by duoduoCain** [comment]
@jordan-dimov @mtd-api-team  Thanks a lot
