### ISSUE TITLE
A question about taking positive and negative numbers for Box4（vatReclaimedCurrPeriod）

### ISSUE THREAD

**Issue by duoduoCain** [hmrc/vat-api#709]
When does Box4 take a positive number and when does it take a negative number

**Comment by mtd-api-team** [comment]
Hi @duoduoCain  

https://www.gov.uk/guidance/how-to-fill-in-and-submit-your-vat-return-vat-notice-70012

If you follow the above link, section 3 details information on how to correctly fill in each box. If you have any other questions contact the software developer support team via SDSTeam@hmrc.gov.uk
