### ISSUE TITLE
Documentation on the definitive list of errors returned by MTD API - when?

### ISSUE THREAD

**Issue by RobertMarczycki** [hmrc/vat-api#71]
Hi,

We're working on showing more customer friendly messages when an error occurs. 

When (whether?) we can expect more complete information on errors returned by the API? Examples:
* /vat/{vrn}/returns lists 8 error scenarios only, it looks incomplete - e.g. one of the error we found some time ago was INVALID_MONETARY_AMOUNT not shown on the page, I guess there might be more?
* judging by other threads here there will be background services connected with the MTD API, if so - what additional errors we may expect?
* are there plans related to change error wording

We're aware the MTD service is still in Alpha stage so changes may happen - having to do deal with changes is usually easier than implementing from scratch, any  documentation improvement would be appreciated!

Thanks,
Robert

**Comment by jacobbrownlowhmrc** [comment]
Hi Robert

Apologies that the documentation isn't as good as it could be, the new team is currently looking at this and we plan to review and update all the existing API documentation.

For VAT returns it appears that the backend validation errors have been given but not our internal errors.
I can see the following possible errors in our API:

**INVALID_MONETARY_AMOUNT**
There are various rules around what each monetary item can have. I assume these follow normal VAT business rules.
netVatDue must be positive
totalValueSalesExVAT, totalValuePurchasesExVAT, totalValueGoodsSuppliedExVAT and totalAcquisitionsExVAT must be whole amounts (no decimals)

**VAT_TOTAL_VALUE**
reject VAT returns in which the totalVatDue is not equal to vatDueSales + vatDueAcquisitions

**VAT_NET_VALUE**
reject VAT returns in which the vatDueAcquisitions and netVatDue is not equal to totalVatDue - vatReclaimedCurrPeriod

There are no future error responses planned for VAT returns, so in total there should be only 11 possible errors. We may however change the wording of errors when these are reviewed by the new team.

Jacob

**Comment by RobertMarczycki** [comment]
Thanks!
