### ISSUE TITLE
Trying to test Fraud Prevention Headers

### ISSUE THREAD

**Issue by MrNicks** [hmrc/vat-api#713]
I implemented the Fraud Prevention Headers back in April 2019 and they are in production.  We have not had any problems with requests to either the test sandbox or to the live portal with our fraud prevention headers.  However, I thought I would try using the validate API to double check.

I have set the request headers as per your API documentation and have created an OAuth 2.0 Bearer Token with our software which has both scopes: _read:vat_ and _write:vat_.  On sending a request to the validate endpoint, I am receiving the following response:

Status Code: 403
Json Content: {"code": "RESOURCE_FORBIDDEN", "message": "The application is not subscribed to the API which it is attempting to invoke"}

I would appreciate your advice on what is required in order to be able to use the validation API please.

**Comment by adamdavi3s** [comment]
You need to mark it as subscribed in your developer hub. Application>[your application] manage API subscriptions

**Comment by MrNicks** [comment]
Thanks.  I've enabled that in our developer hub for the application.  I'll give it a go again.

**Comment by MrNicks** [comment]
I have enabled Test Fraud Prevention Headers in the developer hub for our application.  I am still receiving the same response despite having created a fresh OAuth 2.0 Bearer token!

**Comment by MrNicks** [comment]
I've seen the error of my ways, and I am now received a 200 OK response.

**Comment by MrNicks** [comment]
I have a missing header:
   Gov-Client-Device-ID
but our connection method is:
   WEB_APP_VIA_SERVER
So, how do we generate a suitable ID and persist it?

**Comment by adamdavi3s** [comment]
good luck is all I can say, the SDS team will insist you save a file or registry key on the local machine. However they will not fault the developer if the client deletes it.

**Comment by MrNicks** [comment]
Get a MISSING_HEADER error for this header, but we can't send an empty header otherwise we get an EMPTY_HEADER error.  Will just have to leave this and live with the MISSING_HEADER error

**Comment by adamdavi3s** [comment]
Yes if its an error rather than a warning then HMRC can refuse your clients submission and may ask you to explain why it is empty... its a bit of an insane requirement

**Comment by balexandre** [comment]
@MrNicks did you fixed? I would see the OAuth 2.0 `scope` that you are using as it now need to contain the correct scope or you will get that error...

I'm just trying to find what is the right scope in order to use the [Test Fraud Prevention Headers API](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/txm-fph-validator-api/1.0)

I've tried with `read:vat` as found in several examples, but without luck, and the `hello` as expected, won't work either

the docs mention as:

> The scope for each user-restricted endpoint is defined in the [API documentation](https://developer.service.hmrc.gov.uk/api-documentation/docs/api).

but I fail to see where they are 😢

**Comment by hmrc-api-team** [comment]
Hello, we are closing this issue due to age. If you still have any persisting issues please feel free to open a new issue.
