### ISSUE TITLE
periodKey - possible values

### ISSUE THREAD

**Issue by AndyLee-Avalara** [hmrc/vat-api#72]
On the endpoint /vat/{vrn}/returns

Could you confirm the valid values for periodKey
I can see an example of #001 
Is this mapping to months/quarters or is it simply any string that the sender chooses?

**Comment by jacobbrownlowhmrc** [comment]
Hi 
Please see these issues about the period key: #49 and #63
Jacob

**Comment by AndyLee-Avalara** [comment]
Thx @jacobbrownlowhmrc  

So can I understand periodKey is a mandatory field, but you have no criteria for what it may contain?

I saw on #63 that it can be any 4 chr alpha

Must they be kept unique at all? 

It sounds like it is for the our calling service to use how we like, is that right?

**Comment by markogrady** [comment]
You get the period key when you retrieve the obligations

**Comment by jacobbrownlowhmrc** [comment]
The period key is created by one of our backend systems. It is created when an obligation is created, therefore it is unique to the VRN and period.

The backend system has its own validation, but we only validate that it is 4 alpha-numeric characters.

**Comment by AndyLee-Avalara** [comment]
Ok thanks, I understand it now, it is a reference to the obligation..  thx
