### ISSUE TITLE
Anyone elses customers using invalid internal IP address ranges? (Fraud Prevention Headers)

### ISSUE THREAD

**Issue by adonohoe** [hmrc/vat-api#723]
We're getting errors on our FPH reports that we have no control over. 
A couple of our customers have internal IP addresses with ranges like 222.x.x.x and 100.x.x.x and HMRC are throwing it back as 
**gov-client-local-ips: error : At least one of the values in the list is not a local IP address.**

Anyone else come across this? I'm in no position to tell my customers they need to fix their IP addresses. And while using those ranges is non-conforming, it _**is**_ their local IP address.

While I'm on the subject anyone else found that the examples in the documentation for Gov-Client-User-Agent are invalid when sent to the FPH API?
Their example of "**Windows/XP (/)**" throws back "**At least one value for 'Device Model' is missing.**"

**Comment by rosco1974** [comment]
Yes, we also received the gov-client-local-ips error and we have clients on cloud servers and their IP addresses are non confirming, nothing they can do to change.  I also receive the Device Manufacturer/Model error even though we add it as (/), again we don't have this information as the desktop app is run from a cloud server.

Tested different scenarios today and only one that passed is when adding Acer/Aspire for example.

**Comment by JeeBeePee** [comment]
Haven't had that particular issue, but HMRC have complained that I don't gather available local IP addresses, despite my app being browser based and therefore not having access to them. HMRC have helpfully suggested that I simply integrate WebRTC, completely failing to realise that WebRTC makes use of a security loophole that is now being closed in most browsers.

You weren't expecting HMRC to realise that they're not always correct and amend their fraud prevention headers spec, were you?

**Comment by adonohoe** [comment]
Okay, thanks for your inputs - Nothing much I can do, so I'll just leave it as it is then. 

> You weren't expecting HMRC to realise that they're not always correct and amend their fraud prevention headers spec, were you?

We went through the same kind of pain with their payroll RTI. I guess I was hoping that they'd see sense as there are clear issues with their spec. I've sent this to their SDS Team as well and I'll post back if/when I get an answer.

**Comment by kingstonrk** [comment]
We've been going through similar issues - got dinged in the recent automated header tests for not supplying local IP addresses but the SDS Team have never replied to our requests for a reference implementation that does not invlove the hugely problematic WebRTC methods.

**Comment by GrahamHDawson** [comment]
RE Gov-Client-User-Agent after a lot of experimentation the following works...

Gov-Client-User-Agent: Windows/Microsoft%20Windows%208.1 **(%20/%20)**

In other words where you can't get Manufacturer or Model insert a percent-encoded space DON'T just leave a blank or a non-encoded space ie (/) or ( / ) won't work (%20/%20) will work.

**Comment by adonohoe** [comment]
Thanks for that Graham - great work.

**Comment by gbs-matt** [comment]
> Anyone else come across this? I'm in no position to tell my customers they need to fix their IP addresses. And while using those ranges is non-conforming, it _**is**_ their local IP address.

I contacted SDSTeam about this on the 20th Feb.  They replied 6 days later and mentioned I could fix it by filtering for private IPs.  I received an additional reply from them today in which they said the following:

> _Please review how you collect local IPs and if you establish that public IPs are included due to an unusual network setup there would be no code changes required. However, previously, we asked you to filter out public IPs. If you’ve done this, you’ll need to undo it and provide public IPs as before as it more correctly reflects the local IPs leased to a device._ 

Maybe the problem here is the definition of 'local IP'.  I assumed that 'local' meant '**assigned to the local network card**'.  Having searched the web I see that 'local IP' is just another name for 'private IP' however HMRC now don't want me to filter for private IPs.

It looks to me that the only way to give HMRC what they're asking for is to list all IPs assigned to the local network card unless they're accessible externally.  Perhaps I just need to finish my mind-reading software...

**Comment by akashdsouza** [comment]
Chrome and firefox now obfuscate host addresses obtained through WebRTC. [Related Chrome announcment](https://groups.google.com/forum/#!msg/discuss-webrtc/4Yggl6ZzqZk/nV24XkXXAQAJ)

**Comment by cb-rfk** [comment]
Hi @akashdsouza ,
Yes, been on the cards for a while and really frustrating that HMRC are insisting that we provide information that we cannot reasonably obtain, particularly as we have asked several times via email for them to provide us with some form of reference implementation to follow, which they have not done.
We are simply having to ignore this header for now despite the repeated requests to include it.... 😏

**Comment by revk** [comment]
We went through all the same hassle. Making it so "difficult" just encourages people to "fake" the data and give them what they want, which is not actually helpful for anyone. They failed to understand that WEBAPP is not appropriate for something that is web server based with no "app" at all on the client, not even javascript. I have been seriously tempted to make a variation of the VAT submission that works on a serial console in text and connect to an ASR-33, make a video, and ask them what fraud headers they would like for that!

**Comment by hmrc-api-team** [comment]
Hello, we are closing this issue due to age. If you still have any persisting issues please feel free to open a new issue.
