### ISSUE TITLE
Retrieve VAT obligations, invalid date range for 365 days date ranges on leap year (2020)

### ISSUE THREAD

**Issue by minkok3** [hmrc/vat-api#724]
- [x] API 

**Bug**
On PROD MTD API, when a year date range is sent to get the VAT obligations endpoint `Retrieve VAT obligations` e.g. `fromDate=2019-03-04&toDate=2020-03-04` (366 days). The response is `INVALID_DATE_RANGE`. Changing the from date to make 365 days works i.e. `fromDate=2019-03-04`

**To Reproduce**
Use date range `fromDate=2019-03-04&toDate=2020-03-04` on `/organisations/vat/{vrn}/obligations`

**Comment by mtd-api-team** [comment]
Hi @minkok3 

when supplying a 365 day date range what dates did you use?

Regards.

**Comment by minkok3** [comment]
Retested the 365 days, it works. Only 366 days it throws invalid date error. I am updating the issue to reflect.

**Comment by mtd-api-team** [comment]
Hi @minkok3

the dates supplied would totally to 367 days as the date range is inclusive.

Regards.

**Comment by minkok3** [comment]
Fair enough, tested and working.
