### ISSUE TITLE
VAT Deferrals and MTD VAT - will this change responses?

### ISSUE THREAD

**Issue by GrahamHDawson** [hmrc/vat-api#729]
The chancellor announce a VAT deferral to help businesses...

> For VAT, the deferral will apply from 20 March 2020 until 30 June 2020
> 
> This is an automatic offer with no applications required. Businesses will not need to make a VAT payment during this period. Taxpayers will be given until the end of the 2020 to 2021 tax year to pay any liabilities that have accumulated during the deferral period. VAT refunds and reclaims will be paid by the government as normal.

How will this affect the responses from the MTD VAT API?
For instance will Obligations and Liabilities show an amended 'Due Date' or the default?

Also will the 366 day date range when querying need change?

**Comment by mtd-api-team** [comment]
The due date is also the submission by date. The deferral only relates to payments. We don't currently envisage any changes to the API functionality or to the data returned from any requests.

**Comment by GrahamHDawson** [comment]
I can see how the due date and submission date would apply to Obligations, but I always thought the 'Due Date' returned from Liabilites **was** the payment date, and it's payments that are being deferred.

**Comment by hmrc-api-team** [comment]
Hello, we are closing this issue due to age. If you still have any persisting issues please feel free to open a new issue.
