### ISSUE TITLE
return - finalised: false

### ISSUE THREAD

**Issue by AndyLee-Avalara** [hmrc/vat-api#73]
Could I get an understanding of the use case for submitting not finalised?

How would the benefit to the user be, is it to run some sort of validation check?

**Comment by jacobbrownlowhmrc** [comment]
Hi

Having spoken to our business analyst, he informs me there is no use case for a non finalised return. It will always be finalised. It only serves as a declaration by the customer that the information supplied is true and complete.

Thanks

**Comment by AndyLee-Avalara** [comment]
Ok thx @jacobbrownlowhmrc
