### ISSUE TITLE
when i call MTD API oauth/token

### ISSUE THREAD

**Issue by duoduoCain** [hmrc/vat-api#730]
Map<String, Object> body = new HashMap<String, Object>();
		body.put("client_secret", "79f1cc61-588f-4bd3-84fb-3df87ad30541");
		body.put("client_id","kEc4JLyrZjqeHFxWvFszVQtc8wMa");
		body.put("grant_type", "refresh_token");
		body.put("refresh_token", "ffa250e75e986e6b4e1ccc98c814e66");
//		String post = HttpUtil.post(OstVatConfig.getAuthRefresh(), body);
		Map<String, String> headers = new HashMap<String, String>();
		headers.put("content-type", "application/x-www-form-urlencoded");
		HttpResponse execute = HttpRequest.post("https://test-api.service.hmrc.gov.uk/oauth/token").addHeaders(headers).execute();
		System.out.println(execute);
Response Headers: 
    null=[HTTP/1.1 400 Bad Request]
    Strict-Transport-Security=[max-age=31536000;]
    Cache-Control=[no-cache,no-store,max-age=0]
    Content-Security-Policy=[default-src 'self']
    Connection=[close]
    Content-Length=[72]
    Date=[Mon, 23 Mar 2020 12:09:57 GMT]
    Content-Type=[application/json]
Response Body: 
    {"error":"invalid_request","error_description":"grant_type is required"}

**Comment by GrahamHDawson** [comment]
Not a Java user - but the headers for getting a refreshed token is just
Accept: application/vnd.hmrc.1.0+json

So I'm guessing for you that translates to 

headers.put("Accept", "application/vnd.hmrc.1.0+json");

Also not sure body as HashMap<String, Object> is correct, maybe better just using
HashMap<String, String> (as in the headers)

**Comment by BunglowBill** [comment]
Again, not a Java user but I had the same error

I had Content Type = "application/x-www-form-urlencoded;" with a semi-colon on the end.

Fixed by removing the semi-colon.

Could point out that it was working for months up till about February.

**Comment by hmrc-api-team** [comment]
Hello, we are closing this issue due to age. If you still have any persisting issues please feel free to open a new issue.
