### ISSUE TITLE
VAT(MTD)  - Obligations issue - POSTMAN giving null response

### ISSUE THREAD

**Issue by SpineTech** [hmrc/vat-api#735]
Hello 
I am trying to integrate the HMRC VAT(MTD) API into our application.
When I make the request for getting the code and url is (organisations/vat/{vrn}/obligations)
I got some response like this in the POSTMAN.

{
	"message": "Success",
	"success": "True",
	"hmrcResponseDataModel": {
		"start": null,
		"end": null,
		"due": null,
		"status": null,
		"periodKey": null,
		"received": null
	}
}
![image](https://user-images.githubusercontent.com/62633865/77499950-93eb7000-6e79-11ea-8b7a-d97d65e4b49b.png)

please advise

**Comment by mtd-api-team** [comment]
Hi @SpineTech sorry for the delayed response.

This is not a response from the vat-api. We return:
```
{
  "obligations": [
    {
      "start": "2017-01-01",
      "end": "2017-03-31",
      "due": "2017-05-07",
      "status": "F",
      "periodKey": "18A1",
      "received": "2017-05-06"
    }
  ]
}
```
It appears there is an issue with the application you are using. 

Regards
