### ISSUE TITLE
Regards Refresh Token

### ISSUE THREAD

**Issue by heythisiskishore** [hmrc/vat-api#739]
Hi Team,

Is there any issue going with the Refresh Token.

It is throwing the message like 

The remote server returned an error: (400) Bad Request.

**Comment by mtd-api-team** [comment]
Hi 

We aren't experiencing any issues in Sandbox. If this is happening in Production, please contact Software Developers Support Team on SDSTeam@hmrc.gov.uk.

Regards

<img width="902" alt="Screenshot 2020-03-30 at 09 03 40" src="https://user-images.githubusercontent.com/49438676/77889250-7cd7c400-7265-11ea-9855-2841bde67616.png">
