### ISSUE TITLE
Could there be a userinfo orginfo endpoint

### ISSUE THREAD

**Issue by markogrady** [hmrc/vat-api#74]
Hi

Could there be a orginfo endpoint. When you call it you are able to retrieve the authorised user 
It could retrieve 
SelfAssessment UTR
CorpTax UTR
VAT Registration Number

This would allow me to store the VAT reg no in case someone keyed it incorrectly.

A lot of other api call it userinfo
http://docs.identityserver.io/en/release/endpoints/userinfo.html

**Comment by narendravijayarao** [comment]
Hi Mark,

Thank you for your question, unfortunately we cannot answer this question as it relates to the wider programme. This channel is only for specific questions relating to the MTD VAT API.

Could you please send your question to this email address SDSTeam@hmrc.gsi.gov.uk and your question will be dealt with.

Thanks and sorry for the inconvenience
Narendra
