### ISSUE TITLE
SandBox test scenario doesnt work

### ISSUE THREAD

**Issue by ornjohan** [hmrc/vat-api#749]
Im getting below error when trying whatever "Header Value (Gov-Test-Scenario)" against VAT (MTD) API.
I even tried blank and still returns below message.

{"code": "MATCHING_RESOURCE_NOT_FOUND", "message": "A resource with the name in the request can not be found in the API"}

In the string it is trying to send for example:
<"Authorization: Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxx", "Gov-Test-Scenario: QUARTERLY_NONE_MET">

**Comment by mtd-api-team** [comment]
Hi @ornjohan,

That looks like the error which the platform returns when it doesn't recognise the request url. Could you please give me some more details about the request which you are making (url, accept header etc)?

Kind regards,
MTD-API team

**Comment by ornjohan** [comment]
Thanks for quick answer :)

Im sending from Dynamics AX 2012.

Below is the webRequest in its whole:
<"Authorization: Bearer xxxxxxxxxxxxxxxxx", "Gov-Test-Scenario: QUARTERLY_NONE_MET", "Gov-Client-Connection-Method: DESKTOP_APP_VIA_SERVER", "Gov-Client-Device-ID: xxxxxxxxxxxxxxxxxxxx", "Gov-Client-User-IDs: os=xxxxxx", "Gov-Client-Timezone: UTC+00:00", "Gov-Client-Screens: width=1710&height=822&colour-depth=32", "Gov-Client-Window-Size: width=340&height=135", "Gov-Client-User-Agent: Windows/ (/)", "Gov-Vendor-Version: Microsoft-Dynamics-AX=6.3.3000.111", "Gov-Client-MAC-Addresses: 00%3A0D%3A3A%3A20%3ACA%3A31">

**Comment by ornjohan** [comment]
https://test-api.service.hmrc.gov.uk

and this URL.

**Comment by mtd-api-team** [comment]
In Sandbox the full url for the Retrieve Obligations endpoint should look like this:
'https://test-api.service.hmrc.gov.uk/organisations/vat/**{vrn}**/obligations'
 followed by any query parameters you are providing. 

From the link you've provided, it would seem like you've missed out the VRN parameter between 'vat' and obligations. Can you try adding that parameter into the request url and see if that fixes your issue?

**Comment by ornjohan** [comment]
Ok seems i came a bit further when adding that, but now i got below. Saw this on the error codes on the documentation, but everything should be setup regarding this. I have access token and all setup.
![2020-04-09 16_39_15-Window](https://user-images.githubusercontent.com/49483767/78907227-ba67f880-7a80-11ea-9173-3bb752bad357.png)

**Comment by ornjohan** [comment]
Strange, i redid the process of getting authorization code, and got a new access token again, to see if it was something with that, but still i get above error.

**Comment by mtd-api-team** [comment]
This particular error usually occurs in one of two scenarios. Firstly, you could be submitting a valid bearer token with a vrn which it is not associated with. Secondly, you could be submitting the correct vrn and bearer token for a user which is not properly enrolled in VAT. If you are confident that you are submitting the correct vrn and bearer token I would suggest checking to make sure that the user you are using is properly enroled in VAT. You should be able to do this by using the [get available services](https://developer.staging.tax.service.gov.uk/api-documentation/docs/api/service/api-platform-test-user/1.0#_get-available-services_get_accordion) endpoint and supplying your bearer token.

**Comment by ornjohan** [comment]
Now i got it to work :) Thank you very much! And Happy easter to you!

So for anyone else using AX2012 in the future:
1. In the table TaxHMRCApplication_UK, there is a fields called "TestUserVAT", where i needed to fill in the CoRegNo on the legal entity.
2. Server token that AX is asking for when trying to create new test user, is the Bearer. I tried applying the Application ID from HMRC website, but that didnt work. When debugging the "retreive VAT obligations" it is getting the valid access token as the bearer, i copied that bearer id into "Server token" window, and voila, everything worked :)

**Comment by mtd-api-team** [comment]
Glad to be of service! Happy Easter to you too!

Kind Regards,
MTD-API team
