### ISSUE TITLE
User first use flow

### ISSUE THREAD

**Issue by nnotsofun** [hmrc/vat-api#75]
Hello,

A few questions around the first use/onboarding experience from software perspective, and following on from a few earlier issues:

* Based on the excellent responses in #42 - the only way I can see a software determining whether a business/VRN is MTD enabled will be by hitting the obligation list endpoint? And then gracefully handling the yet to be determined unauthorized error? Is that correct and the expected flow?
* Does a user nominate a software for a business/VRN from the HMRC website? Based on the user auth flow and within the sandbox environment I understand this isn’t the case but would like to double confirm.
  * We’re considering the scenario where a user login is associated with multiple businesses. 
  * For example - let’s say a user owns two businesses, Bob’s Fried Chicken (BFC) and Sally’s Cafe (SC), if a user logs into their software of choice and goes through the user authorisation flow with VAT scopes for that software, then those OAuth tokens could be used to hit the VAT api endpoints for either BFC and SC? Is that right?
* Closed #23 and bringing my last question over - is there a scenario where the user will get an error during the user authorisation process given an authorize link contains all the correct query parameters? 
  * For example if a user is not associated with any business but requests read/write scopes for VAT - will that result in an error or continue on? 
  * For clarity - I’m not talking about accessing API’s but the user authorisation flow.
* In sandbox if we pass in invalid parameters for example:
https://test-api.service.hmrc.gov.uk/oauth/authorize?response_type=code&client_id=[YOUR-CLIENT-ID]&scope=[REQUESTED-SCOPE]&state=[STATE]&redirect_uri=[YOUR-REDIRECT-URI]
It gives a service error response, in production will that give an actual error page?
* Will the XML gateway throw an error if a business/VRN has already been setup for MTD?

Thanks and cheers,

Nick

**Comment by narendravijayarao** [comment]
Hi,

Thank you for your question, unfortunately we cannot answer this question as it relates to the wider programme. This channel is only for specific questions relating to the MTD VAT API.

Could you please send your question to this email address SDSTeam@hmrc.gsi.gov.uk and your question will be dealt with.

Thanks and sorry for the inconvenience
Narendra
