### ISSUE TITLE
Obligations date range question

### ISSUE THREAD

**Issue by MrSent** [hmrc/vat-api#761]
Am I the only one that finds the documentation on the HMRC website useless or particularly convoluted? All I'm looking for are well written example code. The language doesn't really matter as long as I can read it. I've created a module for an accounting package that our customers use. We're a business partner for the accounting software vendor. This means my module will be deployed to about a hundred different servers.

It's been running for a year now and I've had ups and downs with it. Most of the problems are with the access token not being valid and having to go through granting authority AGAIN. I can live with that.

Recently I've had a couple of emails about fraud prevention headers with them being incorrect but for now it is not being enforced AND they were just letting me know. It doesn't tell me which customer has incorrect anti fraud headers, so I can't find out what is going on, so basically I shall do nothing until HMRC decide to say "no more".

An issue I've got at the moment is with getting obligations. I have an obligations request object in which I put in the VRN and the date from and to. It returns an obligations response object. With regards to the dates for to and from. What is an acceptable date range? If I hard code the from date, say to the 1st April 2019, this request/response will just grow. The from and to dates are required.

**Comment by mtd-api-team** [comment]
Hi @MrSent,

Thankyou for your feedback.

The [documentation](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0#_retrieve-vat-obligations_get_accordion) states that an invalid date range is as follows: `Invalid date range, must be 366 days or less`.  

We can not, and should not, suggest how you develop against the API, so we do not provide code examples.  What we can do, is provide a uniform interface against which software applications on a variety of platforms can access the information they ask for.

For any Fraud Prevention Header related queries, please contact SDST for additional support here SDSTeam@hmrc.gov.uk

Enjoy your weekend,
 MTD API team

**Comment by MrSent** [comment]
I'm not suggesting you tell me how to develop. I'm trying to solve a
problem I've been having and all you've said it RTFM which isn't helping so
I've asked for help. Isn't this the place to come for help? From the people
who've created it? If by reading the documentation isn't helping then where
do I go from here?

**Comment by cb-rfk** [comment]
We supply our users with a pair of date dropdowns for them to select the search date range, and then validate to make sure they can't select > 365 days. 

Alternatively I think you could offer them a list of Vat reporting periods if you have those stored in your system, bearing in mind the customers can change their vat year start/end.

Regardless, they should know what date range of obligations they are interested in viewing.

Regarding the Fraud Prevention Headers, yes I agree these have not been implemented at all well, although following initial feedback we have had a constructive dialog with HMRC to address particular issues. Just keep up the emails is all I can suggest there really...

**Comment by JeeBeePee** [comment]
@MrSent I've been quite critical of the initial rollout and documentation (which is now much better), but I will defend the API team here - why on earth would someone publish sample code for a REST API? It makes no sense. At the very most, you might wish for a Postman collection.

The documentation for the obligations endpoint states that it must be 366 days or less. That's probably why you were told to "RTFM" as you put it..

If you need your hand holding to the extent that you need "well written sample code", there are myriad REST API examples on the net in any language you care to choose. Google, not the API team, is your friend here.
