### ISSUE TITLE
VAT(MTD) - liabilities & payments not giving any results

### ISSUE THREAD

**Issue by SpineTech** [hmrc/vat-api#768]
Hello
We are done with obligation and VAT submission, but we are not getting any return value for  liabilities & payments. 
Another query being when we submit VAT successfully is there any further process from our side to be done?

Please advise.
Thanks
SLal

**Comment by mtd-api-team** [comment]
Hi @SpineTech,

What response are you receiving for Liabilities and Payments might we ask?  If it is a 404 then it means that no data exists in HMRCs stores for the date range you have been providing.  

Are you testing this in the Sandbox environment or is this in Production?

In regards to the VAT Submission, there is nothing else to do other than to store the response items for your own needs if relevant.  The Obligations endpoint can be used to check if the obligation for that period has been set to fulfilled after the receipt of your submission.

Regards,

MTD API team

**Comment by SpineTech** [comment]
Hello Team,

We are testing in Sandbox environment.
Liabilities and Payments showing 404. - That's fine as per your reply. 
Just a query non of the date range shows any reply, is that normal in sandbox.

The Obligations endpoint does not update even after submission have been successfully done. It still shows unfulfilled.
Please advise.

Regards
SLal

**Comment by GrahamHDawson** [comment]
Sandbox responses are 'canned' - so the Obligations won't update even after a successful test submission.
If you want to see a response then choose one of the Obligation test scenarios that have one or more fulfilled.

**Comment by NiraliB** [comment]
Which date range should I have to pass in Liability and Payment api?

**Comment by hmrc-api-team** [comment]
Hello, we are closing this issue due to age. If you still have any persisting issues please feel free to open a new issue.
