### ISSUE TITLE
Relationship between obligation periods and MTD subscription dates ?

### ISSUE THREAD

**Issue by kmanish86** [hmrc/vat-api#77]
Lets say a user is on quarterly filing scheme with periods as follows:
- 1st Jan - 31st Mar
- 1st Apr - 30th Jun 
- 1st Jul - 30th Sep 
- 1st Oct - 31st Dec. 

What will be the obligation dates and first OPEN obligation period be for filing via MTD apis for the following MTD subscription dates.

1. 1st of April.
2. 30th of April.
3. 30th of June.

**Comment by jonathanleather** [comment]
Hi @kmanish86 

Thank you for your question, unfortunately we cannot answer this question as it relates to the wider programme. This channel is only for specific technical questions relating to the MTD VAT API.

Could you please send your question to this email address SDSTeam@hmrc.gsi.gov.uk and your question will be dealt with.

Thanks and sorry for the inconvenience
Jon

**Comment by kmanish86** [comment]
Sure. Thank you @jonathanleather
