### ISSUE TITLE
Get obligations query parameters

### ISSUE THREAD

**Issue by MrSent** [hmrc/vat-api#771]
- [x] Documentation
- [ ] API 

This page:
https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0#_retrieve-vat-obligations_get_accordion

states that all of the query parameters are optional. If they're all optional, why when they're all omitted, do you get an error saying INVALID_DATE_RANGE? If I want to retrieve by status, I leave the status field blank to return both open and fulfilled, but I then require a date range. The documentation is misleading.

**Comment by JeeBeePee** [comment]
"Mandatory unless the status is O."

**Comment by mtd-api-team** [comment]
Hi @MrSent,

Apologies for any confusion. As is stated in the field descriptions for the `from` and `to` query parameters, they are both mandatory unless a status of `O` has been provided. If you wish to retrieve both open and fulfilled obligations then the date query parameters are required.

Kind regards,
MTD-API-Team

**Comment by MrSent** [comment]
Thanks for the clarification. Personally, I would write that as:

If a status of O is provided, the from and to dates are not required. In all other circumstances, they are required.
