### ISSUE TITLE
Accepts VAT returns with negative values in boxes 6, 7, 8 & 9

### ISSUE THREAD

**Issue by istuart0** [hmrc/vat-api#781]
# Bug report

You must read the information below before you submit a bug report. 

The MTD API team cannot help if your bug report is about:

- Fraud Prevention Headers
- Issues relating to OAuth2
- Subscribing or registering to use the API Platform, MTD enrolment, de-enrolment, registration for VAT, Beta services, etc.
- Issues integrating with the API Platform (e.g. setting up an application/access)
- Code examples in a given programming language
- Business-related questions or processes pre MTD
- Scheduled maintenance windows and days
- Onboarding (e.g. registering, obtaining keys)
- Performance metrics

For any of the above, you **must** contact the Software Developer Support Team directly at SDSTeam@hmrc.gov.uk.  The SDS Team do not monitor this repository.

This repository is for bug reports relating to VAT API code in this repository only.

Fill in the sections below to submit your bug report:

- [ ] Documentation
- [ ] API 

**Describe the bug**
The API returns the normal response (I.E. receipt Id etc) when submitting a VAT return with negative values for boxes 6, 7, 8 & 9

**To Reproduce**
Submit a VAT return with negative values in boxes 6 to 9
**Expected behavior**
I expected an error return INVALID_MONETARY_AMOUNT, and an array containing the names of the 4 invalid fields

**Screenshots / Requests / Responses**
This is the JSON request:
{
   "method":"POST",
   "uri":"https://test-api.service.hmrc.gov.uk/organisations/vat/624520663/returns",
   "headers":{
      "Accept":"application/vnd.hmrc.1.0+json",
      "Content-Type":"application/json",
      "Authorization":"Bearer ++++++++++++++",
      "Gov-Client-Browser-Do-Not-Track":false,
      "Gov-Vendor-Public-IP":"216.58.204.3",
      "Gov-Client-Local-IPs":"192.168.1.1",
      "Gov-Client-Public-Port":0,
      "Gov-Vendor-Version":"VatsubWebServerion=3.01&VatsubNodeJSVersion=0.9",
      "Gov-Client-User-IDs":"VatsubUserId=istuart0%40gmail.com",
      "Gov-Client-Device-ID":"240ced3e-a5f0-4dee-90a4-2c4a0e8990a6",
      "Gov-Vendor-Forwarded":"by=216.58.204.3&for=146.200.139.250",
      "Gov-Client-Timezone":"UTC+1:00",
      "Gov-Client-Connection-Method":"WEB_APP_VIA_SERVER",
      "Gov-Vendor-License-IDs":"VatsubLicenceId=5ba93c9db0cff93f52b521d7420e43f6eda2784f",
      "Gov-Client-Public-IP":"146.200.139.250",
      "Gov-Client-Browser-Plugins":"undefinedChrome%20PDF%20Plugin,Chrome%20PDF%20Viewer,Native%20Client",
      "Gov-Client-Browser-JS-User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36",
      "Gov-Client-Multi-Factor":"type=TOTP&timestamp=2020-06-06T10:54Z&unique-reference=d420dd3094b398c8250d42315a0688c6f3e05171",
      "Gov-Client-Screens":"width=1879&height=1057&scaling-factor=24&colour-depth=24",
      "Gov-Client-Window-Size":"width=1839&height=940"
   },
   "body":{
      "periodKey":"18A1",
      "vatDueSales":-99.9,
      "vatDueAcquisitions":0,
      "totalVatDue":-99.9,
      "vatReclaimedCurrPeriod":0,
      "netVatDue":99.9,
      "totalValueSalesExVAT":-1235,
      "totalValuePurchasesExVAT":-9899,
      "totalValueGoodsSuppliedExVAT":-999,
      "totalAcquisitionsExVAT":-888999,
      "finalised":true
   },
   "json":true,
   "simple":false,
   "resolveWithFullResponse":true

**Additional context**

**Comment by GrahamHDawson** [comment]
That's as expected - see the documentation

https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0#_view-vat-return_get_accordion

entries for box 6,7,8 and 9 all have this for the validation of the value
The value must be between -9999999999999 and 9999999999999.

**Comment by hmrc-api-team** [comment]
Hi

Sorry for the delayed response. Graham is correct, this is expected.

Also we'd advise against sharing your `Authorization` token, even with Sandbox data.

Regards

**Comment by hmrc-api-team** [comment]
Hello, we are closing this issue due to age. If you still have any persisting issues please feel free to open a new issue.
