### ISSUE TITLE
VAT Return submission test endpoint returning inconsistent paymentIndicator

### ISSUE THREAD

**Issue by stuartajd** [hmrc/vat-api#783]
# Support request

You must read the information below before you submit a support request.

The MTD API team cannot help if your query is about:

- Fraud Prevention Headers
- Issues relating to OAuth2
- Subscribing or registering to use the API Platform, MTD enrolment, de-enrolment, registration for VAT, Beta services, etc
- Issues integrating with the API Platform (e.g. setting up an application/access)
- Code examples in a given programming language
- Business-related questions or processes pre MTD
- Scheduled maintenance windows and days
- Onboarding (e.g. registering)
- Performance metrics

For any of the above, you **must** contact the Software Developer Support Team directly at SDSTeam@hmrc.gov.uk.  The SDS Team do not monitor this repository.

This repository is for technical queries relating to the VAT API.  We can help with VAT-API technical queries only.

Common support questions and answers can be found on [VAT API Wiki](https://github.com/hmrc/vat-api/wiki/FAQ). You can also search for previous support questions [here](https://github.com/hmrc/vat-api/issues?utf8=%E2%9C%93&q=).

---

Hello,

I have recently been running tests on the VAT Return submission endpoint as during my sandbox testing for my application I noticed that it was returning DD instead of BANK, when the totalVatDue was less than vatReclaimedCurrPeriod - this would be a reclaim, therefore it should return BANK.

I have submitted multiple VAT Returns through Postman to simulate a submission, changing the periodKey on each submission.

Is this a bug within the API or if there is something that I have missed when running these tests. As it doesn't seem consistent at all, but may be just to simulate the different responses.

Would love to hear your thoughts on the issue!

### POST
```json
{
  "periodKey": "18D2",
  "vatDueSales": 0,
  "vatDueAcquisitions": 0,
  "totalVatDue": 0,
  "vatReclaimedCurrPeriod": 1500,
  "netVatDue": 1500,
  "totalValueSalesExVAT": 0,
  "totalValuePurchasesExVAT": 0,
  "totalValueGoodsSuppliedExVAT": 0,
  "totalAcquisitionsExVAT": 0,
  "finalised": true
}
```

### Response
```json
{
    "processingDate": "2020-06-19T19:24:14.528Z",
    "formBundleNumber": "827426582780",
    "paymentIndicator": "DD",
    "chargeRefNumber": "OT83UqRljETjgByH"
}
```

### POST

```json
{
  "periodKey": "18D6",
  "vatDueSales": 0,
  "vatDueAcquisitions": 0,
  "totalVatDue": 0,
  "vatReclaimedCurrPeriod": 1500,
  "netVatDue": 1500,
  "totalValueSalesExVAT": 0,
  "totalValuePurchasesExVAT": 0,
  "totalValueGoodsSuppliedExVAT": 0,
  "totalAcquisitionsExVAT": 0,
  "finalised": true
}
```

```json
{
    "processingDate": "2020-06-19T19:32:47.622Z",
    "formBundleNumber": "464745236267",
    "paymentIndicator": "BANK"
}
```

**Comment by hmrc-api-team** [comment]
Hi @stuartajd,

Is this an issue you're having in production, or in one of the test enviroments?

Kind regards,
MTD API team

**Comment by stuartajd** [comment]
@hmrc-api-team 

Thanks for the reply! Clears that all up, I did assume during my postman tests that it was random, but just wanted to double check!

**Comment by hmrc-api-team** [comment]
Hi @stuartajd,

Apologies for any confusion caused. The data we return in the test environments is randomised.

Kind regards,
MTD API team

(Just reposting this to remove the edit history)
