### ISSUE TITLE
Internal Server Error - Production

### ISSUE THREAD

**Issue by LukeHirst** [hmrc/vat-api#784]
# Bug report

You must read the information below before you submit a bug report. 

The MTD API team cannot help if your bug report is about:

- Fraud Prevention Headers
- Issues relating to OAuth2
- Subscribing or registering to use the API Platform, MTD enrolment, de-enrolment, registration for VAT, Beta services, etc.
- Issues integrating with the API Platform (e.g. setting up an application/access)
- Code examples in a given programming language
- Business-related questions or processes pre MTD
- Scheduled maintenance windows and days
- Onboarding (e.g. registering, obtaining keys)
- Performance metrics

For any of the above, you **must** contact the Software Developer Support Team directly at SDSTeam@hmrc.gov.uk.  The SDS Team do not monitor this repository.

This repository is for bug reports relating to VAT API code in this repository only.

Fill in the sections below to submit your bug report:

- [ ] Documentation
- [ x] API 

**Describe the bug**
Internal server error occuring when retrieving obligations from vat-api

**To Reproduce**
Send a GET request using the following url (actual VRN obfuscated):

https://api.service.hmrc.gov.uk/organisations/vat/VRN/obligations?from=2019-11-01&to=2020-10-31

**Expected behavior**
Obligations should be returned so client can submit a VAT return

**Screenshots / Requests / Responses**
The response below is received: 

{
"code":"INTERNAL_SERVER_ERROR",
"message":"An internal server error occurred"
}

**Additional context**
Retrieval of VAT obligations has been successful up until recently. Is it possible to know what this internal server error issue is to get to a quick solution?

VAT obligations endpoint works as expected within the sandbox

**Comment by hmrc-api-team** [comment]
Hi @LukeHirst,

From the look of our logs there was some temporary issue with one of the services which we retrieve our data from. This was then being surfaced up to you as an INTERNAL_SERVER_ERROR. The issue looks to have resolved itself over the last hour, so if you send the request again it should hopefully work. Please keep us updated if these issues persist.

Kind regards,
MTD API team

**Comment by LukeHirst** [comment]
This does not seem to have resolved the issue, as returns are time sensitive we need a resolution to this issue.

**Comment by hmrc-api-team** [comment]
The new failures appear to have been caused by the same underlying error as last time. I can see successful requests to this endpoint between your attempts so it doesn't appear to be an availability issue. I'm afraid you'll have to contact SDSTeam@hmrc.gov.uk as we on the API team aren't able to investigate potential data issues in the production environment.

Kind regards,
MTD API team

**Comment by LukeHirst** [comment]
Would it be possible for yourselves to ensure that we get a communication from the SDSTeam today? 

I have sent an email in tandem with setting up this github ticket, this is very time sensitive and needs a satisfactory response for the client

**Comment by MathewRimmington** [comment]
This continues to be an intermittent problem for users. Is anyone actively looking into this issue?

It is both time consuming and frustrating to explain to customers that even though our software is presenting the error, it is a HMRC fault causing it.

This has been outstanding since June. Six months and beyond is not an acceptable timeframe to fix such a serious fault.

**Comment by MathewRimmington** [comment]
HMRC have advised that the specific issue I reported last week is happening when customers switch from a Partnership to a Limited company. Hopefully the API can be updated soon to either fix problem or provide a meaningful error message.
