### ISSUE TITLE
Obligations periodKey return on Test API

### ISSUE THREAD

**Issue by OrenIn** [hmrc/vat-api#789]
When using the test environment, we are getting the obligation with the periodKey field at the start of the string

{"obligations":[{"periodKey":"XXXX","start":"2017-01-01","end":"2017-03-31","due":"2017-05-07","status":"F","received":"2017-05-06"},

We used to get it as the last field or one before the last earlier

{"obligations":[{"start":"2017-01-01","end":"2017-03-31","due":"2017-05-07","status":"F","periodKey":"18A1","received":"2017-05-06"},{"start":"2017-04-01","end":"2017-06-30","due":"2017-08-07","status":"O","periodKey":"XXXX"}]}

Has the format changed in the obligation response ?

**Comment by hmrc-api-team** [comment]
Hi @OrenIn,

Aesthetically the response has slightly reordered yes, although JSON as standard is fundamentally undordered and we can't guarantee the order it will render in after it leaves our platform.

As such we will always suggest that you build to our responses disregarding the order that it may come back in within the test environment or in the examples in the documentation.

Thanks,

@hmrc-api-team

**Comment by OrenIn** [comment]
Hi

Would it be the same in production as we are about to submit to the live system ? or is the format fixed in live production ?

**Comment by hmrc-api-team** [comment]
Hi @OrenIn,

Our advice would be that regardless of environment, you should not take into account the expected order of responses.

As it stands the same response should be returned from Prod as from the test environment, but in an attempt to be absolutely clear, we can never guarantee the order that you will receive the response as JSON is by definition an unordered set of keys and pairs.

Thanks,

@hmrc-api-team

**Comment by hmrc-api-team** [comment]
Hello, we are closing this issue due to age. If you still have any persisting issues please feel free to open a new issue.
