### ISSUE TITLE
How to authenticate use while submitting Vat from VB6 application (desktop)

### ISSUE THREAD

**Issue by thakurankesh** [hmrc/vat-api#79]
I need to call VAT submit api from VB6 application. But while authenticating it ask for redirect_url. Can't I call it directly without using redirect_url as my application is desktop application?

**Comment by scottylace** [comment]
Thank you for your question, unfortunately we cannot answer this question as it relates to the wider HMRC API Plaform and is not exclusive to the MTD Self Assessment and VAT APIs.

Could you please send your question to this email address SDSTeam@hmrc.gsi.gov.uk and your question will be dealt with.

Thanks and sorry for the inconvenience.

**Comment by philipburrell** [comment]
Have you found a solution for this?

**Comment by thakurankesh** [comment]
No, I emailed team but did not get any answer yet

**Comment by markogrady** [comment]
You would have to have an interim web solution. Your product would call it
which auths it . If you need to discuss it send me your contact details.

**Comment by thakurankesh** [comment]
Thanks markogrady , interim web solution can be an option but I think this will cause extra work around.

yes, i want to discuss it with you, my contact details - thakurankesh@gmail.com

**Comment by CoppensBart** [comment]
You need to set the redirect url to either:
"urn:ietf:wg:oauth:2.0:oob" or "urn:ietf:wg:oauth:2.0:oob:auto"
As mentioned here:
https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints

**Comment by philipburrell** [comment]
Tried that a get an html page with <title>Sorry, we are experiencing technical difficulties - 500</title>
c# code (Using RestSharp)
    string url = "https://test-api.service.hmrc.gov.uk";
    string client_id = "_xxxxxxxxxxxxxxxxxxxxxxxxxx";
    string redirectUri = "urn:ietf:wg:oauth:2.0:oob";
    var restclient = new RestClient(url);
    RestRequest request = new RestRequest("oauth/authorize") { Method = Method.GET };
    request.AddParameter("response_type", "code");
    request.AddParameter("client_id", client_id);
    request.AddParameter("scope", "hello");
    request.AddParameter("redirect_uri", redirectUri);

**Comment by sonicmule** [comment]
Authorisation is down at the moment - Was working earlier today

**Comment by thakurankesh** [comment]
Thanks, I tired using urn:ietf:wg:oauth:2.0:oob:auto but it saying redirect_url invalid.

**Comment by CoppensBart** [comment]
@thakurankesh ,
you also need to add that redirect url to the "Redirect URI" allowed on your application details page on:
https://developer.service.hmrc.gov.uk/developer/applications

**Comment by thakurankesh** [comment]
Thanks @CoppensBart . Just to confirm one thing, will it ask for login after API call is complete?
If thats true, how can we submit Vat without asking for login details from our VB6 app

**Comment by mathiasbanda** [comment]
@thakurankesh 
Follow @CoppensBart advice. Think of the refreshtoken as your as your apps login details

**Comment by andyjmcfarlane** [comment]
Does anybody have sample code for the calling of the VAT submit API in VB6?

**Comment by sdabyrne** [comment]
This is probably very late as I note your last post was 12 June and you have probably worked out a solution. However, I like you, am using VB6 and have developed routines for the new HMRC API using Chilkat Software ActiveX components. Not too expensive and very good.

**Comment by Chris-Manchester** [comment]
I am looking at developing VB6 code for HMRC API. I have done some web interaction programs and also routines for the Government Gateway for VAT and Payroll.  It would be nice to talk to other developers to prevent us all having to reinvent the wheel. I can see there being a lot of additional work being neeed in the future if HMRC has their way.   chris@abc6.co.uk

**Comment by aaronmowla** [comment]
Hi All, can anyone suggest a contact for VB6 development HMRC VAT at Chilkat? We are having a lot of issues with obtaining structured sensible responses from HMRC (like so many of the contributors!). Thanks Aaron

**Comment by mathiasbanda** [comment]
Have you had a look at this: https://www.chilkatsoft.com/refdoc/vbnetOAuth2Ref.html

**Comment by sdabyrne** [comment]
The contact at Chilkat Software is Matt Fausey   support@chilkatsoft.com <mailto:support@chilkatsoft.com>   he is extremely helpful.

 

Peter Byrne 

 

United Kingdom

 

Telephone: 01489 894 180    l    Mobile: 07860 487 956    l    EMail:  <mailto:pbyrne@sdalogic.com> pbyrne@sdalogic.com

 

This message and any attachments are private and confidential. If you have received this message in error, please remove it from your system. The contents of this email and any attached material have been scanned for known viruses prior to transmission. However, it is the responsibility of the recipient(s) to ensure that it is virus free and no responsibility is accepted by SDA Logic Limited for any loss or damage in any way arising from its use.

**Comment by aaronmowla** [comment]
Hi Peter


Superb! Thanks so much!!! If I find any new information I'll post it on the group.


Thanks again


Aaron

________________________________
