### ISSUE TITLE
Received an unexpected EOF or 0 bytes from the transport stream.

### ISSUE THREAD

**Issue by GaryThePlasterer** [hmrc/vat-api#790]
Hi,
Everything was working for our clients in March when they submitted their March VAT. At some point from then to now we are not getting the following message:

**Received an unexpected EOF or 0 bytes from the transport stream.**

Even with Hello World API we get the message. Can someone help as to what the issue could be?
Sample of code.
static void TestHttpGET(Args _args)
{
    str destinationUrl = 'https://test-api.service.hmrc.gov.uk/hello/world', strRequest, strResponse;

    System.Net.HttpWebRequest       httpRequest = null;
    System.Net.HttpWebResponse      httpResponse = null;

    System.Net.WebHeaderCollection  headerCollection;

    CLRObject                       clrObj;
    System.IO.Stream                requestStream, responseStream;
    System.IO.StreamReader          streamReader = null;
    System.Exception                ex;
    int                             a;

    try
    {
        new InteropPermission(InteropKind::ClrInterop).assert();

        clrObj = System.Net.WebRequest::Create(destinationUrl);

        httpRequest = clrObj;

        httpRequest.set_ContentType(@"application/json");
        httpRequest.set_Accept("application/vnd.hmrc.1.0+json");

        httpRequest.set_Method("GET");

        //By pass proxy
        httpRequest.set_Proxy(System.Net.GlobalProxySelection::GetEmptyWebProxy());

        //bp deviation documented
        httpResponse = httpRequest.GetResponse();

        a = httpResponse.get_StatusCode();

        responseStream = httpResponse.GetResponseStream();
        streamReader = new System.IO.StreamReader(responseStream);

        strResponse = streamReader.ReadToEnd();

        info(strfmt("Response:  %1",strResponse));
        info(strfmt("Code:  %1",int2str(a)));

        codeAccessPermission::revertAssert();

        httpResponse.Close();
        responseStream.Close();
        streamReader.Close();
    }
    catch
    {
        //bp deviation documented
        ex = CLRInterop::getLastException().GetBaseException();
        error(ex.get_Message());
    }
    codeAccessPermission::revertAssert();
}

**Comment by MatthewJWalters** [comment]
Have you checked that you are using TLS1.2 or higher. I remeber earleir versions being unsupported but thought that was earlier than March.

**Comment by GaryThePlasterer** [comment]
Hi Mathew, 
I'm having the tech team check the server and .NET version. It could be the server has an old .NET . It's an old third party system with MTD built on top and Tls1.2 is not an option. 

![a](https://user-images.githubusercontent.com/68425173/87798241-a7b14c80-c843-11ea-87e2-38bda92ce385.jpg)

Maybe the server has a default setting and all system can use it.

**Comment by hmrc-api-team** [comment]
Hello, we are closing this issue due to age. If you still have any persisting issues please feel free to open a new issue.
