### ISSUE TITLE
New status for open return during current period

### ISSUE THREAD

**Issue by JeeBeePee** [hmrc/vat-api#796]
# Feature request
**Is your feature request related to a problem? Please describe.**
Submissions for open returns are rejected until the period end date has passed. A good user experience necessitates that a user be prevented from attempting to submit a return that will definitely fail, due to the period end date being in the future. This requires business logic in the application to determine whether the period end date is in the future or not.

**Describe the solution you'd like**
A new status for VAT return objects that differentiates between an open VAT return that can be submitted and one that can't, for example O=open and can be submitted, C=current period therefore cannot be submitted. This would be a non-breaking change.

**Describe alternatives you've considered**
A "submittable?" flag on the VAT return object returned by the returns endpoint. Potentially a breaking change for implementations that error on unexpected JSON nodes.

**Additional context**
Looking to refactor now that the API is stable and would like to reduce the amount of logic in our application.

**Comment by GrahamHDawson** [comment]
I don't think that's a worthwhile change, end-users are accustomed to waiting until after the end of a VAT period before they do a return, and if they attempt a return too early then you get the 403 TAX_PERIOD_NOT_ENDED error which is easy to trap and display to the user.
Also the date a return is 'submittable' can change to the the status of the business.

**Comment by JeeBeePee** [comment]
They're not though. The reason that logic has been added into our application to prevent users submitting returns during the current period is because there were numerous customer complaints either that they couldn't file a return and didn't understand why, even given an error message, or that they'd spent some time following the workflow to submit a return (for bridging software, this can involve a point-and-click marathon) only for it to fail.

Given that the error is "TAX_PERIOD_NOT_ENDED", I'd be interested to hear those other scenarios that can change the date from which a return can be submitted/

**Comment by GrahamHDawson** [comment]
Correct, when the business folds or de-registers for MTD VAT due to changes of status to for example charity or not for profit organisation.

**Comment by hmrc-api-team** [comment]
Hello, we are closing this issue due to age. If you still have any persisting issues please feel free to open a new issue.
