### ISSUE TITLE
Live API now sending blank instead of 0 amount on payments

### ISSUE THREAD

**Issue by adamdavi3s** [hmrc/vat-api#797]
Hi All,

We have had a spate of customers with an error in our application, its a simple one whereby we're expecting an number to come back in the get payments call, however it is returning a blank amount rather than a zero amount.
it is an easy enough fix, but this behaviour doesn't match the endpoint specification:

amount
number
required  

The payment value. 
Defines a monetary value (to 2 decimal places), between -9,999,999,999,999.99 and 9,999,999,999,999.99

**Comment by MarkAKelly** [comment]
Hi @adamdavi3s,

Just to clarify, are we saying that the amount field is not being returned at all, i.e

```
{
  "payments": [{
    "received": "2018-04-06"
  }]
}
```
or that the JSON is malformed, i.e
```
{
  "payments": [{
    "amount": ,
    "received": "2018-04-06"
  }]
}
```
Do you know when this behaviour started to occur?  We will look into this right away.

**Comment by adamdavi3s** [comment]
Hi @MarkAKelly ,

I'm not able to get the exact response body as I can't observe the behaviour on any of my systems, it is just a number of customers now reporting it. I will see what I can get out of them but it may not be quick! Appears to be a very recent (last week) issue

**Comment by adamdavi3s** [comment]
@MarkAKelly  Apparently the first reported instance was last Tuesday

**Comment by hmrc-api-team** [comment]
Hello, we are closing this issue due to age. If you still have any persisting issues please feel free to open a new issue.
