### ISSUE TITLE
Fraud Prevention Headers :  Header required (found in 100% of your requests)

### ISSUE THREAD

**Issue by JOMYJAMES** [hmrc/vat-api#799]
What is mean by this?

**Comment by cb-rfk** [comment]
It's not very intuitive I agree, but "found in 100% of your requests" means the error was found in 100% of your requests, not that the header was found in them... 😂

**Comment by JOMYJAMES** [comment]
HA HA HA... 👍

**Comment by JOMYJAMES** [comment]
•	gov-client-screens
o	errors
	Header required (found in 100% of your requests)
 I have Send this header...But showing this...No idea

**Comment by JOMYJAMES** [comment]
then Found in 40% means 60% are correct ...Am I right?
