### ISSUE TITLE
Percentage encoded header values

### ISSUE THREAD

**Issue by Oms-J** [hmrc/vat-api#801]
Which are the headers need to do percentage encoding in WEB_APP_VIA_SERVER method?

Do I need to encode the Government-Client-Timezone,Gov-Client-Browser-JS-User-Agent headers when submitting?

I have read the document but did not get much clarity. Could any one help me?

**Comment by hmrc-api-team** [comment]
Hello, we are closing this issue due to age. If you still have any persisting issues please feel free to open a new issue.
