### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by peteralarkins** [hmrc/vat-api#802]
**Note: Please read before raising an issue**. This repository's issues are reserved for **Technical** queries relating to the VAT-API Only. 
If your issue falls into any of the below categories please contact SDST at SDSTeam@hmrc.gsi.gov.uk:
- Issues relating to subscribing/registering to use the API Platform, MTD enrolment / de enrolment  / registration for VAT / BETA etc
- Issues relating to OAuth2
- Issues relating to integrating with the API Platform (setting up an application/access)
- Vendor application software questions (code examples in .NET / VB6 etc.)
- Business related questions
- Scheduled maintenance days / windows
- Onboarding 
- Performance metrics
- Questions relating to the process pre MTD

**Do not include personal or private information within your issues, this is a public repository and is available to everyone**

Personal and private information includes (but is not limited to): 
  -  Authorization Token
  
  -  Client Id
  
  -  VRN
  
When submitting an issue please try to provide the following information:

* **I'm submitting a ...**
  - [ ] Bug - API
  - [ ] Bug - Documentation
  - [ ] Improvement
  - [ ] Feature request
  - [ ] Support request

* **What is the current behaviour?**

* **What is the expected behaviour?**

* **Other information** (e.g. detailed explanation, screenshots, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Find answers to common questions [here](https://github.com/hmrc/vat-api/wiki/FAQ)

**Comment by hmrc-api-team** [comment]
Hello, we are closing this issue due to age. If you still have any persisting issues please feel free to open a new issue.
