### ISSUE TITLE
Submit VAT Return - Mandatory Field Missing Error

### ISSUE THREAD

**Issue by swdatatracks** [hmrc/vat-api#81]
Hello,

We are trying to post the following payload to "/vat/666592090/returns"

`{"periodKey":"#001","vatDueSales":20000.0,"vatDueAcquisitions":40000.0,"totalVatDue":60000.0,"vatReclaimedCurrPeriod":65000.0,"netVatDue":5000.0,"totalValueSalesExVAT":123131.0,"totalValuePurchasesExVAT":121313.0,"totalValueGoodsSuppliedExVAT":147654654.0,"totalAcquisitionsExVAT":147654654213.0,"finalised":true}`

but we are getting the following error:

`{"code":"INVALID_REQUEST","message":"Invalid request","errors":[{"code":"MANDATORY_FIELD_MISSING","message":"a mandatory field is missing","path":"/vatReclaimedCurrPeriod"},{"code":"MANDATORY_FIELD_MISSING","message":"a mandatory field is missing","path":"/periodKey"},{"code":"MANDATORY_FIELD_MISSING","message":"a mandatory field is missing","path":"/totalAcquisitionsExVAT"},{"code":"MANDATORY_FIELD_MISSING","message":"a mandatory field is missing","path":"/netVatDue"},{"code":"MANDATORY_FIELD_MISSING","message":"a mandatory field is missing","path":"/totalVatDue"},{"code":"MANDATORY_FIELD_MISSING","message":"a mandatory field is missing","path":"/totalValueGoodsSuppliedExVAT"},{"code":"MANDATORY_FIELD_MISSING","message":"a mandatory field is missing","path":"/totalValuePurchasesExVAT"},{"code":"MANDATORY_FIELD_MISSING","message":"a mandatory field is missing","path":"/finalised"},{"code":"MANDATORY_FIELD_MISSING","message":"a mandatory field is missing","path":"/totalValueSalesExVAT"},{"code":"MANDATORY_FIELD_MISSING","message":"a mandatory field is missing","path":"/vatDueAcquisitions"},{"code":"MANDATORY_FIELD_MISSING","message":"a mandatory field is missing","path":"/vatDueSales"}]}`

All the fields are available in the payload and we don't have a clue about this error. Can you please tell us where are we doing wrong?

**Comment by jacobbrownlow** [comment]
Hi

I have tried using the payload you have provided and I am getting no issues. Your error states that all fields are missing, so it looks like it's a problem with your json structure?

Come back to me if you keep having this issue

Thanks, Jacob

**Comment by swdatatracks** [comment]
@jacobbrownlow, the payload mentioned above is the actual json I am trying to submit.

**Comment by jonathanleather** [comment]
@swdatatracks 

I have managed to submit successfully in ET using the details you have provided for Submit VAT Return. 
Does what you are sending match the below?
![selection_057](https://user-images.githubusercontent.com/19834448/37469720-d9e0a170-285d-11e8-9bf1-723d84287071.png)
![selection_058](https://user-images.githubusercontent.com/19834448/37470085-a2fcb8a0-285e-11e8-9aa3-348713efa823.png)

Cheers
Jon

**Comment by swdatatracks** [comment]
@jacobbrownlow, @jonathanleather: It was my bad. I am able to submit now. Thanks for the help.
