### ISSUE TITLE
Is OAuth currently broken in the sandbox?

### ISSUE THREAD

**Issue by sonicmule** [hmrc/vat-api#82]
Just stating a new sprint today on our VAT integration and we no longer able to obtain an access token from https://test-api.service.hmrc.gov.uk/oauth/token.

We simply get 
{"error":"server_error","error_description":"An unexpected error occurred"}

So no progress can be made.

**Comment by jonathanleather** [comment]
Hi @sonicmule 
Thank you for your question, unfortunately we cannot answer this question as it relates to the wider HMRC API Plaform and is not exclusive to the MTD Self Assessment and VAT APIs.

Could you please send your question to this email address SDSTeam@hmrc.gsi.gov.uk and your question will be dealt with.

Thanks and sorry for the inconvenience.
Jon

**Comment by sri-akshat** [comment]
+1, facing same issue

**Comment by sonicmule** [comment]
I've emailed the SDSTeam

**Comment by jonathanleather** [comment]
@sonicmule @sri-akshat 
The OAuth issue appears to be resolved.

Cheers
Jon

**Comment by sonicmule** [comment]
Yes, I can confirm it's up and running now.

Many thanks
Simon
