### ISSUE TITLE
Liabilites Tax Period

### ISSUE THREAD

**Issue by markogrady** [hmrc/vat-api#83]
Should the tax period in a liability match the obligation?

Small thing, maybe irrelevant but just for consistency. Should the model be normalised? so that it is 
`{
    "taxPeriod": {
      "from": "2017-04-06",
      "to": "2017-07-06"
    },
    "type": "VAT ...",
    "originalAmount": 6000.00,
    "outstandingAmount": 100.00,
    "due": "2017-07-06"
  }`
to 
`{   
     "from": "2017-04-06",
     "to": "2017-07-06",    
    "type": "VAT ...",
    "originalAmount": 6000.00,
    "outstandingAmount": 100.00,
    "due": "2017-07-06"
  }`   

All other objects have the dates inline

**Comment by sarcas** [comment]
In a related question: if the liabilities and the obligations do match up , does it make sense to send the `periodKey` to the liability as well?

**Comment by jonathanleather** [comment]
Hi @sarcas 
We have stories on our backlog to look at the possibility of surfacing the periodKey with the liability as an enhancement in the future. Although we do not have a current ETA of when this will be available. I will however add your comments to the story.

@markogrady 
Thanks for your comments and apologies for the delay in replying to this. I'll add a story based on your comments for the team to look at.  

Cheers
Jon
