### ISSUE TITLE
C# extract authorisation code from redirect url

### ISSUE THREAD

**Issue by Grantymtd** [hmrc/vat-api#830]
How do I extract the authorisation code from the redirect URL after authority has been granted, please. I am using C#

**Comment by mPisano** [comment]
Set the return type to urn:ietf:wg:oauth:2.0:oob for you application in HMRC and on the request.
You need to use the embedded browser and look at redirect page with title "Success code".
There was also a few reg changes to make sure winforms enabled then correct browser with javascript.
Refer to my app at https://github.com/mPisano/MTDCompliance
HTH - Mike

**Comment by mPisano** [comment]
Look at the Browser sub and Keep in mind there are two methods.
Either use your own browser and copy paste the code, or use the embedded and hook the events and sniff for the success page.  Let me know how it goes... Mike

**Comment by Grantymtd** [comment]
This works. Thank you
