### ISSUE TITLE
Gateway/VRN  Mismatch

### ISSUE THREAD

**Issue by KenRandall** [hmrc/vat-api#832]
We are finding quite often when users have multiple Government Gateway ID's that they use the wrong one to authorise our software. What is the best way of checking that the VRN is associated with the Gateway ID?

**Comment by hmrc-api-team** [comment]
Hi Ken

Currently there is no way for the API team to check which VRN is being authorised prior to hitting our service. I can only recommend users login to the tax platform frontend and check their credentials before authorising the vendor application.

I would suggest contacting the Software Developers Support Team on SDSTeam@hmrc.gov.uk and making them aware that this is an issue, as we are not in control of the auth journey, and can't implement any improvements to the pages that are displayed to users.

Sorry we can't be of more help

**Comment by hmrc-api-team** [comment]
Hello, we are closing this issue due to age. If you still have any persisting issues please feel free to open a new issue.
