### ISSUE TITLE
403 when requesting tokens

### ISSUE THREAD

**Issue by JeeBeePee** [hmrc/vat-api#837]
I know this isn't for prod issues, but as usual I'm not getting a response from the SDS team.

My application is down in prod because I get a HTTP 403 when requesting tokens. Using same credentials as ever. Can't get into developer hub to see what's going on because 2FA doesn't seem to work and I'm getting no response from the team that can temporarily disable 2FA either.

Anyone else having the same issue with 403 responses to token requests?

**Comment by JeeBeePee** [comment]
One copy-pasted reply from someone on the SDS team who didn't read my original email. And nothing since.

A whole day explaining the situation to angry customers who are unable to file returns.

Apparently no way of escalating when there's nothing coming back.

Does anyone from the SDS team read this board?

**Comment by mPisano** [comment]
I do get an 403 trying to login to https://www.access.service.gov.uk/login/signin/creds
But the Developer portal @ https://developer.service.hmrc.gov.uk/developer/login  works fine.

I don't use 2FA for Application , just Authenticator app for portal, but have no current oAuth issues in Production or sandbox?

**As far as your oAuth 403, Make sure  TLS 1.2 is Enabled**

HTH - Mike

**Comment by JeeBeePee** [comment]
Thanks for responding Mike - I'm on TLS 1.2 and have been for yonks. Bit of a head-scratcher.

**Comment by mPisano** [comment]
Whats the client environment and yours?

**Comment by JeeBeePee** [comment]
It's a web app so I own the whole deployment. FWIW, Tomcat in Java on Linux using Otlu for OAuth2.

**Comment by mPisano** [comment]
Hosted on your own servers? 
Are their any clients on this platform\Server\Build that work?
How long did it work for?

**Comment by mPisano** [comment]
Also - The HMRC notes elude to 403 "codes" (ie INVALID_SCOPE)
https://developer.service.hmrc.gov.uk/api-documentation/docs/reference-guide#redirect-uris

Also From what I remember the Redirect URL during the Auth needs to Match the HMRC Portal string for the application..
Other things like TLS, possible firewall\NAT and even System Clock come to mind...

**Comment by JeeBeePee** [comment]
Really appreciate the suggestions Mike, but it's none of those. Been working now for almost two years and no changes made on my side for months.

The thing that annoys me most is that the SDS team are completely unreachable and don't seem to care. This is the last system I'll implement against an HMRC API.

**Comment by PJR-slo** [comment]
This is the last system I'll implement against an HMRC API.

+1

This is costing us a fortune :(  We are discussing withdrawing our product - let some other mug bare the ongoing costs and headaches.

**Comment by mPisano** [comment]
@PJR-slo  Are you saying you are having the same issue as JeeBeePee?

The only thing similar we had was two months ago a windows 7 user could not authenticate.  It was because of TLS and we assumed the user clicked Default in Internet Explorer options which is SSL on 7. The User insisted he never did which make me wonder if HMRC changed anything on their backend. For that user clicking enable TSL1.2 fixed it....

I would double check your server setting, and see if the client made any firewall changed that would block that traffic.
If your software saves the auth and refresh tokens I would delete them and do the full oAuth dance again.

**Comment by PJR-slo** [comment]
@mPisano No, fortunately, we are not having these issues; just a few never-ending minor niggles which we cannot get to the bottom of.

**Comment by JeeBeePee** [comment]
Finally managed to resolve the issue and thought I would post the resolution here, as it's non-obvious.

When my app fails to get a valid response from an endpoint, it retries.  For the business endpoints, it is coded to retry every 2 seconds for a total of 10 seconds.  However, for the token endpoint, no such logic is implemented - it hammers the endpoint for 30s.  I will have to look at the OAuth2 lib I'm using to see how to implement a rate limit.

After the outage on Wednesday, my application fell foul of the rate limiting protection, which per the documentation *should* cause the server to return HTTP 429 (too many requests).  The token endpoint, however, returns HTTP 403 (not authorised) when rejecting requests that breach the rate limit.

Also, per the documentation, rate limiting should only be enforced for 5 minutes after the message burst, but in this instance, it remained in force.  HMRC were unable to say for how long - might be overnight, might be 48 hours.

So, to the resolution. I changed my external IP address.

**Comment by mPisano** [comment]
Glad you're operational again!
Very strange, luckily you had more than one public ;)

**Comment by hmrc-api-team** [comment]
Hello, we are closing this issue due to age. If you still have any persisting issues please feel free to open a new issue.
