### ISSUE TITLE
VAT Collection Date from returns API

### ISSUE THREAD

**Issue by craigfrancis** [hmrc/vat-api#842]
# Feature request

**Is your feature request related to a problem? Please describe.**
With the old XML API, the `VATDeclarationResponse` would include the `CollectionDate`, so I could easily record when the VAT payment is expected to be collected.

**Describe the solution you'd like**
The [response from the `returns` API](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0#_submit-vat-return-for-period_post_accordion) includes `processingDate` (the time that the message was processed in the system), and 3 references, but no indication when the payment will be collected.

**Describe alternatives you've considered**
I might be able to get it from the [`liabilities` API](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0#_retrieve-vat-liabilities_get_accordion) (haven't tested yet, as the Sandbox Server only returns `NOT_FOUND`), and I suspect these will only be available once the VAT return has completed it's processing (I'm assuming more than a few minutes?).

**Comment by craigfrancis** [comment]
While it's not an API, this web-page seems to have the answers:

https://www.gov.uk/vat-payment-deadlines

For example, to get the "date the money will be taken from your account", via Direct Debit, for the VAT period ending on Feb 2021:

https://www.gov.uk/vat-payment-deadlines/y/2021-02-28/direct-debit

---

Alternatively, I believe the calculation is:

"1 calendar month and 7 days after the end of an accounting period"
https://www.gov.uk/vat-returns/deadlines

Then, for a Direct Debit payment, "3 working days after the payment deadline"
https://www.gov.uk/pay-vat/direct-debit

In terms of calculations that's "2021-02-28" to "2021-03-31" for the 1 calendar month, then "2021-04-07" for the 7 days, then "2021-04-12" for the 3 working days (due to the 10th/11th being a weekend).

**Comment by hmrc-api-team** [comment]
Hello, we are closing this issue due to age. If you still have any persisting issues please feel free to open a new issue.
