### ISSUE TITLE
Requesting a new refresh token - documentation error

### ISSUE THREAD

**Issue by gbs-matt** [hmrc/vat-api#848]
- [X] Documentation
- [ ] API 

**Describe the bug**
The **Request a new token** section in the [documentation](https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints) describes how the refresh token expires after 18 months.  It mentions the following:

> If the user's refresh_token has expired, calls from your application to our token endpoint will return a response with an HTTP status code of 400 (Bad Request) and an error code of invalid_request.

The code returned in this scenario is actually **invalid_grant**,  This matches the **Refresh Token is invalid** error scenario in the table just above that section.

I'd been wondering why our users couldn't figure out that they needed to re-authorise.  Turns out I was checking for invalid_request.

**Comment by hmrc-api-team** [comment]
Hi @gbs-matt, I've raised this with the team that looks after that page. Thank you for bringing this to our attention.

Many thanks

**Comment by hmrc-api-team** [comment]
Hello, we are closing this issue due to age. If you still have any persisting issues please feel free to open a new issue.
