### ISSUE TITLE
Error response inconsistency

### ISSUE THREAD

**Issue by nnotsofun** [hmrc/vat-api#85]
Hi,

We've encountered two sets of error responses:
![image](https://user-images.githubusercontent.com/17335370/37627955-0f8d0c5c-2c2b-11e8-8c65-a113724f4938.png)
(code is in the message property, statusCode provided)

![image](https://user-images.githubusercontent.com/17335370/37627963-18cf2ec6-2c2b-11e8-8283-1adc3c5c015a.png)
(code is in the code property, no statusCode provided)

Are there plans to make them consistent in the future?

Cheers,

N

**Comment by MarkAKelly** [comment]
Hi @nnotsofun - your right, they are currently inconsistent.  The first error response s from our service, and the latter is from a seperate service.  We are currently reviewing all error scenarios and responses to make sure that they are consistent not only for our API, but also consistent across the HMRC API platform.

Any changes to error responses and formats will be communicated (although I would expect them to follow the format of the second error response).

**Comment by MeliaDavies** [comment]
All breaking changes to V1 will be communicated well in advance. It's more than likely that these changes will be made if and when V2 will be released.
