### ISSUE TITLE
VAT API has been made temporarily unavailable

### ISSUE THREAD

**Issue by hmrc-api-team** [hmrc/vat-api#851]
Hi all,

A critical service downstream to us has had to be taken offline, so the decision has been made to temporarily block any incoming requests to the VAT API (to avoid us just returning `500` error messages to you guys).

We've made contact with the team who owns https://www.gov.uk/government/publications/making-tax-digital-for-vat-service-availability-and-issues/making-tax-digital-for-vat-service-availability-and-issues but until that page is updated, please refer back to this Issue for further updates.

Many thanks

**Comment by vitalcode** [comment]
Thank you, very much appreciated!

**Comment by hmrc-api-team** [comment]
VAT API has now been made available again.

**Comment by hmrc-api-team** [comment]
Hi all,

Due to problems downstream of us we've had to take the decision to temporarily block all requests to the VAT API.  We will try to keep you updated about the issues here or through the regular channels as the situation progresses.

Many thanks,
MTD API team

**Comment by hmrc-api-team** [comment]
Hi all,

The issues appear to have been resolved and the service should be back up now.

Kind regards,
MTD API Team
