### ISSUE TITLE
I can not get the response from Retrieve VAT liabilities and  Retrieve VAT payments apis. Which Date range should be pass as a query parameter?

### ISSUE THREAD

**Issue by NiraliB** [hmrc/vat-api#852]
I can not get the response from Retrieve VAT liabilities and  Retrieve VAT payments apis. Which Date range should be pass as a query parameter?

**Comment by ys00065** [comment]
Try with this date in sandbox.
Start Date: 1st April 2017
End Date: 30th June 2017

**Comment by hmrc-api-team** [comment]
Hello, we are closing this issue due to age. If you still have any persisting issues please feel free to open a new issue.
