### ISSUE TITLE
500-after test user sign in

### ISSUE THREAD

**Issue by Grantymtd** [hmrc/vat-api#854]
Lately (ie last few weeks), when I enter test users credentials in order to grant authority and to retrieve authorisation code, it takes me to this page below
![image](https://user-images.githubusercontent.com/75227407/116446656-139ef780-a84f-11eb-8910-5b7a4ad9b3fa.png)

Fiddler shows this to be a 500 error

I've emailed the online support team, and also SDSTeam, but none have responded to my query. Has any one encountered this issues? Or is there any one that can help?

This is happening in the test environment. Before then this was working & I've not made any changes my program. Thank you

**Comment by kdb119** [comment]
Yes, exactly the same issue.  For me it's been happening since Tuesday the 18th May.  I've also received no response.

**Comment by nmicoud** [comment]
Hi,
Same issue here ; we manage to got an answer which was to recreate a new user :-/
We did it and now we can have access.
Hope it helps

**Comment by kdb119** [comment]
Many thanks, that really does help.  I'll give that a try later.

**Comment by hmrc-api-team** [comment]
Hello, we are closing this issue due to age. If you still have any persisting issues please feel free to open a new issue.
