### ISSUE TITLE
01-JUN-2021 - Organisations/vat' API is currently unavailable

### ISSUE THREAD

**Issue by alanfinnharris** [hmrc/vat-api#857]
Hi,
Currently getting this response when we try to 'Read VAT' from the MTD for VAT API. Is the service down?

l_err_msg[503] - Service Unavailable
l_response{ "code": "SERVER_ERROR", "message": "The 'organisations/vat' API is currently unavailable" }

Thanks,
Alan

**Comment by hmrc-api-team** [comment]
Hi @alanfinnharris,

We've had to take the API down this morning due to issues with one of our dependent downstream services. Updates should be given in #851 once we have them.

Kind regards,
MTD API Team

**Comment by hmrc-api-team** [comment]
The issues appear to have been resolved and the service should be back up now.

Kind regards,
MTD API Team
