### ISSUE TITLE
Sandbox Down?

### ISSUE THREAD

**Issue by AndyYouens** [hmrc/vat-api#859]
getting 

Sorry, we’re experiencing technical difficulties
Please try again in a few minutes.

Is this page not working properly? (opens in new tab)

**Comment by hmrc-api-team** [comment]
Hi Andy,

Is this problem occurring whilst trying to access the documentation, or are you attempting to hit the API itself?

Kind regards,
MTD API Team

**Comment by AndyYouens** [comment]
trying to test our security headers via the API

**Comment by AndyYouens** [comment]
error from https://test-www.tax.service.gov.uk/api-test-login/sign-in

**Comment by AndyYouens** [comment]
I tried again with another users details & it worked fine.

That is a misleading error page to show the user ID is invalid. :-(
