### ISSUE TITLE
ID on payment

### ISSUE THREAD

**Issue by markogrady** [hmrc/vat-api#86]
Could there be an if added to the payment? 

I want to be able to reconcile a payment against vat returns and if there were two payments on the same day then it would be hard to say which one is which. In the example where the organisation is late paying and makes two payments at once.

Do you have any link from the payment to the vat return or do organisation sometimes make one payment for multiple returns?

**Comment by jonathanleather** [comment]
Hi @markogrady 
It is possible for a company to make a large payment that gets split towards multiple liabilities and this will be extended in the future to liabilities across regimes. 

Unfortunately it is not currently possible to link the payment to a specific VAT return. I have however  passed your comments onto the relevant people, as this is something we may consider as a future enhancement.

Cheers
Jon

**Comment by markogrady** [comment]
But could there still be an id on the payment incase there are 2 in a day and I can remember whether I have processed it

**Comment by markogrady** [comment]
Sorry I added two questions

**Comment by Renu84** [comment]
Hi All,

@MarkAKelly has this been implemented yet onto VAT API?

Many Thanks,

**Comment by hmrc-api-team** [comment]
Issue Closed due to age. If this is still relevant feel free to open a new one.
