### ISSUE TITLE
Fraud Prevention Header Support group

### ISSUE THREAD

**Issue by Mark-Mason2021** [hmrc/vat-api#861]
Is there a MTD developer support group?

I've noticed a lot of questions about MTD Fraud Headers which can't be answered here. Some of which can't be answered at all (IMHO). Does anyone no of a support group or forum where developers can discuss issues and possibly offer solutions?

**Comment by hmrc-api-team** [comment]
Hello, #565 is designed to allow for discussion around Fraud Headers that don't require HMRC support. Please feel free to continue any discussion there.
