### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by alanfinnharris** [hmrc/vat-api#864]
Hi, When we attempt to submit declarations via the API today we are getting the 503 Service Unavailable error, but the platform status page says the service is operational, anybody experiencing the same issue?
Thanks

**Comment by hmrc-api-team** [comment]
Hello alanfinnharris, I'm afraid we don't have the data available for this anymore, if you still are experiencing issues feel free to raise it with SDST and provide a detailed rundown of your issue.
