### ISSUE TITLE
Negative Box 5 - Undefined Payment Indicator in Production 

### ISSUE THREAD

**Issue by AndyYouens** [hmrc/vat-api#868]
if the amount due to HMRC in box 5 is negative, in the sandbox,a submission will return the payment indicator as Bank, where as in production the payment indicator is not return (therefore undefined)

can you get these environments to work in the same way, to give us developers a chance??

#690 - not resolved - Please fix

**Comment by AndyYouens** [comment]
Can this be looked at instead of 'closing due to age'!

**Comment by Nboaram** [comment]
Hey Andy, thanks for re-opening the issue to let us know it's still current. 

The value in netVatDue (box 5) must be positive. It works the same way as the old paper forms. It is the difference between **totalVatDue** (box 3) and **vatReclaimedCurrPeriod** (box 4).

If the figure in **totalVatDue** is more than the figure in **vatReclaimedCurrPeriod**, the difference is the amount you must pay. If the figure in **totalVatDue** is less than the figure in **vatReclaimedCurrPeriod** we'll credit your account and repay the balance, subject to any enquiries we may need to make.

Payment indicator is randomised in Sandbox, the value changes between `DD` and `BANK`

**Comment by hmrc-api-team** [comment]
Hey Andy, thanks for re-opening the issue to let us know it's still current. 

The value in netVatDue (box 5) must be positive. It works the same way as the old paper forms. It is the difference between **totalVatDue** (box 3) and **vatReclaimedCurrPeriod** (box 4).

If the figure in **totalVatDue** is more than the figure in **vatReclaimedCurrPeriod**, the difference is the amount you must pay. If the figure in **totalVatDue** is less than the figure in **vatReclaimedCurrPeriod** we'll credit your account and repay the balance, subject to any enquiries we may need to make.

Payment indicator is randomised in Sandbox, the value changes between `DD` and `BANK`

**Comment by AndyYouens** [comment]
Thanks for the reply, and yes I understand the logic and have no problem with that.

My problem is if the amount due to HMRC in box 5 is negative, in the sandbox,a submission will return the payment indicator as Bank or DD , where as in production the payment indicator is not returned (therefore undefined).  Can it return NULL?

With it not being returned in production is not the same as the sandbox, can they be synced so they both are consistant?

**Comment by hmrc-api-team** [comment]
Hi Andy

The description of the payment indicator is 
> Is DD if the netVatDue value is a debit and HMRC holds a Direct Debit Instruction for the client. Is BANK if the netVatDue value is a credit and HMRC holds the client’s bank data. Otherwise not present.

As an optional field, we would normally opt to always return it in the Sandbox to enable testing, as we couldn't cater for every scenario:
1. debit where HRMC hold direct debit instructions = `DD`
2. debit where HMRC doesn't = Not returned
3. credit where HMRC holds client bank data = `BANK`
4. credit where HMRC doesn't = Not returned

Additionally our stubbed backend used Sandbox is not currently able to calculate whether box 5 is a debit or credit.

I'll pass on the suggestion to enhance this to the MTD team. However, I wouldn't expect we'd touch it given the Sandbox response is a correct example of a Production response, and the Sandbox environment is not intended to provide a like-for-like Production experience.

Thanks

**Comment by hmrc-api-team** [comment]
Our team considers this issue resolved. Please use git to raise any new issues.
