### ISSUE TITLE
VAT Collection Date from returns API

### ISSUE THREAD

**Issue by craigfrancis** [hmrc/vat-api#869]
# Feature Request

**Note:** This is repeating the old, and now closed [Issue 842](https://github.com/hmrc/vat-api/issues/842).

**Is your feature request related to a problem? Please describe.**
With the old XML API, the `VATDeclarationResponse` would include the `CollectionDate`, so I could easily record when the VAT payment was going to be collected.

**Describe the solution you'd like**
The [new `returns` API](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0#Submit%20VAT%20return%20for%20period) should also note when the payment will be collected. At the moment this API only returns the `processingDate` (i.e. now), and 3 references.

**Describe alternatives you've considered**
Maybe a different API could return this date, e.g. the [`liabilities` API](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0#Retrieve%20VAT%20liabilities).

---

# Work Around

While it's not an API, the [VAT Payments Deadlines](https://www.gov.uk/vat-payment-deadlines) web-page knows the "date the money will be taken from your account"; e.g. via Direct Debit, for the VAT period ending on Feb 2021:
https://www.gov.uk/vat-payment-deadlines/y/2021-02-28/direct-debit

I believe the calculation is:

"1 calendar month and 7 days after the end of an accounting period"
https://www.gov.uk/vat-returns/deadlines

Then, for a Direct Debit payment, "3 working days after the payment deadline"
https://www.gov.uk/pay-vat/direct-debit

e.g. Starting with "2021-02-28", you go to "2021-03-31" for the 1 calendar month, then "2021-04-07" for the 7 days, then "2021-04-12" for the 3 working days (due to the 10th/11th being a weekend). Keep in mind you will also need to factor in [bank holidays](https://www.gov.uk/bank-holidays) (also available in [JSON format](https://www.gov.uk/bank-holidays.json)).

**Comment by hmrc-api-team** [comment]
Thank you for your feedback, we will pass it on.

**Comment by hmrc-api-team** [comment]
Our team considers this issue resolved. Please use git to raise any new issues.

**Comment by craigfrancis** [comment]
How do they consider this issue resolved?

Do they expect everyone to dig though the documentation to find this information, and hope that every implementation does not make a mistake with these date calculations?

**Comment by hmrc-api-team** [comment]
Unfortunately, this API acts as an external interface through which users may interact with downstream government tax services. As such we are unable to surface any information other than that which we receive from those services, which does not currently include the data which you are requesting. We are able to relay your feedback to those responsible for the data which is surfaced back to us, but the decision to enact those changes is not within our control.

**Comment by craigfrancis** [comment]
Please relay this feedback.

The old XML API did provide the `CollectionDate`, which is important from an accounting point of view (and only HMRC can reliably provide this).
