### ISSUE TITLE
Revoking authority and refreshing tokens

### ISSUE THREAD

**Issue by nnotsofun** [hmrc/vat-api#87]
Hi,

Im working out what happens when we revoke authority. When I revoke authority and try to refresh my tokens (on /oauth/token) I get this response:

```js
{
   "error": "invalid_grant",
   "error_description": "refresh_token is invalid"
}
```

In the documentation it's listed that I should get back an "invalid_request":
![image](https://user-images.githubusercontent.com/17335370/38012251-6a4ca652-32ac-11e8-8391-6d1ae4924c25.png)

Is that an issue or should we handle both scenarios?

Thanks!

Cheers,

N

**Comment by narendravijayarao** [comment]
Hi,

Unfortunately we cannot answer this as it is related to the user registration and authorisation process. This channel is only of specific questions relating to the MTD VAT APIs.

Could you please send your question to this email address SDSTeam@hmrc.gsi.gov.uk and your question will be dealt with.

Thanks and sorry for the inconvenience
Narendra
