### ISSUE TITLE
404 Error "code": "MATCHING_RESOURCE_NOT_FOUND"

### ISSUE THREAD

**Issue by h-edwards** [hmrc/vat-api#872]
Hi, I'm trying to POST test VAT data to the "/organisations/vat/{vrn}/returns" endpoint. I'm able to grant authorisation using a test organisation login, however after doing so the code I've created keeps returning: "code": "MATCHING_RESOURCE_NOT_FOUND" Anyone have an idea why? I've tried to adjust the headers but I keep getting back the same message. I'm wondering if HMRC enables us to POST data to a test user or not?

**Comment by hmrc-api-team** [comment]
Yes. This should work. 
Can you share any more details of the url, request and response headers and payloads?

**Comment by h-edwards** [comment]
Awesome! Here's the code I have so far:

var CLIENT_ID = 'thQadHpQDi52iVxxxxxxxxxxxxxx';
var CLIENT_SECRET = '702b5465-4a2b-xxxx-xxxx-xxxxxxxx';


// Authorizes and makes a request to the HMRC API //

function run() {
//getService().reset();
  var service = getService();
  if (service.hasAccess()) {
    var url = 'https://test-api.service.hmrc.gov.uk/organisations/vat/766434212/returns';
    var response = UrlFetchApp.fetch(url, {
      headers: {
        Accept : 'application/vnd.hmrc.1.0+json',
        Authorization: 'Bearer ' + service.getAccessToken(),
        ContentType: 'application/json',
        Scope: 'write:vat'
      }});
    var result = JSON.parse(response.getContentText());
    Logger.log(JSON.stringify(result, null, 2));

// POST VAT Test Data //

    var vatData = {
      'grant_type': 'client_credentials',
      'client_secret' : CLIENT_SECRET,
      'client_id': CLIENT_ID,
      'periodKey': '18A2',
      'vatDueSales': 105.50,
      'vatDueAcquisitions': -100.45,
      'totalVatDue': 5.05,
      'vatReclaimedCurrPeriod': 105.15,
      'netVatDue': 100.10,
      'totalValueSalesExVAT': 300,
      'totalValuePurchasesExVAT': 300,
      'totalValueGoodsSuppliedExVAT': 3000,
      'totalAcquisitionsExVAT': 3000,
      'finalised': true
    };

    var options = {
      'Accept' : 'application/vnd.hmrc.1.0+json',
      'Authorization': 'Bearer ' + service.getAccessToken(),
      'method' : 'POST',
      'contentType': 'application/json',
      'payload' : vatData,
      'gov-test-scenario': 'QUARTERLY_NONE_MET'
    };

UrlFetchApp.fetch('https://test-api.service.hmrc.gov.uk/organisations/vat/766434212/returns', options);
  } else {
    var authorizationUrl = service.getAuthorizationUrl();
    Logger.log('%s',authorizationUrl);
  }
}

// Configure the service //

function getService() {
  return OAuth2.createService('oAuth Testing')
    // Set the endpoint URLs.
      .setAuthorizationBaseUrl('https://test-api.service.hmrc.gov.uk/oauth/authorize')
      .setTokenUrl('https://test-api.service.hmrc.gov.uk/oauth/token')
      .setClientId(CLIENT_ID)
      .setClientSecret(CLIENT_SECRET)
      .setCallbackFunction('authCallback')
      .setPropertyStore(PropertiesService.getUserProperties())
      .setScope('write:vat')
}


// Auth Callback //

function authCallback(request) {
  var service = getService();
  var authorized = service.handleCallback(request);
  if (authorized) {
    return HtmlService.createHtmlOutput('Success!');
  } else {
    return HtmlService.createHtmlOutput('Denied.');
  }
}


// Access the Redirect URI //

function logRedirectUri() {
  Logger.log(OAuth2.getRedirectUri());
}

**Comment by hmrc-api-team** [comment]
Hello @h-edwards,

Are you able to tell me what `message` the error is being returned with? If it matches `A resource with the name in the request can not be found in the API` then it is likely that our service cannot recognise the request which you are making. This usually happens when an incorrect HTTP method is used, or when the request uri differs from what is expected.

Kind regards,
MTD-API Team

**Comment by h-edwards** [comment]
Hi @hmrc-api-team,

Yes the code returns this message:

Exception: Request failed for https://test-api.service.hmrc.gov.uk returned code 404. Truncated server response: {"code": "MATCHING_RESOURCE_NOT_FOUND", "message": "A resource with the name in the request can not be found in the API"} (use muteHttpExceptions option to examine full response)

**Comment by hmrc-api-team** [comment]
From looking at our logs I can see that your requests are being sent to us with a HTTP method of GET instead of POST. If you are able to change the HTTP method of your requests to POST you should hopefully stop getting this error.

Kind regards,
MTD-API Team

**Comment by h-edwards** [comment]
So simple, thanks for your help @hmrc-api-team ! I'll look into that :)

**Comment by h-edwards** [comment]
Sorry I have one more question @hmrc-api-team, is Fraud prevention required with this API?
