### ISSUE TITLE
Production Authorising Software

### ISSUE THREAD

**Issue by KenRandall** [hmrc/vat-api#876]
Hi,

We are getting a success message back and a an authorisation code but when try to convert it to an access token and refresh token we are getting the error back Requests to this endpoint cannot be made with data in query parameters."

We have not changed our software and this was always working before. As far as I am aware it has only started happening after the weekend.

Thanks,

Ken Randall

**Comment by nickgabb** [comment]
I have just wasted 2 hours trying to resolve getting a New token using Delphi 11
Finally reverted to Delphi 10.2 and problem gone FOR NOW
"Requests to this endpoint cannot be made with data in query parameters."
Has this been resolved? 
Or do I carry on sharpening the razor blade for my wrists!!!

**Comment by KenRandall** [comment]
There is a bug in Delphi 11 to do with HTTP Requests. I had a quick look on the quality portal but can't seem to find it.

**Comment by nickgabb** [comment]
Nor can I !


Regards

Nick

***@***.***
