### ISSUE TITLE
VAT API is currently unavailable

### ISSUE THREAD

**Issue by ddaddy** [hmrc/vat-api#884]
The VAT MTD API is returning Status `503`: `The 'organisations/vat' API is currently unavailable` all this morning.

> { "code": "SERVER_ERROR", "message": "The 'organisations/vat' API is currently unavailable" }

I know there was half an hour of maintenance last night which shows as being completed, but maybe they forgot to switch something back on?

The platform status page is as useless as a chocolate teapot as it reports all systems are normal (And has done in the past when there have been server issues).

<img width="893" alt="Screenshot 2021-12-12 at 11 47 54" src="https://user-images.githubusercontent.com/1425808/145710918-12aa0406-e996-4b4a-9223-0021ff48ce4a.png">

Maybe someone will get a notification for this issue and flip the switch?

**Comment by KenRandall** [comment]
We were getting the same yesterday but ok this morning.

**Comment by KenRandall** [comment]
Something needs to be seriously addressed with HMRC support at weekends!

**Comment by DDCTLS-DEV-TEAM** [comment]
Good Morning,

Thank you for your comments. We, unfortunately, had a scenario with one of the backend services over the weekend that has continued onto today, where we needed to render the API unavailable. 

The API currently is up and running however the backend services are still being looked at.

We apologies for any inconvenience caused.

**Comment by ddaddy** [comment]
Why would the service status report that everything is Operational when it isn't?
It results in users of our app thinking it's a problem with us and blaming us.

Surely your service status should run it's own unit tests at regular intervals to monitor itself?

**Comment by DDCTLS-DEV-TEAM** [comment]
Hello, 

Unfortunately, we are not the team that deals with the status of the operational flag and is actually controlled by an external team. We can only react to what the service is doing. But the status page is directly controlled by the SDSTeam here is their email SDSTeam@hmrc.gov.uk. We don't have access to changing that flag, unfortunately. 

Kind Regards
