### ISSUE TITLE
error with https://api.service.hmrc.gov.uk/organisations/vat/{vatnum}/returns

### ISSUE THREAD

**Issue by tianfengLiang** [hmrc/vat-api#885]
we use this api https://api.service.hmrc.gov.uk/organisations/vat/{vatnum}/returns with postman
{
  "periodKey": "21B3",
  "vatDueSales": -97.84,
  "vatDueAcquisitions": 0.00,
  "totalVatDue": -97.84,
  "vatReclaimedCurrPeriod": 0.00,
  "netVatDue": 97.84,
  "totalValueSalesExVAT": 185.00,
  "totalValuePurchasesExVAT": 0.00,
  "totalValueGoodsSuppliedExVAT": 0.00,
  "totalAcquisitionsExVAT": 0.00,
  "finalised": true
}
but it return 
{
            "code": "VAT_TOTAL_VALUE",
            "message": "totalVatDue should be equal to vatDueSales + vatDueAcquisitions",
            "path": "/totalVatDue"
}
-97.84 should be equal to -97.84+ 0.00?

**Comment by DDCTLS-DEV-TEAM** [comment]
Hello there, sorry for the delayed response. We have looked into the code and ran unit tests locally and  on Ext test Environment using POSTman. With the data you provided, it absolutely works fine and no error is reported. We are unable to recreate the defect with the data you provided. Please can you verify once again and let us know if the data you provided is indeed the same one which is returning the error code you got back.
If not please provide the data so we can assist you further. Thank you in advance. Live Services Team

**Comment by tianfengLiang** [comment]
It is normal in the test environment, but it is wrong in the formal environment，I don't know why. That's why I asked you. thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hmrc/vat-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月31日(星期一) 晚上7:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hmrc/vat-api] error with https://api.service.hmrc.gov.uk/organisations/vat/{vatnum}/returns (Issue #885)





 
Hello there, sorry for the delayed response. We have looked into the code and ran unit tests locally and&nbsp; on Ext test Environment using POSTman. With the data you provided, it absolutely works fine and no error is reported. We are unable to recreate the defect with the data you provided. Please can you verify once again and let us know if the data you provided is indeed the same one which is returning the error code you got back.
 If not please provide the data so we can assist you further. Thank you in advance. Live Services Team
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DDCTLS-DEV-TEAM** [comment]
I believe you are referring to External test ENV when you said test environment? Also formal environment meant local one?

**Comment by tianfengLiang** [comment]
I say formal environment meat&nbsp;https://api.service.hmrc.gov.uk/organisations/vat/ ;&nbsp;
the test ENV mean&nbsp;https://test-api.service.hmrc.gov.uk/organisations/vat/；
the problem in&nbsp;formal environment；


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hmrc/vat-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月31日(星期一) 晚上7:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hmrc/vat-api] error with https://api.service.hmrc.gov.uk/organisations/vat/{vatnum}/returns (Issue #885)





 
I believe you are referring to External test ENV when you said test environment? Also formal environment meant local one?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DDCTLS-DEV-TEAM** [comment]
This is interesting. Can you please send your VRN to this email SDSTeam@hmrc.gov.uk with a link to this github issue? This is a secure way for us to get your VRN and to check our monitoring systems outside please. Thank you in advance

**Comment by tianfengLiang** [comment]
thinks，It has been sent. Please check it

**Comment by DDCTLS-DEV-TEAM** [comment]
Thanks. We will get back you to you ASAP.

**Comment by DDCTLS-DEV-TEAM** [comment]
Good News, we have deployed some Auditing stuff into VAT API backend service. We can now see what the user is actually trying to do. Please can you submit the same request for the user in question and let us know once done. Thanks in advance

**Comment by tianfengLiang** [comment]
We can't try again for some reasons. When we encounter problems next time, we will give feedback. thank you


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hmrc/vat-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月2日(星期三) 晚上11:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hmrc/vat-api] error with https://api.service.hmrc.gov.uk/organisations/vat/{vatnum}/returns (Issue #885)





 
Good News, we have deployed some Auditing stuff into VAT API backend service. We can now see what the user is actually trying to do. Please can you submit the same request for the user in question and let us know once done. Thanks in advance
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DDCTLS-DEV-TEAM** [comment]
Thank you for your time. We will close the issue. Please raise another issue if it persists and we can help you. 

Kind regards

**Comment by tianfengLiang** [comment]
We have encountered other issues again. Is anyone still responding here?
