### ISSUE TITLE
Incorrect response, client_id is required when requesting authorisation code

### ISSUE THREAD

**Issue by henriwoodcock** [hmrc/vat-api#894]
When requesting the authorisation code using the url of format:

https://test-www.tax.service.gov.uk/oauth/authorize?response_type=code&client_id=[my-client-id]&scope=hello&redirect_uri=http%3A%2F%2localhost%3A3000%2Fsuccess

I keep getting the error response
```
{"error":"invalid_request","error_description":"client_id is required"}
```

I know client_id is present as I can see it in the url, but this response makes it hard to debug as it is incorrect and does not inform me what is actually going wrong.

**Comment by DDCTLS-DEV-TEAM** [comment]
It looks like the error is being produced by the **Oauth** service. The Oauth service contacts third-party-application which tries to match the correct credentials. It needs client_id , client_secret and totp code. Third-party-application sends error back to Oauth service when the creds fail. But Oauth sends back “client_id is required” to the user as error description. This does not mean that the client_id is absent from the request sent by the user. It means that the user provided credentials are wrong or not matched. You need to refresh the user tokens - client_id, client_secret.
Please feel free to explore on this:
https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0#testing
