### ISSUE TITLE
Missing Authentication - HMRC error code 401

### ISSUE THREAD

**Issue by adrianb1612** [hmrc/vat-api#913]
Using Microsoft Axapta 2012 R3 for VAT MTD.  For Q2 2022 - 01/04/2022-30/06/2022 I am unable to create an obligation in the AX 2012 system and therefore not submit my VAT return for the quarter which is now overdue.  Despite numerous attempts to re-authorise and obtain new access codes to update the access token, we always receive error code 401 - Missing credentials - authentication information is not provided.  This appears to relate to an invalid client secret code.

We have tried using 2 different client secret codes provided by Microsoft from their support website - 1 file dated 2019 and the other 2021, neither are working.  Original file attached.  Company VAT number 205503996.

**Comment by DDCTLS-DEV-TEAM** [comment]
hello @adrianb1612 

Thank you for reaching out to us. If you could can you please delete the file from the issue you have raised as it has your client id etc and anyone can access these issues? 

If you could please follow this testing documentation that should give you everything you need to test the API https://developer.service.hmrc.gov.uk/api-documentation/docs/testing 

If you still struggle to get authentication please reach out to the SDS team on this email: SDSTeam@hmrc.gov.uk
they can make sure your access is all set up etc. 

Thank you and if you need any more help please reach out.
