### ISSUE TITLE
VAT Penalty API - Discrepancy in API JSON names or keys

### ISSUE THREAD

**Issue by dev-efr** [hmrc/vat-api#967]
# Bug report

- [ ] Documentation
- [ ] API 

**Describe the bug**
There are two discrepancies observed as below :

**Responses**
1. Retrieve VAT penalties : Partial JSON from API Documentation pasted 
{
    "totalisations": {
        "lateSubmissionPenaltyTotalValue": 400,
        "penalisedPrincipalTotal": 10000,
        "latePaymentPenaltyPostedTotal": 425.21,
        "latePaymentPenaltyEstimateTotal": 30.68
    },
    "lateSubmissionPenalty": {
        "summary": {
            "**activePenaltyPoints**": 4,

Actual JSON response from the Dev Hub API call
{
  "totalisations" : {
    "lateSubmissionPenaltyTotalValue" : 0,
    "penalisedPrincipalTotal" : 7014.02,
    "latePaymentPenaltyPostedTotal" : 805.21,
    "latePaymentPenaltyEstimateTotal" : 4762.36
  },
  "lateSubmissionPenalty" : {
    "summary" : {
      "**activePoints**" : 1,

----------------------------------------------------------------------------------
2. Retrieve financial details : Partial JSON from API Documentation pasted
 {
  "**totalisations**": {
    "totalOverdue": 123.45,
    "totalNotYetDue": 12.34,   

Actual JSON response from the Dev Hub API call
{
  "**totalisation**" : {
    "totalOverdue" : 123.45,
    "totalNotYetDue" : 12.34,

**Comment by DDCTLS-DEV-TEAM** [comment]
Hi dev-efr,
We are looking into this for you now.

**Comment by DDCTLS-DEV-TEAM** [comment]
Hi dev-efr,
This issue has now been resolved
